local soundBank = {
	enemyNames = {
		'Zallay Subaddamael',
		'Assantus Hansar',
		'Tunipy Shamirbasour',
		'Emul-Ran',
		'Kashtes Ilabael',
		'Sakin Sanammasour',
		'Esar-Don Dunsamsi',
		'Hairan Mannanalit',
		'Assallit Assunbahanammu',
		'Tubilalk Mirathrernenum',
		'Yan-Ahhe Darirnaddunumm',
		'Kammu',
		'Sen',
		'Urshamusa Rapli',
		'Zallit',
		'Addammus',
		'Ulabael',
		'Assamma-Idan',
		'Dutadalk',
		'Yenammu',
		'Kausi',
		'Lanabi',
		'Mabarrabael',
		'Mamaea',
		'Mausur',
		'Nummu',
		'Sinnammu Mirpal',
		'Assaba-Bentus',
		'Hairan',
		'Hirarend',
		'Kummu',
		'Kushishi',
		'Tinti',
		'Addut-Lamanu',
		'Ainab',
		'Ahaz',
		'Ulath-Pal',
		'Ashu-Ahhe',
		'Assemmus',
		'Zebba',
		'Han-Ammu',
		'Yantus',
		'Massarapal',
		'Ulibabi',
		'Ranabi',
		'Salattanat',
		'Manirai',
		'Hainab',
		'Shabinbael',
		'Shallath-Piremus',
		'Tussurradad',
		'Ahasour',
		'Senipu',
		'Sul-Matuul',
		'Kurapli',
		'Maeli',
		'Sakiran',
		'Yen',
		'Ninirrasour',
		'Shara',
		'Shimsun',
		'Nibani Maesa',
		'Zabamund',
		'Zanummu',
		'Sakulerib',
		'Zaba',
		'Ababael Timsar-Dadisun',
		'Ashibaal',
		'Kaushad',
		'Ashur-Dan',
		'Minassour',
		'Patababi',
		'Tussi',
		'Sonummu Zabamat',
		'Shanat Kaushminipu',
		'Tibdan Shalarnetus',
		'Zallay Subaddamael',
		'Abassel Asserbassalit',
		'Kund Assarnibani',
		'Rawia Ashirbibi',
		'Kausha Mantashpi',
		'Manu Zainab',
		'Nummu Assudiraplit',
		'Odaishah Yasalmibaal',
		'Yapal Esatliballit',
		'Shara Atinsabia',
		'Zainat Ahalkalun',
		'Adibael Hainnabibi',
		'Assurdan Serdimapal',
		'Ibanammu Assutladainab',
		'Kanit Niladon',
		'Yanit Sehabani',
		'Maesat Shinirbael',
		'Missun Hainterari',
		'Samsi Ulannanit',
		'Manabi Kummimmidan',
		'Sargon Santumatus',
		'Teshmus Assebiriddan',
		'Yahaz Ashurnasaddas',
		'Adairan Lalansour',
		'Hemus Zelma-Alit',
		'Manat Shimmabadas',
		'Rasamsi Esurarnat',
		'Zalit Salkatanat',
		'Seba Anurnudai',
		'Tis Abalkala',
		'Zelay Sobbinisun',
		'Anit Eramarellaku',
		'Minisun Ulirbabi',
		'Zalabelk Saladnius',
		'Mamaea Ashun-Idantus',
		'Mimanu Zeba-Adad',
		'Zennammu',
		'Mal Mibishanit',
		'Mi-Ilu Massitisun',
		'Subenend Urshummarnamus',
		'Kitbael Assurnumanit',
		'Nind Dudnebisun',
		'Patus Assumanallit'
	},
	combatTracks = {
		{
			path = 'Music/MS/combat/Ashlander/combat1.mp3',
			length = 78
		},
		{
			path = 'Music/MS/combat/Ashlander/combat2.mp3',
			length = 64
		},
		{
			path = 'Music/MS/combat/Ashlander/combat3.mp3',
			length = 79
		}
	}
}

return soundBank
