local tooltipsComplete = include("Tooltips Complete.interop")
local tooltipData = {
	{ id = "ab_w_adamrapier", description = "Thrusting swords most common to High Rock and the Summerset Isles, Adamantium rapiers are fashioned from what little ore may be uncovered in the east. Favored primarily by the Altmer for its enchantability, Adamantium has been a material utilized for untold millenia by elves, and Dunmer are of no exception.", itemType = "weapon" },
	{ id = "ab_w_bonearrow", description = "Simple arrow fashioned from animal bone, an easily-crafted field weapon for adventurers and hunters, and cheap for those on a budget.", itemType = "weapon" },
	{ id = "ab_w_bonearrowfla", description = "Simple arrow fashioned from animal bone, an easily-crafted field weapon for adventurers and hunters, and cheap for those on a budget.", itemType = "weapon" },
	{ id = "ab_w_bonebolt", description = "Simple bolt fashioned from animal bone, an easily-crafted field weapon for adventurers and hunters, and cheap for those on a budget.", itemType = "weapon" },
	{ id = "ab_w_chitinhalberd", description = "Created from laminated carapace, Chitin halberds tend to be more flexible than average and typically have their edges serrated to cause more severe damage.", itemType = "weapon" },
	{ id = "ab_w_chitinmace", description = "Created from laminated carapace, Chitin maces tend to be more flexible than average and typically have their edges serrated to cause more severe damage.", itemType = "weapon" },	
	{ id = "ab_w_chitintomahawk", description = "Created from laminated carapace, Chitin throwing clubs tend to be more flexible than average and typically have their edges serrated to cause more severe damage.", itemType = "weapon" },
	{ id = "ab_w_chitintomahawkfire", description = "Created from laminated carapace, Chitin throwing clubs tend to be more flexible than average and typically have their edges serrated to cause more severe damage.", itemType = "weapon" },
	{ id = "ab_w_daedrichalberd", description = "Among the most rare and valuable treasures of Tamriel, Daedric halberds are crafted from raw ebony refined in the ritual binding of a Daedric vestige to its shape, the weapon's power being directly enhanced by the prolonged suffering and rage of the Daedroth now dwelling within.", itemType = "weapon" },
	{ id = "ab_w_daedricknife", description = "Among the most rare and valuable treasures of Tamriel, Daedric throwing knives are crafted from raw ebony refined in the ritual binding of a Daedric vestige to its shape, the weapon's power being directly enhanced by the prolonged suffering and rage of the Daedroth now dwelling within.", itemType = "weapon" },
	{ id = "ab_w_daedricrapier", description = "Thrusting swords most common to High Rock and the Summerset Isles, Daedric rapiers are crafted from raw ebony refined in the ritual binding of a Daedric vestige to its shape, the piece becoming a vessel for whatever unlucky Daedroth now inhabits the armor and enhances its properties.", itemType = "weapon" },
	{ id = "ab_w_daedrictomahawk", description = "Among the most rare and valuable treasures of Tamriel, Daedric throwing axes are crafted from raw ebony refined in the ritual binding of a Daedric vestige to its shape, the weapon's power being directly enhanced by the prolonged suffering and rage of the Daedroth now dwelling within.", itemType = "weapon" },
	{ id = "ab_w_daelongpear", description = "Among the most rare and valuable treasures of Tamriel, Daedric long spears are crafted from raw ebony refined in the ritual binding of a Daedric vestige to its shape, the weapon's power being directly enhanced by the prolonged suffering and rage of the Daedroth now dwelling within.", itemType = "weapon" },
	{ id = "ab_w_dreughbattleaxe", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create edged weapons like the Dreugh battle axe.", itemType = "weapon" },
	{ id = "ab_w_dreughclaymore", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create edged weapons like the Dreugh claymore.", itemType = "weapon" },
	{ id = "ab_w_dreughdagger", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create piercing weapons like the Dreugh dagger.", itemType = "weapon" },
	{ id = "ab_w_dreughgreatmace", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create blunt weapons like the Dreugh greatmace.", itemType = "weapon" },
	{ id = "ab_w_dreughhalberd", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create edged weapons like the Dreugh halberd.", itemType = "weapon" },
	{ id = "ab_w_dreughlongsword", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create edged weapons like the Dreugh longsword.", itemType = "weapon" },
	{ id = "ab_w_dreughmace", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create blunt weapons like the Dreugh mace.", itemType = "weapon" },
	{ id = "ab_w_dreughshortsword", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create edged weapons like the Dreugh shortsword.", itemType = "weapon" },
	{ id = "ab_w_dreughspear", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create piercing weapons like the Dreugh spear.", itemType = "weapon" },
	{ id = "ab_w_dreughwaraxe", description = "While quite effective in its application to armor, Dreugh carapace is difficult to manipulate and thus unsuitable for use in much else. However, the wax of Dreugh shells may be heated, molded into shape, then cooled in order to create edged weapons like the Dreugh war axe.", itemType = "weapon" },
	{ id = "ab_w_dwrvarbalest", description = "Their trade restricted by the Empire as archaeological artifacts, Dwemer arbalests are an advanced variation of crossbow fashioned from an ancient Dwarven alloy resistant to corrosion and of particularly great weight.", itemType = "weapon" },
	{ id = "ab_w_dwrv_longspear", description = "Their trade restricted by the Empire as archaeological artifacts, Dwemer long spears are fashioned from an ancient Dwarven alloy resistant to corrosion and blunting.", itemType = "weapon" },
	{ id = "ab_w_ebonybolt", description = "As powerful as they are valuable, Ebony bolts are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
	{ id = "ab_w_ebonybolt_bdeath", description = "As powerful as they are valuable, Ebony bolts are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
	{ id = "ab_w_ebonybolt_rdeath", description = "As powerful as they are valuable, Ebony bolts are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
	{ id = "ab_w_ebonybolt_viper", description = "As powerful as they are valuable, Ebony bolts are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
	{ id = "ab_w_ebonybow", description = "As powerful as they are valuable, Ebony bows are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
    { id = "ab_w_ebonyclaymore", description = "As powerful as they are valuable, Ebony claymores are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
	{ id = "ab_w_ebonyglaive", description = "As powerful as they are valuable, Ebony glaives are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
	{ id = "ab_w_ebonyhalberd", description = "As powerful as they are valuable, Ebony halberds are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
	{ id = "ab_w_glassdart", description = "Virtually unparalleled in sharpness and light weight, Glass darts are created using rare metals and native volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glassdkatana", description = "Virtually unparalleled in sharpness and light weight, Glass dai-katanas are created using rare metals and native volcanic glass to produce an expensive yet delicate weapon. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_glasskatana", description = "Virtually unparalleled in sharpness and light weight, Glass katanas are created using rare metals and native volcanic glass to produce an expensive yet delicate weapon. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_glassrapier", description = "Thrusting swords most common to High Rock and the Summerset Isles, Glass rapiers are created using rare metals and volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glassrapierdirfla", description = "Thrusting swords most common to High Rock and the Summerset Isles, Glass rapiers are created using rare metals and volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glassrapierdirfro", description = "Thrusting swords most common to High Rock and the Summerset Isles, Glass rapiers are created using rare metals and volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glassrapierdirsto", description = "Thrusting swords most common to High Rock and the Summerset Isles, Glass rapiers are created using rare metals and volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glassrapierdirvip", description = "Thrusting swords most common to High Rock and the Summerset Isles, Glass rapiers are created using rare metals and volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glassspear", description = "Virtually unparalleled in sharpness and light weight, Glass spears are created using rare metals and native volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glasstanto", description = "Virtually unparalleled in sharpness and light weight, Glass tantos are created using rare metals and native volcanic glass to produce an expensive yet delicate weapon. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_glasstomahawk", description = "Virtually unparalleled in sharpness and light weight, Glass throwing axes are created using rare metals and native volcanic glass to produce an expensive yet delicate weapon.", itemType = "weapon" },
	{ id = "ab_w_glasswakizashi", description = "Virtually unparalleled in sharpness and light weight, Glass wakizashis are created using rare metals and native volcanic glass to produce an expensive yet delicate weapon. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_goblinarrow", description = "Forked arrow utilized by the goblin denizens of the Mournhold sewers, capable of noteworthy craftsmanship despite their brutish nature.", itemType = "weapon" },
	{ id = "ab_w_goblintomahawk", description = "Utilized by the goblin denizens of the Mournhold sewers, this throwing axe is fashioned from Durzog bone, the creatures never failing to find an unconventional use for their surroundings.", itemType = "weapon" },
	{ id = "ab_w_goldstclaymore", description = "Golden claymore collected from the remains of a Golden Saint that has been banished from the mortal plane. Better known as Aureals within the realms of Oblivion, these Daedra are primarily associated with Sheogorath and his Shivering Isles. Within his realm they maintain a matriarchal society and share a caste system with an eight-tier hierarchy, though hold a perpetual rivalry with the Mazken, or Dark Seducers.", itemType = "weapon" },
	{ id = "ab_w_huntsarrow", description = "Simple arrow fashioned from stone, an easily-crafted field weapon for adventurers and hunters, and cheap for those on a budget.", itemType = "weapon" },
	{ id = "ab_w_huntsbow", description = "Simple bow fashioned from animal bone, an easily-crafted field weapon for adventurers and hunters, and cheap for those on a budget.", itemType = "weapon" },
	{ id = "ab_w_impbow", description = "Standard-issue steel weapons for legionaries of the Empire, Imperial shortbows are imported to the various centers of Imperial power across Morrowind, largely due to a lacking supply of steel in the province and lesser production costs elsewhere in Tamriel.", itemType = "weapon" },
	{ id = "ab_w_impdaikatana", description = "Standard-issue steel weapons for legionaries of the Empire, Imperial dai-katanas are imported to the various centers of Imperial power across Morrowind, largely due to a lacking supply of steel in the province and lesser production costs elsewhere in Tamriel. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_impkatana", description = "Standard-issue steel weapons for legionaries of the Empire, Imperial katanas are imported to the various centers of Imperial power across Morrowind, largely due to a lacking supply of steel in the province and lesser production costs elsewhere in Tamriel. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_impspear", description = "Standard-issue steel weapons for legionaries of the Empire, Imperial spears are imported to the various centers of Imperial power across Morrowind, largely due to a lacking supply of steel in the province and lesser production costs elsewhere in Tamriel.", itemType = "weapon" },
	{ id = "ab_w_imptanto", description = "Standard-issue steel weapons for legionaries of the Empire, Imperial tantos are imported to the various centers of Imperial power across Morrowind, largely due to a lacking supply of steel in the province and lesser production costs elsewhere in Tamriel. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_impwakizashi", description = "Standard-issue steel weapons for legionaries of the Empire, Imperial wakizashis are imported to the various centers of Imperial power across Morrowind, largely due to a lacking supply of steel in the province and lesser production costs elsewhere in Tamriel. Having originated in the mysterious land of Akavir, this particular style of blade was brought to Tamriel after a series of Akaviri invasions and settlements, ultimately influencing the Second Empire and popularizing them across the provinces.", itemType = "weapon" },
	{ id = "ab_w_ironrapier", description = "Thrusting swords most common to High Rock and the Summerset Isles, Iron rapiers tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_ironrapierfla", description = "Thrusting swords most common to High Rock and the Summerset Isles, Iron rapiers tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_ironrapiersha", description = "Thrusting swords most common to High Rock and the Summerset Isles, Iron rapiers tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_ironrapierspa", description = "Thrusting swords most common to High Rock and the Summerset Isles, Iron rapiers tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_ironrapiervip", description = "Thrusting swords most common to High Rock and the Summerset Isles, Iron rapiers tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_irontomahawk", description = "Crafted from one of the most abundant materials of Tamriel, Iron throwing axes tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_irontomahawkfla", description = "Crafted from one of the most abundant materials of Tamriel, Iron throwing axes tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_irontomahawksha", description = "Crafted from one of the most abundant materials of Tamriel, Iron throwing axes tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_irontomahawkspa", description = "Crafted from one of the most abundant materials of Tamriel, Iron throwing axes tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_irontomahawkvip", description = "Crafted from one of the most abundant materials of Tamriel, Iron throwing axes tend to be heavier than desired and comparatively less effective in combat due to a lack in sharpness. However, their cheap cost makes them a popular choice among adventurers and bandits.", itemType = "weapon" },
	{ id = "ab_w_nordiclongaxe", description = "Fashioned from steel and enchanted with the mystical runes of Skyrim, Nordic long axes are carried by Nord warriors across Tamriel, never to forget their northern heritage.", itemType = "weapon" },
	{ id = "ab_w_nordicmace", description = "Fashioned from steel and enchanted with the mystical runes of Skyrim, Nordic maces are carried by Nord warriors across Tamriel, never to forget their northern heritage.", itemType = "weapon" },
	{ id = "ab_w_nordicsilverbow", description = "Decorated in mystical runes, Nordic Silver bows are native to Solstheim and crafted by the Skaal people, whose legends tell of their arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_nordicsilverspear", description = "Decorated in mystical runes, Nordic Silver spears are native to Solstheim and crafted by the Skaal people, whose legends tell of their arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_nordictomahawk", description = "Fashioned from steel and enchanted with the mystical runes of Skyrim, Nordic throwing axes are carried by Nord warriors across Tamriel, never to forget their northern heritage.", itemType = "weapon" },
	{ id = "ab_w_orcisharrow", description = "Ornately designed by their master craftsmen, Orcish arrows are among the few fine steel weapons crafted by the Orsimer, whose talents are more commonly applied to armor.", itemType = "weapon" },
	{ id = "ab_w_orcishmace", description = "Ornately designed by their master craftsmen, Orcish maces are among the few fine steel weapons crafted by the Orsimer, whose talents are more commonly applied to armor.", itemType = "weapon" },
	{ id = "ab_w_recrossbow", description = "Made from the cheapest and most abundant materials with which to fashion weapons, reinforced crossbows are an improvement on the common wooden variant, fashioned with iron limbs for greater stability.", itemType = "weapon" },
	{ id = "ab_w_silverhalberd", description = "Produced by the plating of silver onto steel, Silver halberds are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silverknife", description = "Produced by the plating of silver onto steel, Silver throwing knives are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silverrapier", description = "Thrusting swords most common to High Rock and the Summerset Isles, Silver rapiers are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silverrapiercrufla", description = "Thrusting swords most common to High Rock and the Summerset Isles, Silver rapiers are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silverrapiercrusha", description = "Thrusting swords most common to High Rock and the Summerset Isles, Silver rapiers are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silverrapiercruspa", description = "Thrusting swords most common to High Rock and the Summerset Isles, Silver rapiers are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silverrapiercruvip", description = "Thrusting swords most common to High Rock and the Summerset Isles, Silver rapiers are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silvertomahawk", description = "Produced by the plating of silver onto steel, Silver throwing axes are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silvertomahawkcrufla", description = "Produced by the plating of silver onto steel, Silver throwing axes are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silvertomahawkcrusha", description = "Produced by the plating of silver onto steel, Silver throwing axes are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silvertomahawkcruspa", description = "Produced by the plating of silver onto steel, Silver throwing axes are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_silvertomahawkcruvip", description = "Produced by the plating of silver onto steel, Silver throwing axes are far more visually appealing but marginally less capable than regular steel, however their function comes primarily from arcane effectiveness against the undead and werewolves.", itemType = "weapon" },
	{ id = "ab_w_stalhrimarrow", description = "Crafted only by skilled blacksmiths educated in the art, Stalhrim arrows are fashioned from the rare material Stalhrim, a form of enchanted ice originally used in the burial rites of ancient Nords.", itemType = "weapon" },
	{ id = "ab_w_stalhrimbattleaxe", description = "Crafted only by skilled blacksmiths educated in the art, Stalhrim battle axes are fashioned from the rare material Stalhrim, a form of enchanted ice originally used in the burial rites of ancient Nords.", itemType = "weapon" },
	{ id = "ab_w_stalhrimbow", description = "Crafted only by skilled blacksmiths educated in the art, Stalhrim bows are fashioned from the rare material Stalhrim, a form of enchanted ice originally used in the burial rites of ancient Nords.", itemType = "weapon" },
	{ id = "ab_w_stalhrimshortsword", description = "Crafted only by skilled blacksmiths educated in the art, Stalhrim shortswords are fashioned from the rare material Stalhrim, a form of enchanted ice originally used in the burial rites of ancient Nords.", itemType = "weapon" },
	{ id = "ab_w_stalhrimspear", description = "Crafted only by skilled blacksmiths educated in the art, Stalhrim spears are fashioned from the rare material Stalhrim, a form of enchanted ice originally used in the burial rites of ancient Nords.", itemType = "weapon" },
	{ id = "ab_w_steelrapier", description = "Thrusting swords most common to High Rock and the Summerset Isles, Steel rapiers are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal.", itemType = "weapon" },
	{ id = "ab_w_steelrapiercrufla", description = "Thrusting swords most common to High Rock and the Summerset Isles, Steel rapiers are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal.", itemType = "weapon" },
	{ id = "ab_w_steelrapiercrusha", description = "Thrusting swords most common to High Rock and the Summerset Isles, Steel rapiers are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal.", itemType = "weapon" },
	{ id = "ab_w_steelrapiercruspa", description = "Thrusting swords most common to High Rock and the Summerset Isles, Steel rapiers are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal.", itemType = "weapon" },
	{ id = "ab_w_steelrapiercruvip", description = "Thrusting swords most common to High Rock and the Summerset Isles, Steel rapiers are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal.", itemType = "weapon" },
	{ id = "ab_w_steeltomahawk", description = "The first choice of many soldiers and mercenaries on a budget, Steel throwing axes are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal. While this particular design is Imperial in origin, steel has been incorporated into a wide variety of weapons.", itemType = "weapon" },
	{ id = "ab_w_steeltomahawkfla", description = "The first choice of many soldiers and mercenaries on a budget, Steel throwing axes are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal. While this particular design is Imperial in origin, steel has been incorporated into a wide variety of weapons.", itemType = "weapon" },
	{ id = "ab_w_steeltomahawksha", description = "The first choice of many soldiers and mercenaries on a budget, Steel throwing axes are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal. While this particular design is Imperial in origin, steel has been incorporated into a wide variety of weapons.", itemType = "weapon" },
	{ id = "ab_w_steeltomahawkspa", description = "The first choice of many soldiers and mercenaries on a budget, Steel throwing axes are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal. While this particular design is Imperial in origin, steel has been incorporated into a wide variety of weapons.", itemType = "weapon" },
	{ id = "ab_w_steeltomahawkvip", description = "The first choice of many soldiers and mercenaries on a budget, Steel throwing axes are crafted from a refined form of common iron which offers notable improvement in durability  without increasing the weight of the metal. While this particular design is Imperial in origin, steel has been incorporated into a wide variety of weapons.", itemType = "weapon" },
	{ id = "ab_w_toolebonypick", description = "High quality ebony tool utilized by miners in breaking apart rock, or by less innocent characters in breaking apart bone. As powerful as they are valuable, Ebony picks are crafted with a rare volcanic glass found primarily on Vvardenfell. Legend claims Ebony to be the crystallized blood of the trickster-god Lorkhan, but even ignoring such supposed significance, it remains among the most precious substances in the Empire on account of its durability.", itemType = "weapon" },
}

local function initialized()
    if tooltipsComplete then
        for _, data in ipairs(tooltipData) do
            tooltipsComplete.addTooltip(data.id, data.description, data.itemType)
        end
    end
end
event.register("initialized", initialized)

-- key - Generic keys or other objects used to unlock or activate objects, such as Propylon Indices. Lockpicks do NOT fall under this category.
-- quest - Items required for the completion of a quest.
-- unique - Notable items which may only be found once or rewarded once after a quest, generally have the same appearance as other generic items.
-- artifact - Objects with a unique appearance and lore significance, such as Daedric and Aedric objects.
-- armor - Regular and generic enchanted armor and shields.
-- weapon - Regular and generic enchanted weapons and ammunition.
-- tool - Objects centered around a game mechanic such as alchemical apparatus, lockpicks, probes, and repair hammers.
-- soulGem - Empty gems or similar added object capable of holding a soul.
-- creature - Any creature which might have its soul trapped, descriptions should generally be about the creature in question.
-- misc - Clutter, coins, decorative objects, and any other items that don't fall into another category.
-- light - Objects that emit light and may be picked up and/or equipped by the player.
-- book - Books, notes, and any other readable object the player may acquire.
-- clothing - Regular and generic enchanted clothing and jewelry.
-- alchemy - Magical potions that are pre-made or otherwise have unique IDs, beverages like Sujamma do NOT fall under this category.
-- ingredients - Any items that may be used to brew potions or poisons, as well as beverages like Sujamma.
-- scroll - Enchanted scrolls used to cast magical spells.