return {
    "great",
    "polished",
    "close visor",
    "open visor",
    "black",
    "klappvizeir",
    "plate",
    "gilt",
    "open",
    "close'",
    "copper",
    "male",
    "footman's",
    "red tabbard",
    "white tabbard",
    "redguard",
    "with coif 2",
    "fingered",
    "high soft",
    "with poleyns",
    "landsknecht",
    "& sash",
    "quilted",
    "poet",
    "lamellar",
    "fishnet",
    "bronze",
    "sempach", 
    "large",
    "small hook",
    "as spear",
    "ceremonial",
    "dragonfly",
    "long",
    "cloth",
    "red bone",
    "mud mesh",
    "camo",
    "black & red",
    "velvet",
}