return {
    "hestatur, service area",
    "hestatur, feast hall",
    "hestatur, chapel",
    "hestatur, great hall",
    "hestatur, guard tower",
    "hestatur, the tower of glory",
    "hestatur, guard tower attic",
    "hestatur, library",
    "hestatur, servants' rooms",
    "hestatur, lord's chambers",
    "hestatur, entry hall",
    "hestatur, gallery",
    "hestatur, guest rooms",
    "hestatur, attic",
    "hestatur, laboratory",
    "hestatur, south wall",
    "hestatur, small tower",
    "hestatur, guard tower, upper floors",
    "hestatur, bath",
    "hestatur, basement hall",
    "hestatur, east basement hallway",
    "hestatur, crypt",
    "hestatur, prison",
    "hestatur, main tower top",
    "Esm3ExteriorCell:6:26",
    "Esm3ExteriorCell:5:26",
    "Esm3ExteriorCell:6:25",
}
