return {

    rugs = {
        objects = {
            "G_Furn_rug_big_01",
            "spok_rug_*",
            "G_Furn_rug_big_05",
            "spok_rug_round_05",
            "furn_de_rug_*",
            "g_furn_rug_*",
            "G_Furn_rug_big_08",
        },
        name = "Rugs",
        price = 500,
    },
    paintings = {
        objects = {
            "spok_hpic_*",
            
        },
        name = "Paintings",
        price = 500,
    },
    mannequins = {
        objects = {
            "spok_mannequin_s",
            "spok_mannequin_w",
            "furn_velothi_altar_01",
        },
        name = "Mannequins",
        price = 500
    },
    banners = {
        objects = { "furn_c_t_wizard_01",
            "furn_banner_temple_03_indoors",
            "furn_banner_temple_01_indoors",
            "furn_banner_temple_02_indoors",
            "furn_de_tapestry_*",
            "furn_com_tapestry_*",
            "furn_c_t_*",
            "furn_g_tapestry_*",
            "furn_de_bannerpost_02" },
        name = "Wall Banners/Posters",
        price = 500
    },
    furniture = {
        objects = {
            "furn_de_r_table_07",
            "furn_de_r_table_08",
            "spok_chest_5",
            "spok_chest_1",
            "furn_com_rm_chair_03",
            "spok_chest_2",
            "furn_com_r_table_01",
            "furn_com_rm_table_04",
            "active_de_pr_bed_21",
            "spok_bed_m4",
            "furn_de_cushion_square_04",
            "furn_de_r_bench_02",
            "furn_de_r_chair_03",
            "misc_uni_pillow_01",
            "spok_chest_5",
            "active_de_pr_bed_21",
            "misc_uni_pillow_01",
            "furn_de_r_table_*",
            "furn_com_r_chair_01",
            "light_com_candle_08",
            "AB_o_DeRchDeskEmpty",
            "spok_chest_7",
            "spok_cupboard_1",
            "Furn_De_R_Bookshelf_02",
            "furn_com_r_bookshelf_01",
            "spok_drawers_3",
            "spok_table_1",
            "spok_table_2",
            "furn_de_r_table_03",
            "spok_chest_s2",
            "spok_chest_s1",
            "furn_de_r_bench_01",
            "furn_de_r_wallscreen_02",
            "furn_com_r_chair_01",
            "furn_glassdisplaycase_0*",
            "furn_com_rm_barstool",
            "furn_com_rm_shelf_02",
            "light_com_candle_10",
            "active_com_bunk_01",
            "furn_de_p_bookshelf_01",
            "active_com_bunk_01",
            "spok_chest_6",
            "spok_barrel_*",
            "furn_firepit00",
            "light_logpile",
            "spok_closet_1",
            "furn_de_p_*",
            "spok_hutch*",
            "spok_chest*",
            "spok_sack*",
            "spok_urn*",
            "spok_drawers*",
            "furn_de_p_chair_01",
            "furn_de_p_table_06",
            "spok_crate_1",
            "furn_dwrv_stove_00"
        },
        name = "Furniture",
        price = 500
    },
}
