local UndercityCellNames = {
    ['nar shaddaa, lower city'] = true,
    ['nar shaddaa, shony factory'] = true,
    ['nar shaddaa, peyuska plaza'] = true,
    ['nar shaddaa, smuggler\'s operation'] = true,
    ['nar shaddaa, gang hideout'] = true,
    ['nar shaddaa, obsheeda plaza'] = true,
    ["nar shaddaa, 110 peyjee alley"] = true,
    ["nar shaddaa, 111 peyjee alley"] = true,
    ["nar shaddaa, 1120 central alley"] = true,
    ["nar shaddaa, 112 peyjee alley"] = true,
    ["nar shaddaa, 1130 central alley"] = true,
    ["nar shaddaa, 1134 central alley"] = true,
    ["nar shaddaa, 1135 central alley"] = true,
    ["nar shaddaa, 1137 central alley"] = true,
    ["nar shaddaa, 113 peyjee alley"] = true,
    ["nar shaddaa, 132 alley west"] = true,
    ["nar shaddaa, 134 alley west"] = true,
    ["nar shaddaa, 135 alley west"] = true,
    ["nar shaddaa, 140 alley west"] = true,
    ["nar shaddaa, 144 alley west"] = true,
    ["nar shaddaa, 153 alley west"] = true,
    ["nar shaddaa, 155 alley west"] = true,
    ["nar shaddaa, 158 alley east"] = true,
    ["nar shaddaa, 161 alley east"] = true,
    ["nar shaddaa, 162 alley east"] = true,
    ["nar shaddaa, 163 alley east"] = true,
    ["nar shaddaa, 165 alley east"] = true,
    ["nar shaddaa, 166 alley east"] = true,
    ["nar shaddaa, 167 alley east"] = true,
    ["nar shaddaa, 168 alley east"] = true,
    ["nar shaddaa, 170 alley east"] = true,
    ["nar shaddaa, 173 alley east"] = true,
    ["nar shaddaa, 175 alley east"] = true,
    ["nar shaddaa, 176 alley east"] = true,
    ["nar shaddaa, 177 alley east"] = true,
    ["nar shaddaa, 178 alley east"] = true,
    ["nar shaddaa, 2440 magari alley"] = true,
    ["nar shaddaa, 2443 magari alley"] = true,
    ["nar shaddaa, 2444 magari alley"] = true,
    ["nar shaddaa, 2448 magari alley"] = true,
    ["nar shaddaa, 2449 magari alley"] = true,
    ["nar shaddaa, 2500 magari alley"] = true,
    ["nar shaddaa, 2 inops alley"] = true,
    ["nar shaddaa, 3224 market alley"] = true,
    ["nar shaddaa, 3225 market alley"] = true,
    ["nar shaddaa, 3227 market alley"] = true,
    ["nar shaddaa, 3228 market alley"] = true,
    ["nar shaddaa, 3229 market alley"] = true,
    ["nar shaddaa, 3232 market alley"] = true,
    ["nar shaddaa, 3235 market alley"] = true,
    ["nar shaddaa, 3 inops alley"] = true,
    ["nar shaddaa, 44 wehmoom alley"] = true,
    ["nar shaddaa, 45 wehmoom alley"] = true,
    ["nar shaddaa, 47 wehmoom alley"] = true,
    ["nar shaddaa, 480 olivier alley"] = true,
    ["nar shaddaa, 485 olivier alley"] = true,
    ["nar shaddaa, 486 olivier alley"] = true,
    ["nar shaddaa, 491 olivier alley"] = true,
    ["nar shaddaa, 4 inops alley"] = true,
    ["nar shaddaa, 712 hooga alley"] = true,
    ["nar shaddaa, 715 hooga alley"] = true,
    ["nar shaddaa, 717 hooga alley"] = true,
    ["nar shaddaa, 718 hooga alley"] = true,
    ["nar shaddaa, 720 hooga alley"] = true,
    ["nar shaddaa, 7 inops alley"] = true,
    ["nar shaddaa, 8 inops alley"] = true,
    ["nar shaddaa, quanun alley"] = true,
}

local CantinaCellNames = {
    ['cantina lodgings'] = true,
    ['lok, graveridge cantina'] = true,
    ['manaan, cantina'] = true,
    ['manaan, inner city cantina'] = true,
    ['nar shaddaa, cantina'] = true,
    ['nar shaddaa, eddie\'s den'] = true,
    ['taris, lower city cantina'] = true,
    ['taris, upper city cantina'] = true,
    ['taris, upper city cantina, arena'] = true,
    ['tatooine, cantina'] = true,
}

local DantooineCellNames = {
    ['dantooine'] = true,
    ['dantooine, apartment a'] = true,
    ['dantooine, apartment b'] = true,
    ['dantooine, apartment c'] = true,
    ['dantooine, apartment d'] = true,
    ['dantooine, apartment e'] = true,
    ['dantooine, apartment f'] = true,
    ['dantooine, apartment g'] = true,
    ['dantooine, apartments'] = true,
    ['dantooine, ballast'] = true,
    ['dantooine, cavern'] = true,
    ['dantooine, crystal cave'] = true,
    ['dantooine, czerka barracks'] = true,
    ['dantooine, czerka mine barracks'] = true,
    ['dantooine, czerka mining office'] = true,
    ['dantooine, czerka office'] = true,
    ['dantooine, damp cave'] = true,
    ['dantooine, dantari wilds'] = true,
    ['dantooine, daranti stronghold'] = true,
    ['dantooine, empty manor'] = true,
    ['dantooine, equipment warehouse'] = true,
    ['dantooine, estate grounds'] = true,
    ['dantooine, farmhand\'s quarters'] = true,
    ['dantooine, farmhouse'] = true,
    ['dantooine, home'] = true,
    ['dantooine, hunting grounds'] = true,
    ['dantooine, jitaii estate'] = true,
    ['dantooine, jitaii servant\'s quarters'] = true,
    ['dantooine, kagrid\'s hut'] = true,
    ['dantooine, kath cave'] = true,
    ['dantooine, lavigne estate'] = true,
    ['dantooine, lavigne manor'] = true,
    ['dantooine, lavigne tunnels'] = true,
    ['dantooine, lucienelle estate'] = true,
    ['dantooine, medical bay'] = true,
    ['dantooine, meditation site'] = true,
    ['dantooine, sea'] = true,
    ['dantooine, seaside grotto'] = true,
    ['dantooine, seaside manor'] = true,
    ['dantooine, seaside temple'] = true,
    ['dantooine, servant\'s quarters'] = true,
    ['dantooine, starkos\' arms'] = true,
    ['dantooine, storehouse'] = true,
    ['dantooine, terenthium mine'] = true,
    ['dantooine, tiiona\'s weapons'] = true,
    ['dantooine, valley of the jedi'] = true,
    ['dantooine, yot bean storehouse'] = true,
    ['dantooine, zanotti estate'] = true,
    ['dantooine, zanotti servant quarters'] = true,
}

local EndarSpireCellNames = {
    ['imperial prison ship'] = true,
    ['the endar spire'] = true,
}

local KashyykCellNames = {
    ['kashyyk'] = true,
    ['kashyyk, arena'] = true,
    ['kashyyk, arena office'] = true,
    ['kashyyk, azoozoo\'s hut'] = true,
    ['kashyyk, banished chief\'s hut'] = true,
    ['kashyyk, banished lands'] = true,
    ['kashyyk, banished storehouse'] = true,
    ['kashyyk, banished wookie\'s hut'] = true,
    ['kashyyk, beast cave'] = true,
    ['kashyyk, blue manor'] = true,
    ['kashyyk, bolotaur den'] = true,
    ['kashyyk, boyle research facility'] = true,
    ['kashyyk, chokoon\'s hut'] = true,
    ['kashyyk, creaky hut'] = true,
    ['kashyyk, czerka barracks'] = true,
    ['kashyyk, czerka office'] = true,
    ['kashyyk, gary sinnerman\'s hut'] = true,
    ['kashyyk, geerah\'s tent'] = true,
    ['kashyyk, gray jedi camp'] = true,
    ['kashyyk, gray\'s tent'] = true,
    ['kashyyk, great tree interior'] = true,
    ['kashyyk, green manor'] = true,
    ['kashyyk, infested grotto'] = true,
    ['kashyyk, jaa vene\'s hut'] = true,
    ['kashyyk, jhir voo\'s tent'] = true,
    ['kashyyk, joseph evan\'s tent'] = true,
    ['kashyyk, kahaama\'s hut'] = true,
    ['kashyyk, kinrath lair'] = true,
    ['kashyyk, lab'] = true,
    ['kashyyk, mandalorian camp'] = true,
    ['kashyyk, mar vim\'s tent'] = true,
    ['kashyyk, medical bay'] = true,
    ['kashyyk, odd tent'] = true,
    ['kashyyk, orange manor'] = true,
    ['kashyyk, pholin\'s equipment and pet shop'] = true,
    ['kashyykrace'] = true,
    ['kashyyk, ransacked hut'] = true,
    ['kashyyk, red manor'] = true,
    ['kashyyk, shade smith\'s tent'] = true,
    ['kashyyk, shadowlands'] = true,
    ['kashyyk, shadowlands south'] = true,
    ['kashyyk, shaman\'s hut'] = true,
    ['kashyyk, terentatek lair'] = true,
    ['kashyyk, walkways'] = true,
    ['kashyyk, wookie hut'] = true,
    ['kashyyk, wookie village'] = true,
}

local KorribanCellNames = {
    ['korriban'] = true,
    ['korriban, ancient complex'] = true,
    ['korriban, ancient structure'] = true,
    ['korriban, ancient tomb'] = true,
    ['korriban, dark valley'] = true,
    ['korriban, dark valley, dark jedi\'s yurt'] = true,
    ['korriban, dark valley, kyber chamber'] = true,
    ['korriban, dark valley, trials of hate'] = true,
    ['korriban, dark valley, trials of pain'] = true,
    ['korriban, yargrum\'s tomb'] = true,
}

local ManaanCellNames = {
    ['manaan, apartment a1'] = true,
    ['manaan, apartment a2'] = true,
    ['manaan, apartment a3'] = true,
    ['manaan, apartment a4'] = true,
    ['manaan, apartment b1'] = true,
    ['manaan, apartment b2'] = true,
    ['manaan, apartment b3'] = true,
    ['manaan, apartment b4'] = true,
    ['manaan, apartments'] = true,
    ['manaan, bazaar'] = true,
    ['manaan, cantina'] = true,
    ['manaan, central'] = true,
    ['manaan, delivery ship'] = true,
    ['manaan, derivian\'s waterwear'] = true,
    ['manaan, disease control facility'] = true,
    ['manaan, docking bay'] = true,
    ['manaan, eagle 5'] = true,
    ['manaan, ghurbha 1'] = true,
    ['manaan, ghurbha 2'] = true,
    ['manaan, ghurbha 3'] = true,
    ['manaan, ghurbha 4'] = true,
    ['manaan, ghurbha 5'] = true,
    ['manaan, ghurbha 6'] = true,
    ['manaan, ghurbha apartments'] = true,
    ['manaan, ignatious\' reef'] = true,
    ['manaan, import and export bay'] = true,
    ['manaan, inner city'] = true,
    ['manaan, inner city cantina'] = true,
    ['manaan, ivesh\'s'] = true,
    ['manaan, kogal\'s office'] = true,
    ['manaan, kolto processing facility'] = true,
    ['manaan, medical facility'] = true,
    ['manaan, melchior\'s reef'] = true,
    ['manaan, moh-ruh 1'] = true,
    ['manaan, moh-ruh 2'] = true,
    ['manaan, moh-ruh 3'] = true,
    ['manaan, moh-ruh 4'] = true,
    ['manaan, moh-ruh apartments'] = true,
    ['manaan, nauther lair'] = true,
    ['manaanrace'] = true,
    ['manaan, republic docking bay'] = true,
    ['manaan, republic embassy'] = true,
    ['manaan, selkath facility'] = true,
    ['manaan, sith docking bay'] = true,
    ['manaan, sith embassy'] = true,
    ['manaan, sith prisoner transport customs'] = true,
    ['manaan, sith prison transport hangar'] = true,
    ['manaan, submersible docking bay'] = true,
    ['manaan, tyvak\'s armory'] = true,
    ['manaan, west'] = true,
    ['manaan, yortal\'s junkpile'] = true,
}

local TarisCellNames = {
    ['taris'] = true,
    ['taris, across the wall'] = true,
    ['taris, battleground'] = true,
    ['taris, black vulkar base, barracks'] = true,
    ['taris, black vulkar base, lower level'] = true,
    ['taris, black vulkar base, main level'] = true,
    ['taris, black vulkar base, spice lab'] = true,
    ['taris, black vulkar base, underdark'] = true,
    ['taris, central plaza'] = true,
    ['taris, central plaza, capital tower'] = true,
    ['taris, central plaza, capital tower lab'] = true,
    ['taris, central plaza, capital tower underground lab'] = true,
    ['taris, central plaza, capital tower upper level'] = true,
    ['taris, central plaza, government office a'] = true,
    ['taris, central plaza, government office b'] = true,
    ['taris, central plaza, government office c'] = true,
    ['taris, central plaza, government office d'] = true,
    ['taris, central plaza, outpost'] = true,
    ['taris, infested sewers'] = true,
    ['taris, lower city'] = true,
    ['taris, lower city black market'] = true,
    ['taris, lower city cantina'] = true,
    ['taris, lower city maintenance room'] = true,
    ['taris, lower city north apartments'] = true,
    ['taris, lower city south apartments'] = true,
    ['taris, rakghoul territory'] = true,
    ['taris, remnants'] = true,
    ['taris, ruined plaza'] = true,
    ['taris, ruined plaza, central building'] = true,
    ['taris, ruined plaza, medical bay'] = true,
    ['taris, ruined plaza, outpost'] = true,
    ['taris, ruined plaza, refugee retreat'] = true,
    ['taris, sith headquarters, level 1'] = true,
    ['taris, sith headquarters, level 2'] = true,
    ['taris, sith headquarters, level 3'] = true,
    ['taris, sith headquarters, oc office'] = true,
    ['taris, the promised land'] = true,
    ['taris, undercity'] = true,
    ['taris, undercity nest'] = true,
    ['taris, upper city apartments'] = true,
    ['taris, upper city cantina'] = true,
    ['taris, upper city cantina, arena'] = true,
    ['taris, upper city central building'] = true,
    ['taris, upper city north'] = true,
    ['taris, upper city north, marketplace'] = true,
    ['taris, upper city south'] = true,
}

local TarisRuinedPlazaCells = {
    ['taris, ruined plaza'] = true,
    ['taris, ruined plaza, central building'] = true,
    ['taris, ruined plaza, medical bay'] = true,
    ['taris, ruined plaza, outpost'] = true,
    ['taris, ruined plaza, refugee retreat'] = true,
}

local TatooineDangerousCellNames = {
    ['tatooine'] = true,
    -- Not a part of the original soundBank but seems cool here
    ['tatooine, arena'] = true,
    ['tatooine, death canyon'] = true,
    ['tatooine, deep sea'] = true,
    ['tatooine, dune sea'] = true,
    ['tatooine, expanse'] = true,
    -- ['tatooine, genoharadan guildhall'] = true,
}

local TatooineCivilizedCellNames = {
    ['tatooine, abandoned hut'] = true,
    ['tatooine, beast\'s lair'] = true,
    ['tatooine, beekno\'s hut'] = true,
    ['tatooine, beero\'s hut'] = true,
    ['tatooine, carl terro\'s droid shop'] = true,
    ['tatooine, cecil\'s blasters and shields'] = true,
    ['tatooine, coro\'s hut'] = true,
    ['tatooine czerka office'] = true,
    ['tatooine, dex\'s hut'] = true,
    ['tatooine, durelium mine'] = true,
    ['tatooine, elisa\'s hut'] = true,
    ['tatooine, empty hut'] = true,
    ['tatooine, empty manor'] = true,
    ['tatooine, farm house'] = true,
    ['tatooine, gin\'s hut'] = true,
    ['tatooine, gudda\'s hut'] = true,
    ['tatooine, haydun\'s hut'] = true,
    -- ['tatooine, hooded sandcrawler'] = true,
    ['tatooine, hunter\'s lodge'] = true,
    ['tatooine, hut'] = true,
    ['tatooine, hutt base'] = true,
    ['tatooine, isael\'s hut'] = true,
    ['tatooine, jail'] = true,
    ['tatooine, jawa sandcrawler'] = true,
    ['tatooine, jaysun\'s hut'] = true,
    ['tatooine, kli rei\'s lodge'] = true,
    ['tatooine, manor'] = true,
    ['tatooine, medical bay'] = true,
    -- ['tatooine, mouth of the sea'] = true,
    ['tatooine, narva\'s hut'] = true,
    ['tatooine, old water station'] = true,
    -- ['tatooinerace'] = true,
    -- ['tatooine, republic base'] = true,
    ['tatooine, rodian district'] = true,
    ['tatooine, roomo\'s hut'] = true,
    -- ['tatooine, sandcrawler'] = true,
    -- ['tatooine, sand hole'] = true,
    -- ['tatooine, sand people cave'] = true,
    ['tatooine, sandreach'] = true,
    ['tatooine, sandreach, borg\'s hut'] = true,
    ['tatooine, sandreach, czerka barracks'] = true,
    ['tatooine, sandreach, czerka office'] = true,
    ['tatooine, sandreach, czerka underground'] = true,
    ['tatooine, sandreach, czerka underground backroom'] = true,
    ['tatooine, sandreach, czerka underground chamber'] = true,
    ['tatooine, sandreach, czerka underground lab'] = true,
    ['tatooine, sandreach, czerka underground tram'] = true,
    ['tatooine, sandreach, gando\'s hut'] = true,
    ['tatooine, sandreach, general store'] = true,
    ['tatooine, sandreach, jorjor\'s hut'] = true,
    ['tatooine, sandreach, mango\'s hut'] = true,
    ['tatooine, sandreach, manor'] = true,
    ['tatooine, sandreach, medical bay'] = true,
    ['tatooine, sandreach, northeast bay'] = true,
    ['tatooine, sandreach, northwest bay'] = true,
    ['tatooine, sandreach, south bay'] = true,
    ['tatooine, sandriver'] = true,
    -- ['tatooine, sewers'] = true,
    -- ['tatooine, swoop racetrack'] = true,
    -- ['tatooine, the great bazaar'] = true,
    -- ['tatooine, the hidden stash'] = true,
    -- ['tatooine, tusken raider hut'] = true,
    -- ['tatooine, vacant hut'] = true,
    ['tatooine, vorn\'s hut'] = true,
    ['tatooine, warat\'s hut'] = true,
    ['tatooine warehouse'] = true,
    -- ['tatooine, watery tomb'] = true,
    ['tatooine, zoboo\'s hut'] = true,
}

---@type S3maphorePlaylist[]
return {
    {
        id = 'Sounds of Starwind - Undercity',
        priority = 500,
        randomize = true,

        tracks = {
            'Music/Undercity/Undercity 1.mp3',
            'Music/Undercity/Undercity 2.mp3',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(UndercityCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Nar Shaddaa Market',
        priority = 488,

        tracks = {
            'Music/Nar Shaddaa Ambience.mp3',
        },

        isValidCallback = function(playback)
            return playback.state.cellName == 'nar shaddaa, makacheesa market'
        end,
    },
    {
        id = 'sounds of starwind/kashyyk',
        priority = 495,
        randomize = true,

        tracks = {
            'Music/Kashyyk.mp3',
            'Music/Kashyyk2.mp3',
            'Music/Kashyyk3.wav',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(KashyykCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Tatooine Settlement',
        priority = 499,
        randomize = true,

        tracks = {
            'Music/Sandriver.mp3',
            'Music/Sandriver2.mp3',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(TatooineCivilizedCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Tatooine Desert',
        priority = 491,
        randomize = true,

        tracks = {
            'Music/Tatooine.mp3',
            'Music/Tatooine2.mp3',
            'Music/Tatooine3.wav',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(TatooineDangerousCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Dantooine',
        priority = 497,
        randomize = true,

        tracks = {
            'Music/Dantooine.mp3',
            'Music/Dantooine2.mp3',
            'Music/Dantooine3.wav',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(DantooineCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Korriban',
        priority = 494,
        randomize = true,

        tracks = {
            'Music/Korriban.mp3',
            'Music/Korriban2.mp3',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(KorribanCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Manaan',
        priority = 498,
        randomize = true,
        tracks = {
            'Music/Manaan.mp3',
            'Music/Manaan2.mp3',
            'Music/Manaan3.wav',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(ManaanCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Taris',
        priority = 496,
        randomize = true,

        tracks = {
            'Music/Taris3.mp3',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(TarisCellNames)
        end,
    },
    {
        id = 'Sounds of Starwind - Taris Ruined Plaza',
        priority = 492,

        tracks = {
            'Music/Shadetheme.mp3',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(TarisRuinedPlazaCells)
        end,
    },
    {
        id = 'sounds of starwind/cantina',
        priority = 493,

        tracks = {
            'Music/SSW/Cantinabackground.mp3',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(CantinaCellNames)
        end,
    },
    {
        id = 'sounds of starwind/endar spire',
        priority = 50,

        tracks = {
            'Music/Endar Spire.mp3',
        },

        isValidCallback = function(playback)
            return playback.rules.cellNameExact(EndarSpireCellNames)
        end,
    },
}
