-- -----------------------------------------------------------------------------
-- Item data for Expanded Loot - Food and Dishes
-- -----------------------------------------------------------------------------
return {
   consumables = {
      -- Snacks                         Th   Hu   Ex
      ["o_ingred_ash_yam_slcd"]     = { 0,  -25, 0 },
      ["o_ingred_roll_egg"]         = { 0,  -50, 0 },
      ["o_ingred_roll_meat"]        = { 0,  -50, 0 },
      ["o_ingred_roll_mushrm"]      = { 0,  -50, 0 },
      ["o_ingred_roll_rice"]        = { 0,  -50, 0 },
      ["o_ingred_guar_jerky"]       = { 0,  -50, 0 },
      ["o_cup_rice"]                = { 0,  -50, 0 },
      ["o_bowl_beans"]              = { 0,  -50, 0 },
      ["o_ml_beanrice"]             = { 0,  -75, 0 },
      ["o_6th_bloodberry"]          = { 0,  -15, 0 },
      ["o_meat_roast"]              = { 0, -100, 0 },
      ["o_ml_herbs"]                = { 0,  -15, 0 },
      ["o_drumstick_big"]           = { 0,  -65, 0 },
      ["o_drumstick_small"]         = { 0,  -50, 0 },

      -- Egg and Sandwich              Th   Hu   Ex
      ["o_boilegg"]                 = { 0,  -75, 0 },
      ["o_friedegg"]                = { 0,  -75, 0 },
      ["o_ml_egg_kresh"]            = { 0,  -75, 0 },
      ["o_ml_mtl_egg"]              = { 0,  -75, 0 },
      ["o_ml_egg_guar_jerky"]       = { 0, -100, 0 },
      ["o_ml_egg_bread"]            = { 0, -100, 0 },
      ["o_sandwich_eggslice"]       = { 0,  -75, 0 },
      ["o_sandwich_meat"]           = { 0,  -75, 0 },
      ["o_sandwich_meat_dbl"]       = { 0,  -75, 0 },
      ["o_6th_jam_sandwich"]        = { 0,  -75, 0 },
      ["o_sandwich_egg_dbl"]        = { 0,  -75, 0 },
      ["o_ml_kwama_bun"]            = { 0, -100, 0 },
      ["o_kwama_bun"]               = { 0, -100, 0 },
      ["o_ml_2xsandw"]              = { 0, -125, 0 },
      ["o_ml_sndwich_rolls"]        = { 0, -125, 0 },
      ["o_ml_3roll"]                = { 0, -125, 0 },

      -- Porridges                     Th   Hu   Ex
      ["o_bogfly_bowl"]             = { 0,   -75, 0 },
      ["o_lamprey_bowl"]            = { 0,   -75, 0 },
      ["o_spice_rice"]              = { 0,   -75, 0 },
      ["o_bowl_meat_sml"]           = { 0,   -85, 0 },
      ["o_netch_jelly"]             = { -10,  -35, 0 },
      ["o_netch_jelly_bowl"]        = { -10,  -35, 0 },
      ["o_rice_porridge"]           = { -15,  -35, 0 },
      ["o_cp_broth"]                = { -35,  -50, 0 },
      ["o_ml_gulash"]               = { -35,  -65, 0 },
      ["o_tp_bonemeal_stew"]        = { -35,  -35, 0 },

      -- Soups                         Th    Hu   Ex
      ["o_bgsoup_a"]                = { -150, -125, 0 },
      ["o_bgsoup_b"]                = { -150, -125, 0 },
      ["o_ml_soupshroom"]           = { -150, -125, 0 },
      ["o_muschroom_soup"]          = { -150, -125, 0 },
      ["o_tlv_insect_soup"]         = { -150, -125, 0 },
      ["o_tlv_lumi_soup"]           = { -150,  -50, 0 },
      ["o_bowl_soup_sml"]           = {  -75,  -50, 0 },
      ["o_bowl_soup2_sml"]          = {  -75,  -50, 0 },
      ["o_tlv_insect_soup_small"]   = {  -75,  -50, 0 },
      ["o_fishsoup_sml"]            = {  -75,  -75, 0 },
      ["o_wd_soup"]                 = { -100,  -75, 0 },
      ["o_wd_soup2"]                = { -100,  -75, 0 },
      ["o_marrow_stew"]             = {  -50, -100, 0 },

      -- Big Caloric Dishes            Th    Hu    Ex
      ["o_ingred_slaughtfish_roast"]      = { 0,   -300, 0 },
      ["o_tlv_baked_truffles"]            = { 0,   -250, 0 },
      ["o_6th_steak"]                     = { 0,   -300, 0 },
      ["o_ml_fish_rice"]                  = { 0,   -300, 0 },
      ["o_fish_stew_bittergreen"]         = { 0,   -300, 0 },
      ["o_yammeat"]                       = { 0,   -300, 0 },
      ["o_ml_comberry_fish"]              = { -15, -300, 0 },
      ["o_ml_crabstew_mt"]                = { -75, -275, 0 },
      ["o_ml_meatrice"]                   = { 0,   -300, 0 },
      ["o_mushroom_rat_stew"]             = { -75, -275, 0 },
      ["o_ml_scuttlesoup"]                = { -75, -275, 0 },
      ["o_ml_yamscut"]                    = { 0,   -300, 0 },
      ["o_ml_meatash"]                    = { 0,   -300, 0 },
      ["o_ml_crab_stew"]                  = { -50, -225, 0 },
      ["o_ml_ash_roast"]                  = { 0,   -300, 0 },
      ["o_ml_fish_ashyam"]                = { 0,   -300, 0 },
      ["o_ml_fish_ash_yam_bittergreen"]   = { 0,   -300, 0 },
      ["o_ml_kwama_meat_roast"]           = { 0,   -300, 0 },
      ["o_ml_ash_yam_stew"]               = { 0,   -300, 0 },
      ["o_ml_meatrice_mt"]                = { 0,   -300, 0 },

      -- Ribs                          Th   Hu    Ex
      ["o_drumstick_bucket"]         = { 0, -375, 0 },
      ["o_ingred_guar_ribs_raw"]     = { 0, -400, 0 },
      ["o_ingred_guar_ribs_roasted"] = { 0, -400, 0 },
      ["o_ingred_roasted_scrib"]     = { 0, -400, 0 },
      ["o_ml_b_anther_meat"]         = { 0, -400, 0 },
      ["o_ml_roasted_scrib"]         = { 0, -400, 0 },
      ["o_ml_guar_ribs_ash_yam"]     = { 0, -400, 0 },
      ["o_tlv_spore_ribs"]           = { 0, -400, 0 },
      ["o_ribs_spicy"]               = { 0, -400, 0 },
      ["o_guar_ribs_beans"]          = { 0, -400, 0 },
      ["o_6th_ribs"]                 = { 0, -400, 0 },
      ["o_ml_guar_ribs_bread"]       = { 0, -400, 0 },

      -- Feasts                        Th   Hu    Ex
      ["o_feast_kwama_roast"]        = { 0, -500, 0 },
      ["o_tp_ml_coda_roast"]         = { 0, -450, 0 },
      ["o_6th_corprust_feast"]       = { 0, -475, 0 },

      -- Drinks                        Th    Hu  Ex
      ["o_tea_bittergreen"]          = { -150, 0, 0 },
      ["o_tea_bittergreen_p"]        = { -150, 0, 0 },
      ["o_tea_bittergreen_s"]        = { -150, 0, 0 },
      ["o_tea_firefern"]             = { -150, 0, 0 },
      ["o_tea_goldenkanet"]          = { -150, 0, 0 },
      ["o_tea_goldkanet_s"]          = { -150, 0, 0 },
      ["o_tea_kanet_milk"]           = { -175, 0, 0 },
      ["o_tea_kresh"]                = { -150, 0, 0 },
      ["o_tea_kresh_peach"]          = { -150, 0, 0 },
      ["o_tea_scathecraw_y"]         = { -150, 0, 0 },
      ["o_tea_swamp"]                = { -150, 0, -35 },
      ["o_cp_juc_cberry"]            = { -150, 0, 0 },
      ["o_juice_comberry"]           = { -150, 0, 0 },
   },
}
