local defaultConfig = {
    harvestEnabled = true,
    harvestKey = {keyCode = tes3.scanCode.h, isShiftDown = false, isAltDown = false, isControlDown = false},
    toggleMod = {keyCode = tes3.scanCode.p, isShiftDown = false, isAltDown = false, isControlDown = false},
    blacklistKey = {keyCode = tes3.scanCode.b, isShiftDown = false, isAltDown = false, isControlDown = false},
    harvestDistance = 2,
    harvestTime = 10,
    ingredient = true,
    waitHarvest = false,
    AHContainerBL = {
        ["barrel_01_ahnassi_drink"] = true,
        ["barrel_01_ahnassi_food"] = true,
        ["com_chest_02_mg_supply"] = true,
        ["com_chest_02_fg_supply"] = true,
        ["t_mwcom_furn_ch2fguild"] = true,
        ["t_mwcom_furn_ch2mguild"] = true,
        ["tr_com_sack_02_i501_mry"] = true,
        ["tr_i3-295-de_p_drinks"] = true,
        ["tr_i3-672_de_rm_deskalc"] = true,
        ["tr_m2_com_sack_i501_bg"] = true,
        ["tr_m2_com_sack_i501_sl"] = true,
        ["tr_m2_com_sack_i501_ww"] = true,
        ["tr_m2_q_27_fgchest"] = true,
        ["tr_m2_q_29_fgchest"] = true,
        ["tr_m3_i395_sack_local1"] = true,
        ["tr_m3_ingchest_i3-390-i"] = true,
        ["tr_m3_oe_anjzhirra_sack"] = true,
        ["tr_m3_soil_i3-390-ind"] = true,
        ["rock_adam_py09"] = true,
        ["rock_diamond_01"] = true,
        ["rock_diamond_02"] = true,
        ["rock_diamond_03"] = true,
        ["rock_diamond_04"] = true,
        ["rock_diamond_05"] = true,
        ["rock_diamond_06"] = true,
        ["rock_diamond_07"] = true,
        ["rock_ebony_01"] = true,
        ["rock_ebony_02"] = true,
        ["rock_ebony_03"] = true,
        ["rock_ebony_04"] = true,
        ["rock_ebony_05"] = true,
        ["rock_ebony_06"] = true,
        ["rock_ebony_07"] = true,
        ["rock_glass_01"] = true,
        ["rock_glass_02"] = true,
        ["rock_glass_03"] = true,
        ["rock_glass_04"] = true,
        ["rock_glass_05"] = true,
        ["rock_glass_06"] = true,
        ["rock_glass_07"] = true,
    },
}

local mwseConfig = mwse.loadConfig("Krimson.Auto Harvest", defaultConfig)

return mwseConfig