return {
    ", berber",
    ", black",
    ", blue squares",
    ", blue",
    ", brown & white",
    ", brown",
    ", cable blue",
    ", cable",
    ", dark brown",
    ", diamonds",
    ", fisherman",
    ", gold",
    ", gray",
    ", green diamonds",
    ", green",
    ", green",
    ", khaki",
    ", lt",
    ", orange",
    ", red & green",
    ", red",
    ", rust",
    ", stripes",
    ", tan",
    ", white",
    "black",
    "blue",
    "brown",
    "fur",
    "gold",
    "gray",
    "green",
    "long",
    "multi",
    "pink",
    "rust",
    "short",
    "suede",
    "tan",
    "wine",
    "long johns",
}