local defaultConfig = {
	Version = "REEEE v2",
	itemChance = 1,
	itemList = {
"0s_sc_argentglow",
"0s_sc_azarath",
"0s_sc_bloodfire",
"0s_sc_celerity",
"0s_sc_corrosion",
"0s_sc_darkstorm",
"0s_sc_daynarsairybubble",
"0s_sc_elementalburstfire",
"0s_sc_elementalburstfrost",
"0s_sc_elementalburstshock",
"0s_sc_evasion",
"0s_sc_folms",
"0s_sc_friction",
"0s_sc_galbedir",
"0s_sc_gamblersprayer",
"0s_sc_insight",
"0s_sc_janand",
"0s_sc_jovren",
"0s_sc_light",
"0s_sc_llervi",
"0s_sc_motion",
"0s_sc_ondres",
"0s_sc_ondusisunhinging",
"0s_sc_perpetrate",
"0s_sc_purify",
"0s_sc_rebound",
"0s_sc_restoration",
"0s_sc_spirit_of_sai",
"0s_sc_teldryn",
"0s_sc_traction",
"0s_sc_uvaren",
"0s_sc_valyne",
"0s_sc_vigor",
"0s_sc_vitality",
"0s_sc_paper_F",
"0s_sc_paper_H",
"0s_sc_paper_M",
"0s_sc_paper_wF",
"0s_sc_paper_wH",
"0s_sc_paper_wM",
"sc_daydenespanacea",
"sc_almsiviintervention",
"sc_divineintervention",
"sc_mark",
"amulet of almsivi intervention",
"amulet of balyna's antidote",
"amulet of frost",
"amulet of health",
"amulet of mighty blows",
"amulet of opening",
"amulet of shield",
"amulet of stamina",
"balm amulet",
"belt of balyna's soothing balm",
"belt of charisma",
"belt of feet of notorgo",
"belt of fortitude",
"belt of nimbleness",
"belt of orc's strength",
"belt of wisdom",
"0s_ring_light_10",
"0s_ring_lv_10",
"0s_ring_minor_heal",
"0s_ring_wb_10",
"0s_ring_ww_10",
"Misc_SoulGem_Lesser",
"Misc_SoulGem_Common",
"Misc_SoulGem_Petty"}
}

local config = mwse.loadConfig ("REEEE", defaultConfig)
return config