local M = {
    regionModifiers = {
        very_hot = 160,
        hot = 90,
        warm = 40,
        neutral = 0,
        chilly = -60,
        cold = -110,
        very_cold = -160,
    },
    -- Indoor base temperature multiplier by detected region category.
    -- Applied to the exterior region signed temperature (base + seasonal + time-of-day)
    -- before interior cell-type modifiers.
    -- Example: 0.70 = 70% of outside, 1.20 = 120% of outside.
    interiorBaseByRegion = {
        very_hot = 0.65,
        hot = 0.45,
        warm = 0.45,
        neutral = 0.0,
        chilly = 0.65,
        cold = 0.30,
        very_cold = 0.30,
    },
    -- Signed temperature modifier by detected cell type.
    -- Positive values warm the player, negative values cool the player.
    cellTypeModifiers = {
        neutralToScorching = {
            exterior = 0,
            interior = 0,
            volcanic = 110,
            cave = -15,
            ice_cave = -45,
            mine = 0,
            dwemer = 20,
            daedric = 30,
            tomb = 10,
            house = -10,
            castle = -20,
            mushroom = -10,
            hlaalu = -10,
            redoran = -20,
            sewer = -20,
            temple = -10,
        },
        chillyToFreezing = {
            exterior = 0,
            interior = 0,
            volcanic = 110,
            cave = -15,
            ice_cave = -45,
            mine = 10,
            dwemer = 10,
            daedric = 20,
            tomb = -10,
            house = 10,
            castle = 0,
            mushroom = 10,
            hlaalu = 10,
            redoran = 10,
            sewer = -20,
            temple = 10,
        },
    },
    campfire = {
        -- Base campfire warmth by detected climate category.
        warmthByRegion = {
            very_hot = 30,
            hot = 30,
            warm = 40,
            neutral = 40,
            chilly = 60,
            cold = 80,
            very_cold = 120,
        },
        -- Interiors with positive cell-type modifier receive only half campfire warmth.
        interiorPositiveCellTypeMultiplier = 0.5,
        -- Campfire scan defaults.
        defaultRadius = 500,
        temperatureModReference = 8,
        sourceCacheRescanSeconds = 0.5,
        -- How often player.lua requests refreshed cell heat-source info from the global script.
        cellInfoRequestIntervalSeconds = 0.5,
        falloff = {
            innerRadiusUnits = 300,
            fireInnerRadiusUnits = 100,
            fireInteriorRadiusUnits = 700,
            exponent = 3,
        },
        -- Multiplier applied to temperature tick progression while near an active heat source
        -- and the player is warming up (toward a higher target temperature).
        temperatureTickMultiplierWhenNearSource = 5.0,
    },
    seasonalRegionOffsets = {
        winter = {
            very_hot = -20,
            hot = -20,
            warm = -20,
            neutral = -40,
            chilly = -35,
            cold = -35,
            very_cold = -45,
        },
        spring = {
            very_hot = 0,
            hot = 0,
            warm = 0,
            neutral = 0,
            chilly = 0,
            cold = 0,
            very_cold = 0,
        },
        summer = {
            very_hot = 40,
            hot = 40,
            warm = 30,
            neutral = 15,
            chilly = 20,
            cold = 0,
            very_cold = 0,
        },
        autumn = {
            very_hot = 0,
            hot = 0,
            warm = 0,
            neutral = 0,
            chilly = 0,
            cold = 0,
            very_cold = 0,
        },
    },
    seasonalTimeOfDayRegionOffsets = {
        winter = {
            morning = {
                very_hot = -70,
                hot = -45,
                warm = -40,
                neutral = -35,
                chilly = -45,
                cold = -55,
                very_cold = -80,
            },
            evening = {
                very_hot = -80,
                hot = -55,
                warm = -50,
                neutral = -45,
                chilly = -55,
                cold = -65,
                very_cold = -90,
            },
            night = {
                very_hot = -120,
                hot = -90,
                warm = -90,
                neutral = -90,
                chilly = -105,
                cold = -120,
                very_cold = -120,
            },
        },
        spring = {
            morning = {
                very_hot = -45,
                hot = -25,
                warm = -15,
                neutral = -10,
                chilly = -25,
                cold = -35,
                very_cold = -60,
            },
            evening = {
                very_hot = -35,
                hot = -25,
                warm = -20,
                neutral = -15,
                chilly = -25,
                cold = -35,
                very_cold = -55,
            },
            night = {
                very_hot = -75,
                hot = -55,
                warm = -45,
                neutral = -35,
                chilly = -55,
                cold = -75,
                very_cold = -100,
            },
        },
        summer = {
            morning = {
                very_hot = -20,
                hot = -10,
                warm = -5,
                neutral = 0,
                chilly = -10,
                cold = -20,
                very_cold = -35,
            },
            evening = {
                very_hot = -25,
                hot = -15,
                warm = -10,
                neutral = -5,
                chilly = -15,
                cold = -25,
                very_cold = -40,
            },
            night = {
                very_hot = -60,
                hot = -45,
                warm = -40,
                neutral = -30,
                chilly = -45,
                cold = -60,
                very_cold = -80,
            },
        },
        autumn = {
            morning = {
                very_hot = -55,
                hot = -30,
                warm = -25,
                neutral = -20,
                chilly = -35,
                cold = -45,
                very_cold = -70,
            },
            evening = {
                very_hot = -45,
                hot = -30,
                warm = -30,
                neutral = -25,
                chilly = -35,
                cold = -45,
                very_cold = -70,
            },
            night = {
                very_hot = -90,
                hot = -65,
                warm = -55,
                neutral = -45,
                chilly = -70,
                cold = -90,
                very_cold = -90,
            },
        },
    },
    weatherModifiers = {
        foggy = -20,
        overcast = -10,
        rain = -35,
        thunder = -45,
        snow = -150,
        blizzard = -220,
        ash_storm = 90,
        blight = 90,
    },
    weathermultiplier = {
        -- Multiplies temperature tick progression after entering a configured weather.
        -- multiplier now ends when temperature reaches the initial target, not after a timer.
        multiplier = 2.5,
    },
    interiorRegionmultiplier = {
        -- Applies indoors only, when direction matches region:
        -- chilly/cold/very_cold while warming, warm/hot/very_hot while cooling.
        multiplier = 4.0,
    },
    regionTransition = {
        -- Real-time seconds to hold the previous exterior region contribution
        -- before applying the new region contribution in one step.
        delayTransitionTime = 30,
    },
    modifierPipeline = {
        -- How often heavy modifier state is rebuilt while the player is in steady state.
        -- Lower values are more responsive but cost more CPU time.
        refreshIntervalSeconds = 0.25,
        -- How often full temperature simulation work runs in player update.
        -- Uses accumulated elapsed time, so temperature progression remains consistent.
        temperatureUpdateIntervalSeconds = 0.5,
    },
    system = {
        min = -400,
        max = 400,
        tickSeconds = 0.04 * 60 * 60,
        tickDivisor = 40,
        -- Caps how many ticks are applied per update while a multiplier multiplier (>1) is active.
        -- This prevents multiplier from collapsing many ticks into a single instant temperature jump.
        multiplierMaxTicksPerAdvance = 1,
        tickMinStep = 2,
        tickSnapThreshold = 1,
    },
    -- Stage threshold multipliers by race.
    -- Values above 1.0 require more temperature to reach harsher stages on that side.
    -- Values below 1.0 require less temperature to reach harsher stages on that side.
    racialAbilities = {
        default = {
            heatStageMultiplier = 1.0,
            coldStageMultiplier = 1.0,
        },
        dark_elf = {
            heatStageMultiplier = 1.15,
            coldStageMultiplier = 0.90,
        },
        nord = {
            heatStageMultiplier = 0.95,
            coldStageMultiplier = 1.15,
        },
        argonian = {
            heatStageMultiplier = 1.25,
            coldStageMultiplier = 0.75,
        },
        khajiit = {
            heatStageMultiplier = 1.10,
            coldStageMultiplier = 1.0,
        },
        orc = {
            heatStageMultiplier = 1.0,
            coldStageMultiplier = 1.15,
        },
    },
    wellHydrated = {
        -- Multiplies total target temperature while Well Hydrated is active.
        -- Only applies when the final target temperature is above zero.
        positiveHeatTargetMultiplier = 0.85,
    },
    stageThresholds = {
        freezing = { min = -400, max = -301 },
        very_cold = { min = -300, max = -201 },
        cold = { min = -200, max = -101 },
        chilly = { min = -100, max = -26 },
        neutral = { min = -25, max = 40 },
        warm = { min = 41, max = 100 },
        hot = { min = 101, max = 200 },
        very_hot = { min = 201, max = 300 },
        scorching = { min = 301, max = 400 },
    },
    clothingWarmth = {
        default = 5,
        robe = 25,
        glovesOrShoes = 2.5,
        belt = 0,
    },
    robeWarmthByRegion = {
        very_hot = 20,
        hot = 20,
        warm = 20,
        neutral = 25,
        chilly = 25,
        cold = 30,
        very_cold = 45,
    },
    robeArmorWarmthMultiplierByRegion = {
        very_hot = 0.50,
        hot = 0.50,
        warm = 0.50,
        neutral = 0.50,
        chilly = 1.0,
        cold = 1.0,
        very_cold = 1.0,
    },
    robeMediumArmorWarmthMultiplierByRegion = {
        very_hot = 0.25,
        hot = 0.25,
        warm = 0.25,
        neutral = 0.25,
        chilly = 1.0,
        cold = 1.0,
        very_cold = 1.0,
    },
    interiorArmorWarmthMultiplierByRegion = {
        very_hot = 0.5,
        hot = 0.5,
        warm = 0.5,
        neutral = 0.6,
        chilly = 1.0,
        cold = 1.0,
        very_cold = 1.0,
    },
    armorWarmthByRegion = {
        heavy = {
            very_hot = {
                cuirass = 25,
                helmet = 15,
                greaves = 25,
                boots = 15,
                gauntlet = 7.5,
                pauldron = 10,
            },
            hot = {
                cuirass = 25,
                helmet = 15,
                greaves = 25,
                boots = 15,
                gauntlet = 7.5,
                pauldron = 10,
            },
            warm = {
                cuirass = 25,
                helmet = 15,
                greaves = 25,
                boots = 15,
                gauntlet = 7.5,
                pauldron = 10,
            },
            neutral = {
                cuirass = 20,
                helmet = 15,
                greaves = 20,
                boots = 15,
                gauntlet = 5,
                pauldron = 10,
            },
            chilly = {
                cuirass = 5,
                helmet = 3.5,
                greaves = 5,
                boots = 3.5,
                gauntlet = 1.5,
                pauldron = 2.5,
            },
            cold = {
                cuirass = 5,
                helmet = 3.5,
                greaves = 5,
                boots = 3.5,
                gauntlet = 1.5,
                pauldron = 2.5,
            },
            very_cold = {
                cuirass = 5,
                helmet = 3.5,
                greaves = 5,
                boots = 3.5,
                gauntlet = 1.5,
                pauldron = 2.5,
            },
        },
        light = {
            very_hot = {
                cuirass = 10,
                helmet = 4,
                greaves = 10,
                boots = 4,
                gauntlet = 1.5,
                pauldron = 3,
            },
            hot = {
                cuirass = 10,
                helmet = 4,
                greaves = 10,
                boots = 4,
                gauntlet = 1.5,
                pauldron = 3,
            },
            warm = {
                cuirass = 10,
                helmet = 4,
                greaves = 10,
                boots = 4,
                gauntlet = 1.5,
                pauldron = 3,
            },
            neutral = {
                cuirass = 10,
                helmet = 4,
                greaves = 10,
                boots = 4,
                gauntlet = 1.5,
                pauldron = 3,
            },
            chilly = {
                cuirass = 12,
                helmet = 6,
                greaves = 12,
                boots = 6,
                gauntlet = 3,
                pauldron = 6,
            },
            cold = {
                cuirass = 12,
                helmet = 6,
                greaves = 12,
                boots = 6,
                gauntlet = 3,
                pauldron = 6,
            },
            very_cold = {
                cuirass = 12,
                helmet = 6,
                greaves = 12,
                boots = 6,
                gauntlet = 3,
                pauldron = 6,
            },
        },
        medium = {
            very_hot = {
                cuirass = 10,
                helmet = 8,
                greaves = 10,
                boots = 8,
                gauntlet = 5,
                pauldron = 10,
            },
            hot = {
                cuirass = 15,
                helmet = 10,
                greaves = 15,
                boots = 10,
                gauntlet = 5,
                pauldron = 10,
            },
            warm = {
                cuirass = 15,
                helmet = 10,
                greaves = 15,
                boots = 10,
                gauntlet = 5,
                pauldron = 10,
            },
            neutral = {
                cuirass = 15,
                helmet = 10,
                greaves = 15,
                boots = 10,
                gauntlet = 5,
                pauldron = 10,
            },
            chilly = {
                cuirass = 5,
                helmet = 3.5,
                greaves = 5,
                boots = 3.5,
                gauntlet = 1.5,
                pauldron = 2.5,
            },
            cold = {
                cuirass = 5,
                helmet = 3.5,
                greaves = 5,
                boots = 3.5,
                gauntlet = 1.5,
                pauldron = 2.5,
            },
            very_cold = {
                cuirass = 5,
                helmet = 3.5,
                greaves = 5,
                boots = 3.5,
                gauntlet = 1.5,
                pauldron = 2.5,
            },
        },
    },
}

return M
