--function getStuff()
-- array of display misc items
--local MiscDisplays = {

return{
  --=-=-=-=-  Daedric 
["tw_dae_arrow_act"     ] = { item = "daedric arrow"            , name = "Daedric Arrow"             , Info = "The Daedric Arrow is a rare arrow in Vvardenfell that is best use with the Daedric Long Bow." },
["tw_dae_battle_act"    ] = { item = "daedric battle axe"       , name = "Daedric Battle Axe"        , Info = "" },
["tw_helm_clavic_act"   ] = { item = "daedric_helm_clavicusvile", name = "Daedric Helm Clavicusvile" , Info = "" },
["tw_dae_claymore_act"  ] = { item = "daedric claymore"         , name = "Daedric Claymore"          , Info = "" },
["tw_dae_club_act"      ] = { item = "daedric club"             , name = "Daedric Club"              , Info = "" },
["tw_dae_crescent_act"  ] = { item = "daedric_crescent_unique"  , name = "Daedric_Crescent"          , Info = "" },
["tw_dae_dagger_act"    ] = { item = "daedric dagger"           , name = "Daedric Dagger"            , Info = "" },
["tw_dae_daikatana_act" ] = { item = "daedric dai-katana"       , name = "Daedric Dai-Katana"        , Info = "" },
["tw_dae_dart_act"      ] = { item = "daedric dart"             , name = "Daedric Dart"              , Info = "" },
["tw_helm_god_act"      ] = { item = "daedric_god_helm"         , name = "Daedric God Helm"          , Info = "" },
["tw_helm_inspire_act"  ] = { item = "daedric_fountain_helm"    , name = "Daedric Inspiration Helm"  , Info = "" },
["tw_dae_katana_act"    ] = { item = "daedric katana"           , name = "Daedric Katana"            , Info = "" },
["tw_dae_longbow_act"   ] = { item = "daedric long bow"         , name = "Daedric Long Bow"          , Info = "" },
["tw_dae_longsword_act" ] = { item = "daedric longsword"        , name = "Daedric Longsword"         , Info = "" },
["tw_dae_mace_act"      ] = { item = "daedric mace"             , name = "Daedric Mace"              , Info = "" },
["tw_dae_shield_act"    ] = { item = "daedric_towershield"      , name = "Daedric Towershield"       , Info = "" },
["tw_dae_spear_act"     ] = { item = "daedric spear"            , name = "Daedric Spear"             , Info = "" },
["tw_dae_staff_act"     ] = { item = "Daedric Staff"            , name = "Daedric Staff"             , Info = "" },
["tw_helm_terror_act"   ] = { item = "daedric_terrifying_helm"  , name = "Daedric Terrifying Helm"   , Info = "" },
["tw_dae_wakizashi_act" ] = { item = "daedric wakizashi"        , name = "Daedric Wakizashi"         , Info = "" },
["tw_dae_waraxe_act"    ] = { item = "daedric war axe"          , name = "Daedric War Axe"           , Info = "" },
["tw_dae_warhammer_act" ] = { item = "daedric warhammer"        , name = "Daedric Warhammer"         , Info = "" },
--=-=-=-=-  Dwemer
["tw_dwr_shield_act"     ] = { item = "dwemer_shield"           , name = "Dwarven Shield"          , Info = "" },  
["tw_dwrv_airship_act"   ] = { item = "misc_dwrv_artifact20"    , name = "Dwarven Airship Plans"   , Info = "" },  
["tw_dwrv_anumidum_act"  ] = { item = "misc_dwrv_artifact30"    , name = "Dwarven Anumidum"        , Info = "" },  
["tw_dwr_battle_act"     ] = { item = "dwarven battle axe"      , name = "Dwarven Battle Axe"      , Info = "" },  
["tw_dwrv_bowl_act"      ] = { item = "misc_dwrv_bowl00"        , name = "Dwarven Bow"             , Info = "" },  
["tw_dwrv_centurion_act" ] = { item = "misc_dwrv_artifact80"    , name = "Dwarven Centurion Plans" , Info = "" },  
["tw_dwrv_coherer_act"   ] = { item = "misc_dwrv_artifact50"    , name = "Dwarven Coherer"         , Info = "" },  
["tw_dwr_claymore_act"   ] = { item = "dwarven claymore"        , name = "Dwarven Claymore"        , Info = "" },  
["tw_dwrv_cylinder_act"  ] = { item = "misc_dwrv_artifact00"    , name = "Dwarven Cylinder"        , Info = "" },  
["tw_dwrv_gear_act"      ] = { item = "misc_dwrv_gear00"        , name = "Dwarven Rusty Gear"      , Info = "" },  
["tw_dwrv_goblet1_act"   ] = { item = "misc_dwrv_goblet10"      , name = "Dwarven Goblet"          , Info = "" },  
["tw_dwrv_goblet_act"    ] = { item = "misc_dwrv_goblet00"      , name = "Dwarven Goblet"          , Info = "" },  
["tw_dwr_halbeard_act"   ] = { item = "dwarven halberd"         , name = "Dwarven Halberd"         , Info = "" },  
["tw_dwr_mace_act"       ] = { item = "dwarven mace"            , name = "Dwarven Mace"            , Info = "" },  
["tw_dwrv_mug_act"       ] = { item = "misc_dwrv_mug00"         , name = "Dwarven Mug"             , Info = "" },  
["tw_dwrv_pitcher_act"   ] = { item = "misc_dwrv_pitcher00"     , name = "Dwarven Pitcher"         , Info = "" },  
["tw_dwrv_scarab_act"    ] = { item = "misc_dwrv_artifact10"    , name = "Dwarven Scarab Plans"    , Info = "" },  
["tw_dwrv_scarabs_act"   ] = { item = "misc_dwrv_artifact40"    , name = "Dwarven Scarab Plans"    , Info = "" },  
["tw_dwrv_schema_act"    ] = { item = "misc_dwrv_artifact70"    , name = "Dwarven Schema Plans"    , Info = "" },  
["tw_dwr_scrap_act"      ] = { item = "ingred_scrap_metal_01"   , name = "Dwarven Scrap Metal"     , Info = "" },  
["tw_dwr_shortsword_act" ] = { item = "dwarven shortsword"      , name = "Dwarven Shortsword"      , Info = "" },  
["tw_dwr_spear_act"      ] = { item = "dwarven spear"           , name = "Dwarven Spear"           , Info = "" },  
["tw_dwrv_tube_act"      ] = { item = "misc_dwrv_artifact60"    , name = "Dwarven Tube"            , Info = "" },  
["tw_dwr_waraxe_act"     ] = { item = "dwarven war axe"         , name = "Dwarven War Axe"         , Info = "" },  
["tw_dwr_warhammer_act"  ] = { item = "dwarven warhammer"       , name = "Dwarven Warhammer"       , Info = "" },  
--=-=-=-=-  Grasslands
["tw_guar_act"          ] = { item = "ingred_guar_hide_01"      , name = "Guar"         , Info = "" },
["tw_alit_act"          ] = { item = "ingred_alit_hide_01"      , name = "Alit"         , Info = "" },
["tw_kagouti_act"       ] = { item = "ingred_kagouti_hide_01"   , name = "Kagouti"      , Info = "" },
["tw_cliffracer_act"    ] = { item = "ingred_racer_plumes_01"   , name = "Cliff Racer"  , Info = "" },
["tw_shalk_act"         ] = { item = "ingred_shalk_resin_01"    , name = "Shalk"        , Info = "" },
--=-=-=-=-  Solstheim   Leave the Raven and Snowman there all the time.    
["tw_horker_act"        ] = { item = "ingred_horker_tusk_01"       , name = "Horker"       , Info = "" },
["tw_snowbear_act"      ] = { item = "ingred_snowbear_pelt_unique" , name = "Snow Bear"    , Info = "" },
["tw_wolfsnow_act"      ] = { item = "ingred_snowwolf_pelt_unique" , name = "Snow Wolf"    , Info = "" },
["tw_spriggan_act"      ] = { item = "ingred_heartwood_01"         , name = "Spriggan"     , Info = "" },
["tw_frostboar_act"     ] = { item = "ingred_boar_leather"         , name = "Frost Boar"   , Info = "" },
--=-=-=-=-  
["tw_atronach_frost_act"  ] = { item = "ingred_frost_salts_01"   , name = "Frost Atronach"   , Info = "" },
["tw_atronach_flame_act"  ] = { item = "ingred_fire_salts_01"    , name = "Flame Atronach"   , Info = "" },
["tw_atronach_storm_act"  ] = { item = "ingred_void_salts_01"    , name = "Storm Atronach"   , Info = "" },
["tw_skeleton_act"        ] = { item = "ingred_bonemeal_01"      , name = "Skeleton"         , Info = "" },
["tw_scrib_act"           ] = { item = "ingred_scrib_jerky_01"   , name = "Scrib"            , Info = "" },
["tw_scamp_act"           ] = { item = "ingred_scamp_skin_01"    , name = "Scamp"            , Info = "" },
["tw_rat_act"             ] = { item = "ingred_rat_meat_01"      , name = "Rat"              , Info = "" },
["tw_ogrim_act"           ] = { item = "ingred_daedras_heart_01" , name = "Ogrim"            , Info = "" },
["tw_kwama forager_act"   ] = { item = "ingred_kwama_cuttle_01"  , name = "Kwama Forager"    , Info = "" },
--=-=-=-=-  Ebony
["tw_ebony staff_act"            ] = { item = "ebony staff"          , name = "Ebony Staff"         , Info = "" },
["tw_ebony_mace_act"             ] = { item = "ebony mace"           , name = "Ebony Mace"          , Info = "" },
["tw_ebony war axe_act"          ] = { item = "ebony war axe"        , name = "Ebony War Axe"       , Info = "" },
["tw_ebony spear_act"            ] = { item = "ebony spear"          , name = "Ebony Spear"         , Info = "" },
["tw_ebony dart_act"             ] = { item = "ebony dart"           , name = "Ebony Dart"          , Info = "" },
["tw_ebonythrowingstar_act"      ] = { item = "ebony throwing star"  , name = "Ebony Throwing Star" , Info = "" },
["tw_ebony shortsword_act"       ] = { item = "ebony shortsword"     , name = "Ebony Shortsword"    , Info = "" },
["tw_ebony longsword_act"        ] = { item = "ebony longsword"      , name = "Ebony Longsword"     , Info = "" },
["tw_ebony broadsword_act"       ] = { item = "ebony broadsword"     , name = "Ebony Broadsword"    , Info = "" },
["tw_ebony scimitar_act"         ] = { item = "Ebony Scimitar"       , name = "Ebony Scimitar"      , Info = "" },
["tw_ebony arrow_act"            ] = { item = "ebony arrow"          , name = "Ebony Arrow"         , Info = "" },
["tw_ebony_bow_auriel_act"       ] = { item = "ebony_bow_auriel"     , name = "Auriel's Bow"        , Info = "" },
["tw_ebony_shield_auriel_act"    ] = { item = "ebony_shield_auriel"  , name = "Auriel's Shield"     , Info = "" },
["tw_ebony_dagger_mehrunes_act"  ] = { item = "ebony_dagger_mehrunes", name = "Mehrune's Razor"     , Info = "" },
["tw_eleidon_unique_act"         ] = { item = "towershield_eleidon_unique_x", name = "Eleidon's Ward", Info = "" },
--=-=-=-=-  Glass
["tw_glass war axe_act"          ] = { item = "glass war axe"        , name = "Glass War Axe"        , Info = "" },
["tw_glass halberd_act"          ] = { item = "glass halberd"        , name = "Glass Halberd"        , Info = "" },
["tw_glass dagger_act"           ] = { item = "glass dagger"         , name = "Glass Dagger"         , Info = "" },
["tw_glassthrowingknife_act"     ] = { item = "glass throwing knife" , name = "Glass Throwing Knife" , Info = "" },
["tw_glassthrowingstar_act"      ] = { item = "glass throwing star"  , name = "Glass Throwing Star"  , Info = "" },
["tw_glass longsword_act"        ] = { item = "glass longsword"      , name = "Glass Longsword"      , Info = "" },
["tw_glass arrow_act"            ] = { item = "glass arrow"          , name = "Glass Arrow"          , Info = "" },
["tw_glass staff_act"            ] = { item = "glass staff"          , name = "Glass Staff"          , Info = "" },
["tw_glass claymore_act"         ] = { item = "glass claymore"       , name = "Glass Claymore"       , Info = "" },
["tw_glass_dagger_enamor_act"    ] = { item = "glass_dagger_enamor"  , name = "Enamor"               , Info = "" },
--=-=-=-=-  Silver
["tw_silver longsword_act"      ] = { item = "silver longsword"     , name = "Silver Longsword"     , Info = "" },
["tw_silver claymore_act"       ] = { item = "silver claymore"      , name = "Silver Claymore"      , Info = "" },
["tw_silver staff_act"          ] = { item = "silver staff"         , name = "Silver Staff"         , Info = "" },  
["tw_silver spear_act"          ] = { item = "silver spear"         , name = "Silver Spear"         , Info = "" },
["tw_silver dagger_act"         ] = { item = "silver dagger"        , name = "Silver Dagger"        , Info = "" },
["tw_silver dart_act"           ] = { item = "silver dart"          , name = "Silver Dart"          , Info = "" },
["tw_silver throwing star_act"  ] = { item = "silver throwing star" , name = "Silver Throwing Star" , Info = "" },
["tw_silver shortsword_act"     ] = { item = "silver shortsword"    , name = "Silver Shortsword"    , Info = "" },
["tw_silver war axe_act"        ] = { item = "silver war axe"       , name = "Silver War Axe"       , Info = "" },
--=-=-=-=-  Adamantium 
["tw_adamantium_mace_act"        ] = { item = "adamantium_mace"       , name = "Adamantium Mace"       , Info = "" },
["tw_adamantium_claymore_act"    ] = { item = "adamantium_claymore"   , name = "Adamantium Claymore"   , Info = "" },
["tw_adamantium_shortsword_act"  ] = { item = "adamantium_shortsword" , name = "Adamantium Shortsword" , Info = "" },
["tw_adamantium_spear_act"       ] = { item = "adamantium_spear"      , name = "Adamantium Spear"      , Info = "" },
["tw_adamantium_axe_act"         ] = { item = "adamantium_axe"        , name = "Admantium Axe"         , Info = "" },
-- Wall displays
--["tw_bearhead_brown"     ] = { item = "ingred_bear_pelt" , name = "Brown Bearhead"   , Info = "" },
--["tw_bearhead_red"       ] = { item = "ingred_bear_pelt" , name = "Red Bearhead"     , Info = "" },
--["tw_wolfhead_black"     ] = { item = "ingred_wolf_pelt" , name = "Black Wolfhead"   , Info = "" },
--["tw_wolfhead_red"       ] = { item = "ingred_wolf_pelt" , name = "Red Wolfhead"     , Info = "" },
--=-=-=-=-  Nordic
["tw_nordic silver dagger_act"      ] = { item = "BM nordic silver dagger"      , name = "Nordic Silver Dagger"    , Info = "" },
["tw_nordic silver shortsword_act"  ] = { item = "BM nordic silver shortsword"  , name = "Nordic Silver Shortsword", Info = "" },
["tw_nordic silver longsword_act"   ] = { item = "BM nordic silver longsword"   , name = "Nordic Silver Longsword" , Info = "" },
["tw_nordic silver claymore_act"    ] = { item = "BM nordic silver claymore"    , name = "Nordic Silver Claymore"  , Info = "" },
["tw_nordic silver mace_act"        ] = { item = "BM nordic silver mace"        , name = "Nordic Silver Mace"      , Info = "" },
["tw_nordic silver axe_act"         ] = { item = "BM nordic silver axe"         , name = "Nordic Silver Axe"       , Info = "" },
["tw_nordic silver battleaxe_act"   ] = { item = "BM nordic silver battleaxe"   , name = "Nordic Silver Battleaxe" , Info = "" },
["tw_nordic battle axe_act"         ] = { item = "nordic battle axe"            , name = "Nordic Battle Axe"       , Info = "" },
["tw_nordic claymore_act"           ] = { item = "nordic claymore"              , name = "Nordic Claymore"         , Info = "" },  
["tw_nordic broadsword_act"         ] = { item = "nordic broadsword"            , name = "Nordic Broadsword"       , Info = "" },
--=-=-=-=-  ice
["tw_ice mace_act"            ] = { item = "BM ice mace"               , name = "Stalhrim Mace"       , Info = "" },
["tw_ice longsword_act"       ] = { item = "BM ice longsword"          , name = "Stalhrim Longsword"  , Info = "" },
["tw_ice dagger_act"          ] = { item = "BM ice dagger"             , name = "Stalhrim Dagger"     , Info = "" },
["tw_ice war axe_act"         ] = { item = "BM ice war axe"            , name = "Stalhrim War Axe"    , Info = "" },
--=-=-=-=-  iron
["tw_iron war axe_act"       ] = { item = "iron war axe"          , name = "Iron War Axe"       , Info = "" },
["tw_iron warhammer_act"     ] = { item = "iron warhammer"        , name = "Iron Warhammer"     , Info = "" },
["tw_iron mace_act"          ] = { item = "iron mace"             , name = "Iron Mace"          , Info = "" },
["tw_iron battle axe_act"    ] = { item = "iron battle axe"       , name = "Iron Battle Axe"    , Info = "" },
["tw_iron club_act"          ] = { item = "iron club"             , name = "Iron Club"          , Info = "" },
["tw_iron spear_act"         ] = { item = "iron spear"            , name = "Iron Spear"         , Info = "" },
["tw_iron halberd_act"       ] = { item = "iron halberd"          , name = "Iron Halberd"       , Info = "" },
["tw_iron longsword_act"     ] = { item = "iron longsword"        , name = "Iron Longsword"     , Info = "" },
["tw_iron claymore_act"      ] = { item = "iron claymore"         , name = "Iron Claymore"      , Info = "" },
["tw_iron broadsword_act"    ] = { item = "iron broadsword"       , name = "Iron Broadsword"    , Info = "" },
["tw_iron dagger_act"        ] = { item = "iron dagger"           , name = "Iron Dagger"        , Info = "" },
["tw_iron throwing knife_act"] = { item = "iron throwing knife"   , name = "Iron Throwing Knife", Info = "" },
["tw_iron wakizashi_act"     ] = { item = "iron wakizashi"        , name = "Iron Wakizashi"     , Info = "" },
["tw_iron tanto_act"         ] = { item = "iron tanto"            , name = "Iron Tanto"         , Info = "" },
--=-=-=-=-  steel
["tw_steel halberd_act"      ] = { item = "steel halberd"         , name = "Steel Halberd"      , Info = "" },
["tw_steel spear_act"        ] = { item = "steel spear"           , name = "Steel Spear"        , Info = "" },
["tw_steel staff_act"        ] = { item = "steel staff"           , name = "Steel Staff"        , Info = "" },
["tw_steel dart_act"         ] = { item = "steel dart"            , name = "Steel Dart"         , Info = "" },
["tw_steel war axe_act"      ] = { item = "steel war axe"         , name = "Steel War Axe"      , Info = "" },
["tw_steel warhammer_act"    ] = { item = "steel warhammer"       , name = "Steel Warhammer"    , Info = "" },
["tw_steel club_act"         ] = { item = "steel club"            , name = "Steel Club"         , Info = "" },
["tw_steel battle axe_act"   ] = { item = "steel battle axe"      , name = "Steel Battle Axe"   , Info = "" },
["tw_steel mace_act"         ] = { item = "steel mace"            , name = "Steel Mace"         , Info = "" },
["tw_steel broadsword_act"   ] = { item = "steel broadsword"      , name = "Steel Broadsword"   , Info = "" },
["tw_steel claymore_act"     ] = { item = "steel claymore"        , name = "Steel Claymore"     , Info = "" },
["tw_steel longsword_act"    ] = { item = "steel longsword"       , name = "Steel Longsword"    , Info = "" },
["tw_steel saber_act"        ] = { item = "steel saber"           , name = "Steel Saber"        , Info = "" },
["tw_steel longbow_act"      ] = { item = "steel longbow"         , name = "Steel Longbow"      , Info = "" },
["tw_steel wakizashi_act"    ] = { item = "steel wakizashi"       , name = "Steel Wakizashi"    , Info = "" },
["tw_steel katana_act"       ] = { item = "steel katana"          , name = "Steel Katana"       , Info = "" },
["tw_steel dai-katana_act"   ] = { item = "steel dai-katana"      , name = "Steel Dai-katana"   , Info = "" },
["tw_steel throwingstar_act" ] = { item = "steel throwing star"   , name = "Steel Throwing Star", Info = "" },
["tw_steel tanto_act"        ] = { item = "steel tanto"           , name = "Steel Tanto"        , Info = "" },
["tw_steel dagger_act"       ] = { item = "steel dagger"          , name = "Steel Dagger"       , Info = "" },
--=-=-=-=-  Artefacts
["tw_keening_act"                 ] = { item = "keening"                         , name = "Keening"                    , Info = "" },
["tw_sunder_act"                  ] = { item = "sunder"                          , name = "Sunder"                     , info = "" },
["tw_wraithguard_act"             ] = { item = "wraithguard"                     , name = "Wraithguard"                , Info = "" },
["tw_artifact_bittercup_act"      ] = { item = "artifact_bittercup_01"           , name = "Bittercup"                  , Info = "" },
["tw_staff of magnus_act"         ] = { item = "staff_magnus_unique"             , name = "Staff of Magnus"            , Info = "" },
["tw_bloodworm_helm_act"          ] = { item = "bloodworm_helm_unique"           , name = "Bloodworm Helm"             , Info = "" },
["tw_helm_bearclaw_act"           ] = { item = "helm_bearclaw_unique"            , name = "Helm of Oreyn Bearclaw"     , Info = "" },
["tw_imperial_helm_frald_act"     ] = { item = "imperial_helm_frald_uniq"        , name = "Helm of Graff the White"    , Info = "" },
["tw_sword of almalexia_act"      ] = { item = "Sword of Almalexia"              , name = "Hopesfire"                  , Info = "" },
["tw_nerevarblade_flame_act"      ] = { item = "nerevarblade_01_flame"           , name = "Trueflame"                  , Info = "" },
["tw_cleaverstfelms_act"          ] = { item = "cleaverstfelms"                  , name = "Cleaver of St. Felms"       , Info = "" },
["tw_daedric_scourge_act"         ] = { item = "daedric_scourge_unique"          , name = "Scourge"                    , Info = "" },
["tw_mace_aevar_act"              ] = { item = "BM_Mace_Aevar_UNI"               , name = "Mace of Aevar Stone-Singer" , Info = "" },
["tw_mace of slurring_act"        ] = { item = "Mace of Slurring"                , name = "Mace of Slurring"           , Info = "" },
["tw_mace of molag bal_act"       ] = { item = "mace of molag bal_unique"        , name = "Mace of Molag Bal"          , Info = "" },
["tw_warhammer_crusher_act"       ] = { item = "warhammer_crusher_unique"        , name = "Skull Crusher"              , Info = "" },
["tw_spear_mercy_act"             ] = { item = "spear_mercy_unique"              , name = "Spear of Bitter Mercy"      , Info = "" },
["tw_stendar_hammer_act"          ] = { item = "stendar_hammer_unique"           , name = "Stendarr's Hammer"          , Info = "" },
["tw_crosierstllothis_act"        ] = { item = "crosierstllothis"                , name = "Crosier of St. Llothis"     , Info = "" },
["tw_staff_hasedoki_act"          ] = { item = "staff_hasedoki_unique"           , name = "Staff of Hasedoki"          , Info = "" },
["tw_hammer_volendrung_act"       ] = { item = "dwarven_hammer_volendrung"       , name = "Volendrung"                 , Info = "" },
["tw_hunterspear_act"             ] = { item = "BM_hunterspear_unique"           , name = "Spear of the Hunter"        , Info = "" },
["tw_warhammer_ttgd_act"          ] = { item = "daedric warhammer_ttgd"          , name = "Veloth's Judgement"         , Info = "" },
["tw_bloodska_act"                ] = { item = "BM_nordic_silver_lgswd_bloodska" , name = "Bloodskal"                  , Info = "" },
["tw_bipolar blade_act"           ] = { item = "Bipolar Blade"                   , name = "BiPolar Blade"              , Info = "" },
["tw_claymore_chrysamere_act"     ] = { item = "claymore_chrysamere_unique"      , name = "Chrysamere"                 , Info = "" },
["tw_longsword_umbra_act"         ] = { item = "longsword_umbra_unique"          , name = "Umbra Sword"                , Info = "" },
["tw_claymore_iceblade_act"       ] = { item = "claymore_iceblade_unique"        , name = "Ice Blade of the Monarch"   , Info = "" },
["tw_katana_goldbrand_act"        ] = { item = "katana_goldbrand_unique"         , name = "Goldbrand"                  , Info = "" },
["tw_spell_breaker_act"           ] = { item = "spell_breaker_unique"            , name = "Spell Breaker"              , info = "" },
--=-=-=-=- Jewlery
["tw_moon_and_star_act"           ] = { item = "moon_and_star"                   , name = "Moon-and-Sta"               , Info = "" },
["tw_ring_vampiric_act"           ] = { item = "ring_vampiric_unique"            , name = "Vampiric Ring"              , Info = "" },
["tw_ring_shashev_act"            ] = { item = "ring_shashev_unique"             , name = "Shashev's Ring"             , Info = "" },
["tw_ring_khajiit_act"            ] = { item = "ring_khajiit_unique"             , name = "Ring of Khajiit"            , Info = "" },
["tw_ring_phynaster_act"          ] = { item = "ring_phynaster_unique"           , name = "Ring of Phynaster"          , Info = "" },
["tw_ring_surrounding_act"        ] = { item = "ring_surrounding_unique"         , name = "Ring of Surroundings"       , Info = "" },
["tw_ring_blackjinx_act"          ] = { item = "ring_blackjinx_uniq"             , name = "Black Jinx"                 , Info = "" },
["tw_necromancers_amulet_act"     ] = { item = "necromancers_amulet_uniq"        , name = "Necromancer's Amulet"       , Info = "" },
["tw_amulet_unity_act"            ] = { item = "amulet_unity_uniq"               , name = "Amulet of Unity"            , Info = "" },
["tw_amulet of ashamanu_act"      ] = { item = "amulet of ashamanu (unique)"     , name = "Amulet of Ashamanu"         , Info = "" },
["tw_amulet_skink_act"            ] = { item = "amulet_skink_unique"             , name = "Skink's Amulet"             , Info = "" },
["tw_amuletfleshmadewhole_act"    ] = { item = "amuletfleshmadewhole_uniq"       , name = "Amulet of Flesh Made Whole" , Info = "" },
["tw_hlervu_locket_act"           ] = { item = "hlervu_locket_unique"            , name = "Hlervu Locket"              , Info = "" },
["tw_amulet_agustas_act"          ] = { item = "amulet_Agustas_unique"           , name = "Augustus' Amulet"           , Info = "" },
["tw_teeth_act"                   ] = { item = "teeth"                           , name = "Teeth of the Urshilaku"     , Info = "" },
["tw_ring_wind_act"               ] = { item = "ring_wind_unique"                , name = "Ring of the Wind"           , Info = "" },
["tw_ring_hircine_act"            ] = { item = "BM_ring_hircine"                 , name = "Hircine's Ring"             , Info = "" },
["tw_ring_dahrkmezalf_act"        ] = { item = "ring_dahrkmezalf_uniq"           , name = "Ring of Dahrk Mezalf"       , Info = "" },
["tw_ring of telekinesis_act"     ] = { item = "ring of telekinesis_UNIQUE"      , name = "Ring of Far Reaching"       , Info = "" },
["tw_ring_equity_act"             ] = { item = "ring_equity_uniq"                , name = "Ring of Equity"             , Info = "" },
["tw_common_ring_05_act"          ] = { item = "common_ring_05_BM_UNI"           , name = "Common Ring"                , Info = "" },
["tw_ring_fathasa_act"            ] = { item = "ring_fathasa_unique"             , name = "Fathasa's Ring"             , Info = "" },
["tw_extravagant_ring_aund_act"   ] = { item = "extravagant_ring_aund_uni"       , name = "Aundae Signet Ring"         , Info = "" },
["tw_ring_mentor_act"             ] = { item = "ring_mentor_unique"              , name = "Mentor's Ring"              , Info = "" },
["tw_ring_marara_act"             ] = { item = "ring_marara_unique"              , name = "Marara's Ring"              , Info = "" },
["tw_ring_denstagmer_act"         ] = { item = "ring_denstagmer_unique"          , name = "Denstagmer's Ring"          , Info = "" },
["tw_ring_warlock_act"            ] = { item = "ring_warlock_unique"             , name = "Warlock's Ring"             , Info = "" },
--=-=-=-=- Bonemold/Chitin
["tw_bonemold_longbow.act"  ] = { item = "bonemold long bow"    , name = "Bonemold Long Bow"    , Info = "" },
["tw_bonemold arrow_act"    ] = { item = "bonemold arrow"       , name = "Bonemold Arrow"       , Info = "" },
["tw_chitin spear_act"      ] = { item = "chitin spear"         , name = "Chitin Spear"         , Info = "" },
["tw_chitin short bow_act"  ] = { item = "chitin short bow"     , name = "Chitin Short Bow"     , Info = "" },
["tw_chitin arrow_act"      ] = { item = "chitin arrow"         , name = "Chitin Arrow"         , Info = "" },
["tw_chitin dagger_act"     ] = { item = "chitin dagger"        , name = "Chitin Dagger"        , Info = "" },
["tw_chitinstar_act"        ] = { item = "chitin throwing star" , name = "Chitin Throwing Star" , Info = "" },
["tw_chitin shortsword_act" ] = { item = "chitin shortsword"    , name = "Chitin Shortsword"    , Info = "" },
["tw_chitin club_act"       ] = { item = "chitin club"          , name = "Chitin Club"          , Info = "" },
["tw_chitin war axe_act"    ] = { item = "chitin war axe"       , name = "Chitin War Axe"       , Info = "" },
-- Requires extra plugins !!!
["tw_akavirshield_act"      ] = { item = "Ward of Akavir"       , name = "Dragonscale Ward of Akavir" , Info = "" },
["tw_adamantium_helm_act"   ] = { item = "helm_tohan_unique"    , name = "Adamantium Helm of Tohan"   , Info = "" },
-- todo
--[""   ] = { item = ""    , name = ""   , Info = "" },
}
--[[
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
["" ] = { item = "" , name = "" , Info = "" },
--]]


--return MiscDisplays
--end