return {
    "short",
    "long",
    "red",
    "chain",
    "with stockings",
    "black",
    "witch",
    "sorceress",
    "freya",
    "violet",
    "white",
    "black",
    "dancer",
    "dark desires",
    "ether",
    "mabrigash",
    "janus",
    "volliandrium",
    "cyrodiilic",
    "crimson",
    "gold",
    "jade",
    "indigo",
    "dark",
    "princess armor",
    "ceremonial armor",
    "clematis",
    "sphinx",
}