local core = require("openmw.core")
local T = require("openmw.types")

local attributes = core.stats.Attribute.records
local effectTypes = core.magic.EFFECT_TYPE
local enchantTypes = core.magic.ENCHANTMENT_TYPE
local rangeTypes = core.magic.RANGE

return {
    {
        id = "burden-self-target-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.Burden,
                range = rangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 300, 400, 500, 600 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Burden,
                range = rangeTypes.Target,
                area = { false, 20, 30, 40, 50 },
                min = { false, 100, 200, 300, 400 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "drainSpeed-self-target-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Target,
                area = { false, 20, 30, 40, 50 },
                min = { false, 10, 20, 30, 40 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "blind-self-target-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.Blind,
                range = rangeTypes.Self,
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Blind,
                range = rangeTypes.Target,
                area = { false, 20, 30, 40, 50 },
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "fortifySpeed-sanctuary-blind-sound-self-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Sanctuary,
                range = rangeTypes.Self,
                min = { false, 10, 15, 20, 25 },
                max = { false, 15, 20, 25, 30 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Blind,
                range = rangeTypes.Self,
                min = { false, 40, 50, 60, 70 },
                max = { false, 50, 60, 70, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Sound,
                range = rangeTypes.Self,
                min = { false, 25, 30, 35, 40 },
                max = { false, 35, 40, 45, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFire,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFrost,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToShock,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToMagicka,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "levitate-light-fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnUse,
        cost = 20,
        charge = 100,
        effects = {
            {
                id = effectTypes.Levitate,
                range = rangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.Light,
                range = rangeTypes.Self,
                min = { false, 5, 10, 15, 20 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { 200, 200, 200, 200, 200 },
                max = { 200, 200, 200, 200, 200 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToFire,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToFrost,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToShock,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToMagicka,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "fortifyStrength-drainAgility-weaknesses-self-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.strength.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFire,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFrost,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToShock,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToMagicka,
                range = rangeTypes.Touch,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "damagehealth-self-touch-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.DamageHealth,
                range = rangeTypes.Touch,
                min = { false, 8, 16, 24, 32 },
                max = { false, 20, 40, 60, 80 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DamageHealth,
                range = rangeTypes.Self,
                min = { false, 2, 4, 6, 8 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
}
