local this = {}

this.components = {
    tes3.objectType.alchemy,
}

this.spoiledPotionsAltNames = {
    ["p_drain willpower_q"] = "Spoiled Potion",
    ["p_drain_agility_q"] = "Spoiled Potion",
    ["p_drain_endurance_q"] = "Spoiled Potion",
    ["p_drain_intelligence_q"] = "Spoiled Potion",
    ["p_drain_luck_q"] = "Spoiled Potion",
    ["p_drain_magicka_q"] = "Spoiled Potion",
    ["p_drain_personality_q"] = "Spoiled Potion",
    ["p_drain_speed_q"] = "Spoiled Potion",
    ["p_drain_strength_q"] = "Spoiled Potion",
}

this.baseNames = {}

this.baseNames[tes3.objectType.alchemy] = {
    ["p_burden_b"] = "Slowfall, Bargain",
    ["p_burden_c"] = "Slowfall, Cheap",
    ["p_burden_e"] = "Slowfall, Special",
    ["p_burden_q"] = "Slowfall, Quality",
    ["p_burden_s"] = "Slowfall, Normal",
    ["p_chameleon_b"] = "Resist Blight, Bargain",
    ["p_chameleon_c"] = "Resist Blight, Cheap",
    ["p_chameleon_e"] = "Resist Blight, Special",
    ["p_chameleon_q"] = "Resist Blight, Quality",
    ["p_chameleon_s"] = "Resist Blight, Normal",
    ["p_cure_paralyzation_s"] = "Resist Paralysis, Normal",
    ["p_drain willpower_q"] = "Spoiled Potion",
    ["p_drain_agility_q"] = "Spoiled Potion",
    ["p_drain_endurance_q"] = "Spoiled Potion",
    ["p_drain_intelligence_q"] = "Spoiled Potion",
    ["p_drain_luck_q"] = "Spoiled Potion",
    ["p_drain_magicka_q"] = "Spoiled Potion",
    ["p_drain_personality_q"] = "Spoiled Potion",
    ["p_drain_speed_q"] = "Spoiled Potion",
    ["p_drain_strength_q"] = "Spoiled Potion",
    ["p_fortify_attack_e"] = "Fortify Attack, Special",
    ["p_fortify_intelligence_b"] = "Shield, Bargain",
    ["p_fortify_intelligence_c"] = "Shield, Cheap",
    ["p_fortify_intelligence_e"] = "Shield, Special",
    ["p_fortify_intelligence_q"] = "Shield, Quality",
    ["p_fortify_intelligence_s"] = "Shield, Normal",
    ["p_fortify_luck_b"] = "Sanctuary, Bargain",
    ["p_fortify_luck_c"] = "Sanctuary, Cheap",
    ["p_fortify_luck_e"] = "Sanctuary, Special",
    ["p_fortify_luck_q"] = "Sanctuary, Quality",
    ["p_fortify_luck_s"] = "Sanctuary, Normal",
    ["p_invisibility_b"] = "Resist Paralysis, Bargain",
    ["p_invisibility_c"] = "Resist Paralysis, Cheap",
    ["p_invisibility_e"] = "Resist Paralysis, Special",
    ["p_invisibility_q"] = "Resist Paralysis, Quality",
    ["p_invisibility_s"] = "Invisibility",
    ["p_light_b"] = "Fortify Attack, Bargain",
    ["p_light_c"] = "Fortify Attack, Cheap",
    ["p_light_e"] = "Fortify Attack, Special",
    ["p_light_q"] = "Fortify Attack, Quality",
    ["p_light_s"] = "Fortify Attack, Normal",
    ["p_paralyze_b"] = "Water Walking, Bargain",
    ["p_paralyze_c"] = "Water Walking, Cheap",
    ["p_paralyze_e"] = "Water Walking, Special",
    ["p_paralyze_q"] = "Water Walking, Quality",
    ["p_paralyze_s"] = "Feather, Normal",
    ["p_recall_s"] = "Divine Intervention",
    ["p_silence_b"] = "Water Breathing, Bargain",
    ["p_silence_c"] = "Water Breathing, Cheap",
    ["p_silence_e"] = "Water Breathing, Special",
    ["p_silence_q"] = "Water Breathing, Quality",
    ["p_silence_s"] = "Swift Swim, Normal",
    ["p_slowfall_s"] = "Recall",
    ["p_water_breathing_s"] = "Water Breathing, Normal",
    ["p_water_walking_s"] = "Water Walking, Normal",
}

return this