local data = {}
data.pfx = "AHelp:"
data.effects = {{name = "Absorb Acrobatics", id = 89, skl = 20},
                {name = "Absorb Agility", id = 85, atr = 3},
                {name = "Absorb Alchemy", id = 89, skl = 16},
                {name = "Absorb Alteration", id = 89, skl = 11},
                {name = "Absorb Armorer", id = 89, skl = 1},
                {name = "Absorb Athletics", id = 89, skl = 8},
                {name = "Absorb Axe", id = 89, skl = 6},
                {name = "Absorb Block", id = 89, skl = 0},
                {name = "Absorb Blunt Weapon", id = 89, skl = 4},
                {name = "Absorb Conjuration", id = 89, skl = 13},
                {name = "Absorb Destruction", id = 89, skl = 10},
                {name = "Absorb Enchant", id = 89, skl = 9},
                {name = "Absorb Endurance", id = 85, atr = 5},
                {name = "Absorb Fatigue", id = 88},
                {name = "Absorb Hand to Hand", id = 89, skl = 26},
                {name = "Absorb Health", id = 86},
                {name = "Absorb Heavy Armor", id = 89, skl = 3},
                {name = "Absorb Illusion", id = 89, skl = 12},
                {name = "Absorb Intelligence", id = 85, atr = 1},
                {name = "Absorb Light Armor", id = 89, skl = 21},
                {name = "Absorb Long Blade", id = 89, skl = 5},
                {name = "Absorb Luck", id = 85, atr = 7},
                {name = "Absorb Magicka", id = 87},
                {name = "Absorb Marksman", id = 89, skl = 23},
                {name = "Absorb Medium Armor", id = 89, skl = 2},
                {name = "Absorb Mercantile", id = 89, skl = 24},
                {name = "Absorb Mysticism", id = 89, skl = 14},
                {name = "Absorb Personality", id = 85, atr = 6},
                {name = "Absorb Restoration", id = 89, skl = 15},
                {name = "Absorb Security", id = 89, skl = 18},
                {name = "Absorb Short Blade", id = 89, skl = 22},
                {name = "Absorb Sneak", id = 89, skl = 19},
                {name = "Absorb Spear", id = 89, skl = 7},
                {name = "Absorb Speechcraft", id = 89, skl = 25},
                {name = "Absorb Speed", id = 85, atr = 4},
                {name = "Absorb Strength", id = 85, atr = 0},
                {name = "Absorb Unarmored", id = 89, skl = 17},
                {name = "Absorb Willpower", id = 85, atr = 2},
                {name = "Almsivi Intervention", id = 63},
                {name = "Blind", id = 47},
                {name = "Bound BattleAxe", id = 123},
                {name = "Bound Boots", id = 129},
                {name = "Bound Cuirass", id = 127},
                {name = "Bound Dagger", id = 120},
                {name = "Bound Gloves", id = 131},
                {name = "Bound Helm", id = 128},
                {name = "Bound Longbow", id = 125},
                {name = "Bound Longsword", id = 121},
                {name = "Bound Mace", id = 122},
                {name = "Bound Shield", id = 130},
                {name = "Bound Spear", id = 124},
                {name = "Burden", id = 7},
                {name = "Call Bear", id = 139},
                {name = "Call Wolf", id = 138},
                {name = "Calm Creature", id = 50},
                {name = "Calm Humanoid", id = 49},
                {name = "Chameleon", id = 40},
                {name = "Charm", id = 44},
                {name = "Command Creature", id = 118},
                {name = "Command Humanoid", id = 119},
                {name = "Corprus", id = 132},
                {name = "Cure Blight Disease", id = 70},
                {name = "Cure Common Disease", id = 69},
                {name = "Cure Corprus Disease", id = 71},
                {name = "Cure Paralyzation", id = 73},
                {name = "Cure Poison", id = 72},
                {name = "Damage Acrobatics", id = 26, skl = 20},
                {name = "Damage Agility", id = 22, atr = 3},
                {name = "Damage Alchemy", id = 26, skl = 16},
                {name = "Damage Alteration", id = 26, skl = 11},
                {name = "Damage Armorer", id = 26, skl = 1},
                {name = "Damage Athletics", id = 26, skl = 8},
                {name = "Damage Axe", id = 26, skl = 6},
                {name = "Damage Block", id = 26, skl = 0},
                {name = "Damage Blunt Weapon", id = 26, skl = 4},
                {name = "Damage Conjuration", id = 26, skl = 13},
                {name = "Damage Destruction", id = 26, skl = 10},
                {name = "Damage Enchant", id = 26, skl = 9},
                {name = "Damage Endurance", id = 22, atr = 5},
                {name = "Damage Fatigue", id = 25},
                {name = "Damage Hand to Hand", id = 26, skl = 26},
                {name = "Damage Health", id = 23},
                {name = "Damage Heavy Armor", id = 26, skl = 3},
                {name = "Damage Illusion", id = 26, skl = 12},
                {name = "Damage Intelligence", id = 22, atr = 1},
                {name = "Damage Light Armor", id = 26, skl = 21},
                {name = "Damage Long Blade", id = 26, skl = 5},
                {name = "Damage Luck", id = 22, atr = 7},
                {name = "Damage Magicka", id = 24},
                {name = "Damage Marksman", id = 26, skl = 23},
                {name = "Damage Medium Armor", id = 26, skl = 2},
                {name = "Damage Mercantile", id = 26, skl = 24},
                {name = "Damage Mysticism", id = 26, skl = 14},
                {name = "Damage Personality", id = 22, atr = 6},
                {name = "Damage Restoration", id = 26, skl = 15},
                {name = "Damage Security", id = 26, skl = 18},
                {name = "Damage Short Blade", id = 26, skl = 22},
                {name = "Damage Sneak", id = 26, skl = 19},
                {name = "Damage Spear", id = 26, skl = 7},
                {name = "Damage Speechcraft", id = 26, skl = 25},
                {name = "Damage Speed", id = 22, atr = 4},
                {name = "Damage Strength", id = 22, atr = 0},
                {name = "Damage Unarmored", id = 26, skl = 17},
                {name = "Damage Willpower", id = 22, atr = 2},
                {name = "Demoralize Creature", id = 54},
                {name = "Demoralize Humanoid", id = 53},
                {name = "Detect Animal", id = 64},
                {name = "Detect Enchantment", id = 65},
                {name = "Detect Key", id = 66},
                {name = "Disintegrate Armor", id = 38},
                {name = "Disintegrate Weapon", id = 37},
                {name = "Dispel", id = 57},
                {name = "Divine Intervention", id = 62},
                {name = "Drain Acrobatics", id = 21, skl = 20},
                {name = "Drain Agility", id = 17, atr = 3},
                {name = "Drain Alchemy", id = 21, skl = 16},
                {name = "Drain Alteration", id = 21, skl = 11},
                {name = "Drain Armorer", id = 21, skl = 1},
                {name = "Drain Athletics", id = 21, skl = 8},
                {name = "Drain Axe", id = 21, skl = 6},
                {name = "Drain Block", id = 21, skl = 0},
                {name = "Drain Blunt Weapon", id = 21, skl = 4},
                {name = "Drain Conjuration", id = 21, skl = 13},
                {name = "Drain Destruction", id = 21, skl = 10},
                {name = "Drain Enchant", id = 21, skl = 9},
                {name = "Drain Endurance", id = 17, atr = 5},
                {name = "Drain Fatigue", id = 20},
                {name = "Drain Hand to Hand", id = 21, skl = 26},
                {name = "Drain Health", id = 18},
                {name = "Drain Heavy Armor", id = 21, skl = 3},
                {name = "Drain Illusion", id = 21, skl = 12},
                {name = "Drain Intelligence", id = 17, atr = 1},
                {name = "Drain Light Armor", id = 21, skl = 21},
                {name = "Drain Long Blade", id = 21, skl = 5},
                {name = "Drain Luck", id = 17, atr = 7},
                {name = "Drain Luck", id = 17, atr = 7},
                {name = "Drain Magicka", id = 19},
                {name = "Drain Marksman", id = 21, skl = 23},
                {name = "Drain Medium Armor", id = 21, skl = 2},
                {name = "Drain Mercantile", id = 21, skl = 24},
                {name = "Drain Mysticism", id = 21, skl = 14},
                {name = "Drain Personality", id = 17, atr = 6},
                {name = "Drain Restoration", id = 21, skl = 15},
                {name = "Drain Security", id = 21, skl = 18},
                {name = "Drain Short Blade", id = 21, skl = 22},
                {name = "Drain Sneak", id = 21, skl = 19},
                {name = "Drain Spear", id = 21, skl = 7},
                {name = "Drain Speechcraft", id = 21, skl = 25},
                {name = "Drain Speed", id = 17, atr = 4},
                {name = "Drain Strength", id = 17, atr = 0},
                {name = "Drain Unarmored", id = 21, skl = 17},
                {name = "Drain Willpower", id = 17, atr = 2},
                {name = "Feather", id = 8},
                {name = "Fire Damage", id = 14},
                {name = "Fire Shield", id = 4},
                {name = "Fortify Acrobatics", id = 83, skl = 20},
                {name = "Fortify Agility", id = 79, atr = 3},
                {name = "Fortify Alchemy", id = 83, skl = 16},
                {name = "Fortify Alteration", id = 83, skl = 11},
                {name = "Fortify Armorer", id = 83, skl = 1},
                {name = "Fortify Athletics", id = 83, skl = 8},
                {name = "Fortify Attack", id = 117},
                {name = "Fortify Axe", id = 83, skl = 6},
                {name = "Fortify Block", id = 83, skl = 0},
                {name = "Fortify Blunt Weapon", id = 83, skl = 4},
                {name = "Fortify Conjuration", id = 83, skl = 13},
                {name = "Fortify Destruction", id = 83, skl = 10},
                {name = "Fortify Enchant", id = 83, skl = 9},
                {name = "Fortify Endurance", id = 79, atr = 5},
                {name = "Fortify Fatigue", id = 82},
                {name = "Fortify Hand to Hand", id = 83, skl = 26},
                {name = "Fortify Health", id = 80},
                {name = "Fortify Heavy Armor", id = 83, skl = 3},
                {name = "Fortify Illusion", id = 83, skl = 12},
                {name = "Fortify Intelligence", id = 79, atr = 1},
                {name = "Fortify Light Armor", id = 83, skl = 21},
                {name = "Fortify Long Blade", id = 83, skl = 5},
                {name = "Fortify Luck", id = 79, atr = 7},
                {name = "Fortify Magicka", id = 81},
                {name = "Fortify Marksman", id = 83, skl = 23},
                {name = "Fortify MaximumMagicka", id = 84},
                {name = "Fortify Medium Armor", id = 83, skl = 2},
                {name = "Fortify Mercantile", id = 83, skl = 24},
                {name = "Fortify Mysticism", id = 83, skl = 14},
                {name = "Fortify Personality", id = 79, atr = 6},
                {name = "Fortify Restoration", id = 83, skl = 15},
                {name = "Fortify Security", id = 83, skl = 18},
                {name = "Fortify Short Blade", id = 83, skl = 22},
                {name = "Fortify Sneak", id = 83, skl = 19},
                {name = "Fortify Spear", id = 83, skl = 7},
                {name = "Fortify Speechcraft", id = 83, skl = 25},
                {name = "Fortify Speed", id = 79, atr = 4},
                {name = "Fortify Strength", id = 79, atr = 0},
                {name = "Fortify Unarmored", id = 83, skl = 17},
                {name = "Fortify Willpower", id = 79, atr = 2},
                {name = "Frenzy Creature", id = 52},
                {name = "Frenzy Humanoid", id = 51},
                {name = "Frost Damage", id = 16},
                {name = "Frost Shield", id = 6},
                {name = "Invisibility", id = 39},
                {name = "Jump", id = 9},
                {name = "Levitate", id = 10},
                {name = "Light", id = 41},
                {name = "Lightning Shield", id = 5},
                {name = "Lock", id = 12},
                {name = "Mark", id = 60},
                {name = "NightEye", id = 43},
                {name = "Open", id = 13},
                {name = "Paralyze", id = 45},
                {name = "Poison", id = 27},
                {name = "Rally Creature", id = 56},
                {name = "Rally Humanoid", id = 55},
                {name = "Recall", id = 61},
                {name = "Reflect", id = 68},
                {name = "Remove Curse", id = 100},
                {name = "Resist Blight Disease", id = 95},
                {name = "Resist Common Disease", id = 94},
                {name = "Resist Corprus Disease", id = 96},
                {name = "Resist Fire", id = 90},
                {name = "Resist Frost", id = 91},
                {name = "Resist Magicka", id = 93},
                {name = "Resist Normal Weapons", id = 98},
                {name = "Resist Paralysis", id = 99},
                {name = "Resist Poison", id = 97},
                {name = "Resist Shock", id = 92},
                {name = "Restore Acrobatics", id = 78, skl = 20},
                {name = "Restore Agility", id = 74, atr = 3},
                {name = "Restore Alchemy", id = 78, skl = 16},
                {name = "Restore Alteration", id = 78, skl = 11},
                {name = "Restore Armorer", id = 78, skl = 1},
                {name = "Restore Athletics", id = 78, skl = 8},
                {name = "Restore Axe", id = 78, skl = 6},
                {name = "Restore Block", id = 78, skl = 0},
                {name = "Restore Blunt Weapon", id = 78, skl = 4},
                {name = "Restore Conjuration", id = 78, skl = 13},
                {name = "Restore Destruction", id = 78, skl = 10},
                {name = "Restore Enchant", id = 78, skl = 9},
                {name = "Restore Endurance", id = 74, atr = 5},
                {name = "Restore Fatigue", id = 77},
                {name = "Restore Hand to Hand", id = 78, skl = 26},
                {name = "Restore Health", id = 75},
                {name = "Restore Heavy Armor", id = 78, skl = 3},
                {name = "Restore Illusion", id = 78, skl = 12},
                {name = "Restore Intelligence", id = 74, atr = 1},
                {name = "Restore Light Armor", id = 78, skl = 21},
                {name = "Restore Long Blade", id = 78, skl = 5},
                {name = "Restore Luck", id = 74, atr = 7},
                {name = "Restore Magicka", id = 76},
                {name = "Restore Marksman", id = 78, skl = 23},
                {name = "Restore Medium Armor", id = 78, skl = 2},
                {name = "Restore Mercantile", id = 78, skl = 24},
                {name = "Restore Mysticism", id = 78, skl = 14},
                {name = "Restore Personality", id = 74, atr = 6},
                {name = "Restore Restoration", id = 78, skl = 15},
                {name = "Restore Security", id = 78, skl = 18},
                {name = "Restore Short Blade", id = 78, skl = 22},
                {name = "Restore Sneak", id = 78, skl = 19},
                {name = "Restore Spear", id = 78, skl = 7},
                {name = "Restore Speechcraft", id = 78, skl = 25},
                {name = "Restore Speed", id = 74, atr = 4},
                {name = "Restore Strength", id = 74, atr = 0},
                {name = "Restore Unarmored", id = 78, skl = 17},
                {name = "Restore Willpower", id = 74, atr = 2},
                {name = "Sanctuary", id = 42},
                {name = "sEffectSummonCreature04", id = 141},
                {name = "sEffectSummonCreature05", id = 142},
                {name = "Shield", id = 3},
                {name = "Shock Damage", id = 15},
                {name = "Silence", id = 46},
                {name = "Slow Fall", id = 11},
                {name = "Soultrap", id = 58},
                {name = "Sound", id = 48},
                {name = "Spell Absorption", id = 67},
                {name = "Stunted Magicka", id = 136},
                {name = "Summon AncestralGhost", id = 106},
                {name = "Summon Bonelord", id = 110},
                {name = "Summon Bonewalker", id = 108},
                {name = "Summon Bonewolf", id = 140},
                {name = "Summon Centurion Sphere", id = 134},
                {name = "Summon Clannfear", id = 103},
                {name = "Summon Daedroth", id = 104},
                {name = "Summon Dremora", id = 105},
                {name = "Summon Fabricant", id = 137},
                {name = "Summon FlameAtronach", id = 114},
                {name = "Summon FrostAtronach", id = 115},
                {name = "Summon GoldenSaint", id = 113},
                {name = "Summon GreaterBonewalker", id = 109},
                {name = "Summon Hunger", id = 112},
                {name = "Summon Scamp", id = 102},
                {name = "Summon SkeletalMinion", id = 107},
                {name = "Summon StormAtronach", id = 116},
                {name = "Summon WingedTwilight", id = 111},
                {name = "Sun Damage", id = 135},
                {name = "Swift Swim", id = 1},
                {name = "Telekinesis", id = 59},
                {name = "Turn Undead", id = 101},
                {name = "Vampirism", id = 133},
                {name = "Water Breathing", id = 0},
                {name = "Water Walking", id = 2},
                {name = "Weakness to Blight Disease", id = 33},
                {name = "Weakness to Common Disease", id = 32},
                {name = "Weakness to Corprus Disease", id = 34},
                {name = "Weakness to Fire", id = 28},
                {name = "Weakness to Frost", id = 29},
                {name = "Weakness to Magicka", id = 31},
                {name = "Weakness to Normal Weapons", id = 36},
                {name = "Weakness to Poison", id = 35},
                {name = "Weakness to Shock", id = 30}}

data.attrib = {{name = "Strength", id = 0},
               {name = "Intelligence", id = 1},
               {name = "Willpower", id = 2},
               {name = "Agility", id = 3},
               {name = "Speed", id = 4},
               {name = "Endurance", id = 5},
               {name = "Personality", id = 6},
               {name = "Luck", id = 7}}

data.skills = {{name = "Block", id = 0},
               {name = "Armorer", id = 1},
               {name = "Medium Armor", id = 2},
               {name = "Heavy Armor", id = 3},
               {name = "Blunt Weapon", id = 4},
               {name = "Long Blade", id = 5},
               {name = "Axe", id = 6},
               {name = "Spear", id = 7},
               {name = "Athletics", id = 8},
               {name = "Enchant", id = 9},
               {name = "Destruction", id = 10},
               {name = "Alteration", id = 11},
               {name = "Illusion", id = 12},
               {name = "Conjuration", id = 13},
               {name = "Mysticism", id = 14},
               {name = "Restoration", id = 15},
               {name = "Alchemy", id = 16},
               {name = "Unarmored", id = 17},
               {name = "Security", id = 18},
               {name = "Sneak", id = 19},
               {name = "Acrobatics", id = 20},
               {name = "Light Armor", id = 21},
               {name = "Short Blade", id = 22},
               {name = "Marksman", id = 23},
               {name = "Mercantile", id = 24},
               {name = "Speechcraft", id = 25},
               {name = "Hand to Hand", id = 26}}
return data
