local defaultConfig = {

	notify = false,
	width = 317,
	height = 127,
	minSize = true,
	alpha = 0.8,
	position = "bottom",
	msgTimer = false,
	msgTime = 10,
	msgLimit = true,
	maxMessages = 250,
	cellLog = true,
	dmgLog = false,
	hitLog = false,
	deathLog = false,
	resistLog = false,
	questLog = true,
	musicLog = false,
	musicPath = false,
	chatLog = false,
	showTopic = false,
	barterLog = true,
	buyLog = false,
	sellLog = false,
	dropLog = true,
	grabLog = false,
	castLog = false,
	cChanceLog = false,
	useLog = false,
	timeStamp = false,
	timeFormat = "%X",
	msgOffset = 2,
	titleText = "Message Box",
	highText = "ERROR",
	filterText = "@@@@",
	textRed = 1.00, -- Default Text Red (White)
	textGreen = 1.00, --Default Text Green
	textBlue = 1.00, --Default Text Blue
	highRed = 1.00, --Highlight Red (Magenta)
	highGreen = 0.00, --Highlight Green
	highBlue = 1.00, --Highlight Blue
	cellRed = 0.20, --Cell Change Red (Forest Green)
	cellGreen = 0.60, --Cell Change Green
	cellBlue = 0.20, --Cell Change Blue
	dmgRed = 0.80, --Damage Red (Red)
	dmgGreen = 0.40, --Damage Green
	dmgBlue = 0.40, --Damage Blue
	lastRed = 0.60, -- Choice Box Red (Grey)
	lastGreen = 0.60, --Choice Box Green
	lastBlue = 0.60, --Choice Box Blue
	dedRed = 1.00, --Death Red (Orangish)
	dedGreen = 0.60, --Death Green
	dedBlue = 0.00, --Death Blue
	resRed = 0.50, -- Resist Text Red (Purple)
	resGreen = 0.20, --Resist Text Green
	resBlue = 0.70, --Resist Text Blue
	musRed = 0.74, --Minty
	musGreen = 0.97,
	musBlue = 0.61,
	queRed = 0.30, --Neon Blue
	queGreen = 0.30,
	queBlue = 1.00,
	diaRed = 1.00,-- Yellow
	diaGreen = 1.00,
	diaBlue = 0.00,
	castRed = 0.53, --Baby Blue
	castGreen = 0.82,
	castBlue = 0.96,
	useRed = 0.53, --Baby Blue
	useGreen = 0.82,
	useBlue = 0.96,
	topRed = 0.59, --Answer Orange-Red
	topGreen = 0.20,
	topBlue = 0.12,
	hitRed = 1.00, --Pink
	hitGreen = 0.70,
	hitBlue = 0.80,
	cChanceRed = 0.00, --Cyan
	cChanceGreen = 1.00,
	cChanceBlue = 1.00,
	buyRed = 0.86, --Dark Gold
	buyGreen = 0.71,
	buyBlue = 0.35,
	sellRed = 0.89, --Light Gold
	sellGreen = 0.77,
	sellBlue = 0.48,
	grabRed = 0.73, --Choccy Milk
	grabGreen = 0.63,
	grabBlue = 0.53,
	dropRed = 0.59, --Mocha
	dropGreen = 0.49,
	dropBlue = 0.40,
	dtRed = 0.95, --Interop Colors--
	dtGreen = 0.66,--Daily Training (Peach)
	dtBlue = 0.36,
	clRed = 0.66, --Companion Leveler (Matte Purple)
	clGreen = 0.53,
	clBlue = 0.99,
	logLevel = "INFO",
	boxBind = {
		keyCode = tes3.scanCode.b
	},
}

local mwseConfig = mwse.loadConfig("Message Box", defaultConfig)

return mwseConfig;
