local data = {}

-- footprint statics keywords e.g. footPrint object ids examples:
-- 'ab01fpFootR', 'ab01fpBoot2L' (modPrefix+keyword+side)
data.fpStaTypes = {'anml','boot','boot2','foot','guar','hoof','mech','mech2','paw','puff','rat','rept','skel','taln'}

-- recognized creature lowercased meshes keywords
data.creStaTypes = {
['almalexia'] = 'foot',
['ashghoul'] = 'foot',
['ashvampire'] = 'foot',
['ashzombie'] = 'foot',
['atronach_fire'] = 'boot2',
['atronach_frost'] = 'boot',
['atronach_storm'] = 'boot',
['bear_black_larger'] = 'paw',
['bear_blond_larger'] = 'paw',
['bear_brown_larger'] = 'paw',
['bonewalker'] = 'foot',
['byagram'] = 'taln',
['cavemudcrab'] = 'taln',
['centurionspider'] = 'taln',
['clannfear'] = 'rept',
['clannfear_daddy'] = 'paw',
['corprus_stalker'] = 'foot',
['cr_draugr'] = 'boot2',
['daedroth'] = 'foot',
['dagothr'] = 'boot',
['draugrlord'] = 'boot2',
['dremora'] = 'boot2',
['durzog'] = 'rept',
['durzogcollar'] = 'rept',
['duskyalit'] = 'rept',
['fabricant'] = 'mech',
['fabricant_hulking'] = 'taln',
['fabricant_imperfect'] = 'boot',
['frostgiant'] = 'paw',
['goblin01'] = 'rept',
['goblin02'] = 'rept',
['goblin03'] = 'rept',
['golden saint'] = 'boot2',
['greatbonewalker'] = 'boot',
['guar'] = 'guar',
['guar_white'] = 'guar',
['guar_withpack'] = 'guar',
['hircine'] = 'boot',
['hircine_bear_larger'] = 'paw',
['hircinewolf'] = 'paw',
['hunger'] = 'mech',
['ice troll'] = 'paw',
['iceminion'] = 'boot',
['icemraider'] = 'hoof',
['kwama queen'] = 'rept',
['kwama warior'] = 'rept',
['kwama worker'] = 'rept',
['lame_corprus'] = 'foot',
['leastkagouti'] = 'rept',
['liche_king'] = 'skel',
['lordvivec'] = 'foot',
['minescrib'] = 'taln',
['mount'] = 'hoof',
['nixhound'] = 'rept',
['packrat'] = 'rat',
['rust rat'] = 'rat',
['scamp_fetch'] = 'rept',
['scrib'] = 'taln',
['shalk'] = 'taln',
['skeleton'] = 'skel',
['skinnpc'] = 'paw',
['steam_centurions'] = 'mech2',
['udyrfrykte'] = 'paw',
['undeadwolf_2'] = 'paw',
['war_wt_armor'] = 'rept',
['war_wt_glowy'] = 'rept',
['war_wt_grunda'] = 'rept',
['wingedtwilight'] = 'rept',
['wolf_black'] = 'paw',
['wolf_red'] = 'paw',
['wolf_white'] = 'paw',
}

return data