local this = {
    {
        id = "pray_longsword",
        name = "Longsword",
        ids = {
            "daedric claymore",
            "dwarven claymore",
            "glass claymore",
            "iron claymore",
            "nordic claymore",
            "steel claymore",
            "adamantium_claymore",
            "BM nordic silver claymore",
            "BM nordic silver claymore_ber",
            "silver claymore",
            "daedric longsword",
            "silver longsword",
            "glass longsword",
            "iron longsword",
            "BM ice longsword",
            "steel longsword",
            "ebony longsword",
            "BM nordic silver longsword",
            "BM nordic silver longsword_ber",
            "BM nordic_longsword_tracker",
            "BM hunstman longsword",
        }
    },
    {
        id = "pray_mace",
        name = "Mace",
        ids = {
            "chitin club",
            "iron club",
            "steel club",
            "spiked club",
            "dreugh club",
            "daedric club",
            "iron mace",
            "steel mace",
            "dwarven mace",
            "ebony mace",
            "daedric mace",
        }
    },
    {
        id = "pray_empty_soulgem",
        name = "Empty Soul Gem",
        ids = {
            "Misc_SoulGem_Grand",
            "Misc_SoulGem_Greater",
            "Misc_SoulGem_Common",
            "Misc_SoulGem_Lesser",
            "Misc_SoulGem_Petty",
        }
    },
    {
        id = "pray_feather",
        name = "Feather",
        ids = {
            "ingred_racer_plumes_01",
            "Misc_Quill",
        }
    },
    {
        id = "restore_health_ingred",
        name = "Health Ingredients",
        ids = {
            "ingred_corkbulb_root_01",
            "ingred_corprus_weepings_01",
            "ingred_emerald_01",
            "ingred_marshmerrow_01",
            "ingred_raw_Stalhrim_01",
            "ingred_resin_01",
            "ingred_saltrice_01",
            "ingred_sweetpulp_01",
            "ingred_wickwheat_01",
        }
    },
    {
        id = "gem",
        name = "Gem",
        ids = {
            "ingred_diamond_01",
            "ingred_emerald_01",
            "ingred_pearl_01",
            "ingred_ruby_01",
            "ingred_diamond_01",
        }
    },
    {
        id = "cup",
        name = "Cup",
        ids = {
            "misc_com_tankard_01",
            "misc_com_metal_goblet_01",
            "misc_com_metal_goblet_02",
            "misc_com_wood_cup_01",
            "misc_com_wood_cup_02",
            "Misc_Com_Redware_Cup",
            "misc_de_goblet_01",
            "misc_de_goblet_02",
            "misc_de_goblet_03",
            "misc_de_goblet_04",
            "misc_de_goblet_05",
            "misc_de_goblet_06",
            "misc_de_goblet_07",
            "misc_de_goblet_08",
            "misc_de_goblet_09",
            "misc_de_tankard_01",
            "misc_imp_silverware_cup",
            "Misc_Imp_Silverware_Cup_01",
            "misc_dwrv_mug00",
            "misc_dwrv_mug00_uni",
            "misc_dwrv_goblet00",
            "misc_dwrv_goblet00_uni",
            "misc_dwrv_goblet10",
            "misc_dwrv_goblet10_uni",
            "misc_dwrv_goblet10_tgcp",
            "misc_lw_cup",
        }
    },
    {
        id = "pray_gold",
        name = "Gold",
        ids = {
            "Gold_001"
        }
    },
    {
        id = "candle",
        name = "Candle",
        ids = {
            "Light_Com_Candle_01",
            "Light_Com_Candle_12",
            "Light_Com_Candle_12_77",
            "Light_Com_Candle_12_off",
            "Light_Com_Candle_14",
            "Light_Com_Candle_14_77",
            "Light_Com_Candle_15",
            "Light_Com_Candle_16",
            "Light_Com_Candle_16_77",
            "Light_Com_Candle_01_64",
            "light_com_candle_03",
            "light_com_candle_03_64",
            "light_com_candle_05",
            "light_com_candle_05_off",
            "light_com_candle_05_64",
            "light_com_candle_08",
            "light_com_candle_08_64",
            "light_com_candle_09",
            "light_com_candle_09_64",
            "light_com_candle_09_off",
            "light_com_candle_09_128",
            "light_com_candle_10",
            "light_com_candle_10_64",
            "light_com_candle_10_128",
            "light_com_candle_10_off",
            "light_de_candle_ivory_64",
            "light_de_candle_ivory_01",
            "light_de_candle_ivory_01_64",
            "light_de_candle_ivory_01_128",
            "light_de_candle_ivory_01_off",
            "light_de_candle_ivory_dead",
            "light_de_candle_red_01_64",
            "light_de_candle_red_01",
            "light_de_candle_red_02",
            "light_de_candle_red_02_64",
            "light_de_candle_green_01",
            "light_de_candle_green_01_64",
            "light_de_candle_green_01_Off",
            "light_de_candle_blue_01",
            "light_de_candle_blue_01_64",
            "light_de_candle_blue_01_Off",
            "light_de_candle_blue_02",
            "light_de_candle_blue_02_64",
            "light_de_candle_blue_02_100",
            "light_de_candle_15_64",
            "light_de_candle_16_64",
            "light_de_candle_17_64",
            "light_com_candle_02",
            "light_com_candle_01_off",
            "light_de_candle_03",
            "light_de_candle_03_64",
            "light_de_candle_05",
            "light_de_candle_05_64",
            "light_de_candle_05_77",
            "light_de_candle_06",
            "light_de_candle_06_64",
            "light_de_candle_06_off",
            "light_de_candle_128_off",
            "light_de_candle_10",
            "light_de_candle_10_64",
            "light_de_candle_11",
            "light_de_candle_11_off",
            "light_de_candle_11_64",
            "light_de_candle_12",
            "light_de_candle_12_64",
            "light_de_candle_13",
            "light_de_candle_13_64",
            "light_de_candle_13_off",
            "light_de_candle_14",
            "light_de_candle_14_64",
            "light_de_candle_15",
            "light_de_candle_15_off",
            "light_de_candle_16",
            "light_de_candle_17",
            "light_de_candle_18",
            "light_de_candle_18_64",
            "light_de_candle_19",
            "light_de_candle_19_64",
            "light_de_candle_19_256",
            "Light_De_Candle_20",
            "Light_De_Candle_21",
            "Light_De_Candle_22",
            "Light_De_Candle_24",
            "Light_De_Candle_24_64",
            "Light_De_Candle_25",
            "Light_De_Candle_26",
            "light_com_candle_02_64",
            "Light_De_Candle_23_177",
            "Light_De_Candle_23",
            "light_com_Dae_cursed_candle_10",
        }
    },
    {
        id = "skull",
        name = "Skull",
        ids = {
            "misc_skull00",
            "misc_skull10",
            "misc_Skull_Llevule",
            "misc_skull_griss",
            "misc_skull_griss_floor",
            "misc_skull_Skaal",
            "misc_skull_oddfrid",
            "misc_argonianhead_01",
        }
    },
    {
        id = "instrument",
        name = "Instrument",
        ids = {
            "misc_de_drum_01",
            "misc_de_drum_02",
            "misc_de_lute_01",
            "misc_de_lute_01_phat",
        }
    },
    {
        id = "ash_statue",
        name = "Ash Statue",
        ids = {
            "misc_6th_ash_statue_01",
            "misc_6th_ash_hrcs",
            "misc_6th_ash_hrmm",
        }
    },
    {
        id = "pray_6th_house",
        name = "6th House Item",
        ids = {
            "misc_goblet_dagoth",
            "misc_de_goblet_04_dagoth",
            "6th bell hammer",
        }
    },
    {
        id = "corprusmeat",
        name = "Corprusmeat",
        ids = {

            "ingred_6th_corprusmeat_01",
            "ingred_6th_corprusmeat_02",
            "ingred_6th_corprusmeat_03",
            "ingred_6th_corprusmeat_04",
            "ingred_6th_corprusmeat_05",
            "ingred_6th_corprusmeat_06",
            "ingred_6th_corprusmeat_07",
        }
    },
    {
        id = "skooma_pipe",
        name = "Ritual Pipe",
        ids = {
            "apparatus_a_spipe_01",
            "apparatus_a_spipe_tsiya"
        }
    },
    {
        id = "pray_moon_sugar",
        name = "Ritual Dust",
        ids = {
            "ingred_moon_sugar_01"
        }
    },
    {
        id = "ashlander_lit",
        name = "Ashlander Text",
        ids = {
            "bk_Ashland_Hymns",
            "bk_five_far_stars",
            "bk_thelostprophecy",
            "bk_words_of_the_wind",
        }
    },
    {
        id = "pray_ashlander_cuirass",
        name = "Ashlander Cuirass",
        ids = {
            "bonemold_armun-an_cuirass",
            "netch_leather_boiled_cuirass",
            "erur_dan_cuirass_unique",
            "bonemold_gah-julan_cuirass",
            "indoril cuirass",
            "bonemold_cuirass",
            "chitin cuirass",
        }
    }
}

return this