return {
    "meridian",
    "wooden",
    "mage",
    "bloodstone",
    "soulstone",
    "elven",
    "high guard",
    "of the dark lord",
    "spectral",
    "phantasm",
    "crystal",
    "amethyst",
    "quartz",
	
    "masquerade",
    "dawn song",
    "mindstone",
    "hak'",
    "yathar",
    "laal'",
    "ahmar",
    "nii'",
    "azra",
    "hra'",
    "xdar",
    "kaa'",
    "aswa",
    "jas'",
    "ang",
    "asfar",
    "kak'",
    "abya",
    "saf'",
    "ani'",
    "ashan",
    "gul'",
    "azar",
    "bhu'",
    "azmar",
    "asmar",
    "golden",
    "'bhu",
    "'kaa",
    "ilrion's",
    "mannan's",
    "ethron's",
    "virian's",
    "eleth's",
    "espiria's",
    "alladan's",
    "cirithel's",
    "finuola's",
    "dirian's",
    "rinola's",
    "artisana's",
    "golitha's",
    "kiriel's",
    "atalan's",
    "mithiria's",
    "galidorn's",
    "'s mastery",
    "halidan's",
    "orian's",
    "lirian's",
    "kilian's",
    "ceruila's",
    "altia's",
    "canisia's",
    "merisian's",
    "of the fae",
    "dark",
    "of mab",
    "of titania",
    "of morganna",
    "of oberon",
    "merisande's",
    "wizard's",
    "raw silk",
    "drake skin",
    "autumnal",
    "of the aurora",
    "dragon's breath",
    "yokudan",
    "eastern province",
    "djinni",
    "maille",
    "summerset",
    "skyrim",
    "dragontail",
    "malefica",
    "bella domina",
    "dunmer leather",
    "elven sorcery",
    "assassin's",
    "night song",
    "shadow fox",
    "box weave",
    "bamboo ",
    "woven ",
    "light wicker",
    "wicker ",
    "daedric arcana",
    "of the kyn",
    "nuada's", 
    "nuala's",
    "leviathan", 
    "sea kindred",
    "kheran",
    "Emmissary's",
    "cermonial", 
    "sea",
}