return {
{ID="adamantium_bracer_left", name="Adamantium Bracer Left"},
{ID="adamantium_pauldron_left", name="Adamantium Pauldron Left"},
{ID="adamantium_bracer_right", name="Adamantium Bracer Right"},
{ID="adamantium_pauldron_right", name="Adamantium Pauldron Right"},
{ID="steel_gauntlet_left_ancient", name="Ancient Steel Gauntlet Left"},
{ID="steel_pauldron_left_ancient", name="Ancient Steel Pauldron Left"},
{ID="steel_gauntlet_right_ancient", name="Ancient Steel Gauntlet Right"},
{ID="steel_pauldron_right_ancient", name="Ancient Steel Pauldron Right"},
{ID="bonemold_armun-an_cuirass", name="Bonemold Armun-An Cuirass"},
{ID="bonemold_armun-an_pauldron_l", name="Bonemold Armun-An Pauldron L"},
{ID="bonemold_armun-an_pauldron_r", name="Bonemold Armun-An Pauldron R"},
{ID="ebony_shield_auriel", name="Shield Auriel's"},
{ID="ebony_shield_auriel_x", name="Shield Auriel's"},
{ID="azura's servant", name="Shield Azura's Servant"},
{ID="BM bear greaves", name="Bear leggings"},
{ID="bm bear left gauntlet", name="Bear Gauntlet Left"},
{ID="BM Bear left Pauldron", name="Bear Pauldron Left"},
{ID="BM bear right gauntlet", name="Bear Gauntlet Right"},
{ID="BM bear right pauldron", name="Bear Pauldron Right"},
{ID="blessed_shield", name="Shield Steel Blessed"},
{ID="blessed_tower_shield", name="Tower Shield Steel Blessed"},
{ID="Blood_Feast_Shield", name="Shield Blood Feast"},
{ID="bloodworm_helm_unique", name="Helm Bloodworm"},
{ID="bloodworm_helm_unique_x", name="Helm Bloodworm"},
{ID="netch_leather_boiled_cuirass", name="Netch Boiled Leather Cuirass"},
{ID="netch_leather_boiled_helm", name="Netch Boiled Leather Helm"},
{ID="bonedancer gauntlet", name="Bonedancer Gauntlet Right"},
{ID="lbonemold brace of horny fist", name="Bonemold Bracer of Horny Fist L"},
{ID="rbonemold bracer of horny fist", name="Bonemold Bracer of Horny Fist R"},
{ID="bonemold_pauldron_l", name="Bonemold Pauldron Left"},
{ID="bonemold_bracer_left", name="Bonemold Bracer Left"},
{ID="bonemold_pauldron_r", name="Bonemold Pauldron Rright"},
{ID="bonemold_bracer_right", name="Bonemold Bracer Right"},
{ID="boneweave gauntlet", name="Boneweave Gauntlet Left"},
{ID="bound_gauntlet_left", name="Bound Gauntlet Left"},
{ID="bound_gauntlet_right", name="Bound Gauntlet Right"},
{ID="bound_helm", name="Bound Helm"},
{ID="chitin guantlet - left", name="Chitin Gauntlet Left"},
{ID="chitin pauldron - left", name="Chitin Pauldron Left"},
{ID="chitin guantlet - right", name="Chitin Gauntlet Right"},
{ID="chitin pauldron - right", name="Chitin Pauldron Right"},
{ID="cloth bracer left", name="Cloth Bracer Left"},
{ID="cloth bracer right", name="Cloth Bracer Right"},
{ID="fur_colovian_helm", name="Colovian Fur Helm"},
{ID="conoon_chodala_boots_unique", name="Boots Conoon Chodala's"},
{ID="daedric_gauntlet_left", name="Daedric Gauntlet Left"},
{ID="daedric_pauldron_left", name="Daedric Pauldron Left"},
{ID="daedric_gauntlet_right", name="Daedric Gauntlet Right"},
{ID="daedric_pauldron_right", name="Daedric Pauldron Right"},
{ID="DarkBrotherhood gauntlet_L", name="Dark Brotherhood Gauntlet Left"},
{ID="DarkBrotherhood pauldron_L", name="Dark Brotherhood Pauldron Left"},
{ID="DarkBrotherhood gauntlet_R", name="Dark Brotherhood Gauntlet Right"},
{ID="DarkBrotherhood pauldron_R", name="Dark Brotherhood Pauldron Right"},
{ID="darksun_shield_unique", name="Shield Darksun"},
{ID="demon cephalopod", name="Demon Helm Cephalopod"},
{ID="demon helm", name="Demon Helm"},
{ID="demon mole crab", name="Demon Helm Mole Crab"},
{ID="devil cephalopod helm", name="Devil Helm Cephalopod"},
{ID="devil helm", name="Devil Helm"},
{ID="devil mole crab helm", name="Devil Helm Mole Crab"},
{ID="dwemer_bracer_left", name="Dwemer Bracer Left"},
{ID="dwemer_pauldron_left", name="Dwemer Pauldron Left"},
{ID="dwemer_bracer_right", name="Dwemer Bracer Right"},
{ID="dwemer_pauldron_right", name="Dwemer Pauldron Right"},
{ID="ebony_closed_helm", name="Ebony Helm Closed"},
{ID="ebony_bracer_left", name="Ebony Bracer Left"},
{ID="ebony_bracer_left_tgeb", name="Ebony Bracer Left"},
{ID="ebony_pauldron_left", name="Ebony Pauldron Left"},
{ID="ebony_bracer_right", name="Ebony Bracer Right"},
{ID="ebony_bracer_right_tgeb", name="Ebony Bracer Right"},
{ID="ebony_pauldron_right", name="Ebony Pauldron Right"},
{ID="feather_shield", name="Shield Feather"},
{ID="fiend helm", name="Helm Fiend"},
{ID="gauntlet_fists_l_unique", name="Fist of Randagulf Left"},
{ID="gauntlet_fists_r_unique", name="Fist of Randagulf Right"},
{ID="bonemold_gah-julan_cuirass", name="Bonemold Gah-Julan Cuirass"},
{ID="bonemold_gah-julan_pauldron_l", name="Bonemold Gah-Julan Pauldron L"},
{ID="bonemold_gah-julan_pauldron_r", name="Bonemold Gah-Julan Pauldron R"},
{ID="glass_pauldron_left", name="Glass Pauldron Left"},
{ID="glass_pauldron_right", name="Glass Pauldron Right"},
{ID="gondolier_helm", name="Helm Gondolier's"},
{ID="cephalopod_helm_HTNK", name="Helm Cephalopod Gothren's"},
{ID="heavy_leather_boots", name="Leather Boots Heavy"},
{ID="Indoril_Almalexia_gauntlet_L", name="Her Hand's Gauntlet Left"},
{ID="Indoril_MH_Guard_gauntlet_L", name="Her Hand's Gauntlet Left"},
{ID="Indoril_Almalexia_Pauldron_L", name="Her Hand's Pauldron Left"},
{ID="Indoril_MH_Guard_Pauldron_L", name="Her Hand's Pauldron Left"},
{ID="Indoril_Almalexia_gauntlet_R", name="Her Hand's Gauntlet Right"},
{ID="Indoril_MH_Guard_gauntlet_R", name="Her Hand's Gauntlet Right"},
{ID="Indoril_Almalexia_Pauldron_R", name="Her Hand's Pauldron Right"},
{ID="Indoril_MH_Guard_Pauldron_R", name="Her Hand's Pauldron Right"},
{ID="bonemold_tshield_hlaaluguard", name="Bonemold Shield Hlaalu Guard"},
{ID="holy_shield", name="Shield Holy"},
{ID="holy_tower_shield", name="Tower Shield Holy"},
{ID="BM_Ice_gauntletL", name="Ice Armor Gauntlet Left"},
{ID="BM_Ice_PauldronL", name="Ice Armor Pauldron Left"},
{ID="BM_Ice_gauntletR", name="Ice Armor Gauntlet Right"},
{ID="BM_Ice_PauldronR", name="Ice Armor Pauldron Right"},
{ID="imperial_chain_pauldron_left", name="Imperial Chain Pauldron Left"},
{ID="imperial_chain_pauldron_right", name="Imperial Chain Pauldron Right"},
{ID="imperial left gauntlet", name="Imperial Steel Gauntlet Left"},
{ID="imperial left pauldron", name="Imperial Steel Pauldron Left"},
{ID="imperial right gauntlet", name="Imperial Steel Gauntlet Right"},
{ID="imperial right pauldron", name="Imperial Steel Pauldron Right"},
{ID="imperial_studded_cuirass", name="Studded Leather Cuirass"},
{ID="templar bracer left", name="Imperial Templar Bracer Left"},
{ID="templar_pauldron_left", name="Imperial Templar Pauldron Left"},
{ID="templar bracer right", name="Imperial Templar Bracer Right"},
{ID="templar_pauldron_right", name="Imperial Templar Pauldron Right"},
{ID="indoril left gauntlet", name="Indoril Gauntlet Left"},
{ID="indoril pauldron left", name="Indoril Pauldron Left"},
{ID="indoril right gauntlet", name="Indoril Gauntlet Right"},
{ID="indoril pauldron right", name="Indoril Pauldron Right"},
{ID="iron_bracer_left", name="Iron Bracer Left"},
{ID="iron_gauntlet_left", name="Iron Gauntlet Left"},
{ID="iron_pauldron_left", name="Iron Pauldron Left"},
{ID="iron_bracer_right", name="Iron Bracer Right"},
{ID="iron_gauntlet_right", name="Iron Gauntlet Right"},
{ID="iron_pauldron_right", name="Iron Pauldron Right"},
{ID="left cloth horny fist bracer", name="Cloth Horny Fist Bracer Left"},
{ID="Gauntlet_of_Glory_left", name="Gauntlet of Glory Left"},
{ID="left gauntlet of the horny fist", name="Gauntlet of the Horny Fist L"},
{ID="gauntlet _horny_fist_l", name="Gauntlet of the Horny Fist L"},
{ID="glass_bracer_left", name="Glass Bracer Left"},
{ID="left_horny_fist_gauntlet", name="Glove of the Horny Fist Left"},
{ID="left leather bracer", name="Leather Bracer Left"},
{ID="morag_tong_helm", name="Helm Morag Tong"},
{ID="netch_leather_gauntlet_left", name="Netch Leather Gauntlet Left"},
{ID="netch_leather_pauldron_left", name="Netch Leather Pauldron Left"},
{ID="netch_leather_gauntlet_right", name="Netch Leather Gauntlet Right"},
{ID="netch_leather_pauldron_right", name="Netch Leather Pauldron Right"},
{ID="fur_bracer_left", name="Nordic Fur Bracer Left"},
{ID="fur_gauntlet_left", name="Nordic Fur Gauntlet Left"},
{ID="fur_pauldron_left", name="Nordic Fur Pauldron Left"},
{ID="fur_bracer_right", name="Nordic Fur Bracer Right"},
{ID="fur_gauntlet_right", name="Nordic Fur Gauntlet Right"},
{ID="fur_pauldron_right", name="Nordic Fur Pauldron Right"},
{ID="BM_NordicMail_gauntletL", name="Nordic Mail Gauntlet Left"},
{ID="BM_NordicMail_PauldronL", name="Nordic Mail Pauldron Left"},
{ID="BM_NordicMail_gauntletR", name="Nordic Mail Gauntlet Right"},
{ID="BM_NordicMail_PauldronR", name="Nordic Mail Pauldron Right"},
{ID="orcish_bracer_left", name="Orcish Bracer Left"},
{ID="orcish_pauldron_left", name="Orcish Pauldron Left"},
{ID="orcish_bracer_right", name="Orcish Bracer Right"},
{ID="orcish_pauldron_right", name="Orcish Pauldron Right"},
{ID="fur_colovian_helm_red", name="Colovian Fur Helm Red"},
{ID="chitin_watchman_helm", name="Redoran Watchman Helm"},
{ID="BM_Ice minion_Shield1", name="Shield Riekling"},
{ID="right cloth horny fist bracer", name="Cloth Horny Fist Bracer Right"},
{ID="gauntlet_of_glory_right", name="Gauntlet of Glory Right"},
{ID="right gauntlet of horny fist", name="Gauntlet of the Horny Fist R"},
{ID="gauntlet_horny_fist_r", name="Gauntlet of the Horny Fist R"},
{ID="glass_bracer_right", name="Glass Bracer Right"},
{ID="right horny fist gauntlet", name="Glove of the Horny Fist Right"},
{ID="right leather bracer", name="Leather Bracer Right"},
{ID="Helsethguard_gauntlet_left", name="Royal Guard Gauntlet Left"},
{ID="Helsethguard_pauldron_left", name="Royal Guard Pauldron Left"},
{ID="Helsethguard_gauntlet_right", name="Royal Guard Gauntlet Right"},
{ID="Helsethguard_pauldron_right", name="Royal Guard Pauldron Right"},
{ID="saint's shield", name="Shield Saint's"},
{ID="ebony_closed_helm_fghl", name="Ebony Helm Sarano"},
{ID="shadow_shield", name="Shield of Shadow"},
{ID="slave_bracer_left", name="Slave's Bracer Left"},
{ID="slave_bracer_right", name="Slave's Bracer Right"},
{ID="BM_bear_left_gauntlet_snow", name="Snow Bear Gauntlet Left"},
{ID="BM_Bear_left_Pauldron_snow", name="Snow Bear Pauldron Left"},
{ID="BM_bear_right_gauntlet_snow", name="Snow Bear Gauntlet Right"},
{ID="BM_bear_right_pauldron_snow", name="Snow Bear Pauldron Right"},
{ID="BM_wolf_left_gauntlet_snow", name="Snow Wolf Gauntlet Left"},
{ID="BM_wolf_left_pauldron_snow", name="Snow Wolf Pauldron Left"},
{ID="BM_wolf_right_gauntlet_snow", name="Snow Wolf Gauntlet Right"},
{ID="BM_wolf_right_pauldron_snow", name="Snow Wolf Pauldron Right"},
{ID="steel_gauntlet_left", name="Steel Gauntlet Left"},
{ID="steel_pauldron_left", name="Steel Pauldron Left"},
{ID="steel_gauntlet_right", name="Steel Gauntlet Right"},
{ID="steel_pauldron_right", name="Steel Pauldron Right"},
{ID="storm helm", name="Helm Storm"},
{ID="velothian_helm", name="Chitin Helm Blessed"},
{ID="velothian shield", name="Chitin Shield Blessed"},
{ID="velothis_shield", name="Shield Velothi's"},
{ID="veloths_shield", name="Shield Veloth's"},
{ID="veloths_tower_shield", name="Netch Tower Shield Blessed"},
{ID="fur_colovian_helm_white", name="Colovian Fur Helm White"},
{ID="bm wolf left gauntlet", name="Wolf Gauntlet Left"},
{ID="BM Wolf Left Pauldron", name="Wolf Pauldron Left"},
{ID="BM wolf right gauntlet", name="Wolf Gauntlet Right"},
{ID="BM Wolf right pauldron", name="Wolf Pauldron Right"},
{ID="T_Imp_Silver_BracerL_01", name="Imperial Silver Bracer Left"},
{ID="T_Imp_Silver_BracerR_01", name="Imperial Silver Bracer Right"},
{ID="T_Imp_Silver_PauldronL_01", name="Imperial Silver Pauldron Left"},
{ID="T_Imp_Silver_PauldronR_01", name="Imperial Silver Pauldron Right"},
{ID="T_Nor_Companion_PauldronR_01", name="Companion Armor Pauldron Right"},
{ID="T_Nor_Companion_GauntletR_01", name="Companion Armor Gauntlet Right"},
{ID="T_Nor_Companion_PauldronL_01", name="Companion Armor Pauldron Left"},
{ID="T_Nor_Companion_GauntletL_01", name="Companion Armor Gauntlet Left"},
{ID="T_Orc_Leather_GauntletL_01", name="Orc Leather Gauntlet Left"},
{ID="T_Orc_Leather_PauldronL_01", name="Orc Leather Pauldron Left"},
{ID="T_Orc_Leather_GauntletR_01", name="Orc Leather Gauntlet Right"},
{ID="T_Orc_Leather_PauldronR_01", name="Orc Leather Pauldron Right"},
{ID="T_Nor_Steel_PauldronL_01", name="Nord Steel Pauldron Left"},
{ID="T_Nor_Steel_PauldronR_01", name="Nord Steel Pauldron Right"},
{ID="T_Nor_Steel_GauntletR_01", name="Nord Steel Gauntlet Right"},
{ID="T_Nor_Steel_GauntletL_01", name="Nord Steel Gauntlet Left"},
{ID="T_Nor_Guard_GauntletL_01", name="Nord Guard Gauntlet Left"},
{ID="T_Nor_Guard_PauldronL_01", name="Nord Guard Pauldron Left"},
{ID="T_Nor_Guard_GauntletR_01", name="Nord Guard Gauntlet Right"},
{ID="T_Nor_Guard_PauldronR_01", name="Nord Guard Pauldron Right"},
{ID="T_Rea_Wormmouth_BracerL_01", name="Wormmouth Bracer Left"},
{ID="T_Rea_Wormmouth_BracerR_01", name="Wormmouth Bracer Right"},
{ID="T_Rea_Wormmouth_PauldronR_01", name="Wormmouth Pauldron Right"},
{ID="T_Rea_Wormmouth_PauldronL_01", name="Wormmouth Pauldron Left"},
{ID="T_Nor_Wood_Shield_01", name="Shield Round"},
{ID="T_Nor_Wood_Shield_02", name="Shield Round"},
{ID="T_Nor_Wood_Shield_03", name="Shield Round"},
{ID="T_Nor_Sabrecat_Helm_02", name="Sabre Snow Cat Helmet"},
{ID="T_Nor_Ironwood_Shield_01", name="Shield Ironwood"},
{ID="T_Nor_Ironwood_Shield_02", name="Shield Ironwood Black"},
{ID="T_Imp_ColBronzeOld_Helm_01", name="Helm Bronze"},
{ID="T_Bre_BjoulsaeFur_Helm_01", name="Helm Bjoulsae Fur"},
{ID="T_Nor_Trollbone_BracerL_01", name="Nordic Trollbone Bracer Left"},
{ID="T_Nor_Trollbone_BracerR_01", name="Nordic Trollbone Bracer Right"},
{ID="T_Nor_Trollbone_PauldronL_01", name="Nordic Trollbone Pauldron Left"},
{ID="T_Nor_Trollbone_PauldronR_01", name="Nordic Trollbone Pauldron Right"},
{ID="T_He_Direnni_BracerL_01", name="Direnni Bracer Left"},
{ID="T_He_Direnni_BracerR_01", name="Direnni Bracer Right"},
{ID="T_He_Direnni_PauldronL_01", name="Direnni Pauldron Left"},
{ID="T_He_Direnni_PauldronR_01", name="Direnni Pauldron Right"},
{ID="T_Imp_Ep_HatColWest_01", name="Leather Hat Expensive"},
{ID="T_Imp_Ep_HatColWest_02", name="Leather Hat Expensive"},
{ID="T_Imp_Cm_BootsCol_01", name="Leather Boots Common"},
{ID="T_Imp_Cm_BootsCol_02", name="Leather Boots Common"},
{ID="T_Imp_Cm_BootsCol_03", name="Leather Boots Common"},
{ID="T_Imp_Cm_BootsCol_04", name="Leather Boots Common"},
{ID="T_Rga_Ep_Headdress_01", name="Redguard Hat Expensive"},
{ID="T_Imp_Cm_HatColWest_01", name="Cloth Cap Common"},
{ID="T_Imp_Templar_ShieldTower_01", name="Imperial Templar Shield"},
{ID="T_Imp_Dragonscale_BarcerR_01", name="Dragonscale Bracer Right"},
{ID="T_Imp_Dragonscale_BarcerL_01", name="Dragonscale Bracer Left"},
{ID="T_Imp_Dragonscale_PauldronR_01", name="Dragonscale Pauldron Right"},
{ID="T_Imp_Dragonscale_PauldronL_01", name="Dragonscale Pauldron Left"},
{ID="T_Imp_Newtscale_GauntletR_01", name="Imperial Newtscale Gauntlet R"},
{ID="T_Imp_Newtscale_GauntletL_01", name="Imperial Newtscale Gauntlet L"},
{ID="T_Imp_Newtscale_PauldronR_01", name="Imperial Newtscale Pauldron R"},
{ID="T_Imp_Newtscale_PauldronL_01", name="Imperial Newtscale Pauldron L"},
{ID="T_Imp_ColIron2_PauldronL_01", name="Colovian Prince Pauldron Left"},
{ID="T_Imp_ColIron2_PauldronR_01", name="Colovian Prince Pauldron Right"},
{ID="T_Imp_ColIron2_BracerR_01", name="Colovian Prince Bracer Right"},
{ID="T_Imp_ColIron2_BracerL_01", name="Colovian Prince Bracer Left"},
{ID="T_Imp_ColIron1_PauldronR_01", name="Colovian Iron Pauldron Right"},
{ID="T_Imp_ColIron1_PauldronL_01", name="Colovian Iron Pauldron Left"},
{ID="T_Imp_ColIron1_GauntletL_01", name="Colovian Iron Gauntlet Left"},
{ID="T_Imp_ColIron1_GauntletR_01", name="Colovian Iron Gauntlet Right"},
{ID="T_Imp_ColSteel1_BracerL_01", name="Colovian Steel Bracer Left"},
{ID="T_Imp_ColSteel1_BracerR_01", name="Colovian Steel Bracer Right"},
{ID="T_Imp_ColSteel1_PauldronL_01", name="Colovian Steel Pauldron Left"},
{ID="T_Imp_ColSteel1_PauldronR_01", name="Colovian Steel Pauldron Right"},
{ID="T_Imp_NibBronze_BracerL_01", name="Nibenese Bronze Bracer Left"},
{ID="T_Imp_NibBronze_BracerR_01", name="Nibenese Bronze Bracer Right"},
{ID="T_Imp_NibBronze_PauldronL_01", name="Nibenese Bronze Pauldron Left"},
{ID="T_Imp_NibBronze_PauldronR_01", name="Nibenese Bronze Pauldron Right"},
{ID="T_Imp_GuardTown1_GauntletL_01", name="Cataphract Gauntlet Left"},
{ID="T_Imp_GuardTown1_GauntletR_01", name="Cataphract Gauntlet Right"},
{ID="T_Imp_Et_HatColNorth_04", name="Colovian Hat Extravagant"},
{ID="T_Imp_Et_HatColNorth_05", name="Colovian Hat Extravagant"},
{ID="T_Imp_Et_HatColNorth_01", name="Colovian Hat Extravagant"},
{ID="T_Imp_Et_HatColNorth_02", name="Colovian Hat Extravagant"},
{ID="T_Imp_Et_HatColNorth_03", name="Colovian Hat Extravagant"},
{ID="T_Dae_Lord_PauldronL_01", name="Daedric Lords Pauldron Left"},
{ID="T_Dae_Lord_PauldronR_01", name="Daedric Lords Pauldron Right"},
{ID="T_Dae_Lord_GauntletL_01", name="Daedric Lords Gauntlet Left"},
{ID="T_Dae_Lord_GauntletR_01", name="Daedric Lords Gauntlet Right"},
{ID="T_Nor_Bearskin_BracerL_01", name="Nordic Bearskin Bracer Left"},
{ID="T_Nor_Bearskin_BracerR_01", name="Nordic Bearskin Bracer Right"},
{ID="T_Nor_Bearskin_PauldronL_01", name="Nordic Bearskin Pauldron Left"},
{ID="T_Nor_Bearskin_PauldronR_01", name="Nordic Bearskin Pauldron Right"},
{ID="T_De_Bonemold_HelmOpen_01", name="Bonemold Helm Open"},
{ID="T_De_Chitin_HelmOpen_01", name="Chitin Helm Open"},
{ID="T_De_DaedricHide_GauntletL_01", name="Daedric Hide Gauntlet Left"},
{ID="T_De_DaedricHide_GauntletR_01", name="Daedric Hide Gauntlet Right"},
{ID="T_De_DaedricHide_PauldronL_01", name="Daedric Hide Pauldron Left"},
{ID="T_De_DaedricHide_PauldronR_01", name="Daedric Hide Pauldron Right"},
{ID="T_Dae_Regular_PauldronL_01", name="Daedric Pauldron Left"},
{ID="T_Dae_Regular_PauldronR_01", name="Daedric Pauldron Right"},
{ID="T_De_DresBonemold_GauntletL_01", name="Native Gah'Kogo Gauntlet Left"},
{ID="T_De_DresBonemold_GauntletR_01", name="Native Gah'Kogo Gauntlet Right"},
{ID="T_De_DresBonemold_PauldronL_01", name="Native Gah'Kogo Pauldron Left"},
{ID="T_De_DresBonemold_PauldronR_01", name="Native Gah'Kogo Pauldron Right"},
{ID="T_De_Dreugh_BracerL_01", name="Dreugh Bracer Left"},
{ID="T_De_Dreugh_BracerR_01", name="Dreugh Bracer Right"},
{ID="T_De_Dreugh_PauldronL_01", name="Dreugh Pauldron Left"},
{ID="T_De_Dreugh_PauldronR_01", name="Dreugh Pauldron Right"},
{ID="T_Dwe_Regular_ShieldTower_01", name="Dwarven Tower Shield"},
{ID="T_De_Ebony_HelmOpen_01", name="Ebony Helm Open"},
{ID="T_Cr_Goblin_PauldronL_01", name="Goblin Pauldron Left"},
{ID="T_Cr_Goblin_PauldronR_01", name="Goblin Pauldron Right"},
{ID="T_De_IndBonemold_GauntletL_01", name="Native Chuzei Gauntlet Left"},
{ID="T_De_IndBonemold_GauntletR_01", name="Native Chuzei Gauntlet Right"},
{ID="T_De_IndBonemold_PauldronL_01", name="Native Chuzei Pauldron Left"},
{ID="T_De_IndBonemold_PauldronL_02", name="Native Chuzei Pauldron Left"},
{ID="T_De_IndBonemold_PauldronR_01", name="Native Chuzei Pauldron Right"},
{ID="T_De_IndBonemold_PauldronR_02", name="Native Chuzei Pauldron Right"},
{ID="T_Com_Iron_BracerL_01", name="Iron Bracer Left"},
{ID="T_Com_Iron_BracerL_02", name="Iron Bracer Left"},
{ID="T_Com_Iron_BracerR_01", name="Iron Bracer Right"},
{ID="T_Com_Iron_BracerR_02", name="Iron Bracer Right"},
{ID="T_Com_Iron_PauldronL_01", name="Iron Pauldron Left"},
{ID="T_Com_Iron_PauldronL_02", name="Iron Pauldron Left"},
{ID="T_Com_Iron_PauldronR_01", name="Iron Pauldron Right"},
{ID="T_Com_Iron_PauldronR_02", name="Iron Pauldron Right"},
{ID="T_De_Molecrab_BracerL_01", name="Telvanni Molecrab Bracer Left"},
{ID="T_De_Molecrab_BracerR_01", name="Telvanni Molecrab Bracer Right"},
{ID="T_De_Molecrab_PauldronL_01", name="Telvanni Molecrab Pauldron L"},
{ID="T_De_Molecrab_PauldronR_01", name="Telvanni Molecrab Pauldron R"},
{ID="T_De_Necrom_PauldronL_01", name="Necrom Indoril Pauldron Left"},
{ID="T_De_Necrom_PauldronR_01", name="Necrom Indoril Pauldron Right"},
{ID="T_Nor_Iron_GauntletL_01", name="Nordic Iron Gauntlet Left"},
{ID="T_Nor_Iron_GauntletR_01", name="Nordic Iron Gauntlet Right"},
{ID="T_Nor_Iron_PauldronL_01", name="Nordic Iron Pauldron Left"},
{ID="T_Nor_Iron_PauldronR_01", name="Nordic Iron Pauldron Right"},
{ID="T_Orc_Regular_HelmOpen_01", name="Orcish Helm Open"},
{ID="T_De_RedHeroBonemold_PauldrL_01", name="Redoran Pauldron Left"},
{ID="T_De_RedHeroBonemold_PauldrR_01", name="Redoran Pauldron Right"},
{ID="T_De_RedMastBonemold_PauldrL_01", name="Redoran Master Pauldron Left"},
{ID="T_De_RedMastBonemold_PauldrR_01", name="Redoran Master Pauldron Right"},
{ID="T_Com_Steel_PauldronL_01", name="Steel Pauldron Left"},
{ID="T_Com_Steel_PauldronL_02", name="Steel Pauldron Left"},
{ID="T_Com_Steel_PauldronL_03", name="Steel Pauldron Left"},
{ID="T_Com_Steel_PauldronR_01", name="Steel Pauldron Right"},
{ID="T_Com_Steel_PauldronR_02", name="Steel Pauldron Right"},
{ID="T_Com_Steel_PauldronR_03", name="Steel Pauldron Right"},
{ID="T_Imp_StuddedLeather_PauldrL_01", name="Studded Leather Pauldron Left"},
{ID="T_Imp_StuddedLeather_PauldrR_01", name="Studded Leather Pauldron Right"},
{ID="T_De_RedWatchChitin_Boots_01", name="Redoran Watchman Boots"},
{ID="T_De_RedWatchChitin_GauntlL_01", name="Redoran Watchman Gauntlet Left"},
{ID="T_De_RedWatchChitin_GauntlR_01", name="Redoran Watchman Gauntlet Right"},
{ID="T_De_RedWatchChitin_PauldrL_01", name="Redoran Watchman Pauldron Left"},
{ID="T_De_RedWatchChitin_PauldrR_01", name="Redoran Watchman Pauldron Right"},
{ID="T_Imp_Wood_ShieldTower_01", name="Wooden Tower Shield"},
{ID="T_De_DresHunter_PauldronL_01", name="Dres Hunter Pauldron Left"},
{ID="T_De_DresHunter_PauldronR_01", name="Dres Hunter Pauldron Left"},
{ID="T_De_Diviner_Helm_01", name="Helm Diviner"},
{ID="T_De_UNI_IrfeidsShoulderL", name="Irfeid's Shoulder Left"},
{ID="T_De_UNI_IrfeidsShoulderR", name="Irfeid's Shoulder Right"},
{ID="T_De_UNI_ShoulderOfGhostlightL", name="Shoulder of Ghostlight Left"},
{ID="T_De_UNI_ShoulderOfGhostlightR", name="Shoulder of Ghostlight Right"},
{ID="T_Imp_UNI_BlacksmithsHandR", name="Blacksmith's Hand Right"},
{ID="T_Imp_UNI_BlacksmithsHandL", name="Blacksmith's Hand Left"},
{ID="T_De_Dreugh_PauldronL_Swim", name="Dreugh Pauldron-Fin Left"},
{ID="T_De_Dreugh_PauldronR_Swim", name="Dreugh Pauldron-Fin Right"},
{ID="T_Aka_Regular_Shield_01", name="Shield Akaviri"},
{ID="T_Ayl_Saliache_PauldronL_01", name="Saliache Pauldron Left"},
{ID="T_Ayl_Saliache_PauldronR_01", name="Saliache Pauldron Right"},
{ID="T_Ayl_Saliache_BracerL_01", name="Saliache Bracer Left"},
{ID="T_Ayl_Saliache_BracerR_01", name="Saliache Bracer Right"},
{ID="T_Imp_StuddedLeather_cuirass_02", name="Studded Leather Cuirass Brena"},
{ID="T_Imp_StuddedLeather_cuirass_03", name="Studded Leather Cuirass Kreath"},
{ID="T_Imp_StuddedLeather_Helm_02", name="Studded Leather Helm Brena"},
{ID="T_Imp_StuddedLeather_Helm_03", name="Studded Leather Helm Kreath"},
{ID="T_Imp_ColIron1_GauntletL_02", name="Murena Iron Gauntlet Left"},
{ID="T_Imp_ColIron1_GauntletR_02", name="Murena Iron Gauntlet Right"},
{ID="T_Imp_ColIron1_PauldronL_02", name="Murena Iron Pauldron Left"},
{ID="T_Imp_ColIron1_PauldronR_02", name="Murena Iron Pauldron Right"},
{ID="T_Imp_ColIron1_GauntletL_03", name="Mhorla Iron Gauntlet Left"},
{ID="T_Imp_ColIron1_GauntletR_03", name="Mhorla Iron Gauntlet Right"},
{ID="T_Imp_ColIron1_PauldronL_03", name="Mhorla Iron Pauldron Left"},
{ID="T_Imp_ColIron1_PauldronR_03", name="Mhorla Iron Pauldron Right"},
{ID="T_Imp_ColSteel1_BracerL_02", name="Oloman Steel Bracer Left"},
{ID="T_Imp_ColSteel1_BracerR_02", name="Oloman Steel Bracer Right"},
{ID="T_Imp_ColSteel1_PauldronL_02", name="Oloman Steel Pauldron Left"},
{ID="T_Imp_ColSteel1_PauldronR_02", name="Oloman Steel Pauldron Right"},
{ID="T_Imp_ColSteel1_BracerL_03", name="Larich Steel Bracer Left"},
{ID="T_Imp_ColSteel1_BracerR_03", name="Larich Steel Bracer Right"},
{ID="T_Imp_ColSteel1_PauldronL_03", name="Larich Steel Pauldron Left"},
{ID="T_Imp_ColSteel1_PauldronR_03", name="Larich Steel Pauldron Right"},
{ID="T_Imp_Militia_PauldronR_01", name="Militia Steel Pauldron Right"},
{ID="T_Imp_Militia_GauntR_01", name="Militia Steel Gauntlet Right"},
{ID="T_Imp_Militia_PauldronL_01", name="Militia Steel Pauldron Left"},
{ID="T_Imp_Militia_GauntL_01", name="Militia Steel Gauntlet Left"},
{ID="T_Imp_ColFur_GauntL_03", name="Colovian Fur Gauntlet Left"},
{ID="T_Imp_ColFur_GauntR_03", name="Colovian Fur Gauntlet Right"},
{ID="T_Imp_ColFur_GauntL_01", name="Colovian Fur Gauntlet Left"},
{ID="T_Imp_ColFur_GauntR_01", name="Colovian Fur Gauntlet Right"},
{ID="T_Imp_ColFur_GauntL_02", name="Colovian Fur Gauntlet Left"},
{ID="T_Imp_ColFur_GauntR_02", name="Colovian Fur Gauntlet Right"},
{ID="T_Imp_ColFur_GauntL_04", name="Colovian Fur Gauntlet Left"},
{ID="T_Imp_ColFur_GauntR_04", name="Colovian Fur Gauntlet Right"},
{ID="T_Imp_ColIron1_GauntletL_04", name="Sarchali Iron Gauntlet Left"},
{ID="T_Imp_ColIron1_GauntletR_04", name="Sarchali Iron Gauntlet Right"},
{ID="T_Imp_ColIron1_PauldronL_04", name="Sarchali Iron Pauldron Left"},
{ID="T_Imp_ColIron1_PauldronR_04", name="Sarchali Iron Pauldron Right"},
{ID="T_Imp_ColSteel1_BracerL_04", name="Kvatchi Steel Bracer Left"},
{ID="T_Imp_ColSteel1_BracerR_04", name="Kvatchi Steel Bracer Right"},
{ID="T_Imp_ColSteel1_PauldronL_04", name="Kvatchi Steel Pauldron Left"},
{ID="T_Imp_ColSteel1_PauldronR_04", name="Kvatchi Steel Pauldron Right"},
{ID="T_Imp_GuardTown2_GauntletL_01", name="Kalantar Gauntlet Left"},
{ID="T_Imp_GuardTown2_GauntletR_01", name="Kalantar Gauntlet Right"},
{ID="T_Imp_GuardTown3_GauntletL_01", name="Klibanion Gauntlet Left"},
{ID="T_Imp_GuardTown3_GauntletR_01", name="Klibanion Gauntlet Right"},
{ID="T_Imp_GuardTown1_HelmSut_01", name="Guard Captain Helmet Sutch"},
{ID="T_Imp_GuardTown2_HelmArt_01", name="Guard Captain Helmet Artemon"},
{ID="T_Imp_GuardTown2_HelmBru_01", name="Guard Captain Helmet Bruma"},
{ID="T_Imp_GuardTown2_HelmCho_01", name="Guard Captain Helmet Chorrol"},
{ID="T_Imp_GuardTown3_HelmKva_01", name="Guard Captain Helmet Kvatch"},
{ID="T_Imp_GuardTown3_HelmSar_01", name="Guard Captain Helmet Sarchal"},
{ID="T_Imp_GuardTown3_HelmSkn_01", name="Guard Captain Helmet Skingrad"},
{ID="T_Imp_GuardTown2_PauldrL_01", name="Kalantar Pauldron Left"},
{ID="T_Imp_GuardTown2_PauldrR_01", name="Kalantar Pauldron Right"},
{ID="T_Imp_GuardTown3_PauldrL_01", name="Klibanion Pauldron Left"},
{ID="T_Imp_GuardTown3_PauldrR_01", name="Klibanion Pauldron Right"},
{ID="T_Imp_Chain_GauntletL_01", name="Imperial Chain Gauntlet Left"},
{ID="T_Imp_Chain_GauntletR_02", name="Imperial Chain Gauntlet Right"},
{ID="T_Rga_Lamellar_Bracer_L_01", name="Redguard Lamellar Bracer Left"},
{ID="T_Rga_Lamellar_Bracer_R_01", name="Redguard Lamellar Bracer Right"},
{ID="T_Com_SteelSpike_PauldronL_01", name="Steel Pauldron Left Spiked"},
{ID="T_Com_SteelSpike_PauldronR_01", name="Steel Pauldron Right Spiked"},
{ID="T_Com_IronSpike_PauldronL_01", name="Iron Pauldron Left Spiked"},
{ID="T_Com_IronSpike_PauldronR_01", name="Iron Pauldron Right Spiked"},
{ID="T_Imp_Ebony_PauldronL", name="Imperial Ebony Pauldron Left"},
{ID="T_Imp_Ebony_PauldronR", name="Imperial Ebony Pauldron Right"},
{ID="T_Imp_Ebony_BracerR", name="Imperial Ebony Bracer Right"},
{ID="T_Imp_Ebony_BracerL", name="Imperial Ebony Bracer Left"},
{ID="T_De_Chitin_PauldrL_01", name="Chitin Light Pauldron Left"},
{ID="T_De_Chitin_PauldrR_01", name="Chitin Light Pauldron Right"},
{ID="T_Imp_ColFur_HelmEx_01", name="Colovian Fur Helm Extravagant"},
{ID="T_Imp_Ep_Hat_02", name="Imperial Cap Expensive"},
{ID="T_Imp_Cm_HatColWest_02", name="Cloth Cap Common"},
{ID="T_De_BonemoldKrage_PauldronL_01", name="Kragen Bonemold Pauldron Left"},
{ID="T_De_BonemoldKrage_PauldronR_01", name="Kragen Bonemold Pauldron Right"},
{ID="T_De_Caravaner_Helm_01", name="Helm Caravaner's"},
{ID="T_De_RedBonemold_HelmOpen_01", name="Redoran Helm Open"},
{ID="T_De_IndChevAram_Helm_01", name="Chev-Aram Chitin Helm Native"},
{ID="T_De_IndChevAram_PauldrR_01", name="Chev-Aram Chitin Pauldron Right"},
{ID="T_De_IndChevAram_PauldrL_01", name="Chev-Aram Chitin Pauldron Left"},
{ID="T_De_Necrom_GauntletR_01", name="Necrom Indoril Gauntlet Right"},
{ID="T_De_Necrom_GauntletL_01", name="Necrom Indoril Gauntlet Left"},
{ID="T_De_UNI_VivecShield", name="Shield Vivec's"},
{ID="T_De_BonemoldMarad_PauldronL_01", name="Maradlai Bonemold Pauldron L"},
{ID="T_De_BonemoldMarad_PauldronR_01", name="Maradlai Bonemold Pauldron R"},
{ID="T_De_TelvCephalopod_PauldL_01", name="Telvanni Cephalopod Pauldron L"},
{ID="T_De_TelvCephalopod_PauldR_01", name="Telvanni Cephalopod Pauldron R"},
{ID="T_De_TelvCephalopod_GauntL_01", name="Telvanni Cephalopod Gauntlet L"},
{ID="T_De_TelvCephalopod_GauntR_01", name="Telvanni Cephalopod Gauntlet R"},
{ID="T_Imp_Domina_GauntletL_01", name="Domina Gauntlet Left"},
{ID="T_Imp_Domina_GauntletR_01", name="Domina Gauntlet Right"},
{ID="T_Imp_Domina_PauldronL_01", name="Domina Pauldron Left"},
{ID="T_Imp_Domina_PauldronR_01", name="Domina Pauldron Right"},
{ID="T_Imp_Gold_PauldronL_01", name="Gold Armor Pauldron Left"},
{ID="T_Imp_Gold_PauldronR_01", name="Gold Armor Pauldron Right"},
{ID="T_Dwe_Scrap_Bracer_L", name="Dwemer Scrap Bracer Left"},
{ID="T_Dwe_Scrap_Bracer_R", name="Dwemer Scrap Bracer Right"},
{ID="T_Dwe_Scrap_Pauldron_L", name="Dwemer Scrap Pauldron Left"},
{ID="T_Dwe_Scrap_Pauldron_R", name="Dwemer Scrap Pauldron Right"},
{ID="T_Imp_Reman_PauldronL_01", name="Reman Legion Pauldron Left"},
{ID="T_Imp_Reman_PauldronR_01", name="Reman Legion Pauldron Right"},
{ID="T_Imp_Reman_BracerL_01", name="Reman Legion Bracer Left"},
{ID="T_Imp_Reman_BracerR_01", name="Reman Legion Bracer Right"},
{ID="T_De_Glass_Helm_Closed_01", name="Glass Helm Closed"},
{ID="T_De_HvChit_Pauldron_L", name="Heavy Chitin Pauldron Left"},
{ID="T_De_HvChit_Pauldron_R", name="Heavy Chitin Pauldron Right"},
{ID="T_De_HvChit_Gauntlet_L", name="Heavy Chitin Gauntlet Left"},
{ID="T_De_HvChit_Gauntlet_R", name="Heavy Chitin Gauntlet Right"},
{ID="T_De_NativeEbony_GauntletL_01", name="Native Ebony Gauntlet Left"},
{ID="T_De_NativeEbony_GauntletR_01", name="Native Ebony Gauntlet Right"},
{ID="T_De_NativeEbony_HelmClosed_01", name="Native Ebony Helmet Closed"},
{ID="T_De_NativeEbony_HelmClosed_02", name="Native Ebony Helmet Closed"},
{ID="T_De_NativeEbony_HelmOpen_01", name="Native Ebony Helmet Open"},
{ID="T_De_NativeEbony_HelmOpen_02", name="Native Ebony Helmet Open"},
{ID="T_De_NativeEbony_PauldronL_01", name="Native Ebony Pauldron Left"},
{ID="T_De_NativeEbony_PauldronR_01", name="Native Ebony Pauldron Right"},
{ID="T_Com_IronSkull_PauldronL_01", name="Iron Gruesome Pauldron Left"},
{ID="T_Com_IronSkull_PauldronR_01", name="Iron Gruesome Pauldron Right"},
{ID="T_De_ThirrBonemold_Bracer_01_R", name="Native Thirr Bracer Right"},
{ID="T_De_ThirrBonemold_Bracer_01_L", name="Native Thirr Bracer Left"},
{ID="T_De_ThirrBonemold_Pauldrn_01_R", name="Native Thirr Pauldron Right"},
{ID="T_De_ThirrBonemold_Pauldrn_01_L", name="Native Thirr Pauldron Left"},
{ID="T_De_IndChevAram_BracerR_01", name="Chev-Aram Chitin Bracer Right"},
{ID="T_De_IndChevAram_BracerL_01", name="Chev-Aram Chitin Bracer Left"},
{ID="T_De_IndChevAram_Helm_02", name="Chev-Aram Chitin Helm Native"},
{ID="AB_a_CephPauldronRight", name="Cephalopod Pauldron Right"},
{ID="AB_a_CephPauldronLeft", name="Cephalopod Pauldron Left"},
{ID="AB_a_BugBluePldRight", name="Blue Bug Pauldron Right"},
{ID="AB_a_BugBluePldLeft", name="Blue Bug Pauldron Left"},
{ID="AB_a_BugGreenPldLeft", name="Green Bug Pauldron Left"},
{ID="AB_a_BugGreenPldRight", name="Green Bug Pauldron Right"},
{ID="AB_a_BugBlueGntLeft", name="Blue Bug Gauntlet Left"},
{ID="AB_a_BugBlueGntRight", name="Blue Bug Gauntlet Right"},
{ID="AB_a_BugGreenGntLeft", name="Green Bug Gauntlet Left"},
{ID="AB_a_BugGreenGntRight", name="Green Bug Gauntlet Right"},
{ID="AB_a_NetchBoilPldLeft", name="Netch Boiled Leather Pauldron L"},
{ID="AB_a_NetchBoilPldRight", name="Netch Boiled Leather Pauldron R"},
{ID="AB_a_IronDePldLeft", name="Dunmer Iron Pauldron Left"},
{ID="AB_a_IronDePldRight", name="Dunmer Iron Pauldron Right"},
{ID="AB_a_BonemLightBracerR", name="Sal-Amur Bonemold Bracer Right"},
{ID="AB_a_BonemLightBracerL", name="Sal-Amur Bonemold Bracer Left"},
{ID="AB_c_CommonHood01", name="Hood Common"},
{ID="AB_c_CommonHood02", name="Hood Common"},
{ID="AB_c_CommonHood02h", name="Hood Common"},
{ID="AB_c_CommonHood02hh", name="Hood Common"},
{ID="AB_c_CommonHood02r", name="Hood Common"},
{ID="AB_c_CommonHood02rr", name="Hood Common"},
{ID="AB_c_CommonHood02t", name="Hood Common"},
{ID="AB_c_CommonHood02tt", name="Hood Common"},
{ID="AB_c_CommonHood03", name="Hood Common"},
{ID="AB_c_CommonHood03a", name="Hood Common"},
{ID="AB_c_CommonHood03b", name="Hood Common"},
{ID="AB_c_CommonHood04", name="Hood Common"},
{ID="AB_c_CommonHood05", name="Hood Common"},
{ID="AB_c_CommonHood05a", name="Hood Common"},
{ID="AB_c_CommonHood05b", name="Hood Common"},
{ID="AB_c_CommonHood05c", name="Hood Common"},
{ID="AB_c_ExpensiveHood01", name="Hood Expensive"},
{ID="AB_c_ExpensiveHood02", name="Hood Expensive"},
{ID="AB_c_ExpensiveHood02a", name="Hood Expensive"},
{ID="AB_c_ExpensiveHood03", name="Hood Expensive"},
{ID="AB_c_ExquisiteHood01", name="Hood Exquisite"},
{ID="AB_c_ExtravagantHood01", name="Hood Extravagant"},
{ID="AB_c_ExtravagantHood01a", name="Hood Extravagant"},
{ID="AB_c_ExtravagantHood01b", name="Hood Extravagant"},
{ID="AB_c_ExtravagantHood01h", name="Hood Extravagant"},
{ID="AB_c_ExtravagantHood01r", name="Hood Extravagant"},
{ID="AB_c_ExtravagantHood01c", name="Hood Extravagant"},
{ID="AB_c_ExtravagantHood01t", name="Hood Extravagant"},
{ID="AB_c_ExtravagantHood02", name="Hood Extravagant"},
{ID="AB_a_DustBracerLeft", name="Dust Merchant Bracer Left"},
{ID="AB_a_DustBracerRight", name="Dust Merchant Bracer Right"},
{ID="AB_a_DustPldrLeft", name="Dust Merchant Pauldron Left"},
{ID="AB_a_DustPldrRight", name="Dust Merchant Pauldron Right"},
{ID="AB_a_SteelGntlLeft", name="Light Steel Gauntlet Left"},
{ID="AB_a_SteelGntlRight", name="Light Steel Gauntlet Right"},
{ID="AB_a_SteelPldrLeft", name="Light Steel Pauldron Left"},
{ID="AB_a_SteelPldrRight", name="Light Steel Pauldron Right"},
{ID="AM_meat", name="Netch Leather Gauntlet Right"},
{ID="AM_Tankard", name="Netch Leather Gauntlet Right"},
{ID="AM_cephalopod_helm", name="Cephalopod Helm"},
{ID="AM_CamonnaKnifeBracer", name="Cloth Bracer Left"},
{ID="AM_FarmerScythe", name="Slave's Bracer Right"},
{ID="AM_FarmerSack", name="Slave's Bracer Right"},
{ID="R0_netch_leather_pauldron_left_", name="Shulki's Pauldron Left"},
{ID="R0_netch_leather_pauldron_right", name="Shulki's Pauldron Right"},
{ID="tel_a_de_brcrL_mwc6_4_t", name="Cephalopod Bracer Left"},
{ID="tel_a_de_brcrR_mwc6_4_t", name="Cephalopod Bracer Right"},
{ID="tel_a_de_brcrL_mwc6_0_t", name="Cephalopod Bracer Left"},
{ID="tel_a_de_brcrR_mwc6_0_t", name="Cephalopod Bracer Right"},
{ID="tel_a_de_pldclL_mwc8_0a", name="Bonemold Pauldron Left"},
{ID="tel_a_de_pldclR_mwc8_0a", name="Bonemold Pauldron Right"},
{ID="tel_a_de_plduaL_mwc1_2", name="Bonemold Pauldron Left"},
{ID="tel_a_de_plduaR_mwc1_2", name="Bonemold Pauldron Right"},
{ID="izi_dark_cephalopod", name="Helm Manaseeker"},
{ID="izi_netch_leather_boiled_helm", name="Helm Hunter's"},
{ID="crcl_glasshelm", name="Glass Helm Ancient"},
{ID="iron_pauldron_left_rustyaf", name="Rusty Pauldron Left"},
{ID="iron_pauldron_right_rustyaf", name="Rusty Pauldron Right"},
{ID="OJ_ME_BoundPauldronLeft", name="Bound Pauldron Left"},
{ID="OJ_ME_BoundPauldronRight", name="Bound Pauldron Right"},
{ID="dnk_ceph_p_l", name="Cephalopod Pauldron Left"},
{ID="dnk_ceph_p_r", name="Cephalopod Pauldron Right"},
{ID="dnk_ceph_gaunt_l", name="Cephalopod Gauntlet Left"},
{ID="dnk_ceph_gaunt_r", name="Cephalopod Gauntlet Right"},
{ID="_dnk_ceph_p_l", name="Cephalopod Pauldron Left"},
{ID="_dnk_ceph_p_r", name="Cephalopod Pauldron Right"},
{ID="_dnk_ceph_gaunt_l", name="Cephalopod Gauntlet Left"},
{ID="_dnk_ceph_gaunt_r", name="Cephalopod Gauntlet Right"},
{ID="bonemold_gah-julan_gauntlet_l", name="Bonemold Gah-Julan Gauntlet L"},
{ID="bonemold_gah-julan_gauntlet_r", name="Bonemold Gah-Julan Gauntlet R"},
{ID="rptrl_a_de_helm_rptrl1_3c_g", name="Redoran Watchman Helm"},
{ID="rptrl_a_de_cuir_rptrl1_gnd", name="Redoran Watchman Cuirass"},
{ID="rptrl_a_de_cuir_rptrl2_gnd", name="Redoran Watchman Cuirass"},
{ID="rptrl_a_de_gntL_mwc12_gnd", name="Bonemold Gauntlet Left"},
{ID="rptrl_a_de_gntR_mwc12_gnd", name="Bonemold Gauntlet Right"},
{ID="rptrl_a_de_pldL_rptrl1_1_g", name="Redoran Watchman Pauldron Left"},
{ID="rptrl_a_de_pldR_rptrl1_1_g", name="Redoran Watchman Pauldron Right"},
{ID="if_ca_KRS_Asent_Gaunt_L", name="Aundae Sentinel's Gauntlet L"},
{ID="if_ca_KRS_Asent_Gaunt_R", name="Aundae Sentinel's Gauntlet R"},
{ID="if_ca_KRS_Asent_Pauld_L", name="Aundae Sentinel's Pauldron L"},
{ID="if_ca_KRS_Asent_Pauld_R", name="Aundae Sentinel's Pauldron R"},
{ID="BST_fine_silver_gauntlet_l", name="Fine Silver Gauntlet Left"},
{ID="BST_fine_silver_gauntlet_r", name="Fine Silver Gauntlet Right"},
{ID="BST_fine_silver_pauldron_l", name="Fine Silver Pauldron Left"},
{ID="BST_fine_silver_pauldron_r", name="Fine Silver Pauldron Right"},
{ID="darkdwemer_bracer_left", name="Dark Dwemer Bracer Left"},
{ID="darkdwemer_bracer_right", name="Dark Dwemer Bracer Right"},
{ID="darkdwemer_pauldron_left", name="Dark Dwemer Pauldron Left"},
{ID="darkdwemer_pauldron_right", name="Dark Dwemer Pauldron Right"},
{ID="KO_Goddess_Bracer_L", name="Goddess Bracer Left"},
{ID="KO_Goddess_Bracer_R", name="Goddess Bracer Right"},
{ID="KO_Elven_Right_Gauntlet", name="Elven Ordinace Gauntlet Right"},
{ID="KO_Elven_Left_Gauntlet", name="Elven Ordinace Gauntlet Left"},
{ID="BKA2_elfen_pauldl", name="Elfen Pauldron left"},
{ID="BKA2_elven_pauldr", name="Elfen Pauldron right"},
{ID="BKA2_BootsV_1", name="Fur Boots Brown Bear"},
{ID="BKA2_BootsV_2", name="Fur Boots Polar Bear"},
{ID="BKA2_BootsV_3", name="Fur Boots Blue Fox"},
{ID="BKA2_celtic_bronze", name="Armor Celtic Bronze"},
{ID="BKA2_celtic_silver", name="Armor Celtic Silver"},
{ID="BKA2_Coat_8Arm", name="Toga of the Guard A"},
{ID="BKA2_Coat_9Arm", name="Toga of the Guard Captain A"},
{ID="BKA2_Coat_of_arm3", name="Coat of Arm Red"},
{ID="BKA2_Coat_of_arm4", name="Coat of Arm Green"},
{ID="BKA2_Coat_of_arm5", name="Coat of Arm Black"},
{ID="BKA2_Coat_of_arm6", name="Coat of Arm Violet"},
{ID="BKA2_Elfen armor", name="Armor Elfen"},
{ID="BKA2_FemCoat_K01", name="Lin Corish Dress Blue"},
{ID="BKA2_FemCoat_K02", name="Lin Corish Fur Coat Brown"},
{ID="BKA2_FemCoat_K03", name="Lin Corish Wayfarer Brown"},
{ID="BKA2_FemCoat_K04", name="Lin Corish Fur Coat Polar Bear"},
{ID="BKA2_FemCoat_K05", name="Lin Corish Dress Brown"},
{ID="BKA2_FemCoat_K06", name="Lin Corish Fur Coat Blue"},
{ID="BKA2_FemCoat_K07", name="Lin Corish Magician Fur"},
{ID="BKA2_FemCoat_K08", name="Lin Corish White Robe"},
{ID="BKA2_leather_01Arm", name="Armor Celtic Leather"},
{ID="BKA2_leather_02Arm", name="Armor Leather Red"},
{ID="BKA2_leather_03Arm", name="Armor Leather Brown"},
{ID="BKA2_Livery1", name="Livery Footmen"},
{ID="BKA2_Livery10", name="Livery Imperial Crossbowman"},
{ID="BKA2_Livery2", name="Livery Archer"},
{ID="BKA2_Livery3", name="Livery Soldier"},
{ID="BKA2_Livery4", name="Livery Pikeman"},
{ID="BKA2_Livery5", name="Livery Hellebardier"},
{ID="BKA2_Livery6", name="Livery Imperial Archer"},
{ID="BKA2_Livery7", name="Livery Crossbowman Guard"},
{ID="BKA2_Livery8", name="Livery Crossbowman"},
{ID="BKA2_Livery9", name="Livery Falconer"},
{ID="BKA2_pants_1", name="Falconer Pants (Medium)"},
{ID="BKA2_pants_2 ", name="Pants Plated Brown (Light)"},
{ID="BKA2_pants_3", name="Pants Plated Orange (Light)"},
{ID="BKA2_pants_6", name="Pants Guard Brown (Light)"},
{ID="BKA2_pants_7 ", name="Pants Guard Blue (Light)"},
{ID="BKA2_pants_8", name="Veteran Wolfpants  (Medium)"},
{ID="BKA2_pants_9", name="Pants Chain Armor (Heavy)"},
{ID="BKA2_pants10", name="Veteran Pants Blue (Heavy)"},
{ID="BKA2_pants11", name="Pants Chain Plate (Heavy)"},
{ID="BKA2_pants12", name="Veteran Pants Brown (Heavy)"},
{ID="BKA2_silver_armor_02", name="Armor Silver Babarian (Medium)"},
{ID="BKA2_gold_armor_01", name="Crusader Armor Gold (Medium)"},
{ID="BKA2_silver_armor_lion", name="Crusader Armor Lion (Heavy)"},
{ID="BKA2_Coat_of_arm1", name="Crusader Coat Long"},
{ID="BKA2_silver_armor_04", name="Crusader Armor Plate (Heavy)"},
{ID="BKA2_Coat_of_arm2", name="Crusader Coat Short"},
{ID="BKA2_silver_armor_01", name="Crusader Armor Silver (Heavy)"},
{ID="BKA2_silver_armor_03", name="Crusader Armor Silver (Medium)"},
{ID="BKA2_gold_armor_02", name="Falconer Armor Gold (Light)"},
{ID="BKA2_silver_armor_05", name="Falconer Armor Silver (Light)"},
{ID="BKA2_thief_armor1", name="Thief Black Leather (Light)"},
{ID="BKA2_thief_armor2", name="Thief Tribal Brown Armor"},
{ID="BKA2_silver_armor_06", name="Veteran Armor Silver (Medium)"},
{ID="KO_Silver_Pauldron_Right", name="Silver War Maiden Pauldron R"},
{ID="KO_Festival_hat_armor", name="Hat Festival"},
{ID="KO_Festival_hat_GR_armor", name="Hat Festival Green"},
{ID="KO_Dark_Mage_Robe", name="Robe Dark Mage"},
{ID="KO_Fae_Purple_wig", name="Wif Fae Purple"},
{ID="KO_Fae_Blue_wig", name="Wig Fae Blue"},
{ID="KO_Fae_Green_wig", name="Wig Fae Green"},
{ID="KO_Fae_Pink_wig", name="Wig Fae Pink"},
{ID="KO_Floral_hat_armor", name="Hat Floral"},
{ID="KO_Black_hat_feather", name="Hat Black with Feather"},
{ID="KO_Black_hat", name="Hat Black"},
{ID="KO_Orc_Priestess_armor", name="Armor Orc Priestess"},
{ID="KO_Silver_Pauldron_Left", name="Silver War Maiden Pauldron L"},
{ID="KO_Silver_Gauntlet_L", name="Silver War Maiden Gauntlet L"},
{ID="KO_Silver_Gauntlet_R", name="Silver War Maiden Gauntlet R"},
}
