return {
{ID="p_almsivi_intervention_s", name="Potion Fool's Luck"},
{ID="p_burden_b", name="Potion Burden Bargn"},
{ID="p_burden_c", name="Potion Burden Cheap"},
{ID="p_burden_e", name="Potion Burden Exclus"},
{ID="p_burden_q", name="Potion Burden Qualty"},
{ID="p_burden_s", name="Potion Burden Std"},
{ID="p_chameleon_b", name="Potion Shadow Bargn"},
{ID="p_chameleon_c", name="Potion Shadow Cheap"},
{ID="p_chameleon_e", name="Potion Shadow Exclus"},
{ID="p_chameleon_q", name="Potion Shadow Qualty"},
{ID="p_chameleon_s", name="Potion Shadow Std"},
{ID="p_cure_blight_s", name="Potion Cure Blight Disease"},
{ID="p_cure_common_s", name="Potion Cure Common Disease"},
{ID="p_cure_paralyzation_s", name="Potion Cure Paralysis"},
{ID="p_cure_poison_s", name="Potion Cure Poison"},
{ID="p_detect_creatures_s", name="Potion Detect Creatures"},
{ID="p_detect_enchantment_s", name="Potion Detect Enchantments"},
{ID="p_detect_key_s", name="Potion Detect Key"},
{ID="p_disease_resistance_b", name="Potion Resist Disease Bargn"},
{ID="p_disease_resistance_c", name="Potion Resist Disease Cheap"},
{ID="p_disease_resistance_e", name="Potion Resist Disease Exclus"},
{ID="p_disease_resistance_q", name="Potion Resist Disease Qualty"},
{ID="p_disease_resistance_s", name="Potion Resist Disease Std"},
{ID="p_dispel_s", name="Potion Dispel"},
{ID="p_drain willpower_q", name="Spoiled Potion Cure Disease"},
{ID="p_drain_agility_q", name="Spoiled Potion Slowfalling"},
{ID="p_drain_endurance_q", name="Spoiled Potion Slowfalling"},
{ID="p_drain_intelligence_q", name="Spoiled Potion Swift Swim"},
{ID="p_drain_luck_q", name="Spoiled Potion Cure Disease"},
{ID="p_drain_magicka_q", name="Spoiled Potion Cure Poison"},
{ID="p_drain_personality_q", name="Spoiled Potion Swift Swim"},
{ID="p_drain_speed_q", name="Spoiled Potion Cure Poison"},
{ID="p_drain_strength_q", name="Spoiled Potion Cure Disease"},
{ID="p_feather_b", name="Potion Feather Bargn"},
{ID="p_feather_c", name="Potion Feather Cheap"},
{ID="p_feather_e", name="Potion Feather Exclus"},
{ID="p_feather_q", name="Potion Feather Qualty"},
{ID="p_fire resistance_s", name="Potion Resist Fire Std"},
{ID="p_fire_resistance_b", name="Potion Resist Fire Bargn"},
{ID="p_fire_resistance_c", name="Potion Resist Fire Cheap"},
{ID="p_fire_resistance_e", name="Potion Resist Fire Exclus"},
{ID="p_fire_resistance_q", name="Potion Resist Fire Qualty"},
{ID="p_fire_shield_b", name="Potion Shield Fire Bargn"},
{ID="p_fire_shield_c", name="Potion Shield Fire Cheap"},
{ID="p_fire_shield_e", name="Potion Shield Fire Exclus"},
{ID="p_fire_shield_q", name="Potion Shield Fire Qualty"},
{ID="p_fire_shield_s", name="Potion Shield Fire Std"},
{ID="p_fortify_agility_b", name="Potion Fortify Agility Bargn"},
{ID="p_fortify_agility_c", name="Potion Fortify Agility Cheap"},
{ID="p_fortify_agility_e", name="Potion Fortify Agility Exclus"},
{ID="p_fortify_agility_q", name="Potion Fortify Agility Qualty"},
{ID="p_fortify_agility_s", name="Potion Fortify Agility Std"},
{ID="p_fortify_attack_e", name="Potion Fortify Attack Exclus"},
{ID="p_fortify_endurance_b", name="Potion Fortify Endurance Bargn"},
{ID="p_fortify_endurance_c", name="Potion Fortify Endurance Cheap"},
{ID="p_fortify_endurance_e", name="Potion Fortify Endurance Exclus"},
{ID="p_fortify_endurance_q", name="Potion Fortify Endurance Qualty"},
{ID="p_fortify_endurance_s", name="Potion Fortify Endurance Std"},
{ID="p_fortify_fatigue_b", name="Potion Fortify Fatigue Bargn"},
{ID="p_fortify_fatigue_c", name="Potion Fortify Fatigue Cheap"},
{ID="p_fortify_fatigue_e", name="Potion Fortify Fatigue Exclus"},
{ID="p_fortify_fatigue_q", name="Potion Fortify Fatigue Qualty"},
{ID="p_fortify_fatigue_s", name="Potion Fortify Fatigue Std"},
{ID="p_fortify_health_b", name="Potion Fortify Health Bargn"},
{ID="p_fortify_health_c", name="Potion Fortify Health Cheap"},
{ID="p_fortify_health_e", name="Potion Fortify Health Exclus"},
{ID="p_fortify_health_q", name="Potion Fortify Health Qualty"},
{ID="p_fortify_health_s", name="Potion Fortify Health Std"},
{ID="p_fortify_intelligence_b", name="Potion Fortify Intellect Bargn"},
{ID="p_fortify_intelligence_c", name="Potion Fortify Intellect Cheap"},
{ID="p_fortify_intelligence_e", name="Potion Fortify Intellect Exclus"},
{ID="p_fortify_intelligence_q", name="Potion Fortify Intellect Qualty"},
{ID="p_fortify_intelligence_s", name="Potion Fortify Intellect Std"},
{ID="p_fortify_luck_b", name="Potion Fortify Luck Bargn"},
{ID="p_fortify_luck_c", name="Potion Fortify Luck Cheap"},
{ID="p_fortify_luck_e", name="Potion Fortify Luck Exclus"},
{ID="p_fortify_luck_q", name="Potion Fortify Luck Qualty"},
{ID="p_fortify_luck_s", name="Potion Fortify Luck Std"},
{ID="p_fortify_magicka_b", name="Potion Fortify Magicka Bargn"},
{ID="p_fortify_magicka_c", name="Potion Fortify Magicka Cheap"},
{ID="p_fortify_magicka_e", name="Potion Fortify Magicka Exclus"},
{ID="p_fortify_magicka_q", name="Potion Fortify Magicka Qualty"},
{ID="p_fortify_magicka_s", name="Potion Fortify Magicka Std"},
{ID="p_fortify_personality_b", name="Potion Fortify Persona Bargn"},
{ID="p_fortify_personality_c", name="Potion Fortify Persona Cheap"},
{ID="p_fortify_personality_e", name="Potion Fortify Persona Exclus"},
{ID="p_fortify_personality_q", name="Potion Fortify Persona Qualty"},
{ID="p_fortify_personality_s", name="Potion Fortify Persona Std"},
{ID="p_fortify_speed_b", name="Potion Fortify Speed Bargn"},
{ID="p_fortify_speed_c", name="Potion Fortify Speed Cheap"},
{ID="p_fortify_speed_e", name="Potion Fortify Speed Exclus"},
{ID="p_fortify_speed_q", name="Potion Fortify Speed Qualty"},
{ID="p_fortify_speed_s", name="Potion Fortify Speed Std"},
{ID="p_fortify_strength_b", name="Potion Fortify Strength Bargn"},
{ID="p_fortify_strength_c", name="Potion Fortify Strength Cheap"},
{ID="p_fortify_strength_e", name="Potion Fortify Strength Exclus"},
{ID="p_fortify_strength_q", name="Potion Fortify Strength Qualty"},
{ID="p_fortify_strength_s", name="Potion Fortify Strength Std"},
{ID="p_fortify_willpower_b", name="Potion Fortify Willpower Bargn"},
{ID="p_fortify_willpower_c", name="Potion Fortify Willpower Cheap"},
{ID="p_fortify_willpower_e", name="Potion Fortify Willpower Exclus"},
{ID="p_fortify_willpower_q", name="Potion Fortify Willpower Qualty"},
{ID="p_fortify_willpower_s", name="Potion Fortify Willpower Std"},
{ID="p_frost_resistance_b", name="Potion Resist Frost Bargn"},
{ID="p_frost_resistance_c", name="Potion Resist Frost Cheap"},
{ID="p_frost_resistance_e", name="Potion Resist Frost Exclus"},
{ID="p_frost_resistance_q", name="Potion Resist Frost Qualty"},
{ID="p_frost_resistance_s", name="Potion Resist Frost Std"},
{ID="p_frost_shield_b", name="Potion Shield Frost Bargn"},
{ID="p_frost_shield_c", name="Potion Shield Frost Cheap"},
{ID="p_frost_shield_e", name="Potion Shield Frost Exclus"},
{ID="p_frost_shield_q", name="Potion Shield Frost Qualty"},
{ID="p_frost_shield_s", name="Potion Shield Frost Std"},
{ID="p_heroism_s", name="Potion Heroism"},
{ID="p_invisibility_b", name="Potion Invisibility Bargn"},
{ID="p_invisibility_c", name="Potion Invisibility Cheap"},
{ID="p_invisibility_e", name="Potion Invisibility Exclus"},
{ID="p_invisibility_q", name="Potion Invisibility Qualty"},
{ID="p_invisibility_s", name="Potion Invisibility Std"},
{ID="p_jump_b", name="Potion Jump Bargn"},
{ID="p_jump_c", name="Potion Jump Cheap"},
{ID="p_jump_e", name="Potion Jump Exclus"},
{ID="p_jump_q", name="Potion Jump Qualty"},
{ID="p_jump_s", name="Potion Jump Std"},
{ID="p_levitation_b", name="Potion Rising Force Bargn"},
{ID="p_levitation_c", name="Potion Rising Force Cheap"},
{ID="p_levitation_e", name="Potion Rising Force Exclus"},
{ID="P_Levitation_Q", name="Potion Rising Force Qualty"},
{ID="p_levitation_s", name="Potion Rising Force Std"},
{ID="p_light_b", name="Potion Light Bargn"},
{ID="p_light_c", name="Potion Light Cheap"},
{ID="p_light_e", name="Potion Light Exclus"},
{ID="p_light_q", name="Potion Light Qualty"},
{ID="p_light_s", name="Potion Light Std"},
{ID="p_lightning shield_b", name="Potion Shield Lightning Bargn"},
{ID="p_lightning shield_c", name="Potion Shield Lightning Cheap"},
{ID="p_lightning shield_e", name="Potion Shield Lightning Exclus"},
{ID="p_lightning shield_q", name="Potion Shield Lightning Qualty"},
{ID="p_lightning shield_s", name="Potion Shield Lightning Std"},
{ID="p_magicka_resistance_b", name="Potion Resist Magicka Bargn"},
{ID="p_magicka_resistance_c", name="Potion Resist Magicka Cheap"},
{ID="p_magicka_resistance_e", name="Potion Resist Magicka Exclus"},
{ID="p_magicka_resistance_q", name="Potion Resist Magicka Qualty"},
{ID="p_magicka_resistance_s", name="Potion Resist Magicka Std"},
{ID="p_night-eye_b", name="Potion Night-Eye Bargn"},
{ID="p_night-eye_c", name="Potion Night-Eye Cheap"},
{ID="p_night-eye_e", name="Potion Night-Eye Exclus"},
{ID="p_night-eye_q", name="Potion Night-Eye Qualty"},
{ID="p_night-eye_s", name="Potion Night-Eye Std"},
{ID="p_paralyze_b", name="Potion Paralyze Bargn"},
{ID="p_paralyze_c", name="Potion Paralyze Cheap"},
{ID="p_paralyze_e", name="Potion Paralyze Exclus"},
{ID="p_paralyze_q", name="Potion Paralyze Qualty"},
{ID="p_paralyze_s", name="Potion Paralyze Std"},
{ID="p_poison_resistance_b", name="Potion Resist Poison Bargn"},
{ID="p_poison_resistance_c", name="Potion Resist Poison Cheap"},
{ID="p_poison_resistance_e", name="Potion Resist Poison Exclus"},
{ID="p_poison_resistance_q", name="Potion Resist Poison Qualty"},
{ID="p_poison_resistance_s", name="Potion Resist Poison Std"},
{ID="p_reflection_b", name="Potion Reflection Bargn"},
{ID="p_reflection_c", name="Potion Reflection Cheap"},
{ID="p_reflection_e", name="Potion Reflection Exclus"},
{ID="p_reflection_q", name="Potion Reflection Qualty"},
{ID="p_reflection_s", name="Potion Reflection Std"},
{ID="p_restore_agility_b", name="Potion Restore Agility Bargn"},
{ID="p_restore_agility_c", name="Potion Restore Agility Cheap"},
{ID="p_restore_agility_e", name="Potion Restore Agility Exclus"},
{ID="p_restore_agility_q", name="Potion Restore Agility Qualty"},
{ID="p_restore_agility_s", name="Potion Restore Agility Std"},
{ID="p_restore_endurance_b", name="Potion Restore Endurance Bargn"},
{ID="p_restore_endurance_c", name="Potion Restore Endurance Cheap"},
{ID="p_restore_endurance_e", name="Potion Restore Endurance Exclus"},
{ID="p_restore_endurance_q", name="Potion Restore Endurance Qualty"},
{ID="p_restore_endurance_s", name="Potion Restore Endurance Std"},
{ID="p_restore_fatigue_b", name="Potion Restore Fatigue Bargn"},
{ID="p_restore_fatigue_c", name="Potion Restore Fatigue Cheap"},
{ID="p_restore_fatigue_e", name="Potion Restore Fatigue Exclus"},
{ID="p_restore_fatigue_q", name="Potion Restore Fatigue Qualty"},
{ID="p_restore_fatigue_s", name="Potion Restore Fatigue Std"},
{ID="p_restore_health_b", name="Potion Restore Health Bargn"},
{ID="p_restore_health_c", name="Potion Restore Health Cheap"},
{ID="p_restore_health_e", name="Potion Restore Health Exclus"},
{ID="p_restore_health_q", name="Potion Restore Health Qualty"},
{ID="p_restore_health_s", name="Potion Restore Health Std"},
{ID="p_restore_intelligence_b", name="Potion Restore Intellect Bargn"},
{ID="p_restore_intelligence_c", name="Potion Restore Intellect Cheap"},
{ID="p_restore_intelligence_e", name="Potion Restore Intellect Exclus"},
{ID="p_restore_intelligence_q", name="Potion Restore Intellect Qualty"},
{ID="p_restore_intelligence_s", name="Potion Restore Intellect Std"},
{ID="p_restore_luck_b", name="Potion Restore Luck Bargn"},
{ID="p_restore_luck_c", name="Potion Restore Luck Cheap"},
{ID="p_restore_luck_e", name="Potion Restore Luck Exclus"},
{ID="p_restore_luck_q", name="Potion Restore Luck Qualty"},
{ID="p_restore_luck_s", name="Potion Restore Luck Std"},
{ID="p_restore_magicka_b", name="Potion Restore Magicka Bargn"},
{ID="p_restore_magicka_c", name="Potion Restore Magicka Cheap"},
{ID="p_restore_magicka_e", name="Potion Restore Magicka Exclus"},
{ID="p_restore_magicka_q", name="Potion Restore Magicka Qualty"},
{ID="p_restore_magicka_s", name="Potion Restore Magicka Std"},
{ID="p_restore_personality_b", name="Potion Restore Persona Bargn"},
{ID="p_restore_personality_c", name="Potion Restore Persona Cheap"},
{ID="p_restore_personality_e", name="Potion Restore Persona Exclus"},
{ID="p_restore_personality_q", name="Potion Restore Persona Qualty"},
{ID="p_restore_personality_s", name="Potion Restore Persona Std"},
{ID="p_restore_speed_b", name="Potion Restore Speed Bargn"},
{ID="p_restore_speed_c", name="Potion Restore Speed Cheap"},
{ID="p_restore_speed_e", name="Potion Restore Speed Exclus"},
{ID="p_restore_speed_q", name="Potion Restore Speed Qualty"},
{ID="p_restore_speed_s", name="Potion Restore Speed Std"},
{ID="p_restore_strength_b", name="Potion Restore Strength Bargn"},
{ID="p_restore_strength_c", name="Potion Restore Strength Cheap"},
{ID="p_restore_strength_e", name="Potion Restore Strength Exclus"},
{ID="p_restore_strength_q", name="Potion Restore Strength Qualty"},
{ID="p_restore_strength_s", name="Potion Restore Strength Std"},
{ID="p_restore_willpower_b", name="Potion Restore Willpower Bargn"},
{ID="p_restore_willpower_c", name="Potion Restore Willpower Cheap"},
{ID="p_restore_willpower_e", name="Potion Restore Willpower Exclus"},
{ID="p_restore_willpower_q", name="Potion Restore Willpower Qualty"},
{ID="p_restore_willpower_s", name="Potion Restore Willpower Std"},
{ID="p_shock_resistance_b", name="Potion Resist Shock Bargn"},
{ID="p_shock_resistance_c", name="Potion Resist Shock Cheap"},
{ID="p_shock_resistance_e", name="Potion Resist Shock Exclus"},
{ID="p_shock_resistance_q", name="Potion Resist Shock Qualty"},
{ID="p_shock_resistance_s", name="Potion Resist Shock Std"},
{ID="p_silence_b", name="Potion Silence Bargn"},
{ID="p_silence_c", name="Potion Silence Cheap"},
{ID="p_silence_e", name="Potion Silence Exclus"},
{ID="p_silence_q", name="Potion Silence Qualty"},
{ID="p_silence_s", name="Potion Silence Std"},
{ID="p_slowfall_s", name="Potion Slowfalling"},
{ID="p_spell_absorption_b", name="Potion Spell Absorption Bargn"},
{ID="p_spell_absorption_c", name="Potion Spell Absorption Cheap"},
{ID="p_spell_absorption_e", name="Potion Spell Absorption Exclus"},
{ID="p_spell_absorption_q", name="Potion Spell Absorption Qualty"},
{ID="p_spell_absorption_s", name="Potion Spell Absorption Std"},
{ID="p_swift_swim_b", name="Potion Swift Swim Bargn"},
{ID="p_swift_swim_c", name="Potion Swift Swim Cheap"},
{ID="p_swift_swim_e", name="Potion Swift Swim Exclus"},
{ID="p_swift_swim_q", name="Potion Swift Swim Qualty"},
{ID="p_telekinesis_s", name="Potion Telekinesis"},
{ID="p_water_breathing_s", name="Potion Water Breathing"},
{ID="p_water_walking_s", name="Potion Water Walking"},
{ID="AB_dri_TramaTea", name="Tea Trama Root"},
{ID="ab01p_water_breathing_e", name="Potion Water Breathing Exclus"},
{ID="ab01p_water_breathing_q", name="Potion Water Breathing Qualty"},
{ID="KO_CMK_Teacup", name="Tea Hot"},
{ID="ks_water_walking_p", name="Potion Water Walking Extra"},
{ID="MWlib_teamug_01", name="Tea Black"},
{ID="MWlib_teamug_02", name="Tea White"},
{ID="MWlib_teamug_03", name="Tea Red"},
{ID="MWlib_teamug_04", name="Tea Green"},
{ID="MWlib_teamug_05", name="Tea Nori Salt"},
{ID="MWlib_teamug_06", name="Tea Pink"},
{ID="MWlib_teamug_07", name="Tea Ginger Spice"},
{ID="MWlib_teamug_08", name="Tea Golden"},
{ID="MWlib_teamug_09", name="Tea Dragon"},
{ID="PB_ASP_Potion2", name="Nirnroot Elixir of Quality"},
{ID="T_Com_Potion_ResistParalysis_B", name="Potion Resist Paralysis Bargn"},
{ID="T_Com_Potion_ResistParalysis_C", name="Potion Resist Paralysis Cheap"},
{ID="T_Com_Potion_ResistParalysis_E", name="Potion Resist Paralysis Exclus"},
{ID="T_Com_Potion_ResistParalysis_Q", name="Potion Resist Paralysis Qualty"},
{ID="T_Com_Potion_ResistParalysis_S", name="Potion Resist Paralysis Std"},
{ID="T_Nor_Drink_BeerLight_01", name="Beer Light"},
{ID="T_Nor_Potion_Burden_C", name="Potion Burden Cheap"},
{ID="T_Nor_Potion_Burden_Q", name="Potion Burden Qualty"},
{ID="T_Nor_Potion_Chameleon_C", name="Potion Shadow Cheap"},
{ID="T_Nor_Potion_Chameleon_Q", name="Potion Shadow Qualty"},
{ID="T_Nor_Potion_CureCommon_01", name="Potion Cure Common Disease+"},
{ID="T_Nor_Potion_DrainAgility_Q", name="Spoiled Potion SlowFall"},
{ID="T_Nor_Potion_DrainEndurance_Q", name="Spoiled Potion SlowFall"},
{ID="T_Nor_Potion_DrainIntelli_Q", name="Spoiled Potion Swift Swim"},
{ID="T_Nor_Potion_DrainLuck_Q", name="Spoiled Potion Cure Disease"},
{ID="T_Nor_Potion_DrainMagicka_Q", name="Spoiled Potion Cure Poison"},
{ID="T_Nor_Potion_DrainPersonality_Q", name="Spoiled Potion Swift Swim"},
{ID="T_Nor_Potion_DrainSpeed_Q", name="Spoiled Potion Cure Poison"},
{ID="T_Nor_Potion_DrainStrength_Q", name="Spoiled Potion Cure Disease"},
{ID="T_Nor_Potion_DrainWillpow_Q", name="Spoiled Potion Cure Disease"},
{ID="T_Nor_Potion_Feather_C", name="Potion Feather Cheap"},
{ID="T_Nor_Potion_Feather_Q", name="Potion Feather Qualty"},
{ID="T_Nor_Potion_FortifyAgility_C", name="Potion Fortify Agility Cheap"},
{ID="T_Nor_Potion_FortifyAgility_Q", name="Potion Fortify Agility Qualty"},
{ID="T_Nor_Potion_FortifyEndurance_C", name="Potion Fortify Endurance Cheap"},
{ID="T_Nor_Potion_FortifyEndurance_Q", name="Potion Fortify Endurance Qualty"},
{ID="T_Nor_Potion_FortifyFatigue_C", name="Potion Fortify Fatigue Cheap"},
{ID="T_Nor_Potion_FortifyFatigue_Q", name="Potion Fortify Fatigue Qualty"},
{ID="T_Nor_Potion_FortifyHealth_C", name="Potion Fortify Health Cheap"},
{ID="T_Nor_Potion_FortifyHealth_Q", name="Potion Fortify Health Qualty"},
{ID="T_Nor_Potion_FortifyIntell_C", name="Potion Fortify Intellect Cheap"},
{ID="T_Nor_Potion_FortifyIntelli_Q", name="Potion Fortify Intellect Qualty"},
{ID="T_Nor_Potion_FortifyLuck_C", name="Potion Fortify Luck Cheap"},
{ID="T_Nor_Potion_FortifyLuck_Q", name="Potion Fortify Luck Qualty"},
{ID="T_Nor_Potion_FortifyMagicka_C", name="Potion Fortify Magicka Cheap"},
{ID="T_Nor_Potion_FortifyMagicka_Q", name="Potion Fortify Magicka Qualty"},
{ID="T_Nor_Potion_FortifyPersonal_C", name="Potion Fortify Persona Cheap"},
{ID="T_Nor_Potion_FortifyPersonal_Q", name="Potion Fortify Persona Qualty"},
{ID="T_Nor_Potion_FortifySpeed_C", name="Potion Fortify Speed Cheap"},
{ID="T_Nor_Potion_FortifySpeed_Q", name="Potion Fortify Speed Qualty"},
{ID="T_Nor_Potion_FortifyStrength_C", name="Potion Fortify Strength Cheap"},
{ID="T_Nor_Potion_FortifyStrength_Q", name="Potion Fortify Strength Qualty"},
{ID="T_Nor_Potion_FortifyWillpow_C", name="Potion Fortify Willpower Cheap"},
{ID="T_Nor_Potion_FortifyWillpow_Q", name="Potion Fortify Willpower Qualty"},
{ID="T_Nor_Potion_Invisibility_C", name="Potion Invisibility Cheap"},
{ID="T_Nor_Potion_Invisibility_Q", name="Potion Invisibility Qualty"},
{ID="T_Nor_Potion_Jump_C", name="Potion Jump Cheap"},
{ID="T_Nor_Potion_Jump_Q", name="Potion Jump Qualty"},
{ID="T_Nor_Potion_Levitation_C", name="Potion Levitation Cheap"},
{ID="T_Nor_Potion_Levitation_Q", name="Potion Rising Force Qualty"},
{ID="T_Nor_Potion_Light_C", name="Potion Light Cheap"},
{ID="T_Nor_Potion_Light_Q", name="Potion Light Qualty"},
{ID="T_Nor_Potion_NightEye_C", name="Potion Night-Eye Cheap"},
{ID="T_Nor_Potion_NightEye_Q", name="Potion Night-Eye Qualty"},
{ID="T_Nor_Potion_Paralyze_C", name="Potion Paralyze Cheap"},
{ID="T_Nor_Potion_Paralyze_Q", name="Potion Paralyze Qualty"},
{ID="T_Nor_Potion_Reflection_C", name="Potion Reflection Cheap"},
{ID="T_Nor_Potion_Reflection_Q", name="Potion Reflection Qualty"},
{ID="T_Nor_Potion_ResistDesease_C", name="Potion Resist Disease Cheap"},
{ID="T_Nor_Potion_ResistDisease_Q", name="Potion Resist Disease Qualty"},
{ID="T_Nor_Potion_ResistFire_C", name="Potion Resist Fire Cheap"},
{ID="T_Nor_Potion_ResistFire_Q", name="Potion Resist Fire Qualty"},
{ID="T_Nor_Potion_ResistFrost_C", name="Potion Resist Frost Cheap"},
{ID="T_Nor_Potion_ResistFrost_Q", name="Potion Resist Frost Qualty"},
{ID="T_Nor_Potion_ResistMagicka_C", name="Potion Resist Magicka Cheap"},
{ID="T_Nor_Potion_ResistMagicka_Q", name="Potion Resist Magicka Qualty"},
{ID="T_Nor_Potion_ResistPoison_C", name="Potion Resist Poison Cheap"},
{ID="T_Nor_Potion_ResistPoison_Q", name="Potion Resist Poison Qualty"},
{ID="T_Nor_Potion_ResistShock_C", name="Potion Resist Shock Cheap"},
{ID="T_Nor_Potion_ResistShock_Q", name="Potion Resist Shock Qualty"},
{ID="T_Nor_Potion_RestoreAgility_C", name="Potion Restore Agility Cheap"},
{ID="T_Nor_Potion_RestoreAgility_Q", name="Potion Restore Agility Qualty"},
{ID="T_Nor_Potion_RestoreEnduranc_C", name="Potion Restore Endurance Cheap"},
{ID="T_Nor_Potion_RestoreEndurance_Q", name="Potion Restore Endurance Qualty"},
{ID="T_Nor_Potion_RestoreFatigue_C", name="Potion Restore Fatigue Cheap"},
{ID="T_Nor_Potion_RestoreFatigue_Q", name="Potion Restore Fatigue Qualty"},
{ID="T_Nor_Potion_RestoreHealth_C", name="Potion Restore Health Cheap"},
{ID="T_Nor_Potion_RestoreHealth_Q", name="Potion Restore Health Qualty"},
{ID="T_Nor_Potion_RestoreIntelli_C", name="Potion Restore Intellect Cheap"},
{ID="T_Nor_Potion_RestoreIntelli_Q", name="Potion Restore Intellect Qualty"},
{ID="T_Nor_Potion_RestoreLuck_C", name="Potion Restore Luck Cheap"},
{ID="T_Nor_Potion_RestoreLuck_Q", name="Potion Restore Luck Qualty"},
{ID="T_Nor_Potion_RestoreMagicka_C", name="Potion Restore Magicka Cheap"},
{ID="T_Nor_Potion_RestoreMagicka_Q", name="Potion Restore Magicka Qualty"},
{ID="T_Nor_Potion_RestorePersonal_C", name="Potion Restore Persona Cheap"},
{ID="T_Nor_Potion_RestorePersonal_Q", name="Potion Restore Persona Qualty"},
{ID="T_Nor_Potion_RestoreSpeed_C", name="Potion Restore Speed Cheap"},
{ID="T_Nor_Potion_RestoreSpeed_Q", name="Potion Restore Speed Qualty"},
{ID="T_Nor_Potion_RestoreStrength_C", name="Potion Restore Strength Cheap"},
{ID="T_Nor_Potion_RestoreStrength_Q", name="Potion Restore Strength Qualty"},
{ID="T_Nor_Potion_RestoreWillpow_C", name="Potion Restore Willpower Cheap"},
{ID="T_Nor_Potion_RestoreWillpow_Q", name="Potion Restore Willpower Qualty"},
{ID="T_Nor_Potion_ShieldFire_C", name="Potion Shield Fire Cheap"},
{ID="T_Nor_Potion_ShieldFire_Q", name="Potion Shield Fire Qualty"},
{ID="T_Nor_Potion_ShieldFrost_C", name="Potion Shield Frost Cheap"},
{ID="T_Nor_Potion_ShieldFrost_Q", name="Potion Shield Frost Qualty"},
{ID="T_Nor_Potion_ShieldLightning_C", name="Potion Shield Lightning Cheap"},
{ID="T_Nor_Potion_ShieldLightning_Q", name="Potion Shield Lightning Qualty"},
{ID="T_Nor_Potion_Silence_C", name="Potion Silence Cheap"},
{ID="T_Nor_Potion_Silence_Q", name="Potion Silence Qualty"},
{ID="T_Nor_Potion_SpellAbsorbtion_C", name="Potion Spell Absorption Cheap"},
{ID="T_Nor_Potion_SpellAbsorbtion_Q", name="Potion Spell Absorption Qualty"},
{ID="T_Nor_Potion_SwiftSwim_C", name="Potion Swift Swim Cheap"},
{ID="T_Nor_Potion_Swiftswim_Q", name="Potion Swift Swim Qualty"},
}
