return {
    "of zenithar",
    "of akatosh",
    "of arkay",
    "of talos",
    "of dibella",
    "of julianos",
    "of mara",
    "oracle",
    "of stendarr",
    "handmaiden",
    "of kynareth",
    "disciple",
    "of julianos",
    "novice",
    "of stendarr",
    "adept",
    "servant",
    "invoker",
    "daughter",
    "acolyte",
}
