local ssqn = include("SSQN.interop")
if not ssqn then
	print("SSQN interop not available")
	return
end


ssqn.blockQBanner("a1_dreams")
ssqn.blockQBanner("a1_sleepers_alvura")
ssqn.blockQBanner("a1_sleepers_assi")
ssqn.blockQBanner("a1_sleepers_daynasa")
ssqn.blockQBanner("a1_sleepers_dralas")
ssqn.blockQBanner("a1_sleepers_drarayne")
ssqn.blockQBanner("a1_sleepers_dravasa")
ssqn.blockQBanner("a1_sleepers_endris")
ssqn.blockQBanner("a1_sleepers_eralane")
ssqn.blockQBanner("a1_sleepers_llandras")
ssqn.blockQBanner("a1_sleepers_neldris")
ssqn.blockQBanner("a1_sleepers_nelmil")
ssqn.blockQBanner("a1_sleepers_rararyn")
ssqn.blockQBanner("a1_sleepers_relur")
ssqn.blockQBanner("a1_sleepers_vireveri")
ssqn.blockQBanner("a1_sleepers_vivyne")

ssqn.blockQBanner("a2_4_milo_hola_go")
ssqn.blockQBanner("a2_4_milocaiusgone")
ssqn.blockQBanner("a2_4_milogone_books")
ssqn.blockQBanner("a2_4_miloprisonsafe")

ssqn.blockQBanner("a2_6_ane_teria")
ssqn.blockQBanner("a2_6_conoon")
ssqn.blockQBanner("a2_6_erur-dan")
ssqn.blockQBanner("a2_6_hort-ledd")
ssqn.blockQBanner("a2_6_idrenie")
ssqn.blockQBanner("a2_6_peakstar")

ssqn.blockQBanner("b2_ahemmusakill")
ssqn.blockQBanner("b2_ahemmusawalk")
ssqn.blockQBanner("b2a_kausi")
ssqn.blockQBanner("b2b_dutadalk")
ssqn.blockQBanner("b2c_yenammu")

ssqn.blockQBanner("b4_erabenimsunkill")
ssqn.blockQBanner("b4_heartfire")
ssqn.blockQBanner("b4_robe")
ssqn.blockQBanner("b4_waraxe")
ssqn.blockQBanner("b4_warloverkill")

ssqn.blockQBanner("b5_arobarhort")
ssqn.blockQBanner("b5_llethrihort")
ssqn.blockQBanner("b5_morvaynhort")
ssqn.blockQBanner("b5_ramoranhort")
ssqn.blockQBanner("b5_redoranbook")
ssqn.blockQBanner("b5_sarethihort")
ssqn.blockQBanner("b5_venimhort")

ssqn.blockQBanner("b6_berohort")
ssqn.blockQBanner("b6_curiohort")
ssqn.blockQBanner("b6_drenhortator")
ssqn.blockQBanner("b6_hlaalubook")
ssqn.blockQBanner("b6_omanihort")
ssqn.blockQBanner("b6_uleshort")
ssqn.blockQBanner("b6_ynglinghort")

ssqn.blockQBanner("b7_aryonhort")
ssqn.blockQBanner("b7_baladashort")
ssqn.blockQBanner("b7_drathahort")
ssqn.blockQBanner("b7_gothrenhort")
ssqn.blockQBanner("b7_nelothhort")
ssqn.blockQBanner("b7_telvannibook")
ssqn.blockQBanner("b7_theranahort")

ssqn.blockQBanner("b8_all_hortator")
ssqn.blockQBanner("b8_all_nerevarine")
ssqn.blockQBanner("b8_backdoor1")
ssqn.blockQBanner("b8_backdoor2")
ssqn.blockQBanner("b8_backdoor3")
ssqn.blockQBanner("b8_backdoor4")
ssqn.blockQBanner("b8_backdoor5")
ssqn.blockQBanner("b8_backdoor6")
ssqn.blockQBanner("b8_failed_nerevarine")
ssqn.blockQBanner("b8_nibani_2_vivec")

ssqn.blockQBanner("c0_act_c_expo")
ssqn.blockQBanner("c2_sunder")


ssqn.blockQBanner("ic10_aengoth")
ssqn.blockQBanner("ic10_baradras")
ssqn.blockQBanner("ic10_buckmoth_not")
ssqn.blockQBanner("ic10_cienne")
ssqn.blockQBanner("ic10_codus")
ssqn.blockQBanner("ic10_dular")
ssqn.blockQBanner("ic10_edwinna")
ssqn.blockQBanner("ic10_erranil")
ssqn.blockQBanner("ic10_estoril")
ssqn.blockQBanner("ic10_galthragoth")
ssqn.blockQBanner("ic10_hoki")
ssqn.blockQBanner("ic10_lirielle")
ssqn.blockQBanner("ic10_malpenix")
ssqn.blockQBanner("ic10_manis")
ssqn.blockQBanner("ic10_merthierry")
ssqn.blockQBanner("ic10_persius")
ssqn.blockQBanner("ic10_tauryon")
ssqn.blockQBanner("ic10_tongue")
ssqn.blockQBanner("ic10_yak")

ssqn.blockQBanner("ic12_bacola")
ssqn.blockQBanner("ic12_banor")
ssqn.blockQBanner("ic12_benunius")
ssqn.blockQBanner("ic12_dulnea")

ssqn.blockQBanner("ic13_fight")
ssqn.blockQBanner("ic13_rumor")
ssqn.blockQBanner("ic13_slave")

ssqn.blockQBanner("ic14_delay")
ssqn.blockQBanner("ic14_demand")
ssqn.blockQBanner("ic14_flacassia")
ssqn.blockQBanner("ic14_mossanon")
ssqn.blockQBanner("ic14_nottell")
ssqn.blockQBanner("ic14_okan")
ssqn.blockQBanner("ic14_promise")
ssqn.blockQBanner("ic14_shazgob")
ssqn.blockQBanner("ic14_sinyaramen")
ssqn.blockQBanner("ic14_tell")

ssqn.blockQBanner("ic8_bedraflod")
ssqn.blockQBanner("ic8_briring")
ssqn.blockQBanner("ic8_eiruki")
ssqn.blockQBanner("ic8_heidmir")
ssqn.blockQBanner("ic8_ingokning")

ssqn.blockQBanner("ic9_slave_hiding")

ssqn.blockQBanner("tr08_hlaalu_a")
ssqn.blockQBanner("tr08_hlaalu_alen")
ssqn.blockQBanner("tr08_hlaalu_alen_a")
ssqn.blockQBanner("tr08_hlaalu_berano")
ssqn.blockQBanner("tr08_hlaalu_berano_a")
ssqn.blockQBanner("tr08_hlaalu_hloggar")
ssqn.blockQBanner("tr08_hlaalu_hloggar_a")
ssqn.blockQBanner("tr08_hlaalu_ravani")


