local I       = require('openmw.interfaces')
local shared  = require('scripts.gshared')
local DEFAULTS = shared.DEFAULTS

I.Settings.registerGroup {
    key              = 'SettingsGreedyNPCs',
    page             = 'GreedyNPCs',
    l10n             = 'GreedyNPCs',
    name             = 'settings_groupName',
    permanentStorage = true,
    order            = 1,
    settings = {
        {
            key         = 'PICKUP_ENABLED',
            name        = 'pickup_enabled_name',
            description = 'pickup_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.PICKUP_ENABLED,
        },
        {
            key         = 'CRIME_ENABLED',
            name        = 'crime_enabled_name',
            description = 'crime_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.CRIME_ENABLED,
        },
        {
            key         = 'RANK_EXEMPT_ENABLED',
            name        = 'rank_exempt_enabled_name',
            description = 'rank_exempt_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.RANK_EXEMPT_ENABLED,
        },
        {
            key         = 'RANK_EXEMPT_DIFF',
            name        = 'rank_exempt_diff_name',
            description = 'rank_exempt_diff_desc',
            renderer    = 'number',
            default     = DEFAULTS.RANK_EXEMPT_DIFF,
            argument    = { integer = true, min = 1, max = 9 },
        },
        {
            key         = 'PICKUP_RADIUS',
            name        = 'pickup_radius_name',
            description = 'pickup_radius_desc',
            renderer    = 'number',
            default     = DEFAULTS.PICKUP_RADIUS,
            argument    = { integer = true, min = 50, max = 1000 },
        },
        {
            key         = 'CONTRABAND_RADIUS',
            name        = 'contraband_radius_name',
            description = 'contraband_radius_desc',
            renderer    = 'number',
            default     = DEFAULTS.CONTRABAND_RADIUS,
            argument    = { integer = true, min = 100, max = 2000 },
        },
        {
            key         = 'PICKUP_DELAY',
            name        = 'pickup_delay_name',
            description = 'pickup_delay_desc',
            renderer    = 'number',
            default     = DEFAULTS.PICKUP_DELAY,
            argument    = { min = 0.5, max = 30.0 },
        },
        {
            key         = 'CHAMELEON_THRESHOLD',
            name        = 'chameleon_threshold_name',
            description = 'chameleon_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.CHAMELEON_THRESHOLD,
            argument    = { integer = true, min = 1, max = 100 },
        },
        {
            key         = 'SNEAK_THRESHOLD',
            name        = 'sneak_threshold_name',
            description = 'sneak_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.SNEAK_THRESHOLD,
            argument    = { integer = true, min = 1, max = 100 },
        },
        {
            key         = 'SIGN_COMPAT',
            name        = 'sign_compat_name',
            description = 'sign_compat_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.SIGN_COMPAT,
        },
        {
            key         = 'ESCORT_FOLLOW_BUSY',
            name        = 'escort_follow_busy_name',
            description = 'escort_follow_busy_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.ESCORT_FOLLOW_BUSY,
        },
        {
            key         = 'EQUIP_ARMOR',
            name        = 'equip_armor_name',
            description = 'equip_armor_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.EQUIP_ARMOR,
        },
        {
            key         = 'SHOW_PICKUP_MESSAGES',
            name        = 'show_pickup_messages_name',
            description = 'show_pickup_messages_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.SHOW_PICKUP_MESSAGES,
        },
        {
            key         = 'SHOW_HEAVY_MESSAGES',
            name        = 'show_heavy_messages_name',
            description = 'show_heavy_messages_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.SHOW_HEAVY_MESSAGES,
        },
    }
}

I.Settings.registerGroup {
    key              = 'SettingsGreedyNPCsValues',
    page             = 'GreedyNPCs',
    l10n             = 'GreedyNPCs',
    name             = 'settings_groupValues',
    permanentStorage = true,
    order            = 2,
    settings = {
        {
            key         = 'MIN_APPARATUS',
            name        = 'min_apparatus_name',
            description = 'min_apparatus_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_APPARATUS,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_BOOK',
            name        = 'min_book_name',
            description = 'min_book_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_BOOK,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_CLOTHING',
            name        = 'min_clothing_name',
            description = 'min_clothing_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_CLOTHING,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_ARMOR',
            name        = 'min_armor_name',
            description = 'min_armor_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_ARMOR,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_WEAPON',
            name        = 'min_weapon_name',
            description = 'min_weapon_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_WEAPON,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_INGREDIENT',
            name        = 'min_ingredient_name',
            description = 'min_ingredient_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_INGREDIENT,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_POTION',
            name        = 'min_potion_name',
            description = 'min_potion_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_POTION,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_LOCKPICK',
            name        = 'min_lockpick_name',
            description = 'min_lockpick_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_LOCKPICK,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_PROBE',
            name        = 'min_probe_name',
            description = 'min_probe_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_PROBE,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_REPAIR',
            name        = 'min_repair_name',
            description = 'min_repair_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_REPAIR,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_MISC',
            name        = 'min_misc_name',
            description = 'min_misc_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_MISC,
            argument    = { integer = true, min = 0, max = 10000 },
        },
    }
}

I.Settings.registerGroup {
    key              = 'SettingsGreedyNPCsLure',
    page             = 'GreedyNPCs',
    l10n             = 'GreedyNPCs',
    name             = 'settings_groupLure',
    permanentStorage = true,
    order            = 3,
    settings = {
        {
            key         = 'LURE_ENABLED',
            name        = 'lure_enabled_name',
            description = 'lure_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.LURE_ENABLED,
        },
        {
            key         = 'LURE_RADIUS',
            name        = 'lure_radius_name',
            description = 'lure_radius_desc',
            renderer    = 'number',
            default     = DEFAULTS.LURE_RADIUS,
            argument    = { integer = true, min = 100, max = 2000 },
        },
        {
            key         = 'LURE_PICKUP_DELAY',
            name        = 'lure_pickup_delay_name',
            description = 'lure_pickup_delay_desc',
            renderer    = 'number',
            default     = DEFAULTS.LURE_PICKUP_DELAY,
            argument    = { min = 0.0, max = 10.0 },
        },
        {
            key         = 'LURE_RETURN_DELAY',
            name        = 'lure_return_delay_name',
            description = 'lure_return_delay_desc',
            renderer    = 'number',
            default     = DEFAULTS.LURE_RETURN_DELAY,
            argument    = { min = 0.0, max = 10.0 },
        },
        {
            key         = 'LURE_LINGER_DELAY',
            name        = 'lure_linger_delay_name',
            description = 'lure_linger_delay_desc',
            renderer    = 'number',
            default     = DEFAULTS.LURE_LINGER_DELAY,
            argument    = { min = 0.0, max = 10.0 },
        },
    }
}