-- Acknowledgement: Voice lines were generated by vonwolfe using ElevenLabs
-- ChatGPT 2024 was used to fill in this file (4.0 was really helpfull, 3.5 was always confused about this file though)

local types = require("openmw.types")

local vf = "scripts\\MaxYari\\MercyCAO\\voices\\"
local vvf = "Sound\\Vo\\"

-- Note that the format of this records is slightly different from vanilla to keep it shorter.
local records = {
   StandGround = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMStandGround1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMStandGround2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMStandGround3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMStandGround1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMStandGround2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMStandGround3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFStandGround1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFStandGround2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFStandGround3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFStandGround1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFStandGround2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFStandGround3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMStandGround1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMStandGround2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMStandGround3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMStandGround1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMStandGround2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMStandGround3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFStandGround1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFStandGround2.mp3"
            }
         }
      },
   },
   CombatDowntime = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMCombatDowntime1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMCombatDowntime2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMCombatDowntime3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMCombatDowntime1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMCombatDowntime2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMCombatDowntime3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFCombatDowntime1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFCombatDowntime2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFCombatDowntime3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFCombatDowntime1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFCombatDowntime2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFCombatDowntime3.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFCombatDowntime4.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFCombatDowntime5.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMCombatDowntime1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMCombatDowntime2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMCombatDowntime3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMCombatDowntime1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMCombatDowntime2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMCombatDowntime3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFCombatDowntime1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFCombatDowntime2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFCombatDowntime3.mp3"
            }
         }
      },
   },
   Retreat = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMRetreat1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMRetreat2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMRetreat3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMRetreat1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMRetreat2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMRetreat3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFRetreat1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFRetreat2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFRetreat3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFRetreat1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFRetreat2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFRetreat3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMRetreat1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMRetreat2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMRetreat3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMRetreat1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMRetreat2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMRetreat3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFRetreat1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFRetreat2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFRetreat3.mp3"
            }
         }
      },
   },
   GetEm = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "Grab her!",
               sound = vvf .. "i\\m\\OP_IM001.mp3",
               targetGender = "female"
            },
            {
               text = "Grab him!",
               sound = vvf .. "i\\m\\OP_IM002.mp3",
               targetGender = "male"
            },
            {
               text = "She's over here!",
               sound = vvf .. "i\\m\\OP_IM003.mp3",
               targetGender = "female"
            },
            {
               text = "He's over here!",
               sound = vvf .. "i\\m\\OP_IM004.mp3",
               targetGender = "male"
            },
            {
               text = "There he is!",
               sound = vvf .. "i\\m\\OP_IM005.mp3",
               targetGender = "male"
            },
            {
               text = "There she is!",
               sound = vvf .. "i\\m\\OP_IM006.mp3",
               targetGender = "female"
            },
            {
               text = "Seize her!",
               sound = vvf .. "i\\m\\OP_IM007.mp3",
               targetGender = "female"
            },
            {
               text = "Seize him!",
               sound = vvf .. "i\\m\\OP_IM008.mp3",
               targetGender = "male"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "Grab her!",
               sound = vvf .. "o\\f\\OP_OF001.mp3",
               targetGender = "female"
            },
            {
               text = "Grab him!",
               sound = vvf .. "o\\f\\OP_OF002.mp3",
               targetGender = "male"
            },
            {
               text = "She's over here!",
               sound = vvf .. "o\\f\\OP_OF003.mp3",
               targetGender = "female"
            },
            {
               text = "He's over here!",
               sound = vvf .. "o\\f\\OP_OF004.mp3",
               targetGender = "male"
            },
            {
               text = "There he is!",
               sound = vvf .. "o\\f\\OP_OF005.mp3",
               targetGender = "male"
            },
            {
               text = "There she is!",
               sound = vvf .. "o\\f\\OP_OF006.mp3",
               targetGender = "female"
            },
            {
               text = "Seize her!",
               sound = vvf .. "o\\f\\OP_OF007.mp3",
               targetGender = "female"
            },
            {
               text = "Seize him!",
               sound = vvf .. "o\\f\\OP_OF008.mp3",
               targetGender = "male"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "Grab her!",
               sound = vvf .. "o\\m\\OP_OM001.mp3",
               targetGender = "female"
            },
            {
               text = "Grab him!",
               sound = vvf .. "o\\m\\OP_OM002.mp3",
               targetGender = "male"
            },
            {
               text = "She's over here!",
               sound = vvf .. "o\\m\\OP_OM003.mp3",
               targetGender = "female"
            },
            {
               text = "He's over here!",
               sound = vvf .. "o\\m\\OP_OM004.mp3",
               targetGender = "male"
            },
            {
               text = "There he is!",
               sound = vvf .. "o\\m\\OP_OM005.mp3",
               targetGender = "male"
            },
            {
               text = "There she is!",
               sound = vvf .. "o\\m\\OP_OM006.mp3",
               targetGender = "female"
            },
            {
               text = "Seize her!",
               sound = vvf .. "o\\m\\OP_OM007.mp3",
               targetGender = "female"
            },
            {
               text = "Seize him!",
               sound = vvf .. "o\\m\\OP_OM008.mp3",
               targetGender = "male"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "Grab her!",
               sound = vvf .. "n\\m\\int_OP001.mp3",
               targetGender = "female"
            },
            {
               text = "Grab him!",
               sound = vvf .. "n\\m\\int_OP002.mp3",
               targetGender = "male"
            },
            {
               text = "She's over here!",
               sound = vvf .. "n\\m\\int_OP003.mp3",
               targetGender = "female"
            },
            {
               text = "He's over here!",
               sound = vvf .. "n\\m\\int_OP004.mp3",
               targetGender = "male"
            },
            {
               text = "There he is!",
               sound = vvf .. "n\\m\\int_OP005.mp3",
               targetGender = "male"
            },
            {
               text = "There she is!",
               sound = vvf .. "n\\m\\int_OP006.mp3",
               targetGender = "female"
            },
            {
               text = "Seize her!",
               sound = vvf .. "n\\m\\int_OP008.mp3",
               targetGender = "female"
            },
            {
               text = "Seize him!",
               sound = vvf .. "n\\m\\int_OP009.mp3",
               targetGender = "male"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "Grab her!",
               sound = vvf .. "n\\f\\OP_NF001.mp3",
               targetGender = "female"
            },
            {
               text = "Grab him!",
               sound = vvf .. "n\\f\\OP_NF002.mp3",
               targetGender = "male"
            },
            {
               text = "She's over here!",
               sound = vvf .. "n\\f\\OP_NF003.mp3",
               targetGender = "female"
            },
            {
               text = "He's over here!",
               sound = vvf .. "n\\f\\OP_NF004.mp3",
               targetGender = "male"
            },
            {
               text = "There he is!",
               sound = vvf .. "n\\f\\OP_NF005.mp3",
               targetGender = "male"
            },
            {
               text = "There she is!",
               sound = vvf .. "n\\f\\OP_NF006.mp3",
               targetGender = "female"
            },
            {
               text = "Seize her!",
               sound = vvf .. "n\\f\\OP_NF007.mp3",
               targetGender = "female"
            },
            {
               text = "Seize him!",
               sound = vvf .. "n\\f\\OP_NF008.mp3",
               targetGender = "male"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "Grab her!",
               sound = vvf .. "d\\m\\OP_DM001.mp3",
               targetGender = "female"
            },
            {
               text = "Grab him!",
               sound = vvf .. "d\\m\\OP_DM002.mp3",
               targetGender = "male"
            },
            {
               text = "She's over here!",
               sound = vvf .. "d\\m\\OP_DM003.mp3",
               targetGender = "female"
            },
            {
               text = "He's over here!",
               sound = vvf .. "d\\m\\OP_DM004.mp3",
               targetGender = "male"
            },
            {
               text = "There he is!",
               sound = vvf .. "d\\m\\OP_DM005.mp3",
               targetGender = "male"
            },
            {
               text = "There she is!",
               sound = vvf .. "d\\m\\OP_DM006.mp3",
               targetGender = "female"
            },
            {
               text = "Seize her!",
               sound = vvf .. "d\\m\\OP_DM007.mp3",
               targetGender = "female"
            },
            {
               text = "Seize him!",
               sound = vvf .. "d\\m\\OP_DM008.mp3",
               targetGender = "male"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "Grab her!",
               sound = vvf .. "d\\f\\OP_DF001.mp3",
               targetGender = "female"
            },
            {
               text = "Grab him!",
               sound = vvf .. "d\\f\\OP_DF002.mp3",
               targetGender = "male"
            },
            {
               text = "She's over here!",
               sound = vvf .. "d\\f\\OP_DF003.mp3",
               targetGender = "female"
            },
            {
               text = "He's over here!",
               sound = vvf .. "d\\f\\OP_DF004.mp3",
               targetGender = "male"
            },
            {
               text = "There he is!",
               sound = vvf .. "d\\f\\OP_DF005.mp3",
               targetGender = "male"
            },
            {
               text = "There she is!",
               sound = vvf .. "d\\f\\OP_DF006.mp3",
               targetGender = "female"
            },
            {
               text = "Seize her!",
               sound = vvf .. "d\\f\\OP_DF007.mp3",
               targetGender = "female"
            },
            {
               text = "Seize him!",
               sound = vvf .. "d\\f\\OP_DF008.mp3",
               targetGender = "male"
            }
         }
      }
   },
   Mercy = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMMercy1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMMercy2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMMercy3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMMercy1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMMercy2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMMercy3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFMercy1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFMercy2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFMercy3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFMercy1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercy2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercy3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMMercy1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMMercy2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMMercy3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMMercy1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMMercy2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMMercy3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFMercy1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFMercy2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFMercy3.mp3"
            }
         }
      }
   },
   MercyDisarm = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMMercyDisarm1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMMercyDisarm2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMMercyDisarm3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMMercyDisarm1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMMercyDisarm2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMMercyDisarm3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFMercyDisarm1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFMercyDisarm2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFMercyDisarm3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFMercyDisarm1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisarm2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisarm3.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisarm4.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisarm5.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisarm6.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMMercyDisarm1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMMercyDisarm2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMMercyDisarm3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMMercyDisarm1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMMercyDisarm2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMMercyDisarm3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFMercyDisarm1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFMercyDisarm2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFMercyDisarm3.mp3"
            }
         }
      }
   },
   MercyDisengage = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMMercyDisengage1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMMercyDisengage2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMMercyDisengage3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMMercyDisengage1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMMercyDisengage2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMMercyDisengage3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFMercyDisengage1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFMercyDisengage2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFMercyDisengage3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFMercyDisengage1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisengage2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisengage3.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFMercyDisengage4.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMMercyDisengage1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMMercyDisengage2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMMercyDisengage3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMMercyDisengage1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMMercyDisengage2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMMercyDisengage3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFMercyDisengage1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFMercyDisengage2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFMercyDisengage3.mp3"
            }
         }
      }
   },
   FriendDead = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMFriendDead1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMFriendDead2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMFriendDead3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMFriendDead1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMFriendDead2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMFriendDead3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFFriendDead1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFFriendDead2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFFriendDead3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMFriendDead1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMFriendDead2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMFriendDead3.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFFriendDead1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFFriendDead2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFFriendDead3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMFriendDead1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMFriendDead2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMFriendDead3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFFriendDead1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFFriendDead2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFFriendDead3.mp3"
            }
         }
      }
   },
   Warcry = {
      {
         race = "imperial",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "ImpMWarcry1.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMWarcry2.mp3"
            },
            {
               text = "",
               sound = vf .. "ImpMWarcry3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "OrcMWarcry1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMWarcry2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcMWarcry3.mp3"
            }
         }
      },
      {
         race = "orc",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "OrcFWarcry1.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFWarcry2.mp3"
            },
            {
               text = "",
               sound = vf .. "OrcFWarcry3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "DunFWarcry1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFWarcry2.mp3"
            },
            {
               text = "",
               sound = vf .. "DunFWarcry3.mp3"
            }
         }
      },
      {
         race = "dark elf",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "DunMWarcry1.mp3"
            },
            {
               text = "",
               sound = vf .. "DunMWarcry2.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "female",
         infos = {
            {
               text = "",
               sound = vf .. "NordFWarcry1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordFWarcry2.mp3"
            }
         }
      },
      {
         race = "nord",
         gender = "male",
         infos = {
            {
               text = "",
               sound = vf .. "NordMWarcry1.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMWarcry2.mp3"
            },
            {
               text = "",
               sound = vf .. "NordMWarcry3.mp3"
            }
         }
      }
   }
}

local function findRelevantInfos(recordType, race, gender, isBeast)
   local fittingInfos = {}
   local typerecords = records[recordType]
   if not typerecords then return fittingInfos end

   for _, infosGroup in ipairs(typerecords) do
      if infosGroup.race == race and infosGroup.gender == gender then
         fittingInfos = infosGroup.infos
         break
      end
   end

   return fittingInfos
end

return {
   records = records,
   findRelevantInfos = findRelevantInfos
}
