return {
"_we_silver mace",
"_we_silver warhammer",
"_we_silver wakizashi",
"_we_silver tanto",
"_we_silver katana",
"_we_silver dai-katana",
"_we_silver battle axe",
"_we_glass shortsword",
"_we_glass mace",
"_we_glass spear",
"_we_glass broadsword",
"_we_ebony dagger",
"_we_ebony battle axe",
"_we_ebony club",
"_we_glass club",
"_we_ebony warhammer",
"_we_glass warhammer",
"_we_ebony tanto",
"_we_glass tanto",
"_we_ebony wakizashi",
"_we_glass wakizashi",
"_we_ebony katana",
"_we_glass katana",
"_we_ebony dai-katana",
"_we_glass dai-katana",
"_we_glass saber",
"_we_ebony claymore",
"_we_ebony halberd",
"_we_dwemer dagger",
"_we_dreugh shortsword",
"_we_dreugh dagger",
"_we_chitin halberd",
"_we_chitin mace",
"_we_chitin sickle",
"_we_chitin claymore",
"_we_chitin throwing knife",
"_we_iron staff",
"_we_chitin staff",
"_we_bonemold mace",
"_we_bonemold katana",
"_we_bonemold spear",
"_we_bonemold shortsword",
"_we_bonemold dai-katana",
"_we_bonemold dagger",
"_we_bonemold tanto",
"_we_bonemold wakizashi",
"_we_bonemold war axe",
"_we_bonemold longsword",
"_we_orcish saber",
"_we_orcish mace",
"_we_orcish dagger",
"_we_dreugh war axe",
"_we_orcish short bow",
"_we_iron katana",
"_we_iron dai-katana",
"_we_iron throwing star",
"_we_iron throwing star 2",
"_we_chitin longsword",
"_we_chitin battle axe",
"_we_dreugh claymore",
"_we_dreugh halberd",
"_we_dreugh longsword",
"_we_dreugh mace",
"_we_dreugh greatmace",
"_we_dreugh spear",
"_we_dreugh battle axe",
"_we_ebony saber",
"_we_glass longbow",
"_we_imperial dagger",
"_we_imperial war axe",
"_we_nordic dagger",
"_we_nordic club",
"_we_nordic dart",
"_we_nordic halberd",
"_we_nordic longsword",
"_we_nordic mace",
"_we_nordic shortsword",
"_we_nordic spear",
"_we_nordic staff",
"_we_nordic throwing knife",
"_we_nordic war axe",
"_we_nordic arrow",
"_we_nordic bolt",
"_we_orcish war axe",
"_we_orcish shortsword",
"_we_orcish spear",
"_we_orcish longsword",
"_we_orcish halberd",
"_we_orcish dart",
"_we_orcish crossbow",
"_we_orcish club",
"_we_orcish staff",
"_we_orcish throwing knife",
"_we_orcish throwing star",
"_we_silver throwing knife",
"_we_silver club",
"_we_silver broadsword",
"_we_orcish claymore",
"_we_nordic warhammer",
"_we_ebony throwing knife",
"_we_dreugh tanto",
"_we_dreugh dai-katana",
"_we_dreugh katana",
"_we_dreugh wakizashi",
"_we_dwemer longsword",
"_we_dwemer club",
"_we_dwemer staff",
"_we_silver saber",
"_we_imperial battle axe",
"_we_imperial halberd",
"_we_chitin dai-katana",
"_we_chitin katana",
"_we_chitin tanto",
"_we_chitin wakizashi",
"_we_chitin saber",
"_we_chitin bolt",
"_we_chitin broadsword",
"_we_iron dart",
"_we_chitin dart",
"_we_chitin greatmace",
"_we_daedric halberd",
"_we_daedric throwing knife",
"_we_daedric throwing star",
"_we_imperial saber",
"_we_imperial mace",
"_we_imperial arrow",
"_we_imperial bolt",
"_we_imperial claymore",
"_we_imperial club",
"_we_imperial longsword",
"_we_imperial spear",
"_we_imperial tanto",
"_we_imperial throwing knife",
"_we_imperial warhammer",
"_we_imperial wakizashi",
"_we_imperial dai-katana",
"_we_imperial dart",
"_we_imperial katana",
"_we_imperial staff",
"_we_imperial throwing star",
"_we_imperial odachi",
"_we_imperial crossbow",
"_we_orcish broadsword",
"_we_bonemold longspear",
"_we_dreugh longspear",
"_we_glass longspear",
"_we_imperial longspear",
"_we_nordic longspear",
"_we_orcish longspear",
"_we_chitin longspear",
"_we_ebony spear",
"_we_iron longspear",
"_we_silver longspear",
"_we_steel longspear",
"_we_steel broadsword",
"_we_glass battle axe",
"_we_daedric saber",
"_we_dreugh saber",
"_we_silver halberd",
"_we_orcish arrow",
"_we_orcish dai-katana",
"_we_orcish katana",
"_we_orcish wakizashi",
"_we_orcish tanto",
"_we_nordic tanto",
"_we_nordic wakizashi",
"_we_nordic katana",
"_we_nordic dai-katana",
"_we_nordic throwing star",
"_we_nordic saber",
"_we_corkbulb dart",
"_we_corkbulb staff",
"_we_glass bolt",
"_we_glass dart",
"_we_dreugh dart",
"_we_dreugh bolt",
"_we_dreugh arrow",
"_we_dreugh throwing star",
"_we_dreugh throwing knife",
"_we_dreugh short bow",
"_we_dreugh broadsword",
"_we_daedric broadsword",
"_we_ebony bolt",
"_we_daedric bolt",
"_we_ebony crossbow",
"_we_dwemer dai-katana",
"_we_dwemer arrow",
"_we_dwemer bolt",
"_we_dwemer broadsword",
"_we_dwemer katana",
"_we_dwemer saber",
"_we_dwemer tanto",
"_we_dwemer throwing knife",
"_we_dwemer throwing star",
"_we_dwemer wakizashi",
"_we_bonemold halberd",
"_we_bonemold claymore",
"_we_bonemold warhammer",
"_we_bonemold battle axe",
"_we_bonemold broadsword",
"_we_bonemold club",
"_we_bonemold saber",
"_we_bonemold staff",
"_we_bonemold throwing knife",
"_we_bonemold throwing star",
"_we_bonemold dart",
"dreugh war axe",
"dreugh battle axe",
"emerald dagger",
"emerald claymore",
"emerald battle axe",
"emerald spear",
"emerald mace",
"emerald longsword",
"emerald katana",
}