local APPEARANCE_POOLS = {
  ["argonian_female"] = {
    heads = {
      "b_n_argonian_f_head_01",
      "b_n_argonian_f_head_02",
      "b_n_argonian_f_head_03",
      "t_b_arg_headfemtr_01",
      "t_b_arg_headfemtr_02",
      "t_b_arg_headfemtr_03",
      "t_b_arg_headfemtr_04",
      "t_b_arg_headfemtr_05",
      "t_b_arg_headfemtr_06",
    },
    hairs = {
      "b_n_argonian_f_hair01",
      "b_n_argonian_f_hair02",
      "b_n_argonian_f_hair03",
      "b_n_argonian_f_hair04",
      "b_n_argonian_f_hair05",
      "t_b_arg_hairfemtr_01",
      "t_b_arg_hairfemtr_02",
      "t_b_arg_hairfemtr_03",
      "t_b_arg_hairfemtr_04",
      "t_b_arg_hairfemtr_05",
      "t_b_arg_hairfemtr_06",
      "t_b_arg_hairfemtr_07",
      "t_b_arg_hairfemtr_08",
    },
  },
  ["argonian_male"] = {
    heads = {
      "b_n_argonian_m_head_01",
      "b_n_argonian_m_head_02",
      "b_n_argonian_m_head_03",
      "t_b_arg_headmaletr_01",
      "t_b_arg_headmaletr_02",
      "t_b_arg_headmaletr_03",
      "t_b_arg_headmaletr_04",
      "t_b_arg_headmaletr_05",
      "t_b_arg_headmaletr_06",
      "t_b_arg_headmaletr_07",
    },
    hairs = {
      "b_n_argonian_m_hair01",
      "b_n_argonian_m_hair02",
      "b_n_argonian_m_hair03",
      "b_n_argonian_m_hair04",
      "b_n_argonian_m_hair05",
      "b_n_argonian_m_hair06",
      "t_b_arg_hairmaletr_01",
      "t_b_arg_hairmaletr_02",
      "t_b_arg_hairmaletr_03",
      "t_b_arg_hairmaletr_04",
      "t_b_arg_hairmaletr_05",
      "t_b_arg_hairmaletr_06",
      "t_b_arg_hairmaletr_07",
      "t_b_arg_hairmaletr_08",
      "t_b_arg_hairmaletr_09",
      "t_b_arg_hairmaletr_10",
      "t_b_arg_hairmaletr_11",
    },
  },
  ["breton_female"] = {
    heads = {
      "b_n_breton_f_head_01",
      "b_n_breton_f_head_02",
      "b_n_breton_f_head_03",
      "b_n_breton_f_head_04",
      "b_n_breton_f_head_05",
      "b_n_breton_f_head_06",
      "t_b_bre_headfemhr_01",
      "t_b_bre_headfemhr_02",
      "t_b_bre_headfemhr_04",
      "t_b_bre_headfemhr_05",
      "t_b_bre_headfemhr_06",
      "t_b_bre_headfemhr_07",
      "t_b_bre_headfemhr_08",
      "t_b_bre_headfemhr_09",
      "t_b_bre_headfemhr_10",
      "t_b_bre_headfemhr_11",
      "t_b_bre_headfemhr_14",
      "t_b_bre_headfemhr_16",
      "t_b_bre_headfemhr_17", 
      "t_b_bre_headfemtr_01",
      "t_b_bre_headfemtr_04",
      "t_b_bre_headfemtr_05",
      "t_b_bre_headfemtr_06",
    },
    hairs = {
      "b_n_breton_f_hair_01",
      "b_n_breton_f_hair_02",
      "b_n_breton_f_hair_03",
      "b_n_breton_f_hair_04",
      "b_n_breton_f_hair_05",
      "t_b_bre_hairfemhr_01",
      "t_b_bre_hairfemhr_02",
      "t_b_bre_hairfemhr_03",
      "t_b_bre_hairfemhr_04",
      "t_b_bre_hairfemhr_05",
      "t_b_bre_hairfemhr_06",
      "t_b_bre_hairfemhr_07",
      "t_b_bre_hairfemhr_08",
      "t_b_bre_hairfemhr_09",
      "t_b_bre_hairfemhr_10",
      "t_b_bre_hairfemhr_11",
      "t_b_bre_hairfemhr_12",
      "t_b_bre_hairfemhr_13",
      "t_b_bre_hairfemhr_14",
      "t_b_bre_hairfemhr_15",
      "t_b_bre_hairfemhr_16",
      "t_b_bre_hairfemhr_17",
      "t_b_bre_hairfemhr_18",
      "t_b_bre_hairfemhr_19",
    },
  },
  ["breton_male"] = {
    heads = {
      "b_n_breton_m_head_01",
      "b_n_breton_m_head_02",
      "b_n_breton_m_head_03",
      "b_n_breton_m_head_04",
      "b_n_breton_m_head_05",
      "b_n_breton_m_head_06",
      "b_n_breton_m_head_07",
      "b_n_breton_m_head_08",
      "t_b_bre_headmalehr_01",
      "t_b_bre_headmalehr_02",
      "t_b_bre_headmalehr_03",
      "t_b_bre_headmalehr_04",
      "t_b_bre_headmalehr_05",
      "t_b_bre_headmalehr_06",
      "t_b_bre_headmalehr_07",
      "t_b_bre_headmalehr_08",
      "t_b_bre_headmalehr_09",
      "t_b_bre_headmalehr_10",
      "t_b_bre_headmalehr_11",
      "t_b_bre_headmalehr_12",
      "t_b_bre_headmalehr_14",
      "t_b_bre_headmalehr_15",
      "t_b_bre_headmalehr_16",
      "t_b_bre_headmalehr_17",
      "t_b_bre_headmalehr_19",
      "t_b_bre_headmalehr_21",
      "t_b_bre_headmalehr_24",
      "t_b_bre_headmaletr_01",
      "t_b_bre_headmaletr_02",
      "t_b_bre_headmaletr_03",
      "t_b_bre_headmaletr_04",
      "t_b_bre_headmaletr_05",
      "t_b_bre_headmaletr_06",
      "t_b_bre_headmaletr_07",
    },
    hairs = {
      "b_n_breton_m_hair_00",
      "b_n_breton_m_hair_01",
      "b_n_breton_m_hair_02",
      "b_n_breton_m_hair_03",
      "b_n_breton_m_hair_04",
      "b_n_breton_m_hair_05",
      "t_b_bre_hairmalehr_01",
      "t_b_bre_hairmalehr_02",
      "t_b_bre_hairmalehr_03",
      "t_b_bre_hairmalehr_04",
      "t_b_bre_hairmalehr_05",
      "t_b_bre_hairmalehr_06",
      "t_b_bre_hairmalehr_07",
      "t_b_bre_hairmalehr_09",
      "t_b_bre_hairmalehr_10",
      "t_b_bre_hairmalehr_13",
      "t_b_bre_hairmalehr_14",
      "t_b_bre_hairmalehr_16",
      "t_b_bre_hairmalehr_17",
      "t_b_bre_hairmalehr_18",
      "t_b_bre_hairmalehr_19",
      "t_b_bre_hairmalehr_20",
      "t_b_bre_hairmalehr_22",
      "t_b_bre_hairmalehr_23",
      "t_b_bre_hairmalehr_24",
    },
  },
  ["dark_elf_female"] = {
    heads = {
      "b_n_dark elf_f_head_01",
      "b_n_dark elf_f_head_02",
      "b_n_dark elf_f_head_03",
      "b_n_dark elf_f_head_04",
      "b_n_dark elf_f_head_05",
      "b_n_dark elf_f_head_06",
      "b_n_dark elf_f_head_07",
      "b_n_dark elf_f_head_08",
      "b_n_dark elf_f_head_09",
      "b_n_dark elf_f_head_10",
      "t_b_de_headfemtr_01",
      "t_b_de_headfemtr_02",
      "t_b_de_headfemtr_03",
      "t_b_de_headfemtr_04",
      "t_b_de_headfemtr_06",
      "t_b_de_headfemtr_07",
      "t_b_de_headfemtr_08",
      "t_b_de_headfemtr_09",
      "t_b_de_headfemtr_10",
      "t_b_de_headfemtr_12",
      "t_b_de_headfemtr_13",
      "t_b_de_headfemtr_15",
      "t_b_de_headfemtr_16",
      "t_b_de_headfemtr_17",
      "t_b_de_headfemtr_18",
      "t_b_de_headfemtr_20",
      "t_b_de_headfemtr_26",
      "t_b_de_headfemtr_27",
      "t_b_de_headfemtr_28",
      "t_b_de_headfemtr_32",
      "t_b_de_headfemtr_36",
      "t_b_de_headfemtr_37",
      "t_b_de_headfemtr_38",
      "t_b_de_headfemtr_39",
      "t_b_de_headfemtr_47",
    },
    hairs = {
      "b_n_dark elf_f_hair_01",
      "b_n_dark elf_f_hair_02",
      "b_n_dark elf_f_hair_03",
      "b_n_dark elf_f_hair_04",
      "b_n_dark elf_f_hair_05",
      "b_n_dark elf_f_hair_06",
      "b_n_dark elf_f_hair_07",
      "b_n_dark elf_f_hair_08",
      "b_n_dark elf_f_hair_09",
      "b_n_dark elf_f_hair_10",
      "b_n_dark elf_f_hair_11",
      "b_n_dark elf_f_hair_12",
      "b_n_dark elf_f_hair_13",
      "b_n_dark elf_f_hair_14",
      "b_n_dark elf_f_hair_15",
      "b_n_dark elf_f_hair_16",
      "b_n_dark elf_f_hair_17",
      "b_n_dark elf_f_hair_18",
      "b_n_dark elf_f_hair_19",
      "b_n_dark elf_f_hair_20",
      "b_n_dark elf_f_hair_21",
      "b_n_dark elf_f_hair_22",
      "b_n_dark elf_f_hair_23",
      "b_n_dark elf_f_hair_24",
    },
  },
  ["dark_elf_male"] = {
    heads = {
      "b_n_dark elf_m_head_01",
      "b_n_dark elf_m_head_02",
      "b_n_dark elf_m_head_03",
      "b_n_dark elf_m_head_04",
      "b_n_dark elf_m_head_05",
      "b_n_dark elf_m_head_06",
      "b_n_dark elf_m_head_07",
      "b_n_dark elf_m_head_08",
      "b_n_dark elf_m_head_09",
      "b_n_dark elf_m_head_10",
      "b_n_dark elf_m_head_11",
      "b_n_dark elf_m_head_12",
      "b_n_dark elf_m_head_13",
      "b_n_dark elf_m_head_14",
      "b_n_dark elf_m_head_15",
      "b_n_dark elf_m_head_16",
      "b_n_dark elf_m_head_17",
      "t_b_de_headmaletr_01",
      "t_b_de_headmaletr_02",
      "t_b_de_headmaletr_03",
      "t_b_de_headmaletr_04",
      "t_b_de_headmaletr_05",
      "t_b_de_headmaletr_06",
      "t_b_de_headmaletr_07",
      "t_b_de_headmaletr_08",
      "t_b_de_headmaletr_09",
      "t_b_de_headmaletr_10",
      "t_b_de_headmaletr_11",
      "t_b_de_headmaletr_12",
      "t_b_de_headmaletr_13",
      "t_b_de_headmaletr_14",
      "t_b_de_headmaletr_15",
      "t_b_de_headmaletr_16",
      "t_b_de_headmaletr_17",
      "t_b_de_headmaletr_18",
      "t_b_de_headmaletr_19",
      "t_b_de_headmaletr_20",
      "t_b_de_headmaletr_21",
      "t_b_de_headmaletr_22",
      "t_b_de_headmaletr_23",
      "t_b_de_headmaletr_24",
      "t_b_de_headmaletr_25",
      "t_b_de_headmaletr_26",
      "t_b_de_headmaletr_27",
      "t_b_de_headmaletr_31",
      "t_b_de_headmaletr_32",
      "t_b_de_headmaletr_33",
      "t_b_de_headmaletr_34",
      "t_b_de_headmaletr_37",
      "t_b_de_headmaletr_42",
      "t_b_de_headmaletr_44",
      "t_b_de_headmaletr_45",
    },
    hairs = {
      "b_n_dark elf_m_hair_01",
      "b_n_dark elf_m_hair_02",
      "b_n_dark elf_m_hair_03",
      "b_n_dark elf_m_hair_04",
      "b_n_dark elf_m_hair_05",
      "b_n_dark elf_m_hair_06",
      "b_n_dark elf_m_hair_07",
      "b_n_dark elf_m_hair_08",
      "b_n_dark elf_m_hair_09",
      "b_n_dark elf_m_hair_10",
      "b_n_dark elf_m_hair_11",
      "b_n_dark elf_m_hair_12",
      "b_n_dark elf_m_hair_13",
      "b_n_dark elf_m_hair_14",
      "b_n_dark elf_m_hair_15",
      "b_n_dark elf_m_hair_16",
      "b_n_dark elf_m_hair_17",
      "b_n_dark elf_m_hair_18",
      "b_n_dark elf_m_hair_19",
      "b_n_dark elf_m_hair_21",
      "b_n_dark elf_m_hair_22",
      "b_n_dark elf_m_hair_23",
      "b_n_dark elf_m_hair_24",
      "b_n_dark elf_m_hair_25",
      "b_n_dark elf_m_hair_26",
      "t_b_de_hairimpmaletr_01",
      "t_b_de_hairmaletr_04",
      "t_b_de_hairmaletr_05",
      "t_b_de_hairmaletr_06",
      "t_b_de_hairmaletr_09",
      "t_b_de_hairmaletr_10",
      "t_b_de_hairmaletr_11",
      "t_b_de_hairmaletr_12",
      "t_b_de_hairmaletr_13",
      "t_b_de_hairmaletr_14",
      "t_b_de_hairmaletr_15",
      "t_b_de_hairmaletr_16",
      "t_b_de_hairmaletr_17",
      "t_b_de_hairmaletr_18",
      "t_b_de_hairmaletr_19",
      "t_b_de_hairmaletr_20",
      "t_b_de_hairmaletr_21",
      "t_b_de_hairmaletr_22",
      "t_b_de_hairmaletr_23",
      "t_b_de_hairmaletr_24",
      "t_b_de_hairmaletr_25",
      "t_b_de_hairmaletr_26",
      "t_b_de_hairmaletr_27",
      "t_b_de_hairmaletr_28",
      "t_b_de_hairmaletr_29",
      "t_b_de_hairmaletr_30",
      "t_b_de_hairmaletr_31",
      "t_b_de_hairmaletr_32",
      "t_b_de_hairmaletr_33",
      "t_b_de_hairmaletr_34",
      "t_b_de_hairmaletr_35",
      "t_b_de_hairmaletr_36",
      "t_b_de_hairmaletr_37",
      "t_b_de_hairmaletr_38",
      "t_b_de_hairmaletr_39",
      "t_b_de_hairmaletr_42",
      "t_b_de_hairmaletr_43",
      "t_b_de_hairmaletr_44",
      "t_b_de_hairmaletr_45",
    },
  },
  ["high_elf_female"] = {
    heads = {
      "b_n_high elf_f_head_01",
      "b_n_high elf_f_head_02",
      "b_n_high elf_f_head_03",
      "b_n_high elf_f_head_04",
      "b_n_high elf_f_head_05",
      "b_n_high elf_f_head_06",
      "t_b_he_headfemtr_01",
      "t_b_he_headfemtr_02",
      "t_b_he_headfemtr_03",
      "t_b_he_headfemtr_04",
      "t_b_he_headfemtr_07",
      "t_b_he_headfemtr_10",
      "t_b_he_headfemtr_12",
      "t_b_he_headfemtr_13",
      "t_b_he_headfemtr_16",
      "t_b_he_headfemtr_19",
      "t_b_he_headfemtr_20",
    },
    hairs = {
      "b_n_high elf_f_hair_01",
      "b_n_high elf_f_hair_02",
      "b_n_high elf_f_hair_03",
      "b_n_high elf_f_hair_04",
      "t_b_he_hairfemtr_01",
      "t_b_he_hairfemtr_02",
      "t_b_he_hairfemtr_03",
      "t_b_he_hairfemtr_04",
      "t_b_he_hairfemtr_06",
      "t_b_he_hairfemtr_13",
      "t_b_he_hairfemtr_14",
      "t_b_he_hairfemtr_15",
      "t_b_he_hairfemtr_16",
    },
  },
  ["high_elf_male"] = {
    heads = {
      "b_n_high elf_m_head_01",
      "b_n_high elf_m_head_02",
      "b_n_high elf_m_head_03",
      "b_n_high elf_m_head_04",
      "b_n_high elf_m_head_05",
      "b_n_high elf_m_head_06",
      "t_b_he_headmaletr_01",
      "t_b_he_headmaletr_02",
      "t_b_he_headmaletr_03",
      "t_b_he_headmaletr_04",
      "t_b_he_headmaletr_05",
      "t_b_he_headmaletr_06",
      "t_b_he_headmaletr_07",
      "t_b_he_headmaletr_09",
      "t_b_he_headmaletr_10",
      "t_b_he_headmaletr_12",
      "t_b_he_headmaletr_14",
      "t_b_he_headmaletr_18",
    },
    hairs = {
      "b_n_high elf_m_hair_01",
      "b_n_high elf_m_hair_02",
      "b_n_high elf_m_hair_03",
      "b_n_high elf_m_hair_04",
      "b_n_high elf_m_hair_05",
      "t_b_he_hairmaletr_01",
      "t_b_he_hairmaletr_02",
      "t_b_he_hairmaletr_03",
      "t_b_he_hairmaletr_04",
      "t_b_he_hairmaletr_05",
      "t_b_he_hairmaletr_06",
      "t_b_he_hairmaletr_07",
      "t_b_he_hairmaletr_08",
      "t_b_he_hairmaletr_09",
      "t_b_he_hairmaletr_10",
      "t_b_he_hairmaletr_11",
      "t_b_he_hairmaletr_12",
      "t_b_he_hairmaletr_13",
      "t_b_he_hairmaletr_14",
      "t_b_he_hairmaletr_15",
      "t_b_he_hairmaletr_16",
      "t_b_he_hairmaletr_17",
      "t_b_he_hairmaletr_18",
      "t_b_he_hairmaletr_19",
      "t_b_he_hairmaletr_20",
      "t_b_he_hairmaletr_21",
      "t_b_he_hairmaletr_22",
      "t_b_he_hairmaletr_23",
    },
  },
  ["imperial_female"] = {
    heads = {
      "b_n_imperial_f_head_01",
      "b_n_imperial_f_head_02",
      "b_n_imperial_f_head_03",
      "b_n_imperial_f_head_04",
      "b_n_imperial_f_head_05",
      "b_n_imperial_f_head_06",
      "b_n_imperial_f_head_07",
      "t_b_imp_headcolnorthfempc_01",
      "t_b_imp_headcolnorthfempc_02",
      "t_b_imp_headcolrgafempc_01",
      "t_b_imp_headcolrgafempc_02",
      "t_b_imp_headcolwestfempc_01",
      "t_b_imp_headcolwestfempc_02",
      "t_b_imp_headfempc_03",
      "t_b_imp_headfempc_04",
      "t_b_imp_headfempc_05",
      "t_b_imp_headfempc_06",
      "t_b_imp_headfempc_14",
      "t_b_imp_headfempc_18",
      "t_b_imp_headfemtr_01",
      "t_b_imp_headfemtr_02",
      "t_b_imp_headfemtr_03",
      "t_b_imp_headfemtr_05",
      "t_b_imp_headfemtr_06",
      "t_b_imp_headfemtr_07",
      "t_b_imp_headfemtr_10",
      "t_b_imp_headfemtr_11",
      "t_b_imp_headnibfempc_04",
      "t_b_imp_headnibfempc_06",
      "t_b_imp_headnibfempc_08",
    },
    hairs = {
      "b_n_imperial_f_hair_01",
      "b_n_imperial_f_hair_02",
      "b_n_imperial_f_hair_03",
      "b_n_imperial_f_hair_04",
      "b_n_imperial_f_hair_05",
      "b_n_imperial_f_hair_06",
      "b_n_imperial_f_hair_07",
      "t_b_imp_haircolrgafemalepc_01",
      "t_b_imp_hairfempc_01",
      "t_b_imp_hairfempc_02",
      "t_b_imp_hairfempc_03",
      "t_b_imp_hairfempc_05",
      "t_b_imp_hairfempc_06",
      "t_b_imp_hairfempc_08",
      "t_b_imp_hairfempc_09",
      "t_b_imp_hairfempc_11",
      "t_b_imp_hairfempc_14",
      "t_b_imp_hairfempc_15",
      "t_b_imp_hairfempc_16",
      "t_b_imp_hairfempc_17",
      "t_b_imp_hairfempc_18",
      "t_b_imp_hairfempc_19",
      "t_b_imp_hairfemtr_01",
      "t_b_imp_hairfemtr_02",
      "t_b_imp_hairfemtr_03",
      "t_b_imp_hairfemtr_04",
    },
  },
  ["imperial_male"] = {
    heads = {
      "b_n_imperial_m_head_01",
      "b_n_imperial_m_head_02",
      "b_n_imperial_m_head_03",
      "b_n_imperial_m_head_04",
      "b_n_imperial_m_head_05",
      "b_n_imperial_m_head_06",
      "b_n_imperial_m_head_07",
      "t_b_imp_headcolnorthmalepc_01",
      "t_b_imp_headcolnorthmalepc_02",
      "t_b_imp_headcolnorthmalepc_03",
      "t_b_imp_headcolnorthmalepc_04",
      "t_b_imp_headcolrgamalepc_01",
      "t_b_imp_headcolrgamalepc_02",
      "t_b_imp_headcolrgamalepc_03",
      "t_b_imp_headcolwestmalepc_01",
      "t_b_imp_headcolwestmalepc_02",
      "t_b_imp_headcolwestmalepc_03",
      "t_b_imp_headcolwestmalepc_06",
      "t_b_imp_headcolwestmalepc_07",
      "t_b_imp_headmalepc_02",
      "t_b_imp_headmalepc_03",
      "t_b_imp_headmalepc_04",
      "t_b_imp_headmalepc_05",
      "t_b_imp_headmaletr_01",
      "t_b_imp_headmaletr_02",
      "t_b_imp_headmaletr_03",
      "t_b_imp_headmaletr_04",
      "t_b_imp_headmaletr_09",
      "t_b_imp_headmaletr_10",
      "t_b_imp_headmaletr_11",
      "t_b_imp_headmaletr_12",
      "t_b_imp_headmaletr_13",
      "t_b_imp_headmaletr_14",
      "t_b_imp_headmaletr_15",
      "t_b_imp_headnibmalepc_02",
      "t_b_imp_headnibmalepc_04",
      "t_b_imp_headnibmalepc_05",
      "t_b_imp_headnibmalepc_08",
      "t_b_imp_headnibmalepc_10",
      "t_b_imp_headnibmalepc_11",
      "t_b_imp_headnibmalepc_13",
      "t_b_imp_headnibmalepc_14",
    },
    hairs = {
      "b_n_imperial_m_hair_00",
      "b_n_imperial_m_hair_01",
      "b_n_imperial_m_hair_02",
      "b_n_imperial_m_hair_03",
      "b_n_imperial_m_hair_04",
      "b_n_imperial_m_hair_05",
      "b_n_imperial_m_hair_06",
      "b_n_imperial_m_hair_07",
      "b_n_imperial_m_hair_08",
      "b_n_imperial_m_hair_09",
      "t_b_imp_haircolrgamalepc_01",
      "t_b_imp_haircolrgamalepc_02",
      "t_b_imp_hairmalepc_01",
      "t_b_imp_hairmalepc_05",
      "t_b_imp_hairmalepc_06",
      "t_b_imp_hairmalepc_11",
      "t_b_imp_hairmalepc_12",
      "t_b_imp_hairmalepc_13",
      "t_b_imp_hairmalepc_15",
      "t_b_imp_hairmalepc_16",
      "t_b_imp_hairmaletr_01",
      "t_b_imp_hairmaletr_02",
      "t_b_imp_hairmaletr_03",
      "t_b_imp_hairmaletr_04",
      "t_b_imp_hairmaletr_05",
    },
  },
  ["khajiit_female"] = {
    heads = {
      "b_n_khajiit_f_head_01",
      "b_n_khajiit_f_head_02",
      "b_n_khajiit_f_head_03",
      "b_n_khajiit_f_head_04",
      "t_b_kha_headfemtr_01",
      "t_b_kha_headfemtr_02",
      "t_b_kha_headfemtr_03",
      "t_b_kha_headfemtr_04",
      "t_b_kha_headfemtr_05",
      "t_b_kha_headfemtr_06",
      "t_b_kha_headfemtr_07",
      "t_b_kha_headfemtr_08",
      "t_b_kha_headfemtr_09",
    },
    hairs = {
      "b_n_khajiit_f_hair01",
      "b_n_khajiit_f_hair02",
      "b_n_khajiit_f_hair03",
      "b_n_khajiit_f_hair04",
      "b_n_khajiit_f_hair05",
      "t_b_kha_hairfemtr_01",
      "t_b_kha_hairfemtr_02",
    },
  },
  ["khajiit_male"] = {
    heads = {
      "b_n_khajiit_m_head_01",
      "b_n_khajiit_m_head_02",
      "b_n_khajiit_m_head_03",
      "b_n_khajiit_m_head_04",
      "t_b_kha_headmaletr_01",
      "t_b_kha_headmaletr_02",
      "t_b_kha_headmaletr_03",
      "t_b_kha_headmaletr_04",
      "t_b_kha_headmaletr_05",
      "t_b_kha_headmaletr_06",
      "t_b_kha_headmaletr_07",
      "t_b_kha_headmaletr_08",
      "t_b_kha_headmaletr_09",
      "t_b_kha_headmaletr_10",
      "t_b_kha_headmaletr_11",
      "t_b_kha_headmaletr_12",
    },
    hairs = {
      "b_n_khajiit_m_hair01",
      "b_n_khajiit_m_hair02",
      "b_n_khajiit_m_hair03",
      "b_n_khajiit_m_hair04",
      "b_n_khajiit_m_hair05",
      "t_b_kha_hairmaletr_01",
      "t_b_kha_hairmaletr_02",
      "t_b_kha_hairmaletr_03",
      "t_b_kha_hairmaletr_04",
      "t_b_kha_hairmaletr_05",
      "t_b_kha_hairmaletr_06",
    },
  },
  ["redguard_female"] = {
    heads = {
      "b_n_redguard_f_head_01",
      "b_n_redguard_f_head_02",
      "b_n_redguard_f_head_03",
      "b_n_redguard_f_head_04",
      "b_n_redguard_f_head_05",
      "b_n_redguard_f_head_06",
      "t_b_rga_headfemshotn_01",
      "t_b_rga_headfemshotn_02",
      "t_b_rga_headfemshotn_03",
      "t_b_rga_headfemshotn_04",
      "t_b_rga_headfemshotn_06",
      "t_b_rga_headfemshotn_07",
      "t_b_rga_headfemtr_01",
      "t_b_rga_headfemtr_02",
      "t_b_rga_headfemtr_04",
      "t_b_rga_headfemtr_05",
    },
    hairs = {
      "b_n_redguard_f_hair_01",
      "b_n_redguard_f_hair_02",
      "b_n_redguard_f_hair_03",
      "b_n_redguard_f_hair_04",
      "b_n_redguard_f_hair_05",
      "t_b_rga_hairfemtr_05",
      "t_b_rga_hairfemtr_06",
      "t_b_rga_hairfemtr_07",
      "t_b_rga_hairfemtr_08",
      "t_b_rga_hairfemtr_09",
      "t_b_rga_hairfemtr_10",
      "t_b_rga_hairfemtr_11",
      "t_b_rga_hairfemtr_12",
      "t_b_rga_hairfemtr_13",
      "t_b_rga_hairfemtr_14",
      "t_b_rga_hairfemtr_15",
      "t_b_rga_hairfemtr_16",
      "t_b_rga_hairfemtr_17",
    },
  },
  ["redguard_male"] = {
    heads = {
      "b_n_redguard_m_head_01",
      "b_n_redguard_m_head_02",
      "b_n_redguard_m_head_03",
      "b_n_redguard_m_head_04",
      "b_n_redguard_m_head_05",
      "b_n_redguard_m_head_06",
      "t_b_rga_headmaleshotn_01",
      "t_b_rga_headmaleshotn_02",
      "t_b_rga_headmaleshotn_03",
      "t_b_rga_headmaleshotn_04",
      "t_b_rga_headmaleshotn_05",
      "t_b_rga_headmaleshotn_06",
      "t_b_rga_headmaletr_01",
      "t_b_rga_headmaletr_02",
      "t_b_rga_headmaletr_03",
      "t_b_rga_headmaletr_04",
      "t_b_rga_headmaletr_05",
      "t_b_rga_headmaletr_06",
      "t_b_rga_headmaletr_07",
      "t_b_rga_headmaletr_08",
      "t_b_rga_headmaletr_09",
    },
    hairs = {
      "b_n_redguard_m_hair_00",
      "b_n_redguard_m_hair_01",
      "b_n_redguard_m_hair_02",
      "b_n_redguard_m_hair_03",
      "b_n_redguard_m_hair_04",
      "b_n_redguard_m_hair_05",
      "b_n_redguard_m_hair_06",
      "t_b_rga_hairmaletr_01",
      "t_b_rga_hairmaletr_02",
      "t_b_rga_hairmaletr_03",
      "t_b_rga_hairmaletr_04",
      "t_b_rga_hairmaletr_05",
      "t_b_rga_hairmaletr_06",
      "t_b_rga_hairmaletr_07",
      "t_b_rga_hairmaletr_08",
    },
  },
}

return APPEARANCE_POOLS
