--A list of material names to remove from the name of the base object
local materials = {
    "ashlander",
    "hlaalu guard",
    "adamantium",
    "armor",
    "bear",
    "boiled",
    "bonemold",
    "chain",
    "chitin",
    "chuzei",
    "common",
    "daedric",
    "dunmer",
    "dreugh",
    "dragonscale",
    "dwarven",
    "dwemer",
    "ebony",
    "expensive",
    "exquisite",
    "extravagant",
    "fine",
    "gah-julan",
    "glass",
    "goblin",
    "huntsman",
    "house",
    "ice armor",
    "ice",
    "iron",
    "imperial",
    "leather",
    "long",
    "native",
    "netch",
    "armun-an",
    "nordic",
    "orcish",
    "redoran",
    "reikling",
    "ringmail",
    "sixth",
    "short",
    "silver",
    "steel",
    "throwing",
    "war",
    "wolf",
    "wooden",
    "cephalopod",
}
return materials