return {
    "heavy",
    "redguard ",
    "mercenary ",
    "rangard's",
    "khajiit",
    "monk's",
    "iszara's",
    "cyrodiilic",
    "improvised",
    "chipped",
    "fishing",
    "ceremonial",
    "bone",
    "akaviri",
    "heavy",
    "ashlander",
    "bug ",
}