return {
    ["amphora"] = {
        open = "tew\\A\\N\\drstn_o.wav",
        close = "tew\\A\\N\\drstn_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.6,
        idPatterns = {
            "_furn_cola",
        },
    },
    ["bale"] = {
        open = "tew\\A\\N\\hay_o.wav",
        close = "tew\\A\\N\\hay_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "_furn_bl",
        },
    },
    ["barrel"] = {
        open = "tew\\A\\N\\barrel_o.wav",
        close = "tew\\A\\N\\barrel_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "_var_bl",
            "barrel",
        },
    },
    ["basket"] = {
        open = "tew\\A\\N\\basket_o.wav",
        close = "tew\\A\\N\\basket_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "_furn_ba",
            "_setnmd_bs",
            "_var_bs",
            "basket",
        },
    },
    ["bookcase"] = {
        open = "Fx\\BOOKOPN1.wav",
        close = "Fx\\BOOKCLS1.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "_dngruin_bc",
            "bookcase",
        },
    },
    ["box"] = {
        open = "tew\\A\\N\\smallchest_o.wav",
        close = "tew\\A\\N\\smallchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "_furn_box",
            "_furn_cardhort",
            "ab_o_ashltrinketbox",
            "ab_o_boxflour",
        },
    },
    ["chest"] = {
        open = "tew\\A\\N\\chest_o.wav",
        close = "tew\\A\\N\\chest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "chest",
            "de_m_01_v_potion_", -- wooden chest
            "dem_01_v_potion_", -- wooden chest
            "stolen_goods",
            "_cyrimp_dngruin_ch",
            "_dngdir_ch",
            "_dngruin_ch4", -- ayleid chest
            "_furn_ch1",
            "_furn_ch2",
            "_furn_ch3",
            "_furn_ch4",
            "_furn_cho1", -- worn chest
            "_furnr_ch1",
            "_setnmd_ch",
            "_setvel_ches",
        },
    },
    ["chest of drawers"] = {
        open = "tew\\A\\N\\drawers_o.wav",
        close = "tew\\A\\N\\drawers_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.8,
        idPatterns = {
            "ab_o_comrchdrawr0",
            "ab_o_deplndrawers",
            "ab_o_derchdrawers",
            "bm_drawers_clothing",
            "com_drawers_",
            "de_drawers_",
            "de_r_drawers_",
            "rufinus_alleius_chest",
            "t_skynor_furnr_dw",
        },
    },
    ["clay jar"] = {
        open = "tew\\A\\N\\drstn_o.wav",
        close = "tew\\A\\N\\drstn_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.5,
        idPatterns = {
            "_dngcolb_j",
        },
    },
    ["closet"] = {
        open = "tew\\A\\N\\closet_o.wav",
        close = "tew\\A\\N\\closet_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "closet",
            "_furnm_cl",
            "_furnp_cl",
            "_furnr_cl",
        },
    },
    ["coffer"] = {
        open = "tew\\A\\N\\chest_o.wav",
        close = "tew\\A\\N\\chest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "_coff",
            "_dngcolb_ch2", -- wooden coffer
            "coffer",
        },
    },
    ["crate"] = {
        open = "tew\\A\\N\\crate_o.wav",
        close = "tew\\A\\N\\crate_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "crate",
            "general_t_cra",
            "_var_cr",
        },
    },
    ["culdem"] = {
        open = "tew\\A\\N\\drstn_o.wav",
        close = "tew\\A\\N\\drstn_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 2.0,
        idPatterns = {
            "_setind_cul",
        },
    },
    ["cupboard"] = {
        open = "tew\\A\\N\\cupboard_o.wav",
        close = "tew\\A\\N\\cupboard_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.8,
        idPatterns = {
            "cupboard",
            "_furn_cb",
            "_furnm_cb",
            "_furnp_cb",
            "_md_mg_ingclos",
        },
    },
    ["daedric chest"] = {
        open = "tew\\A\\N\\daedricchest_o.wav",
        close = "tew\\A\\N\\daedricchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "ab_o_daedricchest",
            "daed_chest",
        },
    },
    ["desk"] = {
        open = "tew\\A\\N\\cupboard_o.wav",
        close = "tew\\A\\N\\cupboard_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.8,
        idPatterns = {
            "desk",
            "_dngdir_ds",
            "_furnm_ds",
            "_furnp_ds",
            "_furnr_ds",
        },
    },
    ["drawers"] = {
        open = "tew\\A\\N\\drawers_o.wav",
        close = "tew\\A\\N\\drawers_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.8,
        idPatterns = {
            "drawers",
            "_dngdir_dw",
            "_furnm_dw",
            "_furnp_dw",
            "_furnr_dw",
        },
    },
    ["heavy dwemer chest"] = {
        open = "tew\\A\\N\\dwemerchest_o.wav",
        close = "tew\\A\\N\\dwemerchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "ab_o_dwchestlarge",
            "dwrv_chest_divayth00",
            "dwrv_chest_divayth02",
            "dwrv_chest_divayth03",
            "dwrv_chest_divayth05",
            "dwrv_chest00",
            "dwrv_chest_fals",
        },
    },
    ["heavy dwemer desk"] = {
        open = "tew\\A\\N\\dwemercloset_o.wav",
        close = "tew\\A\\N\\dwemercloset_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "ab_o_dwdeskpos",
            "dwrv_desk",
            "dwrv_endusal_desk",
        },
    },
    ["hutch"] = {
        open = "tew\\A\\N\\cupboard_o.wav",
        close = "tew\\A\\N\\cupboard_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.8,
        idPatterns = {
            "_furnm_ht",
            "_furnr_ht",
            "hutch",
        },
    },
    ["lectern"] = {
        open = "tew\\A\\N\\smallchest_o.wav",
        close = "tew\\A\\N\\smallchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "_furnr_lc",
        },
    },
    ["ornate dwemer chest"] = {
        open = "tew\\A\\N\\dwemerchest_o.wav",
        close = "tew\\A\\N\\dwemerchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "ab_o_dwchestrare",
            "ab_o_dwchestweap",
            "dwrv_chest10",
            "dwrv_chest_arrows_bolts",
            "dwrv_chest_bam",
            "dwrv_chest_divayth01",
            "dwrv_chest_divayth04",
            "dwrv_chest_divayth07",
            "dwrv_chest_missile",
            "dwrv_chest_satchel",
        },
    },
    ["pot"] = {
        open = "tew\\A\\N\\pot_o.wav",
        close = "tew\\A\\N\\pot_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.7,
        idPatterns = {
            "_furn_pot",
            "crabpot",
            "pot_01",
        },
    },
    ["reliquary"] = {
        open = "tew\\A\\N\\drstn_o.wav",
        close = "tew\\A\\N\\drstn_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 2.0,
        idPatterns = {
            "t_cyrayl_dngruin_ch1",
            "t_cyrayl_dngruin_ch2",
            "t_cyrayl_dngruin_ch3",
        },
    },
    ["rusted dwemer cabinet"] = {
        open = "tew\\A\\N\\dwemercloset_o.wav",
        close = "tew\\A\\N\\dwemercloset_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "ab_o_dwcab",
            "dwrv_cabinet",
        },
    },
    ["sack"] = {
        open = "tew\\A\\N\\sack_o.wav",
        close = "tew\\A\\N\\sack_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "sack",
            "_setnmd_sk",
            "_var_csk",
            -- numbers here because _var_skeleton
            "_var_sk1",
            "_var_sk2",
            "_var_sk3",
            "_var_sk4",
            "_var_sk5",
        },
    },
    ["small chest"] = {
        open = "tew\\A\\N\\smallchest_o.wav",
        close = "tew\\A\\N\\smallchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.7,
        idPatterns = {
            "_chest_sgem",
            "_furn_chs",
            "chest_andrano",
            "chest_small",
            "chest_tomb_small",
            "moneybox",
            "redoran_treas_chest",
            "smallchest",
        },
    },
    ["small ornate dwemer chest"] = {
        open = "tew\\A\\N\\dwemerchest_o.wav",
        close = "tew\\A\\N\\dwemerchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "dwrv_chest_small",
        },
    },
    ["steel dwemer closet"] = {
        open = "tew\\A\\N\\dwemercloset_o.wav",
        close = "tew\\A\\N\\dwemercloset_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "ab_o_dwclosetall",
            "dwrv_closet",
        },
    },
    ["steel dwemer dresser"] = {
        open = "tew\\A\\N\\dwemercloset_o.wav",
        close = "tew\\A\\N\\dwemercloset_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "ab_o_dwdrawerspos",
            "dwrv_drawers",
        },
    },
    ["steel dwemer table"] = {
        open = "tew\\A\\N\\dwemerchest_o.wav",
        close = "tew\\A\\N\\dwemerchest_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "ab_o_dwtablepos",
            "dwrv_table",
        },
    },
    ["steel keg"] = {
        open = "tew\\A\\N\\dwemerkeg_o.wav",
        close = "tew\\A\\N\\dwemerkeg_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.0,
        idPatterns = {
            "ab_o_dwbarreling",
            "dwrv_barrel00",
        },
    },
    ["steel quarter keg"] = {
        open = "tew\\A\\N\\dwemerkeg_o.wav",
        close = "tew\\A\\N\\dwemerkeg_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "ab_o_dwbarrelshorting",
            "dwrv_barrel10",
        },
    },
    ["table"] = {
        open = "tew\\A\\N\\drawers_o.wav",
        close = "tew\\A\\N\\drawers_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.8,
        idPatterns = {
            "_furnr_cls1", -- nighttable
            "_furnp_dw2", -- endtable
            "_furnp_st1", -- sidetable
            "table",
        },
    },
    ["urn"] = {
        open = "tew\\A\\N\\drstn_o.wav",
        close = "tew\\A\\N\\drstn_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.8,
        idPatterns = {
            -- need to dodge *furn* ids that aren't urns
            "_dngcryp_u1",
            "_dngbarr_u",
            "_furn_u1",
            "_furn_u2",
            "_furn_u3",
            "_furn_u4",
            "_furn_u5",
            "_setdre_u",
            "_urn",
            "6thurn",
            "demnevannijar1",
            "demnevannijar3",
            "urn_01",
            "urn_02",
            "urn_03",
            "urn_04",
            "urn_05",
            "urn_ash",
        },
    },
    ["vase"] = {
        open = "tew\\A\\N\\pot_o.wav",
        close = "tew\\A\\N\\pot_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 1.5,
        idPatterns = {
            "_furn_vs",
        },
    },
    ["wicker chest"] = {
        open = "tew\\A\\N\\basket_o.wav",
        close = "tew\\A\\N\\basket_c.wav",
        openSoundObj = nil,
        closeSoundObj = nil,
        volume = 0.9,
        idPatterns = {
            "_skyrea_furn_ch",
        },
    },
}