local this = {}

this.talkativeness = {
    ["agent"] = 2,
    ["bard"] = 2,
    ["healer"] = 2,
    ["knight"] = 2,
    ["pilgrim"] = 2,
    ["rogue"] = 2,
    ["alchemist"] = 2,
    ["apothecary"] = 2,
    ["bookseller"] = 2,
    ["buoyant armiger"] = 2,
    ["caravaner"] = 2,
    ["clothier"] = 2,
    ["drillmaster"] = 2,
    ["enchanter"] = 2,
    ["gondolier"] = 2,
    ["guard"] = 2,
    ["merchant"] = 2,
    ["noble"] = 2,
    ["pauper"] = 2,
    ["pawnbroker"] = 2,
    ["priest"] = 2,
    ["publican"] = 2,
    ["savant"] = 2,
    ["shipmaster"] = 2,
    ["trader"] = 2,
    ["wise woman"] = 2,
    ["acrobat"] = 1,
    ["archer"] = 1,
    ["battlemage"] = 1,
    ["crusader"] = 1,
    ["mage"] = 1,
    ["scout"] = 1,
    ["sorcerer"] = 1,
    ["spellsword"] = 1,
    ["warrior"] = 1,
    ["witchhunter"] = 1,
    ["commoner"] = 1,
    ["farmer"] = 1,
    ["guild guide"] = 1,
    ["herder"] = 1,
    ["hunter"] = 1,
    ["mabrigash"] = 1,
    ["master-at-arms"] = 1,
    ["miner"] = 1,
    ["ordinator"] = 1,
    ["ordinator guard"] = 1,
    ["smith"] = 1,
    ["warlock"] = 1,
    ["witch"] = 1,
    ["assassin"] = 0.5,
    ["barbarian"] = 0.5,
    ["monk"] = 0.5,
    ["nightblade"] = 0.5,
    ["champion"] = 0.5,
    ["dreamer"] = 0.5,
    ["enforcer"] = 0.5,
    ["necromancer"] = 0.5,
    ["sharpshooter"] = 0.5,
    ["slave"] = 0.5,
    ["smuggler"] = 0.5,
    ["thief"] = 0.5
}

this.proTopics = {
    "orders",
    "chores",
    "jobs",
    "duties",
    "advancement",
    "requirements",
    "work",
    "business",
    "rules",
    "writ",
}

return this