-- npc classes who can have tomes added to their inventory
spellTomeClasses = {
	["alchemist"]				= true,
	["alchemist service"]		= true,
	["enchanter"]				= true,
	["enchanter service"]		= true,
	["healer"]					= true,
	["healer service"]			= true,
	["mage"]					= true,
	["mage service"]			= true,
	["necromancer"]				= true,
	["nightblade"]				= true,
	["pilgrim"]					= true,
	["scribe"]					= true,
	["sorcerer"]				= true,
	["spellsword"]				= true,
	["warlock"]					= true,
	["witch"]					= true,
	["witchhunter"]				= true,
	['apothecary']				= true,
	['apothecary service']		= true,
	['bard']					= true,
	['battlemage']				= true,
	['battlemage service']		= true,
	['bookseller']				= true,
	['buoyant armiger']			= true,
	['crusader']				= true,
	['dreamers']				= true,
	['enchanter']				= true,
	['enchanter service']		= true,
	['guild guide']				= true,
	['healer']					= true,
	['mabrigash']				= true,
	['mage']					= true,
	['mage service']			= true,
	['monk']					= true,
	['monk service']			= true,
	['necromancer']				= true,
	['nightblade']				= true,
	['nightblade service']		= true,
	['noble']					= true,
	['ordinator']				= true,
	['ordinator guard']			= true,
	['pilgrim']					= true,
	['priest']					= true,
	['priest service']			= true,
	['savant']					= true,
	['savant service']			= true,
	['sorcerer']				= true,
	['sorcerer service']		= true,
	['spellsword']				= true,
	['warlock']					= true,
	['wise woman']				= true,
	['wise woman service']		= true,
	['witch']					= true,
	['witchhunter']				= true,
	['gardener']				= true,
	['journalist']				= true,
	['shaman']					= true,
	
	-- TR
	['t_glb_apothecaryservice'] = true,
	['t_glb_artist']			= true,
	['t_glb_astrologer']		= true,
	['t_glb_barrister']			= true,
	['t_glb_bookseller']		= true,
	['t_glb_healer']			= true,
	['t_glb_jeweler']			= true,
	['t_glb_naturalist']		= true,
	['t_glb_priest']			= true,
	['t_glb_savant']			= true,
	['t_glb_scribe']			= true,
	
	-- SHOTN
	['t_sky_clever-man']		= true,
	
	-- OAAB
	['ab_author']				= true,
	['ab_clerk']				= true,
	['ab_painter']				= true,
	['ab_sculptor']				= true,
}