local ashfall = include("mer.ashfall.interop")
if ashfall then

    --Object Registration

    ashfall.registerFoods{
		mc_chefsalad = "food",
		mc_mixedgreens = "food",
		mc_potatosalad = "food",
		mc_ricetreat = "food",
		mc_wheatroll = "food",
		mc_pemmican = "food",	
		mc_kanet_butter = "herb",
		mc_riceflour = "herb",
		mc_ryeflour = "herb",
		mc_wheatflour = "herb",
		mc_sausagepod = "meat",
		mc_crabmeat_cooked = "food",
		mc_fried_mushroom = "food",
		mc_kwamalarge = "egg",
		mc_kwamasmall = "egg",
		mc_potato_baked = "food",
		mc_ashyam_baked = "food",
		mc_bubble_squeak = "food",
		mc_guar_cooked = "cookedMeat",
		mc_hound_cooked = "cookedMeat",
		mc_kagouti_cooked = "cookedMeat",
		mc_rat_cooked = "cookedMeat",
		mc_racer_cooked = "cookedMeat",
		mc_durzog_cooked = "cookedMeat",
		mc_fish_cooked = "cookedMeat",
		mc_guarstew = "food",
		mc_kagarine = "food",
		mc_potluckstew = "food",
		mc_racerrevenge = "food",
		mc_seafood_medley = "food",
		mc_seafood_stew = "food",
		mc_felaril = "food",
		mc_glowpotsoup = "food",
		mc_mushroomsoup = "food",
		mc_root_soup = "food",
		mc_scuttle_soup = "food",
		mc_spice_soup = "food",
		mc_trailbroth = "food",
		mc_wheatbread = "food",
		mc_ryebread = "food",
		mc_ricebread = "food",
		mc_suncake = "food",
		mc_swamproll = "food",
		mc_sweetbread = "food",
		mc_sweetcake = "food",
		mc_trailcake = "food",
		mc_plains_pie = "food",
		mc_pot_pie = "food",
		mc_quiche = "food",
		mc_sweetyam_pie = "food",
		mc_berry_pie = "food",
		mc_guarherdpie = "food",
		["mc_hackle-lo_powder"] = "seasoning",
		mc_starch = "seasoning",
		mc_sugar = "herb",
		mc_fish_raw = "meat",
		mc_potato_raw = "vegetable",
		mc_onion = "vegetable",
		mc_garlic = "vegetable",
		mc_horker_blubber = "meat",
		mc_sandwich_crab = "food",
		mc_sandwich_fish = "food",
		mc_sandwich_guar = "food",
		mc_sandwich_hound = "food",
		mc_sandwich_kagouti = "food",
		mc_sandwich_racer = "food",
		mc_sandwich_rat = "food"
    }

    ashfall.registerHeatSources{
        mc_logfire = 100,
        mc_campfire = 100,
    }


end