local goalsList = {
    { name = "Become a millionaire", description = "Sit on a dragon's horde of 1 million septims." },
    { name = "Hunter: REPLACE", description = "Kill 100 REPLACE.", replacerOptions = { "Cliff Racers", "Alit", "Golden Saints", "Durzogs", "Clannfear"} },
    { name = "Kill REPLACE", description = "REPLACE needs to die.", replacerOptions = { "Fargoth", "Caius Cosades", "Gothren", "Bolvyn Venim", "Orvas Dren", "Duke Vedam Dren", "Tholer Saryoni", "Berel Sala", "Crassius Curio", "Therana", "Neloth", "Divayth Fyr"} },
    { name = "The Tribunal Must Die", description = "Their time is over. Kill Almalexia, Sotha Sil, and Vivec." },
    { name = "Become REPLACE leader", description = "Become the leader of the REPLACE.", replacerOptions = { "Mages Guild", "Fighters Guild", "Thieves Guild", "Imperial Legion", "Imperial Cult", "Tribunal Temple", "Morag Tong", "House Hlaalu", "House Telvanni", "House Redoran" }},
    { name = "Bloodbath", description = "Exterminate 30 members of the Camonna Tong." },
    { name = "Pious Pilgrim", description = "Complete all the Tribunal Temple pilgrimages." },
    { name = "Guar Herder", description = "Gather a herd of guar. Bonus points if you can gather together friends such as Corky and Rollie." },
    { name = "Acquire REPLACE", description = "It must be yours.", replacerOptions = { "Moon-and-Star", "The Fork of Horripilation", "Azura's Star", "Mehrunes Razor", "The Comfy Pillow" } },
    { name = "Steal 5 artifacts from museum", description = "They must ALL be yours." },
    { name = "Dwemer collector", description = "Collect 10 of each type of Dwemer item." },
    { name = "Become a vampire", description = "Become a feared creature of the night." },
    { name = "Become a werewolf", description = "Become a feared creature of the night." },
    { name = "Abolitionist", description = "Free 30 slaves." },
    { name = "Soul dealer", description = "Soultrap 30 different creatures." },
    { name = "Polite Tomb Visitor", description = "Make an offering in 100 tombs." },
    { name = "Entertainer", description = "Tell a joke in every inn." },
    { name = "Tribute giver", description = "Pay tribute to Pop Je, Scourge, G.Lyngas, Lord Brinne and D. Bryant." },
    { name = "Vivec's Wisdom", description = "Collect 36 sermons." },
    { name = "M'aiq's Wisdom", description = "Find M'aiq and ask for his wisdom on various topics." },
    { name = "Sanguine Collector", description = "Collect all 27 Sanguine Items." },
    { name = "Curse seeker", description = "Collect 20 cursed diamonds, daedra hearts, emeralds, pearls, ebony chunks, and rubies." },
    { name = "Hide collector", description = "Collect a set of hides: Girith, Marsus, alit, kagouti, guar, netch, bear, wolf, and bristleback." },
    { name = "Miner", description = "Collect 20 pieces of glass, ebony, adamantium, and Stalhrim." },
    { name = "Necromancer", description = "Collect 20 skulls, 20 servant skulls and the dwarven bone." },
    { name = "Flavour seeker", description = "Collect 15 ash, salt, frost and void salts." },
    { name = "Dagoth slayer", description = "Kill 36 Dagoths." },
    { name = "Exorcist", description = "Collect 100 ectoplasm, including the Gateway Ghost, Galos, Kanit, Senipul and Mezalf." },
    { name = "Magpie", description = "Collect 50 of each precious gem, eg: pearls, diamond, emeralds, rubies." },
    { name = "Addict", description = "Collect the following: a skooma pipe, silver spoon, 50 pieces of moon sugar, and 50 bottles of skooma." },
    { name = "Jiub's rival", description = "Collect 200 racer plumes from racers you slew yourself." },
    { name = "Oblivion bane", description = "Collect 50 pieces each of daedra skin, daedra heart, and scamp skin." },
    { name = "Poisoner", description = "Collect poison goop, 10 corprus weepings, and 10 spoiled potions." },
    { name = "Heavy drinker", description = "Collect 5 of each beverage. Then let the party begin!" },
    { name = "Numismatist", description = "Collect coins: 50 dwemer 10 magic, 10 of any others." },
    { name = "Ash Statue expert", description = "Collect 150 ash statues." },
    { name = "Sea lover", description = "Collect 200 shells, stars, pearls etc." },
    { name = "Become a Dagoth", description = "Go through with the transformation into a Dagoth." },
    { name = "Long live the King", description = "Kill Helseth." },
    { name = "Bow to the Duke", description = "Pay all the dukes and duchesses a visit." },
    { name = "Undead army", description = "Summon an army of 20 undead minions." },
    { name = "Daedra worshipper", description = "Complete quests for 5 of the Daedric Princes." },
    { name = "Mudcrab's Mate", description = "Bring the Drunken Mudcrab to a tavern." },
    { name = "Plunder the Dungeon", description = "Plunder Divayth Fyr's tower for treasures." },
    { name = "Give Ur victory", description = "This time, make sure Dagoth Ur wins." },
    { name = "Oblivion Explorer", description = "Visit 5 different realms of Oblivion."},
    { name = "Lich Aspirant", description = "Become a lich."},
    { name = "Plaguebearer", description = "Infect 100 different NPCs with diseases."},
    { name = "Bounty Hunter", description = "Bring death to 20 notorious outlaws."},
    { name = "Master of Mushrooms", description = "Build a new Telvanni city."},
    { name = "Dwemer Scholar", description = "Discover what happened to the Dwemer."},
    { name = "Interprovincial Traveler", description = "Visit at least three different provinces of Tamriel."},
    { name = "Fashionista", description = "Swap outfits every day; collect one of each robe."},
    { name = "Architect", description = "Build a pillow fort."},
    { name = "Explorer", description = "Visit somewhere you've never been."},
    { name = "Librarian", description = "Collect 500 books." },
    { name = "Vampire Hunter", description = "Kill all vampires." },
    { name = "Tourist", description = "Visit REPLACE.", replacerOptions = { "Seyda Neen", "Pelagiad", "Vivec", "Ebonheart", "Sadrith Mora", "Tel Aruhn", "Tel Mora", "Tel Fyr", "Tel Branora", "Balmora", "Hla Oad", "Gnaar Mok", "Suran", "Ald-ruhn", "Maar Gan", "Molag Mar", "Gnisis", "Khuul", "Ald Velothi", "Solstheim", "Ghostgate", "Mournhold" } }
}

return goalsList