local core = require("openmw.core")
local T = require("openmw.types")

local attributes = core.stats.Attribute.records
local skills = core.stats.Skill.records
local effectTypes = core.magic.EFFECT_TYPE
local enchantTypes = core.magic.ENCHANTMENT_TYPE
local rangeTypes = core.magic.RANGE

return {
    {
        id = "burden-self-touch-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.Burden,
                range = rangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 300, 400, 500, 600 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Burden,
                range = rangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 100, 200, 300, 400 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "drainSpeed-self-touch-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 10, 20, 30, 40 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "blind-self-touch-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.Blind,
                range = rangeTypes.Self,
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Blind,
                range = rangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "fortifySpeed-sanctuary-blind-sound-self-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Sanctuary,
                range = rangeTypes.Self,
                min = { false, 10, 15, 20, 25 },
                max = { false, 15, 20, 25, 30 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Blind,
                range = rangeTypes.Self,
                min = { false, 40, 50, 60, 70 },
                max = { false, 50, 60, 70, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Sound,
                range = rangeTypes.Self,
                min = { false, 25, 30, 35, 40 },
                max = { false, 35, 40, 45, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFire,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFrost,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToShock,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToMagicka,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "levitate-light-fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = "prefix",
        value = 100,
        castType = enchantTypes.CastOnUse,
        cost = 20,
        charge = 100,
        effects = {
            {
                id = effectTypes.Levitate,
                range = rangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.Light,
                range = rangeTypes.Self,
                min = { false, 5, 10, 15, 20 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Self,
                min = { 200, 200, 200, 200, 200 },
                max = { 200, 200, 200, 200, 200 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToFire,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToFrost,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToShock,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.WeaknessToMagicka,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "reflect-weaknesses-onUse",
        affixType = "prefix",
        value = 100,
        castType = enchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = effectTypes.Reflect,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = effectTypes.WeaknessToFire,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = effectTypes.WeaknessToFrost,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = effectTypes.WeaknessToShock,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = effectTypes.WeaknessToMagicka,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = effectTypes.WeaknessToNormalWeapons,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
        },
        itemTypes = {
            [T.Armor] = { types = {
                [T.Armor.TYPE.Cuirass] = true,
            } },
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Robe] = true,
            } },
        },
    },
    {
        id = "fortifyStrengthMarksman-drainAgility-burden-onUse",
        affixType = "prefix",
        value = 100,
        castType = enchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.strength.id,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = effectTypes.FortifySkill,
                skill = skills.marksman.id,
                range = rangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Self,
                min = { false, false, 30, 40, 50 },
                max = { false, false, 40, 50, 60 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = effectTypes.Burden,
                range = rangeTypes.Self,
                min = { false, false, 200, 300, 400 },
                max = { false, false, 300, 400, 500 },
                duration = { false, false, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "fortifyStrength-drainAgility-weaknesses-self-onUse",
        affixType = "prefix",
        value = 50,
        castType = enchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.strength.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFire,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToFrost,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToShock,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.WeaknessToMagicka,
                range = rangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "sunDamage-touch-blind-self-onUse",
        affixType = "prefix",
        value = 100,
        castType = enchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = effectTypes.SunDamage,
                range = rangeTypes.Touch,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 3, 4, 5, 6 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.Blind,
                range = rangeTypes.Self,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 10, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
        },
    },
    {
        id = "damageHealth-self-touch-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.DamageHealth,
                range = rangeTypes.Touch,
                min = { false, 8, 16, 24, 32 },
                max = { false, 20, 40, 60, 80 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DamageHealth,
                range = rangeTypes.Self,
                min = { false, 2, 4, 6, 8 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "dispel-self-touch-onUse",
        affixType = "suffix",
        value = 200,
        castType = enchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = effectTypes.Dispel,
                range = rangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.Dispel,
                range = rangeTypes.Touch,
                area = { false, 5, 10, 15, 20 },
                min = { false, 20, 30, 40, 50 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "dispel-self-touch-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.Dispel,
                range = rangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 20, 30, 40, 50 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.Dispel,
                range = rangeTypes.Touch,
                area = { 0, 5, 10, 15, 20 },
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 20, 30, 40, 50 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "poison-weaknessToPoison-self-touch-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Self,
                min = { false, 30, 40, 50, 60 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = effectTypes.WeaknessToPoison,
                range = rangeTypes.Touch,
                min = { false, 30, 40, 50, 60 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = effectTypes.Poison,
                range = rangeTypes.Self,
                min = { false, 1, 1, 1, 1 },
                max = { false, 1, 1, 2, 3 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = effectTypes.Poison,
                range = rangeTypes.Touch,
                min = { false, 2, 2, 2, 2 },
                max = { false, 3, 4, 5, 6 },
                duration = { false, 8, 12, 16, 20 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
            } },
        },
    },
    {
        id = "absorbMagicka-target-damageFatigue-self-onUse",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = effectTypes.AbsorbMagicka,
                range = rangeTypes.Target,
                min = { 1, 1, 1, 1, 1 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = effectTypes.DamageFatigue,
                range = rangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 3, 6, 9, 12, 15 },
                duration = { 10, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "damageFatigue-touch-damageLuck-touch-self-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.DamageFatigue,
                range = rangeTypes.Touch,
                min = { 5, 15, 25, 35, 50 },
                max = { 25, 35, 45, 60, 75 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DamageAttribute,
                attribute = attributes.luck.id,
                range = rangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DamageAttribute,
                attribute = attributes.luck.id,
                range = rangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "drainHealth-touch-damageFatigue-self-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.DrainHealth,
                range = rangeTypes.Touch,
                min = { 20, 30, 40, 60, 80 },
                max = { 30, 40, 50, 75, 100 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DamageFatigue,
                range = rangeTypes.Self,
                min = { 40, 50, 60, 80, 120 },
                max = { 50, 60, 70, 100, 150 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "sanctuary-fortifyShortBlade-drainBlock-damageFatigue-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.Sanctuary,
                range = rangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.FortifySkill,
                skill = skills.shortblade.id,
                range = rangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.DrainSkill,
                skill = skills.block.id,
                range = rangeTypes.Self,
                min = { 50, 60, 70, 80, 90 },
                max = { 60, 70, 80, 90, 100 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.DamageFatigue,
                range = rangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
            } },
        },
    },
    {
        id = "sanctuary-fortifyLongBlade-drainBlock-damageFatigue-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.Sanctuary,
                range = rangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.FortifySkill,
                skill = skills.longblade.id,
                range = rangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.DrainSkill,
                skill = skills.block.id,
                range = rangeTypes.Self,
                min = { 50, 60, 70, 80, 90 },
                max = { 60, 70, 80, 90, 100 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.DamageFatigue,
                range = rangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.LongBladeOneHand] = true,
            } },
        },
    },
    {
        id = "disintegrateArmor-touch-damageFatigue-self-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.DisintegrateArmor,
                range = rangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 50, 75, 100, 150, 200 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = effectTypes.DamageFatigue,
                range = rangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 20, 40, 60, 80, 100 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.AxeOneHand] = true,
                [T.Weapon.TYPE.AxeTwoHand] = true,
                [T.Weapon.TYPE.BluntTwoClose] = true,
                [T.Weapon.TYPE.BluntTwoWide] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "drainSpeedAgility-fortifyStrength-onStrike",
        affixType = "suffix",
        value = 100,
        castType = enchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.speed.id,
                range = rangeTypes.Touch,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.DrainAttribute,
                attribute = attributes.agility.id,
                range = rangeTypes.Touch,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = effectTypes.FortifyAttribute,
                attribute = attributes.strength.id,
                range = rangeTypes.Touch,
                min = { 25, 30, 40, 55, 70 },
                max = { 30, 35, 45, 60, 75 },
                duration = { 5, 5, 5, 5, 5 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.SpearTwoWide] = true,
            } },
        },
    },
}