return {
"ko_goddess_bracer_l",
"ko_goddess_bracer_r",
"ko_goddess_brownboots",
"ko_goddess_curaiss",
"ko_elvencuraisss",
"ko_elvenboots_arm",
"ko_elven_right_gauntlet",
"ko_elven_left_gauntlet",
"ko_bronzed_curaiss",
"ko_bronzed_boots",
"bka2_elfen_pauldl",
"bka2_elven_pauldr",
"bka2_bootsv_3",
"bka2_femcoat_k06",
"bka2_bootsv_1",
"bka2_femcoat_k01",
"bka2_bootsv_2",
"bka2_femcoat_k05",
"bka2_femcoat_k07",
"bka2_femcoat_k08",
"bka2_femcoat_k02",
"bka2_femcoat_k03",
"bka2_femcoat_k04",
"bka2_coat_1arm",
"bka2_celtic_bronze",
"bka2_elfen armor",
"bka2_celtic_silver",
"bka2_silver_armor_01",
"bka2_silver_armor_02",
"bka2_silver_armor_03",
"bka2_silver_armor_04",
"bka2_silver_armor_05",
"bka2_silver_armor_06",
"bka2_gold_armor_01",
"bka2_gold_armor_02",
"bka2_silver_armor_lion",
"bka2_thief_armor1",
"bka2_thief_armor2",
"bka2_gambeson_or",
"bka2_gambeson_gr",
"bka2_livery1",
"bka2_livery2",
"bka2_livery3",
"bka2_livery4",
"bka2_livery5",
"bka2_livery6",
"bka2_livery7",
"bka2_livery8",
"bka2_livery9",
"bka2_livery10",
"bka2_coat_2arm",
"bka2_coat_3arm",
"bka2_coat_4arm",
"bka2_coat_5arm",
"bka2_coat_6arm",
"bka2_coat_7arm",
"bka2_coat_8arm",
"bka2_coat_9arm",
"bka2_leather_01arm",
"bka2_leather_02arm",
"bka2_leather_03arm",
"bka2_coat_10arm",
"bka2_coat_of_arm1",
"bka2_coat_of_arm2",
"bka2_coat_of_arm3",
"bka2_coat_of_arm4",
"bka2_coat_of_arm5",
"bka2_coat_of_arm6",
"bka2_pants_1",
"bka2_pants_3",
"bka2_pants_6",
"bka2_pants_7 ",
"bka2_pants_2 ",
"bka2_pants_8",
"bka2_pants_9",
"bka2_pants10",
"bka2_pants11",
"bka2_pants12",
"bka2_femcoat_k09",
"ko_silver_pauldron_right",
"ko_white_cape_gold",
"ko_white_cape_silver",
"ko_fur_coats",
"ko_fur_pantss",
"ko_fur_bootss",
"ko_festival_hat_armor",
"ko_festival_hat_gr_armor",
"ko_dark_mage_robe",
"ko_fae_purple_wig",
"ko_fae_blue_wig",
"ko_fae_green_wig",
"ko_fae_pink_wig",
"ko_floral_hat_armor",
"ko_eye_patch_armor",
"ko_black_hat_feather",
"ko_black_hat",
"ko_orc_priestess_armor",
"ko_white_fur_pants_armor",
"ko_white_fur_jacket_armor",
"ko_white_fur_pants_boots",
"ko_skull_staff_sheild",
"r05 dress",
"r05 boots",
"r06 dress",
"r06 bodysuit",
"r06 boots",
"r07 dress",
"r07 boots",
"r08 boots",
"r08 pants",
"r08 shirt",
"r09 dress",
"r09 boots",
"r10 bodysuit",
"r10 boots",
"r10 skirt",
"r11 pants",
"r11 shirt",
"r12 boots",
"r12 bodysuit",
"r12 glove",
"r12 sleeve",
"r12 skirt",
"r13 robe",
"r13 boots",
"r14 bodysuit",
"r14 boots",
"r15 dress",
"r16 dress",
"r17 tunic",
"r17 tights",
"r17 boots",
"ko_warrior_queen_robe",
"ko_silver_curaiss",
"ko_silver_greeves",
"ko_silver_pauldron_left",
"ko_silver_boots",
"ko_silver_gauntlet_l",
"ko_silver_gauntlet_r",
"ko_silver_helm",
"ko_silver_sheilds",
"ko_professional_curiass",
"ko_professional_greaves",
"ko_professional_boots_arm",
"ko_mfae_ar_wig_01",
"ko_mfae_ar_whiterose",
"ko_mfae_ar_yellowrose",
"ko_mfae_ar_pinkrose",
"ko_mfae_ar_purplerose",
"ko_mfae_ar_bluerose",
"ko_mfae_ar_redrose",
"ko_mfae_ar_blackrose",
"ko_dawn_boots_green_armor",
"ko_dawn_curaiss_green_armor",
"ko_dawn_curaiss_white_armor",
"ko_dawn_boots_white_armor",
"ko_dawn_boots_black_armor",
"ko_dawn_curaiss_black_armor",
"ko_dawn_curaiss_red_armor",
"ko_dawn_boots_red_armor",
"ko_dawn_sheild",
"ko_curaiss_ladydeath",
"ko_lady death's boots",
"ko_red_sheild",
"ko_celtic_sheild",
"ko_venomrose_arm_bodysuit",
"ko_venomrose_arm_bootsblk",
"ko_redglass_shield",
"ko_redglass_towershield",
"ko_gypsywig",
"ko_falconer_arm_skirt_leather",
"ko_falconer_acuirass_leather_f",
"ko_arm_rangersheild",
"ko_falconer_arm_boots_leather_m",
"ko_falconer_arm_boots_leather_f",
"ko_falconer_acuirass_leather_m",
"ko_falconer_agreeves_male",
"ko_falconer_arm_coats",
"ko_falconer_agreeves_female_lu",
"ko_falconer_agreeves_female",
}
