return {
    "and horker",
    "anki's",
    "anna",
    "armored",
    "bar maid's",
    "battle dawn",
    "bavarian",
    "bergschenken",
    "black & red",
    "blackyellow",
    "bloodcape",
    "blueyellow",
    "bronzed",
    "carlile",
    "celtic",
    "chain",
    "chainplate",
    "chinese",
    "cloudy",
    "colored",
    "corded",
    "court",
    "crude",
    "crusader",
    "dame",
    "dark",
    "dawn of an angel",
    "death's kiss",
    "dew drop",
    "elfen",
    "elven",
    "fae",
    "falconer",
    "female",
    "festival",
    "fiona's",
    "fire",
    "fishnet",
    "flemish",
    "floral",
    "flower",
    "gardener's",
    "goddess",
    "gypsy",
    "heeled",
    "korana's",
    "lace up",
    "lace",
    "laced",
    "ladies",
    "lady koranas's",
    "layered",
    "light",
    "lightning",
    "lin corish",
    "lingere",
    "long's",
    "male",
    "men's",
    "of the baron a",
    "of the crusader",
    "of the guard",
    "of the healer a",
    "of the landsknecht a",
    "of the lord a",
    "of the veteran a",
    "old world",
    "peacock",
    "peasant",
    "pirate",
    "plateau",
    "plated",
    "poet",
    "priestess",
    "professional",
    "psychodelic",
    "pumpkin",
    "rainbow",
    "ranger's",
    "robin hood",
    "sabrina's",
    "short",
    "shroud of darkness",
    "silk",
    "snowflakes",
    "sparkle",
    "sparrow",
    "sprite",
    "starfield",
    "striped",
    "sweet",
    "the maiden's",
    "thief",
    "velvet",
    "venetian",
    "venom rose's",
    "veteran",
    "war maiden",
    "wearable",
    "wench",
}