-- -----------------------------------------------------------------------------
-- Item data for OAAB_Data
-- -----------------------------------------------------------------------------
return {
   consumables = {
      -- Drinks                            Th  Hu  Ex
      ["ab_dri_guarmilk"]              = { -150, 0, 0 },
      ["ab_dri_musa"]                  = { -100, 0, 0 },
      ["ab_dri_sillapi"]               = { -50, 0, 0 },
      ["ab_dri_tramatea"]              = { -150, 0, 0 },
      ["ab_dri_yamuz"]                 = { -50, 0, 0 },
      -- Food                              Th  Hu  Ex
      ["ab_ingcrea_guarmeat_01"]       = { 0, -150, 0 },
      ["ab_ingcrea_horsemeat01"]       = { 0, -150, 0 },
      ["ab_ingcrea_sfmeat_01"]         = { 0, -150, 0 },
      ["ab_ingcrea_sturgeonmeat01"]    = { 0, -150, 0 },
      ["ab_ingcrea_sturgeonmeat02"]    = { 0, -150, 0 },
      ["ab_ingcrea_sturgeonmeat03"]    = { 0, -150, 0 },
      ["ab_ingflor_pomegranate01"]     = { 0, -50, 0 },
      ["ab_ingflor_pomegranate02"]     = { 0, -50, 0 },
      ["ab_ingfood_bread01a"]          = { 0, -100, 0 },
      ["ab_ingfood_bread01b"]          = { 0, -100, 0 },
      ["ab_ingfood_bread02"]           = { 0, -100, 0 },
      ["ab_ingfood_comjam"]            = { 0, -150, 0 },
      ["ab_ingfood_doughlump"]         = { 0, -50, 0 },
      ["ab_ingfood_doughrolled"]       = { 0, -50, 0 },
      ["ab_ingfood_kwamaeggcentcut"]   = { 0, -100, 0 },
      ["ab_ingfood_kwamaeggcentwrap"]  = { 0, -100, 0 },
      ["ab_ingfood_kwamaloaf"]         = { 0, -150, 0 },
      ["ab_ingfood_kwamaloafslice"]    = { 0, -100, 0 },
      ["ab_ingfood_saltricebread"]     = { 0, -100, 0 },
      ["ab_ingfood_saltriceporridge"]  = { 0, -100, 0 },
      ["ab_ingfood_scuttlepie"]        = { 0, -150, 0 },
      ["ab_ingfood_sweetroll"]         = { 0, -50, 0 },
      ["ab_ingfood_wickwheatdumpling"] = { 0, -100, 0 },
   },
   containers = {
     "ab_misc_combottle_01",
     "ab_misc_combottle_02",
     "ab_misc_combottle_03",
     "ab_misc_combottler01",
     "ab_misc_combottler02",
     "ab_misc_combottler03",
     "ab_misc_combottler04",
     "ab_misc_combottler05",
     "ab_misc_combottler06",
     "ab_misc_declayflask_01",
     "ab_misc_declayflask_02",
     "ab_misc_deyelglassflask_01",
     "ab_misc_drinkcyrobrandy",
     "ab_misc_drinkflin",
     "ab_misc_drinkgreef",
     "ab_misc_drinkmazte",
     "ab_misc_drinkshein",
     "ab_misc_drinksillapi",
     "ab_misc_drinksujamma",
   },
}
