local goalsList = {
    { name = "Become a millionaire", description = "Sit on a dragon's horde of 1 million septims." },
    { name = "Hunter: REPLACE", description = "Kill 100 REPLACE.", replacerOptions = { "Cliff Racers", "Alit", "Golden Saints", "Durzogs", "Clannfear"} },
    { name = "Kill REPLACE", description = "REPLACE needs to die.", replacerOptions = { "Fargoth", "Caius Cosades", "Gothren", "Bolvyn Venim", "Orvas Dren", "Duke Vedam Dren", "Tholer Saryoni", "Berel Sala", "Crassius Curio", "Therana", "Neloth", "Divayth Fyr"} },
    { name = "The Tribunal Must Die", description = "Their time is over. Kill Almalexia, Sotha Sil, and Vivec." },
    { name = "Become REPLACE leader", description = "Become the leader of the REPLACE.", replacerOptions = { "Mages Guild", "Fighters Guild", "Thieves Guild", "Imperial Legion", "Imperial Cult", "Tribunal Temple", "Morag Tong", "House Hlaalu", "House Telvanni", "House Redoran" }},
    { name = "Bloodbath", description = "Exterminate 30 members of the Camonna Tong." },
    { name = "Pious Pilgrim", description = "Complete all the Tribunal Temple pilgrimages." },
    { name = "Guar Herder", description = "Gather a herd of guar. Bonus points if you can gather together friends such as Corky and Rollie." },
    { name = "Acquire REPLACE", description = "It must be yours.", replacerOptions = { "Moon-and-Star", "The Fork of Horripilation", "Azura's Star", "Mehrunes Razor", "The Comfy Pillow" } },
    { name = "Steal 5 artifacts from museum", description = "They must ALL be yours." },
    { name = "Dwemer collector", description = "Collect 10 of each type of Dwemer item." },
    { name = "Become a vampire", description = "Become a feared creature of the night." },
    { name = "Become a werewolf", description = "Become a feared creature of the night." },
    { name = "Abolitionist", description = "Free 30 slaves." },
    { name = "Soul dealer", description = "Soultrap 30 different creatures." },
    { name = "Polite Tomb Visitor", description = "Make an offering in 100 tombs." },
    { name = "Entertainer", description = "Tell a joke in every inn." },
    { name = "Tribute giver", description = "Pay tribute to Pop Je, Scourge, G.Lyngas, Lord Brinne and D. Bryant." },
    { name = "Vivec's Wisdom", description = "Collect 36 sermons." },
    { name = "M'aiq's Wisdom", description = "Find M'aiq and ask for his wisdom on various topics." },
    { name = "Sanguine Collector", description = "Collect all 27 Sanguine Items." },
    { name = "Curse seeker", description = "Collect 20 cursed diamonds, daedra hearts, emeralds, pearls, ebony chunks, and rubies." },
    { name = "Hide collector", description = "Collect a set of hides: Girith, Marsus, alit, kagouti, guar, netch, bear, wolf, and bristleback." },
    { name = "Miner", description = "Collect 20 pieces of glass, ebony, adamantium, and Stalhrim." },
    { name = "Necromancer", description = "Collect 20 skulls, 20 servant skulls and the dwarven bone." },
    { name = "Flavour seeker", description = "Collect 15 ash, salt, frost and void salts." },
    { name = "Dagoth slayer", description = "Kill 36 Dagoths." },
    { name = "Exorcist", description = "Collect 100 ectoplasm, including the Gateway Ghost, Galos, Kanit, Senipul and Mezalf." },
    { name = "Magpie", description = "Collect 50 of each precious gem, eg: pearls, diamond, emeralds, rubies." },
    { name = "Addict", description = "Collect the following: a skooma pipe, silver spoon, 50 pieces of moon sugar, and 50 bottles of skooma." },
    { name = "Jiub's rival", description = "Collect 200 racer plumes from racers you slew yourself." },
    { name = "Oblivion bane", description = "Collect 50 pieces each of daedra skin, daedra heart, and scamp skin." },
    { name = "Poisoner", description = "Collect poison goop, 10 corprus weepings, and 10 spoiled potions." },
    { name = "Heavy drinker", description = "Collect 5 of each beverage. Then let the party begin!" },
    { name = "Numismatist", description = "Collect coins: 50 dwemer 10 magic, 10 of any others." },
    { name = "Ash Statue expert", description = "Collect 150 ash statues." },
    { name = "Sea lover", description = "Collect 200 shells, stars, pearls etc." },
    { name = "Become a Dagoth", description = "Go through with the transformation into a Dagoth." },
    { name = "Long live the King", description = "Kill Helseth." },
    { name = "Bow to the Duke", description = "Pay all the dukes and duchesses a visit." },
    { name = "Undead army", description = "Summon an army of 20 undead minions." },
    { name = "Daedra worshipper", description = "Complete quests for 5 of the Daedric Princes." },
    { name = "Mudcrab's Mate", description = "Bring the Drunken Mudcrab to a tavern." },
    { name = "Plunder the Dungeon", description = "Plunder Divayth Fyr's tower for treasures." },
    { name = "Give Ur victory", description = "This time, make sure Dagoth Ur wins." },
    { name = "Oblivion Explorer", description = "Visit 5 different realms of Oblivion."},
    { name = "Lich Aspirant", description = "Become a lich."},
    { name = "Plaguebearer", description = "Infect 100 different NPCs with diseases."},
    { name = "Bounty Hunter", description = "Bring death to 20 notorious outlaws."},
    { name = "Master of Mushrooms", description = "Build a new Telvanni city."},
    { name = "Dwemer Scholar", description = "Discover what happened to the Dwemer."},
    { name = "Interprovincial Traveler", description = "Visit at least three different provinces of Tamriel."},
    { name = "Fashionista", description = "Swap outfits every day; collect one of each robe."},
    { name = "Architect", description = "Build a pillow fort."},
    { name = "Explorer", description = "Visit somewhere you've never been."},
    { name = "Librarian", description = "Collect 500 books." },
    { name = "Vampire Hunter", description = "Kill all vampires." },
    { name = "Tourist", description = "Visit REPLACE.", replacerOptions = { "Seyda Neen", "Pelagiad", "Vivec", "Ebonheart", "Sadrith Mora", "Tel Aruhn", "Tel Mora", "Tel Fyr", "Tel Branora", "Balmora", "Hla Oad", "Gnaar Mok", "Suran", "Ald-ruhn", "Maar Gan", "Molag Mar", "Gnisis", "Khuul", "Ald Velothi", "Solstheim", "Ghostgate", "Mournhold" } },
    { name = "City Life: REPLACE", description = "Earn enough to buy a dwelling, preferably in the city of REPLACE.", replacerOptions = { "Seyda Neen", "Pelagiad", "Vivec", "Ebonheart", "Vos", "Dagon Fel", "Sadrith Mora", "Balmora", "Hla Oad", "Gnaar Mok", "Suran", "Ald-ruhn", "Maar Gan", "Gnisis", "Khuul", "Mournhold", "Old Ebonheart" } },
	{ name = "Country Life", description = "Buy a dwelling outside a city, preferably in REPLACE.", replacerOptions = { "the Ascadian Isles", "the Ashlands", "Azura's Coast", "the Bitter Coast", "the Grazelands", "Molag Amur", "Sheogorad", "the West Gash", "Aanthirin", "Roth Roryn" } },
    { name = "Affinity for Enchantments", description = "Acquire 60 enchanted items." },
    { name = "Life of a Trader", description = "Amass a horde of wealth through trading." },
	{ name = "Life of a Prohibitionist", description = "Do not drink alchohol. Stay out of places that serve it." },
	{ name = "Life of Crime", description = "Build a bounty on your head to tune of 10,000 septims." },
	{ name = "Life of a Solitudinarian", description = "You prefer to travel alone. You strongly dislike riding with Caravaneers or Gondoleers and outright refuse any traveling companions." },
	{ name = "Life of a Pickpocket", description = "Pickpocketing has always given you a rush. Pick 100 pockets." },
	{ name = "Life of a Hermit", description = "Towns are too crowded for you. Stay out of them unless absolutely neccesary." },
	{ name = "Life of Renown", description = "The people will know your name. Earn 40 reputation." },
	{ name = "Life of the Carefree", description = "Even the lightest of armors has always felt too restrictive for you. You refuse to wear such." },
	{ name = "Life of the Incarnate", description = "Bring an end to the source of the blight plaguing Vvardenfell." },
	{ name = "Life of a Fisherman", description = "Fish five times in every region of Vvardenfell." },
	{ name = "Life of a Pascifist", description = "You shun violence and refuse to enact it yourself. You prefer to handle dangerous situations through pacification magic or slipping away." },
	{ name = "Life of an Iconoclast", description = "Steal Vivec's Ashmask. Slay them while wearing it." },
	{ name = "Life of the Devout", description = "The Tribunal Temple is your guiding light. Visit all their temples and make an offering." },
    { name = "Nomad", description = "You strive to explore the world. Refrain from staying in one place for more than a few nights." },
    { name = "Skooma Brewer", description = "You seek the perfect recipe for your Skooma. Brew 50 bottles." },
	{ name = "Legitimate Citizen", description = "You strive to act within the confines of local law and customs, for whatever reason you have." },
	{ name = "Golden Fascination", description = "You love septims. So much that you can't bring yourself to spend them, only collect more. Gather as many as you can to sate your fascination." },
	{ name = "Bandit's Horde", description = "Amass a horde of stolen wealth." },
	{ name = "Initiate", description = "Intrigued by their ways, you seek to join the ranks of REPLACE.", replacerOptions = { "House Hlaalu", "House Redoran", "House Telvanni", "the Sixth House", "the East Empire Company", "the Fighters Guild", "the Mages Guild", "the Imperial Cult", "the Imperial Legion", "the Tribunal Temple", "the Twin Lamps", "the Thieves Guild", "the Dark Brotherhood" } },
	{ name = "Odd Desires", description = "You have a strange fascination with REPLACE. Collect as many of them as you can.", replacerOptions = { "Pearls", "Candles", "Pillows", "Skooma Pipes", "Limeware", "Spoons", "Brooms", "Muck Shovels", "Skulls", "Belts" } },
	{ name = "Red Mountaineer", description = "Despite the risks, you wish to ascend to the highest peak on Vvardenfell. Climb Red Mountain." },
	{ name = "Good Hearted", description = "Cure 50 diseased or blighted creatures." },
	{ name = "Minimalist", description = "Carrying too much only gives you a headache. You strive to keep little on you at all times." },
	{ name = "Pack Rat", description = "You find it hard to let go of things. Hold as much as you can at all times." },
	{ name = "Camper", description = "Spend a night under the stars in REPLACE.", replacerOptions = { "the Ascadian Isles", "the Ashlands", "Azura's Coast", "the Bitter Coast", "the Grazelands", "Molag Amur", "Red Mountain", "Sheogorad", "the West Gash", "the Sundered Scar", "Aanthirin", "Roth Roryn" } },
	{ name = "Thalassophobic", description = "Something about open water doesn't sit well with you. Avoid crossing it in your travels." },
	{ name = "Strange Tastes: REPLACE", description = "You can't get enough of the taste of REPLACE. Eat as much of it as you can find.", replacerOptions = { "Muck", "Corprus Meat", "Rat Meat", "Scamp Skin", "Scrap Metal", "Raw Glass", "Ampoule Pods", "Ectoplasm", "Sload Soap" } }, 
	{ name = "Seedy Spots", description = "Visit REPLACE.", replacerOptions = { "Desele's House Of Earthly Delights in Suran", "The Eight Plates in Balmora", "The Black Shalk Corner Club in Vivec", "Fat Leg's Drop Off in Hla Oad" } },
	{ name = "Armor Collector: REPLACE", description = "You wish to acquire a full set of REPLACE armor.", replacerOptions = { "Netch Leather", "Glass", "Ice", "Bonemold", "Indoril", "Dwemer", "Imperial Steel", "Royal Guard", "Nordic Fur", "Le Femm" } },
	{ name = "Weapon Collector: REPLACE", description = "Armaments are of interest to you. In particular REPLACE, develop a collection of them.", replacerOptions = { "Bows", "Long Swords", "Short Swords", "Daggers", "Maces", "Spears", "Axes", "Throwing Weapons" } },
	{ name = "Jewelry Collector: REPLACE", description = "You love all kinds of jewelry but in particular, REPLACE. Collect 50 of them.", replacerOptions = { "Enchanted Rings", "Enchanted Amulets", "Expensive Amulets", "Ruby Amulets", "Sapphire Amulets", "Expensive Rings", "Extravagant Rings", "Exquisite Rings" } },
	{ name = "Skeptical of Magic", description = "You don't trust magic or mages and prefer to achieve your goals without the aid of either." },
	{ name = "Neophyte: REPLACE", description = "Join the ranks of the REPLACE.", replacerOptions = { "Aundae Clan", "Berne Clan", "Quarra Clan" } },
	{ name = "Golden Disdain", description = "You despise septims and refuse to carry them or conduct trade using them. Despite the hassles it may bring you." },
	{ name = "Frequent Flier", description = "For your own reasons, you prefer to soar through the air as opposed to walk on the ground. Utilize spells of levitate and jump with reckless abandon." },
	{ name = "Floriculture", description = "Collect 75 flower samples." },
	{ name = "Botany: REPLACE", description = "Collect 60 samples of plant fauna from this region.", replacerOptions = { "Ascadian Isles", "Ashlands", "Azura's Coast", "Bitter Coast", "Grazelands", "Molag Amur", "Sheogorad", "West Gash", "Aanthirin", "Roth Roryn", "Red Mountain" } },
	{ name = "Athlete", description = "Become the fastest in Morrowind. Train the following to 80: Speed, Athletics, Acrobatics." },
	{ name = "Compensate: REPLACE", description = "You feel lacking in REPLACE. To compensate, collect 30 buffing items.", replacerOptions = { "Strength", "Endurance", "Agility", "Speed", "Personality", "Intelligence", "Willpower", "Luck", } },
	{ name = "K.O. King", description = "Knockout Fargoth, Caius Cosades, Yargrum Bagarn, Hentus Yarsurnummu, Vivec, Dagoth Ur."},
	{ name = "Master Soldier:REPLACE", description = "You wish to develop a mastery of REPLACE. No matter how long it takes.", replacerOptions = { "Ranged Weapons", "Long Swords", "Short Swords", "Daggers", "Maces", "Spears", "Axes" } },
	{ name = "Master Craftsmen:REPLACE", description = "You wish to develop a mastery of REPLACE. No matter how long it takes.", replacerOptions = { "Alchemy", "Enchanting", "Mercantile Skills", "Armor Working" } },
	{ name = "Master Wizard: REPLACE", description = "You wish to develop a mastery of REPLACE. No matter how long it takes.", replacerOptions = { "Illusion", "Conjuration", "Alteration", "Destruction", "Mysticism", "Restoration", } },
}

return goalsList