return {
    food = {
        "o_guar_ribs_roasted",
        "o_kwama_bun",
        "o_ribs_spicy",
        "o_guar_ribs_beans",
        "o_ml_fish_rice",
        "o_ml_guar_ribs_bread",
        "o_ml_egg_guar_jerky",
        "o_spice_rice",
        "o_netch_jelly",
        "o_ml_b_anther_meat",
        "o_drumstick_big",
        "o_drumstick_small",
        "o_ml_comberry_fish",
        "o_ml_roasted_scrib",        
        "o_ml_egg_bread",
        "o_sandwich_eggslice",
        "o_sandwich_meat",
        "o_sandwich_meat_dbl",        
        "o_boilegg",
        "o_ml_3roll",
        "o_ml_meatrice_mt",
        "o_sandwich_egg_dbl",
        "o_ml_ash_roast",
        "o_ml_meatash",
        "o_ml_yamscut",
        "o_meat_roast",
        "o_ml_2xsandw",
        "o_bowl_beans",
    },

    drink = {
		"o_cp_juc_cberry",
		"o_juice_comberry",
		"o_tea_bittergreen",
		"o_tea_bittergreen_p",
		"o_tea_bittergreen_s",
		"o_tea_firefern",
		"o_tea_goldenkanet",
		"o_tea_goldkanet_s",
		"o_tea_kanet_milk",
		"o_tea_kresh",
		"o_tea_kresh_peach",
		"o_tea_scathecraw_y",
		"o_tea_swamp",
    },

    misc = {}
}