return {
	"bm bear boots",
	"bm bear cuirass",
	"bm bear greaves",
	"bm bear helmet",
	"bm bear left gauntlet",
	"bm bear left pauldron",
	"bm bear right gauntlet",
	"bm bear right pauldron",
	"bm bear shield",
	"bm huntsman axe",
	"bm huntsman spear",
	"bm nordic silver axe",
	"bm nordic silver battleaxe",
	"bm nordic silver claymore",
	"bm nordic silver dagger",
	"bm nordic silver longsword",
	"bm nordic silver mace",
	"bm nordic silver shortsword",
	"bm silver dagger wolfender",
	"bm wolf boots",
	"bm wolf cuirass",
	"bm wolf greaves",
	"bm wolf helmet",
	"bm wolf left gauntlet",
	"bm wolf left pauldron",
	"bm wolf right gauntlet",
	"bm wolf right pauldron",
	"bm wolf shield",
	"bm_nordic02_glovel",
	"bm_nordicmail_boots",
	"bm_nordicmail_cuirass",
	"bm_nordicmail_gauntletl",
	"bm_nordicmail_gauntletr",
	"bm_nordicmail_greaves",
	"bm_nordicmail_helmet",
	"bm_nordicmail_pauldronl",
	"bm_nordicmail_pauldronr",
	"bm_nordicmail_shield",
	"bm_wool01_shoes",
	"bm_wool02_shoes",
	"bonemold arrow",
	"bonemold bolt",
	"bonemold long bow",
	"bonemold_boots",
	"bonemold_bracer_left",
	"bonemold_bracer_right",
	"bonemold_cuirass",
	"bonemold_greaves",
	"bonemold_helm",
	"bonemold_pauldron_l",
	"bonemold_pauldron_r",
	"bonemold_shield",
	"bonemold_towershield",
	"chitin arrow",
	"chitin boots",
	"chitin club",
	"chitin cuirass",
	"chitin dagger",
	"chitin greaves",
	"chitin guantlet - left",
	"chitin guantlet - right",
	"chitin helm",
	"chitin pauldron - left",
	"chitin pauldron - right",
	"chitin short bow",
	"chitin shortsword",
	"chitin spear",
	"chitin throwing star",
	"chitin war axe",
	"chitin_shield",
	"chitin_towershield",
	"cloth bracer left",
	"cloth bracer right",
	"common_amulet_01",
	"common_amulet_02",
	"common_amulet_03",
	"common_amulet_04",
	"common_amulet_05",
	"common_belt_02",
	"common_pants_01",
	"common_pants_01_a",
	"common_pants_01_e",
	"common_pants_01_u",
	"common_pants_01_z",
	"common_pants_02",
	"common_pants_02_hentus",
	"common_pants_03",
	"common_pants_03_b",
	"common_pants_03_c",
	"common_pants_04",
	"common_pants_04_b",
	"common_pants_05",
	"common_ring_01",
	"common_ring_01_mgbwg",
	"common_ring_02",
	"common_ring_03",
	"common_ring_04",
	"common_ring_05",
	"common_ring_05_bm_uni",
	"common_robe_01",
	"common_robe_02",
	"common_robe_02_h",
	"common_robe_02_hh",
	"common_robe_02_r",
	"common_robe_02_rr",
	"common_robe_02_t",
	"common_robe_02_tt",
	"common_robe_03",
	"common_robe_03_a",
	"common_robe_03_b",
	"common_robe_04",
	"common_robe_05",
	"common_robe_05_a",
	"common_robe_05_b",
	"common_robe_05_c",
	"common_shirt_01",
	"common_shirt_01_a",
	"common_shirt_01_e",
	"common_shirt_01_u",
	"common_shirt_01_z",
	"common_shirt_02",
	"common_shirt_02_h",
	"common_shirt_02_hh",
	"common_shirt_02_r",
	"common_shirt_02_rr",
	"common_shirt_02_t",
	"common_shirt_02_tt",
	"common_shirt_03",
	"common_shirt_03_b",
	"common_shirt_03_c",
	"common_shirt_04",
	"common_shirt_04_a",
	"common_shirt_04_b",
	"common_shirt_04_c",
	"common_shirt_05",
	"common_shoes_01",
	"common_shoes_02",
	"common_shoes_03",
	"common_shoes_04",
	"common_shoes_05",
	"common_skirt_02",
	"corkbulb bolt",
	"daedric battle axe",
	"daedric claymore",
	"daedric club",
	"daedric dagger",
	"daedric dai-katana",
	"daedric katana",
	"daedric long bow",
	"daedric longsword",
	"daedric mace",
	"daedric shortsword",
	"daedric spear",
	"daedric staff",
	"daedric tanto",
	"daedric wakizashi",
	"daedric wakizashi_hhst",
	"daedric war axe",
	"daedric warhammer",
	"daedric_shield",
	"daedric_towershield",
	"dragonscale_towershield",
	"dreugh club",
	"dreugh staff",
	"dreugh_cuirass",
	"dreugh_helm",
	"dreugh_shield",
	"dwarven battle axe",
	"dwarven claymore",
	"dwarven crossbow",
	"dwarven halberd",
	"dwarven mace",
	"dwarven shortsword",
	"dwarven spear",
	"dwarven war axe",
	"dwarven warhammer",
	"dwemer_boots",
	"dwemer_bracer_left",
	"dwemer_bracer_right",
	"dwemer_cuirass",
	"dwemer_greaves",
	"dwemer_helm",
	"dwemer_pauldron_left",
	"dwemer_pauldron_right",
	"dwemer_shield",
	"dwemer_shield_battle_unique",
	"ebony broadsword",
	"ebony longsword",
	"ebony mace",
	"ebony shortsword",
	"ebony spear",
	"ebony staff",
	"ebony war axe",
	"ebony_shield",
	"ebony_shield_auriel",
	"ebony_towershield",
	"expensive_amulet_01",
	"expensive_amulet_02",
	"expensive_amulet_03",
	"expensive_belt_02",
	"expensive_pants_02",
	"expensive_ring_01",
	"expensive_ring_01_bill",
	"expensive_ring_02",
	"expensive_ring_03",
	"expensive_shirt_02",
	"expensive_shoes_02",
	"expensive_skirt_02",
	"exquisite_amulet_01",
	"exquisite_belt_01",
	"exquisite_ring_01",
	"exquisite_ring_02",
	"exquisite_robe_01",
	"exquisite_shirt_01",
	"exquisite_shirt_01_rasha",
	"exquisite_shirt_01_wedding",
	"exquisite_shoes_01",
	"exquisite_skirt_01",
	"extravagant_amulet_01",
	"extravagant_amulet_02",
	"extravagant_belt_01",
	"extravagant_pants_01",
	"extravagant_ring_01",
	"extravagant_ring_02",
	"extravagant_robe_01",
	"extravagant_robe_01_a",
	"extravagant_robe_01_b",
	"extravagant_robe_01_c",
	"extravagant_robe_01_h",
	"extravagant_robe_01_r",
	"extravagant_robe_01_t",
	"extravagant_shirt_01",
	"extravagant_shirt_01_h",
	"extravagant_shirt_01_r",
	"extravagant_shirt_01_t",
	"extravagant_shoes_01",
	"extravagant_skirt_01",
	"foeburner",
	"fur_bearskin_cuirass",
	"fur_boots",
	"fur_bracer_left",
	"fur_bracer_right",
	"fur_cuirass",
	"fur_gauntlet_left",
	"fur_gauntlet_right",
	"fur_greaves",
	"fur_helm",
	"fur_pauldron_left",
	"fur_pauldron_right",
	"glass claymore",
	"glass dagger",
	"glass halberd",
	"glass longsword",
	"glass staff",
	"glass war axe",
	"glass_boots",
	"glass_cuirass",
	"glass_greaves",
	"glass_helm",
	"glass_pauldron_left",
	"glass_pauldron_right",
	"glass_shield",
	"glass_towershield",
	"goblin_club",
	"goblin_sword",
	"imperial boots",
	"imperial broadsword",
	"imperial helmet armor",
	"imperial left gauntlet",
	"imperial left pauldron",
	"imperial right gauntlet",
	"imperial right pauldron",
	"imperial shield",
	"imperial shortsword",
	"imperial skirt_clothing",
	"imperial_chain_coif_helm",
	"imperial_chain_greaves",
	"imperial_chain_pauldron_left",
	"imperial_chain_pauldron_right",
	"imperial_greaves",
	"imperial_studded_cuirass",
	"indoril shield",
	"iron arrow",
	"iron battle axe",
	"iron bolt",
	"iron boots",
	"iron broadsword",
	"iron claymore",
	"iron club",
	"iron dagger",
	"iron halberd",
	"iron long spear",
	"iron longsword",
	"iron mace",
	"iron saber",
	"iron shortsword",
	"iron spear",
	"iron tanto",
	"iron throwing knife",
	"iron wakizashi",
	"iron war axe",
	"iron warhammer",
	"iron_bracer_left",
	"iron_bracer_right",
	"iron_cuirass",
	"iron_gauntlet_left",
	"iron_gauntlet_right",
	"iron_greaves",
	"iron_helmet",
	"iron_pauldron_left",
	"iron_pauldron_right",
	"iron_shield",
	"iron_towershield",
	"left leather bracer",
	"long bow",
	"netch_leather_boiled_cuirass",
	"netch_leather_boiled_helm",
	"netch_leather_boots",
	"netch_leather_cuirass",
	"netch_leather_gauntlet_left",
	"netch_leather_gauntlet_right",
	"netch_leather_greaves",
	"netch_leather_helm",
	"netch_leather_pauldron_left",
	"netch_leather_pauldron_right",
	"netch_leather_shield",
	"netch_leather_towershield",
	"nordic battle axe",
	"nordic broadsword",
	"nordic claymore",
	"nordic_iron_cuirass",
	"nordic_iron_helm",
	"nordic_leather_shield",
	"nordic_ringmail_cuirass",
	"orcish battle axe",
	"orcish bolt",
	"orcish warhammer",
	"orcish_boots",
	"orcish_bracer_left",
	"orcish_bracer_right",
	"orcish_cuirass",
	"orcish_greaves",
	"orcish_helm",
	"orcish_pauldron_left",
	"orcish_pauldron_right",
	"orcish_towershield",
	"right leather bracer",
	"short bow",
	"silver arrow",
	"silver arrow_thirsk_0",
	"silver arrow_thirsk_1",
	"silver arrow_thirsk_2",
	"silver arrow_thirsk_3",
	"silver arrow_thirsk_4",
	"silver arrow_thirsk_5",
	"silver arrow_thirsk_6",
	"silver arrow_thirsk_7",
	"silver arrow_thirsk_8",
	"silver arrow_thirsk_9",
	"silver bolt",
	"silver claymore",
	"silver dagger",
	"silver dagger_iryon_unique",
	"silver dagger_othril_unique",
	"silver dagger_rathalas_unique",
	"silver dart",
	"silver longsword",
	"silver shortsword",
	"silver spear",
	"silver staff",
	"silver throwing star",
	"silver war axe",
	"silver_cuirass",
	"silver_helm",
	"spiked club",
	"steel arrow",
	"steel axe",
	"steel battle axe",
	"steel bolt",
	"steel broadsword",
	"steel claymore",
	"steel club",
	"steel crossbow",
	"steel dagger",
	"steel dai-katana",
	"steel dart",
	"steel halberd",
	"steel katana",
	"steel longbow",
	"steel longbow_carnius",
	"steel longsword",
	"steel mace",
	"steel saber",
	"steel saber_elberoth",
	"steel shortsword",
	"steel spear",
	"steel staff",
	"steel tanto",
	"steel throwing knife",
	"steel throwing star",
	"steel wakizashi",
	"steel war axe",
	"steel warhammer",
	"steel_boots",
	"steel_boots_ancient",
	"steel_cuirass",
	"steel_cuirass_ancient",
	"steel_gauntlet_left",
	"steel_gauntlet_left_ancient",
	"steel_gauntlet_right",
	"steel_gauntlet_right_ancient",
	"steel_greaves",
	"steel_greaves_ancient",
	"steel_helm",
	"steel_helm_ancient",
	"steel_pauldron_left",
	"steel_pauldron_left_ancient",
	"steel_pauldron_right",
	"steel_pauldron_right_ancient",
	"steel_shield",
	"steel_towershield",
	"steel_towershield_ancient",
	"trollbone_cuirass",
	"trollbone_helm",
	"trollbone_shield",
	"wooden staff",
}
