--[[
ErnGearRandomizer for OpenMW.
Copyright (C) 2025 Erin Pentecost

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
]]
local function buildSet(list)
    local set = {}
    for _, v in ipairs(list) do
        set[string.lower(v)] = true
    end
    return set
end

local uniqueIDs =
    buildSet(
    {
        -- https://en.uesp.net/wiki/Morrowind:Clothing_Artifacts
        "artifact_amulet of heartfire",
        "artifact_amulet of heartheal",
        "artifact_amulet of heartrime",
        "artifact_amulet of heartthrum",
        "amulet_usheeja",
        "madstone",
        "teeth",
        "thong",
        "belt of heartfire",
        "seizing",
        "blood ring",
        "ring_denstagmer_unique",
        "heart ring",
        "ring_mentor_unique",
        "moon_and_star",
        "ring_khajiit_unique",
        "ring_phynaster_unique",
        "ring_surrounding_unique",
        "ring_wind_unique",
        "soul ring",
        "ring_vampiric_unique",
        "ring_warlock_unique",
        "expensive_shirt_hair",
        "shoes of st. rilms",
        -- https://en.uesp.net/wiki/Morrowind:Quest_Items
        "lugrub's axe",
        "dwarven war axe_redas",
        "ebony staff caper",
        "wizard's staff",
        "Rusty_Dagger_UNIQUE",
        "devil_tanto_tgamg",
        "daedric wakizashi_hhst",
        "glass_dagger_enamor",
        "dart_uniq_judgement",
        "dwemer_boots of flying",
        "bonemold_gah-julan_hhda",
        "bonemold_tshield_hrlb",
        "amulet of ashamanu (unique)",
        "amuletfleshmadewhole_uniq",
        "amulet_Agustas_unique",
        "expensive_amulet_delyna",
        "expensive_amulet_aeta",
        "sarandas_amulet",
        "exquisite_amulet_hlervu1",
        "Julielle_Aumines_Amulet",
        "Linus_Iulus_Maran Amulet ",
        "amulet_skink_unique",
        "Linus_Iulus_Stendarran_Belt ",
        "sarandas_belt",
        "common_glove_l",
        "r_balmolagmer",
        "extravagant_rt_art_wild",
        "expensive_glove_left_ilmeni",
        "extravagant_glove_left",
        "right_maur",
        "common_pants_02_hentus",
        "sarandas_pants_2",
        "Adusamsi's_Ring ",
        "extravagant_ring_aund_uni",
        "ring_blackjinx_uniq",
        "exquisite_ring_brallion",
        "common_ring_danar ",
        "sarandas_ring_2",
        "ring_keley",
        "expensive_ring_01_BILL",
        "expensive_ring_aeta",
        "sarandas_ring_1",
        "Expensive_Ring_01_HRDT",
        "exquisite_ring_processus",
        "ring_dahrkmezalf_uniq",
        "Extravagant_Robe_01_Red",
        "robe of st roris",
        "exquisite_robe_drake's pride",
        "sarandas_shirt_2",
        "exquisite_shirt_01_rasha",
        "sarandas_shoes_2",
        "therana's skirt ",
        -- https://en.uesp.net/wiki/Morrowind:Sanguine_Items
        "sanguineamuletenterprise",
        "sanguineamuletglibspeech",
        "sanguineamuletnimblearmor",
        "sanguinebeltbalancedarmor",
        "sanguinebeltdeepbiting",
        "sanguinebeltdenial",
        "sanguinebeltfleetness",
        "sanguinebelthewing",
        "sanguinebeltimpaling",
        "sanguinebeltmartialcraft",
        "sanguinebeltsmiting",
        "sanguinebeltstolidarmor",
        "sanguinebeltsureflight",
        "sanguinerglovehornyfist",
        "sanguinelglovesafekeeping",
        "sanguinergloveswiftblade",
        "sanguineringfluidevasion",
        "sanguineringgoldenw",
        "sanguineringgreenw",
        "sanguineringredw",
        "sanguineringsilverw",
        "sanguineringsublimew",
        "sanguineringtranscendw",
        "sanguineringtransfigurw",
        "sanguineringunseenw",
        "sanguineshoesleaping",
        "sanguineshoesstalking",
        -- https://en.uesp.net/wiki/Morrowind:Weapon_Artifacts
        "cleaverstfelms",
        "axe_queen_of_bats_unique",
        "mace of molag bal_unique",
        "daedric_scourge_unique",
        "warhammer_crusher_unique",
        "sunder",
        "crosierstllothis",
        "staff_hasedoki_unique",
        "staff_magnus_unique",
        "dwarven_hammer_volendrung",
        "ebony_bow_auriel",
        "longbow_shadows_unique",
        "katana_bluebrand_unique",
        "katana_goldbrand_unique",
        "claymore_chrysamere_unique",
        "daedric_crescent_unique",
        "claymore_iceblade_unique",
        "longsword_umbra_unique",
        "dagger_fang_unique",
        "fork_horripilation_unique",
        "keening",
        "mehrunes'_razor_unique",
        "spear_mercy_unique",
        -- https://en.uesp.net/wiki/Morrowind:Armor_Artifacts
        "boots_apostle_unique",
        "tenpaceboots",
        "cuirass_savior_unique",
        "dragonbone_cuirass_unique",
        "ebon_plate_cuirass_unique",
        "lords_cuirass_unique",
        "gauntlet_fists_l",
        "r_unique",
        "wraithguard",
        "wraithguard_jury_rig",
        "helm_bearclaw_unique",
        "daedric_helm_clavicusvile",
        "ebony_shield_auriel",
        "towershield_eleidon_unique",
        "spell_breaker_unique",
        -- https://en.uesp.net/wiki/Tribunal:Unique_Items
        "Gravedigger",
        "King's_Oath_pc",
        "daedric dagger_bar",
        "dagger_symmachus_unique",
        "silver dagger_iryon_unique",
        "silver dagger_othril_unique",
        "silver dagger_rathalas_unique",
        "ebony spear_blessed_unique",
        "goblin_shield_durgok_uni",
        "amulet of verbosity",
        "amulet_gaenor",
        "Helseth's Collar",
        "belt_Goval",
        "mazed_band_end",
        "Helseth's Ring",
        "Variner's Ring",
        "common_robe_EOT",
        "Helseth's Robe",
        -- https://en.uesp.net/wiki/Tribunal:Quest_Items
        "ebony war axe_elanande",
        "dwarven mace_salandas",
        "silver dagger_droth_unique_a",
        "silver dagger_droth_unique",
        "ebony shortsword_soscean",
        "silver spear_uvenim",
        "ebony_cuirass_soscean",
        "silver_helm_uvenim",
        "amulet_salandas",
        "extravagant_robe_02_elanande",
        "bladepiece_02",
        "bladepiece_03",
        "dwemer_satchel00",
        "misc_dwrv_weather",
        "misc_dwrv_weather2",
        "bk_playscript",
        "sc_chridittepanacea",
        -- https://en.uesp.net/wiki/Tribunal:Artifacts
        "Mace of Slurring",
        "stendar_hammer_unique",
        "Sword of Almalexia",
        "bladepiece_01",
        "nerevarblade_01",
        "nerevarblade_01_flame",
        "Bipolar Blade",
        "robe_lich_unique",
        -- https://en.uesp.net/wiki/Bloodmoon:Artifacts
        "BM_Mace_Aevar_UNI",
        "BM_ring_hircine",
        "BM_hunterspear_unique",
        -- https://en.uesp.net/wiki/Bloodmoon:Quest_Items
        "bm nordic pick",
        "steel arrow_Carnius",
        "steel longbow_carnius",
        "steel saber_elberoth",
        "BM_dagger_wolfgiver",
        "fur_colovian_helm_white",
        "amulet of infectious charm",
        "expensive_ring_erna",
        -- https://en.uesp.net/wiki/Bloodmoon:Unique_Items
        "bm_ebonyarrow_s",
        "BM nordic silver axe_spurius",
        "BM_axe_Heartfang_Unique",
        "BM_hunter_battleaxe_unique",
        "BM Nord Leg",
        "Lucky_Break",
        "warhammer_rammekald_unique",
        "silver staff of paralysis",
        "bm_ebony_staff_necro",
        "BM_nordic_silver_lgswd_bloodska",
        "BM nordic silver longsword_cft",
        "BM nordic_longsword_tracker",
        "bm_saber_seasplitter",
        "bm_ebonylongsword_s",
        "solvistapp",
        "BM ice longsword_FG_Unique",
        "nordic claymore_stormfang",
        "BM frostgore",
        "imperial shortsword severio",
        "BM silver dagger wolfender",
        "steel spear snow prince",
        "wolfwalkers",
        "BM Bear Helmet_ber",
        "BM Bear Helmet eddard",
        "BM Wolf Helmet_heartfang",
        "daedric_pauldron_right",
        "steel_helm_ancient",
        "steel_cuirass_ancient",
        "steel_pauldron_left_ancient",
        "steel_pauldron_right_ancient",
        "steel_gauntlet_left_ancient",
        "steel_gauntlet_right_ancient",
        "steel_greaves_ancient",
        "steel_boots_ancient",
        "steel_towershield_ancient",
        "bm_amulspd1",
        "bm_amulstr1",
        "bm_black_glove_l_s",
        "bm_black_glove_r_s",
        "BM_ring_Aesliip",
        "bm_ring_marksman",
        "bm_ring_view",
        "mantle of woe",
        "BM_Nordic01_Robe_whitewalk",
        "light_com_lantern_bm_unique"
    }
)

-- uniqueID returns true if the item record is a unique that should NOT be swapped.
local function uniqueID(id)
    return uniqueIDs[string.lower(id)] == true
end

return {
    uniqueID = uniqueID
}
