local I = require('openmw.interfaces')
I.Settings.registerPage {
    key         = 'UnsteadyHands',
    l10n        = 'UnsteadyHands',
    name        = 'page_name',
    description = 'page_desc',
}
I.Settings.registerGroup {
    key              = 'SettingsDisarm',
    page             = 'UnsteadyHands',
    l10n             = 'UnsteadyHands',
    name             = 'settings_groupName',
    permanentStorage = true,
    order            = 1,
    settings = {
        {
            key         = 'MOD_ENABLED',
            name        = 'mod_enabled_name',
            description = 'mod_enabled_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'DISARM_NPCS',
            name        = 'disarm_npcs_name',
            description = 'disarm_npcs_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'DISARM_CREATURES',
            name        = 'disarm_creatures_name',
            description = 'disarm_creatures_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'DISARM_PLAYER',
            name        = 'disarm_player_name',
            description = 'disarm_player_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'BASE_CHANCE',
            name        = 'base_chance_name',
            description = 'base_chance_desc',
            renderer    = 'number',
            default     = 0.03,
            argument    = { min = 0.01, max = 0.10 },
        },
        {
            key         = 'STR_AGI_FACTOR',
            name        = 'str_agi_factor_name',
            description = 'str_agi_factor_desc',
            renderer    = 'number',
            default     = 0.001,
            argument    = { min = 0, max = 0.01 },
        },
        {
            key         = 'MAX_CHANCE',
            name        = 'max_chance_name',
            description = 'max_chance_desc',
            renderer    = 'number',
            default     = 0.10,
            argument    = { min = 0.05, max = 0.15 },
        },
        {
            key         = 'PLAYER_CHANCE_MULT',
            name        = 'player_chance_mult_name',
            description = 'player_chance_mult_desc',
            renderer    = 'number',
            default     = 1.0,
            argument    = { min = 0.1, max = 3.0 },
        },
        {
            key         = 'CREATURE_COMBAT_MULT',
            name        = 'creature_combat_mult_name',
            description = 'creature_combat_mult_desc',
            renderer    = 'number',
            default     = 0.5,
            argument    = { min = 0.1, max = 1.0 },
        },
        {
            key         = 'CHARGE_THRESHOLD',
            name        = 'charge_threshold_name',
            description = 'charge_threshold_desc',
            renderer    = 'number',
            default     = 0.75,
            argument    = { min = 0.5, max = 1.0 },
        },
        {
            key         = 'PICKUP_RADIUS',
            name        = 'pickup_radius_name',
            description = 'pickup_radius_desc',
            renderer    = 'number',
            default     = 300,
            argument    = { integer = true, min = 50, max = 1000 },
        },
        {
            key         = 'PICKUP_DELAY',
            name        = 'pickup_delay_name',
            description = 'pickup_delay_desc',
            renderer    = 'number',
            default     = 1.5,
            argument    = { min = 0.1, max = 10.0 },
        },
        {
            key         = 'WEIGHT_CHECK_ENABLED',
            name        = 'weight_check_enabled_name',
            description = 'weight_check_enabled_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'WEIGHT_THRESHOLD',
            name        = 'weight_threshold_name',
            description = 'weight_threshold_desc',
            renderer    = 'number',
            default     = 10,
            argument    = { integer = true, min = 0, max = 100 },
        },
        {
            key         = 'SHIELD_PROTECTS',
            name        = 'shield_protects_name',
            description = 'shield_protects_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'NPC_PICKUP_ENABLED',
            name        = 'npc_pickup_enabled_name',
            description = 'npc_pickup_enabled_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'NPC_PICKUP_CHANCE',
            name        = 'npc_pickup_chance_name',
            description = 'npc_pickup_chance_desc',
            renderer    = 'number',
            default     = 0.25,
            argument    = { min = 0.1, max = 1.0 },
        },
        {
            key         = 'DAMAGE_THRESHOLD',
            name        = 'damage_threshold_name',
            description = 'damage_threshold_desc',
            renderer    = 'number',
            default     = 5,
            argument    = { integer = true, min = 1, max = 10 },
        },
        {
            key         = 'SKILL_THRESHOLD',
            name        = 'skill_threshold_name',
            description = 'skill_threshold_desc',
            renderer    = 'number',
            default     = 10,
            argument    = { integer = true, min = 0, max = 20 },
        },
    }
}