local types = require("openmw.types")

return {
    -- don't change that
    DEFAULTS = {
        MOD_ENABLED          = true,
        DISARM_NPCS          = true,
        DISARM_CREATURES     = true,
        DISARM_PLAYER        = true,
        BASE_CHANCE          = 0.03,
        STR_AGI_FACTOR       = 0.001,
        MAX_CHANCE           = 0.15,
        PLAYER_CHANCE_MULT   = 1.0,
        CHARGE_THRESHOLD     = 0.75,
        PICKUP_RADIUS        = 300,
        PICKUP_DELAY         = 1.5,
        WEIGHT_CHECK_ENABLED = true,
        WEIGHT_THRESHOLD     = 10,
        SHIELD_PROTECTS      = true,
        NPC_PICKUP_ENABLED   = true,
        NPC_PICKUP_CHANCE    = 0.25,
        DAMAGE_THRESHOLD     = 5,
        SKILL_THRESHOLD      = 10,
        CREATURE_COMBAT_MULT = 0.5
    },
    WEAPON_SKILL = {
        [types.Weapon.TYPE.ShortBladeOneHand] = "shortblade",
        [types.Weapon.TYPE.LongBladeOneHand]  = "longblade",
        [types.Weapon.TYPE.LongBladeTwoHand]  = "longblade",
        [types.Weapon.TYPE.BluntOneHand]      = "bluntweapon",
        [types.Weapon.TYPE.BluntTwoClose]     = "bluntweapon",
        [types.Weapon.TYPE.BluntTwoWide]      = "bluntweapon",
        [types.Weapon.TYPE.AxeOneHand]        = "axe",
        [types.Weapon.TYPE.AxeTwoHand]        = "axe",
        [types.Weapon.TYPE.SpearTwoWide]      = "spear",
    },
    WEAPON_SOUND = {
        [types.Weapon.TYPE.ShortBladeOneHand] = "Item Weapon Shortblade Up",
        [types.Weapon.TYPE.LongBladeOneHand]  = "Item Weapon Longblade Up",
        [types.Weapon.TYPE.LongBladeTwoHand]  = "Item Weapon Longblade Up",
        [types.Weapon.TYPE.BluntOneHand]      = "Item Weapon Blunt Up",
        [types.Weapon.TYPE.BluntTwoClose]     = "Item Weapon Blunt Up",
        [types.Weapon.TYPE.BluntTwoWide]      = "Item Weapon Blunt Up",
        [types.Weapon.TYPE.AxeOneHand]        = "Item Weapon Blunt Up",
        [types.Weapon.TYPE.AxeTwoHand]        = "Item Weapon Blunt Up",
        [types.Weapon.TYPE.SpearTwoWide]      = "Item Weapon Spear Up",
    },
    -- Add IDs of npcs or creatures who won't get disarmed
    EXCLUDED_NPCS = {
        ["divayth fyr"]             = true,
        ["bolvyn venim"]            = true,
        ["trebonius artorius"]      = true,
        ["wulf"]                    = true,
        ["baladas demnevanni"]      = true,
        ["mastrius"]                = true,
        ["Galos Farethi"]           = true,
        ["eno hlaalu"]              = true,
        ["berel sala"]              = true,
        ["gothren"]                 = true,
        ["Vedam Dren"]              = true,
        ["grand inquisito"]         = true,
        ["Orvas Dren Druglord"]     = true,
        ["almalexia_warrior"]       = true,
        ["barenziah"]               = true,
        ["ordinator_mournhold"]     = true,
        ["ordinator_mh_stationary"] = true,
        ["dandras vules"]           = true,
        ["Gaenor"]                  = true,
        ["yarnar"]                  = true,
        ["karrod"]                  = true,
        ["Salas Valor"]             = true,
        ["TR_m4_varos"]             = true,
        ["TR_m1_T_Rilvin_Dral"]     = true,
        ["TR_m7_Brelin Thevur"]     = true,
        ["TR_m2_Alvu Sareleth"]     = true,
        ["TR_m3_Caecalia Victrix"]  = true,
        ["TR_m1_Ilwen"]             = true,
        ["TR_m1_O_Ilwen"]           = true,
        ["TR_m1_T_Mithras"]         = true,
        ["TR_m3_Kh_Balver Raathim"] = true,
        ["TR_m7_Selar Adryn"]       = true,
        ["TR_m7_Ethala Faranis"]    = true,
        ["TR_m7_Darius Maximius"]   = true,
        ["TR_m7_Hlarur Galan"]      = true,
    },
}