return {
    --Houses
    " house",
    " manor",
    " domain",
    " shack",
    " apartment",
    " yurt",
    "hlaalu",
    "redoran",
    "telvanni",
    "indoril",

    --Velothi
    "ancestral tomb",
    " temple",
    " shrine",
    " chapel",
    "imperial chapel",
    "imperial cult chapel",
    "talos",

    --Guards
    "tower",
    "outpost",
    "fort",
    "tel ",
    "legion",
    "garrison",
    "barracks",


    --Nord
    "barrow",

    --Guilds
    " guild",
    "guild of fighters",
    "fighter's guild",
    "guild of mages",
    "mage's guild",
    "morag",
    "east empire",

    --Mines
    " mine",
    "quarry",
    " cave",
    "farm",
    "plantation",
    "storage",
    "warehouse",

    --Ships
    "ship",
    "cabin",
    "deck",
    "hold",
    "upper level",
    "lighthouse",


    --Shops
    " fine ",
    "trade",
    " goods",
    " wares",
    "market",
    "merchandise",
    "bazaar",
    "enchanter",
    "pawnbroker",
    "alchemist",
    "apothecary",
    "philter",
    "elixir",
    "potion",
    "herbalist",
    "healer",
    "book",
    "librar",
    "outfitter",
    "clothier",
    "tailor",
    "smith",
    "armorer",
    "weapons",
    "potter",
    "arrows",
    "fletcher",
    "the razor hole",
    "drop off",
    "sorcerer",
    "llaalam m",


    --Old Ebonheart
    "the perfect quarrel",
    "the fetcher's pawn",
    "the mother alessia",
    "tail tales",

    --Inns
    "brewer",
    "council club",
    "the rat in the pot",
    "eight plates",
    "lucky lockup",
    "s shovel",
    "the end of the world",
    "six fishes",
    "tower of dusk",
    " tavern",
    "s hole in the wall",
    " inn",
    "cornerclub",
    "arrille",
    "earthly delights",
    "plot and plaster",
    "the covenant",
    "the lizard",
    "the grey lodge",
    "the laughing goblin",
    "underground bazaar",
    "the pious pirate",
    "the dancing cup",
    "golden moons club",
    "the guar with no name",
    "lucky shalaasa's caravanserai",
    "the nest",
    "the gentle velk",
    "the howling noose",
    "silver serpent",
    "unnamed legion bar",
    "the emerald haven inn",
    "mjornir's meadhouse",
    "the red drake",
    "the leaking spore",
    "pilgrim's respite",
    "hostel",
    "the black ogre tavern",
    "the empress katariah",
    "legion boarding house",
    "the moth and tiger",
    "the salty futtocks",
    "the strider's wake",
    "the toiling guar",
    "the howling hound",

    "the avenue",
    "s rest",
    "the dancing jug",
    "the glass goblet",
    "the golden glade",
    "the howling noose",
    "limping scrib",
    "the magic mudcrab",
    "mining bunkhouse",
    " alehouse",
    "the note in your eye",
    "s cutlass",
    "the swallow",
    "twisted root",


    --Dwemer ruins
    "aleft",
    "amschend",
    "arkngth",
    "bethamez",
    "bthanchend",
    "dagoth ur",
    "druscashti",
    "endusal",
    "galom daeus",
    --"mudan",
    "mzahnch",
    "mzanchend",
    "mzuleft",
    "nchard",
    "nchu",
    "odrosal",
    "tureynulal",
    "vemynal",
    "akuband",
    "alencheth",
    "amthuandz",
    "archtumz",
    "barzamthuand",
    "bazak",
    "bazhthum",
    "bthalag",
    "bthangthamuzand",
    "bthuangthuv",
    "bthung",
    "bthzundch",
    "chunzefk",
    "durthungz",
    "stardumz",
    "kemel",
    "khadumzunch",
    "leftunch",
    "manrizache",
    "mvelthngth",
    "mzankh",
    "mzungleft",
    "nchal",
    "nchazdrumn",
    "nchulark",
    "nchulegfth",
    "ngelfltingth",
    "ratharzak",
    "rthungzark",
    "yaztaramz",


    --Dunmer Strongholds
    "andasreth",
    "berandas",
    "falasmaryon",
    "falensarano",
    "hlormaren",
    "indoranyon",
    "kogoruhn",
    "marandus",
    "rotheran",
    "telasero",
    "valenvaryon",
    "baan urlai",
    "bisandryon",
    "hlorandus",
    "idaverrano",
    "koranyon",
    "mandaran",
    "merihayan",
    "othrano",
    "romayon",
    "salandus",
    "tulesmath",
    "turendas",
    "valendus",
    "volenfaryon",


    --Daedric Shrines
    "ashunartes",
    "ashurnibibi",
    "asurdirapal",
    "dushariran",
    "ibishammus",
    "kaushtarari",
    "shashpilamat",
    "zergonipal",
    "ald sotha",
    "ashalmimilkala",
    "assarnatamat",
    "assernerairan",
    "ebernanit",
    "ularradallaku",
    "yasammidan",
    "ashalmawia",
    "bal ur",
    "estunamus",
    "kushtashpi",
    "ramimilk",
    "tusenend",
    "yasirramus",
    "addadshashanammu",
    "ald daedroth",
    "almurbalarammi",
    "asslkushalit",
    "bal fell",
    "ihinipalit",
    "maelkashishi",
    "onnisiralis",
    "zaintiraris",
    "anudnabia",
    "shrine of azura",
    "shrine of boethia",
    "balititashpi",
    "yashazmus",
    "ald uman",
    "alumawia",
    "mashadananit",
    "ashushushi",
    "onimushili",
    "ald mirathi",
    "ossurnashalit",
    "ald niripal",
    "ald uran",
    "ebamusharisus",
    "ashpibishal",
    "bal dushal",
    "veranzaris",
    "baelkashpitu",
    "yanishanabi",
    "hummurushtapi",
    "anashbibi",
    "yamandalkal",
    "yabananit",
    "kannidamarus",
    "ald balaal",
    "essarnartes",
    "esuranamit",
    "hadrumnibibi",
    "ikinammassu",
    "ibiammusashan",
    "bapatipi",
    "shambalu",
    "ebunammidan",
    "bushipananit",
    "ulanababia",
    "malkamalit",
    "teknilashashulpi",
    "yamuninisharn",


}
