local I = require('openmw.interfaces')

I.Settings.registerGroup {
    key              = 'SettingsGreedyNPCs',
    page             = 'GreedyNPCs',
    l10n             = 'GreedyNPCs',
    name             = 'settings_groupName',
    permanentStorage = true,
    order            = 1,
    settings = {
        {
            key         = 'PICKUP_ENABLED',
            name        = 'pickup_enabled_name',
            description = 'pickup_enabled_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'CRIME_ENABLED',
            name        = 'crime_enabled_name',
            description = 'crime_enabled_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'RANK_EXEMPT_ENABLED',
            name        = 'rank_exempt_enabled_name',
            description = 'rank_exempt_enabled_desc',
            renderer    = 'checkbox',
            default     = true,
        },
        {
            key         = 'RANK_EXEMPT_DIFF',
            name        = 'rank_exempt_diff_name',
            description = 'rank_exempt_diff_desc',
            renderer    = 'number',
            default     = 3,
            argument    = { integer = true, min = 1, max = 9 },
        },
        {
            key         = 'PICKUP_RADIUS',
            name        = 'pickup_radius_name',
            description = 'pickup_radius_desc',
            renderer    = 'number',
            default     = 200,
            argument    = { integer = true, min = 50, max = 1000 },
        },
        {
            key         = 'CONTRABAND_RADIUS',
            name        = 'contraband_radius_name',
            description = 'contraband_radius_desc',
            renderer    = 'number',
            default     = 600,
            argument    = { integer = true, min = 100, max = 2000 },
        },
        {
            key         = 'PICKUP_DELAY',
            name        = 'pickup_delay_name',
            description = 'pickup_delay_desc',
            renderer    = 'number',
            default     = 2.0,
            argument    = { min = 0.5, max = 30.0 },
        },
        {
            key         = 'CHAMELEON_THRESHOLD',
            name        = 'chameleon_threshold_name',
            description = 'chameleon_threshold_desc',
            renderer    = 'number',
            default     = 85,
            argument    = { integer = true, min = 1, max = 100 },
        },
        {
            key         = 'SNEAK_THRESHOLD',
            name        = 'sneak_threshold_name',
            description = 'sneak_threshold_desc',
            renderer    = 'number',
            default     = 75,
            argument    = { integer = true, min = 1, max = 100 },
        },
    }
}

I.Settings.registerGroup {
    key              = 'SettingsGreedyNPCsValues',
    page             = 'GreedyNPCs',
    l10n             = 'GreedyNPCs',
    name             = 'settings_groupValues',
    permanentStorage = true,
    order            = 2,
    settings = {
        {
            key         = 'MIN_APPARATUS',
            name        = 'min_apparatus_name',
            description = 'min_apparatus_desc',
            renderer    = 'number',
            default     = 100,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_BOOK',
            name        = 'min_book_name',
            description = 'min_book_desc',
            renderer    = 'number',
            default     = 100,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_CLOTHING',
            name        = 'min_clothing_name',
            description = 'min_clothing_desc',
            renderer    = 'number',
            default     = 25,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_ARMOR',
            name        = 'min_armor_name',
            description = 'min_armor_desc',
            renderer    = 'number',
            default     = 300,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_WEAPON',
            name        = 'min_weapon_name',
            description = 'min_weapon_desc',
            renderer    = 'number',
            default     = 300,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_INGREDIENT',
            name        = 'min_ingredient_name',
            description = 'min_ingredient_desc',
            renderer    = 'number',
            default     = 99,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_POTION',
            name        = 'min_potion_name',
            description = 'min_potion_desc',
            renderer    = 'number',
            default     = 60,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_LOCKPICK',
            name        = 'min_lockpick_name',
            description = 'min_lockpick_desc',
            renderer    = 'number',
            default     = 99,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_PROBE',
            name        = 'min_probe_name',
            description = 'min_probe_desc',
            renderer    = 'number',
            default     = 99,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_REPAIR',
            name        = 'min_repair_name',
            description = 'min_repair_desc',
            renderer    = 'number',
            default     = 99,
            argument    = { integer = true, min = 0, max = 10000 },
        },
        {
            key         = 'MIN_MISC',
            name        = 'min_misc_name',
            description = 'min_misc_desc',
            renderer    = 'number',
            default     = 200,
            argument    = { integer = true, min = 0, max = 10000 },
        },
    }
}