return {
    "rag",
    "war",
    "founder's",
    "sathil mercenary",
    "cephalopod",
    "telvanni",
    "carapace",
    "racer",
    "redoran",
    "padded",
    "roughspun",
    "craftsman's",
    "smith's",
}