local I = require('openmw.interfaces')
local shared   = require('scripts.wdisarm_shared')
local DEFAULTS = shared.DEFAULTS

I.Settings.registerPage {
    key         = 'UnsteadyHands',
    l10n        = 'UnsteadyHands',
    name        = 'page_name',
    description = 'page_desc',
}

I.Settings.registerGroup {
    key              = 'SettingsDisarm',
    page             = 'UnsteadyHands',
    l10n             = 'UnsteadyHands',
    name             = 'settings_groupName',
    permanentStorage = true,
    order            = 1,
    settings = {
        {
            key         = 'MOD_ENABLED',
            name        = 'mod_enabled_name',
            description = 'mod_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.MOD_ENABLED,
        },
        {
            key         = 'DISARM_NPCS',
            name        = 'disarm_npcs_name',
            description = 'disarm_npcs_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.DISARM_NPCS,
        },
        {
            key         = 'DISARM_CREATURES',
            name        = 'disarm_creatures_name',
            description = 'disarm_creatures_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.DISARM_CREATURES,
        },
        {
            key         = 'DISARM_PLAYER',
            name        = 'disarm_player_name',
            description = 'disarm_player_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.DISARM_PLAYER,
        },
        {
            key         = 'STRENGTH_AS_MULT',
            name        = 'strength_as_mult_name',
            description = 'strength_as_mult_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.STRENGTH_AS_MULT,
        },
        {
            key         = 'USE_PHYSICS',
            name        = 'enable_lua_physics_name',
            description = 'enable_lua_physics_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.USE_PHYSICS,
        },
        {
            key         = 'BASE_CHANCE',
            name        = 'base_chance_name',
            description = 'base_chance_desc',
            renderer    = 'number',
            default     = DEFAULTS.BASE_CHANCE,
            argument    = { min = 0.01, max = 0.10 },
        },
        {
            key         = 'STR_AGI_FACTOR',
            name        = 'str_agi_factor_name',
            description = 'str_agi_factor_desc',
            renderer    = 'number',
            default     = DEFAULTS.STR_AGI_FACTOR,
            argument    = { min = 0, max = 0.01 },
        },
        {
            key         = 'MAX_CHANCE',
            name        = 'max_chance_name',
            description = 'max_chance_desc',
            renderer    = 'number',
            default     = DEFAULTS.MAX_CHANCE,
            argument    = { min = 0.05, max = 0.15 },
        },
        {
            key         = 'PLAYER_CHANCE_MULT',
            name        = 'player_chance_mult_name',
            description = 'player_chance_mult_desc',
            renderer    = 'number',
            default     = DEFAULTS.PLAYER_CHANCE_MULT,
            argument    = { min = 0.1, max = 3.0 },
        },
        {
            key         = 'CREATURE_COMBAT_MULT',
            name        = 'creature_combat_mult_name',
            description = 'creature_combat_mult_desc',
            renderer    = 'number',
            default     = DEFAULTS.CREATURE_COMBAT_MULT,
            argument    = { min = 0.1, max = 1.0 },
        },
        {
            key         = 'CHARGE_THRESHOLD',
            name        = 'charge_threshold_name',
            description = 'charge_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.CHARGE_THRESHOLD,
            argument    = { min = 0.5, max = 1.0 },
        },
        {
            key         = 'PICKUP_RADIUS',
            name        = 'pickup_radius_name',
            description = 'pickup_radius_desc',
            renderer    = 'number',
            default     = DEFAULTS.PICKUP_RADIUS,
            argument    = { integer = true, min = 50, max = 1000 },
        },
        {
            key         = 'PICKUP_DELAY',
            name        = 'pickup_delay_name',
            description = 'pickup_delay_desc',
            renderer    = 'number',
            default     = DEFAULTS.PICKUP_DELAY,
            argument    = { min = 0.1, max = 10.0 },
        },
        {
            key         = 'WEIGHT_CHECK_ENABLED',
            name        = 'weight_check_enabled_name',
            description = 'weight_check_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.WEIGHT_CHECK_ENABLED,
        },
        {
            key         = 'WEIGHT_THRESHOLD',
            name        = 'weight_threshold_name',
            description = 'weight_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.WEIGHT_THRESHOLD,
            argument    = { integer = true, min = 0, max = 100 },
        },
        {
            key         = 'SHIELD_PROTECTS',
            name        = 'shield_protects_name',
            description = 'shield_protects_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.SHIELD_PROTECTS,
        },
        {
            key         = 'NPC_PICKUP_ENABLED',
            name        = 'npc_pickup_enabled_name',
            description = 'npc_pickup_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.NPC_PICKUP_ENABLED,
        },
        {
            key         = 'NPC_PICKUP_CHANCE',
            name        = 'npc_pickup_chance_name',
            description = 'npc_pickup_chance_desc',
            renderer    = 'number',
            default     = DEFAULTS.NPC_PICKUP_CHANCE,
            argument    = { min = 0.1, max = 1.0 },
        },
        {
            key         = 'DAMAGE_THRESHOLD',
            name        = 'damage_threshold_name',
            description = 'damage_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.DAMAGE_THRESHOLD,
            argument    = { integer = true, min = 1, max = 10 },
        },
        {
            key         = 'SKILL_THRESHOLD',
            name        = 'skill_threshold_name',
            description = 'skill_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.SKILL_THRESHOLD,
            argument    = { integer = true, min = 0, max = 20 },
        },
    }
}