local badEffects = {

        firedamage = 'firedamage',
        shockdamage = 'shockdamage',
        frostdamage = 'frostdamage',

        drainhealth = 'drainhealth',
        drainmagicka = 'drainmagicka',
        drainfatigue = 'drainfatigue',

        damagehealth = 'damagehealth',
        damagemagicka = 'damagemagicka',
        damagefatigue = 'damagefatigue',

        absorbhealth = 'absorbhealth',
        absorbmagicka = 'absorbmagicka',
        absorbfatigue = 'absorbfatigue',

        drainattribute = 'drainattribute',
        drainskill = 'drainskill',
        damageattribute = 'damageattribute',
        damageskill = 'damageskill',
        absorbattribute = 'absorbattribute',
        absorbskill = 'absorbskill',

        poison = 'poison',

        disintegrateweapon = 'disintegrateweapon',
        disintegratearmor = 'disintegratearmor',

        -- swiftswim = 'swiftswim',
        -- waterwalking = 'waterwalking',
        -- shield = 'shield',
        -- fireshield = 'fireshield',
        -- lightningshield = 'lightningshield',
        -- frostshield = 'frostshield',
        -- burden = 'burden',
        -- feather = 'feather',
        -- jump = 'jump',
        -- levitate = 'levitate',
        -- slowfall = 'slowfall',
        -- lock = 'lock',
        -- open = 'open',
        -- weaknesstofire = 'weaknesstofire',
        -- weaknesstofrost = 'weaknesstofrost',
        -- weaknesstoshock = 'weaknesstoshock',
        -- weaknesstomagicka = 'weaknesstomagicka',
        -- weaknesstocommondisease = 'weaknesstocommondisease',
        -- weaknesstoblightdisease = 'weaknesstoblightdisease',
        -- weaknesstocorprusdisease = 'weaknesstocorprusdisease',
        -- weaknesstopoison = 'weaknesstopoison',
        -- weaknesstonormalweapons = 'weaknesstonormalweapons',
        -- invisibility = 'invisibility',
        -- chameleon = 'chameleon',
        -- light = 'light',
        -- sanctuary = 'sanctuary',
        -- nighteye = 'nighteye',
        -- charm = 'charm',
        -- paralyze = 'paralyze',
        -- silence = 'silence',
        -- blind = 'blind',
        -- sound = 'sound',
        -- calmhumanoid = 'calmhumanoid',
        -- calmcreature = 'calmcreature',
        -- frenzyhumanoid = 'frenzyhumanoid',
        -- frenzycreature = 'frenzycreature',
        -- demoralizehumanoid = 'demoralizehumanoid',
        -- demoralizecreature = 'demoralizecreature',
        -- rallyhumanoid = 'rallyhumanoid',
        -- rallycreature = 'rallycreature',
        -- dispel = 'dispel',
        -- soultrap = 'soultrap',
        -- telekinesis = 'telekinesis',
        -- mark = 'mark',
        -- recall = 'recall',
        -- divineintervention = 'divineintervention',
        -- almsiviintervention = 'almsiviintervention',
        -- detectanimal = 'detectanimal',
        -- detectenchantment = 'detectenchantment',
        -- detectkey = 'detectkey',
        -- spellabsorption = 'spellabsorption',
        -- reflect = 'reflect',
        -- curecommondisease = 'curecommondisease',
        -- cureblightdisease = 'cureblightdisease',
        -- curecorprusdisease = 'curecorprusdisease',
        -- curepoison = 'curepoison',
        -- cureparalyzation = 'cureparalyzation',
        -- restoreattribute = 'restoreattribute',
        -- restorehealth = 'restorehealth',
        -- restoremagicka = 'restoremagicka',
        -- restorefatigue = 'restorefatigue',
        -- restoreskill = 'restoreskill',
        -- fortifyattribute = 'fortifyattribute',
        -- fortifyhealth = 'fortifyhealth',
        -- fortifymagicka = 'fortifymagicka',
        -- fortifyfatigue = 'fortifyfatigue',
        -- fortifyskill = 'fortifyskill',
        -- fortifymaximummagicka = 'fortifymaximummagicka',
        -- resistfire = 'resistfire',
        -- resistfrost = 'resistfrost',
        -- resistshock = 'resistshock',
        -- resistmagicka = 'resistmagicka',
        -- resistcommondisease = 'resistcommondisease',
        -- resistblightdisease = 'resistblightdisease',
        -- resistcorprusdisease = 'resistcorprusdisease',
        -- resistpoison = 'resistpoison',
        -- resistnormalweapons = 'resistnormalweapons',
        -- resistparalysis = 'resistparalysis',
        -- removecurse = 'removecurse',
        -- turnundead = 'turnundead',
        -- summonscamp = 'summonscamp',
        -- summonclannfear = 'summonclannfear',
        -- summondaedroth = 'summondaedroth',
        -- summondremora = 'summondremora',
        -- summonancestralghost = 'summonancestralghost',
        -- summonskeletalminion = 'summonskeletalminion',
        -- summonbonewalker = 'summonbonewalker',
        -- summongreaterbonewalker = 'summongreaterbonewalker',
        -- summonbonelord = 'summonbonelord',
        -- summonwingedtwilight = 'summonwingedtwilight',
        -- summonhunger = 'summonhunger',
        -- summongoldensaint = 'summongoldensaint',
        -- summonflameatronach = 'summonflameatronach',
        -- summonfrostatronach = 'summonfrostatronach',
        -- summonstormatronach = 'summonstormatronach',
        -- fortifyattack = 'fortifyattack',
        -- commandcreature = 'commandcreature',
        -- commandhumanoid = 'commandhumanoid',
        -- bounddagger = 'bounddagger',
        -- boundlongsword = 'boundlongsword',
        -- boundmace = 'boundmace',
        -- boundbattleaxe = 'boundbattleaxe',
        -- boundspear = 'boundspear',
        -- boundlongbow = 'boundlongbow',
        -- boundcuirass = 'boundcuirass',
        -- boundhelm = 'boundhelm',
        -- boundboots = 'boundboots',
        -- boundshield = 'boundshield',
        -- boundgloves = 'boundgloves',
        -- corprus = 'corprus',
        -- vampirism = 'vampirism',
        -- summoncenturionsphere = 'summoncenturionsphere',
        -- stuntedmagicka = 'stuntedmagicka',
        -- extraspell = 'extraspell', ???
        -- sundamage = 'sundamage', ???

}



return {
        badEffects = badEffects,
}
