return mwse.loadConfig("Character Sound Overhaul", {
	footstepSounds = true,
	PCfootstepVolume = 65,
	NPCfootstepVolume = 85,
	weatherSounds = true,
	PCweatherFootstepVolume = 60,
	NPCweatherFootstepVolume = 80,
	armorSounds = true,
	altArmor = false,
	PCarmorVolume = 65,
	NPCarmorVolume = 85,
	weaponSounds = true,
	PCweaponVolume = 65,
	NPCweaponVolume = 85,
	itemSounds = true,
	itemUseSounds = true,
	itemVolume = 75,
	journalSounds = true,
	lootSounds = true,
	thumps = false,
	miscVolume = 75,
	debugMode = false,
})
