local this = {}

this.vanillaTable = {
	-- Morrowind
	["addhiranirr"] = { entry = "A2_4_MiloGone", index = 1 },
	["athyn sarethi"] = { entry = "B5_RedoranHort", index = 50 },
	["Blatta Hateria"] = { entry = "A2_4_MiloGone", index = 50 },
	["caius cosades"] = { entry = "A2_4_MiloGone", index = 1 },
	["crassius curio"] = { entry = "B6_HlaaluHort", index = 50 },
	["danso indules"] = { entry = "B8_MeetVivec", index = 50 },
	["divayth fyr"] = { entry = "A2_4_MiloGone", index = 1 },
	["dram bero"] = { entry = "B6_HlaaluHort", index = 50 },
	["dutadalk"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["endryn llethan"] = { entry = "B8_MeetVivec", index = 50 },
	["falura llervu"] = { entry = "B3_ZainabBride", index = 50 },
	["garisa llethri"] = { entry = "B5_RedoranHort", index = 50 },
	["gilvas barelo"] = { entry = "A2_4_MiloGone", index = 50 },
	["han-ammu"] = { entry = "B4_KillWarLovers", index = 55 },
	["hasphat antabolis"] = { entry = "A2_4_MiloGone", index = 1 },
	["hassour zainsubani"] = { entry = "A2_4_MiloGone", index = 1 },
	["hlaren ramoran"] = { entry = "B5_RedoranHort", index = 50 },
	["huleeya"] = { entry = "A2_4_MiloGone", index = 1 },
	["kaushad"] = { entry = "B3_ZainabBride", index = 50 },
	["kausi"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["manirai"] = { entry = "B4_KillWarLovers", index = 55 },
	["mehra milo"] = { entry = "A2_4_MiloGone", index = 50 },
	["miner arobar"] = { entry = "B5_RedoranHort", index = 50 },
	["brara morvayn"] = { entry = "B5_RedoranHort", index = 50 },
	["nevena ules"] = { entry = "B6_HlaaluHort", index = 50 },
	["nibani maesa"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["raesa pullia"] = { entry = "A2_4_MiloGone", index = 1 },
	["savile imayn"] = { entry = "B3_ZainabBride", index = 50 },
	["sharn gra-muzgob"] = { entry = "A2_4_MiloGone", index = 1 },
	["sinnammu mirpal"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["sonummu zabamat"] = { entry = "B3_ZainabBride", index = 50 },
	["sul-matuul"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["tholer saryoni"] = { entry = "B8_MeetVivec", index = 50 },
	["uupse fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["varvur sarethi"] = { entry = "B5_RedoranHort", index = 50 },
	["velanda omani"] = { entry = "B6_HlaaluHort", index = 50 },
	["vivec_god"] = { entry = "B8_MeetVivec", index = 50 },
	["yagrum bagarn"] = { entry = "C3_DestroyDagoth", index = 50 },
	["yenammu"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["zabamund"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	-- Tribunal
	["almalexia"] = { entry = "TR_SothaSil", index = 100 },
	["apelles matius"] = { entry = "TR_DBAttack", index = 50 },
	["barenziah"] = { entry = "TR_SothaSil", index = 100 },
	["fedris hler"] = { entry = "TR_SothaSil", index = 100 },
	["gavas drin"] = { entry = "TR_MazedBand", index = 90 },
	["karrod"] = { entry = "TR_Blade", index = 35 },
	["King Hlaalu Helseth"] = { entry = "TR_SothaSil", index = 100 },
	["dwarven ghost_radac"] = { entry = "TR_Blade", index = 80 },
	["Tienius Delitian"] = { entry = "TR_SothaSil", index = 100 },
	-- Bloodmoon
	["falx carius"] = { entry = "BM_WildHunt", index = 100 },
	["tharsten heart-fang"] = { entry = "BM_WildHunt", index = 64 },
}
this.extendedTable = {
	-- Morrowind
	["ababael timsar-dadisun"] = { entry = "B3_ZainabBride", index = 50 },
	["addammus"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["addut-lamanu"] = { entry = "B4_KillWarLovers", index = 55 },
	["ahasour"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["alfe fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["ashibaal"] = { entry = "B3_ZainabBride", index = 50 },
	["ashur-dan"] = { entry = "B3_ZainabBride", index = 50 },
	["assamma-idan"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["assemmus"] = { entry = "B4_KillWarLovers", index = 55 },
	["beyte fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["bolvyn venim"] = { entry = "B5_RedoranHort", index = 50 },
	["delte fyr"] = { entry = "A2_3_CorprusCure", index = 50 },
	["hainab"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["kammu"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["kummu"] = { entry = "B4_KillWarLovers", index = 55 },
	["kurapli"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["lanabi"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["mabarrabael"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["maeli"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["mamaea"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["massarapal"] = { entry = "B4_KillWarLovers", index = 55 },
	["mausur"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["minassour"] = { entry = "B3_ZainabBride", index = 50 },
	["ninirrasour"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["nummu"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["patababi"] = { entry = "B3_ZainabBride", index = 50 },
	["sakiran"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["sakulerib"] = { entry = "B3_ZainabBride", index = 50 },
	["chargen captain"] = { entry = "A1_1_FindSpymaster", index = 1 },
	["sen"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["senipu"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shabinbael"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shallath-piremus"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shara"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["shimsun"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["tussi"] = { entry = "B3_ZainabBride", index = 50 },
	["tussurradad"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["ulabael"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["ulibabi"] = { entry = "B4_KillWarLovers", index = 55 },
	["urshamusa rapli"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["vistha_kai"] = { entry = "A2_3_CorprusCure", index = 50 },
	["yantus"] = { entry = "B4_KillWarLovers", index = 55 },
	["yen"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["zaba"] = { entry = "B3_ZainabBride", index = 50 },
	["zallit"] = { entry = "B2_AhemmusaSafe", index = 50 },
	["zanummu"] = { entry = "B1_UnifyUrshilaku", index = 50 },
	["zebba"] = { entry = "B4_KillWarLovers", index = 55 },
}
this.guildTable = {
	-- House Hlaalu
	["nileno dorvayn"] = { entry = "HH_IndEsp4", index = 100 },
	["edryno arethi"] = { entry = "HH_GuardMerchant", index = 100 },
	["crassius curio"] = { entry = "HH_DestroyTelUvirith", index = 100 },
	["odral helvi"] = { entry = "HH_EbonyDelivery", index = 100 },
	["ilmeni dren"] = { entry = "HH_TwinLamps3", index = 100 },
	["Vedam Dren"] = { entry = "HH_WinCamonna", index = 100 },
	-- House Redoran
	["neminda"] = { entry = "HR_GuardSarethi", index = 100 },
	["theldyn virith"] = { entry = "HR_CultElimination", index = 100 },
	["athyn sarethi"] = { entry = "HR_Archmaster", index = 100 },
	["lloros sarano"] = { entry = "HR_LostBanner", index = 100 },
	["faral retheran"] = { entry = "HR_AttackRethan", index = 100 },
	["tuveso beleth"] = { entry = "HR_BillCollect", index = 100 },
	["brara morvayn"] = { entry = "HR_MorvaynManor", index = 100 },
	["hlaren ramoran"] = { entry = "HR_OldFlame", index = 100 },
	["garisa llethri"] = { entry = "HR_CalderaDisrupt", index = 100 },
	["miner arobar"] = { entry = "HR_ArobarKidnap", index = 100 },
	-- House Telvanni
	["raven omayn"] = { entry = "HT_BlackJinx", index = 100 },
	["arara uvulas"] = { entry = "HT_SilverDawn", index = 100 },
	["felisa ulessen"] = { entry = "HT_SlaveRebellion", index = 100 },
	["baladas demnevanni"] = { entry = "HT_DahrkMezalf", index = 100 },
	["mallam ryon"] = { entry = "HT_NchuleftKey", index = 100 },
	["galos mathendis"] = { entry = "HT_DaedraSkin", index = 100 },
	["therana"] = { entry = "HT_AurielBow", index = 100 },
	["dratha"] = { entry = "HT_FleshAmulet", index = 100 },
	["neloth"] = { entry = "HT_DrakePride", index = 100 },
	["edd theman"] = { entry = "HT_EddieAmulet", index = 100 },
	["aryon"] = { entry = "HT_Archmagister", index = 100 },
	-- Fighters Guild
	["eydis fire-eye"] = { entry = "FG_HungerLoose", index = 100 },
	["lorbumol gro-aglakh"] = { entry = "FG_SilenceMagistrate", index = 100 },
	["hrundi"] = { entry = "FG_FindPudai", index = 100 },
	["persius mercius"] = { entry = "FG_KillHardHeart", index = 100 },
	["sjoring hard-heart"] = { entry = "FG_BigBosses", index = 100 },
	-- Mages Guild
	["ajira"] = { entry = "MG_WarlocksRing", index = 100 },
	["ranis athrys"] = { entry = "MG_SpyCatch", index = 100 },
	["edwinna elbert"] = { entry = "MG_Guildmaster", index = 100 },
	["skinkintreesshade"] = { entry = "MG_Guildmaster", index = 100 },
	["trebonius artorius"] = { entry = "MG_Guildmaster", index = 100 },
	["sharn gra-muzgob"] = { entry = "MG_Sharn_Necro", index = 10 },
	-- Thieves Guild
	["habasi"] = { entry = "TG_BalmoraDefenses", index = 100 },
	["aengoth"] = { entry = "TG_DartsJudgement", index = 100 },
	["big helende"] = { entry = "TG_EbonyStaff", index = 100 },
	["stacey"] = { entry = "TG_KillHardHeart", index = 100 },
	-- Tribunal Temple
	["tuls valen"] = { entry = "TT_Hassour", index = 100 },
	["endryn llethan"] = { entry = "TT_DagonFel", index = 100 },
	["tharer rotheloth"] = { entry = "TT_GalomDeus", index = 100 },
	["uvoo llaren"] = { entry = "TT_LlothisCrosier", index = 100 },
	["tholer saryoni"] = { entry = "TT_Assarnibibi", index = 110 },
	-- Morag Tong
	["eno hlaalu"] = { entry = "MT_Grandmaster", index = 100 },
	["ethasi rilvayn"] = { entry = "MT_Grandmaster", index = 100 },
	["Goren Andarys"] = { entry = "MT_Grandmaster", index = 100 },
	["dunsalipal dun-ahhe"] = { entry = "MT_Grandmaster", index = 100 },
	-- Imperial Cult
	["Synnolian Tunifus"] = { entry = "IC7_netch", index = 50 },
	["Iulus Truptor"] = { entry = "IC14_Ponius", index = 48 },
	["Kaye"] = { entry = "IC19_Restless_Spirit", index = 50 },
	["Lalatia Varian"] = { entry = "IC29_Crusher", index = 50 },
	-- Imperial Legion
	["general darius"] = { entry = "IL_TalosTreason", index = 100 },
	["imsin the dreamer"] = { entry = "IL_MaidenToken", index = 100 },
	["radd hard-heart"] = { entry = "IL_Necromancer", index = 100 },
	["Frald the White"] = { entry = "IL_ProtectEntius", index = 100 },
	["Varus Vatinius"] = { entry = "IL_Grandmaster", index = 100 },
	-- Clan Aundae
	["dhaunayne aundae"] = { entry = "VA_VampHunter", index = 100 },
	-- Clan Berne
	["raxle berne"] = { entry = "VA_VampCountess", index = 60 },
	-- Clan Quarra
	["volrina quarra"] = { entry = "VA_VampAmulet", index = 40 },
}
this.sideTable = {
	-- Vampire Misc Quests
	["fathasa llethri"] = { entry = "VA_VampRich", index = 80 },
	["marara"] = { entry = "VA_VampMarara", index = 40 },
	["mastrius"] = { entry = "VA_VampCurse", index = 100 },
	["sirilonwe"] = { entry = "VA_VampDust", index = 100 },
	["raven omayn"] = { entry = "VA_VampBlood2", index = 100 },
	-- Bal Molagmer
	["stacey"] = { entry = "TG_SS_ChurchPolice", index = 100 },
	-- Misc Quests
	["urshamusa rapli"] = { entry = "MS_WhiteGuar", index = 80 },
	["kurapli"] = { entry = "A2_1_Kurapli_Zallay", index = 50 },
	["teris raledran"] = { entry = "MV_RichTrader", index = 100 },
	["paur maston"] = { entry = "MV_TraderMissed", index = 100 },
	["nels llendo"] = { entry = "MV_3_Charming", index = 90 },
	["tinos drothan"] = { entry = "MV_AngryTrader", index = 100 },
	["maurrie aurmine"] = { entry = "MV_VictimRomance", index = 100 },
	["edras oril"] = { entry = "MV_StrayedPilgrim", index = 100 },
	["thoronor"] = { entry = "MV_StrayedPilgrim", index = 100 },
	["nevrasa dralor"] = { entry = "MV_WanderingPilgrim", index = 100 },
	["tul"] = { entry = "MV_FakeSlave", index = 100 },
	["falanu indaren"] = { entry = "MV_MissingCompanion", index = 60 },
	["drerel indaren"] = { entry = "MV_MissingCompanion", index = 60 },
	["fonus rathryon"] = { entry = "MV_PoorPilgrim", index = 100 },
	["viatrix petilia"] = { entry = "MV_RichPilgrim", index = 100 },
	["Satyana"] = { entry = "MS_ArenimTomb", index = 100 },
	["athanden girith"] = { entry = "MV_OutcastAshlanders", index = 110 },
	["botrir"] = { entry = "MV_RecoverWidowmaker", index = 70 },
	["marsus tullius"] = { entry = "MV_InnocentAshlanders", index = 110 },
	["reeh_jah"] = { entry = "MV_RunawaySlave", index = 36 },
	["ashumanu eraishah"] = { entry = "MS_Umbra", index = 50 },
	["aeta wave-breaker"] = { entry = "MV_BanditVictim", index = 100 },
	["bugrol gro-bagul"] = { entry = "MV_Bugrol", index = 100 },
	["sason"] = { entry = "MV_CultistVictim", index = 100 },
	["malexa"] = { entry = "MV_CultistVictim", index = 100 },
	["pemenie"] = { entry = "MV_TraderAbandoned", index = 100 },
	["hlormar wine-sot"] = { entry = "MV_AbusedHealer", index = 80 },
	["synette jeline"] = { entry = "MV_LostRing", index = 30 },
	["din"] = { entry = "MV_MonsterDisease", index = 60 },
	["hisin deep-raed"] = { entry = "MV_ParalyzedBarbarian", index = 100 },
	["Ingwold"] = { entry = "MS_HatandSkirt", index = 50 },
	["rasha"] = { entry = "MV_TraderLate", index = 40 },
	["lucan ostorius"] = { entry = "MV_ThiefTrader", index = 30 },
	["hassour zainsubani"] = { entry = "MS_Hannat", index = 70 },
	["bevene releth"] = { entry = "Town_Ald_Bevene", index = 3 },
	["bivale teneran"] = { entry = "Town_Ald_Bivale", index = 3 },
	["daynes redothril"] = { entry = "Town_Ald_Daynes", index = 3 },
	["llether vari"] = { entry = "Town_Ald_Llethri", index = 3 },
	["tiras sadus"] = { entry = "Town_Ald_Tiras", index = 3 },
	["gindrala hleran"] = { entry = "A1_SleeperDreamer02", index = 50 },
	["larrius varro"] = { entry = "town_balmora", index = 30 },
	["Relam Arinith"] = { entry = "MV_SlaveMule", index = 108 },
	["angaredhel"] = { entry = "town_Sadrith", index = 50 },
	["alusaron"] = { entry = "EB_Deed", index = 40 },
	["elam andas"] = { entry = "town_Vivec", index = 50 },
	["aurane frernis"] = { entry = "MS_Gold_kanet_flower", index = 100 },
	["jobasha"] = { entry = "MS_JobashaAbolitionist", index = 100 },
	["cassius olcinius"] = { entry = "EB_Invisible", index = 120 },
	["balen andrano"] = { entry = "EB_Bone", index = 60 },
	["tarer braryn"] = { entry = "MS_Apologies", index = 100 },
	["miun_gei"] = { entry = "EB_Actor", index = 80 },
	["moroni uvelas"] = { entry = "EB_DeadMen", index = 40 },
	["audenian valius"] = { entry = "EB_Pest", index = 40 },
	["gadayn andarys"] = { entry = "EB_Unrequited", index = 100 },
	["alarvyne indalas"] = { entry = "EB_Shipment", index = 30 },
	["mevure hlen"] = { entry = "EB_TradeSpy", index = 40 },
	["Llaalam Dredil"] = { entry = "EB_Express", index = 50 },
	["Bolrin"] = { entry = "EB_Clients", index = 40 },
	["wulf"] = { entry = "IC30_Imperial_veteran", index = 10 },
	["ahnassi"] = { entry = "Romance_Ahnassi", index = 95 },
	["hentus yansurnummu"] = { entry = "MS_HentusPants", index = 100 },
	["larrius varro"] = { entry = "MV_Bastard", index = 110 },
	["fargoth"] = { entry = "MS_FargothRing", index = 100 },
	["hrisskar flat-foot"] = { entry = "MS_Lookout", index = 30 },
	["vodunius nuccius"] = { entry = "MS_Nuccius", index = 100 },
	["chargen class"] = { entry = "MV_DeadTaxman", index = 100 },
	["daric bielle"] = { entry = "MV_BountyHunter", index = 120 },
	["mollimo of cloudrest"] = { entry = "MS_Trerayna_bounty", index = 50 },
	["turedus talanian"] = { entry = "town_Tel_Vos", index = 35 },
	-- Tribunal
	["thrud"] = { entry = "MS_BarbarianBook", index = 100 },
	["hession"] = { entry = "MS_Bouncer", index = 110 },
	["detritus caria"] = { entry = "MS_ClutterCollector", index = 50 },
	["Geon Auline"] = { entry = "MS_EstateSale", index = 60 },
	["ignatius_flaccus"] = { entry = "MS_BattleBots1", index = 60 },
	["deldrise andoren"] = { entry = "MS_Adulterer", index = 150 },
	["venasa sarano"] = { entry = "MS_BattleBots2", index = 20 },
	["ilnori faustus"] = { entry = "MS_JobHunt", index = 30 },
	["Torasa Aram"] = { entry = "MS_Museum", index = 10 },
	["Dovor Oren"] = { entry = "MS_Warlords", index = 120 },
	["high_pockets"] = { entry = "MS_HolyElf", index = 100 },
	["Alvan Llarys"] = { entry = "MS_Thief", index = 90 },
	["Ten-Tongues_Weerhat"] = { entry = "MS_ScrollSales", index = 100 },
	["meryn othralas"] = { entry = "MS_Performers", index = 100 },
	["Narisa Adus"] = { entry = "MS_BlackDart", index = 100 },
	["Marena Gilnith"] = { entry = "MS_MatchMaker", index = 120 },
	["drathas reyas"] = { entry = "MS_Summoner", index = 30 },
	["mehra helas"] = { entry = "MS_CrimsonPlague", index = 170 },
	["Gaenor"] = { entry = "MS_Natural", index = 10 },
	-- Bloodmoon
	["Carnius Magius"] = { entry = "CO_11", index = 70 },
	["Falco Galenus"] = { entry = "CO_11", index = 60 },
	["severia gratius"] = { entry = "BM_MoonSugar", index = 100 },
	["jeleen"] = { entry = "BM_Missionary", index = 110 },
	["athellor"] = { entry = "BM_Falmer", index = 100 },
	["lassnr"] = { entry = "BM_Tymvaul", index = 100 },
	["svenja snow-song"] = { entry = "BM_MeadHall", index = 100 },
	["ulfgar the unending"] = { entry = "BM_BrodirGrove", index = 100 },
	["geilir the mumbling"] = { entry = "BM_SadSeer", index = 100 },
	["thormoor gray-wave"] = { entry = "BM_CursedCaptain", index = 100 },
	["thormoor_thirsk"] = { entry = "BM_CursedCaptain", index = 100 },
	["ingmar"] = { entry = "BM_Ingmar", index = 45 },
	["kjolver"] = { entry = "BM_WomanScorned", index = 100 },
	["kolfinna"] = { entry = "BM_Retribution", index = 100 },
	["louis beauchamp"] = { entry = "BM_Airship", index = 100 },
	-- Official Plugins
	["chargen captain"] = { entry = "ms_firemoth", index = 100 },
	["folms mirel"] = { entry = "MS_Master_Index", index = 50 },
}
this.questItemTable = {
	-- Morrowind
	["bk_a1_1_caiuspackage"] = { entry = "A1_1_FindSpymaster", index = 12 },
	["lugrub's axe"] = { entry = "IL_WidowLand", index = 70 },
	["dwarven war axe_redas"] = { entry = "HR_RedasTomb", index = 100 },
	["ebony staff caper"] = { entry = "TG_EbonyStaff", index = 100 },
	["Rusty_Dagger_UNIQUE"] = { entry = "DA_Mehrunes", index = 40 },
	["devil_tanto_tgamg"] = { entry = "TG_LootAldruhnMG", index = 100 },
	["daedric wakizashi_hhst"] = { entry = "HH_SunkenTreasure", index = 100 },
	["glass_dagger_enamor"] = { entry = "TG_SS_Enamor", index = 100 },
	["fork_horripilation_unique"] = { entry = "DA_Sheogorath", index = 70 },
	["dart_uniq_judgement"] = { entry = "TG_DartsJudgement", index = 100 },
	["bonemold_gah-julan_hhda"] = { entry = "HH_DisguisedArmor", index = 50 },
	["bonemold_founders_helm"] = { entry = "HR_FoundersHelm", index = 100 },
	["bonemold_tshield_hrlb"] = { entry = "HR_LostBanner", index = 100 },
	["amuletfleshmadewhole_uniq"] = { entry = "HT_FleshAmulet", index = 100 },
	["amulet_Agustas_unique"] = { entry = "MS_ArenimTomb", index = 110 },
	["expensive_amulet_delyna"] = { entry = "HR_MadMilk", index = 90 },
	["expensive_amulet_aeta"] = { entry = "MV_BanditVictim", index = 100 },
	["sarandas_amulet"] = { entry = "Town_Ald_Bevene", index = 3 },
	["exquisite_amulet_hlervu1"] = { entry = "TG_SS_Generosity1", index = 30 },
	["Julielle_Aumines_Amulet"] = { entry = "IC19_Restless_Spirit", index = 40 },
	["Linus_Iulus_Maran Amulet"] = { entry = "IC18_Silver_Staff", index = 50 },
	["Linus_Iulus_Stendarran_Belt"] = { entry = "IC18_Silver_Staff", index = 50 },
	["sarandas_belt"] = { entry = "Town_Ald_Tiras", index = 3 },
	["extravagant_rt_art_wild"] = { entry = "TT_AldDaedroth", index = 100 },
	["expensive_glove_left_ilmeni"] = { entry = "IL_MaidenToken", index = 70 },
	["extravagant_glove_left_maur"] = { entry = "MV_VictimRomance", index = 50 },
	["common_pants_02_hentus"] = { entry = "MS_HentusPants", index = 100 },
	["sarandas_pants_2"] = { entry = "Town_Ald_Bivale", index = 3 },
	["Adusamsi's_Ring"] = { entry = "IC27_Oracle", index = 50 },
	["extravagant_ring_aund_uni"] = { entry = "VA_VampChild", index = 80 },
	["ring_blackjinx_uniq"] = { entry = "HT_BlackJinx", index = 100 },
	["exquisite_ring_brallion"] = { entry = "TG_SS_GreedySlaver", index = 50 },
	["common_ring_danar"] = { entry = "EB_DeadMen", index = 60 },
	["sarandas_ring_2"] = { entry = "Town_Ald_Daynes", index = 3 },
	["ring_keley"] = { entry = "MS_FargothRing", index = 100 },
	["expensive_ring_01_BILL"] = { entry = "MV_LostRing", index = 30 },
	["expensive_ring_aeta"] = { entry = "MV_BanditVictim", index = 100 },
	["sarandas_ring_1"] = { entry = "Town_Ald_Daynes", index = 3 },
	["Expensive_Ring_01_HRDT"] = { entry = "HR_DagothTanis", index = 100 },
	["exquisite_ring_processus"] = { entry = "MV_DeadTaxman", index = 90 },
	["Extravagant_Robe_01_Red"] = { entry = "HR_RedasTomb", index = 100 },
	["robe of st roris"] = { entry = "HH_WinSaryoni", index = 70 },
	["exquisite_robe_drake's pride"] = { entry = "HT_DrakePride", index = 100 },
	["sarandas_shirt_2"] = { entry = "Town_Ald_Bivale", index = 3 },
	["exquisite_shirt_01_rasha"] = { entry = "MV_TraderLate", index = 40 },
	["sarandas_shoes_2"] = { entry = "Town_Ald_Llethri", index = 3 },
	["therana's skirt"] = { entry = "HT_TheranaClothes", index = 100 },
	["misc_Beluelle_silver_bowl"] = { entry = "MS_Piernette", index = 90 },
	["misc_lw_bowl_chapel"] = { entry = "IC15_Missing_Limeware", index = 50 },
	["misc_dwrv_artifact_ils"] = { entry = "IL_Smuggler", index = 100 },
	["misc_dwarfbone_unique"] = { entry = "EB_Bone", index = 30 },
	["misc_dwrv_ark_cube00"] = { entry = "A1_2_AntabolisInformant", index = 10 },
	["Misc_fakesoulgem"] = { entry = "MG_Sabotage", index = 100 },
	["ingred_guar_hide_girith"] = { entry = "MV_OutcastAshlanders", index = 100 },
	["misc_uniq_egg_of_gold"] = { entry = "FG_FindPudai", index = 100 },
	["misc_goblet_dagoth"] = { entry = "A2_6_Incarnate", index = 15 },
	["ingred_guar_hide_marsus"] = { entry = "MV_InnocentAshlanders", index = 100 },
	["misc_6th_ash_hrmm"] = { entry = "HR_MorvaynManor", index = 50 },
	["misc_de_goblet_01_redas"] = { entry = "HR_RedasTomb", index = 100 },
	["misc_Skull_Llevule"] = { entry = "A1_4_MuzgobInformant", index = 15 },
	["misc_6th_ash_hrcs"] = { entry = "HR_ClearSarethi", index = 90 },
	["misc_wraithguard_no_equip"] = { entry = "CX_BackPath", index = 50 },
	["p_cure_common_unique"] = { entry = "MS_Apologies", index = 100 },
	["p_lovepotion_unique"] = { entry = "EB_Unrequited", index = 80 },
	["p_quarrablood_unique"] = { entry = "VA_VampBlood", index = 40 }, { entry = "VA_VampBlood2", index = 100 },
	["p_sinyaramen_unique"] = { entry = "VA_VampChild", index = 70 },
	["ingred_raw_glass_tinos"] = { entry = "MV_AngryTrader", index = 100 },
	["ingred_gold_kanet_unique"] = { entry = "MS_Gold_kanet_flower", index = 100 },
	["ingred_treated_bittergreen_uniq"] = { entry = "DA_Mephala", index = 57 },
	["bk_aedra_tarer_unique"] = { entry = "MS_Apologies", index = 10 },
	["glory_unique"] = { entry = "DA_Boethiah", index = 60 },
	["bk_sharnslegionsofthedead"] = { entry = "MG_Sharn_Necro", index = 10 },
	["bk_alen_note"] = { entry = "TR08_Hlaalu", index = 60 },
	["bk_irano_note"] = { entry = "TR07_Guard", index = 100 },
	["bk_Airship_Captains_Journal"] = { entry = "BM_Airship", index = 70 },
	["bk_snowprince"] = { entry = "BM_Falmer", index = 100 },
	["bk_sovngarde"] = { entry = "BM_BrodirGrove", index = 40 },
	["bk_ajira1"] = { entry = "MG_StolenReport", index = 100 },
	["bk_ajira2"] = { entry = "MG_StolenReport", index = 100 },
	["bk_landdeed_hhrd"] = { entry = "HH_ReplaceDocs", index = 100 },
	["bk_auranefrernis1"] = { entry = "HH_IndEsp1", index = 100 },
	["bk_auranefrernis2"] = { entry = "HH_IndEsp1", index = 100 },
	["bk_auranefrernis3"] = { entry = "HH_IndEsp1", index = 100 },
	["bk_calderaminingcontract"] = { entry = "HH_CaptureSpy", index = 100 },
	["bk_clientlist"] = { entry = "EB_Clients", index = 40 },
	["bk_indreledeed"] = { entry = "TG_SS_Generosity2", index = 50 },
	["bk_dispelrecipe_tgca"] = { entry = "TG_CookbookAlchemy", index = 50 },
	["bk_drenblackmail"] = { entry = "B6_HlaaluHort", index = 50 },
	["bk_uleni's_papers"] = { entry = "town_Sadrith", index = 50 },
	["bk_itermerelsnotes"] = { entry = "MG_EscortScholar2", index = 100 },
	["bk_kagrenac'sjournal_excl"] = { entry = "CX_BackPath", index = 25 },
	["bk_kagrenac'splans_excl"] = { entry = "CX_BackPath", index = 25 },
	["bk_letterfromjzhirr"] = { entry = "EB_Express", index = 30 },
	["bk_letterfromllaalam"] = { entry = "EB_Express", index = 50 },
	["bk_letterfromllaalam2"] = { entry = "EB_TradeSpy", index = 40 },
	["bk_ocato_recommendation"] = { entry = "MG_Guildmaster", index = 50 },
	["bk_a1_2_introtocadiusus"] = { entry = "MG_Excavation", index = 20 },
	["bk_messagefrommasteraryon"] = { entry = "HT_FyrMessage", index = 50 },
	["bk_nemindasorders"] = { entry = "HH_DisguisedArmor", index = 100 },
	["bk_a1_4_sharnsnotes"] = { entry = "A1_4_MuzgobInformant", index = 25 },
	["bk_notefrombashuk"] = { entry = "MV_Bugrol", index = 40 },
	["bk_notefrombugrol"] = { entry = "MV_Bugrol", index = 30 },
	["bk_notefromernil"] = { entry = "MV_SkoomaCorpse", index = 20 },
	["bk_notefromnelos"] = { entry = "MV_VictimRomance", index = 100 },
	["bk_talostreason"] = { entry = "IL_TalosTreason", index = 50 },
	["bk_notetoamaya"] = { entry = "A2_4_MiloGone", index = 10 },
	["bk_enamor"] = { entry = "TG_SS_Enamor", index = 100 },
	["bk_a1_7_huleeyainformant"] = { entry = "A1_V_VivecInformants", index = 50 },
	["bk_landdeedfake_hhrd"] = { entry = "HH_ReplaceDocs", index = 50 },
	["bk_orderesforbivaleteneran"] = { entry = "HH_IndEsp3", index = 50 },
	["bk_progressoftruth"] = { entry = "A1_V_VivecInformants", index = 50 },
	["chargen statssheet"] = { entry = "A1_1_FindSpymaster", index = 1 },
	["bk_responsefromdivaythfyr"] = { entry = "HT_FyrMessage", index = 100 },
	["bk_stronghold_ld_hlaalu"] = { entry = "HH_Stronghold", index = 50 },
	["bk_calderarecordbook2"] = { entry = "HR_CalderaCorrupt", index = 100 },
	["bk_seniliasreport"] = { entry = "MG_Excavation", index = 100 },
	["bk_shishireport"] = { entry = "HR_ShishiReport", index = 100 },
	["bk_sottildescodebook"] = { entry = "FG_Sottilde", index = 100 },
	["bk_tiramgadarscredentials"] = { entry = "MG_SpyCatch", index = 100 },
	["bk_treasury orders"] = { entry = "HH_BankFraud", index = 50 },
	["bk_treasury report"] = { entry = "HH_BankCourier", index = 50 },
	["bk_contract_ralen"] = { entry = "EB_Deed", index = 40 },
	["bk_widowdeed"] = { entry = "IL_WidowLand", index = 100 },
	["bk_ynglingledger"] = { entry = "TG_SS_Yngling", index = 100 },
	["bk_a1_11_zainsubaninotes"] = { entry = "A2_1_MeetSulMatuul", index = 1 },
	-- Tribunal
	["ebony war axe_elanande"] = { entry = "MS_Warlords", index = 70 },
	["dwarven mace_salandas"] = { entry = "MS_Warlords", index = 120 },
	["silver dagger_droth_unique_a"] = { entry = "MS_EstateSale", index = 60 },
	["silver dagger_droth_unique"] = { entry = "MS_EstateSale", index = 60 },
	["ebony shortsword_soscean"] = { entry = "MS_Warlords", index = 40 },
	["silver spear_uvenim"] = { entry = "MS_Warlords", index = 100 },
	["ebony_cuirass_soscean"] = { entry = "MS_Warlords", index = 40 },
	["silver_helm_uvenim"] = { entry = "MS_Warlords", index = 100 },
	["amulet_salandas"] = { entry = "MS_Warlords", index = 120 },
	["extravagant_robe_02_elanande"] = { entry = "MS_Warlords", index = 70 },
	["bladepiece_02"] = { entry = "TR_Blade", index = 65 },
	["bladepiece_03"] = { entry = "TR_Blade", index = 65 },
	["dwemer_shield_battle_unique"] = { entry = "TR_Blade", index = 65 },
	["misc_dwrv_weather"] = { entry = "TR_ShowPower", index = 90 },
	["misc_dwrv_weather2"] = { entry = "TR_ShowPower", index = 90 },
	["bk_playscript"] = { entry = "MS_Performers", index = 30 },
	["sc_chridittepanacea"] = { entry = "MS_CrimsonPlague", index = 110 },
	["pyroil_tar_unique"] = { entry = "TR_Blade", index = 80 },
	-- Bloodmoon
	["fur_colovian_helm_white"] = { entry = "BM_MoonSugar", index = 100 },
	["amulet of infectious charm"] = { entry = "BM_Airship", index = 80 },
	["expensive_ring_erna"] = { entry = "BM_WomanScorned", index = 100 },
	["BM_bearheart_UNIQUE"] = { entry = "BM_BearHunt1", index = 100 },
	["misc_skull_oddfrid"] = { entry = "BM_SadSeer", index = 40 },
	["misc_skull_Skaal"] = { entry = "BM_CariusGone", index = 100 },
	["BM_Seeds_UNIQUE"] = { entry = "BM_Trees", index = 40 },
	["Misc_BM_ClawFang_UNIQUE"] = { entry = "BM_Ceremony1", index = 100 },
	["BM_waterlife_UNIQUE1"] = { entry = "BM_Water", index = 100 },
	["bk_BMtrial_unique"] = { entry = "BM_Trial", index = 55 },
	["bk_colony_Toralf"] = { entry = "CO_13", index = 40 },
	["ingred_emerald_pinetear"] = { entry = "BM_Retribution", index = 100 },
	["ingred_innocent_heart"] = { entry = "BM_WolfGiver", index = 100 },
	["ingred_wolf_heart"] = { entry = "BM_WolfGiver", index = 105 },
}
return this