local types = require("scripts.quest_guider_lite.types")
local commonData = require("scripts.quest_guider_lite.common")
local core = require('openmw.core')
local l10n = core.l10n(commonData.l10nKey)

return {
    [types.requirementType.CustomActor] = { str = l10n("types.requirementType.CustomActor") or "", priority = -999 },
    [types.requirementType.CustomDialogue] = { str = l10n("types.requirementType.CustomDialogue") or "", priority = -1000 },
    [types.requirementType.Item] = { str = l10n("types.requirementType.Item") or "", },
    [types.requirementType.CustomDisposition] = { str = l10n("types.requirementType.CustomDisposition") or "", priority = -1001 },
    [types.requirementType.PreviousDialogChoice] = { str = l10n("types.requirementType.PreviousDialogChoice") or "", priority = -1001 },
    [types.requirementType.CustomPCFaction] = { str = l10n("types.requirementType.CustomPCFaction") or "", },
    [types.requirementType.Dead] = { str = l10n("types.requirementType.Dead") or "", },
    [types.requirementType.CustomActorCell] = { str = l10n("types.requirementType.CustomActorCell") or "", priority = -1000 },
    [types.requirementType.NotActorID] = { str = l10n("types.requirementType.NotActorID") or "", priority = -1001 },
    [types.requirementType.CustomPCRank] = { str = l10n("types.requirementType.CustomPCRank") or "", },
    [types.requirementType.CustomActorGender] = { str = l10n("types.requirementType.CustomActorGender") or "", priority = -1001 },
    [types.requirementType.PlayerLevel] = { str = l10n("types.requirementType.PlayerLevel") or "", },
    [types.requirementType.CustomActorFaction] = { str = l10n("types.requirementType.CustomActorFaction") or "", priority = -1001 },
    [types.requirementType.NotActorRace] = { str = l10n("types.requirementType.NotActorRace") or "", priority = -1001 },
    [types.requirementType.Journal] = { str = l10n("types.requirementType.Journal") or "", },
    [types.requirementType.CustomLocal] = { str = l10n("types.requirementType.CustomLocal") or "", },
    [types.requirementType.CustomCurrentAIPackage] = { str = l10n("types.requirementType.CustomCurrentAIPackage") or "", },
    [types.requirementType.CustomGlobal] = { str = l10n("types.requirementType.CustomGlobal") or "", },
    [types.requirementType.CustomDistance] = { str = l10n("types.requirementType.CustomDistance") or "", },
    [types.requirementType.CustomActorClass] = { str = l10n("types.requirementType.CustomActorClass") or "", priority = -1001 },
    [types.requirementType.NPCSameFactionAsPlayer] = { str = l10n("types.requirementType.NPCSameFactionAsPlayer") or "", },
    [types.requirementType.NPCTalkedToPlayer] = { str = l10n("types.requirementType.NPCTalkedToPlayer") or "", },
    [types.requirementType.CustomSkill] = { str = l10n("types.requirementType.CustomSkill") or "", },
    [types.requirementType.PlayerGender] = { str = l10n("types.requirementType.PlayerGender") or "", },
    [types.requirementType.CustomAIPackageDone] = { str = l10n("types.requirementType.CustomAIPackageDone") or "", },
    [types.requirementType.NPCSameGenderAsPlayer] = { str = l10n("types.requirementType.NPCSameGenderAsPlayer") or "", },
    [types.requirementType.CustomAttribute] = { str = l10n("types.requirementType.CustomAttribute") or "", },
    [types.requirementType.PlayerReputation] = { str = l10n("types.requirementType.PlayerReputation") or "", },
    [types.requirementType.RankRequirement] = { str = l10n("types.requirementType.RankRequirement") or "", },
    [types.requirementType.PlayerIsVampire] = { str = l10n("types.requirementType.PlayerIsVampire") or "", },
    [types.requirementType.NPCIsAlarmed] = { str = l10n("types.requirementType.NPCIsAlarmed") or "", },
    [types.requirementType.NPCAttacked] = { str = l10n("types.requirementType.NPCAttacked") or "", },
    [types.requirementType.PlayerIsDetected] = { str = l10n("types.requirementType.PlayerIsDetected") or "", },
    [types.requirementType.CustomPCSleep] = { str = l10n("types.requirementType.CustomPCSleep") or "", },
    [types.requirementType.PlayerBlightDisease] = { str = l10n("types.requirementType.PlayerBlightDisease") or "", },
    [types.requirementType.CustomDisabled] = { str = l10n("types.requirementType.CustomDisabled") or "", priority = -1001 },
    [types.requirementType.CustomOnPCAdd] = { str = l10n("types.requirementType.CustomOnPCAdd") or "", priority = -1001 },
    [types.requirementType.NPCReputation] = { str = l10n("types.requirementType.NPCReputation") or "", },
    [types.requirementType.PlayerClothingModifier] = { str = l10n("types.requirementType.PlayerClothingModifier") or "", },
    [types.requirementType.PlayerHealth] = { str = l10n("types.requirementType.PlayerHealth") or "", },
    [types.requirementType.CustomBlightDisease] = { str = l10n("types.requirementType.CustomBlightDisease") or "", priority = -1001},
    [types.requirementType.NPCSameRaceAsPlayer] = { str = l10n("types.requirementType.NPCSameRaceAsPlayer") or "", priority = -1001},
    [types.requirementType.CustomWeaponDrawn] = { str = l10n("types.requirementType.CustomWeaponDrawn") or ""},
    [types.requirementType.CustomNotLocal] = { str = l10n("types.requirementType.CustomNotLocal") or "", priority = -1001 },
    [types.requirementType.PlayerRankMinusNPCRank] = { str = l10n("types.requirementType.PlayerRankMinusNPCRank") or "", priority = -1001 },
    [types.requirementType.CustomScale] = { str = l10n("types.requirementType.CustomScale") or "", priority = -1001 },
    [types.requirementType.PlayerCorprus] = { str = l10n("types.requirementType.PlayerCorprus") or "", },
    [types.requirementType.CustomCellChanged] = { str = l10n("types.requirementType.CustomCellChanged") or "", priority = -1001 },
    [types.requirementType.PlayerExpelledFromNPCFaction] = { str = l10n("types.requirementType.PlayerExpelledFromNPCFaction") or "", priority = -1001 },
    [types.requirementType.NPCHello] = { str = l10n("types.requirementType.NPCHello") or "", priority = -1001 },
    [types.requirementType.NPCAlarm] = { str = l10n("types.requirementType.NPCAlarm") or "", priority = -1001 },
    [types.requirementType.NPCFlee] = { str = l10n("types.requirementType.NPCFlee") or "", priority = -1001 },
    [types.requirementType.CustomOnActivate] = { str = l10n("types.requirementType.CustomOnActivate") or "", priority = -1001 },
    [types.requirementType.CustomOnMurder] = { str = l10n("types.requirementType.CustomOnMurder") or "", priority = -1001 },
    [types.requirementType.CustomOnKnockout] = { str = l10n("types.requirementType.CustomOnKnockout") or "", priority = -1001 },
    [types.requirementType.NotActorFaction] = { str = l10n("types.requirementType.NotActorFaction") or "", priority = -1001 },
    [types.requirementType.CustomRace] = { str = l10n("types.requirementType.CustomRace") or "", priority = -1001 },
    [types.requirementType.CustomPos] = { str = l10n("types.requirementType.CustomPos") or "", priority = -1001 },
    [types.requirementType.CustomInterior] = { str = l10n("types.requirementType.CustomInterior") or "", priority = -1001 },
    [types.requirementType.CustomSpell] = { str = l10n("types.requirementType.CustomSpell") or "", priority = -1001 },
    [types.requirementType.CustomLocked] = { str = l10n("types.requirementType.CustomLocked") or "", priority = -1001 },
    [types.requirementType.CustomScriptRunning] = { str = l10n("types.requirementType.CustomScriptRunning") or "", },
    [types.requirementType.CustomGameHour] = { str = l10n("types.requirementType.CustomGameHour") or "", },
    [types.requirementType.CustomWeaponType] = { str = l10n("types.requirementType.CustomWeaponType") or "", priority = -1001 },
    [types.requirementType.PlayerCommonDisease] = { str = l10n("types.requirementType.PlayerCommonDisease") or "", },
    [types.requirementType.CustomHasSoulgem] = { str = l10n("types.requirementType.CustomHasSoulgem") or "", },
    [types.requirementType.CustomStandingPC] = { str = l10n("types.requirementType.CustomStandingPC") or "", },
    [types.requirementType.CustomEffect] = { str = l10n("types.requirementType.CustomEffect") or "", priority = -1001 },
    [types.requirementType.CustomLineOfSight] = { str = l10n("types.requirementType.CustomLineOfSight") or "", priority = -1001 },
    [types.requirementType.NPCLevel] = { str = l10n("types.requirementType.NPCLevel") or "", priority = -1001 },
    [types.requirementType.CustomOnDeath] = { str = l10n("types.requirementType.CustomOnDeath") or "", priority = -1001 },
    [types.requirementType.CustomOnPCHitMe] = { str = l10n("types.requirementType.CustomOnPCHitMe") or "", priority = -1001 },
    [types.requirementType.CustomTarget] = { str = l10n("types.requirementType.CustomTarget") or "", priority = -1001 },
    [types.requirementType.NotActorClass] = { str = l10n("types.requirementType.NotActorClass") or "", priority = -1001 },
    [types.requirementType.CustomCommonDisease] = { str = l10n("types.requirementType.CustomCommonDisease") or "", priority = -1001 },
    [types.requirementType.PlayerCrimeLevel] = { str = l10n("types.requirementType.PlayerCrimeLevel") or "", },
    [types.requirementType.CustomOnPCEquip] = { str = l10n("types.requirementType.CustomOnPCEquip") or "", },
    [types.requirementType.CustomPCCell] = { str = l10n("types.requirementType.CustomPCCell") or "", },
    [types.requirementType.CustomSayDone] = { str = l10n("types.requirementType.CustomSayDone") or "", priority = -1001 },
    [types.requirementType.NotActorCell] = { str = l10n("types.requirementType.NotActorCell") or "", },
    [types.requirementType.CustomHasItemEquipped] = { str = l10n("types.requirementType.CustomHasItemEquipped") or "", priority = -1001 },
    [types.requirementType.CustomHealth] = { str = l10n("types.requirementType.CustomHealth") or "", priority = -1001 },
    [types.requirementType.CustomSoundPlaying] = { str = l10n("types.requirementType.CustomSoundPlaying") or "", },
    [types.requirementType.CustomScript] = { str = l10n("types.requirementType.CustomScript") or "", priority = -2000 },
    ["SCR1"] = { str = l10n("SCR1") or "", priority = -2001 },
    [types.requirementType.CustomDay] = { str = l10n("types.requirementType.CustomDay") or "", },
    [types.requirementType.CustomMonth] = { str = l10n("types.requirementType.CustomMonth") or "", },
    [types.requirementType.CustomYear] = { str = l10n("types.requirementType.CustomYear") or "", },
    [types.requirementType.CustomMenuMode] = { str = l10n("types.requirementType.CustomMenuMode") or "", },
    [types.requirementType.CustomRandom] = { str = l10n("types.requirementType.CustomRandom") or "", },
    [types.requirementType.CustomAngle] = { str = l10n("types.requirementType.CustomAngle") or "", },
    [types.requirementType.CustomVampClan] = { str = l10n("types.requirementType.CustomVampClan") or "", },
    [types.requirementType.Weather] = { str = l10n("types.requirementType.Weather") or "", },
    [types.requirementType.CustomSpellReadied] = { str = l10n("types.requirementType.CustomSpellReadied") or "", },
    [types.requirementType.CustomPCWerewolf] = { str = l10n("types.requirementType.CustomPCWerewolf") or "", },
    [types.requirementType.PlayerWerewolfKills] = { str = l10n("types.requirementType.PlayerWerewolfKills") or "", },
    [types.requirementType.CustomWindSpeed] = { str = l10n("types.requirementType.CustomWindSpeed") or "", },
    [types.requirementType.CustomPCSneaking] = { str = l10n("types.requirementType.CustomPCSneaking") or "", },
    [types.requirementType.PlayerHealthPercent] = { str = l10n("types.requirementType.PlayerHealthPercent") or "", },
    [types.requirementType.NPCHealthPercent] = { str = l10n("types.requirementType.NPCHealthPercent") or "", },
    [types.requirementType.CustomHitOnMe] = { str = l10n("types.requirementType.CustomHitOnMe") or "", },
    [types.requirementType.CustomPCInJail] = { str = l10n("types.requirementType.CustomPCInJail") or "", },
    [types.requirementType.NPCIsWerewolf] = { str = l10n("types.requirementType.NPCIsWerewolf") or "", priority = -1001 },
    [types.requirementType.NPCFight] = { str = l10n("types.requirementType.NPCFight") or "", priority = -1001 },
    [types.requirementType.CustomForceSneak] = { str = l10n("types.requirementType.CustomForceSneak") or "", priority = -1001 },
    [types.requirementType.CustomParalysis] = { str = l10n("types.requirementType.CustomParalysis") or "", priority = -1001 },
    [types.requirementType.CustomInvisible] = { str = l10n("types.requirementType.CustomInvisible") or "", priority = -1001 },
    [types.requirementType.CustomChameleon] = { str = l10n("types.requirementType.CustomChameleon") or "", priority = -1001 },
    [types.requirementType.CustomPCRace] = { str = l10n("types.requirementType.CustomPCRace") or "" },
    [types.requirementType.CustomPCJumping] = { str = l10n("types.requirementType.CustomPCJumping") or "" },
    [types.requirementType.CustomStandingActor] = { str = l10n("types.requirementType.CustomStandingActor") or "" },
    ["DIAO"] = { str = l10n("DIAO") or "", priority = -1001 },
    ["DIAP"] = { str = l10n("DIAP") or "", priority = -1001 },
}