return {
    "wraith-kin",
    "divine brother",
    "blood",
    "minion",
    "demon bone",
    "stalker",
    "dark",
    "hunter",
    "raven",
    "lord",
    "phoenix",
    "scale",
    "blind crown",
    "chain maiden",
    "wraith",
    "doethi's blood",
    "deamon",
    "harvester's",
    "night",
    "magus",
    "of god thrall",
    "black",
    "white",
    "sorcerer’s",
    "sorceress’",
    "red",
    "devil",
    "war master's",
    "of loathing",
    "shame",
    "xangrie's",
    "master's",
}