local I = require('openmw.interfaces')

-- Settings page
I.Settings.registerGroup {
    key = 'Settings/Keytar/Options',
    page = 'Keytar',
    l10n = 'Keytar',
    name = 'ConfigCategoryOptions',
    permanentStorage = true,
    settings = {
        {
            key = 'silenceAmbientMusic',
            renderer = 'checkbox',
            name = 'ConfigAmbientMusic',
            description = 'ConfigAmbientMusicDesc',
            default = true,
        },
        {
            key = 'nearbyNpcsDance',
            renderer = 'checkbox',
            name = 'ConfigNearbyNpcsDance',
            description = 'ConfigNearbyNpcsDanceDesc',
            default = true,
        },
        {
            key = 'enableFollowerAI',
            renderer = 'checkbox',
            name = 'ConfigFollowerAI',
            description = 'ConfigFollowerAIDesc',
            default = true,
        },
        {
            key = 'immortalKeytarists',
            renderer = 'checkbox',
            name = 'ConfigKeytaristsImmortal',
            description = 'ConfigKeytaristsImmortalDesc',
            default = true,
        },
        {
            key = 'untargetableKeytarists',
            renderer = 'checkbox',
            name = 'ConfigKeytaristsUntargetable',
            description = 'ConfigKeytaristsUntargetableDesc',
            default = true,
        },
        {
            key = 'pacifistKeytarists',
            renderer = 'checkbox',
            name = 'ConfigKeytaristsPacifist',
            description = 'ConfigKeytaristsPacifistDesc',
            default = true,
        },
        {
            key = 'inspiringKeytarists',
            renderer = 'checkbox',
            name = 'ConfigKeytaristsInspiring',
            description = 'ConfigKeytaristsInspiringDesc',
            default = true,
        },
        {
            key = 'teleportingKeytarists',
            renderer = 'checkbox',
            name = 'ConfigKeytaristsTeleporting',
            description = 'ConfigKeytaristsTeleportingDesc',
            default = true,
        }
    },
}

I.Settings.registerGroup {
    key = 'Settings/Keytar/Technical',
    page = 'Keytar',
    l10n = 'Keytar',
    name = 'ConfigCategoryTechnical',
    description = 'ConfigCategoryTechnicalDesc',
    permanentStorage = true,
    settings = {
        {
            key = 'playerKeytarVolume',
            renderer = 'number',
            name = 'ConfigPlayerKeytarVolume',
            description = 'ConfigPlayerKeytarVolumeDesc',
            default = 1.0,
            min = 0.0,
            max = 50.0,
        },
        {
            key = 'npcKeytarVolume',
            renderer = 'number',
            name = 'ConfigNpcKeytarVolume',
            description = 'ConfigNpcKeytarVolumeDesc',
            default = 3.0,
            min = 0.0,
            max = 50.0,
        },
        {
            key = 'dagothKeytarVolume',
            renderer = 'number',
            name = 'ConfigDagothKeytarVolume',
            description = 'ConfigDagothKeytarVolumeDesc',
            default = 5.0,
            min = 0.0,
            max = 50.0,
        },
        {
            key = 'dagothReverbVolume',
            renderer = 'number',
            name = 'ConfigDagothReverbVolume',
            description = 'ConfigDagothReverbVolumeDesc',
            default = 1,
            min = 0.0,
            max = 50.0,
        },
        {
            key = 'validKeytaristRecheckInterval',
            renderer = 'number',
            name = 'ConfigValidKeytaristRecheckInterval',
            description = 'ConfigValidKeytaristRecheckIntervalDesc',
            default = 5,
            min = 0,
            max = 60,
        },
        {
            key = 'playerFreezeDistance',
            renderer = 'number',
            name = 'ConfigPlayerFreezeDistance',
            description = 'ConfigPlayerFreezeDistanceDesc',
            default = 200,
            min = 0,
            max = 1000,
        },
        {
            key = 'targetFreezeDistance',
            renderer = 'number',
            name = 'ConfigTargetFreezeDistance',
            description = 'ConfigTargetFreezeDistanceDesc',
            default = 300,
            min = 0,
            max = 1000,
        },
        {
            key = 'playerMoveDistance',
            renderer = 'number',
            name = 'ConfigPlayerMoveDistance',
            description = 'ConfigPlayerMoveDistanceDesc',
            default = 100,
            min = 0,
            max = 1000,
        },
        {
            key = 'teleportingKeytaristsDistance',
            renderer = 'number',
            name = 'ConfigKeytaristsTeleportingDistance',
            description = 'ConfigKeytaristsTeleportingDistanceDesc',
            default = 3000,
            min = 500,
            max = 10000,
        },
        {
            key = 'npcDanceDistance',
            renderer = 'number',
            name = 'ConfigNpcDanceDistance',
            description = 'ConfigNpcDanceDistanceDesc',
            default = 1500,
            min = 0,
            max = 10000,
        },
        {
            key = 'musicResetTime',
            renderer = 'number',
            name = 'ConfigMusicResetTime',
            description = 'ConfigMusicResetTimeDesc',
            default = 3,
            min = 0,
            max = 300,
        }
    },
}