return {
   -- almost every quest entry, exemption and so is taken from the Go Home! mod
   -- if you aren't satisfied with my mod but still want to have NPC schedules, go take a look at: https://modding-openmw.gitlab.io/go-home/
   -- maybe you'll like Go Home! more


    EXEMPT_IDS = {
        -- Morrowind.esm
        ["agronian guy"] = true,
        ["alvela saram"] = true,
        ["ano vando"] = true,
        ["forstaag the sweltering"] = true,
        ["sur surishpi"] = true,
        ["yan assinabi"] = true,
        -- TR
        ["tr_m3_fentus stedanne"] = true,
        -- BCOM
        ["tc_0"] = true,
        ["tc_stand_0"] = true,
        -- An Nwah's Guide
        ["momw_greeter"] = true,
        -- Mournhold
        ["eno romari"] = true,
    },

    -- doors exempt from auto-unlock
    LOCK_EXEMPT_DOORS = {
        -- ["door_id_here"] = true,
    },

    -- NPCs with ids that include these words are exempted
    EXEMPT_PATTERNS = {
        "guard",
        "ordinator",
        "archer",
        "dreamer_",
        "firemoth_",
        "slave",
        "armiger",
        "imperial templar",
        "sharpshooter",
        "watchman",
        "red_watch",
        -- "gn_", -- a lot of NPCs in BCOM Gnisis
        -- GrumblingVomit uses these e.g., in Repopulated Morrowind/Waters. These mods are already excluded by EXEMPT_MODS
        -- "gvrm_",
        -- "gv_",
        -- DetailDevil NPCs
        "detd_",
        -- Rise of House Telvanni NPCs
        "roht_",
    },

    EXEMPT_MODS = {
        ["blademeister_v1.5.esp"] = true,
        ["f&f_base.esm"] = true,
        ["f&f_bcom.esp"] = true,
        ["f&f_tr.esp"] = true,
        ["mca.esm"] = true,
        ["repopulatedbloodmoon.esp"] = true,
        ["repopulatedmainland.esp"] = true,
        ["repopulatedmorrowind.esm"] = true,
        ["repopulatedmorrowind.esp"] = true,
        ["repopulatedmorrowind_magerobes.esp"] = true,
        ["repopulatedmorrowind_immersivemournhold.esp"] = true,
        ["repopulatedmorrowind_oaab_data.esp"] = true,
        ["repopulatedskyrim.esp"] = true,
        ["repopulatedwaters.esp"] = true,
        ["repopulatedwaters_tr.esp"] = true,
        ["sload and slavers.esp"] = true,
        ["sloadic transport.esp"] = true,
        ["starfires npc additions ver-1.11.esp"] = true,
        ["starfires npc additions ver-1.13.esp"] = true,
        ["wandering_merchants.esp"] = true,
    },

    EXEMPT_CLASSES = {
        ["guard"] = true,
        ["slave"] = true,
    },


    -- NPCs with an attached MWScript are exempted by default. Scripts listed here are known-safe to manage.
    SCRIPT_WHITELIST = {
        -- Morrowind.esm
        ["ahemmusakill"]          = true,
        ["balynscript"]           = true,
        ["bill_tt_elvil_vidron"]  = true,
        ["brallionscript"]        = true,
        ["drenslaveowners"]       = true,
        ["drulenescript"]         = true,
        ["erabenimsunkill"]       = true,
        ["h11_beauchamp"]         = true,
        ["hidesfootscript"]       = true,
        ["highpocketsscript"]     = true,
        ["localstate"]            = true,
        ["nolore"]                = true,
        ["sleeperscript"]         = true,
        ["strongholdwives"]       = true,
        ["thrudscript"]           = true,
        ["urshilakukill"]         = true,
        ["velnyawalkscript"]      = true,
        ["voduniusscript"]        = true,
        ["warloverkill"]          = true,
        ["zainabkill"]            = true,
        -- Tribunal.esm
        ["drathasscript"]         = true,
        ["dravilscript"]          = true,
        ["gaenorscript"]          = true,
        ["merynscript"]           = true,
        ["rerlas"]                = true,
        -- TR_Mainland.esm
        ["t_scnpc_mw_map1"]           = true,
        ["t_scnpc_mw_map1nolore"]     = true,
        ["t_scnpc_mw_map2"]           = true,
        ["t_scnpc_mw_map2nolore"]     = true,
        ["t_scnpc_mw_map3"]           = true,
        ["t_scnpc_mw_map3nolore"]     = true,
        ["t_scnpc_mw_map4"]           = true,
        ["t_scnpc_mw_map4nolore"]     = true,
        ["tr_m3_il_merchant1script"]  = true,
        ["tr_m3_npc_oe_common"]       = true,
        ["tr_m3_npc_oe_poor"]         = true,
        ["tr_m3_npc_oe_rich"]         = true,
        ["tr_m3_oe_eecq1_scr"]        = true,
        -- Sky_Main.esm
        ["t_scnpc_sky_hold0"]          = true,
        ["t_scnpc_sky_hold0_nolore"]   = true,
        ["t_scnpc_sky_hold0_reachman"] = true,
        -- Cyr_Main.esm
        ["t_scnpc_cyr_anvil"]     = true,
        ["pc_m1_kellekaro_sc"]    = true,
    },
 
    BAD_WEATHER = {
        [4] = true,  -- thunder
        [5] = true,  -- ash
        [6] = true,  -- blight
        [7] = true,  -- snow (blizzard)
        -- [8] = true, -- snow (light) -- optional
        [9] = true,  -- sandstorm
    },

    TRAVEL_CLASSES = {
        ["caravaner"] = true,
        ["shipmaster"] = true,
        ["gondolier"] = true,
    },

    -- no animated npcs are allowed to move
    ALLOWED_ANIMS = {
        ["meshes/"]                          = true,
        ["meshes/base_anim.nif"]             = true,
        ["meshes/base_anim_female.nif"]      = true,
        ["meshes/base_animkna.nif"]          = true,
        ["meshes/epos_kha_upr_anim_f.nif"]  = true,
        ["meshes/epos_kha_upr_anim_m.nif"]  = true,
        ["meshes/pi_tsa_base_anim.nif"]      = true,
    },

    -- quest exceptions: NPC is skipped while quest stage is >= before and < after
    -- key = recordId (lowercase), value = { quest, before, after }
    QUEST_EXCEPTIONS = {
        -- Morrowind.esm
        ["aeta wave-breaker"]   = { quest = "MV_BanditVictim",     before = 10,  after = 110 },
        ["aryni orethi"]        = { quest = "HR_Stronghold",       before = 220, after = 231 },
        ["assimusa samsi"]      = { quest = "HR_Stronghold",       before = 0,   after = 250 },
        ["balyn omavel"]        = { quest = "DA_Mephala",          before = 20,  after = 60  },
        ["brallion"]            = { quest = "TG_SS_GreedySlaver",  before = 10,  after = 30  },
        ["braynas hlervu"]      = { quest = "TG_SS_Generosity1",   before = 1,   after = 100 },
        ["danso indules"]       = { quest = "B8_MeetVivec",        before = 1,   after = 5   },
        ["elvil vidron"]        = { quest = "TT_FalseIncarnate",   before = 10,  after = 60  },
        ["engar ice-mane"]      = { quest = "BM_Trial",            before = 10,  after = 100 },
        ["fargoth"]             = { quest = "MS_Lookout",          before = 20,  after = 40  },
        ["gee-pop varis"]       = { quest = "TR09_Journalist",     before = 1,   after = 70  },
        ["hides_his_foot"]      = { quest = "HH_TwinLamps3",      before = 50,  after = 70  },
        ["nedhelas"]            = { quest = "IC16_Haunting",       before = 0,   after = 15  },
        ["apelles matius"]      = { quest = "TR_DBAttack",         before = 30,  after = 50  },
        ["tenyeminwe"]          = { quest = "MG_EscortScholar1",   before = 10,  after = 80  },
        -- Sleepers Awake
        ["alvura othrenim"]     = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["assi serimilk"]       = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["daynasa telandas"]    = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["dralas gilu"]         = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["drarayne girith"]     = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["dravasa andrethi"]    = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["endris dilmyn"]       = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["eralane hledas"]      = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["llandras belaal"]     = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["neldris llervu"]      = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["nelmil hler"]         = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["rararyn radarys"]     = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["relur faryon"]        = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["vireveri darethran"]  = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        ["vivyne andrano"]      = { quest = "A1_SleepersAwake",    before = 1,   after = 50  },
        -- Tribunal.esm
        ["drathas reyas"]       = { quest = "MS_Summoner",         before = 1,   after = 10  },
        ["dravil indrano"]      = { quest = "MS_Performers",       before = 10,  after = 100 },
        ["gaenor"]              = { quest = "MS_Natural",          before = 10,  after = 40  },
        ["marena gilnith"]      = { quest = "MS_MatchMaker",      before = 10,  after = 120 },
        ["mehra helas"]         = { quest = "MS_CrimsonPlague",   before = 0,   after = 10  },
        ["meryn othralas"]      = { quest = "MS_Performers",       before = 10,  after = 100 },
        ["thrud"]               = { quest = "MS_BarbarianBook",    before = 10,  after = 110 },
        -- AFFresh
        ["af_terinde"]          = { quest = "AF_TraceTerinde",     before = 60,  after = 120 },
        -- BCoM Open Cantons
        ["nar gro-shagramph"]   = { quest = "FG_DebtOrc",         before = 10,  after = 50  },
        -- Drethos Ancestral Tomb
        ["slf_ho_antjurah_drethos"] = { quest = "slf_ho_drethosancestraltomb", before = 0, after = 90 },
        -- OAAB Brother Junipers Twin Lamps
        ["mollimo of cloudrest"] = { quest = "TL_Abebaal",        before = 20,  after = 100 },
        -- TR
        ["tr_m3_raleth"]        = { quest = "TR_m3_OE_DukeAffair", before = 30, after = 90  },
        -- PC
        ["pc_m1_kellekaro"]     = { quest = "PC_m1_Anv_CrabBuck", before = 0,   after = 100 },
    },

   -- NPCs won't go here
    BLACKLISTED_INTERIORS = {
       ["mournhold, temple courtyard"] = true,
       ["ebonheart, flàvianna: trader"] = true,
       ["ebonheart, argonian mission"] = true,
    },

    -- shop cells that NPCs should never visit
    EXEMPT_SHOP_CELLS = {
        ["balmora, alchemist's loft"] = true,
    },

    -- NPCs that should never go shopping
    EXEMPT_SHOP_IDS = {
        -- ["place_id_here"] = true,
    },

    -- per-NPC door overrides by recordId (lowercase) + cell name (lowercase)
    -- use when a specific NPC needs a different door than the rest of the cell
    -- e.g. rooftop NPC in a cell whose generic override points to the ground entrance
    NPC_DOOR_OVERRIDES = {
        ["hv_gn_belsdarodyr"] = {
             ["gnisis, madach tradehouse"] = { { x = -84311.1, y = 90890, z = 1956.41 } },
        },
        ["hv_gn_llarisasendras"] = {
             ["gnisis, temple"] = { { x = -86449.2, y = 93318.9, z = 2041.77 } },
        },
    },

    -- door position overrides: cell name (lowercase) -> array of {x, y, z}
    -- NPC walks to the nearest override pos (home/safe) or a random one (shop)
    -- used when Beautiful cities of Morrowind.ESP is NOT installed
    DOOR_OVERRIDES = {
        -- ["balmora, eight plates"] = { { x = 1234, y = 5678, z = 90 } },
    },
 
    -- same format, used when Beautiful cities of Morrowind.ESP IS installed
    DOOR_OVERRIDES_BCOM = {
       ["balmora, dorisa darvel: bookseller"] = { { x = -22762, y = -13325, z = 676 } },
       ["balmora, eight plates"] = { { x = -21661, y = -12069, z = 672 }, { x = -21661, y = -12069, z = 938 } },
       ["balmora, milie hastien: fine clothier"] = { { x = -25584.3, y = -9872, z = 1161 } },
       ["balmora, dralcea arethi's house"] = { { x = -16237, y = -14781.5, z = 329.493 } },
       ["balmora, south wall cornerclub"] = { { x = -16719, y = -15773, z = 324 } },
       ["gnisis, temple"] = { { x = -85009.7, y = 93516.5, z = 1451.37 } },
       ["gnisis, madach tradehouse"] = { { x = -84606.8, y = 91182.9, z = 1382.75 } },
       ["gnisis, barracks"] = { { x = -83313.6, y = 92285.7, z = 1350.38 } },
       ["suran, goldyn belaram: pawnbroker"] = { { x = 54590.5, y = -51499.5, z = 335.786 } },
       ["suran, tunila adram: bookseller"] = { { x = 51086.5, y = -54891.4, z = 296.646 } },
    },
    
  
    SHOP_KEYWORDS = {
        ": outfitter",
        ": baker",
        " bakery",
        " bookseller",
        " trader",
        " clothier",
        ": armorer",
        ": enchantress",
        " pawnbroker",
        ": general merchandise",
        " alchemist",
        ": enchanter",
        ": apothecary",
        ": healer",
        ": mage",
        ": monk",
        " smith",
        " smithy",
        ": sorcerer",
        ": tailor",
        "'s rare goods",
        "'s exotic weapons",
        "'s fine potions",
        "'s fine art",
        "'s redguard goods",
        "'s baked goods",
        "'s pantry",
        ": brickmason",
        "s' quality wares",
        "'s quality wares",
        ": herbalist",
        ": potter",
        "'s philters",
        ": general store",
        ": general goods",
        "'s novelties",
        ": master fletcher",
        " perfumes, potions, and elixirs",
        " sundries",
        ": alchemical remedies",
        " distillery",
        "the razor hole",
    },

    SAFE_KEYWORDS = {
        "temple",
        "barracks",
        "high fane",
        "chapel",
        "tradehouse",
        "cornerclub",
        "council club",
        "garrison",
        "fort",
        "inn",
        "tavern",
        "hostel",
        "hotel",
        "meadhouse",
        "ascadian ales",
        "caravanserai",
        -- "waistwork",
        "the blue kagouti", -- bcom vivec foreign quarter
        "temporary telvanni housing", -- vivec telvanni plaza
        "the abbey of st. delyn", 
        "the rat in the pot",
        "eight plates",
        "lucky lockup",
        "shenk's shovel",
        "the end of the world",
        "six fishes",
        "tower of dusk",
        "the pilgrim's rest",
        "fara's hole in the wall",
        "desele's house of",
        "plot and plaster",
        "the covenant",
        -- "no name club", -- Camonna Tong
        "the flowers of gold",
        "the lizard's head",
        "the winged guar",
        "raven rock, bar",
        "the grey lodge",
        "the laughing goblin",
        "limping scrib",
        "the pious pirate",
        "the guar with no name",
        "the dancing cup",
        "moons club",
        "the gentle velk",
        "the howling noose",
        "the queen's cutlass",
        "the red drake",
        "the leaking spore",
        "the musty mudcrub",
        "the swallow's nest",
        "the golden glade",
        "fighting chance",
        "heron hall",
        "the last drop",
        "the hackle-lounge",
        "the merchants's purse",
        "the purple lantern",
        "the fortuna",
        "the rigged challenge",
        "respite",
        "old ebonheart, the empress katariah",
        "old ebonheart, the moth and tiger",
        "old ebonheart, the salty futtocks",
        "port telvannis, the avenue",
        "rayon-ruhn, the dancing jug",
        "sailen, the toiling guar",
        "septim's gate pass, scent of niben",
        "stormgate pass, the saxhleel balladeer",
        "tel gilan, the cliff racer's rest",
        "tel mothrivra, the glass goblet",
        "tel muthada, the note in your eye",
        "tel ouada, the magic mudcrab",
        "verulas pass, twisted root",
        "anvil, the abecette",
        "anvil, the anchor's rest",
        "thresvy, the blind watchtower",
        "anvil, goldenrod house",
        "karthwasten, the dancing saber",
    },

    RECORD_ID_STRIP = {
        ["tr"] = true,
        ["m1"] = true,
        ["m2"] = true,
        ["m3"] = true,
        ["m4"] = true,
        ["m7"] = true,
        ["pc"] = true,
        ["shotn"] = true,
    },

    -- named exterior cells where the mod is active
    CITY_CELLS = {
        ["ahemmusa camp"] = true,
        ["ald velothi"] = true,
        ["ald-ruhn"] = true,
        ["arvel plantation"] = true,
        ["balmora"] = true,
        ["caldera"] = true,
        ["dagon fel"] = true,
        ["dren plantation"] = true,
        ["ebonheart"] = true,
        ["erabenimsun camp"] = true,
        ["gnaar mok"] = true,
        ["gnisis"] = true,
        ["hla oad"] = true,
        ["khuul"] = true,
        ["maar gan"] = true,
        ["molag mar"] = true,
        ["pelagiad"] = true,
        ["sadrith mora"] = true,
        ["seyda neen"] = true,
        ["skaal village"] = true,
        ["suran"] = true,
        ["tel aruhn"] = true,
        ["tel branora"] = true,
        ["tel mora"] = true,
        ["tel vos"] = true,
        ["urshilaku camp"] = true,
        ["vivec, arena"] = true,
        ["vivec, foreign quarter"] = true,
        ["vivec, hlaalu"] = true,
        ["vivec, redoran"] = true,
        ["vivec, st. delyn"] = true,
        ["vivec, st. olms"] = true,
        ["vivec, telvanni"] = true,
        ["vivec, temple"] = true,
        ["vos"] = true,
        ["wolverine hall"] = true,
        ["zainab camp"] = true,
        -- BCOM Vivec Interiors
        ["vivec, foreign quarter waistworks"] = true,
        -- Vivec Interiors
        ["vivec, foreign quarter lower waistworks"] = true,
        ["vivec, redoran waistworks"] = true,
        ["vivec, hlaalu plaza"] = true,
        ["vivec, hlaalu waistworks"] = true,
        ["vivec, telvanni waistworks"] = true,
        ["vivec, telvanni plaza"] = true,
        ["vivec, st. olms plaza"] = true,
        ["vivec, st. delyn plaza"] = true,
        -- Mournhold
        ["mournhold, godsreach"] = true,
        ["mournhold, great bazaar"] = true,
        ["mournhold, plaza brindisi dorom"] = true,
        ["mournhold, royal palace: courtyard"] = true,
        ["mournhold, temple courtyard"] = true,
        -- TR
        ["aimrah"] = true,
        ["akamora"] = true,
        ["almas thirr"] = true,
        ["alt bosara"] = true,
        ["ammar"] = true,
        ["andar mok"] = true,
        ["andothren"] = true,
        ["andothren, docks"] = true,
        ["arvud"] = true,
        ["ashamul"] = true,
        ["bahrammu"] = true,
        ["bal oyra"] = true,
        ["baldrahn"] = true,
        ["bodrum"] = true,
        ["bodrum, quarry"] = true,
        ["bosmora"] = true,
        ["darvonis"] = true,
        ["dondril"] = true,
        ["dreynim"] = true,
        ["ebon tower"] = true,
        ["enamor dayn"] = true,
        ["erethan plantation"] = true,
        ["felms ithul"] = true,
        ["firewatch"] = true,
        ["gah sadrith"] = true,
        ["gol mok"] = true,
        ["gorne"] = true,
        ["helnim"] = true,
        ["hla bulor"] = true,
        ["indal-ruhn"] = true,
        ["ishanuran camp"] = true,
        ["llothanis"] = true,
        ["marog"] = true,
        ["menaan"] = true,
        ["meralag"] = true,
        ["necrom"] = true,
        ["necrom, temple courtyard"] = true,
        ["necrom, upper district"] = true,
        ["necrom, waterfront"] = true,
        ["nivalis"] = true,
        ["obainat camp"] = true,
        ["old ebonheart"] = true,
        ["old ebonheart, docks"] = true,
        ["omaynis"] = true,
        ["oran plantation"] = true,
        ["port telvannis"] = true,
        ["ranyon-ruhn"] = true,
        ["rilsoan"] = true,
        ["roa dyr"] = true,
        ["sadas plantation"] = true,
        ["sailen"] = true,
        ["seitur"] = true,
        ["selyn"] = true,
        ["savrethi distillery"] = true,
        ["tahvel"] = true,
        ["tel aranyon"] = true,
        ["tel gilan"] = true,
        ["tel mothrivra"] = true,
        ["tel muthada"] = true,
        ["tel ouada"] = true,
        ["tel rivus"] = true,
        ["teyn"] = true,
        ["vathras plantation"] = true,
        ["uman"] = true,
        ["vhul"] = true,
        -- PC
        ["anvil, garden quarter"] = true,
        ["anvil, little arenthia"] = true,
        ["anvil, marina"] = true,
        ["anvil, port quarter"] = true,
        ["archad"] = true,
        ["brina cross"] = true,
        ["charach"] = true,
        ["hal sadek"] = true,
        ["marav"] = true,
        ["salthearth"] = true,
        ["talgiana orchard"] = true,
        ["thresvy"] = true,
        -- SHOTN
        ["bailcnoss"] = true,
        ["criaglorc"] = true,
        ["dragonstar east"] = true,
        ["dragonstar west"] = true,
        ["haimtir"] = true,
        ["karthgad"] = true,
        ["karthwasten"] = true,
        ["mairager"] = true,
        ["merduibh"] = true,
        ["nargozh camp"] = true,
        ["uramok camp"] = true,
        -- CRF
        ["ald redaynia"] = true,
    },

    -- not exteriors but mod works here
    MOURNHOLD_INTERIORS = {
        ["mournhold, godsreach"] = true,
        ["mournhold, great bazaar"] = true,
        ["mournhold, plaza brindisi dorom"] = true,
        ["mournhold, royal palace: courtyard"] = true,
        ["mournhold, temple courtyard"] = true,
        -- BCOM Vivec Interiors
        ["vivec, foreign quarter waistworks"] = true,
        -- Vivec Interiors
        ["vivec, foreign quarter lower waistworks"] = true,
        ["vivec, redoran waistworks"] = true,
        ["vivec, hlaalu plaza"] = true,
        ["vivec, hlaalu waistworks"] = true,
        ["vivec, telvanni waistworks"] = true,
        ["vivec, telvanni plaza"] = true,
        ["vivec, st. olms plaza"] = true,
        ["vivec, st. delyn plaza"] = true,

    },

    GRID_CELLS = {
        ["-21,24"] = true,
        ["-7,6"] = true,
        ["-5,4"] = true,
        ["-1,-2"] = true,
        ["-1,-7"] = true,
        ["-1,6"] = true,
        ["1,-9"] = true,
        ["3,-6"] = true,
        ["4,-5"] = true,
        ["4,-7"] = true,
        ["4,-8"] = true,
        ["5,-6"] = true,
        ["5,-8"] = true,
        -- TR
        ["2,-20"] = true,
        ["36,-19"] = true,
        ["37,-19"] = true,
        -- PC
        ["-115,-48"] = true,
        ["-116,-48"] = true,
        ["-125,-46"] = true,
        ["-117,-47"] = true,
        -- CRF
        ["-7,10"] = true,
        ["-9,8"] = true,
    },

    -- tribunal temples
    TRIBUNAL_TEMPLE_CELLS = {
        -- Morrowind.esm
        ["ald-ruhn, temple"]                     = true,
        ["balmora, temple"]                      = true,
        ["gnisis, temple"]                       = true,
        ["maar gan, shrine"]                     = true,
        ["molag mar, temple"]                    = true,
        ["suran, suran temple"]                  = true,
        ["vivec, high fane"]                     = true,
        ["vivec, hlaalu temple"]                 = true,
        ["vos, vos chapel"]                      = true,
        -- Tamriel Rebuilt
        ["ald iuval, temple"]                    = true,
        ["almas thirr, temple"]                  = true,
        ["almas thirr, monastery of st. veloth"] = true,
        ["bal foyen, temple"]                    = true,
        ["hlan oek, temple"]                     = true,
        ["narsis, shrine of the hidden saints"]  = true,
        ["narsis, eight-bones temple"]           = true,
        ["ranyon-ruhn, temple"]                  = true,
    },
 
    -- imperial cult chapels/shrines
    IMPERIAL_SHRINE_CELLS = {
        -- Cyrodiil
        ["anvil, temple of dibella estetica"]    = true,
        -- Tamriel Rebuilt
        ["firewatch, grand chapel of akatosh"]   = true,
        ["helnim, chapel of kynareth"]           = true,
        ["old ebonheart, grand chapel of talos"] = true,
        ["hlerynhul, chapel of dibella"]         = true,
        ["narsis, chapel of zenithar"]           = true,
    },

    DEFAULTS = {
        HARD_RESET             = false,
        GO_HOME_BAD_WEATHER    = false,
        WEATHER_CHECK_INTERVAL = 30,
        UNLOCK_HOME_DOORS      = false,
        NIGHT_START            = 23,
        NIGHT_END              = 6,
        DOOR_SCAN_RANGE        = 7168,
        DOOR_ARRIVAL_DIST      = 270,
        CHECK_INTERVAL         = 3,
        SAFE_SPACING           = 64,
        MAX_SAFE_OCCUPANTS     = 5,
        EXCLUDE_TRAVEL_CLASSES = true,
        MAX_DELAY              = 30,
        CITY_WHITELIST         = true,
        MORNING_BATCH_SIZE     = 8,
        MORNING_BATCH_DELAY    = 1.0,
        ENABLE_DOOR_SOUNDS     = true,
        DOOR_SOUND_COOLDOWN    = 1.0,
        FAR_TELEPORT_DIST      = 7168,  -- player further than this: always teleport, ignore LOS
        ENABLE_LOGS            = false,
        SAFE_WANDER_DIST       = 512,    -- wander distance for NPCs in safe places
        SAFE_WANDER_DURATION   = 10800,
        SAFE_WANDER_IDLE       = {
            idle2 = 20, idle3 = 10, idle4 = 10, idle5 = 20,
            idle6 = 10, idle7 = 10, idle8 = 5,  idle9 = 25,
        },
        ENABLE_SHOP_VISITS     = false,
        SHOP_VISIT_START       = 11,
        SHOP_VISIT_END         = 16,
        SHOP_VISIT_CHANCE      = 5,
        SHOP_WANDER_DIST       = 256, -- wander distance for NPCs in shops
        ENABLE_TEMPLE_VISITS   = false,
        TEMPLE_VISIT_CHANCE    = 2,
    },
}