--[[
Format for Mods:
- ID can be for any soundID, mesh filepath, or texture filepath. Must be lowercase.
- Category hooks into the tables above, so the first value will be the name of the desired table, and the second the desired value within it.
    Anything getting added to ignoreList must have an empty category of: ""
    Anything getting added to corpseMapping must have a category of: "Body"
- Define your soundType so it's properly sorted, for instance 'soundType = land' to specify texture material type.
--]]

local function initialized()
    local cso = include("Character Sound Overhaul.interop")
    if cso == nil then return end
    local soundData = {
        -- Land, Carpet:
        { id = "az\\_5_rug_03", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\_5_rug_18", category = cso.landTypes.carpet, soundType = "land" },
		{ id = "az\\_5_rug_48", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_fabric_pirate", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_sign_port", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_04", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_05", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_06", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_07", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_08", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_09", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_10", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_11", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_12", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_13", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_14", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_furn_tapestry_conj", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_jukung_sail", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_pirate_banner_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_pirate_banner_simple_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_pirate_banner_simple_02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_rug_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_rug_02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_rug_edge_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_rug_edge_02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_tapestry_ouamer_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_tapestry_ouamer_02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_tapestry_ouamer_03", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\az_tiger_scarlet", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\banner_gom", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\banner_gom_long", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\db_adobe_canvas", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\dr_tx_canvass_03", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_009", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_015", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_017", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_021", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_025", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_077", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_081", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_094", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_101", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_104", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_125", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_157", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_167", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_176", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_182", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\key_rugs_01_197", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\md_azura_v_ban01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\md_cloth_green_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\md_tx_sail2", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momocarpet01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momocarpet02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momocarpet03", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momocarpet04", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momofischnetz01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momoleder01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momolederweib", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momoleinen01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momoleinen02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momoleinen04", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momoleinendirt01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momoleinendirt02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\momosack01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\ndib_ex_dock_float", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\ndib_ex_dock_walkway_float", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\ndib_ex_th_ropes", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\r0_net2", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug00", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug02", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug03", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug04", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug05", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug06", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\rr_tx_rug07", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_az_elvenship_sail_siika", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_canvaswrap_target", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_canvaswrap00_wheat", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_dwegarskin_dark", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_dwegarskin_hut", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_fabric_azura", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_fabric_flower", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_fabric_veil_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_lord_yig_rug_004", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_lord_yig_rug_022", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_lord_yig_rug_029", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_lord_yig_rug_030", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_sail_pirate", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_sail_redstripe", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\tx_victorian_shag_01", category = cso.landTypes.carpet, soundType = "land" },
        { id = "az\\zs_ct_rope_01", category = cso.landTypes.carpet, soundType = "land" },

        -- Land, Dirt:
        { id = "az\\az_land_ai_dirt_01", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\az_land_ai_dirt_patch", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\az_land_ai_dirt_road", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\az_land_ai_dirt_tilled", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\az_land_coast_rock_02", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\az_land_sand_01", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\az_land_ti_dirt", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\grains01", category = cso.landTypes.dirt, soundType = "land" },
        { id = "az\\momograin01", category = cso.landTypes.dirt, soundType = "land" },

        -- Land, Grass:
        { id = "az\\az_hedge_wrap", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_hedge_wrap_top", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_kelp_strips_01", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ai_clover", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ai_grass_01", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ai_grass_dirt", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ai_grass_rocky", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ti_grass", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ti_moss", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ti_scrub", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_land_ti_undergrowth", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_lilypad_giant", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_sakura_ground", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_tallflower_petal", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\az_wicker_baskets", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\cpfliana01", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\generic_grass4_col", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\generic_grassoverhang2_col", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\md_seaweed_01", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\md_v_wallvine_tex", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\momoheu01", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\straw", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\tx_dawn_ground", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\tx_rockyscrub_01", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\tx_thatch_roof", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\tx_wicker_checker_01", category = cso.landTypes.grass, soundType = "land" },
        { id = "az\\tx_wicker_checker_03", category = cso.landTypes.grass, soundType = "land" },

        -- Land, Gravel:
        { id = "az\\az_cave_ground_01", category = cso.landTypes.gravel, soundType = "land" },
        { id = "az\\az_land_ai_mudflats", category = cso.landTypes.gravel, soundType = "land" },
        { id = "az\\ex_v_rubble", category = cso.landTypes.gravel, soundType = "land" },
        { id = "az\\tx_gravel_04", category = cso.landTypes.gravel, soundType = "land" },

        -- Land, Ice:
        { id = "az\\az_bone_generic_01", category = cso.landTypes.ice, soundType = "land" },
        { id = "az\\az_mao_seaglass_01", category = cso.landTypes.ice, soundType = "land" },
        { id = "az\\az_mao_seaglass_01_g", category = cso.landTypes.ice, soundType = "land" },
        { id = "az\\elvenship_window", category = cso.landTypes.ice, soundType = "land" },
        { id = "az\\tx_bone_01", category = cso.landTypes.ice, soundType = "land" },
        { id = "az\\tx_glassscreen_02_b", category = cso.landTypes.ice, soundType = "land" },
        { id = "az\\tx_glassscreen_02_c", category = cso.landTypes.ice, soundType = "land" },
        { id = "az\\tx_glassscreen_03", category = cso.landTypes.ice, soundType = "land" },

        -- Land, Metal:
        { id = "az\\az_daed_azura_moon", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_daed_azura_star", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_gold_01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_gold_panel_02", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_gold_trim_01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_gold_trim_02", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_mao_brass_trim_01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_mao_chest_01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_mao_brass_door_01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\az_pirate_coin_tile", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\bar_bronzepanel_beta", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\bar_rusty_metal", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\dawn_star", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\dr_tbl_alchemy_01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\dr_tbl_enchanting_01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\dr_tx_rustmetal_02", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\md_metal_copper", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\md_metal_copper_03", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\md_metal_copper_worn_detail", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\md_metal_copper_worn_grate", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\md_metal_copper_worn_star", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\metal13", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\rgj5steel", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\rost01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\rost02", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\rust01", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\tx_az_elvenship_gold_siika", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\tx_azura_shrine", category = cso.landTypes.metal, soundType = "land" },
        { id = "az\\tx_metal_strip_01", category = cso.landTypes.metal, soundType = "land" },

        -- Land, Mud:
        { id = "az\\az_land_ti_bank", category = cso.landTypes.mud, soundType = "land" },
        { id = "az\\az_land_ti_muck", category = cso.landTypes.mud, soundType = "land" },
        { id = "az\\az_tx_rainbow_clay", category = cso.landTypes.mud, soundType = "land" },
        { id = "az\\md_boarnetch_jelly_01", category = cso.landTypes.mud, soundType = "land" },

        -- Land, Stone:
        { id = "az\\_dni_decor008", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\as_stone_02", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_cave_rocks_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_cave_rocks_02", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_cave_stalactites_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_cave_stalagmites_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_land_ai_cobblestone", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_land_ai_mainroad", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_land_coast_rock_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_land_coast_rock_03", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_land_ti_mainroad", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_land_ti_rock_04", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_land_ti_scrub_rocky", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_fish_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_statue_base", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_statue_water", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_02", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_cobble_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_scales", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_sun_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_trim_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_wall_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_stone_wall_03", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_troll_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_wall_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_mao_wall_03", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_pottery_00", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_pottery_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_pottery_02", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_rock_mineral_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_stucco_imp_02", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_stucco_imp_02_blue", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_stucco_imp_02_green", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_stucco_imp_02_red", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_sundrake_body", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_sundrake_enviro", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_sundrake_head", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_sundrake_horns", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_sundrake_rocks", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_tile_blank", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\az_uwrock_green", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\azurian_rock_mountain", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\azurian_rocks", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\azurian_rocks_cave", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\azurian_rocks_flattop", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\bar_richhearth", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\basalt01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\bx_tx_rock_emerald_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\coralrockrainbow1", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\coralrockrainbow2", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\db_dng_wall01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\fantasy rock 02", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\fire_dec114", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\fire_dec115", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\fire_dec120", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\fire_dec129", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\firerock_diffus", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\hiveshell", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\hiveshell_n", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\hiveshell1", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\hivestairs", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec086", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec088", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec122", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec122_edge", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec123", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec126", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec139", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec147", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec163", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_dec232", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_door_woodmetalframebronceboltshinges", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_sur_000", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\maor_sur_027", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_azura_tx_rock_07", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_coral_plain", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_crystal", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_key_med_017", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_mountain", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_stucco_old02_90", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_tx_rm_rock_ao_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\md_tx_rm_rock_ao_02", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\millstone", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\ndib_furn_urn_1", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\ndib_furn_urn_lid_1", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\ndib_kollop_pink", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\sils_potteryw_top", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\sils_vase_002", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\sils_vase_004", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\tr_z_rock_iron_ore", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\tx_dusk_rock_01", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\tx_umbrage_tile", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\volcano_floor_0", category = cso.landTypes.stone, soundType = "land" },
        { id = "az\\wl_marble", category = cso.landTypes.stone, soundType = "land" },

        -- Land, Water:
        { id = "az\\btrwtr_water_anim_01", category = cso.landTypes.water, soundType = "land" },
        { id = "az\\btrwtr_water_anim_02", category = cso.landTypes.water, soundType = "land" },
        { id = "az\\tx_water_anim_02", category = cso.landTypes.water, soundType = "land" },
        { id = "az\\tx_water_anim_02_dist", category = cso.landTypes.water, soundType = "land" },
        { id = "az\\tx_water_anim_03", category = cso.landTypes.water, soundType = "land" },

        -- Land, Wood:
        { id = "az\\_ar_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\ac_bark002", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_ai_tree_01_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_atlas_woodpoles", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bamboo_stalk", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_02", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_fern", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_gnarly_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_gnarly_02", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_gnarly_03", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_gnarly_04", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_bark_swamp", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_barrel2", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_cypress_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_dawntree_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_dogear_bark_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_hazelnutbush_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_mangrove_bark_02", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_mountainmaple_cap", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_ndib_tree_bark_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_oak_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_peach_bark_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_pine_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_poplar_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_mountainmaple_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_rhododendron_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_riverbirch_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_rum_barrel_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_sakura_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_tree_cypreschauve_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_tree_jungle_bark_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_willow_bark_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_wood_brown_posts_04", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_wood_painted_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_woodplat_atlas", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_woodplatfloor", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\az_woodplatpaintblue_atlas", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\azcrate", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\bamboolantern", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\bar_wood02", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\bar_wood02_beta", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\bark25", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\birchcanoe2", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\birdiehouse", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\bush_01_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\dr_bark03_ayse", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\dr_tbl_alchemy_wood", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\jd_bark16_ayse", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\key_plant_bark_02", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\key_plant_bark_06", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\key_plant_bark_09", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\key_plant_bark_10", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\lacrwood01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\md_shucker_handle", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\medievaldoor01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\medievalwood01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\meubledemage", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\nom_woodpump", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\nom_woodruined", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\palm_bark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\palm2_02", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\palmbark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\philodendronbark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\postenddark01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\rosewood02", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\rr_wood_boat_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\rr_wood_boat_03", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\rr_wood_boat_04", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\sils_potteryw_wood", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\skwooddark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\snow_gum_mod", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\ss_bark_06", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\tx_az_elvenship_post_siika", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\tx_az_elvenship_siding", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\tx_bamboo_slats", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\tx_wood_pirate_01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\tx_wood_pirate_solid", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\wood02dark", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\woodmoulding01", category = cso.landTypes.wood, soundType = "land" },
        { id = "az\\zs_ct_wood_02", category = cso.landTypes.wood, soundType = "land" },

        -- Items, Book:
        { id = "az\\m\\bk_thesundrake.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_whispers.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_weateittobecomeit .nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_wannabepirate.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_thetranslation.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_thetealwatersnakes.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_therepublicofhahd.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_thenautican.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_thelightandthedark.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_theanachronisle.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_theadventurerslife.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_the5pointsofthestar.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_shoroftheshore.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_secretofthedreugh.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_rumorsofspiralskein.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_roseryofazura.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_onkothringi.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_nightlifeoftamriel.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_natureoftheetada.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_missivefromtangmo.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_magesguildcharter.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_liminalbridges.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_honorandmoderation.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_historyofhouseazura.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_hammerandcalcinator.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_fundamentsofalchemy.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_findingtherose.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_fighterguildcharter.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_elvesofsouthisles.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_dragondsea_v5.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_dragondsea_v4.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_dragondsea_v3.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_dragondsea_v2.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_dragondsea_v1_o.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_darkestdivinities_o.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_beforetheagesofman.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_azuratheangel.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\az_bk_daedraslay_vol4.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\az_bk_daedraslay_vol3.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\az_bk_daedraslay_vol2.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\az_bk_daedraslay_vol1.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\az_bk_daedraslay_appa.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\az_bk_buildingboats.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\bk_impcensusofdaedra.nif", category = cso.itemTypes.book, soundType = "item" },
        { id = "az\\m\\az_book_leatherbound.nif", category = cso.itemTypes.book, soundType = "item" },

        -- Items, Clothing:
        { id = "az\\m\\rm_sailcloth.nif", category = cso.itemTypes.clothing, soundType = "item" },
        { id = "az\\m\\az_foldedcloth_00.nif", category = cso.itemTypes.clothing, soundType = "item" },

        -- Items, Gold:
        { id = "az\\m\\piratecoin010.nif", category = cso.itemTypes.gold, soundType = "item" },
        { id = "az\\m\\piratecoin001.nif", category = cso.itemTypes.gold, soundType = "item" },
        { id = "az\\m\\piratecoin005.nif", category = cso.itemTypes.gold, soundType = "item" },
        { id = "az\\m\\piratecoin025.nif", category = cso.itemTypes.gold, soundType = "item" },
        { id = "az\\m\\piratecoin100.nif", category = cso.itemTypes.gold, soundType = "item" },

        -- Items, Gems:
        { id = "az\\m\\sg_soulgem_frag.nif", category = cso.itemTypes.gems, soundType = "item" },
        { id = "az\\m\\az_crystal_chunk.nif", category = cso.itemTypes.gems, soundType = "item" },
        { id = "az\\m\\az_oreessence.nif", category = cso.itemTypes.gems, soundType = "item" }

        -- Lockpicks/Keys:
        { id = "az\\e\\az_dae_graffiti_01.nif", category = cso.itemTypes.lockpick, soundType = "item" },

        -- Items, Repair:
        { id = "az\\e\\az_dae_graffiti_01.nif", category = cso.itemTypes.repair, soundType = "item" },

        -- Items, Scrolls:
        { id = "az\\m\\stxucscroll01.nif", category = cso.itemTypes.scrolls, soundType = "item" },
        { id = "az\\m\\scroll_open_03.nif", category = cso.itemTypes.scrolls, soundType = "item" },
        { id = "az\\m\\az_scroll_map_azura.nif", category = cso.itemTypes.scrolls, soundType = "item" },
        { id = "az\\m\\stxucscroll01.nif", category = cso.itemTypes.scrolls, soundType = "item" },
        { id = "az\\m\\stxucscroll01.nif", category = cso.itemTypes.scrolls, soundType = "item" },
        { id = "az\\m\\stxucscroll01.nif", category = cso.itemTypes.scrolls, soundType = "item" },
        { id = "az\\m\\stxucscroll01.nif", category = cso.itemTypes.scrolls, soundType = "item" },
        { id = "az\\m\\stxucscroll01.nif", category = cso.itemTypes.scrolls, soundType = "item" },

        -- Corpse Containers:
        { id = "az\\o\\fish02_hang.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\fish02_lay.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\fish02_laycut.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\fish03_hang.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\fish03_lay.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\redshark_hang.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\tad_exhibitor_guar.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\tad_exhibitor_kriin.nif", category = cso.specialTypes.body, soundType = "corpse" },
        { id = "az\\o\\tad_exhibitor_rat.nif", category = cso.specialTypes.body, soundType = "corpse" },

        -- Creatures
        { id = "az\\r\\az_fire spirit_fix.nif", category = cso.specialTypes.ghost, soundType = "creature" },

    }
    for _, data in ipairs(soundData) do
        cso.addSoundData(data.id, data.category, data.soundType)
    end
end
event.register("initialized", initialized)