--[[--------------------------------------------------------------------
  Centralised repository for every random-equipment list used by the
  Wabbajack scripts.  Update or extend the IDs here and both the
  actor-side and server-side logic will pick them up automatically.

  If you don’t need a particular slot, simply leave its `ids = {}` empty.
------------------------------------------------------------------------]]

local types = require('openmw.types')

local ITEM_LISTS = {

  ----------------------------------------------------------------------
  -- Armour slots
  ----------------------------------------------------------------------
  helmet = {
    slot = types.Actor.EQUIPMENT_SLOT.Helmet,
    ids = {
      "t_bre_ep_hatwizard_01","t_bre_ep_hatwizard_02","t_com_cm_hat_01",
      "t_com_cm_hat_02","t_com_cm_hat_03","t_com_cm_hat_04","t_com_cm_hat_05",
      "t_com_cm_hat_haggling","t_com_cm_hatclothcoif_01","t_com_cm_hatclothcoif_02",
      "t_com_et_hat_01","t_com_et_hat_02","t_com_et_hat_03","t_com_et_hat_04",
      "t_com_et_hat_05","t_com_et_hat_foresight","t_com_et_hat_imperious",
      "t_com_et_hatclothcoif_01","t_com_foolshat_01","t_com_foolshat_02",
      "t_de_cm_hattelv_01","t_de_cm_hattelv_02","t_de_cm_hattelv_03",
      "t_de_cm_hattelv_04","t_de_cm_hattelv_05","t_de_dreschapthil_helm_01a",
      "t_de_dreschapthil_helm_01b","t_de_dreschapthil_helm_01c",
      "t_de_dreschapthil_helm_01d","t_de_dreschapthil_helm_01e",
      "t_de_dreschapthil_helm_02a","t_de_dreschapthil_helm_02b",
      "t_de_dreschapthil_helm_02c","t_de_dreschapthil_helm_02d",
      "t_de_dreschapthil_helm_02e","t_de_dreschapthil_helm_03a",
      "t_de_dreschapthil_helm_03b","t_de_dreschapthil_helm_03c",
      "t_de_dreschapthil_helm_03e","t_de_ep_hattelv_01","t_de_ep_hattelv_02",
      "t_de_ep_hattelv_03","t_de_et_hattelv_01","t_de_et_hattelv_02",
      "t_de_ex_hattelv_01","t_de_ex_hattelv_02","t_de_guarskin_helm_01",
      "t_imp_cm_hatcolwest_01","t_imp_cm_hatcolwest_02","t_imp_ep_hatcolwest_01",
      "t_imp_ep_hatcolwest_02","t_imp_ep_hatcolwest_03","t_imp_ep_hatcolwest_04",
      "t_imp_et_hatcolnorth_01","t_imp_et_hatcolnorth_02","t_imp_et_hatcolnorth_03",
      "t_imp_et_hatcolnorth_04","t_imp_et_hatcolnorth_05","t_rea_leather_hat_01",
      "t_rea_leather_hat_witchery","t_rea_uni_feathercrown","t_rga_ep_headdress_01",
      "fur_colovian_helm_white"
    },
  },

  robe = {
    slot = types.Actor.EQUIPMENT_SLOT.Robe,
    ids = {
      "common_robe_01","expensive_robe_03","common_robe_02","common_robe_03",
      "common_robe_05","expensive_robe_02","exquisite_robe_01",
      "common_robe_02_t","extravagant_robe_01","extravagant_robe_02",
      "common_robe_02_r","expensive_robe_02_a","common_robe_04",
      "common_robe_05_c","expensive_robe_01","common_robe_03_a",
      "common_robe_05_b","common_robe_05_a","common_robe_02_h",
      "extravagant_robe_01_t","common_robe_02_tt","extravagant_robe_01_a",
      "extravagant_robe_01_b","extravagant_robe_01_c","BM_Nordic01_Robe",
      "common_robe_02_rr","extravagant_robe_01_r","extravagant_robe_01_h",
      "common_robe_03_b","common_robe_02_hh","T_De_Cm_Robe_01",
      "T_De_Ex_Robe_01","BM_Wool01_Robe","T_De_Et_RobeTelv_01",
      "T_De_Et_Robe_01","T_Imp_Cm_RobeNib_01","T_Imp_Cm_RobeNib_02",
      "T_Imp_Cm_RobeNib_03","T_Imp_Cm_RobeNib_04","T_Imp_Cm_RobeNib_05",
      "T_Imp_Cm_RobeNib_06","T_Imp_Ep_RobeNib_01","T_Imp_Ep_RobeNib_02",
      "T_Imp_Ep_RobeNib_03","T_Imp_Ep_RobeNib_04","T_Imp_Et_RobeNib_01",
      "T_Imp_Et_RobeNib_02","T_Imp_Et_RobeNib_03","T_Imp_Et_RobeNib_04",
      "T_Imp_Ex_RobeNib_01","T_Imp_Ex_RobeNib_02","T_Com_Ep_Robe_01",
      "T_De_Cm_Robe_02","T_De_Cm_Robe_03","T_De_Cm_Robe_04","T_De_Cm_Robe_05",
      "T_De_Cm_Robe_06","T_De_Ex_RobeTelv_01","T_Imp_Et_Robe_01",
      "AB_c_CommonRobeBlack","T_Imp_Cm_RobeCol_01","T_Imp_Cm_RobeCol_02",
      "T_Imp_Ep_RobeCol_03","T_Imp_Ep_RobeCol_04","T_Rga_Ep_Robe_01",
      "T_Rga_Et_Robe_01","T_Bre_Ep_RobeWizard_01","T_De_Et_RobeNecromPriest_01",
      "T_De_Et_RobeShin_01","T_De_Et_RobeShin_02"
    },
  },

  boots = {
    slot = types.Actor.EQUIPMENT_SLOT.Boots,
    ids = {
      "ab_a_bonemlightboots",
    "ab_a_bugblueboots",
    "ab_a_buggreenboots",
    "ab_a_dreughboots",
    "ab_a_dustboots",
    "ab_a_impbmboots",
    "ab_a_irondeboots",
    "ab_a_steelboots",
    "adamantium boots",
    "bm bear boots",
    "bm wolf boots",
    "bm_bear_boots_snow",
    "bm_ice_boots",
    "bm_nordicmail_boots",
    "bm_wolf_boots_snow",
    "bonemold_boots",
    "boots of blinding speed[unique]",
    "boots of blinding speed_x",
    "chitin boots",
    "conoon_chodala_boots_unique",
    "darkbrotherhood boots",
    "dwemer_boots",
    "dwemer_boots of flying",
    "ebony_boots",
    "fur_boots",
    "glass_boots",
    "heavy_leather_boots",
    "helsethguard_boots",
    "imperial boots",
    "indoril boots",
    "indoril_mh_guard_boots",
    "iron boots",
    "netch_leather_boots",
    "orcish_boots",
    "steel_boots_ancient",
    "t_ayl_saliache_boots_01",
    "t_com_iron_boots_01",
    "t_com_iron_boots_02",
    "t_com_steel_boots_consuming",
    "t_com_steel_boots_creeping",
    "t_dae_uni_bootsofatronach",
    "t_dae_uni_bootsofpeace_01",
    "t_dae_uni_bootssaviorshide",
    "t_de_bonemold_chuzei_boots",
    "t_de_bonemold_chuzei_boots_e",
    "t_de_bonemold_stone_boots",
    "t_de_bonemold_ulvra_boots",
    "t_de_bonemold_water_boots",
    "t_de_bonemoldsacred_boots_01",
    "t_de_canyonwatch_boots_01",
    "t_de_dreugh_boots_01",
    "t_de_guarskin_boots_01",
    "t_de_hvchit_boots",
    "t_de_indbonemold_boots_01",
    "t_de_indchevaram_boots_01",
    "t_de_kagoutihide_boots_01",
    "t_de_molecrab_boots_01",
    "t_de_narsiswatch_boots_01",
    "t_de_nativeebony_boots_01",
    "t_de_necrom_boots_01",
    "t_de_redoranwatchman_boots",
    "t_de_riverwatch_boots_01",
    "t_de_shinchitin_boots",
    "t_de_telvcephalopod_boots_01",
    "t_dwe_scrap_boots",
    "t_he_altmerglass_boots_01",
    "t_he_direnni_boots_01",
    "t_imp_alessianbrnz_boots_01",
    "t_imp_chain_boots_01",
    "t_imp_cm_bootscol_01",
    "t_imp_cm_bootscol_02",
    "t_imp_cm_bootscol_03",
    "t_imp_cm_bootscol_04",
    "t_imp_colfur_boots_01",
    "t_imp_colfur_boots_02",
    "t_imp_colfur_boots_03",
    "t_imp_colfur_boots_04",
    "t_imp_colgoathide_boots_01",
    "t_imp_colsteel_boots_03",
    "t_imp_colsteel_boots_04",
    "t_imp_domina_boots_01",
    "t_imp_dragonscale_boots_01",
    "t_imp_gold_boots_02",
    "t_imp_guardtown1_boots_01",
    "t_imp_guardtown2_boots_01",
    "t_imp_guardtown3_boots_01",
    "t_imp_militia_boots_01",
    "t_imp_navyoff_boots_01",
    "t_imp_navystud_boots_01",
    "t_imp_newtscale_boots_01",
    "t_imp_reman_boots_01",
    "t_imp_silver_boots_01",
    "t_imp_studdedleather_boots_01",
    "t_mao_scale_boots_01",
    "t_nor_bearskin_boots_01",
    "t_nor_companion_boots_01",
    "t_nor_guardfalkr_boots_01",
    "t_nor_iron_boots_01",
    "t_nor_iron_boots_leap",
    "t_nor_leather1_boots_01",
    "t_nor_rearoy_boots_01",
    "t_nor_ringmail_boots_01",
    "t_nor_ringmail_boots_02",
    "t_nor_steel_boots_01",
    "t_nor_toadscale_boots_01",
    "t_nor_toadscale_boots_02",
    "t_nor_trollbone_boots_01",
    "t_nor_uni_predatorsgrace",
    "t_orc_leather_boots_01",
    "t_qyc_shellmold_boots_01",
    "t_qyk_manatee_boots_01",
    "t_rea_wormmouth_boots_01",
    "t_rga_crownguard1_boots_01",
    "t_rga_iron_boots_01",
    "t_rga_iron_boots_02",
    "t_rga_ironlamellar_boots_01",
    "t_we_wenbone_boots_01",
    },
  },

  cuirass = {
    slot = types.Actor.EQUIPMENT_SLOT.Cuirass,
    ids = {
      "chitin cuirass",
    "templar_cuirass",
    "indoril cuirass",
    "netch_leather_cuirass",
    "netch_leather_boiled_cuirass",
    "fur_cuirass",
    "fur_bearskin_cuirass",
    "imperial_studded_cuirass",
    "imperial_chain_cuirass",
    "nordic_ringmail_cuirass",
    "newtscale_cuirass",
    "silver_cuirass",
    "silver_dukesguard_cuirass",
    "nordic_iron_cuirass",
    "steel_cuirass",
    "iron_cuirass",
    "bonemold_gah-julan_cuirass",
    "bonemold_armun-an_cuirass",
    "trollbone_cuirass",
    "dragonscale_cuirass",
    "dwemer_cuirass",
    "orcish_cuirass",
    "dreugh_cuirass",
    "glass_cuirass",
    "ebony_cuirass",
    "imperial cuirass_armor",
    "merisan_cuirass",
    "the_chiding_cuirass",
    "bonemold_cuirass",
    "dreugh_cuirass_ttrm",
    "mountain spirit", 
  "bm bear cuirass", 
  "bm wolf cuirass", 
  "steel_cuirass_ancient", 
  "bm_wolf_cuirass_snow",
  "bm_bear_cuirass_snow", 
  "bm_nordicmail_cuirass", 
  "bm_ice_cuirass", 
  "ebony_cuirass_soscean",
  "indoril_almalexia_cuirass", 
  "helsethguard_cuirass", 
  "darkbrotherhood cuirass",
  "adamantium_cuirass", 
  "indoril_mh_guard_cuirass", 
  "t_arg_hist_cuirass_01",
  "t_arg_hist_cuirass_freedom", 
  "t_arg_hist_cuirass_visitor", 
  "t_ayl_saliache_cuirass_01",
  "t_com_chain_cuirass_01", 
  "t_com_chain_cuirass_02", 
  "t_com_chain_cuirass_03",
  "t_com_iron_cuirass_01", 
  "t_com_iron_cuirass_02", 
  "t_com_steel_cuirass_01",
  "t_com_steel_cuirass_02", 
  "t_com_steel_cuirass_03", 
  "t_com_steel_cuirass_04",
  "t_com_steel_cuirass_duskdawn", 
  "t_com_steel_cuirass_outermost",
  "t_com_steel_cuirass_scalypelt", 
  "t_com_steel_cuirass_steelhearth",
  "t_dae_alternate_cuirass_01", 
  "t_dae_gold_cuirass_01", 
  "t_de_alithide_cuirass_01",
  "t_de_bonemoldkrage_cuirass_01", 
  "t_de_bonemoldmarad_cuirass_01",
  "t_de_bonemoldsacred_cuirass_01", 
  "t_de_bonemold_chuzei_cuirass",
  "t_de_bonemold_chuzei_cuirass_e", 
  "t_de_bonemold_stone_cuirass",
  "t_imp_guardtown1_cuirass_01",
    "t_imp_guardtown2_cuirass_01",
    "t_imp_guardtown3_cuirass_01",
    "t_imp_militia_cuirass_01",
    "t_imp_navyoff_cuirass_01",
    "t_imp_navystud_cuirass_01",
    "t_imp_nibbronze_cuirass_01",
    "t_imp_reman_cuirass_01",
    "t_imp_silver_cuirassfw_01",
    "t_imp_silver_cuirassred_01",
    "t_imp_studdedleather_cuirass_02",
    "t_imp_studdedleather_cuirass_03",
    "t_mao_scale_cuirass_01",
    "t_nor_companion_cuirass_01",
    "t_nor_guardfalkr_cuirass_01",
    "t_nor_guard_cuirass_01",
    "t_nor_iron_cuirass_wintery",
    "t_nor_leather1_cuirass_01",
    "t_nor_rearoy_cuirass_01",
    "t_nor_ringmail_cuirass_01",
    "t_nor_steel_cuirass_01",
    "t_nor_steel_cuirass_steelhearth",
    "t_nor_toadscale_cuirass_01",
    "t_nor_toadscale_cuirass_02",
    "t_nor_uni_snowdrakepelt",
    "t_orc_leather_cuirass_01",
    "t_qyc_shellmold_cuirass_01",
    "t_qyk_manatee_cuirass_01",
    "t_rea_wormmouth_cuirass_01",
    "t_rga_crownguard1_cuirass_01",
    "t_rga_ironlamellar_cuirass_01",
    "t_rga_iron_cuirass_01",
    "t_rga_iron_cuirass_02",
    "t_rga_lamellar_cuirass",
    "t_rga_lamellar_cuirass_b",
    "t_rga_lamellar_cuirass_g",
    "t_rga_lamellar_cuirass_y",
    "t_we_wenbone_cuirass_01",
    "ab_a_bugbluecuirass",
    "ab_a_buggreencuirass",
    "ab_a_steelcuirass"
    },
  },

  greaves = {
    slot = types.Actor.EQUIPMENT_SLOT.Greaves,
    ids = {
      "chitin greaves",
    "netch_leather_greaves",
    "fur_greaves",
    "imperial_greaves",
    "templar_greaves",
    "steel_greaves",
    "iron_greaves",
    "bonemold_greaves",
    "dwemer_greaves",
    "orcish_greaves",
    "ebony_greaves",
    "imperial_chain_greaves",
    "steel_greaves_ancient",
    "bm_wolf_greaves_snow",
    "bm_bear_greaves_snow",
    "bm_nordicmail_greaves",
    "bm_ice_greaves",
    "indoril_almalexia_greaves",
    "helsethguard_greaves",
    "darkbrotherhood greaves",
    "adamantium_greaves",
    "indoril_mh_guard_greaves",
    "t_ayl_saliache_greaves_01",
    "t_com_iron_greaves_01",
    "t_com_iron_greaves_02",
    "t_com_steel_greaves_bitingpains",
    "t_com_steel_greaves_kings",
    "t_com_steel_greaves_stamptoad",
    "t_dae_gold_greaves_01",
    "t_de_alithide_greaves_01",
    "t_de_bonemold_chuzei_greaves",
    "t_de_bonemold_water_greaves",
    },
  },

  lGauntlet = {
    slot = types.Actor.EQUIPMENT_SLOT.LeftGauntlet,
    ids = {
      "chitin guantlet - left",
    "imperial left gauntlet",
    "indoril left gauntlet",
    "netch_leather_gauntlet_left",
    "steel_gauntlet_left",
    "daedric_gauntlet_left",
    "fur_gauntlet_left",
    "iron_gauntlet_left",
    "left_horny_fist_gauntlet",
    "gauntlet_of_glory_left",
    "bm bear left gauntlet",
    "bm wolf left gauntlet",
    "steel_gauntlet_left_ancient",
    "bm_wolf_left_gauntlet_snow",
    "bm_bear_left_gauntlet_snow",
    "bm_nordicmail_gauntletl",
    "indoril_almalexia_gauntlet_l",
    "helsethguard_gauntlet_left",
    "darkbrotherhood gauntlet_l",
    "indoril_mh_guard_gauntlet_l",
    "t_com_steel_gauntletl_wonder",
    "t_dae_alternate_gauntletl_01",
    "t_dae_gold_gauntletl_01",
    "t_dae_uni_aurorangauntletl",
    "t_de_bonemoldsacred_gauntl_01",
    "t_de_bonemold_stone_gauntletl",
    "t_de_bonemold_ulvra_bracerl",
    "t_de_bonemold_water_bracerl",
    "t_de_dresbonemold_gauntletl_01",
    "t_de_narsiswatch_gauntletl_01",
    },
  },

  rGauntlet = {
    slot = types.Actor.EQUIPMENT_SLOT.RightGauntlet,
    ids = {
      "chitin guantlet - right",
    "imperial right gauntlet",
    "indoril right gauntlet",
    "netch_leather_gauntlet_right",
    "steel_gauntlet_right",
    "daedric_gauntlet_right",
    "fur_gauntlet_right",
    "iron_gauntlet_right",
    "gauntlet_of_glory_right",
    "bm bear right gauntlet",
    "bm wolf right gauntlet",
    "steel_gauntlet_right_ancient",
    "bm_wolf_right_gauntlet_snow",
    "bm_bear_right_gauntlet_snow",
    "bm_nordicmail_gauntletr",
    "indoril_almalexia_gauntlet_r",
    "helsethguard_gauntlet_right",
    "darkbrotherhood gauntlet_r",
    "indoril_mh_guard_gauntlet_r",
    "t_com_steel_gauntletr_wonder",
    "t_dae_alternate_gauntletr_01",
    "t_dae_gold_gauntletr_01",
    "t_dae_uni_aurorangauntletr",
    "t_dae_uni_gauntletofpoor_r",
    "t_de_bonemoldsacred_gauntr_01",
    "t_de_bonemold_stone_gauntletr",
    "t_de_bonemold_ulvra_bracerr",
    "t_de_bonemold_water_bracerr",
    "t_de_dresbonemold_gauntletr_01",
    "t_de_narsiswatch_gauntletr_01",
    },
  },

  lPauldron = {
    slot = types.Actor.EQUIPMENT_SLOT.LeftPauldron,
    ids = {
      "indoril pauldron left",
  "netch_leather_pauldron_left",
  "steel_pauldron_left",
  "chitin pauldron - left",
  "imperial left pauldron",
  "fur_pauldron_left",
  "orcish_pauldron_left",
  "iron_pauldron_left",
  "indoril_mh_guard_pauldron_l",
  "dwemer_pauldron_left",
  "imperial_chain_pauldron_left",
  "helsethguard_pauldron_left",
  "bm bear left pauldron",
  "glass_pauldron_left",
  "bm_nordicmail_pauldronl",
  "templar_pauldron_left",
  "darkbrotherhood pauldron_l",
  "ebony_pauldron_left",
  "bm wolf left pauldron",
  "indoril_almalexia_pauldron_l",
  "t_imp_coliron_pauldronl_01",
  "t_imp_studdedleather_pauldrl_01",
  "t_com_ironspike_pauldronl_01",
  "t_com_steel_pauldronl_01",
  "t_com_steel_pauldronl_02",
  "t_com_steel_pauldronl_03",
  "t_com_iron_pauldronl_01",
  "t_com_iron_pauldronl_02",
  "t_orc_leather_pauldronl_01",
  "t_qyc_shellmold_pauldl_01",
  "adamantium_pauldron_left",
  "t_dae_gold_pauldronl_01",
  "t_de_alithide_pauldronl_01",
  "t_de_chitin_pauldrl_01",
  "t_de_guarskin_pauldronl_01",
  "t_de_hvchit_pauldron_l",
  "t_imp_colsteel_pauldronl_01",
  "t_nor_bearskin_pauldronl_01",
  "t_nor_steel_pauldronl_01",
  "t_com_steelspike_pauldronl_01",
  "t_de_bonemoldsacred_pauldl_01",
  "t_de_dresbonemold_pauldronl_01",
  "t_de_dreugh_pauldronl_01",
  "t_de_indbonemold_pauldronl_01"
    },
  },

  rPauldron = {
    slot = types.Actor.EQUIPMENT_SLOT.RightPauldron,
    ids = {
      "indoril pauldron right",
    "steel_pauldron_right",
    "netch_leather_pauldron_right",
    "bonemold_pauldron_r",
    "bonemold_gah-julan_pauldron_r",
    "bonemold_armun-an_pauldron_r",
    "chitin pauldron - right",
    "imperial right pauldron",
    "iron_pauldron_right",
    "indoril_mh_guard_pauldron_r",
    "fur_pauldron_right",
    "orcish_pauldron_right",
    "dwemer_pauldron_right",
    "imperial_chain_pauldron_right",
    "helsethguard_pauldron_right",
    "glass_pauldron_right",
    "templar_pauldron_right",
    "bm bear right pauldron",
    "bm_nordicmail_pauldronr",
    "darkbrotherhood pauldron_r",
    "ebony_pauldron_right",
    "bm wolf right pauldron",
    "indoril_almalexia_pauldron_r",
    "t_imp_coliron_pauldronr_01",
    "t_com_steel_pauldronr_01",
    "t_com_steel_pauldronr_02",
    "t_com_steel_pauldronr_03",
    "adamantium_pauldron_right",
    "t_com_iron_pauldronr_01",
    "t_com_iron_pauldronr_02",
    "t_orc_leather_pauldronr_01",
    "t_qyc_shellmold_pauldr_01",
    "t_dae_gold_pauldronr_01",
    "t_de_alithide_pauldronr_01",
    "t_de_chitin_pauldrr_01",
    "t_de_guarskin_pauldronr_01",
    "t_de_hvchit_pauldron_r",
    "t_imp_colsteel_pauldronr_01",
    "t_nor_bearskin_pauldronr_01",
    "t_nor_leather1_pauldr_01",
    "t_nor_steel_pauldronr_01",
    "t_com_steelspike_pauldronr_01",
    "t_de_bonemoldkrage_pauldronr_01"
    },
  },

  ----------------------------------------------------------------------
  -- Clothing slots
  ----------------------------------------------------------------------
  pants = {
    slot = types.Actor.EQUIPMENT_SLOT.Pants,
    ids = {
      "common_pants_02",
    "common_pants_01",
    "common_pants_03",
    "common_pants_03_c",
    "common_pants_04",
    "common_pants_05",
    "expensive_pants_02",
    "expensive_pants_03",
    "expensive_pants_01",
    "extravagant_pants_01",
    "common_pants_03_b",
    "common_pants_04_b",
    "extravagant_pants_02",
    "common_pants_01_e",
    "common_pants_01_u",
    "expensive_pants_01_u",
    "expensive_pants_01_e",
    "exquisite_pants_01",
    "common_pants_01_a",
    "bm_wool01_pants",
    "common_pants_06",
    "bm_nordic02_pants",
    "bm_nordic01_pants",
    "bm_wool02_pants",
    "common_pants_07",
    "expensive_pants_mournhold",
    "t_imp_cm_pantscolwest_03",
    "expensive_pants_01_z",
    "t_com_cm_pants_02",
    "t_nor_ep_pants_01",
    "t_nor_cm_pants_01",
    "t_nor_cm_pants_02",
    "t_nor_cm_pants_04",
    "t_nor_cm_pants_03",
    "t_nor_cm_pants_06",
    "t_nor_cm_pants_05",
    "t_nor_cm_pants_08",
    "t_de_et_robe_01",
    "t_com_cm_pants_03",
    "t_com_cm_pants_04",
    "t_imp_cm_pantscolwest_01"
    },
  },

  shirt = {
    slot = types.Actor.EQUIPMENT_SLOT.Shirt,
    ids = {
      "common_shirt_02",
    "common_shirt_03",
    "common_shirt_04",
    "common_shirt_05",
    "expensive_shirt_01",
    "expensive_shirt_02",
    "expensive_shirt_03",
    "extravagant_shirt_01",
    "extravagant_shirt_02",
    "exquisite_shirt_01",
    "common_shirt_01",
    "common_shirt_02_h",
    "common_shirt_03_b",
    "common_shirt_01_z",
    "expensive_shirt_01_u",
    "expensive_shirt_01_a",
    "expensive_shirt_01_e",
    "extravagant_shirt_01_h",
    "extravagant_shirt_01_t",
    "common_shirt_04_b",
    "expensive_shirt_hair",
    "common_shirt_02_r",
    "exquisite_shirt_01_wedding",
    "common_shirt_03_c",
    "exquisite_shirt_01_rasha",
    "sarandas_shirt_2",
    "zenithar_frock",
    "caius_shirt",
    "restoration_shirt",
    "maras_blouse",
    "common_shirt_gondolier",
    "bm_nordic01_shirt",
    "bm_nordic02_shirt",
    "bm_wool01_shirt",
    "bm_wool02_shirt",
    "expensive_shirt_mournhold",
    "common_shirt_06",
    "common_shirt_07",
    "t_com_cm_shirt_01",
    "t_com_cm_shirt_02",
    "t_com_cm_shirt_03",
    "t_com_cm_shirt_04",
    "t_com_cm_shirt_resistparalysis",
    "t_com_ep_shirt_01",
    "t_com_ep_shirt_02",
    "t_com_ep_shirt_03",
    "t_com_ex_shirt_01",
    "t_com_ex_shirt_02",
    "t_com_ex_shirt_03",
    "t_de_cm_shirtdres_01",
    "t_de_cm_shirtdres_02",
    "t_de_cm_shirtdres_03",
    "t_de_cm_shirtind_02",
    "t_de_cm_shirtind_03",
    "t_de_cm_shirttelv_01",
    "t_de_cm_shirt_01",
    "t_de_cm_shirt_02",
    "t_de_cm_shirt_03",
    "t_de_cm_shirt_04",
    "t_de_cm_shirt_05",
    "t_de_cm_shirt_06",
    "t_de_cm_shirt_07",
    "t_de_cm_shirt_08",
    "t_de_cm_shirt_09",
    "t_de_cm_shirt_10",
    "t_de_cm_shirt_11",
    "t_de_cm_shirt_12",
    "t_de_cm_shirt_13",
    "t_de_cm_shirt_14",
    "t_de_cm_shirt_15",
    "t_de_cm_shirt_16",
    "t_de_cm_shirt_17",
    "t_de_ep_shirtshin_01",
    "t_de_ep_shirtshin_02",
    "t_de_ep_shirt_01",
    "t_de_ep_shirt_02",
    "t_de_ep_shirt_03",
    "t_de_ep_shirt_04",
    "t_de_ep_shirt_05",
    "t_de_et_shirtdres_01",
    "t_de_et_shirtdres_02",
    "t_de_et_shirtind_01",
    "t_de_et_shirtind_02",
    "t_de_et_shirt_01",
    "t_de_et_shirt_02",
    "t_de_et_shirt_03",
    "t_de_et_shirt_04",
    "t_de_et_shirt_05",
    "t_de_et_shirt_06",
    "t_de_et_shirt_07",
    "t_de_et_shirt_08",
    "t_de_et_shirt_09",
    "t_de_et_shirt_10",
    "t_de_ex_shirthla_03",
    "t_de_ex_shirthla_04",
    "t_de_ex_shirthla_05",
    "t_de_ex_shirthla_06",
    "t_de_ex_shirthla_07",
    "t_de_ex_shirthla_08",
    "t_de_ex_shirt_01",
    "t_de_ex_shirt_02",
    "t_imp_cm_shirtcolwest_01",
    "t_imp_cm_shirtcolwest_02",
    "t_imp_cm_shirtcolwest_03",
    "t_imp_cm_shirtcolwest_04",
    "t_imp_cm_shirtcolwest_05",
    "t_imp_cm_shirtcolwest_06",
    "t_imp_cm_shirtcolwest_07",
    "t_imp_cm_shirtcolwest_08",
    "t_imp_cm_shirtcolwest_09",
    "t_imp_ep_shirtcolwest_01",
    "t_imp_ep_shirtcolwest_02",
    "t_imp_ep_shirtcolwest_03",
    "t_imp_ep_shirtcolwest_04",
    "t_imp_ep_shirtcolwest_05",
    "t_imp_et_shirtcolwest_01",
    "t_imp_et_shirtcolwest_02",
    "t_imp_et_shirtcolwest_03",
    "t_imp_et_shirtcolwest_04",
    "t_imp_et_shirtcolwest_05",
    "t_imp_et_shirtcolwest_06",
    "t_nor_cm_shirt_01",
    "t_nor_cm_shirt_02",
    "t_nor_cm_shirt_03",
    "t_nor_cm_shirt_04",
    "t_nor_ep_shirt_01",
    "t_nor_ep_shirt_02",
    "t_nor_ep_shirt_03",
    "t_nor_ep_shirt_04",
    "t_nor_et_shirt_01",
    "t_nor_et_shirt_02",
    "t_rea_cm_shirt_01",
    "t_rea_cm_shirt_02",
    "t_rea_cm_shirt_03",
    "t_rea_cm_shirt_04",
    "t_rea_cm_shirt_05",
    "t_rea_cm_shirt_06",
    "t_rea_cm_shirt_07",
    "t_rea_cm_shirt_horsehair",
    "t_rea_uni_wingsoffedelmid",
    "t_rga_ep_shirt_01",
    "t_rga_ep_shirt_02",
    "t_rga_ep_shirt_03",
    "t_rga_ep_shirt_04",
    "t_we_cm_dress_01",
    "t_we_cm_dress_02",
    "t_we_cm_dress_03",
    "t_we_ep_dress_01",
    "ab_c_commonshirt02b",
    },
  },

  skirt = {
    slot = types.Actor.EQUIPMENT_SLOT.Skirt,
    ids = {
      "common_skirt_02",
    "common_skirt_03",
    "common_skirt_04",
    "common_skirt_05",
    "expensive_skirt_01",
    "expensive_skirt_02",
    "expensive_skirt_03",
    "extravagant_skirt_01",
    "extravagant_skirt_02",
    "exquisite_skirt_01",
    "common_skirt_01",
    "common_skirt_04_c",
    "common_skirt_06",
    "common_skirt_07",
    "t_com_ep_skirt_01",
    "t_com_ep_skirt_02",
    "t_com_ep_skirt_03",
    "t_com_ep_skirt_04",
    "t_com_ep_skirt_05",
    "t_com_et_skirt_01",
    "t_com_et_skirt_02",
    "t_com_ex_skirt_01",
    "t_com_ex_skirt_02",
    },
  },
}

return ITEM_LISTS
