return {
 ["ingred_alit_hide_01"             ]  =  {  box ="ss_a_alithide"             , box2 ="rrfm_z_alithide"                   },     
 ["ingred_amethyst_sa"              ]  =  {  box ="ss_a_amethyst"             , box2 ="rrfm_z_amethyst"                   },
 ["ingred_bc_ampoule_pod"           ]  =  {  box ="ss_a_ampoule"              , box2 ="rrfm_z_ampoule"                    },
 ["ingred_ash_salts_01"             ]  =  {  box ="ss_a_ashsalt"              , box2 ="rrfm_z_ashsalt"                    },
 ["ingred_ash_yam_01"               ]  =  {  box ="ss_a_ashyam"               , box2 ="rrfm_z_ashyam"                     },
 ["ingred_ash_proboscis_sa"         ]  =  {  box ="ss_a_ashtentacle"          , box2 ="rrfm_z_ashtentacle"                },
 ["ingred_bear_fat_sa"              ]  =  {  box ="ss_a_bearfat"              , box2 ="rrfm_z_bearfat"                    },
 ["ingred_bear_meat_sa"             ]  =  {  box ="ss_a_bearmeat"             , box2 ="rrfm_z_bearmeat"                   },
 ["ingred_bear_pelt"                ]  =  {  box ="ss_a_bearpelt"             , box2 ="rrfm_z_bearpelt"                   },
 ["ingred_bittergreen_petals_01"    ]  =  {  box ="ss_a_bittergreen"          , box2 ="rrfm_z_bittergreen"                },
 ["ingred_black_anther_01"          ]  =  {  box ="ss_a_blackanther"          , box2 ="rrfm_z_blackanther"                },
 ["ingred_black_lichen_01"          ]  =  {  box ="ss_a_blacklichen"          , box2 ="rrfm_z_blacklichen"                },
 ["ingred_mycena_cap_st"            ]  =  {  box ="ss_a_bleedingmycena"       , box2 ="rrfm_z_bleedingmycena"             },
 ["ingred_blightcap_st"             ]  =  {  box ="ss_a_blightcap"            , box2 ="rrfm_z_blightcap"                  },
 ["ingred_bloat_01"                 ]  =  {  box ="ss_a_bloat"                , box2 ="rrfm_z_bloat"                      },
 ["ingred_dunmer_bone_sa"           ]  =  {  box ="ss_a_bone"                 , box2 ="rrfm_z_bone"                       },
 ["ingred_bonemeal_01"              ]  =  {  box ="ss_a_bonemeal"             , box2 ="rrfm_z_bonemeal"                   },
 ["ingred_bread_01"                 ]  =  {  box ="ss_a_bread"                , box2 ="rrfm_z_bread"                      },
 ["ingred_boar_leather"             ]  =  {  box ="ss_a_bristlebackleather"   , box2 ="rrfm_z_bristbackleather"           },
 ["ingred_bc_bungler's_bane"        ]  =  {  box ="ss_a_bunglers"             , box2 ="rrfm_z_bunglers"                   },
 ["ingred_charcoal_st"              ]  =  {  box ="ss_a_charcoal"             , box2 ="rrfm_z_charcoal"                   },
 ["ingred_chokeweed_01"             ]  =  {  box ="ss_a_chokeweed"            , box2 ="rrfm_z_chokeweed"                  },
 ["ingred_clannfear_scales_sa"      ]  =  {  box ="ss_a_clannfearscales"      , box2 ="rrfm_z_clannfearscales"            },
 ["ingred_coal_st"                  ]  =  {  box ="ss_a_coal"                 , box2 ="rrfm_z_coal"                       },
 ["ingred_bc_coda_flower"           ]  =  {  box ="ss_a_codaflower"           , box2 ="rrfm_z_codaflower"                 },
 ["ingred_comberry_01"              ]  =  {  box ="ss_a_comberry"             , box2 ="rrfm_z_comberry"                   },
 ["ingred_corkbulb_root_01"         ]  =  {  box ="ss_a_corkbulb"             , box2 ="rrfm_z_corkbulb"                   },
 ["ingred_6th_corprusmeat_01"       ]  =  {  box ="ss_a_corprusmeat"          , box2 ="rrfm_z_corprusmeat"                },
 ["ingred_6th_corprusmeat_02"       ]  =  {  box ="ss_a_corprusmeat"          , box2 ="rrfm_z_corprusmeat"                },
 ["ingred_6th_corprusmeat_03"       ]  =  {  box ="ss_a_corprusmeat"          , box2 ="rrfm_z_corprusmeat"                },
 ["ingred_6th_corprusmeat_04"       ]  =  {  box ="ss_a_corprusmeat"          , box2 ="rrfm_z_corprusmeat"                },
 ["ingred_6th_corprusmeat_05"       ]  =  {  box ="ss_a_corprusmeat"          , box2 ="rrfm_z_corprusmeat"                },
 ["ingred_6th_corprusmeat_06"       ]  =  {  box ="ss_a_corprusmeat"          , box2 ="rrfm_z_corprusmeat"                },
 ["ingred_6th_corprusmeat_07"       ]  =  {  box ="ss_a_corprusmeat"          , box2 ="rrfm_z_corprusmeat"                },
 ["ingred_corprus_weepings_01"      ]  =  {  box ="ss_a_corpus_w"             , box2 ="rrfm_z_corpus_w"                   },
 ["ingred_crab_meat_01"             ]  =  {  box ="ss_a_crabmeat"             , box2 ="rrfm_z_crabmeat"                   },
 ["ingred_daedras_heart_01"         ]  =  {  box ="ss_a_daedraheart"          , box2 ="rrfm_z_daedraheart"                },
 ["ingred_daedra_skin_01"           ]  =  {  box ="ss_a_daedraskin"           , box2 ="rrfm_z_daedraskin"                 },
 ["ingred_daedroth_claw_sa"         ]  =  {  box ="ss_a_daedrothclaw"         , box2 ="rrfm_z_daedrothclaw"               },
 ["ingred_diamond_01"               ]  =  {  box ="ss_a_diamond"              , box2 ="rrfm_z_diamond"                    },
 ["ingred_dreugh_wax_01"            ]  =  {  box ="ss_a_dreughwax"            , box2 ="rrfm_z_dreughwax"                  },
 ["ingred_durzog_meat_01"           ]  =  {  box ="ss_a_durzog"               , box2 ="rrfm_z_durzog"                     }, 
 ["ingred_dwemer_grease_sa"         ]  =  {  box ="ss_a_dwemergrease"         , box2 ="rrfm_z_dwemergrease"               },
 ["ingred_dwemer_pipe_sa"           ]  =  {  box ="ss_a_dwemerpipe"           , box2 ="rrfm_z_dwemerpipe"                 },
 ["ingred_ectoplasm_01"             ]  =  {  box ="ss_a_ectoplasm"            , box2 ="rrfm_z_ectoplasm"                  },
 ["ingred_emerald_01"               ]  =  {  box ="ss_a_emeralds"             , box2 ="rrfm_z_emerald"                    },
 ["ingred_fire_petal_01"            ]  =  {  box ="ss_a_firepetal"            , box2 ="rrfm_z_firepetal"                  },
 ["ingred_fire_salts_01"            ]  =  {  box ="ss_a_firesalt"             , box2 ="rrfm_z_firesalts"                  },
 ["ingred_frost_salts_01"           ]  =  {  box ="ss_a_frostsalt"            , box2 ="rrfm_z_frostsalts"                 },
 ["ingred_frostspore_st"            ]  =  {  box ="ss_a_frostspore"           , box2 ="rrfm_z_frostspore"                 },
 ["ingred_ghoul_heart_01"           ]  =  {  box ="ss_a_ghoulheart"           , box2 ="rrfm_z_ghoulheart"                 },
 ["ingred_golden_sedge_01"          ]  =  {  box ="ss_a_goldensedge"          , box2 ="rrfm_z_goldensedge"                },
 ["ingred_gold_kanet_01"            ]  =  {  box ="ss_a_goldkanet"            , box2 ="rrfm_z_goldkanet"                  },
 ["ingred_goldnugget_sa"            ]  =  {  box ="ss_a_goldnugget"           , box2 ="rrfm_z_goldnugget"                 },
 ["ingred_gravedust_01"             ]  =  {  box ="ss_a_gravedust"            , box2 ="rrfm_z_gravedust"                  },
 ["ingred_gravetar_01"              ]  =  {  box ="ss_a_gravetar"             , box2 ="rrfm_z_gravetar"                   }, 
 ["ingred_green_lichen_01"          ]  =  {  box ="ss_a_greenlichen"          , box2 ="rrfm_z_greenlichen"                },
 ["ingred_guar_hide_01"             ]  =  {  box ="ss_a_guarhide"             , box2 ="rrfm_z_guarhide"                   },
 ["ingred_hackle-lo_leaf_01"        ]  =  {  box ="ss_a_hacklo"               , box2 ="rrfm_z_hacklelo"                   },
 ["ingred_heather_01"               ]  =  {  box ="ss_a_heather"              , box2 ="rrfm_z_heather"                    },
 ["ingred_holly_01"                 ]  =  {  box ="ss_a_hollyberries"         , box2 ="rrfm_z_hollyberries"               },
 ["tm_honeycomb"                    ]  =  {  box ="ss_a_honeycomb"            , box2 ="rrfm_z_honeycomb"                  },
 ["ingred_horker_tusk_01"           ]  =  {  box ="ss_a_horkertusk"           , box2 ="rrfm_z_horkertusk"                 },
 ["ingred_horn_lily_bulb_01"        ]  =  {  box ="ss_a_hornlilybulb"         , box2 ="rrfm_z_hornlilybulb"               },
 ["ingred_hound_meat_01"            ]  =  {  box ="ss_a_houndmeat"            , box2 ="rrfm_z_houndmeat"                  },
 ["ingred_hunger_tongue_sa"         ]  =  {  box ="ss_a_hungertongue"         , box2 ="rrfm_z_hungertongue"               },
 ["ingred_bc_hypha_facia"           ]  =  {  box ="ss_a_hyphafacia"           , box2 ="rrfm_z_hyphafacia"                 },
 ["ingred_kagouti_hide_01"          ]  =  {  box ="ss_a_kagouti"              , box2 ="rrfm_z_kagouti"                    },
 ["ingred_kelp_st"                  ]  =  {  box ="ss_a_kelp"                 , box2 ="rrfm_z_kelp"                       },
 ["ingred_kollop_meat_st"           ]  =  {  box ="ss_a_kollopmeat"           , box2 ="rrfm_z_kollopmeat"                 },
 ["ingred_kresh_fiber_01"           ]  =  {  box ="ss_a_kreshfiber"           , box2 ="rrfm_z_kreshfiber"                 },
 ["ingred_kwama_cuttle_01"          ]  =  {  box ="ss_a_kwamacuttle"          , box2 ="rrfm_z_kwamacuttle"                },
 ["food_kwama_egg_01"               ]  =  {  box ="ss_a_kwamaeggs"            , box2 ="rrfm_z_kwamaeggs"                  },
 ["food_kwama_egg_02"               ]  =  {  box ="ss_a_kwamaeggs"            , box2 ="rrfm_z_kwamaeggs"                  },
 ["ingred_lead_st"                  ]  =  {  box ="ss_a_lead"                 , box2 ="rrfm_z_lead"                       },
 ["ingred_lich_dust_sa"             ]  =  {  box ="ss_a_lichdust"             , box2 ="rrfm_z_lichdust"                   },
 ["ingred_lloramor_spines_01"       ]  =  {  box ="ss_a_lloramorspines"       , box2 ="rrfm_z_lloramorspines"             },
 ["ingred_marshmerrow_01"           ]  =  {  box ="ss_a_marshmerrow"          , box2 ="rrfm_z_marshmerrow"                },
 ["ingred_meadow_rye_01"            ]  =  {  box ="ss_a_meadowrye"            , box2 ="rrfm_z_meadowrye"                  },
 ["ingred_moon_sugar_01"            ]  =  {  box ="ss_a_moonsugar"            , box2 ="rrfm_z_moonsugar"                  },
 ["ingred_moss_st"                  ]  =  {  box ="ss_a_moss"                 , box2 ="rrfm_z_moss"                       },
 ["ingred_muck_01"                  ]  =  {  box ="ss_a_muck"                 , box2 ="rrfm_z_muck"                       },
 ["ingred_bread_01_uni3"            ]  =  {  box ="ss_a_muffin"               , box2 ="rrfm_z_muffin"                     },
 ["ingred_namira_cap_st"            ]  =  {  box ="ss_a_namirasrot"           , box2 ="rrfm_z_namirarot"                  },
 ["ingred_netchjelly_st"            ]  =  {  box ="ss_a_netchjelly"           , box2 ="rrfm_z_netchjelly"                 },
 ["ingred_netch_leather_01"         ]  =  {  box ="ss_a_netchleather"         , box2 ="rrfm_z_netchleather"               },
 ["ingred_nirthfly_stalks_01"       ]  =  {  box ="ss_a_nirthflystalks"       , box2 ="rrfm_z_nirthflystalks"             },
 ["ingred_noble_sedge_01"           ]  =  {  box ="ss_a_noblesedgeflower"     , box2 ="rrfm_z_noblesedgeflower"           },
 ["ingred_nocturnal_crepidotus_st"  ]  =  {  box ="ss_a_nocturnalcrepidotus"  , box2 ="rrfm_z_nocturnalcrepid"            },
 ["ingred_ogrim_flesh_sa"           ]  =  {  box ="ss_a_ogrimflesh"           , box2 ="rrfm_z_ogrimflesh"                 },
 ["ingred_opal_sa"                  ]  =  {  box ="ss_a_opal"                 , box2 ="rrfm_z_opal"                       },
 ["ingred_pearl_01"                 ]  =  {  box ="ss_a_pearl"                , box2 ="rrfm_z_pearl"                      },
 ["poison_goop00"                   ]  =  {  box ="ss_a_poison"               , box2 ="rrfm_z_poison"                     },
 ["ingred_racer_plumes_01"          ]  =  {  box ="ss_a_racerplume"           , box2 ="rrfm_z_racerplume"                 },
 ["ingred_rat_meat_01"              ]  =  {  box ="ss_a_ratmeat"              , box2 ="rrfm_z_ratmeat"                    },
 ["ingred_raw_ebony_01"             ]  =  {  box ="ss_a_rawebony"             , box2 ="rrfm_z_rawebony"                   },
 ["ingred_raw_glass_01"             ]  =  {  box ="ss_a_rawglass"             , box2 ="rrfm_z_rawglass"                   },
 ["ingred_silvernugget_st"          ]  =  {  box ="ss_a_rawsilver"            , box2 ="rrfm_z_rawsilver"                  },
 ["ingred_red_lichen_01"            ]  =  {  box ="ss_a_redlichen"            , box2 ="rrfm_z_redlichen"                  },
 ["ingred_resin_01"                 ]  =  {  box ="ss_a_resin"                , box2 ="rrfm_z_resin"                      },
 ["ingred_belladonna_01"            ]  =  {  box ="ss_a_ripebelladonna"       , box2 ="rrfm_z_ripebelladonna"             },
 ["ingred_roobrush_01"              ]  =  {  box ="ss_a_roobush"              , box2 ="rrfm_z_roobush"                    },
 ["ingred_ruby_01"                  ]  =  {  box ="ss_a_ruby"                 , box2 ="rrfm_z_ruby"                       },
 ["ingred_russula_01"               ]  =  {  box ="ss_a_russula"              , box2 ="rrfm_z_luminrussula"               },
 ["ingred_saltrice_01"              ]  =  {  box ="ss_a_saltrice"             , box2 ="rrfm_z_saltrice"                   },
 ["ingred_sapphire_sa"              ]  =  {  box ="ss_a_sapphire"             , box2 ="rrfm_z_sapphire"                   },
 ["ingred_scales_01"                ]  =  {  box ="ss_a_scales"               , box2 ="rrfm_z_scales"                     },
 ["ingred_scamp_skin_01"            ]  =  {  box ="ss_a_scampskin"            , box2 ="rrfm_z_scampskin"                  },
 ["ingred_scrap_metal_01"           ]  =  {  box ="ss_a_scrapmetal"           , box2 ="rrfm_z_scrapmetal"                 },
 ["ingred_scathecraw_01"            ]  =  {  box ="ss_a_scathecraw"           , box2 ="rrfm_z_scathecraw"                 },
 ["ingred_scrib_jelly_01"           ]  =  {  box ="ss_a_scribjelly"           , box2 ="rrfm_z_scribjelly"                 },
 ["ingred_scrib_jerky_01"           ]  =  {  box ="ss_a_scribjerky"           , box2 ="rrfm_z_scribjerky"                 },
 ["ingred_scrib_cabbage_01"         ]  =  {  box ="ss_a_scribcabbage"         , box2 ="rrfm_z_scribcabbage"               },
 ["ingred_scuttle_01"               ]  =  {  box ="ss_a_scuttle"              , box2 ="rrfm_z_scuttle"                    },
 ["ingred_shalk_resin_01"           ]  =  {  box ="ss_a_shalkresin"           , box2 ="rrfm_z_shalkresin"                 },
 ["ingred_fishegg_st"               ]  =  {  box ="ss_a_slaughterfishegg"     , box2 ="rrfm_z_slaughterfishegg"           },
 ["ingred_salt_fish_sa"             ]  =  {  box ="ss_a_slaughterfishfillet"  , box2 ="rrfm_z_saltslaughtfish"            },
 ["ingred_sload_soap_01"            ]  =  {  box ="ss_a_sloadsoap"            , box2 ="rrfm_z_sloadsoap"                  },
 ["ingred_snowbear_pelt_unique"     ]  =  {  box ="ss_a_snowbearpelt"         , box2 ="rrfm_z_snowbearpelt"               },
 ["ingred_snowwolf_pelt_unique"     ]  =  {  box ="ss_a_snowwolfpelt"         , box2 ="rrfm_z_snowwolfpelt"               },
 ["ingred_spidersilk_st"            ]  =  {  box ="ss_a_spidersilk"           , box2 ="rrfm_z_spidersilk"                 },
 ["ingred_bc_spore_pod"             ]  =  {  box ="ss_a_sporepod"             , box2 ="rrfm_z_sporepod"                   },
 ["ingred_stoneflower_petals_01"    ]  =  {  box ="ss_a_stoneflower"          , box2 ="rrfm_z_stoneflower"                },
 ["ingred_sweetpulp_01"             ]  =  {  box ="ss_a_sweetpulp"            , box2 ="rrfm_z_sweetpulp"                  },  
 ["ingred_timsa-come-by_01"         ]  =  {  box ="ss_a_timsa-come-by"        , box2 ="rrfm_z_timsacomeby"                },
 ["ingred_trama_root_01"            ]  =  {  box ="ss_a_tramaroot"            , box2 ="rrfm_z_tramaroot"                  },
 ["ingred_feather_sa"               ]  =  {  box ="ss_a_twilightfeather"      , box2 ="rrfm_z_twilightfeather"            },
 ["ingred_belladonna_02"            ]  =  {  box ="ss_a_unripebelladona"      , box2 ="rrfm_z_unripebelladona"            },
 ["ingred_vampire_dust_01"          ]  =  {  box ="ss_a_vampiredust"          , box2 ="rrfm_z_vampiredust"                },
 ["ingred_coprinus_01"              ]  =  {  box ="ss_a_violetcoprinus"       , box2 ="rrfm_z_violetcoprinus"             },
 ["ingred_void_salts_01"            ]  =  {  box ="ss_a_voidsalts"            , box2 ="rrfm_z_voidsalts"                  },
 ["ingred_wickwheat_01"             ]  =  {  box ="ss_a_wickwheat"            , box2 ="rrfm_z_wickwheat"                  },
 ["ingred_willow_anther_01"         ]  =  {  box ="ss_a_willowanther"         , box2 ="rrfm_z_willowanther"               },
 ["ingred_wolf_jaw_st"              ]  =  {  box ="ss_a_wolfmandible"         , box2 ="rrfm_z_wolfmandible"               },
 ["ingred_wolf_meat_sa"             ]  =  {  box ="ss_a_wolfmeat"             , box2 ="rrfm_z_wolfmeat"                   },
 ["ingred_wolf_pelt"                ]  =  {  box ="ss_a_wolfpelt"             , box2 ="rrfm_z_wolfpelt"                   },
 ["ingred_wolf_ribs_sa"             ]  =  {  box ="ss_a_wolfribs"             , box2 ="rrfm_z_wolfribs"                   },
 ["ingred_wolfsbane_01"             ]  =  {  box ="ss_a_wolfsbanepetals"      , box2 ="rrfm_z_wolfsbanepetals"            },
 --  
 ["ab_ingmine_amber_01"             ]  =  {  box ="ss_a_o_amber"              , box2 = "rrfm_z_amber"                   },
 ["ab_ingflor_bgslime_01"           ]  =  {  box ="ss_a_o_bittergreenslime"   , box2 = "rrfm_z_bittergreenslime"        },
 ["ab_ingmine_blackpearl_01"        ]  =  {  box ="ss_a_o_blackpearl"         , box2 = "rrfm_z_blackpearl"              },
 ["ab_ingmine_blacktourmaline_01"   ]  =  {  box ="ss_a_o_blacktourmaline"    , box2 = "rrfm_z_blacktourmaline"         },
 ["ab_ingcrea_kwamaeggblighted"     ]  =  {  box ="ss_a_o_blightedkwamaegg"   , box2 = "rrfm_z_blightedkwamaegg"        },
 ["ab_ingflor_fomentarius"          ]  =  {  box ="ss_a_o_blisteringfoment"   , box2 = "rrfm_z_blisteringfomen"         },
 ["ab_ingflor_bloodgrass_01"        ]  =  {  box ="ss_a_o_bloodgrass"         , box2 = "rrfm_z_bloodgrass"              },
 ["ab_ingmine_bluediamond"          ]  =  {  box ="ss_a_o_bluediamond"        , box2 = "rrfm_z_bluediamond"             },
 ["ab_ingflor_bluekanet_01"         ]  =  {  box ="ss_a_o_bluekanet"          , box2 = "rrfm_z_bluekanet"               },
 ["ab_ingfood_kwamaeggcentcut"      ]  =  {  box ="ss_a_o_centurykwamaegg"    , box2 = "rrfm_z_centurykwamaegg"         },
 ["ab_ingflor_cindersparklichen_01" ]  =  {  box ="ss_a_o_cindersparklichen"  , box2 = "rrfm_z_cindsparklichen"         },
 ["ab_ingcrea_clannclaw_01"         ]  =  {  box ="ss_a_o_clannfearclaw"      , box2 = "rrfm_z_clannfearclaw"           },
 ["ab_ingcrea_daeteeth_01"          ]  =  {  box ="ss_a_o_daedrothteeth"      , box2 = "rrfm_z_daedrothteeth"           },
 ["ab_ingfood_doughlump"            ]  =  {  box ="ss_a_o_dough"              , box2 = "rrfm_z_dough"                   },
 ["ab_ingcrea_dreughshell_01"       ]  =  {  box ="ss_a_o_dreughshell"        , box2 = "rrfm_z_dreughshell"             },
 ["ab_ingflor_dustcap"              ]  =  {  box ="ss_a_o_dustcap"            , box2 = "rrfm_z_dustcap"                 },
 ["ab_ingmine_firejade_01"          ]  =  {  box ="ss_a_o_firejade"           , box2 = "rrfm_z_firejade"                },
 ["ab_ingmine_garnet_01"            ]  =  {  box ="ss_a_o_garnet"             , box2 = "rrfm_z_garnet"                  },
 ["ab_ingflor_glmuscaria_01"        ]  =  {  box ="ss_a_o_glowingmuscaria"    , box2 = "rrfm_z_glowingmuscaria"         },
 ["ab_ingmine_goldpearl_01"         ]  =  {  box ="ss_a_o_goldenpearl"        , box2 = "rrfm_z_goldenpearl"             },
 ["ab_ingfood_kwamaloaf"            ]  =  {  box ="ss_a_o_goros"              , box2 = "rrfm_z_goros"                   },
 ["ab_ingcrea_guarmeat_01"          ]  =  {  box ="ss_a_o_guarmeat"           , box2 = "rrfm_z_guarmeat"                },
 ["ab_ingflor_harrada_01"           ]  =  {  box ="ss_a_o_harrada"            , box2 = "rrfm_z_harrada"                 },
 ["ab_ingcrea_horsemeat01"          ]  =  {  box ="ss_a_o_horsemeat"          , box2 = "rrfm_z_horsemeat"               },
 ["ab_ingcrea_kwamapoison"          ]  =  {  box ="ss_a_o_kwamapoison"        , box2 = "rrfm_z_kwamapoison"             },
 ["ab_ingmine_obsidian_01"          ]  =  {  box ="ss_a_o_obsidian"           , box2 = "rrfm_z_obsidian"                },
 ["ab_ingmine_peridot_01"           ]  =  {  box ="ss_a_o_peridot"            , box2 = "rrfm_z_peridot"                 },
 ["ab_ingmine_reddiamond"           ]  =  {  box ="ss_a_o_reddiamond"         , box2 = "rrfm_z_reddiamond"              },
 ["ab_ingfood_saltricebread"        ]  =  {  box ="ss_a_o_saltricebread"      , box2 = "rrfm_z_saltricebread"           },
 ["ab_ingcrea_scribshell_01"        ]  =  {  box ="ss_a_o_scribshell"         , box2 = "rrfm_z_scribshell"              },
 ["ab_ingcrea_sfmeat_01"            ]  =  {  box ="ss_a_o_slaughterfishmeat"  , box2 = "rrfm_z_saltslaughtfish"         },
 ["ab_ingcrea_spidervenom"          ]  =  {  box ="ss_a_o_spidervenom"        , box2 = "rrfm_z_spidervenom"             },
 ["ab_ingmine_diopside_01"          ]  =  {  box ="ss_a_o_stardiopside"       , box2 = "rrfm_z_stardiopside"            },
 ["ab_ingmine_sulphur"              ]  =  {  box ="ss_a_o_sulphur"            , box2 = "rrfm_z_sulphur"                 },
 ["ab_ingfood_sweetroll"            ]  =  {  box ="ss_a_o_sweetroll"          , box2 = "rrfm_z_sweetroll"               },
 ["ab_ingflor_telvanniresin"        ]  =  {  box ="ss_a_o_telvanniresin"      , box2 = "rrfm_z_telvanniresin"           },
 ["ab_ingmine_topaz_01"             ]  =  {  box ="ss_a_o_topaz"              , box2 = "rrfm_z_topaz"                   },
 ["ab_ingmine_tourmaline_01"        ]  =  {  box ="ss_a_o_tourmaline"         , box2 = "rrfm_z_tourmaline"              },
 ["ab_ingflor_urnula"               ]  =  {  box ="ss_a_o_veiledurnulacap"    , box2 = "rrfm_z_veiledurnulacap"         },
 ["ab_ingflor_vimuscaria_01"        ]  =  {  box ="ss_a_o_viciousmuscaria"    , box2 = "rrfm_z_viciousmuscaria"         },
 ["ab_ingcrea_twilightmembrane"     ]  =  {  box ="ss_a_o_wingedtwilightm"    , box2 = "rrfm_z_wingtwilightmem"         },
 -- morrowind crafting                                                                      
 ["mc_iron_ore"                     ]  =  {  box ="ss_a_mc_chunkofironore"    , box2 = "rrfm_z_chunk_ironore"          },
 ["mc_silver_ore"                   ]  =  {  box ="ss_a_mc_chunkofsilverore"  , box2 = "rrfm_z_chunk_silverore"        },
 ["mc_daedric_ebony"                ]  =  {  box ="ss_a_mc_daedricebony"      , box2 = "rrfm_z_daedric_ebony"          },
 ["mc_dreugh_hide"                  ]  =  {  box ="ss_a_mc_dreughhide"        , box2 = "rrfm_z_dreughhide"             },
 ["mc_fish_bladder"                 ]  =  {  box ="ss_a_mc_fishbladder"       , box2 = "rrfm_z_fishbladder"            },
 ["mc_garlic"                       ]  =  {  box ="ss_a_mc_garlic"            , box2 = "rrfm_z_garlic"                 },
 ["mc_horker_blubber"               ]  =  {  box ="ss_a_mc_horkerblubber"     , box2 = "rrfm_z_horkerblubber"          },
 ["mc_kagouti_raw"                  ]  =  {  box ="ss_a_mc_kanetbutter"       , box2 = "rrfm_z_kanet_butter"           },
 ["mc_netch_acid"                   ]  =  {  box ="ss_a_mc_netchacid"         , box2 = "rrfm_z_netchacid"              },
 ["mc_onion"                        ]  =  {  box ="ss_a_mc_onion"             , box2 = "rrfm_z_onion"                  },
 ["mc_potato_raw"                   ]  =  {  box ="ss_a_mc_raw potato"        , box2 = "rrfm_z_potato"                 },
 ["mc_racer_raw"                    ]  =  {  box ="ss_a_mc_rawcliffrace"      , box2 = "rrfm_z_racermeat"              },
 ["mc_guar_raw"                     ]  =  {  box ="ss_a_mc_rawguar"           , box2 = "rrfm_z_guarmeat"               },
 ["mc_kagouti_raw"                  ]  =  {  box ="ss_a_mc_rawkagouti"        , box2 = "rrfm_z_kagoutiraw"             },
 ["mc_riceflour"                    ]  =  {  box ="ss_a_mc_riceflour"         , box2 = "rrfm_z_riceflour"              },
 ["mc_ryeflour"                     ]  =  {  box ="ss_a_mc_ryeflour"          , box2 = "rrfm_z_ryeflour"               },
 ["mc_sausagepod"                   ]  =  {  box ="ss_a_mc_sausagepod"        , box2 = "rrfm_z_sausagepod"             },
 ["mc_sugar"                        ]  =  {  box ="ss_a_mc_sugar"             , box2 = "rrfm_z_sugar"                  },
 ["mc_starch"                       ]  =  {  box ="ss_a_mc_vegetablestarch"   , box2 = "rrfm_z_vegstarch"              },
 ["mc_wheatflour"                   ]  =  {  box ="ss_a_mc_wheatflour"        , box2 = "rrfm_z_wheatflour"             },
--- missing boxes                                                                           
 ["ingred_heartwood_01"            	]  =  {  box = "ss_a_heartwood"           , box2 = "rrfm_z_heartwood"              }, 
 ["ingred_human_meat_01"	          ]  =  {  box = "ss_a_humanflesh"          , box2 = "rrfm_z_humanflesh"             }, 
 ["ingred_raw_stalhrim_01"	        ]  =  {  box = "ss_a_rawstalhrim"         , box2 = "rrfm_z_rawstalhrim"            },    
 ["ingred_eyeball"                  ]  =  {  box = "ss_a_grahleyeball"        , box2 = "rrfm_z_grahleyeball"           },  
}

 
 
