local core = require("openmw.core")
local T = require("openmw.types")

local mT = require("scripts.fresh-loot.config.types")

local Attributes = core.stats.Attribute.records
local Skills = core.stats.Skill.records
local EffectTypes = core.magic.EFFECT_TYPE
local EnchantTypes = core.magic.ENCHANTMENT_TYPE
local RangeTypes = core.magic.RANGE

return {
    {
        id = "burden-self-touch-onUse",
        affixType = mT.affixes.Prefix,
        value = 25,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 300, 400, 500, 600 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 100, 200, 300, 400 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
    {
        id = "drainSpeed-self-touch-onUse",
        affixType = mT.affixes.Prefix,
        value = 25,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 10, 20, 30, 40 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
    {
        id = "blind-self-touch-onUse",
        affixType = mT.affixes.Prefix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
    {
        id = "fortifySpeed-sanctuary-blind-sound-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { false, 10, 15, 20, 25 },
                max = { false, 15, 20, 25, 30 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { false, 40, 50, 60, 70 },
                max = { false, 50, 60, 70, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Sound,
                range = RangeTypes.Self,
                min = { false, 25, 30, 35, 40 },
                max = { false, 35, 40, 45, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
    {
        id = "fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
    {
        id = "levitate-light-fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 100,
        effects = {
            {
                id = EffectTypes.Levitate,
                range = RangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Light,
                range = RangeTypes.Self,
                min = { false, 5, 10, 15, 20 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { 200, 200, 200, 200, 200 },
                max = { 200, 200, 200, 200, 200 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
    {
        id = "reflect-weaknesses-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Reflect,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
            {
                id = EffectTypes.WeaknessToNormalWeapons,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 20, 30, 40 },
            },
        },
        itemTypes = {
            [T.Armor] = { types = {
                [T.Armor.TYPE.Cuirass] = true,
                [T.Armor.TYPE.Shield] = true,
            } },
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Robe] = true,
            } },
        },
    },
    {
        id = "fortifyStrengthMarksman-drainAgility-burden-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.marksman.id,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, false, 30, 40, 50 },
                max = { false, false, 40, 50, 60 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Self,
                min = { false, false, 200, 300, 400 },
                max = { false, false, 300, 400, 500 },
                duration = { false, false, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "fortifyStrength-drainAgility-weaknesses-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
                [T.Weapon.TYPE.BluntTwoWide] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
            } },
        },
    },
    {
        id = "sunDamage-touch-blind-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.SunDamage,
                range = RangeTypes.Touch,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 3, 4, 5, 6 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 10, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
    {
        id = "damageHealth-self-touch-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DamageHealth,
                range = RangeTypes.Touch,
                min = { false, 8, 16, 24, 32 },
                max = { false, 20, 40, 60, 80 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageHealth,
                range = RangeTypes.Self,
                min = { false, 2, 4, 6, 8 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "dispel-self-touch-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Touch,
                area = { false, 5, 10, 15, 20 },
                min = { false, 20, 30, 40, 50 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Clothing] = true,
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "dispel-self-touch-onStrike",
        affixType = mT.affixes.Suffix,
        value = 50,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 20, 30, 40, 50 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Touch,
                area = { 0, 5, 10, 15, 20 },
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 20, 30, 40, 50 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "poison-weaknessToPoison-self-touch-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 30, 40, 50, 60 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Touch,
                min = { false, 30, 40, 50, 60 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = EffectTypes.Poison,
                range = RangeTypes.Self,
                min = { false, 1, 1, 1, 1 },
                max = { false, 1, 1, 2, 3 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = EffectTypes.Poison,
                range = RangeTypes.Touch,
                min = { false, 2, 2, 2, 2 },
                max = { false, 3, 4, 5, 6 },
                duration = { false, 8, 12, 16, 20 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
            } },
        },
    },
    {
        id = "absorbMagicka-target-damageFatigue-self-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.AbsorbMagicka,
                range = RangeTypes.Target,
                min = { 1, 1, 1, 1, 1 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 3, 6, 9, 12, 15 },
                duration = { 10, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "damageFatigue-touch-damageLuck-touch-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Touch,
                min = { 5, 15, 25, 35, 50 },
                max = { 25, 35, 45, 60, 75 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "drainHealth-touch-damageFatigue-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DrainHealth,
                range = RangeTypes.Touch,
                min = { 20, 30, 40, 60, 80 },
                max = { 30, 40, 50, 75, 100 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 40, 50, 60, 80, 120 },
                max = { 50, 60, 70, 100, 150 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "sanctuary-fortifyShortBlade-drainBlock-damageFatigue-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.shortblade.id,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.block.id,
                range = RangeTypes.Self,
                min = { 50, 60, 70, 80, 90 },
                max = { 60, 70, 80, 90, 100 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
            } },
        },
    },
    {
        id = "sanctuary-fortifyLongBlade-drainBlock-damageFatigue-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.longblade.id,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.block.id,
                range = RangeTypes.Self,
                min = { 50, 60, 70, 80, 90 },
                max = { 60, 70, 80, 90, 100 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.LongBladeOneHand] = true,
            } },
        },
    },
    {
        id = "disintegrateArmor-touch-damageFatigue-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DisintegrateArmor,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 50, 75, 100, 150, 200 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 20, 40, 60, 80, 100 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.AxeOneHand] = true,
                [T.Weapon.TYPE.AxeTwoHand] = true,
                [T.Weapon.TYPE.BluntTwoClose] = true,
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "drainSpeedAgility-fortifyStrength-onStrike",
        affixType = mT.affixes.Suffix,
        value = 50,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Touch,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Touch,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Touch,
                min = { 25, 30, 40, 55, 70 },
                max = { 30, 35, 45, 60, 75 },
                duration = { 5, 5, 5, 5, 5 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.SpearTwoWide] = true,
            } },
        },
    },
    {
        id = "drainStrengthAgility-poison-touch-weaknessPoisonCommonBlightDiseases-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Touch,
                min = { 1, 2, 3, 4, 5 },
                max = { 3, 4, 5, 6, 7 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Touch,
                min = { 1, 2, 3, 4, 5 },
                max = { 3, 4, 5, 6, 7 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Poison,
                range = RangeTypes.Touch,
                min = { 4, 5, 6, 7, 8 },
                max = { 6, 7, 8, 9, 10 },
                duration = { 1, 2, 3, 4, 5 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "fortifyStrength-weaknessCommonBlightDiseases-constant",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.ConstantEffect,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 30 },
                max = { 5, 10, 15, 20, 30 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { 25, 35, 50, 65, 100 },
                max = { 25, 35, 50, 65, 100 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { 25, 35, 50, 65, 100 },
                max = { 25, 35, 50, 65, 100 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
        },
    },
    {
        id = "absorbMagicka-target-weaknessCommonBlightDiseasesMagicka-self-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.AbsorbMagicka,
                range = RangeTypes.Target,
                min = { 1, 2, 4, 5, 6 },
                max = { 2, 3, 5, 6, 7 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { 15, 30, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 100, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
            [T.Clothing] = true,
        },
    },
    {
        id = "resistWeapons-shield-weaknessCommonBlightDiseasesFireFrost-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.ResistNormalWeapons,
                range = RangeTypes.Self,
                min = { false, 15, 25, 35, 45 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Shield,
                range = RangeTypes.Self,
                min = { false, 15, 25, 35, 45 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { false, 40, 50, 70, 90 },
                max = { false, 50, 60, 80, 100 },
                duration = { false, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { false, 40, 50, 70, 90 },
                max = { false, 50, 60, 80, 100 },
                duration = { false, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 30, 25, 35, 45 },
                max = { false, 25, 30, 40, 50 },
                duration = { false, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 30, 25, 35, 45 },
                max = { false, 25, 30, 40, 50 },
                duration = { false, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
        },
    },
    {
        id = "sanctuary-chameleon-blind-damageFatigue-self-target-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Chameleon,
                range = RangeTypes.Self,
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Chameleon,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { false, false, 25, 35, 55 },
                max = { false, false, 30, 40, 60 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 25, 35, 55 },
                max = { false, false, 30, 40, 60 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { false, false, 2, 3, 5 },
                max = { false, false, 3, 4, 6 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 2, 3, 5 },
                max = { false, false, 3, 4, 6 },
                duration = { false, false, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = true,
        },
    },
    {
        id = "dispel-fortifyStrength-sound-blind-self-touch-onStrike",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
            },
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Sound,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Sound,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "sanctuary-fortifyAttack-weaknessWeaponsMagickaCommonBlightDiseases-constant",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.ConstantEffect,
        effects = {
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { false, 10, 15, 20, 30 },
                max = { false, 10, 15, 20, 30 },
            },
            {
                id = EffectTypes.FortifyAttack,
                range = RangeTypes.Self,
                min = { false, 5, 10, 15, 20 },
                max = { false, 5, 10, 15, 20 },
            },
            {
                id = EffectTypes.WeaknessToNormalWeapons,
                range = RangeTypes.Self,
                min = { false, 10, 15, 20, 30 },
                max = { false, 10, 15, 20, 30 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, 15, 20, 30, 40 },
                max = { false, 15, 20, 30, 40 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { false, 35, 50, 70, 100 },
                max = { false, 35, 50, 70, 100 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { false, 35, 50, 70, 100 },
                max = { false, 35, 50, 70, 100 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
            } },
        },
    },
    {
        id = "chameleon-shield-sunDamage-weaknessCommonDisease-constant",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.ConstantEffect,
        effects = {
            {
                id = EffectTypes.Chameleon,
                range = RangeTypes.Self,
                min = { false, 10, 15, 20, 30 },
                max = { false, 10, 15, 20, 30 },
            },
            {
                id = EffectTypes.Shield,
                range = RangeTypes.Self,
                min = { false, 10, 15, 20, 25 },
                max = { false, 10, 15, 20, 25 },
            },
            {
                id = EffectTypes.SunDamage,
                range = RangeTypes.Self,
                min = { false, 1, 1, 1, 1 },
                max = { false, 1, 2, 3, 5 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { false, 35, 50, 70, 100 },
                max = { false, 35, 50, 70, 100 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
        },
    },
    {
        id = "fortifyHandtohandStrength-drainArmorsAgility-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.handtohand.id,
                range = RangeTypes.Self,
                min = { 10, 20, 30, 40, 50 },
                max = { 15, 25, 35, 40, 50 },
                duration = { 20, 25, 30, 35, 40 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { 10, 20, 30, 40, 50 },
                max = { 15, 25, 35, 40, 50 },
                duration = { 20, 25, 30, 35, 40 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.heavyarmor.id,
                range = RangeTypes.Self,
                min = { 50, 60, 75, 90, 100 },
                max = { 50, 60, 75, 90, 100 },
                duration = { 20, 25, 30, 35, 40 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.mediumarmor.id,
                range = RangeTypes.Self,
                min = { 50, 60, 75, 90, 100 },
                max = { 50, 60, 75, 90, 100 },
                duration = { 20, 25, 30, 35, 40 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.lightarmor.id,
                range = RangeTypes.Self,
                min = { 50, 60, 75, 90, 100 },
                max = { 50, 60, 75, 90, 100 },
                duration = { 20, 25, 30, 35, 40 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { 10, 20, 30, 40, 50 },
                max = { 15, 25, 35, 40, 50 },
                duration = { 20, 25, 30, 35, 40 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.LGlove] = true,
                [T.Clothing.TYPE.RGlove] = true,
            } },
        },
    },
    {
        id = "restoreHealthFatigue-damageWillpowerAgilityLuckSpeed-weaknessCommonDisease-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.RestoreHealth,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 30, 35, 40, 50, 60 },
            },
            {
                id = EffectTypes.RestoreFatigue,
                range = RangeTypes.Self,
                min = { 1, 2, 2, 3, 4 },
                max = { 2, 3, 4, 5, 6 },
                duration = { 30, 35, 40, 50, 60 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.willpower.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { 40, 50, 60, 80, 100 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            }},
        },
    },
}