--don't ask why I'm including id, honestly it's just simpler and faster

return {
	mesh = {
		["alit"] = {
			id = "toilit",
			["r\\duskyalit.nif"] = true,
		},
		["cliffracer"] = {
			id = "cliffracer",
			["r\\cliffracer.nif"] = true,
		},
		["durzog"] = {
			id = "durzog",
			["r\\durzog.nif"] = true,
			["r\\durzog_collar.nif"] = true,
		},
		["guar"] = {
			id = "guar",
			["r\\guar.nif"] = true,
			["r\\guar_white.nif"] = true,
			["r\\guar_withpack.nif"] = true,
			["tr\\cr\\guar_withharness.nif"] = true,
		},
		["kwama"] = {
			id = "kwama",
			["r\\kwama forager.nif"] = true,
			["r\\kwama queen.nif"] = true,
			["r\\kwama warrior.nif"] = true,
			["r\\kwama worker.nif"] = true,
		},
		["kagouti"] = {
			id = "kagouti",
			["r\\leastkagouti.nif"] = true,
		},
		["netch"] = {
			id = "netch",
			["r\\netch_betty.nif"] = true,
			["r\\netch_bull.nif"] = true,
		},
		["nixhound"] = {
			id = "nixhound",
			["r\\nixhound.nif"] = true,
			["tr\\cr\\tr_nixmount.nif"] = true,
		},
		["ornada"] = {
			id = "ornada",
			["tr\\cr\\tr_ornada_vo.nif"] = true,
			["tr\\cr\\tr_ornada_clutch_vo.nif"] = true,
		},
		["rat"] = {
			id = "rat",
			["r\\packrat.nif"] = true,
			["r\\rust rat.nif"] = true,
		},
		["scrib"] = {
			id = "scrib",
			["r\\minescrib.nif"] = true,
		},
		["skyrender"] = {
			id = "skyrender",
			["tr\\cr\\tr_skyrender.nif"] = true,
		},
		["velk"] = {
			id = "velk",
			["tr\\cr\\tr_velk.nif"] = true,
		},
	},

	food = {
		["alit"] = {
			id = "toilit",
			["ingred_crab_meat_01"] = true,
			["ingred_kwama_cuttle_01"] = true,
			["ingred_scrib_jelly_01"] = true,
			["ingred_scrib_jerky_01"] = true,
			["T_IngFood_MeatCliffracer_01"] = true,
			["ingred_durzog_meat_01"] = true,
			["T_IngFood_MeatGuar_01"] = true,
			["T_IngFood_MeatKwama_01"] = true,
			["T_IngFood_MeatOrnada_01"] = true,
			["T_IngFood_MeatParastylus_01"] = true,
		},
		["cliffracer"] = {
			id = "cliffracer",
			["ingred_crab_meat_01"] = true,
			["ingred_kwama_cuttle_01"] = true,
			["ingred_rat_meat_01"] = true,
			["ingred_scales_01"] = true,
			["ingred_scrib_jelly_01"] = true,
			["T_IngFood_FishBrowntrout_01"] = true,
			["T_IngFood_FishChrysophant_01"] = true,
			["T_IngFood_FishCod_01"] = true,
			["T_IngFood_FishLeaperTail_01"] = true,
			["T_IngFood_FishLongfinFilet_01"] = true,
			["T_IngFood_FishPike_01"] = true,
			["T_IngFood_FishPikeperch_01"] = true,
			["T_IngFood_FishSalmon_01"] = true,
			["T_IngFood_FishSlaughterDried_01"] = true,
			["T_IngFood_FishSlaughterDried_02"] = true,
			["T_IngFood_FishSlaughterDried_03"] = true,
			["T_IngFood_FishSpr_01"] = true,
			["T_IngFood_FishStrid_01"] = true,
		},
		["durzog"] = {
			id = "durzog",
			["ingred_crab_meat_01"] = true,
			["ingred_hound_meat_01"] = true,
			["T_IngFood_MeatAlit_01"] = true,
			["T_IngFood_MeatCliffracer_01"] = true,
			["ingred_durzog_meat_01"] = true,
			["T_IngFood_MeatGuar_01"] = true,
			["T_IngFood_MeatKagouti_01"] = true,
			["T_IngFood_MeatKwama_01"] = true,
			["T_IngFood_MeatNixhoundRoast_01"] = true,
			["T_IngFood_MeatOrnada_01"] = true,
			["T_IngFood_MeatRat_01"] = true,
		},
		["guar"] = {
			id = "guar",
			["ingred_chokeweed_01"] = true,
			["ingred_kresh_fiber_01"] = true,
			["ingred_marshmerrow_01"] = true,
			["ingred_saltrice_01"] = true,
			["ingred_wickwheat_01"] = true,
		},
		["kwama"] = {
			id = "kwama",
			["ingred_crab_meat_01"] = true,
			["ingred_kwama_cuttle_01"] = true,
			["ingred_scrib_jelly_01"] = true,
			["ingred_scuttle_01"] = true,
			["Ingred_sweetpulp_01"] = true,
			["ingred_marshmerrow_01"] = true,
			["ingred_scrib_jerky_01"] = true,
			["ingred_comberry_01"] = true,
			["T_IngFood_EggOrnada_01"] = true,
			["ingred_saltrice_01"] = true,
			["ingred_heather_01"] = true,
			["ingred_kresh_fiber_01"] = true,
			["ingred_russula_01"] = true,
			["ingred_wickwheat_01"] = true,
			["T_IngFood_MeatOrnada_01"] = true,
			["T_IngFood_MeatParastylus_01"] = true,
		},
		["kagouti"] = {
			id = "kagouti",
			["T_IngFood_MeatAlit_01"] = true,
			["ingred_durzog_meat_01"] = true,
			["T_IngFood_MeatGuar_01"] = true,
			["T_IngFood_MeatKagouti_01"] = true,
			["T_IngFood_MeatKwama_01"] = true,
		},
		["netch"] = {
			id = "netch",
			["ingred_bc_bungler's_bane"] = true,
			["ingred_heather_01"] = true,
			["ingred_kresh_fiber_01"] = true,
			["ingred_muck_01"] = true,
			["ingred_russula_01"] = true,
			["ingred_saltrice_01"] = true,
			["ingred_wickwheat_01"] = true,
			["ingred_bc_hypha_facia"] = true,
			["ingred_coprinus_01"] = true,
		},
		["nixhound"] = {
			id = "nixhound",
			["food_kwama_egg_01"] = true,
			["food_kwama_egg_02"] = true,
			["ingred_bonemeal_01"] = true,
			["ingred_crab_meat_01"] = true,
			["ingred_kwama_cuttle_01"] = true,
			["ingred_rat_meat_01"] = true,
			["ingred_scrib_jelly_01"] = true,
			["ingred_scrib_jerky_01"] = true,
			["ingred_scuttle_01"] = true,
			["ingred_scales_01"] = true,
			["T_IngFood_MeatCliffracer_01"] = true,
			["T_IngFood_MeatGuar_01"] = true,
			["T_IngFood_MeatKwama_01"] = true,
			["T_IngFood_MeatOrnada_01"] = true,
			["T_IngFood_MeatParastylus_01"] = true,
			["T_IngFood_MeatRat_01"] = true,
		},
		["ornada"] = {
			id = "ornada",
			["ingred_saltrice_01"] = true,
			["ingred_comberry_01"] = true,
		},
		["rat"] = {
			id = "rat",
			["ingred_comberry_01"] = true,
			["ingred_saltrice_01"] = true,
			["ingred_scales_01"] = true,
			["ingred_crab_meat_01"] = true,
			["ingred_kwama_cuttle_01"] = true,
			["ingred_scrib_jelly_01"] = true,
			["ingred_scrib_jerky_01"] = true,
			["ingred_scuttle_01"] = true,
			["Ingred_sweetpulp_01"] = true,
			["ingred_marshmerrow_01"] = true,
			["T_IngFood_EggMolecrab_01"] = true,
			["T_IngFood_EggOrnada_01"] = true,
			["T_IngFood_FishBrowntrout_01"] = true,
			["T_IngFood_FishChrysophant_01"] = true,
			["T_IngFood_FishCod_01"] = true,
			["T_IngFood_FishLeaperTail_01"] = true,
			["T_IngFood_FishLongfinFilet_01"] = true,
			["T_IngFood_FishPike_01"] = true,
			["T_IngFood_FishPikeperch_01"] = true,
			["T_IngFood_FishSalmon_01"] = true,
			["T_IngFood_FishSpr_01"] = true,
			["T_IngFood_FishStrid_01"] = true,
			["T_IngFood_MeatCliffracer_01"] = true,
			["T_IngFood_MeatKwama_01"] = true,
			["T_IngFood_MeatOrnada_01"] = true,
		},
		["scrib"] = {
			id = "scrib",
			["ingred_black_lichen_01"] = true,
			["ingred_green_lichen_01"] = true,
			["ingred_heather_01"] = true,
			["ingred_kresh_fiber_01"] = true,
			["ingred_muck_01"] = true,
			["ingred_red_lichen_01"] = true,
			["ingred_saltrice_01"] = true,
			["ingred_trama_root_01"] = true,
			["ingred_wickwheat_01"] = true,
			["ingred_crab_meat_01"] = true,
			["T_IngFood_EggMolecrab_01"] = true,
			["T_IngFood_EggOrnada_01"] = true,
			["T_IngFood_MeatOrnada_01"] = true,
			["T_IngFood_MeatParastylus_01"] = true,
		},
		["skyrender"] = {
			id = "skyrender",
			["ingred_hound_meat_01"] = true,
			["T_IngFood_MeatAlit_01"] = true,
			["ingred_durzog_meat_01"] = true,
			["T_IngFood_MeatGuar_01"] = true,
			["T_IngFood_MeatKagouti_01"] = true,
			["T_IngFood_MeatKwama_01"] = true,
		},
		["velk"] = {
			id = "velk",
			["ingred_black_anther_01"] = true,
			["ingred_gold_kanet_01"] = true,
			["ingred_heather_01"] = true,
			["ingred_stoneflower_petals_01"] = true,
			["ingred_willow_anther_01"] = true,
		},
	}
}