
local buildData = {
    ["ex_imp_guardtower_02"] = {
        wallPiece = "ex_imp_wall_01",
        freeRotate = true,
        doRotate = true,
        separatingDistance = 512,
        startOffset = 400,
        rotateEnd = false,
        doSlopeRotate = true,
        endOffset = 768,
        wallHeightOffset = 328,
        scrollHeight = 100,
        endPiece = "ex_imp_guardtower_02",
        repeats = true
    },
    ["furn_com_fence_01"] = {
        wallPiece = "furn_com_fence_02",
        freeRotate = true,
        doRotate = true,
        separatingDistance = 256,
        startOffset = 128,
        rotateEnd = true,
        doSlopeRotate = false,
        slopePieceMain = "furn_com_fence_02",
        slopeDist = 32,
        endOffset = 128,
        wallHeightOffset = 0,
        scrollHeight = 10,
        wallRotate = 180,

        endPiece = "furn_com_fence_02",
        repeats = true
    },
    ["furn_com_fence_02"] = {
        wallPiece = "furn_com_fence_02",
        freeRotate = true,
        doRotate = true,
        separatingDistance = 256,
        slopePieceMain = "furn_com_fence_02",
        slopeDist = 28  ,
        startOffset = 128,
        doSlopeRotate = false,
        startPosOffset = 128,
        startPosOffsetDir = "west",
        rotateEnd = true,
        endOffset = 128,
        wallHeightOffset = 0,
        scrollHeight = 10,
        wallRotate = 180,

        endPiece = "furn_com_fence_02",
        repeats = true
    },
    ["zhac_tblock_ai_grass_01"] = {
        
        wallPiece = "zhac_tblock_ai_grass_01",
        slopePieceMain = "zhac_tblock_ai_grass_01",
        slopeDist = 128,
        doSlopeRotate = true,
        freeRotate = false,
        doRotate = true,
        rotateEnd = true,
        separatingDistance = 512,
        startOffset = 0,
        endOffset = 0,
        wallHeightOffset = 0,
        scrollHeight = 40,
        endPiece = "zhac_tblock_ai_grass_01",
        repeats = true
    },
    ["t_imp_legionmw_i_floor_01"] = {
        
        wallPiece = "t_imp_legionmw_i_floor_01",
        freeRotate = false,
        doRotate = true,
        rotateEnd = true,
        separatingDistance = 256,
        startOffset = 0,
        endOffset = 0,
        wallHeightOffset = 0,
        scrollHeight = 40,
        endPiece = "t_imp_legionmw_i_floor_01",
        repeats = true
    },
    ["furn_de_bar_02"] = {
        
        wallPiece = "furn_de_bar_01",
        freeRotate = false,
        doRotate = true,
        rotateEnd = true,
        separatingDistance = 64,
        startOffset = 0,
        endOffset = 0,
        wallRotate = 180,
        wallHeightOffset = 0,
        scrollHeight = 0,
        endPiece = "furn_de_bar_02",
        repeats = true
    },
    ["ex_vivec_w_e_01"] = {
        wallPiece = "ex_vivec_w_01",
        slopePieceMain = "ex_vivec_w_slope_01",
        slopeDist = 128,
        doSlopeRotate = true,
        freeRotate = true,
        doRotate = true,
        rotateEnd = true,
        separatingDistance = 256,
        startOffset = 128,
        endOffset = 256,
        wallHeightOffset = 0,
        scrollHeight = 40,
        endPiece = "ex_vivec_w_e_01",
        repeats = true
    },
    ["ex_imp_dock_02"] = {
        wallPiece = "ex_imp_dock_01",
        doSlopeRotate = true,
        freeRotate = false,
        doRotate = false,
        rotateEnd = true,
        separatingDistance = 512,
        wallRotate = 180,
        startOffset = 0,
        endOffset = 0,
    distOffset = -1024,
        wallHeightOffset = 0,
        scrollHeight = 40,
        endPiece = "T_Imp_LegionMw_X_Dock_04",
        repeats = false,
    }
}
return buildData