local armor = {
    "adamantium boots",
    "adamantium_bracer_left",
    "adamantium_bracer_right",
    "adamantium_cuirass",
    "adamantium_greaves",
    "adamantium_helm",
    "adamantium_pauldron_left",
    "adamantium_pauldron_right",
    "addamantium_helm",
    "bm bear boots",
    "bm bear cuirass",
    "bm bear greaves",
    "bm bear helmet",
    "bm bear left gauntlet",
    "bm bear left pauldron",
    "bm bear right gauntlet",
    "bm bear right pauldron",
    "bm bear shield",
    "bm wolf boots",
    "bm wolf cuirass",
    "bm wolf greaves",
    "bm wolf helmet",
    "bm wolf left gauntlet",
    "bm wolf left pauldron",
    "bm wolf right gauntlet",
    "bm wolf right pauldron",
    "bm wolf shield",
    "bm_nordicmail_boots",
    "bm_nordicmail_cuirass",
    "bm_nordicmail_gauntletl",
    "bm_nordicmail_gauntletr",
    "bm_nordicmail_greaves",
    "bm_nordicmail_helmet",
    "bm_nordicmail_pauldronl",
    "bm_nordicmail_pauldronr",
    "bm_nordicmail_shield",
    "bonemold_armun-an_cuirass",
    "bonemold_armun-an_helm",
    "bonemold_armun-an_pauldron_l",
    "bonemold_armun-an_pauldron_r",
    "bonemold_boots",
    "bonemold_bracer_left",
    "bonemold_bracer_right",
    "bonemold_chuzei_helm",
    "bonemold_cuirass",
    "bonemold_founders_helm",
    "bonemold_gah-julan_cuirass",
    "bonemold_gah-julan_helm",
    "bonemold_gah-julan_pauldron_l",
    "bonemold_gah-julan_pauldron_r",
    "bonemold_greaves",
    "bonemold_helm",
    "bonemold_pauldron_l",
    "bonemold_pauldron_r",
    "bonemold_shield",
    "bonemold_towershield",
    "bonemold_tshield_hlaaluguard",
    "bonemold_tshield_hrlb",
    "bonemold_tshield_redoranguard",
    "bonemold_tshield_telvanniguard",
    "cephalopod_helm",
    "chitin boots",
    "chitin cuirass",
    "chitin greaves",
    "chitin guantlet - left",
    "chitin guantlet - right",
    "chitin helm",
    "chitin pauldron - left",
    "chitin pauldron - right",
    "chitin_mask_helm",
    "chitin_shield",
    "chitin_towershield",
    "chitin_watchman_helm",
    "cloth bracer left",
    "cloth bracer right",
    "daedric_boots",
    "daedric_cuirass",
    "daedric_fountain_helm",
    "daedric_gauntlet_left",
    "daedric_gauntlet_right",
    "daedric_greaves",
    "daedric_pauldron_left",
    "daedric_pauldron_right",
    "daedric_shield",
    "daedric_towershield",
    "dragonscale_cuirass",
    "dragonscale_helm",
    "dragonscale_towershield",
    "dreugh_cuirass",
    "dreugh_helm",
    "dreugh_shield",
    "dust_adept_helm",
    "dwemer_boots",
    "dwemer_bracer_left",
    "dwemer_bracer_right",
    "dwemer_cuirass",
    "dwemer_greaves",
    "dwemer_helm",
    "dwemer_pauldron_left",
    "dwemer_pauldron_right",
    "dwemer_shield",
    "ebony_boots",
    "ebony_bracer_left",
    "ebony_bracer_right",
    "ebony_closed_helm",
    "ebony_cuirass",
    "ebony_greaves",
    "ebony_pauldron_left",
    "ebony_pauldron_right",
    "ebony_shield",
    "ebony_towershield",
    "fur_bearskin_cuirass",
    "fur_boots",
    "fur_bracer_left",
    "fur_bracer_right",
    "fur_colovian_helm_white",
    "fur_colovian_helm",
    "fur_cuirass",
    "fur_gauntlet_left",
    "fur_gauntlet_right",
    "fur_greaves",
    "fur_helm",
    "fur_pauldron_left",
    "fur_pauldron_right",
    "glass_boots",
    "glass_bracer_left",
    "glass_bracer_right",
    "glass_cuirass",
    "glass_greaves",
    "glass_helm",
    "glass_pauldron_left",
    "glass_pauldron_right",
    "glass_shield",
    "glass_towershield",
    "goblin_shield",
    "gondolier_helm",
    "heavy_leather_boots",
    "helsethguard_boots",
    "helsethguard_cuirass",
    "helsethguard_gauntlet_left",
    "helsethguard_gauntlet_right",
    "helsethguard_greaves",
    "helsethguard_helmet",
    "helsethguard_pauldron_left",
    "helsethguard_pauldron_right",
    "imperial boots",
    "imperial cuirass_armor",
    "imperial helmet armor",
    "imperial left gauntlet",
    "imperial left pauldron",
    "imperial right gauntlet",
    "imperial right pauldron",
    "imperial shield",
    "imperial_chain_coif_helm",
    "imperial_chain_cuirass",
    "imperial_chain_greaves",
    "imperial_chain_pauldron_left",
    "imperial_chain_pauldron_right",
    "imperial_greaves",
    "imperial_studded_cuirass",
    "indoril boots",
    "indoril cuirass",
    "indoril helmet",
    "indoril left gauntlet",
    "indoril pauldron left",
    "indoril pauldron right",
    "indoril right gauntlet",
    "indoril shield",
    "indoril_mh_guard_boots",
    "indoril_mh_guard_cuirass",
    "indoril_mh_guard_gauntlet_l",
    "indoril_mh_guard_gauntlet_r",
    "indoril_mh_guard_greaves",
    "indoril_mh_guard_helmet",
    "indoril_mh_guard_pauldron_l",
    "indoril_mh_guard_pauldron_r",
    "indoril_mh_guard_shield",
    "iron boots",
    "iron_bracer_left",
    "iron_bracer_right",
    "iron_cuirass",
    "iron_gauntlet_left",
    "iron_gauntlet_right",
    "iron_greaves",
    "iron_helmet",
    "iron_pauldron_left",
    "iron_pauldron_right",
    "iron_shield",
    "iron_towershield",
    "left leather bracer",
    "mole_crab_helm",
    "morag_tong_helm",
    "netch_leather_boiled_cuirass",
    "netch_leather_boiled_helm",
    "netch_leather_boots",
    "netch_leather_cuirass",
    "netch_leather_gauntlet_left",
    "netch_leather_gauntlet_right",
    "netch_leather_greaves",
    "netch_leather_helm",
    "netch_leather_pauldron_left",
    "netch_leather_pauldron_right",
    "netch_leather_shield",
    "netch_leather_towershield",
    "newtscale_cuirass",
    "nordic_iron_cuirass",
    "nordic_iron_helm",
    "nordic_leather_shield",
    "nordic_ringmail_cuirass",
    "orcish_boots",
    "orcish_bracer_left",
    "orcish_bracer_right",
    "orcish_cuirass",
    "orcish_greaves",
    "orcish_helm",
    "orcish_pauldron_left",
    "orcish_pauldron_right",
    "orcish_towershield",
    "redoran_master_helm",
    "right leather bracer",
    "silver_cuirass",
    "silver_dukesguard_cuirass",
    "silver_helm",
    "steel_boots_ancient",
    "steel_boots",
    "steel_cuirass_ancient",
    "steel_cuirass",
    "steel_gauntlet_left_ancient",
    "steel_gauntlet_left",
    "steel_gauntlet_right_ancient",
    "steel_gauntlet_right",
    "steel_greaves_ancient",
    "steel_greaves",
    "steel_helm_ancient",
    "steel_helm",
    "steel_pauldron_left_ancient",
    "steel_pauldron_left",
    "steel_pauldron_right_ancient",
    "steel_pauldron_right",
    "steel_shield",
    "steel_towershield_ancient",
    "steel_towershield",
    "templar boots",
    "templar bracer left",
    "templar bracer right",
    "templar_cuirass",
    "templar_greaves",
    "templar_helmet_armor",
    "templar_pauldron_left",
    "templar_pauldron_right",
    "trollbone_cuirass",
    "trollbone_helm",
    "trollbone_shield",

    --And some small mods
    "_dnk_ceph_bts",
    "_dnk_ceph_cuirass",
    "_dnk_ceph_greaves",
    "_dnk_ceph_gaunt_l",
    "_dnk_ceph_p_l",
    "_dnk_ceph_gaunt_r",
    "_dnk_ceph_p_r",
    "_dnk_cephal_helm",

}
return armor