local weapons = {
 "adamantium_axe",
 "adamantium_claymore",
 "adamantium_mace",
 "adamantium_shortsword",
 "adamantium_spear",
 "bm huntsman axe",
 "bm huntsman crossbow",
 "bm huntsman longsword",
 "bm huntsman spear",
 "bm huntsman war axe",
 "bm huntsmanbolt",
 "bm ice dagger",
 "bm ice longsword",
 "bm ice mace",
 "bm ice war axe",
 "bm nordic pick",
 "bm nordic silver axe",
 "bm nordic silver battleaxe",
 "bm nordic silver claymore",
 "bm nordic silver dagger",
 "bm nordic silver longsword",
 "bm nordic silver mace",
 "bm nordic silver shortsword",
 "bm riekling lance",
 "bm riekling sword",
 "bm riekling sword_rusted",
 "bm_arrow_riekling_uni",
 "bm_ice_minion_lance",
 "bonemold arrow",
 "bonemold bolt",
 "bonemold long bow",
 "chitin arrow",
 "chitin club",
 "chitin dagger",
 "chitin short bow",
 "chitin shortsword",
 "chitin spear",
 "chitin throwing star",
 "chitin war axe",
 "corkbulb arrow",
 "corkbulb bolt",
 "daedric arrow",
 "daedric battle axe",
 "daedric claymore",
 "daedric club",
 "daedric dagger",
 "daedric dai-katana",
 "daedric dart",
 "daedric katana",
 "daedric long bow",
 "daedric longsword",
 "daedric mace",
 "daedric shortsword",
 "daedric spear",
 "daedric staff",
 "daedric tanto",
 "daedric wakizashi",
 "daedric war axe",
 "daedric warhammer",
 "dreugh club",
 "dreugh staff",
 "dwarven battle axe",
 "dwarven claymore",
 "dwarven crossbow",
 "dwarven halberd",
 "dwarven mace",
 "dwarven shortsword",
 "dwarven spear",
 "dwarven war axe",
 "dwarven warhammer",
 "ebony arrow",
 "ebony broadsword",
 "ebony dart",
 "ebony longsword",
 "ebony mace",
 "ebony scimitar",
 "ebony shortsword",
 "ebony spear",
 "ebony staff",
 "ebony throwing star",
 "ebony war axe",
 "glass arrow",
 "glass claymore",
 "glass dagger",
 "glass halberd",
 "glass longsword",
 "glass staff",
 "glass throwing knife",
 "glass throwing star",
 "glass war axe",
 "goblin_club",
 "goblin_sword",
 "imperial broadsword",
 "imperial shortsword",
 "iron arrow",
 "iron battle axe",
 "iron bolt",
 "iron broadsword",
 "iron claymore",
 "iron club",
 "iron dagger",
 "iron fork",
 "iron halberd",
 "iron long spear",
 "iron longsword",
 "iron mace",
 "iron saber",
 "iron shortsword",
 "iron spear",
 "iron tanto",
 "iron throwing knife",
 "iron wakizashi",
 "iron war axe",
 "iron warhammer",
 "long bow",
 "miner's pick",
 "nordic battle axe",
 "nordic broadsword",
 "nordic claymore",
 "orcish battle axe",
 "orcish bolt",
 "orcish warhammer",
 "short bow",
 "silver arrow",
 "silver bolt",
 "silver claymore",
 "silver dagger",
 "silver dart",
 "silver longsword",
 "silver shortsword",
 "silver spear",
 "silver staff",
 "silver throwing star",
 "silver war axe",
 "spiked club",
 "spring dart",
 "steel arrow",
 "steel axe",
 "steel battle axe",
 "steel bolt",
 "steel broadsword",
 "steel claymore",
 "steel club",
 "steel crossbow",
 "steel dagger",
 "steel dai-katana",
 "steel dart",
 "steel halberd",
 "steel katana",
 "steel longbow",
 "steel longsword",
 "steel mace",
 "steel saber",
 "steel shortsword",
 "steel spear",
 "steel staff",
 "steel tanto",
 "steel throwing knife",
 "steel throwing star",
 "steel wakizashi",
 "steel war axe",
 "steel warhammer",
 "wooden staff",
}
return weapons