return mwse.loadConfig("Watch the Skies", {
    modEnabled = true,
    cloudSpeed = true,
    cloudSpeedMode = 100,
    debugLogOn = false,
    dynamicWeatherChanges = true,
    interiorTransitions = true,
    particleAmount = true,
    particleMesh = true,
    seasonalDaytime = true,
    seasonalWeather = true,
    skyTexture = true,
    useVanillaSkyTextures = true,
    variableFog = true,
    variableRain = true,
})
