local core = require("openmw.core")
local T = require("openmw.types")

local mT = require("scripts.fresh-loot.config.types")

local Attributes = core.stats.Attribute.records
local Skills = core.stats.Skill.records
local EffectTypes = core.magic.EFFECT_TYPE
local EnchantTypes = core.magic.ENCHANTMENT_TYPE
local RangeTypes = core.magic.RANGE

return {
    {
        id = "burden-self-touch-onUse",
        affixType = mT.affixes.Prefix,
        value = 25,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 300, 400, 500, 600 },
                duration = { false, 30, 30, 30, 30 },
            },
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 100, 200, 300, 400 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 30, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "drainSpeed-self-touch-onUse",
        affixType = mT.affixes.Prefix,
        value = 25,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 30, 30, 30, 30 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 10, 20, 30, 40 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 30, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "blind-self-touch-onUse",
        affixType = mT.affixes.Prefix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Touch,
                area = { false, 20, 30, 40, 50 },
                min = { false, 60, 60, 60, 60 },
                max = { false, 80, 80, 80, 80 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "fortifySpeed-sanctuary-blind-sound-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 30, 30, 30, 30 },
            },
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { false, 10, 15, 20, 25 },
                max = { false, 15, 20, 25, 30 },
                duration = { false, 30, 30, 30, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { false, 40, 50, 60, 70 },
                max = { false, 50, 60, 70, 80 },
                duration = { false, 30, 30, 30, 30 },
            },
            {
                id = EffectTypes.Sound,
                range = RangeTypes.Self,
                min = { false, 25, 30, 35, 40 },
                max = { false, 35, 40, 45, 50 },
                duration = { false, 30, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 75,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { false, 20, 40, 80, 120 },
                max = { false, 40, 80, 120, 160 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "levitate-light-fortifySpeed-drainAgility-weaknesses-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 160,
        effects = {
            {
                id = EffectTypes.Levitate,
                range = RangeTypes.Self,
                min = { false, 200, 300, 400, 500 },
                max = { false, 200, 300, 400, 500 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Light,
                range = RangeTypes.Self,
                min = { false, 5, 10, 15, 20 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { 200, 200, 200, 200, 200 },
                max = { 200, 200, 200, 200, 200 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "reflect-weaknesses-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Reflect,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 40, 45 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 40, 45 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 40, 45 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 40, 45 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 40, 45 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 40, 45 },
            },
            {
                id = EffectTypes.WeaknessToNormalWeapons,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 40, 45 },
            },
        },
        itemTypes = {
            [T.Armor] = { types = {
                [T.Armor.TYPE.Cuirass] = true,
                [T.Armor.TYPE.Shield] = true,
            } },
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Robe] = true,
            } },
        },
    },
    {
        id = "fortifyStrengthMarksman-drainAgility-burden-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.marksman.id,
                range = RangeTypes.Self,
                min = { false, false, 20, 30, 40 },
                max = { false, false, 30, 40, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, false, 30, 40, 50 },
                max = { false, false, 40, 50, 60 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Self,
                min = { false, false, 200, 300, 400 },
                max = { false, false, 300, 400, 500 },
                duration = { false, false, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "fortifyStrength-drainAgility-weaknesses-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 10,
        charge = 100,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 40, 50, 60, 70 },
                duration = { false, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.WeaknessToShock,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { false, 20, 40, 60, 80 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 45, 50, 60, 60 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Belt] = true,
            } },
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
                [T.Weapon.TYPE.BluntTwoWide] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
            } },
        },
    },
    {
        id = "sunDamage-touch-blind-self-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.SunDamage,
                range = RangeTypes.Touch,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 3, 4, 5, 6 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 10, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "dispel-self-touch-onUse",
        affixType = mT.affixes.Suffix,
        value = 50,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Self,
                min = { false, 20, 30, 40, 50 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Touch,
                area = { false, 5, 10, 15, 20 },
                min = { false, 20, 30, 40, 50 },
                max = { false, 40, 60, 80, 100 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Clothing] = true,
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "absorbMagicka-target-damageFatigue-self-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.AbsorbMagicka,
                range = RangeTypes.Target,
                min = { 1, 1, 1, 1, 1 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 3, 6, 9, 12, 15 },
                duration = { 10, 15, 20, 25, 30 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "restoreMagicka-damageIntelligenceHealth-poison-onUse",
        affixType = mT.affixes.Suffix,
        value = 75,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.RestoreMagicka,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 3, 4 },
                max = { 1, 2, 4, 5, 6 },
                duration = { 12, 14, 16, 18, 20 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.intelligence.id,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 2, 2, 2, 2, 2 },
                duration = { 1, 2, 3, 4, 5 },
            },
            {
                id = EffectTypes.DamageHealth,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 2, 4, 6, 8, 10 },
            },
            {
                id = EffectTypes.Poison,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 2, 4, 6, 8, 10 },
            },
        },
        itemTypes = {
            [T.Clothing] = true,
        },
    },
    {
        id = "absorbMagicka-target-damageHealthFireFrostShock-self-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 65,
        charge = 200,
        effects = {
            {
                id = EffectTypes.AbsorbMagicka,
                range = RangeTypes.Target,
                min = { 6, 12, 18, 24, 30 },
                max = { 6, 12, 18, 24, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DamageHealth,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FireDamage,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FrostDamage,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.ShockDamage,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 5, 5, 5, 5, 5 },
            },
        },
        itemTypes = {
            [T.Armor] = { types = {
                [T.Armor.TYPE.LBracer] = true,
                [T.Armor.TYPE.RBracer] = true,
                [T.Armor.TYPE.LGauntlet] = true,
                [T.Armor.TYPE.RGauntlet] = true,
            } },
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.LGlove] = true,
                [T.Clothing.TYPE.RGlove] = true,
            } },
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "absorbMagicka-target-weaknessCommonBlightDiseasesMagicka-self-onUse",
        affixType = mT.affixes.Suffix,
        value = 200,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 200,
        effects = {
            {
                id = EffectTypes.AbsorbMagicka,
                range = RangeTypes.Target,
                min = { 1, 2, 4, 5, 6 },
                max = { 2, 3, 5, 6, 7 },
                duration = { 10, 15, 20, 25, 30 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 100, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
            [T.Clothing] = true,
        },
    },
    {
        id = "resistWeapons-shield-weaknessCommonBlightDiseasesFireFrost-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.ResistNormalWeapons,
                range = RangeTypes.Self,
                min = { false, 15, 25, 35, 45 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 30, 35, 40, 45 },
            },
            {
                id = EffectTypes.Shield,
                range = RangeTypes.Self,
                min = { false, 15, 25, 35, 45 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 30, 35, 40, 45 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { false, 40, 50, 70, 90 },
                max = { false, 50, 60, 80, 100 },
                duration = { false, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { false, 40, 50, 70, 90 },
                max = { false, 50, 60, 80, 100 },
                duration = { false, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToFire,
                range = RangeTypes.Self,
                min = { false, 20, 25, 35, 45 },
                max = { false, 25, 30, 40, 50 },
                duration = { false, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToFrost,
                range = RangeTypes.Self,
                min = { false, 20, 25, 35, 45 },
                max = { false, 25, 30, 40, 50 },
                duration = { false, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
        },
    },
    {
        id = "sanctuary-chameleon-blind-damageFatigue-self-target-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Chameleon,
                range = RangeTypes.Self,
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Chameleon,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 15, 25, 45 },
                max = { false, false, 20, 30, 50 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { false, false, 25, 35, 55 },
                max = { false, false, 30, 40, 60 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 25, 35, 55 },
                max = { false, false, 30, 40, 60 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { false, false, 2, 3, 5 },
                max = { false, false, 3, 4, 6 },
                duration = { false, false, 30, 30, 30 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Target,
                area = { false, false, 50, 50, 50 },
                min = { false, false, 2, 3, 5 },
                max = { false, false, 3, 4, 6 },
                duration = { false, false, 30, 30, 30 },
            },
        },
        itemTypes = {
            [T.Clothing] = true,
        },
    },
    {
        id = "fortifyHandtohandStrength-drainArmorsAgility-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.handtohand.id,
                range = RangeTypes.Self,
                min = { 10, 20, 30, 40, 50 },
                max = { 15, 25, 35, 40, 50 },
                duration = { 40, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { 10, 20, 30, 40, 50 },
                max = { 15, 25, 35, 40, 50 },
                duration = { 40, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.heavyarmor.id,
                range = RangeTypes.Self,
                min = { 50, 60, 75, 90, 100 },
                max = { 50, 60, 75, 90, 100 },
                duration = { 40, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.mediumarmor.id,
                range = RangeTypes.Self,
                min = { 50, 60, 75, 90, 100 },
                max = { 50, 60, 75, 90, 100 },
                duration = { 40, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.lightarmor.id,
                range = RangeTypes.Self,
                min = { 50, 60, 75, 90, 100 },
                max = { 50, 60, 75, 90, 100 },
                duration = { 40, 45, 50, 60, 60 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { 10, 20, 30, 40, 50 },
                max = { 15, 25, 35, 40, 50 },
                duration = { 40, 45, 50, 60, 60 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.LGlove] = true,
                [T.Clothing.TYPE.RGlove] = true,
            } },
        },
    },
    {
        id = "restoreHealthFatigue-damageWillpowerAgilityLuckSpeed-weaknessCommonDisease-onUse",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.RestoreHealth,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 30, 35, 40, 50, 60 },
            },
            {
                id = EffectTypes.RestoreFatigue,
                range = RangeTypes.Self,
                min = { 1, 2, 2, 3, 4 },
                max = { 2, 3, 4, 5, 6 },
                duration = { 30, 35, 40, 50, 60 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.willpower.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { 1, 1, 2, 2, 2 },
                max = { 1, 2, 2, 3, 4 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { 40, 50, 60, 80, 100 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Armor] = true,
            [T.Clothing] = true,
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
            } },
        },
    },
    {
        id = "calmCreatureHumanoid-fortifySpeed-silence-onUse",
        affixType = mT.affixes.Suffix,
        value = 150,
        castType = EnchantTypes.CastOnUse,
        cost = 40,
        charge = 160,
        effects = {
            {
                id = EffectTypes.CalmCreature,
                range = RangeTypes.Touch,
                min = { false, 30, 30, 40, 55 },
                max = { false, 30, 35, 50, 60 },
                duration = { false, 10, 15, 20, 30 },
                area = { false, 5, 10, 20, 30 },
            },
            {
                id = EffectTypes.CalmHumanoid,
                range = RangeTypes.Touch,
                min = { false, 30, 30, 40, 55 },
                max = { false, 30, 35, 50, 60 },
                duration = { false, 10, 15, 20, 30 },
                area = { false, 5, 10, 20, 30 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Self,
                min = { false, 10, 10, 20, 30 },
                max = { false, 10, 15, 25, 35 },
                duration = { false, 5, 6, 8, 10 },
            },
            {
                id = EffectTypes.Silence,
                range = RangeTypes.Self,
                duration = { false, 5, 6, 8, 10 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Ring] = true,
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Robe] = true,
            } },
        },
    },
    {
        id = "shield-spellAbsorption-restoreHealthFatigue-burden-silence-onUse",
        affixType = mT.affixes.Prefix,
        value = 300,
        castType = EnchantTypes.CastOnUse,
        cost = 60,
        charge = 180,
        effects = {
            {
                id = EffectTypes.Shield,
                range = RangeTypes.Self,
                min = { false, false, 40, 60, 80 },
                max = { false, false, 50, 70, 90 },
                duration = { false, false, 10, 10, 10 },
            },
            {
                id = EffectTypes.SpellAbsorption,
                range = RangeTypes.Self,
                min = { false, false, 15, 20, 30 },
                max = { false, false, 20, 25, 35 },
                duration = { false, false, 10, 10, 10 },
            },
            {
                id = EffectTypes.RestoreHealth,
                range = RangeTypes.Self,
                min = { false, false, 5, 8, 10 },
                max = { false, false, 7, 10, 15 },
                duration = { false, false, 10, 10, 10 },
            },
            {
                id = EffectTypes.RestoreFatigue,
                range = RangeTypes.Self,
                min = { false, false, 10, 12, 16 },
                max = { false, false, 11, 15, 20 },
                duration = { false, false, 10, 10, 10 },
            },
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Self,
                min = { false, false, 1000, 1000, 1000 },
                max = { false, false, 1000, 1000, 1000 },
                duration = { false, false, 10, 10, 10 },
            },
            {
                id = EffectTypes.Silence,
                range = RangeTypes.Self,
                duration = { false, false, 10, 10, 10 },
            },
        },
        itemTypes = {
            [T.Armor] = { types = {
                [T.Armor.TYPE.Cuirass] = true,
                [T.Armor.TYPE.Shield] = true,
            } },
        },
    },
    {
        id = "commandRallyDemoralizeCreature-fortifyStrength-onUse",
        affixType = mT.affixes.Suffix,
        value = 300,
        castType = EnchantTypes.CastOnUse,
        cost = 150,
        charge = 600,
        effects = {
            {
                id = EffectTypes.CommandCreature,
                range = RangeTypes.Target,
                min = { false, 1, 3, 5, 6 },
                max = { false, 6, 8, 12, 18 },
                duration = { false, 15, 20, 25, 30 },
                area = { false, 5, 10, 15, 20 },
            },
            {
                id = EffectTypes.RallyCreature,
                range = RangeTypes.Target,
                min = { false, 1, 1, 1, 1 },
                max = { false, 50, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
                area = { false, 5, 10, 15, 20 },
            },
            {
                id = EffectTypes.DemoralizeCreature,
                range = RangeTypes.Target,
                min = { false, 1, 1, 1, 1 },
                max = { false, 50, 60, 80, 100 },
                duration = { false, 15, 20, 25, 30 },
                area = { false, 5, 10, 15, 20 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Target,
                min = { false, 1, 1, 1, 1 },
                max = { false, 20, 30, 40, 50 },
                duration = { false, 15, 20, 25, 30 },
                area = { false, 5, 10, 15, 20 },
            },
        },
        itemTypes = {
            [T.Armor] = { types = {
                [T.Armor.TYPE.Helmet] = true,
            } },
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.LGlove] = true,
                [T.Clothing.TYPE.RGlove] = true,
            } },
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "fortifyLuck-restoreFatigue-weaknessMagicka-burden-drainHealth-silence-onUse",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnUse,
        cost = 100,
        charge = 100,
        effects = {
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 30, 45, 60, 80, 100 },
                duration = { 200, 300, 400, 500, 600 },
            },
            {
                id = EffectTypes.RestoreFatigue,
                range = RangeTypes.Self,
                min = { 0, 0, 0, 0, 0 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 200, 300, 400, 500, 600 },
            },
            {
                id = EffectTypes.WeaknessToMagicka,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 30, 45, 60, 80, 100 },
                duration = { 200, 300, 400, 500, 600 },
            },
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 50, 75, 100, 125, 150 },
                duration = { 200, 300, 400, 500, 600 },
            },
            {
                id = EffectTypes.DrainHealth,
                range = RangeTypes.Self,
                min = { 20, 30, 35, 40, 50 },
                max = { 30, 35, 40, 45, 60 },
                duration = { 200, 300, 400, 500, 600 },
            },
            {
                id = EffectTypes.Silence,
                range = RangeTypes.Self,
                duration = { 200, 300, 400, 500, 600 },
            },
        },
        itemTypes = {
            [T.Clothing] = { types = {
                [T.Clothing.TYPE.Amulet] = true,
                [T.Clothing.TYPE.Ring] = true,
            } },
        },
    },
}