local core = require("openmw.core")
local T = require("openmw.types")

local mT = require("scripts.fresh-loot.config.types")

local Attributes = core.stats.Attribute.records
local Skills = core.stats.Skill.records
local EffectTypes = core.magic.EFFECT_TYPE
local EnchantTypes = core.magic.ENCHANTMENT_TYPE
local RangeTypes = core.magic.RANGE

return {
    {
        id = "damageHealth-self-touch-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DamageHealth,
                range = RangeTypes.Touch,
                min = { false, 8, 16, 24, 32 },
                max = { false, 20, 40, 60, 80 },
                duration = { false, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageHealth,
                range = RangeTypes.Self,
                min = { false, 2, 4, 6, 8 },
                max = { false, 5, 10, 15, 20 },
                duration = { false, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "dispel-self-touch-onStrike",
        affixType = mT.affixes.Suffix,
        value = 50,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 20, 30, 40, 50 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Touch,
                area = { 0, 5, 10, 15, 20 },
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 20, 30, 40, 50 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "poison-weaknessToPoison-self-touch-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { false, 30, 40, 50, 60 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Touch,
                min = { false, 30, 40, 50, 60 },
                max = { false, 30, 40, 50, 60 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = EffectTypes.Poison,
                range = RangeTypes.Self,
                min = { false, 1, 1, 1, 1 },
                max = { false, 1, 1, 2, 3 },
                duration = { false, 8, 12, 16, 20 },
            },
            {
                id = EffectTypes.Poison,
                range = RangeTypes.Touch,
                min = { false, 2, 2, 2, 2 },
                max = { false, 3, 4, 5, 6 },
                duration = { false, 8, 12, 16, 20 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
            } },
        },
    },
    {
        id = "damageFatigue-touch-damageLuck-touch-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Touch,
                min = { 5, 15, 25, 35, 50 },
                max = { 25, 35, 45, 60, 75 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "damageFatigue-touch-damageLuck-touch-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Touch,
                min = { 5, 10, 15, 20, 30 },
                max = { 10, 20, 30, 45, 60 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.luck.id,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 1, 2, 3, 4, 5 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
            } },
        },
    },
    {
        id = "drainHealth-touch-damageFatigue-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DrainHealth,
                range = RangeTypes.Touch,
                min = { 20, 30, 40, 60, 80 },
                max = { 30, 40, 50, 75, 100 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 40, 50, 60, 80, 120 },
                max = { 50, 60, 70, 100, 150 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "sanctuary-fortifyShortBlade-drainBlock-damageFatigue-onStrike",
        affixType = mT.affixes.Suffix,
        value = 150,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.shortblade.id,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.block.id,
                range = RangeTypes.Self,
                min = { 50, 60, 70, 80, 90 },
                max = { 60, 70, 80, 90, 100 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.ShortBladeOneHand] = true,
            } },
        },
    },
    {
        id = "sanctuary-fortifyLongBlade-drainBlock-damageFatigue-onStrike",
        affixType = mT.affixes.Suffix,
        value = 150,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Sanctuary,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FortifySkill,
                skill = Skills.longblade.id,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 10, 15, 20, 25, 30 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DrainSkill,
                skill = Skills.block.id,
                range = RangeTypes.Self,
                min = { 50, 60, 70, 80, 90 },
                max = { 60, 70, 80, 90, 100 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 2, 3, 4, 5 },
                max = { 2, 4, 6, 8, 10 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.LongBladeOneHand] = true,
            } },
        },
    },
    {
        id = "disintegrateArmor-touch-damageFatigue-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DisintegrateArmor,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 50, 75, 100, 150, 200 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageFatigue,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 20, 40, 60, 80, 100 },
                duration = { 1, 1, 1, 1, 1 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.AxeOneHand] = true,
                [T.Weapon.TYPE.AxeTwoHand] = true,
                [T.Weapon.TYPE.BluntTwoClose] = true,
                [T.Weapon.TYPE.BluntTwoWide] = true,
            } },
        },
    },
    {
        id = "drainSpeedAgility-fortifyStrength-onStrike",
        affixType = mT.affixes.Suffix,
        value = 75,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.speed.id,
                range = RangeTypes.Touch,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.DrainAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Touch,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 5, 5, 5, 5, 5 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Touch,
                min = { 25, 30, 40, 55, 70 },
                max = { 30, 35, 45, 60, 75 },
                duration = { 5, 5, 5, 5, 5 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.SpearTwoWide] = true,
            } },
        },
    },
    {
        id = "drainStrengthAgility-poison-touch-weaknessPoisonCommonBlightDiseases-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 150,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Touch,
                min = { 1, 2, 3, 4, 5 },
                max = { 3, 4, 5, 6, 7 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.DamageAttribute,
                attribute = Attributes.agility.id,
                range = RangeTypes.Touch,
                min = { 1, 2, 3, 4, 5 },
                max = { 3, 4, 5, 6, 7 },
                duration = { 1, 1, 1, 1, 1 },
            },
            {
                id = EffectTypes.Poison,
                range = RangeTypes.Touch,
                min = { 4, 5, 6, 7, 8 },
                max = { 6, 7, 8, 9, 10 },
                duration = { 1, 2, 3, 4, 5 },
            },
            {
                id = EffectTypes.WeaknessToPoison,
                range = RangeTypes.Self,
                min = { 15, 20, 25, 35, 45 },
                max = { 20, 25, 30, 40, 50 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToCommonDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
            {
                id = EffectTypes.WeaknessToBlightDisease,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 70, 90 },
                max = { 40, 50, 60, 80, 100 },
                duration = { 100, 125, 150, 175, 200 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "dispel-fortifyStrength-sound-blind-self-touch-onStrike",
        affixType = mT.affixes.Prefix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
            },
            {
                id = EffectTypes.Dispel,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.FortifyAttribute,
                attribute = Attributes.strength.id,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Sound,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Sound,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Self,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
            {
                id = EffectTypes.Blind,
                range = RangeTypes.Touch,
                min = { 1, 1, 1, 1, 1 },
                max = { 25, 35, 50, 75, 100 },
                duration = { 5, 5, 10, 10, 15 },
            },
        },
        itemTypes = {
            [T.Weapon] = { notTypes = {
                [T.Weapon.TYPE.Arrow] = true,
                [T.Weapon.TYPE.Bolt] = true,
                [T.Weapon.TYPE.MarksmanThrown] = true,
                [T.Weapon.TYPE.MarksmanBow] = true,
                [T.Weapon.TYPE.MarksmanCrossbow] = true,
            } },
        },
    },
    {
        id = "burden-touch-self-fortifyFatigueAttack-self-onStrike",
        affixType = mT.affixes.Suffix,
        value = 100,
        castType = EnchantTypes.CastOnStrike,
        cost = 20,
        charge = 200,
        effects = {
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Touch,
                min = { 125, 175, 250, 300, 400 },
                max = { 175, 250, 300, 400, 500 },
                duration = { 3, 4, 5, 6, 7 },
            },
            {
                id = EffectTypes.Burden,
                range = RangeTypes.Self,
                min = { 125, 175, 250, 300, 400 },
                max = { 175, 250, 300, 400, 500 },
                duration = { 3, 4, 5, 6, 7 },
            },
            {
                id = EffectTypes.FortifyFatigue,
                range = RangeTypes.Self,
                min = { 30, 40, 50, 75, 100 },
                max = { 30, 40, 50, 75, 100 },
                duration = { 3, 4, 5, 6, 7 },
            },
            {
                id = EffectTypes.FortifyAttack,
                range = RangeTypes.Self,
                min = { 5, 10, 15, 20, 25 },
                max = { 5, 10, 15, 20, 25 },
                duration = { 3, 4, 5, 6, 7 },
            },
        },
        itemTypes = {
            [T.Weapon] = { types = {
                [T.Weapon.TYPE.BluntOneHand] = true,
                [T.Weapon.TYPE.BluntTwoClose] = true,
                [T.Weapon.TYPE.AxeOneHand] = true,
                [T.Weapon.TYPE.AxeTwoHand] = true,
            } },
        },
    },
}