local data = require("CCCP.data")
local defaults = data.defaultFactors

return mwse.loadConfig("CCCP", {
    attributeIncreaseRate = 100,
    attributeSpread = 34,
    initialSkillOffset = 20,
    racialAttributeStart = 50,
    racialAttributeProgress = 30,
    luckIncreaseRate = 70,
    attributesToLevel = 6,
    displayLevelMessages = true,
    manageHealth = true,
    healthBase = 50,
    healthBonus = 12,
    healthBackgroundMult = 100,
    healthInUseMult = 100,
    healthInUseOffset = 0,
    maxMagickaHandling = true,
    magickaRegen = true,
    magMaxMultiplier = 100,
    magMaxProgress = 50,
    magMaxStartOffset = 0,
    magMaxUnaffected = 20,
    magRegenBaseRate = 100,
    magRegenStartOffset = 0,
    magRegenProgress = 70,
    magRegenWilValue = 60,
    magRegenWilInfluence = 60,
    magRegenFatValue = 80,
    magRegenFatInfluence = 80,
    slowdownStart = 60,
    slowdownSpread = 80,
    slowdownRate = 35,
    debugMode = false,
    skillFactors = defaults,
})