local ssqn = include("SSQN.interop")
if not ssqn then
	print("SSQN interop not available")
	return
end

-- Project Cyrodiil

ssqn.registerQBlock("PC_m1_Anv_AdvReadB")
ssqn.registerQBlock("PC_m1_Anv_BookClubA")
ssqn.registerQBlock("PC_m1_Anv_BookClubB")		
ssqn.registerQBlock("PC_m1_Anv_BookClubG")
ssqn.registerQBlock("PC_m1_Anv_BookClubM")
ssqn.registerQBlock("PC_m1_Anv_GoldenrodBR")
ssqn.registerQBlock("PC_m1_Anv_GoldenrodDR")
ssqn.registerQBlock("PC_m1_Anv_GoldenrodEH")
ssqn.registerQBlock("PC_m1_Anv_GoldenrodLI")
ssqn.registerQBlock("PC_m1_Anv_GoldenrodPA")
ssqn.registerQBlock("PC_m1_Anv_GoldenrodSM")
ssqn.registerQBlock("PC_m1_Anv_GoldenrodST")
ssqn.registerQBlock("PC_m1_Anv_NakedNardGloves")
ssqn.registerQBlock("PC_m1_Anv_NakedNardHat")
ssqn.registerQBlock("PC_m1_Anv_NakedNardPants")
ssqn.registerQBlock("PC_m1_Anv_NakedNardShirt")	
ssqn.registerQBlock("PC_m1_Anv_NakedNardShoes")
ssqn.registerQBlock("PC_m1_Anv_OceanBlueDate")
ssqn.registerQBlock("PC_m1_Anv_OceanBlueFood")
ssqn.registerQBlock("PC_m1_Anv_OceanBlueRoute")
ssqn.registerQBlock("PC_m1_Anv_OceanBlueShip")
ssqn.registerQBlock("PC_m1_Anv_TakingTaxKra")
ssqn.registerQBlock("PC_m1_Anv_TakingTaxSle")
ssqn.registerQBlock("PC_m1_Anv_WorkOrcFG")	
ssqn.registerQBlock("PC_m1_Anv_WorkOrcFish")	
ssqn.registerQBlock("PC_m1_Anv_WorkOrcIAS")	
ssqn.registerQBlock("PC_m1_Anv_WorkOrcKarrel")
ssqn.registerQBlock("PC_m1_Anv_WorkOrcNavy")	
ssqn.registerQBlock("PC_m1_Anv_WorkOrcRG")	
ssqn.registerQBlock("PC_m1_Anv_WorkOrcSmith")
ssqn.registerQBlock("PC_m1_Anv_WorkOrcSW")
ssqn.registerQBlock("PC_m1_BC_MurdCrossBrescius")
ssqn.registerQBlock("PC_m1_BC_MurdCrossGosha")
ssqn.registerQBlock("PC_m1_BC_MurdCrossMedina")
ssqn.registerQBlock("PC_m1_BC_MurdCrossRamus")
ssqn.registerQBlock("PC_m1_BC_MurdCrossWound")
ssqn.registerQBlock("PC_m1_BC_WomPetriLegion")
ssqn.registerQBlock("PC_m1_BC_WomPetriLetter")
ssqn.registerQBlock("PC_m1_IP_HY4A")
ssqn.registerQBlock("PC_m1_IP_HY4D")
ssqn.registerQBlock("PC_m1_IP_HY4K")			
ssqn.registerQBlock("PC_m1_IP_Run1BU")
ssqn.registerQBlock("PC_m1_IP_Run1CA")
ssqn.registerQBlock("PC_m1_IP_Run1CC")
ssqn.registerQBlock("PC_m1_IP_Run1JV")
ssqn.registerQBlock("PC_m1_IP_Run1LA")
ssqn.registerQBlock("PC_m1_IP_Run1LE")
ssqn.registerQBlock("PC_m1_IP_Run1LV")
ssqn.registerQBlock("PC_m1_IP_Run1OS")
ssqn.registerQBlock("PC_m1_IP_Run1OT")
ssqn.registerQBlock("PC_m1_IP_Run1PS")
ssqn.registerQBlock("PC_m1_IP_Run1TE")
ssqn.registerQBlock("PC_m1_IP_Run1TH")
ssqn.registerQBlock("PC_m1_IP_Run1TT")
ssqn.registerQBlock("PC_m1_IP_Run1UO")
ssqn.registerQBlock("PC_m1_IP_Run1VA")
ssqn.registerQBlock("PC_m1_IP_Run2UO")
ssqn.registerQBlock("PC_m1_K1_MC6H")
ssqn.registerQBlock("PC_m1_K1_MC6L")
ssqn.registerQBlock("PC_m1_K1_MC6M")
ssqn.registerQBlock("PC_m1_K1_MC6S")
ssqn.registerQBlock("PC_m1_K1_MC6V")
ssqn.registerQBlock("PC_m1_K1_MC7T")
ssqn.registerQBlock("PC_m1_K1_MC8S")
ssqn.registerQBlock("PC_m1_K1_RP3B")
ssqn.registerQBlock("PC_m1_MG_Anv1B")
ssqn.registerQBlock("PC_m1_TG_Anv4B")
ssqn.registerQBlock("PC_m1_TG_Anv6C")
ssqn.registerQBlock("PC_m1_TG_Anv6M")
ssqn.registerQBlock("PC_m1_TG_Anv6V")
ssqn.registerQBlock("PC_m1_Tvy_NobleDebt1")
ssqn.registerQBlock("PC_m1_Tvy_NobleDebt2")
ssqn.registerQBlock("PC_m1_Tvy_NobleDebt3")


