local scrollData = {
    -- Table 1 entries
    { item = "misc_soulgem_grand", container = "spok_ht_sg_grand" },
    { item = "misc_soulgem_common", container = "spok_ht_sg_common" },
    { item = "misc_soulgem_greater", container = "spok_ht_sg_greater" },
    { item = "misc_soulgem_petty", container = "spok_ht_sg_petty" },
    { item = "misc_soulgem_lesser", container = "spok_ht_sg_lesser" },
    { item = "sc_almsiviintervention", container = "spok_ht_scrolls_m" },
    { item = "sc_alvusiaswarping", container = "spok_ht_scrolls_m" },
    { item = "sc_argentglow", container = "spok_ht_scrolls_r" },
    { item = "sc_balefulsuffering", container = "spok_ht_scrolls_d" },
    { item = "sc_blackdeath", container = "spok_ht_scrolls_d" },
    { item = "sc_blackdespair", container = "spok_ht_scrolls_d" },
    { item = "sc_blackfate", container = "spok_ht_scrolls_d" },
    { item = "sc_blackmind", container = "spok_ht_scrolls_d" },
    { item = "sc_blackscorn", container = "spok_ht_scrolls_d" },
    { item = "sc_blacksloth", container = "spok_ht_scrolls_d" },
    { item = "sc_blackstorm", container = "spok_ht_scrolls_d" },
    { item = "sc_blackweakness", container = "spok_ht_scrolls_d" },
    { item = "sc_bloodfire", container = "spok_ht_scrolls_r" },
    { item = "sc_bloodthief", container = "spok_ht_scrolls_m" },
    { item = "sc_brevasavertedeyes", container = "spok_ht_scrolls_i" },
    { item = "sc_celerity", container = "spok_ht_scrolls_r" },
    { item = "sc_corruptarcanix", container = "spok_ht_scrolls_m" },
    { item = "sc_cureblight_ranged", container = "spok_ht_scrolls_r" },
    { item = "sc_daerirsmiracle", container = "spok_ht_scrolls_r" },
    { item = "sc_dawnsprite", container = "spok_ht_scrolls_r" },
    { item = "sc_daydenespanacea", container = "spok_ht_scrolls_r" },
    { item = "sc_daynarsairybubble", container = "spok_ht_scrolls_a" },
    { item = "sc_dedresmasterfuleye", container = "spok_ht_scrolls_i" },
    { item = "sc_didalasknack", container = "spok_ht_scrolls_c" },
    { item = "sc_divineintervention", container = "spok_ht_scrolls_m" },
    { item = "sc_drathissoulrot", container = "spok_ht_scrolls_d" },
    { item = "sc_drathiswinterguest", container = "spok_ht_scrolls_d" },
    { item = "sc_ekashslocksplitter", container = "spok_ht_scrolls_a" },
    { item = "sc_elementalburstfire", container = "spok_ht_scrolls_d" },
    { item = "sc_elementalburstfrost", container = "spok_ht_scrolls_d" },
    { item = "sc_elementalburstshock", container = "spok_ht_scrolls_d" },
    { item = "sc_elevramssty", container = "spok_ht_scrolls_i" },
    { item = "sc_fadersleadenflesh", container = "spok_ht_scrolls_a" },
    { item = "sc_feldramstrepidation", container = "spok_ht_scrolls_i" },
    { item = "sc_fiercelyroastthyenemy_unique", container = "spok_ht_scrolls_d" },
    { item = "sc_fifthbarrier", container = "spok_ht_scrolls_a" },
    { item = "sc_firstbarrier", container = "spok_ht_scrolls_a" },
    { item = "sc_flamebane", container = "spok_ht_scrolls_d" },
    { item = "sc_flameguard", container = "spok_ht_scrolls_r" },
    { item = "sc_fourthbarrier", container = "spok_ht_scrolls_a" },
    { item = "sc_fphyggisgemfeeder", container = "spok_ht_scrolls_m" },
    { item = "sc_frostbane", container = "spok_ht_scrolls_d" },
    { item = "sc_frostguard", container = "spok_ht_scrolls_r" },
    { item = "sc_galmsesseal", container = "spok_ht_scrolls_a" },
    { item = "sc_gamblersprayer", container = "spok_ht_scrolls_r" },
    { item = "sc_golnaraseyemaze", container = "spok_ht_scrolls_i" },
    { item = "sc_gonarsgoad", container = "spok_ht_scrolls_i" },
    { item = "sc_greaterdomination", container = "spok_ht_scrolls_c" },
    { item = "sc_greydeath", container = "spok_ht_scrolls_d" },
    { item = "sc_greydespair", container = "spok_ht_scrolls_d" },
    { item = "sc_greyfate", container = "spok_ht_scrolls_d" },
    { item = "sc_greymind", container = "spok_ht_scrolls_d" },
    { item = "sc_greyscorn", container = "spok_ht_scrolls_d" },
    { item = "sc_greysloth", container = "spok_ht_scrolls_d" },
    { item = "sc_greyweakness", container = "spok_ht_scrolls_d" },
    { item = "sc_healing", container = "spok_ht_scrolls_r" },
    { item = "sc_heartwise", container = "spok_ht_scrolls_r" },
    { item = "sc_hellfire", container = "spok_ht_scrolls_d" },
    { item = "sc_icarianflight", container = "spok_ht_scrolls_r" },
    { item = "sc_illneasbreath", container = "spok_ht_scrolls_d" },
    { item = "sc_inaschastening", container = "spok_ht_scrolls_d" },
    { item = "sc_inasismysticfinger", container = "spok_ht_scrolls_m" },
    { item = "sc_insight", container = "spok_ht_scrolls_r" },
    { item = "sc_invisibility", container = "spok_ht_scrolls_i" },

    -- Table 2 entries
    { item = "sc_chridittepanacea", container = "spok_ht_scrolls_r" },
    { item = "sc_bodily_restoration", container = "spok_ht_scrolls_r" },
    { item = "sc_savagetyranny", container = "spok_ht_scrolls_c" },
    { item = "sc_hiddenkiller", container = "spok_ht_scrolls_r" },
    { item = "sc_chappy_sniper_test", container = "spok_ht_scrolls_r" },
    { item = "sc_leaguestep", container = "spok_ht_scrolls_m" },
    { item = "sc_lesserdomination", container = "spok_ht_scrolls_c" },
    { item = "sc_llirosglowingeye", container = "spok_ht_scrolls_i" },
    { item = "sc_lordmhasvengeance", container = "spok_ht_scrolls_c" },
    { item = "sc_mageseye", container = "spok_ht_scrolls_m" },
    { item = "sc_mageweal", container = "spok_ht_scrolls_r" },
    { item = "sc_manarape", container = "spok_ht_scrolls_m" },
    { item = "sc_mark", container = "spok_ht_scrolls_m" },
    { item = "sc_messengerscroll", container = "spok_ht_scrolls_c" },
    { item = "sc_mindfeeder", container = "spok_ht_scrolls_m" },
    { item = "sc_mondensinstigator", container = "spok_ht_scrolls_i" },
    { item = "sc_nerusislockjaw", container = "spok_ht_scrolls_i" },
    { item = "sc_ninthbarrier", container = "spok_ht_scrolls_a" },
    { item = "sc_oathfast", container = "spok_ht_scrolls_r" },
    { item = "sc_ondusisunhinging", container = "spok_ht_scrolls_a" },
    { item = "sc_princeovsbrightball", container = "spok_ht_scrolls_i" },
    { item = "sc_psychicprison", container = "spok_ht_scrolls_m" },
    { item = "sc_purityofbody", container = "spok_ht_scrolls_r" },
    { item = "sc_radiyasicymask", container = "spok_ht_scrolls_a" },
    { item = "sc_radrenesspellbreaker", container = "spok_ht_scrolls_m" },
    { item = "sc_reddeath", container = "spok_ht_scrolls_m" },
    { item = "sc_reddespair", container = "spok_ht_scrolls_m" },
    { item = "sc_redfate", container = "spok_ht_scrolls_m" },
    { item = "sc_redmind", container = "spok_ht_scrolls_m" },
    { item = "sc_redscorn", container = "spok_ht_scrolls_m" },
    { item = "sc_redsloth", container = "spok_ht_scrolls_m" },
    { item = "sc_redweakness", container = "spok_ht_scrolls_m" },
    { item = "sc_restoration", container = "spok_ht_scrolls_r" },
    { item = "sc_reynosbeastfinder", container = "spok_ht_scrolls_m" },
    { item = "sc_reynosfins", container = "spok_ht_scrolls_a" },
    { item = "sc_salensvivication", container = "spok_ht_scrolls_r" },
    { item = "sc_savagemight", container = "spok_ht_scrolls_r" },
    { item = "sc_secondbarrier", container = "spok_ht_scrolls_a" },
    { item = "sc_selisfieryward", container = "spok_ht_scrolls_a" },
    { item = "sc_selynsmistslippers", container = "spok_ht_scrolls_a" },
    { item = "sc_sertisesporphyry", container = "spok_ht_scrolls_i" },
    { item = "sc_shockbane", container = "spok_ht_scrolls_d" },
    { item = "sc_shockguard", container = "spok_ht_scrolls_r" },
    { item = "sc_sixthbarrier", container = "spok_ht_scrolls_a" },
    { item = "sc_stormward", container = "spok_ht_scrolls_a" },
    { item = "sc_summondaedroth_hto", container = "spok_ht_scrolls_c" },
    { item = "sc_summonflameatronach", container = "spok_ht_scrolls_c" },
    { item = "sc_summonfrostatronach", container = "spok_ht_scrolls_c" },
    { item = "sc_summongoldensaint", container = "spok_ht_scrolls_c" },
    { item = "sc_summonskeletalservant", container = "spok_ht_scrolls_c" },
    { item = "sc_supremedomination", container = "spok_ht_scrolls_c" },
    { item = "sc_taldamsscorcher", container = "spok_ht_scrolls_d" },
    { item = "sc_telvinscourage", container = "spok_ht_scrolls_i" },
    { item = "sc_tendilstrembling", container = "spok_ht_scrolls_i" },
    { item = "sc_tevilspeace", container = "spok_ht_scrolls_i" },
    { item = "sc_tevralshawkshaw", container = "spok_ht_scrolls_m" },
    { item = "sc_thirdbarrier", container = "spok_ht_scrolls_a" },
    { item = "sc_tinurshoptoad", container = "spok_ht_scrolls_a" },
    { item = "sc_toususabidingbeast", container = "spok_ht_scrolls_i" },
    { item = "sc_tranasasspellmire", container = "spok_ht_scrolls_m" },
    { item = "sc_tranasasspelltrap", container = "spok_ht_scrolls_m" },
    { item = "sc_tranasasspelltwist", container = "spok_ht_scrolls_m" },
    { item = "sc_ulmjuicedasfeather", container = "spok_ht_scrolls_a" },
    { item = "sc_uthshandofheaven", container = "spok_ht_scrolls_a" },
    { item = "sc_vaerminaspromise", container = "spok_ht_scrolls_i" },
    { item = "sc_vigor", container = "spok_ht_scrolls_r" },
    { item = "sc_vitality", container = "spok_ht_scrolls_r" },
    { item = "sc_warriorsblessing", container = "spok_ht_scrolls_r" },
    { item = "sc_windform", container = "spok_ht_scrolls_a" },
    { item = "sc_windwalker", container = "spok_ht_scrolls_a" },
}

local ingredient_container_pairs = {
    { item = "ingred_alit_hide_01", container = "spok_k_alit_hide" },
    { item = "ingred_bc_ampoule_pod", container = "spok_k_ampoule_pod" },
    { item = "ingred_ash_salts_01", container = "spok_k_ash_salts" },
    { item = "ingred_ash_yam_01", container = "spok_k_ash_yam" },
    { item = "ingred_bittergreen_petals_01", container = "spok_k_bittergreen" },
    { item = "ingred_black_anther_01", container = "spok_k_black_anther" },
    { item = "ingred_black_lichen_01", container = "spok_k_black_lichen" },
    { item = "ingred_bloat_01", container = "spok_k_bloat" },
    { item = "ingred_bonemeal_01", container = "spok_k_bonemeal" },
    { item = "ingred_bread_01", container = "spok_k_bread" },
    { item = "ingred_bc_bungler's_bane", container = "spok_k_bunglers_bane" },
    { item = "ingred_chokeweed_01", container = "spok_k_chokeweed" },
    { item = "ingred_bc_coda_flower", container = "spok_k_coda_flower" },
    { item = "ingred_comberry_01", container = "spok_k_comberry" },
    { item = "ingred_corkbulb_root_01", container = "spok_k_corkbulb_root" },
    { item = "ingred_6th_corprusmeat_01", container = "spok_k_corprus_meat" },
    { item = "ingred_6th_corprusmeat_02", container = "spok_k_corprus_meat" },
    { item = "ingred_6th_corprusmeat_03", container = "spok_k_corprus_meat" },
    { item = "ingred_6th_corprusmeat_04", container = "spok_k_corprus_meat" },
    { item = "ingred_6th_corprusmeat_05", container = "spok_k_corprus_meat" },
    { item = "ingred_6th_corprusmeat_06", container = "spok_k_corprus_meat" },
    { item = "ingred_6th_corprusmeat_07", container = "spok_k_corprus_meat" },
    { item = "ingred_corprus_weepings_01", container = "spok_k_corprus_weepings" },
    { item = "ingred_crab_meat_01", container = "spok_k_crab_meat" },
    { item = "ingred_daedra_skin_01", container = "spok_k_daedra_skin" },
    { item = "ingred_daedras_heart_01", container = "spok_k_daedras_heart" },
    { item = "ingred_diamond_01", container = "spok_k_diamond" },
    { item = "ingred_dreugh_wax_01", container = "spok_k_dreugh_wax" },
    { item = "ingred_ectoplasm_01", container = "spok_k_ectoplasm" },
    { item = "ingred_emerald_01", container = "spok_k_emerald" },
    { item = "ingred_fire_petal_01", container = "spok_k_fire_petals" },
    { item = "ingred_fire_salts_01", container = "spok_k_fire_salts" },
    { item = "ingred_frost_salts_01", container = "spok_k_frost_salts" },
    { item = "ingred_ghoul_heart_01", container = "spok_k_ghoul_heart" },
    { item = "ingred_gold_kanet_01", container = "spok_k_gold_kanet" },
    { item = "ingred_gravedust_01", container = "spok_k_gravedust" },
    { item = "ingred_green_lichen_01", container = "spok_k_green_lichen" },
    { item = "ingred_guar_hide_01", container = "spok_k_guar_hide" },
    { item = "ingred_hackle-lo_leaf_01", container = "spok_k_hackle_lo" },
    { item = "ingred_heather_01", container = "spok_k_heather" },
    { item = "ingred_hound_meat_01", container = "spok_k_hound_meat" },
    { item = "ingred_human_meat_01", container = "spok_k_human_flesh" },
    { item = "ingred_bc_hypha_facia", container = "spok_k_hypha_facia" },
    { item = "ingred_kagouti_hide_01", container = "spok_k_kagouti_hide" },
    { item = "ingred_kresh_fiber_01", container = "spok_k_kresh_fiber" },
    { item = "ingred_kwama_cuttle_01", container = "spok_k_kwama_cuttle" },
    { item = "food_kwama_egg_02", container = "spok_k_large_kwama_egg" },
    { item = "ingred_russula_01", container = "spok_k_luminous_russula" },
    { item = "ingred_marshmerrow_01", container = "spok_k_marshmerrow" },
    { item = "ingred_scrib_jelly_02", container = "spok_k_scrib_jelly" },
    { item = "ingred_moon_sugar_01", container = "spok_k_moon_sugar" },
    { item = "ingred_muck_01", container = "spok_k_muck" },
    { item = "ingred_netch_leather_01", container = "spok_k_netch_leather" },
    { item = "ingred_pearl_01", container = "spok_k_pearl" },
    { item = "poison_goop00", container = "spok_k_poison" },
    { item = "ingred_racer_plumes_01", container = "spok_k_racer_plumes" },
    { item = "ingred_rat_meat_01", container = "spok_k_rat_meat" },
    { item = "ingred_raw_ebony_01", container = "spok_k_raw_ebony" },
    { item = "ingred_raw_glass_01", container = "spok_k_raw_glass" },
    { item = "ingred_red_lichen_01", container = "spok_k_red_lichen" },
    { item = "ingred_resin_01", container = "spok_k_resin" },
    { item = "ingred_gold_kanet_unique", container = "spok_k_gold_kanet" },
    { item = "ingred_roobrush_01", container = "spok_k_roobrush" },
    { item = "ingred_ruby_01", container = "spok_k_ruby" },
    { item = "ingred_saltrice_01", container = "spok_k_saltrice" },
    { item = "ingred_scales_01", container = "spok_k_scales" },
    { item = "ingred_scamp_skin_01", container = "spok_k_scamp_skin" },
    { item = "ingred_scathecraw_01", container = "spok_k_scathecraw" },
    { item = "ingred_scrap_metal_01", container = "spok_k_scrap_metal" },
    { item = "ingred_scrib_jelly_01", container = "spok_k_scrib_jelly" },
    { item = "ingred_scrib_jerky_01", container = "spok_k_scrib_jerky" },
    { item = "ingred_scuttle_01", container = "spok_k_scuttle" },
    { item = "ingred_shalk_resin_01", container = "spok_k_shalk_resin" },
    { item = "ingred_sload_soap_01", container = "spok_k_sload_soap" },
    { item = "food_kwama_egg_01", container = "spok_k_small_kwama_egg" },
    { item = "ingred_bc_spore_pod", container = "spok_k_spore_pod" },
    { item = "ingred_stoneflower_petals_01", container = "spok_k_stoneflower" },
    { item = "ingred_trama_root_01", container = "spok_k_trama_root" },
    { item = "ingred_vampire_dust_01", container = "spok_k_vampire_dust" },
    { item = "ingred_coprinus_01", container = "spok_k_violet_coprinus" },
    { item = "ingred_void_salts_01", container = "spok_k_void_salts" },
    { item = "ingred_wickwheat_01", container = "spok_k_wickwheat" },
    { item = "ingred_willow_anther_01", container = "spok_k_willow_anther" },  
      -- Tribunal (Mournhold) ingredients
    { item = "ingred_adamantium_ore_01", container = "spok_k_adamantium_ore" },
    { item = "ingred_durzog_meat_01", container = "spok_k_durzog_meat" },
    { item = "ingred_golden_sedge_01", container = "spok_k_golden_sedge" },
    { item = "ingred_horn_lily_bulb_01", container = "spok_k_horn_lily_bulb" },
    { item = "ingred_lloramor_spines_01", container = "spok_k_lloramor_spines" },
    { item = "ingred_meadow_rye_01", container = "spok_k_meadow_rye" },
    { item = "ingred_nirthfly_stalks_01", container = "spok_k_nirthfly_stalks" },
    { item = "ingred_noble_sedge_01", container = "spok_k_noble_sedge" },
    { item = "ingred_scrib_cabbage_01", container = "spok_k_scrib_cabbage" },
    { item = "ingred_sweetpulp_01", container = "spok_k_sweetpulp" },
    { item = "ingred_timsa-come-by_01", container = "spok_k_timsa_come_by" },

    -- Bloodmoon (Solstheim) ingredients
    { item = "ingred_bear_pelt", container = "spok_k_bear_pelt" },
    { item = "ingred_boar_leather", container = "spok_k_bristleback" },
    { item = "ingred_eyeball", container = "spok_k_grahl_eyeball" },
    { item = "ingred_gravetar_01", container = "spok_k_gravetar" },
    { item = "ingred_heartwood_01", container = "spok_k_heartwood" },
    { item = "ingred_holly_01", container = "spok_k_holly_berries" },
    { item = "ingred_horker_tusk_01", container = "spok_k_horker_tusk" },
    { item = "ingred_raw_Stalhrim_01", container = "spok_k_raw_stalhrim" },
    { item = "ingred_belladonna_01", container = "spok_k_ripened_belladon" },
    { item = "ingred_snowbear_pelt_unique", container = "spok_k_snow_bear_pelt" },
    { item = "ingred_snowwolf_pelt_unique", container = "spok_k_snow_wolf_pelt" },
    { item = "ingred_belladonna_02", container = "spok_k_unripened_bella" },
    { item = "ingred_wolf_pelt", container = "spok_k_wolf_pelt" },
    { item = "ingred_wolfsbane_01", container = "spok_k_wolfsbane_petals" }

}

local potionLs = {
    -- Bargain HFM
    { item = "p_fortify_fatigue_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_health_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_magicka_b", container = "spok_ht_pb_all" },
    { item = "p_restore_fatigue_b", container = "spok_ht_pb_all" },
    { item = "p_restore_health_b", container = "spok_ht_pb_all" },
    { item = "p_restore_magicka_b", container = "spok_ht_pb_all" },
    
    -- Cheap HFM
    { item = "p_fortify_fatigue_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_health_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_magicka_c", container = "spok_ht_pc_all" },
    { item = "p_restore_fatigue_c", container = "spok_ht_pc_all" },
    { item = "p_restore_health_c", container = "spok_ht_pc_all" },
    { item = "p_restore_magicka_c", container = "spok_ht_pc_all" },
    
    -- Standard HFM
    { item = "p_fortify_fatigue_s", container = "spok_ht_ps_hfm" },
    { item = "p_fortify_health_s", container = "spok_ht_ps_hfm" },
    { item = "p_fortify_magicka_s", container = "spok_ht_ps_hfm" },
    { item = "p_restore_fatigue_s", container = "spok_ht_ps_hfm" },
    { item = "p_restore_health_s", container = "spok_ht_ps_hfm" },
    { item = "p_restore_magicka_s", container = "spok_ht_ps_hfm" },
    
    -- Quality HFM
    { item = "p_fortify_fatigue_q", container = "spok_ht_pq_hfm" },
    { item = "p_fortify_health_q", container = "spok_ht_pq_hfm" },
    { item = "p_fortify_magicka_q", container = "spok_ht_pq_hfm" },
    { item = "p_restore_fatigue_q", container = "spok_ht_pq_hfm" },
    { item = "p_restore_health_q", container = "spok_ht_pq_hfm" },
    { item = "p_restore_magicka_q", container = "spok_ht_pq_hfm" },
    
    -- Exclusive HFM
    { item = "p_fortify_fatigue_e", container = "spok_ht_pe_hfm" },
    { item = "p_fortify_health_e", container = "spok_ht_pe_hfm" },
    { item = "p_fortify_magicka_e", container = "spok_ht_pe_hfm" },
    { item = "p_restore_fatigue_e", container = "spok_ht_pe_hfm" },
    { item = "p_restore_health_e", container = "spok_ht_pe_hfm" },
    { item = "p_restore_magicka_e", container = "spok_ht_pe_hfm" },
    
    -- Bargain Attributes
    { item = "p_fortify_agility_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_endurance_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_intelligence_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_luck_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_personality_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_speed_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_strength_b", container = "spok_ht_pb_all" },
    { item = "p_fortify_willpower_b", container = "spok_ht_pb_all" },
    { item = "p_restore_agility_b", container = "spok_ht_pb_all" },
    { item = "p_restore_endurance_b", container = "spok_ht_pb_all" },
    { item = "p_restore_intelligence_b", container = "spok_ht_pb_all" },
    { item = "p_restore_luck_b", container = "spok_ht_pb_all" },
    { item = "p_restore_personality_b", container = "spok_ht_pb_all" },
    { item = "p_restore_speed_b", container = "spok_ht_pb_all" },
    { item = "p_restore_strength_b", container = "spok_ht_pb_all" },
    { item = "p_restore_willpower_b", container = "spok_ht_pb_all" },
    
    -- Cheap Attributes
    { item = "p_fortify_agility_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_endurance_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_intelligence_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_luck_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_personality_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_speed_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_strength_c", container = "spok_ht_pc_all" },
    { item = "p_fortify_willpower_c", container = "spok_ht_pc_all" },
    { item = "p_restore_agility_c", container = "spok_ht_pc_all" },
    { item = "p_restore_endurance_c", container = "spok_ht_pc_all" },
    { item = "p_restore_intelligence_c", container = "spok_ht_pc_all" },
    { item = "p_restore_luck_c", container = "spok_ht_pc_all" },
    { item = "p_restore_personality_c", container = "spok_ht_pc_all" },
    { item = "p_restore_speed_c", container = "spok_ht_pc_all" },
    { item = "p_restore_strength_c", container = "spok_ht_pc_all" },
    { item = "p_restore_willpower_c", container = "spok_ht_pc_all" },
    
    -- Standard Attributes
    { item = "p_fortify_agility_s", container = "spok_ht_ps_attr" },
    { item = "p_fortify_endurance_s", container = "spok_ht_ps_attr" },
    { item = "p_fortify_intelligence_s", container = "spok_ht_ps_attr" },
    { item = "p_fortify_luck_s", container = "spok_ht_ps_attr" },
    { item = "p_fortify_personality_s", container = "spok_ht_ps_attr" },
    { item = "p_fortify_speed_s", container = "spok_ht_ps_attr" },
    { item = "p_fortify_strength_s", container = "spok_ht_ps_attr" },
    { item = "p_fortify_willpower_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_agility_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_endurance_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_intelligence_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_luck_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_personality_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_speed_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_strength_s", container = "spok_ht_ps_attr" },
    { item = "p_restore_willpower_s", container = "spok_ht_ps_attr" },
    
    -- Quality Attributes
    { item = "p_fortify_agility_q", container = "spok_ht_pq_attr" },
    { item = "p_fortify_endurance_q", container = "spok_ht_pq_attr" },
    { item = "p_fortify_intelligence_q", container = "spok_ht_pq_attr" },
    { item = "p_fortify_luck_q", container = "spok_ht_pq_attr" },
    { item = "p_fortify_personality_q", container = "spok_ht_pq_attr" },
    { item = "p_fortify_speed_q", container = "spok_ht_pq_attr" },
    { item = "p_fortify_strength_q", container = "spok_ht_pq_attr" },
    { item = "p_fortify_willpower_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_agility_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_endurance_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_intelligence_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_luck_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_personality_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_speed_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_strength_q", container = "spok_ht_pq_attr" },
    { item = "p_restore_willpower_q", container = "spok_ht_pq_attr" },

    { item = "p_fortify_agility_e", container = "spok_ht_pe_attr" },
    { item = "p_fortify_endurance_e", container = "spok_ht_pe_attr" },
    { item = "p_fortify_intelligence_e", container = "spok_ht_pe_attr" },
    { item = "p_fortify_luck_e", container = "spok_ht_pe_attr" },
    { item = "p_fortify_personality_e", container = "spok_ht_pe_attr" },
    { item = "p_fortify_speed_e", container = "spok_ht_pe_attr" },
    { item = "p_fortify_strength_e", container = "spok_ht_pe_attr" },
    { item = "p_fortify_willpower_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_agility_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_endurance_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_intelligence_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_luck_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_personality_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_speed_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_strength_e", container = "spok_ht_pe_attr" },
    { item = "p_restore_willpower_e", container = "spok_ht_pe_attr" },

    -- Flying
    { item = "p_levitation_b", container = "spok_ht_px_fly" },
    { item = "p_levitation_c", container = "spok_ht_px_fly" },
    { item = "p_levitation_s", container = "spok_ht_px_fly" },
    { item = "p_levitation_q", container = "spok_ht_px_fly" },
    { item = "p_levitation_e", container = "spok_ht_px_fly" },

    -- Cure
    { item = "p_cure_blight_s", container = "spok_ht_px_cure" },
    { item = "p_cure_common_s", container = "spok_ht_px_cure" },
    { item = "p_cure_paralyzation_s", container = "spok_ht_px_cure" },
    { item = "p_cure_poison_s", container = "spok_ht_px_cure" },

    -- Water
    { item = "p_water_breathing_s", container = "spok_ht_px_water" },
    { item = "p_water_walking_s", container = "spok_ht_px_water" },

    -- Common etc
    { item = "p_almsivi_intervention_s", container = "spok_ht_px_etc" },
    { item = "p_detect_creatures_s", container = "spok_ht_px_etc" },
    { item = "p_detect_enchantment_s", container = "spok_ht_px_etc" },
    { item = "p_detect_key_s", container = "spok_ht_px_etc" },
    { item = "p_dispel_s", container = "spok_ht_px_etc" },
    { item = "p_mark_s", container = "spok_ht_px_etc" },
    { item = "p_recall_s", container = "spok_ht_px_etc" },
    { item = "p_slowfall_s", container = "spok_ht_px_etc" },
    { item = "p_telekinesis_s", container = "spok_ht_px_etc" },

    -- Fire Resistance
    { item = "p_fire_resistance_b", container = "spok_ht_pb_all" },
    { item = "p_fire_resistance_c", container = "spok_ht_pc_all" },
    { item = "p_fire_resistance_s", container = "spok_ht_ps_etc" },
    { item = "p_fire_resistance_q", container = "spok_ht_pq_etc" },
    { item = "p_fire_resistance_e", container = "spok_ht_pe_etc" },

    -- Fire Shield
    { item = "p_fire_shield_b", container = "spok_ht_pb_all" },
    { item = "p_fire_shield_c", container = "spok_ht_pc_all" },
    { item = "p_fire_shield_s", container = "spok_ht_ps_etc" },
    { item = "p_fire_shield_q", container = "spok_ht_pq_etc" },
    { item = "p_fire_shield_e", container = "spok_ht_pe_etc" },

    -- Frost Resistance
    { item = "p_frost_resistance_b", container = "spok_ht_pb_all" },
    { item = "p_frost_resistance_c", container = "spok_ht_pc_all" },
    { item = "p_frost_resistance_s", container = "spok_ht_ps_etc" },
    { item = "p_frost_resistance_q", container = "spok_ht_pq_etc" },
    { item = "p_frost_resistance_e", container = "spok_ht_pe_etc" },

    -- Frost Shield
    { item = "p_frost_shield_b", container = "spok_ht_pb_all" },
    { item = "p_frost_shield_c", container = "spok_ht_pc_all" },
    { item = "p_frost_shield_s", container = "spok_ht_ps_etc" },
    { item = "p_frost_shield_q", container = "spok_ht_pq_etc" },
    { item = "p_frost_shield_e", container = "spok_ht_pe_etc" },

    -- Shock Resistance
    { item = "p_shock_resistance_b", container = "spok_ht_pb_all" },
    { item = "p_shock_resistance_c", container = "spok_ht_pc_all" },
    { item = "p_shock_resistance_s", container = "spok_ht_ps_etc" },
    { item = "p_shock_resistance_q", container = "spok_ht_pq_etc" },
    { item = "p_shock_resistance_e", container = "spok_ht_pe_etc" },

    -- Lightning Shield
    { item = "p_lightning shield_b", container = "spok_ht_pb_all" },
    { item = "p_lightning shield_c", container = "spok_ht_pc_all" },
    { item = "p_lightning shield_s", container = "spok_ht_ps_etc" },
    { item = "p_lightning shield_q", container = "spok_ht_pq_etc" },
    { item = "p_lightning shield_e", container = "spok_ht_pe_etc" },

    -- Disease Resistance
    { item = "p_disease_resistance_b", container = "spok_ht_pb_all" },
    { item = "p_disease_resistance_c", container = "spok_ht_pc_all" },
    { item = "p_disease_resistance_s", container = "spok_ht_ps_etc" },
    { item = "p_disease_resistance_q", container = "spok_ht_pq_etc" },
    { item = "p_disease_resistance_e", container = "spok_ht_pe_etc" },

    -- Magicka Resistance
    { item = "p_magicka_resistance_b", container = "spok_ht_pb_all" },
    { item = "p_magicka_resistance_c", container = "spok_ht_pc_all" },
    { item = "p_magicka_resistance_s", container = "spok_ht_ps_etc" },
    { item = "p_magicka_resistance_q", container = "spok_ht_pq_etc" },
    { item = "p_magicka_resistance_e", container = "spok_ht_pe_etc" },

    -- Poison Resistance
    { item = "p_poison_resistance_b", container = "spok_ht_pb_all" },
    { item = "p_poison_resistance_c", container = "spok_ht_pc_all" },
    { item = "p_poison_resistance_s", container = "spok_ht_ps_etc" },
    { item = "p_poison_resistance_q", container = "spok_ht_pq_etc" },
    { item = "p_poison_resistance_e", container = "spok_ht_pe_etc" },

    -- Quality Drain Attributes and Single Extras
    { item = "p_fortify_attack_e", container = "spok_ht_pe_etc" },
    { item = "p_drain_agility_q", container = "spok_ht_pq_etc" },
    { item = "p_drain_endurance_q", container = "spok_ht_pq_etc" },
    { item = "p_drain_intelligence_q", container = "spok_ht_pq_etc" },
    { item = "p_drain_luck_q", container = "spok_ht_pq_etc" },
    { item = "p_drain_magicka_q", container = "spok_ht_pq_etc" },
    { item = "p_drain_personality_q", container = "spok_ht_pq_etc" },
    { item = "p_drain_speed_q", container = "spok_ht_pq_etc" },
    { item = "p_drain_strength_q", container = "spok_ht_pq_etc" },
    { item = "p_drain willpower_q", container = "spok_ht_pq_etc" },
    { item = "p_burden_b", container = "spok_ht_pb_all" },
    { item = "p_burden_c", container = "spok_ht_pc_all" },
    { item = "p_burden_s", container = "spok_ht_ps_etc" },
    { item = "p_burden_q", container = "spok_ht_pq_etc" },
    { item = "p_burden_e", container = "spok_ht_pe_etc" },

    -- Chameleon
    { item = "p_chameleon_b", container = "spok_ht_pb_all" },
    { item = "p_chameleon_c", container = "spok_ht_pc_all" },
    { item = "p_chameleon_s", container = "spok_ht_ps_etc" },
    { item = "p_chameleon_q", container = "spok_ht_pq_etc" },
    { item = "p_chameleon_e", container = "spok_ht_pe_etc" },

    -- Invisibility
    { item = "p_invisibility_b", container = "spok_ht_pb_all" },
    { item = "p_invisibility_c", container = "spok_ht_pc_all" },
    { item = "p_invisibility_s", container = "spok_ht_ps_etc" },
    { item = "p_invisibility_q", container = "spok_ht_pq_etc" },
    { item = "p_invisibility_e", container = "spok_ht_pe_etc" },

    -- Jump
    { item = "p_jump_b", container = "spok_ht_pb_all" },
    { item = "p_jump_c", container = "spok_ht_pc_all" },
    { item = "p_jump_s", container = "spok_ht_ps_etc" },
    { item = "p_jump_q", container = "spok_ht_pq_etc" },
    { item = "p_jump_e", container = "spok_ht_pe_etc" },

    -- Light
    { item = "p_light_b", container = "spok_ht_pb_all" },
    { item = "p_light_c", container = "spok_ht_pc_all" },
    { item = "p_light_s", container = "spok_ht_ps_etc" },
    { item = "p_light_q", container = "spok_ht_pq_etc" },
    { item = "p_light_e", container = "spok_ht_pe_etc" },

    -- Night-Eye
    { item = "p_night-eye_b", container = "spok_ht_pb_all" },
    { item = "p_night-eye_c", container = "spok_ht_pc_all" },
    { item = "p_night-eye_s", container = "spok_ht_ps_etc" },
    { item = "p_night-eye_q", container = "spok_ht_pq_etc" },
    { item = "p_night-eye_e", container = "spok_ht_pe_etc" },

    -- Paralyze
    { item = "p_paralyze_b", container = "spok_ht_pb_all" },
    { item = "p_paralyze_c", container = "spok_ht_pc_all" },
    { item = "p_paralyze_s", container = "spok_ht_ps_etc" },
    { item = "p_paralyze_q", container = "spok_ht_pq_etc" },
    { item = "p_paralyze_e", container = "spok_ht_pe_etc" },

    -- Reflect
    { item = "p_reflection_b", container = "spok_ht_pb_all" },
    { item = "p_reflection_c", container = "spok_ht_pc_all" },
    { item = "p_reflection_s", container = "spok_ht_ps_etc" },
    { item = "p_reflection_q", container = "spok_ht_pq_etc" },
    { item = "p_reflection_e", container = "spok_ht_pe_etc" },

    -- Silence
    { item = "p_silence_b", container = "spok_ht_pb_all" },
    { item = "p_silence_c", container = "spok_ht_pc_all" },
    { item = "p_silence_s", container = "spok_ht_ps_etc" },
    { item = "p_silence_q", container = "spok_ht_pq_etc" },
    { item = "p_silence_e", container = "spok_ht_pe_etc" },

    -- Spell Absorption
    { item = "p_spell_absorption_b", container = "spok_ht_pb_all" },
    { item = "p_spell_absorption_c", container = "spok_ht_pc_all" },
    { item = "p_spell_absorption_s", container = "spok_ht_ps_etc" },
    { item = "p_spell_absorption_q", container = "spok_ht_pq_etc" },
    { item = "p_spell_absorption_e", container = "spok_ht_pe_etc" },

    -- Feather
    { item = "p_feather_b", container = "spok_ht_pb_all" },
    { item = "p_feather_c", container = "spok_ht_pc_all" },
    { item = "p_feather_q", container = "spok_ht_pq_etc" },
    { item = "p_feather_e", container = "spok_ht_pe_etc" },

    -- Swift Swim
    { item = "p_swift_swim_b", container = "spok_ht_pb_all" },
    { item = "p_swift_swim_c", container = "spok_ht_pc_all" },
    { item = "p_swift_swim_q", container = "spok_ht_pq_etc" },
    { item = "p_swift_swim_e", container = "spok_ht_pe_etc" },


}
return { scrollData = scrollData, ingredient_container_pairs = ingredient_container_pairs, potionLs = potionLs }