--[[
    Toxicology! — Settings Page
    MENU-scope script. Registers all toggleable settings.
]]

local I = require('openmw.interfaces')

local MODNAME = 'Toxicology'

I.Settings.registerPage {
    key = MODNAME,
    l10n = MODNAME,
    name = 'PageName',
    description = 'PageDescription',
}

I.Settings.registerGroup {
    key = 'Settings_' .. MODNAME,
    page = MODNAME,
    l10n = MODNAME,
    name = 'SettingsName',
    description = 'SettingsDescription',
    permanentStorage = true,
    settings = {
        {
            key = 'enabled',
            renderer = 'checkbox',
            name = 'SettingEnabled',
            description = 'SettingEnabledDescription',
            default = true,
        },
        {
            key = 'blockInCombat',
            renderer = 'checkbox',
            name = 'SettingBlockInCombat',
            description = 'SettingBlockInCombatDescription',
            default = true,
        },
        {
            key = 'ignoreAlcoholPotions',
            renderer = 'checkbox',
            name = 'SettingIgnoreAlcoholPotions',
            description = 'SettingIgnoreAlcoholPotionsDescription',
            default = true,
        },
        {
            key = 'warnOverwrite',
            renderer = 'checkbox',
            name = 'SettingWarnOverwrite',
            description = 'SettingWarnOverwriteDescription',
            default = true,
        },
    },
}

I.Settings.registerGroup {
    key = 'Settings_' .. MODNAME .. '_Skill',
    page = MODNAME,
    l10n = MODNAME,
    name = 'SkillGroupName',
    description = 'SkillGroupDescription',
    permanentStorage = true,
    settings = {
        {
            key = 'enableRaceBonuses',
            renderer = 'checkbox',
            name = 'SettingEnableRaceBonuses',
            description = 'SettingEnableRaceBonusesDescription',
            default = true,
        },
        {
            key = 'enableClassBonus',
            renderer = 'checkbox',
            name = 'SettingEnableClassBonus',
            description = 'SettingEnableClassBonusDescription',
            default = true,
        },
        {
            key = 'enableSkillBooks',
            renderer = 'checkbox',
            name = 'SettingEnableSkillBooks',
            description = 'SettingEnableSkillBooksDescription',
            default = true,
        },
        {
            key = 'xpOnApply',
            renderer = 'checkbox',
            name = 'SettingXpOnApply',
            description = 'SettingXpOnApplyDescription',
            default = true,
        },
        {
            key = 'xpOnStrike',
            renderer = 'checkbox',
            name = 'SettingXpOnStrike',
            description = 'SettingXpOnStrikeDescription',
            default = true,
        },
        {
            key = 'xpOnKill',
            renderer = 'checkbox',
            name = 'SettingXpOnKill',
            description = 'SettingXpOnKillDescription',
            default = true,
        },
        {
            key = 'xpOnBrew',
            renderer = 'checkbox',
            name = 'SettingXpOnBrew',
            description = 'SettingXpOnBrewDescription',
            default = true,
        },
        {
            key = 'xpMultiplier',
            renderer = 'number',
            name = 'SettingXpMultiplier',
            description = 'SettingXpMultiplierDescription',
            default = 100,
            argument = { min = 0, max = 500, integer = true },
        },
    },
}

I.Settings.registerGroup {
    key = 'Settings_' .. MODNAME .. '_Perks',
    page = MODNAME,
    l10n = MODNAME,
    name = 'PerksGroupName',
    description = 'PerksGroupDescription',
    permanentStorage = true,
    settings = {
        {
            key = 'enableAllPerks',
            renderer = 'checkbox',
            name = 'SettingEnableAllPerks',
            description = 'SettingEnableAllPerksDescription',
            default = true,
        },
        {
            key = 'enableEfficientCoating',
            renderer = 'checkbox',
            name = 'SettingEnableEfficientCoating',
            description = 'SettingEnableEfficientCoatingDescription',
            default = true,
        },
        {
            key = 'enableCompoundBlend',
            renderer = 'checkbox',
            name = 'SettingEnableCompoundBlend',
            description = 'SettingEnableCompoundBlendDescription',
            default = true,
        },
        {
            key = 'enableMasterCoating',
            renderer = 'checkbox',
            name = 'SettingEnableMasterCoating',
            description = 'SettingEnableMasterCoatingDescription',
            default = true,
        },
        {
            key = 'enableToxicPrecision',
            renderer = 'checkbox',
            name = 'SettingEnableToxicPrecision',
            description = 'SettingEnableToxicPrecisionDescription',
            default = true,
        },
    },
}

I.Settings.registerGroup {
    key = 'Settings_' .. MODNAME .. '_Distribution',
    page = MODNAME,
    l10n = MODNAME,
    name = 'DistributionGroupName',
    description = 'DistributionGroupDescription',
    permanentStorage = true,
    settings = {
        {
            key = 'enableExistingPoisonDistribution',
            renderer = 'checkbox',
            name = 'SettingEnableExistingPoisonDistribution',
            description = 'SettingEnableExistingPoisonDistributionDescription',
            default = true,
        },
        {
            key = 'distributeExistingPoisonsToContainers',
            renderer = 'checkbox',
            name = 'SettingDistributeExistingPoisonsToContainers',
            description = 'SettingDistributeExistingPoisonsToContainersDescription',
            default = true,
        },
        {
            key = 'distributeExistingPoisonsToMerchants',
            renderer = 'checkbox',
            name = 'SettingDistributeExistingPoisonsToMerchants',
            description = 'SettingDistributeExistingPoisonsToMerchantsDescription',
            default = true,
        },
        {
            key = 'allowMixedEffectPoisons',
            renderer = 'checkbox',
            name = 'SettingAllowMixedEffectPoisons',
            description = 'SettingAllowMixedEffectPoisonsDescription',
            default = true,
        },
        {
            key = 'existingPoisonMerchantStock',
            renderer = 'number',
            name = 'SettingExistingPoisonMerchantStock',
            description = 'SettingExistingPoisonMerchantStockDescription',
            default = 2,
            argument = { min = 1, max = 10, integer = true },
        },
        {
            key = 'existingPoisonContainerChance',
            renderer = 'number',
            name = 'SettingExistingPoisonContainerChance',
            description = 'SettingExistingPoisonContainerChanceDescription',
            default = 0.10,
            argument = { min = 0, max = 1, step = 0.01 },
        },
    },
}

I.Settings.registerGroup {
    key = 'Settings_' .. MODNAME .. '_UI',
    page = MODNAME,
    l10n = MODNAME,
    name = 'UiGroupName',
    description = 'UiGroupDescription',
    permanentStorage = true,
    settings = {
        {
            key = 'showTooltip',
            renderer = 'checkbox',
            name = 'SettingShowTooltip',
            description = 'SettingShowTooltipDescription',
            default = true,
        },
        {
            key = 'showHudIndicator',
            renderer = 'checkbox',
            name = 'SettingShowHudIndicator',
            description = 'SettingShowHudIndicatorDescription',
            default = true,
        },
        {
            key = 'hudIndicatorLockPosition',
            renderer = 'checkbox',
            name = 'SettingHudIndicatorLockPosition',
            description = 'SettingHudIndicatorLockPositionDescription',
            default = false,
        },
        {
            key = 'hudIndicatorIconSize',
            renderer = 'number',
            name = 'SettingHudIndicatorIconSize',
            description = 'SettingHudIndicatorIconSizeDescription',
            default = 18,
            argument = { min = 8, max = 96, integer = true },
        },
        {
            key = 'hudIndicatorX',
            renderer = 'number',
            name = 'SettingHudIndicatorX',
            description = 'SettingHudIndicatorXDescription',
            default = 0,
            argument = { min = 0, max = 10000, integer = true },
        },
        {
            key = 'hudIndicatorY',
            renderer = 'number',
            name = 'SettingHudIndicatorY',
            description = 'SettingHudIndicatorYDescription',
            default = 0,
            argument = { min = 0, max = 10000, integer = true },
        },
        {
            key = 'alchemyGatedTooltip',
            renderer = 'checkbox',
            name = 'SettingAlchemyGatedTooltip',
            description = 'SettingAlchemyGatedTooltipDescription',
            default = true,
        },
        {
            key = 'showMechanicTooltips',
            renderer = 'checkbox',
            name = 'SettingShowMechanicTooltips',
            description = 'SettingShowMechanicTooltipsDescription',
            default = true,
        },
        {
            key = 'showPerkTooltips',
            renderer = 'checkbox',
            name = 'SettingShowPerkTooltips',
            description = 'SettingShowPerkTooltipsDescription',
            default = true,
        },
        {
            key = 'tooltipUnlockedOnly',
            renderer = 'checkbox',
            name = 'SettingTooltipUnlockedOnly',
            description = 'SettingTooltipUnlockedOnlyDescription',
            default = false,
        },
        {
            key = 'hitVfx',
            renderer = 'checkbox',
            name = 'SettingHitVfx',
            description = 'SettingHitVfxDescription',
            default = true,
        },
        {
            key = 'hitSound',
            renderer = 'checkbox',
            name = 'SettingHitSound',
            description = 'SettingHitSoundDescription',
            default = true,
        },
        {
            key = 'showRangedCoatingSpentMessage',
            renderer = 'checkbox',
            name = 'SettingShowRangedCoatingSpentMessage',
            description = 'SettingShowRangedCoatingSpentMessageDescription',
            default = false,
        },
        {
            key = 'perkMessageStyle',
            renderer = 'number',
            name = 'SettingPerkMessageStyle',
            description = 'SettingPerkMessageStyleDescription',
            default = 1,
            argument = { integer = true, min = 0, max = 2 },
        },
        {
            key = 'perkPopupDetail',
            renderer = 'number',
            name = 'SettingPerkPopupDetail',
            description = 'SettingPerkPopupDetailDescription',
            default = 0,
            argument = { integer = true, min = 0, max = 1 },
        },
        {
            key = 'hideSensoryPerkPopups',
            renderer = 'checkbox',
            name = 'SettingHideSensoryPerkPopups',
            description = 'SettingHideSensoryPerkPopupsDescription',
            default = false,
        },
        {
            key = 'popupPosition',
            renderer = 'number',
            name = 'SettingPopupPosition',
            description = 'SettingPopupPositionDescription',
            default = 4,
            argument = { integer = true, min = 0, max = 4 },
        },
        {
            key = 'popupDuration',
            renderer = 'number',
            name = 'SettingPopupDuration',
            description = 'SettingPopupDurationDescription',
            default = 1.35,
            argument = { min = 0.5, max = 10, step = 0.05 },
        },
        {
            key = 'popupMaxVisible',
            renderer = 'number',
            name = 'SettingPopupMaxVisible',
            description = 'SettingPopupMaxVisibleDescription',
            default = 5,
            argument = { integer = true, min = 1, max = 10 },
        },
        {
            key = 'popupColourPreset',
            renderer = 'number',
            name = 'SettingPopupColourPreset',
            description = 'SettingPopupColourPresetDescription',
            default = 0,
            argument = { integer = true, min = 0, max = 1 },
        },
        {
            key = 'perkMessageTextR',
            renderer = 'number',
            name = 'SettingPerkMessageTextR',
            description = 'SettingPerkMessageTextRDescription',
            default = 190,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageTextG',
            renderer = 'number',
            name = 'SettingPerkMessageTextG',
            description = 'SettingPerkMessageTextGDescription',
            default = 0,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageTextB',
            renderer = 'number',
            name = 'SettingPerkMessageTextB',
            description = 'SettingPerkMessageTextBDescription',
            default = 194,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageShadowR',
            renderer = 'number',
            name = 'SettingPerkMessageShadowR',
            description = 'SettingPerkMessageShadowRDescription',
            default = 0,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageShadowG',
            renderer = 'number',
            name = 'SettingPerkMessageShadowG',
            description = 'SettingPerkMessageShadowGDescription',
            default = 77,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageShadowB',
            renderer = 'number',
            name = 'SettingPerkMessageShadowB',
            description = 'SettingPerkMessageShadowBDescription',
            default = 42,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'debugMessages',
            renderer = 'checkbox',
            name = 'SettingDebugMessages',
            description = 'SettingDebugMessagesDescription',
            default = false,
        },
        {
            key = 'debugCombatMessages',
            renderer = 'checkbox',
            name = 'SettingDebugCombatMessages',
            description = 'SettingDebugCombatMessagesDescription',
            default = false,
        },
        {
            key = 'debugDistributionMessages',
            renderer = 'checkbox',
            name = 'SettingDebugDistributionMessages',
            description = 'SettingDebugDistributionMessagesDescription',
            default = false,
        },
        {
            key = 'debugUiMessages',
            renderer = 'checkbox',
            name = 'SettingDebugUiMessages',
            description = 'SettingDebugUiMessagesDescription',
            default = false,
        },
        {
            key = 'debugXpMessages',
            renderer = 'checkbox',
            name = 'SettingDebugXpMessages',
            description = 'SettingDebugXpMessagesDescription',
            default = false,
        },
        {
            key = 'debugActorMessages',
            renderer = 'checkbox',
            name = 'SettingDebugActorMessages',
            description = 'SettingDebugActorMessagesDescription',
            default = false,
        },
        {
            key = 'debugIntegrationMessages',
            renderer = 'checkbox',
            name = 'SettingDebugIntegrationMessages',
            description = 'SettingDebugIntegrationMessagesDescription',
            default = false,
        },
    },
}
