local I = require("openmw.interfaces")
local types = require("openmw.types")

local greenPactPlayers = {}
-- extrected from Sun's Dusk
-- thanks hyacinth
-- supported mods:
-- - Devilish Vampire Overhaul
-- - Expanded Loot
-- - Hackle-lo Smoke
-- - Hunterwind
-- - Uvirith's Legacy
-- - Starwind
-- - The Tea Mod
-- - Tamriel_Data
-- - OAAB_Data
local gpIngredients = {
    ["food_kwama_egg_01"]               = true,
    ["food_kwama_egg_02"]               = true,
    ["ingred_6th_corprusmeat_01"]       = true,
    ["ingred_6th_corprusmeat_02"]       = true,
    ["ingred_6th_corprusmeat_03"]       = true,
    ["ingred_6th_corprusmeat_04"]       = true,
    ["ingred_6th_corprusmeat_05"]       = true,
    ["ingred_6th_corprusmeat_06"]       = true,
    ["ingred_6th_corprusmeat_07"]       = true,
    ["ingred_adamantium_ore_01"]        = true,
    ["1foodcliffracerwing"]             = true,
    ["1foodguarjerky"]                  = true,
    ["1foodomlet"]                      = true,
    ["1foodscrib"]                      = true,
    ["1foodscribleg"]                   = true,
    ["ingred_ash_salts_01"]             = true,
    ["nom_swamp_oil"]                   = true,
    ["ingred_bonemeal_01"]              = true,
    ["ingred_crab_meat_01"]             = true,
    ["ingred_cursed_daedras_heart_01"]  = true,
    ["ingred_dae_cursed_diamond_01"]    = true,
    ["ingred_dae_cursed_emerald_01"]    = true,
    ["ingred_dae_cursed_pearl_01"]      = true,
    ["ingred_dae_cursed_raw_ebony_01"]  = true,
    ["ingred_dae_cursed_ruby_01"]       = true,
    ["ingred_daedras_heart_01"]         = true,
    ["ingred_diamond_01"]               = true,
    ["ingred_durzog_meat_01"]           = true,
    ["ingred_ectoplasm_01"]             = true,
    ["ingred_emerald_01"]               = true,
    ["ingred_eyeball"]                  = true,
    ["ingred_fire_salts_01"]            = true,
    ["ingred_frost_salts_01"]           = true,
    ["ingred_ghoul_heart_01"]           = true,
    ["ingred_gravedust_01"]             = true,
    ["ingred_gravetar_01"]              = true,
    ["ab01ingred_bird_meat"]            = true,
    ["ab01ingred_egg02"]                = true,
    ["ab01ingred_turtlemeat"]           = true,
    ["ashfall_meat_alit"]               = true,
    ["ashfall_meat_guar"]               = true,
    ["ashfall_meat_kag"]                = true,
    ["ashfall_meat_racer"]              = true,
    ["ashfall_meat_sfish"]              = true,
    ["cheese3"]                         = true,
    ["chickenbreastfood1"]              = true,
    ["hb_alphynfeather"]                = true,
    ["hb_alphynmeat"]                   = true,
    ["hb_animal_eye_clumsy"]            = true,
    ["hb_animal_eye_fine"]              = true,
    ["hb_animal_eye_mediocre"]          = true,
    ["hb_animal_eye_perfect"]           = true,
    ["hb_animalfat"]                    = true,
    ["hb_animalheart"]                  = true,
    ["hb_animalteeth_misc"]             = true,
    ["hb_aspismeat"]                    = true,
    ["hb_baitrandom"]                   = true,
    ["hb_bearmeat"]                     = true,
    ["hb_blackbearskin"]                = true,
    ["ingred_hound_meat_01"]            = true,
    ["hb_boarfurpelt"]                  = true,
    ["ingred_human_meat_01"]            = true,
    ["hb_cervidhide"]                   = true,
    ["hb_crab_eggs_roe"]                = true,
    ["hb_fish_eggs_roe"]                = true,
    ["hb_fishbaitmeat"]                 = true,
    ["hb_frogmeat"]                     = true,
    ["hb_frosttrollear"]                = true,
    ["hb_goathorn"]                     = true,
    ["hb_goatmeat"]                     = true,
    ["hb_goatpelt"]                     = true,
    ["hb_goatpeltmountain"]             = true,
    ["hb_grahlpelt"]                    = true,
    ["hb_guartongue"]                   = true,
    ["hb_horkerfurpelt"]                = true,
    ["hb_horsehide"]                    = true,
    ["hb_ingred_alit_hide_improved"]    = true,
    ["hb_ingred_guar_hide_improved"]    = true,
    ["hb_ingred_kagouti_hide_improved"] = true,
    ["hb_insectmeat"]                   = true,
    ["hb_kagouti_horn"]                 = true,
    ["hb_netchbettyjelly"]              = true,
    ["hb_netchbulljelly"]               = true,
    ["hb_netchgland"]                   = true,
    ["hb_netchleatherimproved"]         = true,
    ["hb_normalbearskin"]               = true,
    ["hb_normalwolfskin"]               = true,
    ["hb_plaguebearskin"]               = true,
    ["hb_plaguewolfskin"]               = true,
    ["hb_ratfurpelt"]                   = true,
    ["hb_snakemeat"]                    = true,
    ["hb_snowbearskin"]                 = true,
    ["hb_snowwolfskin"]                 = true,
    ["hb_stridentmeat"]                 = true,
    ["ingred_kwama_cuttle_01"]          = true,
    ["hb_tanthameat"]                   = true,
    ["hb_trollpelt"]                    = true,
    ["hb_wolfmeat"]                     = true,
    ["hb_wormmouthtongue"]              = true,
    ["hb_yethbugmeat"]                  = true,
    ["ingred_pearl_01"]                 = true,
    ["ingred_rat_meat_01"]              = true,
    ["ingred_raw_ebony_01"]             = true,
    ["ingred_raw_glass_01"]             = true,
    ["ingred_raw_stalhrim_01"]          = true,
    ["ingred_ruby_01"]                  = true,
    ["ingred_scales_01"]                = true,
    ["ingred_bear_meat_sa"]             = true,
    ["ingred_scrap_metal_01"]           = true,
    ["ingred_scrib_jelly_01"]           = true,
    ["ingred_scrib_jerky_01"]           = true,
    ["ingred_scuttle_01"]               = true,
    ["ingred_shalk_resin_01"]           = true,
    ["ingred_vampire_dust_01"]          = true,
    ["ingred_void_salts_01"]            = true,
    ["ingred_wolf_heart"]               = true,
    ["ingred_dragon_meat_mwa"]          = true,
    ["ab_ingcrea_dungcake"]             = true,
    ["ab_ingcrea_guarmeat_01"]          = true,
    ["ab_ingcrea_horsemeat01"]          = true,
    ["ab_ingcrea_kwamaeggblighted"]     = true,
    ["ab_ingcrea_kwamapoison"]          = true,
    ["ab_ingcrea_ogrimlard"]            = true,
    ["ab_ingcrea_sfmeat_01"]            = true,
    ["ab_ingcrea_spidermilk"]           = true,
    ["ab_ingcrea_spidervenom"]          = true,
    ["ab_ingcrea_sturgeonmeat01"]       = true,
    ["ab_ingcrea_sturgeonmeat02"]       = true,
    ["ab_ingcrea_sturgeonmeat03"]       = true,
    ["ab_ingcrea_sturgeonroe"]          = true,
    ["ingred_mouse_meat_mva"]           = true,
    ["ab_ingfood_kwamaeggcentcut"]      = true,
    ["ab_ingfood_kwamaeggcentwrap"]     = true,
    ["ab_ingfood_kwamaeggspoillarge"]   = true,
    ["ab_ingfood_kwamaeggspoilsmall"]   = true,
    ["ab_ingfood_kwamaloaf"]            = true,
    ["ab_ingfood_kwamaloafslice"]       = true,
    ["t_com_potion_daedricichor_e"]     = true,
    ["t_com_potion_dragonblood"]        = true,
    ["ingred_wolf_meat_sa"]             = true,
    ["nom_food_bittersweet"]            = true,
    ["nom_food_cheese"]                 = true,
    ["nom_food_cheese2"]                = true,
    ["nom_food_cheese3"]                = true,
    ["nom_food_cheese4"]                = true,
    ["nom_food_cheese5"]                = true,
    ["nom_food_chickenleg1"]            = true,
    ["nom_food_chickenleg1_cook"]       = true,
    ["nom_food_crab_slice"]             = true,
    ["nom_food_egg_boil"]               = true,
    ["nom_food_egg2"]                   = true,
    ["nom_food_fish"]                   = true,
    ["nom_food_fish_fat_01"]            = true,
    ["nom_food_fish_fat_02"]            = true,
    ["nom_food_fried_fish"]             = true,
    ["nom_food_grilled_fish"]           = true,
    ["nom_food_guar_rib"]               = true,
    ["nom_food_guar_rib_grill"]         = true,
    ["nom_food_guar_rib_succ"]          = true,
    ["nom_food_ham"]                    = true,
    ["nom_food_jerky_guar"]             = true,
    ["nom_food_meat"]                   = true,
    ["nom_food_meat_grilled"]           = true,
    ["nom_food_meat_grilled2"]          = true,
    ["nom_food_omelette"]               = true,
    ["nom_food_omelette_crab"]          = true,
    ["t_ingcrea_angelfish_01"]          = true,
    ["t_ingcrea_astraljellyfish_01"]    = true,
    ["nom_food_racer_morsel"]           = true,
    ["t_ingcrea_barracudasteak_01"]     = true,
    ["t_ingcrea_barracudatailfin_01"]   = true,
    ["t_ingcrea_butterflywingcyr_01"]   = true,
    ["t_ingcrea_butterflywingcyr_02"]   = true,
    ["t_ingcrea_butterflywingcyr_03"]   = true,
    ["t_ingcrea_butterflywingcyr_04"]   = true,
    ["t_ingcrea_butterflywingcyr_05"]   = true,
    ["t_ingcrea_butterflywingcyr_06"]   = true,
    ["t_ingcrea_butterflywingsky_01"]   = true,
    ["t_ingcrea_butterflywingsky_02"]   = true,
    ["t_ingcrea_butterflywingsky_03"]   = true,
    ["t_ingcrea_butterflywingsky_04"]   = true,
    ["t_ingcrea_clammeat"]              = true,
    ["t_ingcrea_daedricbateye_01"]      = true,
    ["t_ingcrea_duskyparrotfish_01"]    = true,
    ["t_ingcrea_dwyrmgland"]            = true,
    ["t_ingcrea_eyestar_01"]            = true,
    ["t_ingcrea_frogeye_01"]            = true,
    ["nom_food_roasted_fish"]           = true,
    ["nom_food_roasted_meat"]           = true,
    ["nom_food_salted_fish"]            = true,
    ["nom_food_sausage_guar"]           = true,
    ["nom_food_sausage_mix"]            = true,
    ["nom_food_sausage_sentinel"]       = true,
    ["nom_food_skewer_kag"]             = true,
    ["nom_food_soup_rat"]               = true,
    ["nom_food_soup_turtle"]            = true,
    ["nom_salt"]                        = true,
    ["hb_alitblood"]                    = true,
    ["hb_alphynblood"]                  = true,
    ["hb_animalblood"]                  = true,
    ["hb_aspisblood"]                   = true,
    ["hb_bearblood"]                    = true,
    ["hb_boarblood"]                    = true,
    ["hb_cervidblood"]                  = true,
    ["t_ingcrea_hoomegg_01"]            = true,
    ["hb_dreughblood"]                  = true,
    ["hb_frogblood"]                    = true,
    ["hb_goatblood"]                    = true,
    ["hb_grahlblood"]                   = true,
    ["hb_guarblood"]                    = true,
    ["hb_hemolymph_vial"]               = true,
    ["hb_horkerblood"]                  = true,
    ["hb_horseblood"]                   = true,
    ["hb_kagoutiblood"]                 = true,
    ["hb_mooncrabblod"]                 = true,
    ["hb_mudcrabblood"]                 = true,
    ["hb_muskratblood"]                 = true,
    ["hb_nixhoundblood"]                = true,
    ["hb_racerblood"]                   = true,
    ["hb_ratblood"]                     = true,
    ["hb_scribblood"]                   = true,
    ["hb_stridentblood"]                = true,
    ["hb_tanthablood"]                  = true,
    ["hb_trollblood"]                   = true,
    ["hb_venom"]                        = true,
    ["hb_wolfblood"]                    = true,
    ["hb_wormmouthblood"]               = true,
    ["t_ingcrea_hoppermeat"]            = true,
    ["t_ingcrea_humanheart"]            = true,
    ["t_ingcrea_icewraithteeth_01"]     = true,
    ["t_ingcrea_koboldtongue_01"]       = true,
    ["t_ingcrea_kwoomegg_01"]           = true,
    ["t_ingcrea_lichdust_01"]           = true,
    ["t_ingcrea_meatdark_01"]           = true,
    ["t_ingcrea_meathoney_01"]          = true,
    ["t_ingcrea_moonmothwing_01"]       = true,
    ["t_ingcrea_mothwingcyr_02"]        = true,
    ["t_ingcrea_mothwingcyr_03"]        = true,
    ["t_ingcrea_mothwingcyr_04"]        = true,
    ["t_ingcrea_mothwingcyr_05"]        = true,
    ["t_ingcrea_mothwingcyr_06"]        = true,
    ["t_ingcrea_mothwingmw_01"]         = true,
    ["t_ingcrea_mothwingmw_02"]         = true,
    ["t_ingcrea_mothwingmw_03"]         = true,
    ["t_ingcrea_mothwingsky_01"]        = true,
    ["t_ingcrea_mothwingsky_02"]        = true,
    ["t_ingcrea_mothwingsky_03"]        = true,
    ["t_ingcrea_mothwingsky_04"]        = true,
    ["t_ingcrea_mummyheart_01"]         = true,
    ["t_ingcrea_orcblood_01"]           = true,
    ["t_ingcrea_oystermeat_01"]         = true,
    ["t_ingcrea_oystermeat_02"]         = true,
    ["t_ingcrea_prawntail"]             = true,
    ["t_ingcrea_redsharkmeat_01"]       = true,
    ["t_ingcrea_rocegg_01"]             = true,
    ["t_ingcrea_seaurchinmeat_01"]      = true,
    ["t_ingcrea_silverspademeat_01"]    = true,
    ["t_ingcrea_skyrendervenom_01"]     = true,
    ["t_ingcrea_starfish_01"]           = true,
    ["t_ingcrea_starfish_02"]           = true,
    ["t_ingcrea_starfish_03"]           = true,
    ["t_ingcrea_stridentbirdegg_01"]    = true,
    ["t_ingcrea_sturgeonmeat_01"]       = true,
    ["t_ingcrea_sturgeonroe_01"]        = true,
    ["t_ingcrea_tanthaegg_01"]          = true,
    ["t_ingcrea_trollfat_01"]           = true,
    ["t_ingcrea_twilightmembrane_01"]   = true,
    ["t_ingcrea_velknectarsack_01"]     = true,
    ["t_ingflor_bertpodslice_01"]       = true,
    ["t_ingflor_harrada_01"]            = true,
    ["t_ingflor_sheggoshelf_01"]        = true,
    ["t_ingfood_breadnordrye_02"]       = true,
    ["t_ingfood_cheesebreton_01"]       = true,
    ["t_ingfood_cheesebreton_02"]       = true,
    ["t_ingfood_cheesecolovian_01"]     = true,
    ["t_ingfood_cheesenord_01"]         = true,
    ["t_ingfood_cheeseredguard_01"]     = true,
    ["t_ingfood_eggmolecrab_01"]        = true,
    ["t_ingfood_eggornada_01"]          = true,
    ["t_ingfood_eggseagull_01"]         = true,
    ["t_ingfood_fishbrowntrout_01"]     = true,
    ["t_ingfood_fishcod_01"]            = true,
    ["t_ingfood_fishcoddried_01"]       = true,
    ["t_ingfood_fishleapertail_01"]     = true,
    ["t_ingfood_fishlongfinfilet_01"]   = true,
    ["t_ingfood_fishpike_01"]           = true,
    ["t_ingfood_fishpikeperch_01"]      = true,
    ["t_ingfood_fishsalmon_01"]         = true,
    ["t_ingfood_fishslaughterdried_01"] = true,
    ["t_ingfood_fishslaughterdried_02"] = true,
    ["t_ingfood_fishslaughterdried_03"] = true,
    ["t_ingfood_fishslaughterdried_04"] = true,
    ["t_ingfood_fishspr_01"]            = true,
    ["t_ingfood_fishstrid_01"]          = true,
    ["t_ingfood_honey_01"]              = true,
    ["t_ingfood_meatalit_01"]           = true,
    ["t_ingfood_meatarenthjerky_01"]    = true,
    ["t_ingfood_meatbeef_01"]           = true,
    ["t_ingfood_meatboar_02"]           = true,
    ["t_ingfood_meatchicken_01"]        = true,
    ["t_ingfood_meatcliffracer_01"]     = true,
    ["t_ingfood_meatdolphin_01"]        = true,
    ["t_ingfood_meatgoat_01"]           = true,
    ["t_ingfood_meatguar_01"]           = true,
    ["t_ingfood_meatham_01"]            = true,
    ["t_ingfood_meathorker_01"]         = true,
    ["t_ingfood_meathorse_01"]          = true,
    ["t_ingfood_meatkagouti_01"]        = true,
    ["t_ingfood_meatkwama_01"]          = true,
    ["t_ingfood_meatmutton_01"]         = true,
    ["t_ingfood_meatornada_01"]         = true,
    ["t_ingfood_meatparastylus_01"]     = true,
    ["t_ingfood_meatpork_01"]           = true,
    ["t_ingfood_meatsqrl_01"]           = true,
    ["t_ingfood_meatvenison_01"]        = true,
    ["t_ingfood_riverstrideregg_01"]    = true,
    ["t_ingfood_scribpie_01"]           = true,
    ["t_ingfood_tguarhide"]             = true,
    ["t_ingmine_salt_01"]               = true,
    ["t_we_drink_meatjuicerotmeth_01"]  = true,
    ["t_we_drink_pigmilkbeerjagga_01"]  = true,
    ["t_we_drink_wine_01"]              = true,
}
local meatPatterns = {
    "meat",
    "cuttle",
    "egg",
    "skin",
    "hide",
    "jerky",
    "bone",
    "blood",
    "fish",
    "scales",
    "scrib",
    "shalk",
    "leather",
    "pelt",
    "flesh",
    "brain",
    "_ear",
    "eye",
    "heart",
    "tail",
    "tongue",
    "morsel",
    "_ingcrea",
}

local function hasMeatyName(id)
    for _, pattern in ipairs(meatPatterns) do
        if string.find(id, pattern) then
            return true
        end
    end
    return false
end

local function isGreenPactSafe(item, actor, options)
    if not greenPactPlayers[actor.id] then return end

    if gpIngredients[item.recordId] or hasMeatyName(item.recordId) then
        return true
    else
        actor:sendEvent("ShowMessage", { message = "The Green Pact prohibits you from eating this." })
        return false
    end
end

return {
    eventHandlers = {
        MerlordsTraits_registerGreenPact = function(playerId)
            if not next(greenPactPlayers) then
                I.ItemUsage.addHandlerForType(types.Ingredient, isGreenPactSafe)
            end
            greenPactPlayers[playerId] = true
        end
    }
}
