local ashfall = include("mer.ashfall.interop")
if ashfall then

    ashfall.registerActivators{
		az_flora_dogear_bud_01 = "tree",
		az_flora_dogear_tree_01 = "tree",
		az_flora_dogear_tree_02 = "tree",
		az_flora_dogear_tree_03 = "tree",
		az_flora_TI_tree_shoot_01 = "tree",
		az_flora_TI_tree_shoot_02 = "tree",
		az_flora_tree_az_02 = "tree",
		az_flora_tree_az_04 = "tree",
		az_flora_tree_az_05 = "tree",
		az_flora_tree_az_07 = "tree",
		az_flora_tree_birch_01 = "tree",
		az_flora_tree_birch_02 = "tree",
		az_flora_tree_cedar_01 = "tree",
		az_flora_tree_cedar_02 = "tree",
		az_flora_tree_cedar_03 = "tree",
		az_flora_tree_cypress_01 = "tree",
		az_flora_tree_cypress_02 = "tree",
		az_flora_tree_cypress_03 = "tree",
		az_flora_tree_dawn01 = "tree",
		az_flora_tree_dawn02 = "tree",
		az_flora_tree_fern_00 = "tree",
		az_flora_tree_fern_01 = "tree",
		az_flora_tree_fern_02 = "tree",
		az_flora_tree_fern_03 = "tree",
		az_flora_tree_gnarly_01 = "tree",
		az_flora_tree_gnarly_02 = "tree",
		az_flora_tree_gnarly_03 = "tree",
		az_flora_tree_gnarly_04 = "tree",
		az_flora_tree_jungle_01 = "tree",
		az_flora_tree_kp_01 = "tree",
		az_flora_tree_kp_02 = "tree",
		az_flora_tree_kp_03 = "tree",
		az_flora_tree_l_02 = "tree",
		az_flora_tree_l_03 = "tree",
		az_flora_tree_mangrove_01 = "tree",
		az_flora_tree_mangrove_02 = "tree",
		az_flora_tree_mangrove_03 = "tree",
		az_flora_tree_mangrove_04 = "tree",
		az_flora_tree_mountainmaple01 = "tree",
		az_flora_tree_mountainmaple02 = "tree",
		az_flora_tree_mountainmaple03 = "tree",
		az_flora_tree_MS_aj_t01 = "tree",
		az_flora_tree_MS_aj_t02 = "tree",
		az_flora_tree_MS_aj_t03 = "tree",
		az_flora_tree_MS_aj_t06 = "tree",
		az_flora_tree_MS_aj_t07 = "tree",
		az_flora_tree_MS_GreatElm = "tree",
		az_flora_tree_MS_gum = "tree",
		az_flora_tree_MS_gum2 = "tree",
		az_flora_tree_MS_sakura_01 = "tree",
		az_flora_tree_MS_sakura_02 = "tree",
		az_flora_tree_ndib_G1 = "tree",
		az_flora_tree_ndib_G2 = "tree",
		az_flora_tree_ndib_G5 = "tree",
		az_flora_tree_ndib_G6 = "tree",
		az_flora_tree_ndib_huge = "tree",
		az_flora_tree_palm_nobiax_01 = "tree",
		az_flora_tree_palm_nobiax_03 = "tree",
		az_flora_tree_palm_nobiax_04 = "tree",
		az_flora_tree_palm_nobiax_05 = "tree",
		az_flora_tree_palm_oil_01 = "tree",
		az_flora_tree_palm_oil_02 = "tree",
		az_flora_tree_palm_oil_03 = "tree",
		az_flora_tree_palm_oil_04 = "tree",
		az_flora_tree_palm_turbo01 = "tree",
		az_flora_tree_palm_turbo02 = "tree",
		az_flora_tree_palm_turbo03 = "tree",
		az_flora_tree_palm_turbo04 = "tree",
		az_flora_tree_palm_turbo05 = "tree",
		az_flora_tree_palm_turbo06 = "tree",
		az_flora_tree_palm_turbo07 = "tree",
		az_flora_tree_palm_wax_01 = "tree",
		az_flora_tree_palm_wax_02 = "tree",
		az_flora_tree_palm_wax_03 = "tree",
		az_flora_tree_pine_big_01 = "tree",
		az_flora_tree_pine_big_02 = "tree",
		az_flora_tree_pine_large_01 = "tree",
		az_flora_tree_pine_large_02 = "tree",
		az_flora_tree_pine_med_01 = "tree",
		az_flora_tree_pine_med_02 = "tree",
		az_flora_tree_pine_small_01 = "tree",
		az_flora_tree_sakura_01 = "tree",
		az_flora_tree_sakura_02 = "tree",
		az_flora_tree_sakura_03 = "tree",
		az_flora_tree_willow_01 = "tree",
		az_furn_trough_water = "water",
		az_water_rocksource = "water",
		az_water_round = "water",
		az_ex_v_well = "well",
		az_furn_birdbath_01 = "waterDirty",
		az_In_CaveGrottoStreamBendL = "partial",
		az_In_CaveGrottoStreamBendR = "partial",
		az_In_CaveGrottoStreamLong = "partial",
		az_In_CaveGrottoStreamShort01 = "partial",
		az_In_CaveGrottoStreamShort02 = "partial",
		az_In_CaveGrottoStreamSplit = "partial",
		az_In_CaveLimeStreamBendL = "partial",
		az_In_CaveLimeStreamBendR = "partial",
		az_In_CaveLimeStreamLong = "partial",
		az_In_CaveLimeStreamShort01 = "partial",
		az_In_CaveLimeStreamShort02 = "partial",
		az_In_CaveLimeStreamSplit = "partial",
		az_water_CircleStatic_0064 = "waterDirty",
		az_water_CircleStatic_0128 = "waterDirty",
		az_water_CircleStatic_0256 = "waterDirty",
		az_water_CircleStatic_0512 = "waterDirty",
		az_water_CircleStatic_1024 = "waterDirty",
		az_water_CircleStatic_2048 = "waterDirty",
		az_water_column = "waterDirty",
		az_water_CurveFlow_0256-45 = "waterDirty",
		az_water_CurveFlow_0256-90 = "waterDirty",
		az_water_CurveFlow_0512-45 = "waterDirty",
		az_water_CurveFlow_0512-90 = "waterDirty",
		az_water_CurveRapid_0256-45 = "waterDirty",
		az_water_CurveRapid_0256-90 = "waterDirty",
		az_water_CurveRapid_0512-45 = "waterDirty",
		az_water_CurveRapid_0512-90 = "waterDirty",
		az_water_rapids_01 = "waterDirty",
		az_water_RectFlow_0256-0512 = "waterDirty",
		az_water_RectFlow_0256-2048 = "waterDirty",
		az_water_RectFlow_256-1024 = "waterDirty",
		az_water_RectRapid_256-0512 = "waterDirty",
		az_water_RectRapid_256-1024 = "waterDirty",
		az_water_RectRapid_256-2048 = "waterDirty",
		az_water_SquareFlow_1024 = "waterDirty",
		az_water_SquareFlow_256 = "partial",
		az_water_SquareFlow_512 = "partial",
		az_water_SquareStatic_0256 = "partial",
		az_water_SquareStatic_0512 = "partial",
		az_water_SquareStatic_1024 = "partial",
		az_water_waterfall_01 = "waterDirty"
		az_water_waterfall_01 = "waterDirty"
		az_water_waterfall_02 = "waterDirty"
		az_water_waterfall_03 = "waterDirty"
		az_water_waterfall_04 = "waterDirty"
		az_water_waterfall_05 = "waterDirty"
		az_water_waterfall_OM = "waterDirty"
		az_water_waterfall_OM_small = "waterDirty"
		az_water_waterfall_rock_01 = "partial"
		az_water_waterfall_sewer_01 = "waterDirty"
		az_water_waterfall_test = "waterDirty"
		az_water_waterfall_test = "waterDirty"
		az_water_waterfall_Vivec_03 = "waterDirty"
		az_water_waterfall_Vivec_05 = "waterDirty"
		az_water_waterfall_wide = "waterDirty"
		az_water_waterfall_wide2 = "waterDirty"
		az_waterfall_cliff = "partial"
		az_waterfall_cliff_BM = "partial"
    }

    ashfall.registerWaterContainers{
		az_Misc_ClayCup01 = "cup",
		az_Misc_ClayPitcher = "pitcher",
		az_Misc_IronPot01 = "pot",
		az_Misc_IronPot02 = "pot",
		az_Misc_QuartzGoblet = "goblet",
		az_Misc_ShellwareCup = "cup",
		az_Misc_ShellwarePitcher = "pitcher",
		az_Misc_ShellwarePot = "pot",
    }

    ashfall.registerFoods{
		az_food_biscuit = "food",
		az_food_cookie = "food",
		az_food_egg_skapper_boiled = "food",
		az_food_fish_grilled ="food",
		az_food_fish_lemon = "food",
		az_food_fish_roasted = "food",
		az_food_fish_salted = "food",
		az_food_jellyloaf = "food",
		az_food_jellyslice ="food",
		az_food_kollop_fried ="food",
		az_food_kriin_leg ="meat",
		az_food_kriin_meat = "meat",
		az_food_kriin_meat_cooked = "food",
		az_food_lemon = "food",
		az_food_Lizard_Foot_01 = "food",
		az_food_Lizard_Foot_02 = "food",
		az_food_marshmerrow = "food",
		az_food_meat_cooked_rat = "food",
		az_food_meat_turtle = "meat",
		az_food_omelette_crab = "food",
		az_food_peach = "food",
		az_food_peach_mush = "food",
		az_food_pie_sl_berry = "food",
		az_food_pie_sl_lemon = "food",
		az_food_pie_sl_peach = "food",
		az_food_pie_sl_rat = "food",
		az_food_sausage_sentinel = "food",
		az_food_soup_onion = "food",
		az_food_soup_rat = "food",
		az_food_soup_seaweed = "food",
		az_food_soup_turtle = "food",
		az_food_sweetroll = "food",
		az_food_wasabi_paste = "herb",
		az_food_wasabi_stem = "vegetable",
		az_IngCrea_Angelfish = "meat",
		az_IngCrea_BarracudaSteak = "meat",
		az_IngCrea_BarracudaTailfin = "meat",
		az_IngCrea_IguanaTail = "meat",
		az_IngCrea_Parrotfish = "meat",
		az_IngCrea_RedSharkKabob = "meat",
		az_IngCrea_RedSharkMeat = "meat",
		az_IngCrea_SerowChop = "meat",
		az_IngCrea_SilvSpadeMeat01 = "meat",
		az_IngCrea_SilvSpadeMeat02 = "meat",
		az_IngFlor_BromeliadFruit = "food",
		az_IngFlor_BromeliadFruitSlice = "food",
		az_IngFlor_Ginger = "herb",
		az_IngFlor_MasseranthSeeds = "herb",
		az_IngFood_TanwaJerky = "food",
		az_IngFood_TanwaRib = "meat",
		az_IngFood_TanwaRibSucc = "food",
		az_IngFood_TanwaSausage = "food",
		az_ingred_eggs_skapper = "food",
		az_ingred_jelly = "food",
		az_ingred_seasalt = "herb",
		az_ingred_shroom_02 = "mushroom",
		az_ingred_shroom_03 = "mushroom",
		az_ingred_shroom_04 = "mushroom",
    }

    ashfall.registerHeatSources{
		az_furn_suncrystal_grill_01 = 100,
		az_furn_suncrystal_grill_02 = 100,
		az_In_CaveGrottoSunroot01 = 50,
		az_In_CaveLimeSunroot01 = 50,
		az_Terr_SunstoneChunk01 = 50,
		az_Terr_SunstoneChunk02 = 50,
		az_Terr_SunstoneRock01 = 50,
		az_Terr_SunstoneRock02 = 50,
		az_Terr_SunstoneRock03 = 50,
		az_Terr_SunstoneRock04 = 50,
		az_Terr_SunstoneRock05 = 50,
		az_Terr_SunstoneRock06 = 50,
		az_Terr_SunstoneRock07 = 50,
		az_Terr_SunstoneRock08 = 50,
		az_Terr_SunstoneRock09 = 50,
		az_Terr_SunstoneRock10 = 50,
    }

	ashfall.registerTreeBranches{
        treeIds = {
            'az_flora_tree_palm_nobiax_00',
            'az_flora_tree_palm_nobiax_01',
			'az_flora_tree_palm_nobiax_02',
			'az_flora_tree_palm_nobiax_03',
			'az_flora_tree_palm_nobiax_04',
			'az_flora_tree_palm_nobiax_05',
			'az_flora_tree_palm_stickle_01',
			'az_flora_tree_palm_stickle_02',
			'az_flora_tree_palm_turbo01',
			'az_flora_tree_palm_turbo02',
			'az_flora_tree_palm_turbo03',
			'az_flora_tree_palm_turbo04',
			'az_flora_tree_palm_turbo05',
			'az_flora_tree_palm_turbo06',		
        },
        branchIds = {
            "custom_branch_01",
            "custom_branch_02",
            "custom_branch_03",
        }
    } 

end