local M = {

	["barrelshortgroup.nif"] = "Wood",
	["barricade01.nif"] = "Wood",
	["cave_retain_wall00.nif"] = "Wood",
	["depalisade01.nif"] = "Wood",
	["depalisade02.nif"] = "Wood",
	["ex_ropebridge_01.nif"] = "Wood",
	["ex_ropebridge_1024_01.nif"] = "Wood",
	["ex_ropebridge_2048_01.nif"] = "Wood",
	["ex_ropebridge_512_01.nif"] = "Wood",
	["ex_ropebridge_stake_01.nif"] = "Wood",
	["rem_de_scaffold_01.nif"] = "Wood",
	["streamgravelbendl.nif"] = "Stone",
	["streamgravelbendr.nif"] = "Stone",
	["streamgravellong.nif"] = "Stone",
	["streamgravelshort01.nif"] = "Stone",
	["streamgravelshort02.nif"] = "Stone",
	["streamgravelsplit.nif"] = "Stone",
	["streamgraveltrans01.nif"] = "Stone",
	["streamgraveltrans02.nif"] = "Stone",
	["velaltarbroken03.nif"] = "Stone",
	["absaplingac01.nif"] = "Wood",
	["absaplingac02.nif"] = "Wood",
	["absaplingac03.nif"] = "Wood",
	["absaplingac04.nif"] = "Wood",
	["absaplingai01.nif"] = "Wood",
	["absaplingai02.nif"] = "Wood",
	["absaplingai03.nif"] = "Wood",
	["absaplingai04.nif"] = "Wood",
	["absaplingbc01.nif"] = "Wood",
	["absaplingbc02.nif"] = "Wood",
	["absaplingbc03.nif"] = "Wood",
	["absaplinggl01.nif"] = "Wood",
	["absaplinggl02.nif"] = "Wood",
	["absaplingwg01.nif"] = "Wood",
	}

return M
