local sb_autocomplete = require("sb_autocomplete.interop")
local data = require("sb_autocomplete.data")

local commands_with_params = {
    "AddItem",
    "AddSoulGem",
    "AddSpell",
    "AddToLevCreature",
    "AddToLevItem",
    "AddTopic",
    "Cast",
    "CenterOnCell",
    "COC",
    "ChangeWeather",
    "CreateMaps",
    "Drop",
    "DropSoulGem",
    "Equip",
    "ExplodeSpell",
    "GetDeadCount",
    "GetDistance",
    "GetEffect",
    "GetFactionReaction",
    "GetItemCount",
    "GetJournalIndex",
    "GetLineOfSight",
    "GetLOS",
    "GetPCCell",
    "GetPCFacRep",
    "GetPCRank",
    "GetRace",
    "GetSoundPlaying",
    "GetSpell",
    "GetSpellEffects",
    "GetTarget",
    "HasItemEquipped",
    "HasSoulGem",
    "HitAttemptOnMe",
    "HitOnMe",
    "Journal",
    "LoopGroup",
    "ModFactionReaction",
    "ModPCFacRep",
    "ModRegion",
    "PCClearExpelled",
    "PCExpell",
    "PCExpelled",
    "PCJoinFaction",
    "PCLowerRank",
    "PCRaiseRank",
    "PlaceAtMe",
    "PlaceAtPC",
    "PlaceItem",
    "PlaceItemCell",
    "PlayGroup",
    "PlayLoopSound3D",
    "PlayLoopSound3DVP",
    "PlaySound",
    "PlaySound3D",
    "PlaySound3DVP",
    "PlaySoundVP",
    "PositionCell",
    "RemoveEffects",
    "RemoveFromLevCreature",
    "RemoveFromLevItem",
    "RemoveItem",
    "RemoveSoulGem",
    "RemoveSpell",
    "RemoveSpellEffects",
    "RepairedOnMe",
    "Say",
    "ScriptRunning",
    "Set",
    "SetFactionReaction",
    "SetPCFacRep",
    "ShowMap",
    "StartCombat",
    "StartScript",
    "StopScript",
    "StopSound",
    "StreamMusic",
    "UsedOnMe"
}

local params = {
    { data.suggestItem,        "" },
    { data.suggestCreature,    data.suggestSoulGem },
    { data.suggestSpell,       "" },
    { data.suggestLvlCreature, data.suggestCreature,   "" },
    { data.suggestLvlItem,     data.suggestItem,       "" },
    { data.suggestTopic },
    { data.suggestSpell,       data.suggestCreatureNPC },
    { data.suggestCell },
    { data.suggestCell },
    { data.suggestRegion,      data.suggestWeather },
    { data.suggestESP },
    { data.suggestInvActor,        "" },
    { data.suggestCreature },
    { data.suggestEquip },
    { data.suggestSpell },
    { data.suggestCreatureNPC },
    { data.suggestObject },
    { data.suggestEffect },
    { data.suggestFaction,     data.suggestFaction },
    { data.suggestInvActor },
    { data.suggestJournal },
    { data.suggestObject },
    { data.suggestObject },
    { data.suggestCell },
    { data.suggestFaction },
    { data.suggestFaction },
    { data.suggestRace },
    { data.suggestSound },
    { data.suggestSpell },
    { data.suggestSpell },
    { data.suggestCreatureNPC },
    { data.suggestEquip },
    { data.suggestCreature },
    { data.suggestWeapon },
    { data.suggestWeapon },
    { data.suggestJournal,     "" },
    { data.suggestAnimation,   "",                     "" },
    { data.suggestFaction,     data.suggestFaction,    "" },
    { "",                      data.suggestFaction },
    { data.suggestRegion,      "",                     "", "", "",              "", "", "", "", "", "" },
    { data.suggestFaction },
    { data.suggestFaction },
    { data.suggestFaction },
    { data.suggestFaction },
    { data.suggestFaction },
    { data.suggestFaction },
    { data.suggestObject,      "",                     "", "" },
    { data.suggestObject,      "",                     "", "" },
    { data.suggestObject,      "",                     "", "", "" },
    { data.suggestObject,      data.suggestCell,       "", "", "",              "" },
    { data.suggestAnimation,   "" },
    { data.suggestSound },
    { data.suggestSound,       "",                     "" },
    { data.suggestSound },
    { data.suggestSound,       "",                     "" },
    { data.suggestSound },
    { data.suggestSound,       "",                     "" },
    { "",                      "",                     "", "", data.suggestCell },
    { data.suggestEffect },
    { data.suggestLvlCreature, data.suggestCreature,   "" },
    { data.suggestLvlItem,     data.suggestItem,       "" },
    { data.suggestInvActor,    "" },
    { data.suggestCreature },
    { data.suggestSpellActor },
    { data.suggestSpell },
    { data.suggestEquip },
    { data.suggestVO,          "" },
    { data.suggestScript },
    { data.suggestVariable,    "" },
    { data.suggestFaction,     data.suggestFaction,    "" },
    { "",                      data.suggestFaction },
    { data.suggestCell },
    { data.suggestCreatureNPC },
    { data.suggestScript },
    { data.suggestScript },
    { data.suggestSound },
    { data.suggestMusic },
    { data.suggestWeapon }
}

for index, command in pairs(data.commands) do
    sb_autocomplete:registerSuggestion(command, "mwscript")
end

for index, command in ipairs(commands_with_params) do
    sb_autocomplete:registerCommand(command, "mwscript", params[index])
end
