local I = require('openmw.interfaces')

I.Settings.registerPage({
    key = 'SimpleExpScaling',
    l10n = 'SimpleExpScaling',
    name = 'page_name',
    description = 'page_description',
 })

 I.Settings.registerGroup({
    key = 'SettingsSimpleExpScaling',
    page = 'SimpleExpScaling',
    l10n = 'SimpleExpScaling',
    name = "ui_settings_group",
    permanentStorage = false,
    settings = {
      {
         key = 'togglespeechcraftfail',
         name = 'togglespeechcraftfail_name',
         description = 'togglespeechcraftfail_description',
         default = true,
         renderer = 'checkbox',
      },
      {
         key = 'basespeechcraftfail',
         name = 'basespeechcraftfail_name',
         description = 'basespeechcraftfail_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'speechcraftmulti',
         name = 'speechcraftmulti_name',
         description = 'speechcraftmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'merchantilemulti',
         name = 'merchantilemulti_name',
         description = 'merchantilemulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'athleticsmulti',
         name = 'athleticsmulti_name',
         description = 'athleticsmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'blockmulti',
         name = 'blockmulti_name',
         description = 'blockmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'armorermulti',
         name = 'armorermulti_name',
         description = 'armorermulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'mediumarmormulti',
         name = 'mediumarmormulti_name',
         description = 'mediumarmormulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'heavyarmormulti',
         name = 'heavyarmormulti_name',
         description = 'heavyarmormulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'bluntweaponmulti',
         name = 'bluntweaponmulti_name',
         description = 'bluntweaponmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'longblademulti',
         name = 'longblademulti_name',
         description = 'longblademulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'axemulti',
         name = 'axemulti_name',
         description = 'axemulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'spearmulti',
         name = 'spearmulti_name',
         description = 'spearmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'enchantmulti',
         name = 'enchantmulti_name',
         description = 'enchantmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'destructionmulti',
         name = 'destructionmulti_name',
         description = 'destructionmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'alterationmulti',
         name = 'alterationmulti_name',
         description = 'alterationmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'illusionmulti',
         name = 'illusionmulti_name',
         description = 'illusionmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'conjurationmulti',
         name = 'conjurationmulti_name',
         description = 'conjurationmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'mysticismmulti',
         name = 'mysticismmulti_name',
         description = 'mysticismmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'restorationmulti',
         name = 'restorationmulti_name',
         description = 'restorationmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'alchemymulti',
         name = 'alchemymulti_name',
         description = 'alchemymulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'unarmoredmulti',
         name = 'unarmoredmulti_name',
         description = 'unarmoredmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'securitymulti',
         name = 'securitymulti_name',
         description = 'securitymulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'sneakmulti',
         name = 'sneakmulti_name',
         description = 'sneakmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'acrobaticsmulti',
         name = 'acrobaticsmulti_name',
         description = 'acrobaticsmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'lightarmormulti',
         name = 'lightarmormulti_name',
         description = 'lightarmormulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'shortblademulti',
         name = 'shortblademulti_name',
         description = 'shortblademulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'marksmanmulti',
         name = 'marksmanmulti_name',
         description = 'marksmanmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
      {
         key = 'handtohandmulti',
         name = 'handtohandmulti_name',
         description = 'handtohandmulti_description',
         default = 1,
         renderer = 'number',
         argument = {
            min = 0,
            max = 10,
         },
      },
    },
 })