local soundbank = {

    isInterior = true,
    affectingCells = {
        "Cave",
        "Cavern",
        "Abanabi",
        "Abernanit",
        "Abinabi",
        "Adanumuran",
        "Addamasartus",
        "Aharnabi",
        "Aharunartus",
        "Ahinipalit",
        "Ainab",
        "Ainat",
        "Ansi",
        "Ashanammu",
        "Ashinabi",
        "Ashirbadon",
        "Ashir-Dan",
        "Ashmelech",
        "Assarnud",
        "Assemanu",
        "Assu",
        "Assumanu",
        "Bensamsi",
        "Beshara",
        "Cavern of the Incarnate",
        "Corprusarium",
        "Dubdilla",
        "Dun-Ahhe",
        "Habinbaes",
        "Hassour",
        "Hinnabi",
        "Ibar-Dad",
        "Ilunibi",
        "Kora-Dur",
        "Kudanat",
        "Kumarahaz",
        "Kunirai",
        "Maba-Ilu",
        "Mallapi",
        "Mamaea",
        "Mannammu",
        "Maran-Adon",
        "Masseranit",
        "Mat",
        "Milk",
        "Minabi",
        "Missamsi",
        "Mount Kand",
        "Nallit",
        "Nammu",
        "Nissintu",
        "Nund",
        "Odaishah",
        "Odibaal",
        "Odirnamat",
        "Palansour",
        "Panat",
        "Pinsun",
        "Piran",
        "Pulk",
        "Punabi",
        "Punammu",
        "Punsabanit",
        "Rissun",
        "Salmantu",
        "Sanabi",
        "Sanit",
        "Sargon",
        "Saturan",
        "Sennananit",
        "Sha-Adnius",
        "Shal",
        "Shallit",
        "Sharapli",
        "Shurinbaal",
        "Shushan",
        "Shushishi",
        "Sinsibadon",
        "Subdun",
        "Sud",
        "Surirulk",
        "Tin-Ahhe",
        "Tukushapal",
        "Ulummusa",
        "Yakanalit",
        "Yakin",
        "Yasamsi",
        "Yesamsi",
        "Zainsipilu",
        "Zaintirari",
        "Zanabi",
        "Zebabi",
        "Zenarbael",

        --Bloodmoon 
		"Benkongerike",
        "Bjorn",
        "Caves of Fjalding",
        "Cave of Hidden Music",
        "Domme",
        "Fjell",
        "Frossel",
        "Frykte",
        "Gandrung Caverns",
        "Gloomy Cave",
        "Gronn",
        "Halls of Penumbra",
        "Lair of the Udyrfrykte",
        "Legge",
        "Rimhull",
        "Sjobal",
        "Skygge",
        "Solvjord",
        "Stahlman's Gorge",
        "Varstaad Caves",
		"Karstaag",

        --TR "Adammuburtu",
        "Adhuhartis",
        "Adunji",
        "Ahhesha",
        "Aimmund",
        "Alnadribi",
        "Asnadan",
        "Assarhun",
        "Assinad",
        "Asurnabi",
        "Atsiru-Din",
        "Aymasindo",
        "Azurranu",
        "Balhadarshad Den",
        "Baluridan",
        "Banathi",
        "Barunal",
        "Basan-Dur",
        "Basarnud",
        "Bassuranu",
        "Bedulassadan",
        "Berantus",
        "Binammu",
        "Bruthar",
        "Burraburiash",
        "Dadrunibi",
        "Daelkhun",
        "Dagorda Cavern",
        "Dim-Dai",
        "Dorammu Cavern",
        "Dralnabissit",
        "Drenka Cavern",
        "Duda",
        "Dunada-Nammu",
        "Dungra",
        "Dunusi",
        "Dusura",
        "Elandad",
        "Ermunsour",
        "Ernaberinsu",
        "Falascu",
        "Galseah",
        "Ghand",
        "Git",
        "Habunsanit",
        "Haddut Cave",
        "Hadipasu",
        "Hamtha Cavern",
        "Hamusaddit",
        "Harru Cavern",
        "Harsusirpal",
        "Hlaanis",
        "Hlermu",
        "Ibbanud",
        "Ibinai",
        "Ihnammoth",
        "Ilnakubi",
        "Ilnibu",
        "Isahal",
        "Ishi-Dur",
        "Issarbaddon",
        "Jenigan Cave",
        "Jongala",
        "Kadanuran",
        "Kainat",
        "Kalishlapal",
        "Kanasami",
        "Kharom",
        "Kili Dalder",
        "Kilvurcard",
        "Kirmunad",
        "Kothol",
        "Kulidon",
        "Kumaralk",
        "Kurhu",
        "Kuriki",
        "Lukhalutun",
        "Maarawat",
        "Maatumassu",
        "Maebbu",
        "Maelasi Cavern",
        "Maesabun",
        "Mahsamsi",
        "Malamali",
        "Malumed",
        "Mansurabi",
        "Mansutarmus",
        "Manumnabi",
        "Marananit",
        "Marisanibal",
        "Marushpaanu Tunnel",
        "Marwat",
        "Mashanuad",
        "Massanud",
        "Massapi",
        "Massaunus",
        "Mawapi-Addon",
        "Menuas-Ahhe",
        "Meshenawia",
        "Midannecne",
        "Milcoon",
        "Misapit",
        "Molkobal",
        "Mount Dunul, Cavern",
        "Mount Sarrunabi, Cavern",
        "Mulnabi Tunnel",
        "Muthinis Cave",
        "Naarshamsi",
        "Nalad",
        "Nalmunabi",
        "Namartyon",
        "Nameci Caverns",
        "Nan-Assali",
        "Napali",
        "Nasinammu",
        "Nassurdanami",
        "Nebulud",
        "Nimmutnabanit",
        "Ninnimilk",
        "Ninurtamul",
        "Nirmissin",
        "Nirnidan",
        "Nurgal",
        "Nurshadit",
        "Odimasadra",
        "Odirnamus",
        "Ogroth",
        "Okulanit",
        "Ossu",
        "Otori",
        "Pagondha Cave",
        "Pahunsabi",
        "Pamashibabua",
        "Pamuni Tunnel",
        "Pangoa",
        "Pansaranit",
        "Passu",
        "Pimmu",
        "Puman",
        "Rasdamassilu",
        "Ravalas Cavern",
        "Rilramisnat",
        "Rimal",
        "Rorissud",
        "Runat",
        "Sad",
        "Sadratus",
        "Sagea",
        "Salka Cave",
        "Samapwi",
        "Sambussu Tunnel",
        "Samursi",
        "Sanammasour",
        "Sarbiri",
        "Sarmabael",
        "Sebarmul",
        "Sehutu",
        "Selanasteris",
        "Seranassid",
        "Serasith Cavern",
        "Seris",
        "Serrudan",
        "Sevadartus",
        "Shaden",
        "Shan-Ahhe",
        "Shasharanit",
        "Shashmassadan",
        "Shirel",
        "Siridunbal",
        "Sobhidaz",
        "Soudi",
        "Suldunanit",
        "Sulindon",
        "Surimintu",
        "Syndros",
        "Talmahre Cavern",
        "Tansumiran",
        "Tremelanit",
        "Tristin",
        "Udanasit",
        "Uddunapsit",
        "Urussabi",
        "Ushaninmis",
        "Ushudartus",
        "Uttumilk",
        "Valubi",
        "Venymlan Deeps",
        "Verenabi",
        "Vissamu",
        "Vul",
        "Vynbant",
        "Yadamsi",
        "Yalamalkus",
        "Yamniban",
        "Yanashpi",
        "Yansurashmi",
        "Yenashpi",
        "Yenidan",
        "Zabamallit",
        "Zainna",
        "Zalitalan",
        "Zatamushi",
        "Zeddan",

        --Cyrodiil "Ansedeus",
        "Aschar",
        "Atrene",
        "Buralca",
        "Joranta",
        "Lost Stars Hollow",
        "Melestrata",
        "Nabor",
        "Ogima",
        "Pyraeus",
        "Sorhuk",
        "Thesigir Chasm",
        "Vilenkin",

        --SHOTN "Berfall Caverns",
        "Berjodhre",
        "Bharani Cave",
        "Bjagherd Cave",
        "Black Teeth Caverns",
        "Braignainesaide",
        "Breakneck Den",
        "Bvojou Cavern",
        "Criagachsaide",
        "Duibhmarad",
        "Elgvring Cave",
        "Faldarach",
        "Fyrignar",
        "Harkir\'s Hole",
        "Heifnil\'s Folly",
        "Hrakja Cavern",
        "Husteng Caverns",
        "Kejev Cavern",
        "Kolgath Hollow",
        "Kulmar Cavern",
        "Malghredin\'s Lair",
        "Malagrok",
        "Ocsenna",
        "Orsuld Cave",
        "Skaldvir Cave",
        "Skjuggefald Deeps",
        "Svaer",
        "Taliesinntara",
        "Vorngond Cavern",
		
		-- Caldera Priory
		"Underneath the Well",
		"River of Flame",
		"Sanctuary of Bone",


    },

    ambientLoopSounds = {
        {
            soundPath = "sounds\\DynamicSounds\\cave\\cavewind.wav", 
			loop = true
        },
        {
            soundPath = "sounds\\DynamicSounds\\fauna\\interior\\cave_bats1.wav",
            loop = false,
            PlayChancePercent = 10,
            volume = 0.3
        },
        {
            soundPath = "sounds\\DynamicSounds\\fauna\\interior\\cave_bats2.wav",
            loop = false,
            PlayChancePercent = 10,
            volume = 0.3
        },
        {
            soundPath = "sounds\\DynamicSounds\\cave\\cave06.wav",
            loop = false,
            PlayChancePercent = 20
        },
        {
            soundPath = "sounds\\DynamicSounds\\cave\\cave02.wav",
            loop = false,
            PlayChancePercent = 20
        },
        {
            soundPath = "sounds\\DynamicSounds\\cave\\cave11.wav",
            loop = false,
            PlayChancePercent = 20
        },
    },

    objects = {

        {
            "in_py_rock",
            {
                {
                    soundPath = "sounds\\DynamicSounds\\cave\\cavedrip03.wav", 
					loop = false
                },
                {
                    soundPath = "sounds\\DynamicSounds\\cave\\cavedrip04.wav",
                    loop = false
                },
                {
                    soundPath = "sounds\\DynamicSounds\\cave\\cavedrip05.wav",
                    loop = false
                },
            }
        },
        {
            "ex_common_plat_end",
            {
                {
                    soundPath = "sounds\\DynamicSounds\\wood\\woodcreak01.wav", loop = false
                },
                {
                    soundPath = "sounds\\DynamicSounds\\wood\\woodcreak02.wav",
                    loop = false
                },
                {
                    soundPath = "sounds\\DynamicSounds\\wood\\woodcreak03.wav",
                    loop = false
                },
            }
        },
        {
            "in_ar_0",
            {
                {
                    soundPath = "sounds\\DynamicSounds\\wood\\woodcreak01.wav", loop = false
                },
                {
                    soundPath = "sounds\\DynamicSounds\\wood\\woodcreak02.wav",
                    loop = false
                },
                {
                    soundPath = "sounds\\DynamicSounds\\wood\\woodcreak03.wav",
                    loop = false
                },
            }
        },
        {
            "BM_KA_door_dark",
            {
                {
                    soundPath = "sounds\\DynamicSounds\\wind\\amb_dungeon_cave_wind_2d_lp.wav", 
					loop = true
                },
            }
        },
        {
            "BM_IC_door_pelt",
            {
                {
                    soundPath = "sounds\\DynamicSounds\\wind\\amb_dungeon_cave_wind_2d_lp.wav", 
					loop = true
                },
            }
        },
        {
            "BM_KA_lamp",
            {
                {
                    soundPath = "sounds\\DynamicSounds\\fire\\amb_firecrater_02_lp.wav", 
					loop = true
                },
            }
        },		
        { "Door_PortalFire", 
			{
				{ 	soundPath = "sounds\\DynamicSounds\\magic\\amb_obliviongate_lp.wav", 
					loop = true,
					volume=2,					
				},            	
			} 
		},
        { "Furn_DngChain", 
			{
				{ 	soundPath = "sounds\\DynamicSounds\\metal\\chains4.wav", 
					loop = false,					
				},            	
			} 
		},		
        { "AB_Ex_InfernaceChunk", 
			{
				{ 	
                    soundPath = "sounds\\DynamicSounds\\fire\\amb_firecrater_01_lp.wav",
                    loop = true,
					volume=0.5,	
				},            	
			} 
		},
        -- {
            -- "Act_Crystal_",
            -- {
                -- {
                    -- soundPath = "sounds\\DynamicSounds\\magic\\crystal3.wav", 
					-- loop = true
                -- },
            -- }
        -- },			
    },






}


return soundbank