return {
    -- record IDs of creatures eligible to be tamed, lower-case
    TAMEABLE_CREATURES = {
        ["mudcrab"]      = true,
        ["mudcrab_hrmudcrabnest"] = true,
        ["mudcrab_unique"]        = true, -- now you can tame the crab merchant
        ["alit"]      = true,
        ["rat"]       = true,
        ["guar"]      = true,
        ["shalk"]     = true,
        ["scrib"]     = true,
        ["scrib_vaba-amus"]   = true,
        ["scrib_rerlas"]      = true,
        ["icescrib"]          = true,
        ["aa_cr_horned_scrib"] = true,
        ["scrib_2"]           = true,
        ["ttooth_scrib_2"]    = true,
        ["ttooth_scrib"]      = true,
        ["kwama forager"]     = true,
        ["kwama warrior"]     = true,
        ["kwama worker"]      = true,
        ["kwama worker entrance"] = true,
        ["kagouti"]      = true,
        ["kagouti_hrk"]  = true,
        ["kagouti_mating"] = true,
        ["guar_feral"]     = true,
        ["nix-hound"]      = true,
        ["scamp"]          = true, -- daedra
        ["scamp_creeper"]  = true, -- now you can tame Creeper!

        -- Tribunal
        ["durzog_wild"]    = true,
        ["durzog_wild_weaker"]    = true,
        ["durzog_war"]     = true,
        ["durzog_war_trained"]    = true,
        -- Bloodmoon
        ["bm_bear_black"]  = true,
        ["bm_horker"]      = true,
        ["bm_horker_large"] = true,
        ["bm_frost_boar"]   = true,
        ["bm_wolf_grey_lvl_1"] = true,
        ["bm_wolf_grey"]       = true,
        ["bm_wolf_snow_unique"] = true,
        -- Tamriel Data
        ["t_cyr_fau_alphyn_01"]      = true,
        ["t_sky_fau_bearbk_01"]      = true,
        ["t_sky_fau_bearred_01"]     = true,
        ["t_cyr_fau_bearcol_01"]     = true,
        ["t_sky_fau_beargr_01"]      = true,
        ["t_sky_fau_bearbr_01"]      = true,
        ["t_sky_fau_bearsn_01"]      = true,
        ["t_sky_fau_danswyrm_01"]    = true,
        ["t_cyr_fau_snkdmaspis_01"]  = true,
        ["t_mw_fau_redoranhnd_01"]   = true,
        ["t_mw_fau_redoranhnd_02"]   = true,
        ["t_mw_fau_redoranhnd_03"]   = true,
        ["t_mw_fau_armunkag_01"]     = true,
        ["t_mw_fau_kagrn_01"]        = true,
        ["t_mw_fau_armunkagmat_01"]  = true,
        ["t_glb_cre_landdreu_01"]    = true,
        ["t_sky_fau_mamm_01"]        = true,
        ["t_cyr_fau_muskrat_01"]     = true,
        ["t_cyr_fau_muskratcol_01"]  = true,
        ["t_sky_fau_raki_01"]        = true,
        ["t_glb_fau_ratbk_01"]       = true,
        ["t_glb_fau_ratcv_01"]       = true,
        ["t_glb_fau_ratgr_01"]       = true,
        ["t_cyr_fau_rat_01"]         = true,
        ["t_glb_fau_ratcol_01"]      = true,
        ["t_glb_fau_ratcol_02"]      = true,
        ["t_glb_fau_ratwt_01"]       = true,
        ["t_sky_fau_sabcat_01"]      = true,
        ["t_sky_fau_sabcat_02"]      = true,
        ["t_cyr_fau_birdstrid_01"]   = true,
        ["t_cyr_fau_birdstridn_01"]  = true,
        ["t_mw_fau_tigguar_01"]      = true,
        ["t_sky_fau_boar_01"]        = true,
        ["t_sky_fau_wolfblasml_01"]  = true,
        ["t_sky_fau_wolfgr_01"]      = true,
        ["t_sky_fau_wolfbla_01"]     = true,
        ["t_cyr_fau_wolfcol_02"]     = true,
        ["t_sky_fau_wolfred_01"]     = true,
        ["t_cyr_fau_wolfcol_01"]     = true,
        ["t_ham_fau_wormmth_01"]     = true,
        ["t_mw_fau_beetlebl_01"]     = true,
        ["t_mw_fau_beetleblran_01"]  = true,
        ["t_mw_fau_beetlebr_01"]     = true,
        ["t_mw_fau_beetlebrran_01"]  = true,
        ["t_mw_fau_beetlegr_01"]     = true,
        ["t_mw_fau_beetlegrran_01"]  = true,
        ["t_mw_fau_beetlehr_01"]     = true,
        ["t_mw_fau_beetlehrran_01"]  = true,
        ["t_mw_fau_thresher_01"]     = true,
        ["t_mw_fau_mucklch_01"]      = true,
        ["t_mw_fau_ornqn_01"]        = true,
        ["t_mw_fau_para_01"]         = true,
        ["t_mw_fau_paravn_01"]       = true,
        ["t_mw_fau_sharaihoppe_01"]  = true,
        ["t_glb_fau_lrgspider_03"]   = true,
        ["t_glb_fau_lrgspider_01"]   = true,
        ["t_glb_fau_lrgspider_02"]   = true,
        ["t_ham_fau_spkworm_01"]     = true,
        ["t_mw_fau_plstrid_01"]      = true,
        ["t_mw_fau_yethbug_01"]      = true,
        ["t_dae_cre_spiderdae_01"]   = true, -- daedra
        -- Creatures PR Purist
        ["ttooth_frost_boar_pigle"]   = true,
        ["ttooth_bear_brown_cub"]   = true,
        ["ttooth_bear_black_cub"]   = true,
        ["ttooth_horker_cub2"]   = true,
        ["ttooth_wolf_red_pup"]   = true,
        ["ttooth_wolf_grey_pup"]   = true,
        ["ttooth_alit_baby2"]   = true,
        ["ttooth_kagouti_baby"]   = true,
        ["mu_ice_boar_0"]   = true,
        ["mu_ice_boar_100"]   = true,
        ["mu_ice_boar_150"]   = true,
        ["mu_ice_boar_50"]   = true,
        ["mu_ice_boar_20"]   = true,
        ["guar_unscripted"]   = true,
        ["guar_feral_unscripted"]   = true,
        ["plx_baby_guar_wild"]   = true,
        ["ttooth_nix-hound_pup2"]   = true,
        ["plx_shalk_lesser"]   = true,
        ["plx_baby_guar"]   = true,
        ["plx_nixpup"]   = true,
        ["plx_shalk_herd"]   = true,
        ["plx_shalk_herdt"]   = true,
        ["plx_guar_herd"]   = true,
        ["plx_guar_smaller"]   = true,
        ["plx_guar_feral_smaller"]   = true,
    },

    -- PEACEFUL TAMING: DIET & FOOD TABLES
 
    -- creature diet types
    DIET = {
        HERBIVORE = "herbivore",
        CARNIVORE = "carnivore",
        OMNIVORE  = "omnivore",
    },
 
    -- diet of a creature, keyed by lower-case record id. creatures not listed here fall back to DEFAULT_DIET
    CREATURE_DIET = {
        -- scavengers are omnivores
        ["mudcrab"]                  = "omnivore",
        ["mudcrab_hrmudcrabnest"]    = "omnivore",
        ["mudcrab_unique"]           = "omnivore",
        ["t_cyr_fau_snkdmaspis_01"]  = "omnivore",

        -- predators are carnivores
        ["alit"]                     = "carnivore",
        ["kagouti"]                  = "carnivore",
        ["kagouti_hrk"]              = "carnivore",
        ["kagouti_mating"]           = "carnivore",
        ["t_mw_fau_armunkag_01"]     = "carnivore",
        ["t_mw_fau_kagrn_01"]        = "carnivore",
        ["t_mw_fau_armunkagmat_01"]  = "carnivore",
        ["nix-hound"]                = "carnivore",
        ["scamp"]                    = "carnivore",
        ["scamp_creeper"]            = "carnivore",
        ["durzog_wild"]              = "carnivore",
        ["durzog_wild_weaker"]       = "carnivore",
        ["durzog_war"]               = "carnivore",
        ["durzog_war_trained"]       = "carnivore",
        ["bm_frost_boar"]            = "carnivore",
        ["bm_wolf_grey_lvl_1"]       = "carnivore",
        ["bm_wolf_grey"]             = "carnivore",
        ["bm_wolf_snow_unique"]      = "carnivore",
        ["t_cyr_fau_alphyn_01"]      = "carnivore",
        ["t_sky_fau_danswyrm_01"]    = "carnivore",
        ["t_sky_fau_sabcat_01"]      = "carnivore",
        ["t_sky_fau_sabcat_02"]      = "carnivore",
        ["t_mw_fau_tigguar_01"]      = "carnivore",
        ["t_sky_fau_wolfblasml_01"]  = "carnivore",
        ["t_sky_fau_wolfgr_01"]      = "carnivore",
        ["t_sky_fau_wolfbla_01"]     = "carnivore",
        ["t_cyr_fau_wolfcol_02"]     = "carnivore",
        ["t_sky_fau_wolfred_01"]     = "carnivore",
        ["t_cyr_fau_wolfcol_01"]     = "carnivore",
        ["t_sky_fau_raki_01"]        = "carnivore",
        ["t_ham_fau_wormmth_01"]     = "carnivore",
        ["t_mw_fau_thresher_01"]     = "carnivore",
        ["t_mw_fau_para_01"]         = "carnivore",
        ["t_mw_fau_paravn_01"]       = "carnivore",
        ["t_glb_fau_lrgspider_01"]   = "carnivore",
        ["t_glb_fau_lrgspider_02"]   = "carnivore",
        ["t_glb_fau_lrgspider_03"]   = "carnivore",
        ["t_ham_fau_spkworm_01"]     = "carnivore",
        ["t_dae_cre_spiderdae_01"]   = "carnivore",
        ["t_cyr_fau_birdstrid_01"]   = "carnivore",
        ["t_cyr_fau_birdstridn_01"]  = "carnivore",
        ["t_mw_fau_redoranhnd_01"]   = "carnivore",
        ["t_mw_fau_redoranhnd_02"]   = "carnivore",
        ["t_mw_fau_redoranhnd_03"]   = "carnivore",

        -- grazers are herbivores
        ["guar"]                     = "herbivore",
        ["guar_feral"]               = "herbivore",
        ["bm_horker"]                = "herbivore",
        ["bm_horker_large"]          = "herbivore",
        ["t_sky_fau_mamm_01"]        = "herbivore",
        ["t_mw_fau_plstrid_01"]      = "herbivore",

        -- scribs are herbivors
        ["scrib"]              = "herbivore",
        ["scrib_vaba-amus"]    = "herbivore",
        ["scrib_rerlas"]       = "herbivore",
        ["icescrib"]           = "herbivore",
        ["aa_cr_horned_scrib"] = "herbivore",
        ["scrib_2"]            = "herbivore",
        ["ttooth_scrib_2"]     = "herbivore",
        ["ttooth_scrib"]       = "herbivore",

        -- insects & beetles are omnivores
        ["shalk"]                    = "omnivore",
        ["kwama forager"]            = "omnivore",
        ["kwama warrior"]            = "omnivore",
        ["kwama worker"]             = "omnivore",
        ["kwama worker entrance"]    = "omnivore",
        ["t_mw_fau_beetlebl_01"]     = "omnivore",
        ["t_mw_fau_beetleblran_01"]  = "omnivore",
        ["t_mw_fau_beetlebr_01"]     = "omnivore",
        ["t_mw_fau_beetlebrran_01"]  = "omnivore",
        ["t_mw_fau_beetlegr_01"]     = "omnivore",
        ["t_mw_fau_beetlegrran_01"]  = "omnivore",
        ["t_mw_fau_beetlehr_01"]     = "omnivore",
        ["t_mw_fau_beetlehrran_01"]  = "omnivore",
        ["t_mw_fau_yethbug_01"]      = "omnivore",
        ["t_mw_fau_mucklch_01"]      = "omnivore",
        ["t_mw_fau_ornqn_01"]        = "omnivore",
        ["t_mw_fau_sharaihoppe_01"]  = "omnivore",

        -- rats are omnivores
        ["rat"]                      = "omnivore",
        ["t_cyr_fau_muskrat_01"]     = "omnivore",
        ["t_cyr_fau_muskratcol_01"]  = "omnivore",
        ["t_glb_fau_ratbk_01"]       = "omnivore",
        ["t_glb_fau_ratcv_01"]       = "omnivore",
        ["t_glb_fau_ratgr_01"]       = "omnivore",
        ["t_cyr_fau_rat_01"]         = "omnivore",
        ["t_glb_fau_ratcol_01"]      = "omnivore",
        ["t_glb_fau_ratcol_02"]      = "omnivore",
        ["t_glb_fau_ratwt_01"]       = "omnivore",

        -- bears & boars are omnivores
        ["bm_bear_black"]            = "omnivore",
        ["t_sky_fau_bearbk_01"]      = "omnivore",
        ["t_sky_fau_bearred_01"]     = "omnivore",
        ["t_cyr_fau_bearcol_01"]     = "omnivore",
        ["t_sky_fau_beargr_01"]      = "omnivore",
        ["t_sky_fau_bearbr_01"]      = "omnivore",
        ["t_sky_fau_bearsn_01"]      = "omnivore",
        ["t_sky_fau_boar_01"]        = "omnivore",
        ["t_glb_cre_landdreu_01"]    = "omnivore",

        -- mods
        ["ttooth_frost_boar_pigle"]  = "omnivore",
        ["ttooth_bear_brown_cub"]   = "carnivore",
        ["ttooth_bear_black_cub"]   = "carnivore",
        ["ttooth_horker_cub2"]   = "carnivore",
        ["ttooth_wolf_red_pup"]   = "carnivore",
        ["ttooth_wolf_grey_pup"]   = "carnivore",
        ["ttooth_alit_baby2"]   = "carnivore",
        ["ttooth_kagouti_baby"]   = "carnivore",
        ["mu_ice_boar_0"]   = "omnivore",
        ["mu_ice_boar_100"]   = "omnivore",
        ["mu_ice_boar_150"]   = "omnivore",
        ["mu_ice_boar_50"]   = "omnivore",
        ["mu_ice_boar_20"]   = "omnivore",
        ["guar_unscripted"]   = "herbivore",
        ["guar_feral_unscripted"]   = "herbivore",
        ["plx_baby_guar_wild"]   = "herbivore",
        ["ttooth_nix-hound_pup2"]   = "carnivore",
        ["plx_shalk_lesser"]   = "omnivore",
        ["plx_baby_guar"]   = "herbivore",
        ["plx_nixpup"]   = "carnivore",
        ["plx_shalk_herd"]   = "omnivore",
        ["plx_shalk_herdt"]   = "omnivore",
        ["plx_guar_herd"]   = "herbivore",
        ["plx_guar_smaller"]   = "herbivore",
        ["plx_guar_feral_smaller"]   = "herbivore",
    },

    -- diet assumed for any creature missing from CREATURE_DIET
    DEFAULT_DIET = "omnivore",
 
    -- food tables, lower-case record id
    --   herbivores eat items from FOOD_HERBIVORE
    --   carnivores eat items from FOOD_CARNIVORE
    --   omnivores  eat items from either table
    FOOD_HERBIVORE = {
        ["ingred_wickwheat_01"] = true,
        ["ingred_bread_01"]              = true,
        ["ingred_bc_bungler's_bane"]     = true,
        ["ingred_bc_hypha_facia"]        = true,
        ["ingred_scrib_jelly_01"]        = true,
        ["ingred_marshmerrow_01"]        = true,
        ["ingred_saltrice_01"]           = true,
        ["ingred_scuttle_01"]            = true,
        ["ingred_trama_root_01"]         = true,
        ["ingred_coprinus_01"]           = true,
        -- Tamriel Data
        ["t_ingfood_apple_01"]           = true,
        ["t_ingfood_appleskyrim_01"]     = true,
        ["t_ingfood_blackberry_01"]      = true,
        ["t_ingfood_blueberry_01"]       = true,
        ["t_ingfood_breadkeptu_01"]      = true,
        ["t_ingfood_breadkeptu_02"]      = true,
        ["t_ingfood_bread_01"]           = true,
        ["t_ingfood_bread_02"]           = true,
        ["t_ingfood_bread_03"]           = true,
        ["t_ingfood_carrot_01"]          = true,
        ["t_ingfood_cheesecolovian_01"]  = true,
        ["t_ingfood_wheat_01"]           = true,
        ["t_ingfood_grapewrothgarian_01"] = true,
        ["t_ingfood_passionfruit_01"]    = true,
    },
    FOOD_CARNIVORE = {
        ["ingred_scrib_jerky_01"] = true,
        ["ingred_daedras_heart_01"] = true,
        ["ingred_ghoul_heart_01"]   = true,
        ["ingred_hound_meat_01"]    = true,
        ["ingred_kwama_cuttle_01"]  = true,
        ["food_kwama_egg_02"]       = true,
        ["ingred_scuttle_01"]       = true,
        ["food_kwama_egg_01"]       = true,
        -- Tamriel Data
        ["t_ingcrea_barracudasteak_01"]   = true,
        ["t_ingcrea_barracudatailfin_01"] = true,
        ["t_ingcrea_hoomegg_01"]          = true,
        ["t_ingcrea_kwoomegg_01"]         = true,
        ["t_ingcrea_rocegg_01"]           = true,
        ["t_ingcrea_stridentbirdegg_01"]  = true,
        ["t_ingcrea_tanthaegg_01"]        = true,
        ["t_ingfood_eggchicken_01"]       = true,
        ["t_ingfood_eggmolecrab_01"]      = true,
        ["t_ingfood_eggornada_01"]        = true,
        ["t_ingfood_eggseagull_01"]       = true,
        ["t_ingfood_riverstrideregg_01"]  = true,
        ["t_ingcrea_clammeat"]            = true,
        ["t_ingcrea_oystermeat_01"]       = true,
        ["t_ingcrea_oystermeat_02"]       = true,
        ["t_ingcrea_redsharkmeat_01"]     = true,
        ["t_ingfood_meatalit_01"]         = true,
        ["t_ingfood_meatarenthjerky_01"]  = true,
        ["t_ingfood_meatbeef_01"]         = true,
        ["t_ingfood_meatboar_02"]         = true,
        ["t_ingfood_meatchicken_01"]      = true,
        ["t_glb_random_faungoatmeat"]     = true,
        ["t_ingfood_meatguar_01"]         = true,
        ["t_ingfood_meatmutton_01"]       = true,
        ["t_ingfood_meatham_01"]          = true,
        ["t_ingfood_meatparastylus_01"]   = true,
        ["t_ingfood_meathorker_01"]       = true,
        ["t_ingfood_meatornada_01"]       = true,
        ["t_ingfood_meatkwama_01"]        = true,
        ["t_ingfood_meatkagouti_01"]      = true,
        ["t_ingfood_fishpike_01"]         = true,
        ["t_ingfood_meatpork_01"]         = true,
        ["t_ingfood_meatcliffracer_01"]   = true,
    },

    MESSAGES = {
        tamed     = "%s has been tamed.",
        tame_fail = "%s loses interest and wanders off.",
        died      = "%s has died.",
        lost      = "%s breaks free and turns on you!",
        full      = "You cannot tame any more creatures.",
        peace_full = "%s eats the food, but you cannot tame any more creatures.",
        food_refused = "%s sniffs the food but will not eat it.",
        petted    = "You pet %s. %s seems happy.",
        wait      = "%s waits here.",
        rejoin    = "%s rejoins you.",
        knockout  = "%s is knocked out.",
    },

    -- don't change this
    DEFAULTS = {
        MOD_ENABLED        = true,
        MAX_TAMED          = 5,
        BLUNT_ONLY         = true,
        ALLOW_WAIT         = true,
        STAT_GAIN_PERCENT  = 10,
        KNOCKOUT_DURATION  = 6,
        LOSE_DISTANCE      = 8000,
        TOOLTIP_ENABLED    = true,
        FULL_MESSAGE       = true,
        RENAME_ON_TAME     = true,
        KNOCKOUT_ENABLED   = true,
        SWAP_ACTIONS       = false,
        ENABLE_LOGS        = false,
    },
}