return {
{ID="p_almsivi_intervention_s", name="Fool's Luck"},
{ID="p_burden_b", name="Burden Bargain"},
{ID="p_burden_c", name="Burden Cheap"},
{ID="p_burden_e", name="Burden Select"},
{ID="p_burden_q", name="Burden Quality"},
{ID="p_burden_s", name="Burden Normal"},
{ID="p_chameleon_b", name="Shadow Bargain"},
{ID="p_chameleon_c", name="Shadow Cheap"},
{ID="p_chameleon_e", name="Shadow Select"},
{ID="p_chameleon_q", name="Shadow Quality"},
{ID="p_chameleon_s", name="Shadow Normal"},
{ID="p_cure_blight_s", name="Cure Blight Disease"},
{ID="p_cure_common_s", name="Cure Common Disease"},
{ID="p_cure_paralyzation_s", name="Cure Paralysis"},
{ID="p_cure_poison_s", name="Cure Poison"},
{ID="p_detect_creatures_s", name="Detect Creatures"},
{ID="p_detect_enchantment_s", name="Detect Enchantments"},
{ID="p_detect_key_s", name="Detect Key"},
{ID="p_disease_resistance_b", name="Resist Disease Bargain"},
{ID="p_disease_resistance_c", name="Resist Disease Cheap"},
{ID="p_disease_resistance_e", name="Resist Disease Select"},
{ID="p_disease_resistance_q", name="Resist Disease Quality"},
{ID="p_disease_resistance_s", name="Resist Disease Normal"},
{ID="p_dispel_s", name="Dispel"},
{ID="p_drain willpower_q", name="Spoiled Potion of Cure Disease"},
{ID="p_drain_agility_q", name="Spoiled Potion of Slowfalling"},
{ID="p_drain_endurance_q", name="Spoiled Potion of Slowfalling"},
{ID="p_drain_luck_q", name="Spoiled Potion of Cure Disease"},
{ID="p_drain_magicka_q", name="Spoiled Potion of Cure Poison"},
{ID="p_drain_speed_q", name="Spoiled Potion of Cure Poison"},
{ID="p_drain_strength_q", name="Spoiled Potion of Cure Disease"},
{ID="p_feather_b", name="Feather Bargain"},
{ID="p_feather_c", name="Feather Cheap"},
{ID="p_feather_e", name="Feather Select"},
{ID="p_feather_q", name="Feather Quality"},
{ID="p_fire resistance_s", name="Resist Fire Normal"},
{ID="p_fire_resistance_b", name="Resist Fire Bargain"},
{ID="p_fire_resistance_c", name="Resist Fire Cheap"},
{ID="p_fire_resistance_e", name="Resist Fire Select"},
{ID="p_fire_resistance_q", name="Resist Fire Quality"},
{ID="p_fire_shield_b", name="Shield Fire Bargain"},
{ID="p_fire_shield_c", name="Shield Fire Cheap"},
{ID="p_fire_shield_e", name="Shield Fire Select"},
{ID="p_fire_shield_q", name="Shield Fire Quality"},
{ID="p_fire_shield_s", name="Shield Fire Normal"},
{ID="p_fortify_agility_b", name="Fortify Agility Bargain"},
{ID="p_fortify_agility_c", name="Fortify Agility Cheap"},
{ID="p_fortify_agility_e", name="Fortify Agility Select"},
{ID="p_fortify_agility_q", name="Fortify Agility Quality"},
{ID="p_fortify_agility_s", name="Fortify Agility Normal"},
{ID="p_fortify_attack_e", name="Fortify Attack Select"},
{ID="p_fortify_endurance_b", name="Fortify Endurance Bargain"},
{ID="p_fortify_endurance_c", name="Fortify Endurance Cheap"},
{ID="p_fortify_endurance_e", name="Fortify Endurance Select"},
{ID="p_fortify_endurance_q", name="Fortify Endurance Quality"},
{ID="p_fortify_endurance_s", name="Fortify Endurance Normal"},
{ID="p_fortify_fatigue_b", name="Fortify Fatigue Bargain"},
{ID="p_fortify_fatigue_c", name="Fortify Fatigue Cheap"},
{ID="p_fortify_fatigue_e", name="Fortify Fatigue Select"},
{ID="p_fortify_fatigue_q", name="Fortify Fatigue Quality"},
{ID="p_fortify_fatigue_s", name="Fortify Fatigue Normal"},
{ID="p_fortify_health_b", name="Fortify Health Bargain"},
{ID="p_fortify_health_c", name="Fortify Health Cheap"},
{ID="p_fortify_health_e", name="Fortify Health Select"},
{ID="p_fortify_health_q", name="Fortify Health Quality"},
{ID="p_fortify_health_s", name="Fortify Health Normal"},
{ID="p_fortify_intelligence_b", name="Fortify Intelligence Bargain"},
{ID="p_fortify_intelligence_c", name="Fortify Intelligence Cheap"},
{ID="p_fortify_intelligence_e", name="Fortify Intelligence Select"},
{ID="p_fortify_intelligence_q", name="Fortify Intelligence Quality"},
{ID="p_fortify_intelligence_s", name="Fortify Intelligence Normal"},
{ID="p_fortify_luck_b", name="Fortify Luck Bargain"},
{ID="p_fortify_luck_c", name="Fortify Luck Cheap"},
{ID="p_fortify_luck_e", name="Fortify Luck Select"},
{ID="p_fortify_luck_q", name="Fortify Luck Quality"},
{ID="p_fortify_luck_s", name="Fortify Luck Normal"},
{ID="p_fortify_magicka_b", name="Fortify Magicka Bargain"},
{ID="p_fortify_magicka_c", name="Fortify Magicka Cheap"},
{ID="p_fortify_magicka_e", name="Fortify Magicka Select"},
{ID="p_fortify_magicka_q", name="Fortify Magicka Quality"},
{ID="p_fortify_magicka_s", name="Fortify Magicka Normal"},
{ID="p_fortify_personality_b", name="Fortify Personality Bargain"},
{ID="p_fortify_personality_c", name="Fortify Personality Cheap"},
{ID="p_fortify_personality_e", name="Fortify Personality Select"},
{ID="p_fortify_personality_q", name="Fortify Personality Quality"},
{ID="p_fortify_personality_s", name="Fortify Personality Normal"},
{ID="p_fortify_speed_b", name="Fortify Speed Bargain"},
{ID="p_fortify_speed_c", name="Fortify Speed Cheap"},
{ID="p_fortify_speed_e", name="Fortify Speed Select"},
{ID="p_fortify_speed_q", name="Fortify Speed Quality"},
{ID="p_fortify_speed_s", name="Fortify Speed Normal"},
{ID="p_fortify_strength_b", name="Fortify Strength Bargain"},
{ID="p_fortify_strength_c", name="Fortify Strength Cheap"},
{ID="p_fortify_strength_e", name="Fortify Strength Select"},
{ID="p_fortify_strength_q", name="Fortify Strength Quality"},
{ID="p_fortify_strength_s", name="Fortify Strength Normal"},
{ID="p_fortify_willpower_b", name="Fortify Willpower Bargain"},
{ID="p_fortify_willpower_c", name="Fortify Willpower Cheap"},
{ID="p_fortify_willpower_e", name="Fortify Willpower Select"},
{ID="p_fortify_willpower_q", name="Fortify Willpower Quality"},
{ID="p_fortify_willpower_s", name="Fortify Willpower Normal"},
{ID="p_frost_resistance_b", name="Resist Frost Bargain"},
{ID="p_frost_resistance_c", name="Resist Frost Cheap"},
{ID="p_frost_resistance_e", name="Resist Frost Select"},
{ID="p_frost_resistance_q", name="Resist Frost Quality"},
{ID="p_frost_resistance_s", name="Resist Frost Normal"},
{ID="p_frost_shield_b", name="Shield Frost Bargain"},
{ID="p_frost_shield_c", name="Shield Frost Cheap"},
{ID="p_frost_shield_e", name="Shield Frost Select"},
{ID="p_frost_shield_q", name="Shield Frost Quality"},
{ID="p_frost_shield_s", name="Shield Frost Normal"},
{ID="p_heroism_s", name="Heroism"},
{ID="p_invisibility_b", name="Invisibility Bargain"},
{ID="p_invisibility_c", name="Invisibility Cheap"},
{ID="p_invisibility_e", name="Invisibility Select"},
{ID="p_invisibility_q", name="Invisibility Quality"},
{ID="p_invisibility_s", name="Invisibility Normal"},
{ID="p_jump_b", name="Jump Bargain"},
{ID="p_jump_c", name="Jump Cheap"},
{ID="p_jump_e", name="Jump Select"},
{ID="p_jump_q", name="Jump Quality"},
{ID="p_jump_s", name="Jump Normal"},
{ID="p_levitation_b", name="Rising Force Bargain"},
{ID="p_levitation_c", name="Rising Force Cheap"},
{ID="p_levitation_e", name="Rising Force Select"},
{ID="P_Levitation_Q", name="Rising Force Quality"},
{ID="p_levitation_s", name="Rising Force Normal"},
{ID="p_light_b", name="Light Bargain"},
{ID="p_light_c", name="Light Cheap"},
{ID="p_light_e", name="Light Select"},
{ID="p_light_q", name="Light Quality"},
{ID="p_light_s", name="Light Normal"},
{ID="p_lightning shield_b", name="Shield Lightning Bargain"},
{ID="p_lightning shield_c", name="Shield Lightning Cheap"},
{ID="p_lightning shield_e", name="Shield Lightning Select"},
{ID="p_lightning shield_q", name="Shield Lightning Quality"},
{ID="p_lightning shield_s", name="Shield Lightning Normal"},
{ID="p_magicka_resistance_b", name="Resist Magicka Bargain"},
{ID="p_magicka_resistance_c", name="Resist Magicka Cheap"},
{ID="p_magicka_resistance_e", name="Resist Magicka Select"},
{ID="p_magicka_resistance_q", name="Resist Magicka Quality"},
{ID="p_magicka_resistance_s", name="Resist Magicka Normal"},
{ID="p_night-eye_b", name="Night-Eye Bargain"},
{ID="p_night-eye_c", name="Night-Eye Cheap"},
{ID="p_night-eye_e", name="Night-Eye Select"},
{ID="p_night-eye_q", name="Night-Eye Quality"},
{ID="p_night-eye_s", name="Night-Eye Normal"},
{ID="p_paralyze_b", name="Paralyze Bargain"},
{ID="p_paralyze_c", name="Paralyze Cheap"},
{ID="p_paralyze_e", name="Paralyze Select"},
{ID="p_paralyze_q", name="Paralyze Quality"},
{ID="p_paralyze_s", name="Paralyze Normal"},
{ID="p_poison_resistance_b", name="Resist Poison Bargain"},
{ID="p_poison_resistance_c", name="Resist Poison Cheap"},
{ID="p_poison_resistance_e", name="Resist Poison Select"},
{ID="p_poison_resistance_q", name="Resist Poison Quality"},
{ID="p_poison_resistance_s", name="Resist Poison Normal"},
{ID="p_reflection_b", name="Reflection Bargain"},
{ID="p_reflection_c", name="Reflection Cheap"},
{ID="p_reflection_e", name="Reflection Select"},
{ID="p_reflection_q", name="Reflection Quality"},
{ID="p_reflection_s", name="Reflection Normal"},
{ID="p_restore_agility_b", name="Restore Agility Bargain"},
{ID="p_restore_agility_c", name="Restore Agility Cheap"},
{ID="p_restore_agility_e", name="Restore Agility Select"},
{ID="p_restore_agility_q", name="Restore Agility Quality"},
{ID="p_restore_agility_s", name="Restore Agility Normal"},
{ID="p_restore_endurance_b", name="Restore Endurance Bargain"},
{ID="p_restore_endurance_c", name="Restore Endurance Cheap"},
{ID="p_restore_endurance_e", name="Restore Endurance Select"},
{ID="p_restore_endurance_q", name="Restore Endurance Quality"},
{ID="p_restore_endurance_s", name="Restore Endurance Normal"},
{ID="p_restore_fatigue_b", name="Restore Fatigue Bargain"},
{ID="p_restore_fatigue_c", name="Restore Fatigue Cheap"},
{ID="p_restore_fatigue_e", name="Restore Fatigue Select"},
{ID="p_restore_fatigue_q", name="Restore Fatigue Quality"},
{ID="p_restore_fatigue_s", name="Restore Fatigue Normal"},
{ID="p_restore_health_b", name="Restore Health Bargain"},
{ID="p_restore_health_c", name="Restore Health Cheap"},
{ID="p_restore_health_e", name="Restore Health Select"},
{ID="p_restore_health_q", name="Restore Health Quality"},
{ID="p_restore_health_s", name="Restore Health Normal"},
{ID="p_restore_intelligence_b", name="Restore Intelligence Bargain"},
{ID="p_restore_intelligence_c", name="Restore Intelligence Cheap"},
{ID="p_restore_intelligence_e", name="Restore Intelligence Select"},
{ID="p_restore_intelligence_q", name="Restore Intelligence Quality"},
{ID="p_restore_intelligence_s", name="Restore Intelligence Normal"},
{ID="p_restore_luck_b", name="Restore Luck Bargain"},
{ID="p_restore_luck_c", name="Restore Luck Cheap"},
{ID="p_restore_luck_e", name="Restore Luck Select"},
{ID="p_restore_luck_q", name="Restore Luck Quality"},
{ID="p_restore_luck_s", name="Restore Luck Normal"},
{ID="p_restore_magicka_b", name="Restore Magicka Bargain"},
{ID="p_restore_magicka_c", name="Restore Magicka Cheap"},
{ID="p_restore_magicka_e", name="Restore Magicka Select"},
{ID="p_restore_magicka_q", name="Restore Magicka Quality"},
{ID="p_restore_magicka_s", name="Restore Magicka Normal"},
{ID="p_restore_personality_b", name="Restore Personality Bargain"},
{ID="p_restore_personality_c", name="Restore Personality Cheap"},
{ID="p_restore_personality_e", name="Restore Personality Select"},
{ID="p_restore_personality_q", name="Restore Personality Quality"},
{ID="p_restore_personality_s", name="Restore Personality Normal"},
{ID="p_restore_speed_b", name="Restore Speed Bargain"},
{ID="p_restore_speed_c", name="Restore Speed Cheap"},
{ID="p_restore_speed_e", name="Restore Speed Select"},
{ID="p_restore_speed_q", name="Restore Speed Quality"},
{ID="p_restore_speed_s", name="Restore Speed Normal"},
{ID="p_restore_strength_b", name="Restore Strength Bargain"},
{ID="p_restore_strength_c", name="Restore Strength Cheap"},
{ID="p_restore_strength_e", name="Restore Strength Select"},
{ID="p_restore_strength_q", name="Restore Strength Quality"},
{ID="p_restore_strength_s", name="Restore Strength Normal"},
{ID="p_restore_willpower_b", name="Restore Willpower Bargain"},
{ID="p_restore_willpower_c", name="Restore Willpower Cheap"},
{ID="p_restore_willpower_e", name="Restore Willpower Select"},
{ID="p_restore_willpower_q", name="Restore Willpower Quality"},
{ID="p_restore_willpower_s", name="Restore Willpower Normal"},
{ID="p_shock_resistance_b", name="Resist Shock Bargain"},
{ID="p_shock_resistance_c", name="Resist Shock Cheap"},
{ID="p_shock_resistance_e", name="Resist Shock Select"},
{ID="p_shock_resistance_q", name="Resist Shock Quality"},
{ID="p_shock_resistance_s", name="Resist Shock Normal"},
{ID="p_silence_b", name="Silence Bargain"},
{ID="p_silence_c", name="Silence Cheap"},
{ID="p_silence_e", name="Silence Select"},
{ID="p_silence_q", name="Silence Quality"},
{ID="p_silence_s", name="Silence Normal"},
{ID="p_slowfall_s", name="Slowfalling"},
{ID="p_spell_absorption_b", name="Spell Absorption Bargain"},
{ID="p_spell_absorption_c", name="Spell Absorption Cheap"},
{ID="p_spell_absorption_e", name="Spell Absorption Select"},
{ID="p_spell_absorption_q", name="Spell Absorption Quality"},
{ID="p_spell_absorption_s", name="Spell Absorption Normal"},
{ID="p_swift_swim_b", name="Swift Swim Bargain"},
{ID="p_swift_swim_c", name="Swift Swim Cheap"},
{ID="p_swift_swim_e", name="Swift Swim Select"},
{ID="p_swift_swim_q", name="Swift Swim Quality"},
{ID="p_telekinesis_s", name="Telekinesis"},
{ID="p_water_breathing_s", name="Water Breathing"},
{ID="p_water_walking_s", name="Water Walking"},
{ID="AB_dri_TramaTea", name="Cup of Trama Root Tea"},
{ID="ab01p_divine_intervention", name="Holy Luck"},
{ID="ab01p_water_breathing_e", name="Water Breathing Select"},
{ID="ab01p_water_breathing_q", name="Water Breathing Quality"},
{ID="KO_CMK_Teacup", name="Cup of Hot Tea"},
{ID="ks_water_walking_p", name="Water Walking Super"},
{ID="MWlib_teamug_01", name="Mug of Tea Black"},
{ID="MWlib_teamug_02", name="Mug of Tea White"},
{ID="MWlib_teamug_03", name="Mug of Tea Red"},
{ID="MWlib_teamug_04", name="Mug of Tea Green"},
{ID="MWlib_teamug_05", name="Mug of Tea Nori Salt"},
{ID="MWlib_teamug_06", name="Mug of Tea Pink"},
{ID="MWlib_teamug_07", name="Mug of Tea Ginger Spice"},
{ID="MWlib_teamug_08", name="Mug of Tea Golden"},
{ID="MWlib_teamug_09", name="Mug of Tea Dragon"},
{ID="PB_ASP_Potion2", name="Nirnroot Elixir of Quality"},
{ID="T_Com_Potion_ResistParalysis_B", name="Resist Paralysis Bargain"},
{ID="T_Com_Potion_ResistParalysis_C", name="Resist Paralysis Cheap"},
{ID="T_Com_Potion_ResistParalysis_E", name="Resist Paralysis Select"},
{ID="T_Com_Potion_ResistParalysis_Q", name="Resist Paralysis Quality"},
{ID="T_Com_Potion_ResistParalysis_S", name="Resist Paralysis Normal"},
{ID="T_Nor_Drink_Beer_01", name="Mug of Beer"},
{ID="T_Nor_Drink_BeerLight_01", name="Mug of Beer Light"},
{ID="T_Nor_Potion_Burden_C", name="Burden Cheap"},
{ID="T_Nor_Potion_Burden_Q", name="Burden Quality"},
{ID="T_Nor_Potion_Chameleon_C", name="Shadow Cheap"},
{ID="T_Nor_Potion_Chameleon_Q", name="Shadow Quality"},
{ID="T_Nor_Potion_CureCommon_01", name="Cure Common Disease Plus"},
{ID="T_Nor_Potion_DrainAgility_Q", name="Spoiled Potion of SlowFall"},
{ID="T_Nor_Potion_DrainEndurance_Q", name="Spoiled Potion of SlowFall"},
{ID="T_Nor_Potion_DrainLuck_Q", name="Spoiled Potion of Cure Disease"},
{ID="T_Nor_Potion_DrainMagicka_Q", name="Spoiled Potion of Cure Poison"},
{ID="T_Nor_Potion_DrainSpeed_Q", name="Spoiled Potion of Cure Poison"},
{ID="T_Nor_Potion_DrainStrength_Q", name="Spoiled Potion of Cure Disease"},
{ID="T_Nor_Potion_DrainWillpow_Q", name="Spoiled Potion of Cure Disease"},
{ID="T_Nor_Potion_Feather_C", name="Feather Cheap"},
{ID="T_Nor_Potion_Feather_Q", name="Feather Quality"},
{ID="T_Nor_Potion_FortifyAgility_C", name="Fortify Agility Cheap"},
{ID="T_Nor_Potion_FortifyAgility_Q", name="Fortify Agility Quality"},
{ID="T_Nor_Potion_FortifyEndurance_C", name="Fortify Endurance Cheap"},
{ID="T_Nor_Potion_FortifyEndurance_Q", name="Fortify Endurance Quality"},
{ID="T_Nor_Potion_FortifyFatigue_C", name="Fortify Fatigue Cheap"},
{ID="T_Nor_Potion_FortifyFatigue_Q", name="Fortify Fatigue Quality"},
{ID="T_Nor_Potion_FortifyHealth_C", name="Fortify Health Cheap"},
{ID="T_Nor_Potion_FortifyHealth_Q", name="Fortify Health Quality"},
{ID="T_Nor_Potion_FortifyIntell_C", name="Fortify Intelligence Cheap"},
{ID="T_Nor_Potion_FortifyIntelli_Q", name="Fortify Intelligence Quality"},
{ID="T_Nor_Potion_FortifyLuck_C", name="Fortify Luck Cheap"},
{ID="T_Nor_Potion_FortifyLuck_Q", name="Fortify Luck Quality"},
{ID="T_Nor_Potion_FortifyMagicka_C", name="Fortify Magicka Cheap"},
{ID="T_Nor_Potion_FortifyMagicka_Q", name="Fortify Magicka Quality"},
{ID="T_Nor_Potion_FortifyPersonal_C", name="Fortify Personality Cheap"},
{ID="T_Nor_Potion_FortifyPersonal_Q", name="Fortify Personality Quality"},
{ID="T_Nor_Potion_FortifySpeed_C", name="Fortify Speed Cheap"},
{ID="T_Nor_Potion_FortifySpeed_Q", name="Fortify Speed Quality"},
{ID="T_Nor_Potion_FortifyStrength_C", name="Fortify Strength Cheap"},
{ID="T_Nor_Potion_FortifyStrength_Q", name="Fortify Strength Quality"},
{ID="T_Nor_Potion_FortifyWillpow_C", name="Fortify Willpower Cheap"},
{ID="T_Nor_Potion_FortifyWillpow_Q", name="Fortify Willpower Quality"},
{ID="T_Nor_Potion_Invisibility_C", name="Invisibility Cheap"},
{ID="T_Nor_Potion_Invisibility_Q", name="Invisibility Quality"},
{ID="T_Nor_Potion_Jump_C", name="Jump Cheap"},
{ID="T_Nor_Potion_Jump_Q", name="Jump Quality"},
{ID="T_Nor_Potion_Levitation_C", name="Levitation Cheap"},
{ID="T_Nor_Potion_Levitation_Q", name="Rising Force Quality"},
{ID="T_Nor_Potion_Light_C", name="Light Cheap"},
{ID="T_Nor_Potion_Light_Q", name="Light Quality"},
{ID="T_Nor_Potion_NightEye_C", name="Night-Eye Cheap"},
{ID="T_Nor_Potion_NightEye_Q", name="Night-Eye Quality"},
{ID="T_Nor_Potion_Paralyze_C", name="Paralyze Cheap"},
{ID="T_Nor_Potion_Paralyze_Q", name="Paralyze Quality"},
{ID="T_Nor_Potion_Reflection_C", name="Reflection Cheap"},
{ID="T_Nor_Potion_Reflection_Q", name="Reflection Quality"},
{ID="T_Nor_Potion_ResistDesease_C", name="Resist Disease Cheap"},
{ID="T_Nor_Potion_ResistDisease_Q", name="Resist Disease Quality"},
{ID="T_Nor_Potion_ResistFire_C", name="Resist Fire Cheap"},
{ID="T_Nor_Potion_ResistFire_Q", name="Resist Fire Quality"},
{ID="T_Nor_Potion_ResistFrost_C", name="Resist Frost Cheap"},
{ID="T_Nor_Potion_ResistFrost_Q", name="Resist Frost Quality"},
{ID="T_Nor_Potion_ResistMagicka_C", name="Resist Magicka Cheap"},
{ID="T_Nor_Potion_ResistMagicka_Q", name="Resist Magicka Quality"},
{ID="T_Nor_Potion_ResistPoison_C", name="Resist Poison Cheap"},
{ID="T_Nor_Potion_ResistPoison_Q", name="Resist Poison Quality"},
{ID="T_Nor_Potion_ResistShock_C", name="Resist Shock Cheap"},
{ID="T_Nor_Potion_ResistShock_Q", name="Resist Shock Quality"},
{ID="T_Nor_Potion_RestoreAgility_C", name="Restore Agility Cheap"},
{ID="T_Nor_Potion_RestoreAgility_Q", name="Restore Agility Quality"},
{ID="T_Nor_Potion_RestoreEnduranc_C", name="Restore Endurance Cheap"},
{ID="T_Nor_Potion_RestoreEndurance_Q", name="Restore Endurance Quality"},
{ID="T_Nor_Potion_RestoreFatigue_C", name="Restore Fatigue Cheap"},
{ID="T_Nor_Potion_RestoreFatigue_Q", name="Restore Fatigue Quality"},
{ID="T_Nor_Potion_RestoreHealth_C", name="Restore Health Cheap"},
{ID="T_Nor_Potion_RestoreHealth_Q", name="Restore Health Quality"},
{ID="T_Nor_Potion_RestoreIntelli_C", name="Restore Intelligence Cheap"},
{ID="T_Nor_Potion_RestoreIntelli_Q", name="Restore Intelligence Quality"},
{ID="T_Nor_Potion_RestoreLuck_C", name="Restore Luck Cheap"},
{ID="T_Nor_Potion_RestoreLuck_Q", name="Restore Luck Quality"},
{ID="T_Nor_Potion_RestoreMagicka_C", name="Restore Magicka Cheap"},
{ID="T_Nor_Potion_RestoreMagicka_Q", name="Restore Magicka Quality"},
{ID="T_Nor_Potion_RestorePersonal_C", name="Restore Personality Cheap"},
{ID="T_Nor_Potion_RestorePersonal_Q", name="Restore Personality Quality"},
{ID="T_Nor_Potion_RestoreSpeed_C", name="Restore Speed Cheap"},
{ID="T_Nor_Potion_RestoreSpeed_Q", name="Restore Speed Quality"},
{ID="T_Nor_Potion_RestoreStrength_C", name="Restore Strength Cheap"},
{ID="T_Nor_Potion_RestoreStrength_Q", name="Restore Strength Quality"},
{ID="T_Nor_Potion_RestoreWillpow_C", name="Restore Willpower Cheap"},
{ID="T_Nor_Potion_RestoreWillpow_Q", name="Restore Willpower Quality"},
{ID="T_Nor_Potion_ShieldFire_C", name="Shield Fire Cheap"},
{ID="T_Nor_Potion_ShieldFire_Q", name="Shield Fire Quality"},
{ID="T_Nor_Potion_ShieldFrost_C", name="Shield Frost Cheap"},
{ID="T_Nor_Potion_ShieldFrost_Q", name="Shield Frost Quality"},
{ID="T_Nor_Potion_ShieldLightning_C", name="Shield Lightning Cheap"},
{ID="T_Nor_Potion_ShieldLightning_Q", name="Shield Lightning Quality"},
{ID="T_Nor_Potion_Silence_C", name="Silence Cheap"},
{ID="T_Nor_Potion_Silence_Q", name="Silence Quality"},
{ID="T_Nor_Potion_SpellAbsorbtion_C", name="Spell Absorption Cheap"},
{ID="T_Nor_Potion_SpellAbsorbtion_Q", name="Spell Absorption Quality"},
{ID="T_Nor_Potion_SwiftSwim_C", name="Swift Swim Cheap"},
{ID="T_Nor_Potion_Swiftswim_Q", name="Swift Swim Quality"},
{ID="potion_skooma_01", name="Bottle of Skooma"},
{ID="Potion_Cyro_Whiskey_01", name="Bottle of Flin"},
{ID="potion_comberry_wine_01", name="Bottle of Shein"},
{ID="potion_cyro_brandy_01", name="Bottle of Cyrodiilic Brandy"},
{ID="potion_comberry_brandy_01", name="Bottle of Greef"},
{ID="Potion_Local_Brew_01", name="Bottle of Mazte"},
{ID="potion_local_liquor_01", name="Bottle of Sujamma"},
{ID="potion_t_bug_musk_01", name="Bottle of Telvanni Bug Musk"},
{ID="potion_ancient_brandy", name="Bottle of Ancient Dagoth Brandy"},
{ID="p_vintagecomberrybrandy1", name="Bottle of Vintage Brandy"},
{ID="p_cure_common_unique", name="Potion of Curing Trebonius'"},
{ID="p_sinyaramen_UNIQUE", name="Potion of Sinyaramen"},
{ID="p_lovepotion_unique", name="Potion of Love"},
{ID="pyroil_tar_unique", name="Bottle of Pyroil Tar"},
{ID="p_dwemer_lubricant00", name="Bottle of Spoiled Dwemer Oil"},
{ID="verminous_fabricant_elixir", name="Elixir of Fabricant Verminous"},
{ID="hulking_fabricant_elixir", name="Elixir of Fabricant Hulking"},
{ID="potion_nord_mead", name="Mug of Nord Mead"},
{ID="T_De_Drink_LiquorLlotham_01", name="Bottle of Llotham"},
{ID="T_De_Drink_PunavitJug", name="Bottle of Punavit"},
{ID="T_Rea_Drink_TeaGyrrg_01", name="Bottle of Gyrgg"},
{ID="T_Orc_Drink_LiquorUngorth_02", name="Bottle of Ungorth"},
{ID="T_Rea_Drink_LiquorAeli_01", name="Bottle of Aeli"},
{ID="T_Nor_Drink_WineReach_01", name="Bottled Wine Reach Vintage"},
{ID="T_Imp_Drink_WineTwinMoon_01", name="Bottled Wine Twin Moons"},
{ID="T_Imp_Drink_WineTamikaClr_01", name="Bottled Wine Tamika's Cellar"},
{ID="T_Imp_Drink_WineFreeEstat_01", name="Bottled Wine Free Estates"},
{ID="T_Imp_Drink_WineSurilieBr_01", name="Bottled Wine Surilie Brothers"},
{ID="T_Imp_Drink_WineWolfsbl_01", name="Bottled Wine Wolfsblood"},
{ID="T_Imp_Drink_WinePlalloVin_01", name="Bottled Wine Plallo Vineyard"},
{ID="T_Imp_Drink_AleAkul_01", name="Bottle of Akul"},
{ID="T_Imp_Drink_CiderAliyew_01", name="Bottle of Aliyew"},
{ID="T_Imp_Drink_CherryBrandy_01", name="Bottle of Kurst"},
{ID="T_Imp_Drink_RicebeerMori_01", name="Bottle of Mori"},
{ID="T_Imp_Subst_SloadOil_01", name="Bottle of Sload Oil"},
{ID="T_Imp_Drink_WineBlackhill_01", name="Bottled Wine Black Hills"},
{ID="T_Imp_Drink_WineRufinoClr_01", name="Bottled Wine Rufino's Cellar"},
{ID="T_Rga_Drink_WineSutchTalan_01", name="Bottled Wine Talan's Heritage"},
{ID="T_Rga_Drink_WineSutchGoNogro_01", name="Bottled Wine Go Nogro"},
{ID="T_Nor_Drink_SnowberryaleVeig_01", name="Bottle of Veig"},
{ID="T_De_Drink_BourbonGoya_01", name="Bottle of Goya"},
{ID="T_We_Drink_PigmilkbeerJagga_01", name="Bottle of Jagga"},
{ID="T_Bre_Drink_WineWayrest_01", name="Bottled Wine Wayrest Spiced"},
{ID="T_Imp_Drink_WineBattle_01", name="Bottled Colovian Battlewine"},
{ID="T_Nor_Subst_WasabiPaste_01", name="Paste Wasabi"},
{ID="T_Rga_Drink_Sift", name="Bottle of Sift"},
{ID="T_Com_Subst_Vitriol_Oil_01", name="Bottle of Vitriol Oil"},
{ID="T_Com_Subst_Phyrric_Acid_01", name="Bottle of Phyrric Acid"},
{ID="T_Com_Subst_Aqua_Vita_01", name="Bottle of Aqua Vita"},
{ID="T_Imp_Subst_Incarnadine_01", name="Bottle of Incarnadine"},
{ID="T_De_Drink_PunavitResin_01", name="Bottle of Punavit Residue"},
{ID="T_Imp_Drink_WineSour", name="Bottled Wine Sour"},
{ID="T_Imp_Drink_WineSweet", name="Bottled Wine Sweet"},
{ID="T_Nor_Drink_Fyrg_01", name="Bottle of Fyrg"},
{ID="T_Nor_Drink_Bodja_01", name="Bottle of Bodja"},
{ID="T_Com_Potion_DragonBlood", name="Dragon's Blood"},
{ID="T_De_Drink_GuarMilk_01", name="Bottled Guar Milk"},
{ID="AB_dri_Musa", name="Bottle of Musa"},
{ID="AB_dri_GuarMilk", name="Bottle of Guar Milk"},
{ID="AB_dri_Yamuz", name="Bottle of Yamuz"},
{ID="AB_eff_KwamaPoison", name="Bottle of Kwama Poison"},
{ID="crcl_emptyshein", name="Bottle of Mostly-Empty Shein"},
{ID="crcl_ale1", name="Bottled Ale Bitter Diamond"},
{ID="crcl_ale2", name="Bottled Ale Nocturnal's Reserve"},
{ID="crcl_ale3", name="Bottled Ale Magnus' Golden Ale"},
{ID="crcl_ale4", name="Bottled Ale Lorkhan's Couchlock"},
{ID="crcl_ale5", name="Bottled Ale Ja-Kha'jay Secret"},
{ID="Ascadian Ale 1", name="Mug of Redoran Red"},
{ID="Ascadian Ale 3", name="Mug of Umbra Stout"},
{ID="Ascadian Lager1", name="Mug of Ascadian Screamer"},
{ID="Ascadian Lager2", name="Mug of Hamerfell Thunder"},
{ID="Ascadian Ale4", name="Mug of Dead Guard"},
{ID="Ascadian Mead", name="Mug of Solstheim Sunset"},
{ID="Ascadian Ale 2", name="Mug of Nordic Blonde"},
{ID="Ascadian Ale7", name="Mug of Bitter Coast Bitter"},
{ID="Ascadian Ale 5", name="Mug of Goldmine"},
{ID="a0cw_balmorablue", name="Bottle of Balmora Blue"},
{ID="sl_vos_p_health", name="Eldrilu's Regeneration"},
{ID="IEO_greef_unique", name="Bottle of Greef"},
{ID="NOM_beer_02", name="Bottled Beer Lucky Star"},
{ID="NOM_beer_03", name="Bottled Beer Common Jug"},
{ID="NOM_beer_04", name="Bottled Beer Whiterun"},
{ID="NOM_beer_08", name="Bottled Beer Common"},
{ID="NOM_beer_09", name="Bottled Beer Dwemer"},
{ID="NOM_juice_apple", name="Bottled Juice Apple"},
{ID="NOM_juice_comberry", name="Bottled Juice Berry"},
{ID="NOM_juice_orange", name="Bottled Juice Orange"},
{ID="NOM_juice_pear", name="Bottled Juice Pear"},
{ID="NOM_swamp_oil", name="Bottle of Swamp Oil"},
{ID="NOM_wine_03", name="Bottled Wine Cheap Jug"},
{ID="NOM_wine_04", name="Bottled Wine Fox Tail"},
{ID="NOM_wine_08", name="Bottled Wine Cheap"},
{ID="NOM_wine_09", name="Bottled Wine Moon's Tear"},
{ID="MI_absinthe", name="Bottle of Absinthe"},
{ID="ABtv_pot_CureParalysis", name="Cure Paralysis by Aryon"},
{ID="ABtv_pot_CureBlightMMCure", name="Cure Blight Disease"},
{ID="ABtv_dri_SheinVintage", name="Bottle of Vintage Wine"},
{ID="AB_dri_Sillapi", name="Bottle of Sillapi"},
}
