return {
{ID="pick_apprentice_01", name="Lockpick Apprentice's"},
{ID="pick_journeyman_01", name="Lockpick Journeyman's"},
{ID="pick_master", name="Lockpick Master's"},
{ID="pick_grandmaster", name="Lockpick Master's Grand"},
{ID="pick_secretmaster", name="Lockpick Master's Secret"},
{ID="T_Com_Thief_Fork01", name="Lockpick Thief's Fork"},
{ID="probe_apprentice_01", name="Probe Apprentice's"},
{ID="probe_journeyman_01", name="Probe Journeyman's"},
{ID="probe_master", name="Probe Master's"},
{ID="probe_grandmaster", name="Probe Master's Grand"},
{ID="probe_secretmaster", name="Probe Master's Secret"},
{ID="T_Com_Thief_Spoon01", name="Probe Thief's Spoon"},
{ID="hammer_repair", name="Armorer Hammer Apprentice's"},
{ID="repair_journeyman_01", name="Armorer Hammer Journeyman's"},
{ID="repair_master_01", name="Armorer Hammer Master's"},
{ID="repair_grandmaster_01", name="Armorer Hammer Master's Grand"},
{ID="repair_secretmaster_01", name="Armorer Hammer Master's Secret"},
{ID="T_Com_Hammer_Repair_01", name="Repair Hammer"},
{ID="T_Com_Hammer_Repair_02", name="Repair Hammer Ball-peen"},
{ID="T_Dwe_UNI_HammerGharen_01", name="Repair Hammer of Gharen"},
{ID="apparatus_a_spipe_01", name="Skooma Pipe Good"},
{ID="apparatus_a_spipe_tsiya", name="Skooma Pipe Tsiya's"},
{ID="apparatus_a_alembic_01", name="Alembic Apprentice's"},
{ID="apparatus_j_alembic_01", name="Alembic Journeyman's"},
{ID="apparatus_m_alembic_01", name="Alembic Master's"},
{ID="apparatus_g_alembic_01", name="Alembic Master's Grand"},
{ID="apparatus_sm_alembic_01", name="Alembic Master's Secret"},
{ID="apparatus_a_calcinator_01", name="Calcinator Apprentice's"},
{ID="apparatus_j_calcinator_01", name="Calcinator Journeyman's"},
{ID="apparatus_m_calcinator_01", name="Calcinator Master's"},
{ID="apparatus_g_calcinator_01", name="Calcinator Master's Grand"},
{ID="apparatus_sm_calcinator_01", name="Calcinator Master's Secret"},
{ID="apparatus_a_mortar_01", name="Mortar/Pestle Apprentice's"},
{ID="apparatus_j_mortar_01", name="Mortar/Pestle Journeyman's"},
{ID="apparatus_m_mortar_01", name="Mortar/Pestle Master's"},
{ID="apparatus_g_mortar_01", name="Mortar/Pestle Master's Grand"},
{ID="apparatus_sm_mortar_01", name="Mortar/Pestle Master's Secret"},
{ID="apparatus_a_retort_01", name="Retort Apprentice's"},
{ID="apparatus_j_retort_01", name="Retort Journeyman's"},
{ID="apparatus_m_retort_01", name="Retort Master's"},
{ID="apparatus_g_retort_01", name="Retort Master's Grand"},
{ID="apparatus_sm_retort_01", name="Retort Master's Secret"},
}
