return {
{ID="BookSkill_Short Blade3", name="2920, Evening Star +22"},
{ID="BookSkill_Spear2", name="2920, First Seed +7"},
{ID="BookSkill_Conjuration4", name="2920, FrostFall +13"},
{ID="BookSkill_Conjuration3", name="2920, Hearth Fire +13"},
{ID="BookSkill_Sneak2", name="2920, Last Seed +19"},
{ID="BookSkill_Heavy Armor2", name="2920, MidYear +3"},
{ID="BookSkill_Long Blade2", name="2920, Morning Star +5"},
{ID="BookSkill_Restoration4", name="2920, Rain's Hand +15"},
{ID="BookSkill_Speechcraft3", name="2920, Second Seed +25"},
{ID="BookSkill_Mysticism2", name="2920, Sun's Dawn +14"},
{ID="BookSkill_Short Blade2", name="2920, Sun's Dusk +22"},
{ID="BookSkill_Mercantile3", name="2920, Sun's Height +24"},
{ID="BookSkill_Athletics3", name="36 Vivec Lessons, Sermon 01 +8"},
{ID="BookSkill_Short Blade4", name="36 Vivec Lessons, Sermon 10 +22"},
{ID="bookskill_unarmored3", name="36 Vivec Lessons, Sermon 11 +17"},
{ID="bookskill_heavy armor5", name="36 Vivec Lessons, Sermon 12 +3"},
{ID="BookSkill_Alteration4", name="36 Vivec Lessons, Sermon 13 +11"},
{ID="bookskill_spear3", name="36 Vivec Lessons, Sermon 14 +7"},
{ID="bookskill_unarmored4", name="36 Vivec Lessons, Sermon 15 +17"},
{ID="BookSkill_Axe5", name="36 Vivec Lessons, Sermon 16 +6"},
{ID="BookSkill_Axe5_open", name="36 Vivec Lessons, Sermon 16 +6"},
{ID="bookskill_long blade3", name="36 Vivec Lessons, Sermon 17 +5"},
{ID="BookSkill_Alchemy5", name="36 Vivec Lessons, Sermon 18 +16"},
{ID="bookskill_enchant4", name="36 Vivec Lessons, Sermon 19 +9"},
{ID="BookSkill_Alchemy4", name="36 Vivec Lessons, Sermon 02 +16"},
{ID="bookskill_long blade4", name="36 Vivec Lessons, Sermon 20 +5"},
{ID="bookskill_light armor4", name="36 Vivec Lessons, Sermon 21 +21"},
{ID="bookskill_medium armor4", name="36 Vivec Lessons, Sermon 22 +2"},
{ID="bookskill_long blade5", name="36 Vivec Lessons, Sermon 23 +5"},
{ID="bookskill_spear4", name="36 Vivec Lessons, Sermon 24 +7"},
{ID="BookSkill_Armorer4", name="36 Vivec Lessons, Sermon 25 +1"},
{ID="bookskill_sneak5", name="36 Vivec Lessons, Sermon 26 +19"},
{ID="bookskill_speechcraft5", name="36 Vivec Lessons, Sermon 27 +25"},
{ID="bookskill_light armor5", name="36 Vivec Lessons, Sermon 28 +21"},
{ID="BookSkill_Armorer5", name="36 Vivec Lessons, Sermon 29 +1"},
{ID="BookSkill_Blunt Weapon4", name="36 Vivec Lessons, Sermon 03 +4"},
{ID="BookSkill_Short Blade5", name="36 Vivec Lessons, Sermon 30 +22"},
{ID="BookSkill_Athletics5", name="36 Vivec Lessons, Sermon 31 +8"},
{ID="BookSkill_Block5", name="36 Vivec Lessons, Sermon 32 +0"},
{ID="bookskill_medium armor5", name="36 Vivec Lessons, Sermon 33 +2"},
{ID="bookskill_unarmored5", name="36 Vivec Lessons, Sermon 34 +17"},
{ID="bookskill_spear5", name="36 Vivec Lessons, Sermon 35 +7"},
{ID="BookSkill_Mysticism4", name="36 Vivec Lessons, Sermon 36 +14"},
{ID="BookSkill_Mysticism3", name="36 Vivec Lessons, Sermon 04 +14"},
{ID="BookSkill_Axe4", name="36 Vivec Lessons, Sermon 05 +6"},
{ID="BookSkill_Armorer3", name="36 Vivec Lessons, Sermon 06 +1"},
{ID="BookSkill_Block4", name="36 Vivec Lessons, Sermon 07 +0"},
{ID="BookSkill_Athletics4", name="36 Vivec Lessons, Sermon 08 +8"},
{ID="BookSkill_Blunt Weapon5", name="36 Vivec Lessons, Sermon 09 +4"},
{ID="BookSkill_Acrobatics2", name="A Dance in Fire, Chapter 1 +20"},
{ID="BookSkill_Block3", name="A Dance in Fire, Chapter 2 +0"},
{ID="BookSkill_Athletics2", name="A Dance in Fire, Chapter 3 +8"},
{ID="BookSkill_Acrobatics3", name="A Dance in Fire, Chapter 4 +20"},
{ID="BookSkill_Marksman2", name="A Dance in Fire, Chapter 5 +23"},
{ID="bookskill_mercantile4", name="A Dance in Fire, Chapter 6 +24"},
{ID="bookskill_mercantile5", name="A Dance in Fire, Chapter 7 +24"},
{ID="BookSkill_Alchemy1", name="A Game at Dinner +16"},
{ID="bookskill_destruction3", name="A Hypothetical Treachery +10"},
{ID="BookSkill_Sneak3", name="Azura and the Box +19"},
{ID="BookSkill_Speechcraft1", name="Biography of the Wolf Queen +25"},
{ID="sc_fjellnote", name="Bloody Note +18"},
{ID="BookSkill_Medium Armor2", name="Bone, Part One +2"},
{ID="BookSkill_Medium Armor3", name="Bone, Part Two +2"},
{ID="BookSkill_Alteration1", name="Breathing Water +11"},
{ID="bookskill_security4", name="Chance's Folly +18"},
{ID="bookskill_unarmored2", name="Charwich-Koniinge, Volume 1 +17"},
{ID="bookskill_hand to hand3", name="Charwich-Koniinge, Volume 2 +26"},
{ID="BookSkill_Mysticism5", name="Charwich-Koniinge, Volume 3 +14"},
{ID="bookskill_hand to hand4", name="Charwich-Koniinge, Volume 4 +26"},
{ID="bookskill_medium armor1", name="Cherim's Heart of Anequina +2"},
{ID="BookSkill_Heavy Armor3", name="Chimarvamidium +3"},
{ID="BookSkill_Block1", name="Death Blow of Abernanit +0"},
{ID="BookSkill_Enchant1", name="Feyfolken I +9"},
{ID="BookSkill_Conjuration1", name="Feyfolken II +13"},
{ID="BookSkill_Conjuration2", name="Feyfolken III +13"},
{ID="bookskill_heavy armor1", name="Hallgerd's Tale +3"},
{ID="bookskill_heavy armor4", name="How Orsinium Passed to Orcs +3"},
{ID="BookSkill_Light Armor2", name="Ice and Chiton +21"},
{ID="bookskill_illusion3", name="Incident in Necrom +12"},
{ID="BookSkill_Armorer2", name="Last Scabbard of Akrash +1"},
{ID="bookskill_light armor3", name="Lord Jornibret's Last Dance +21"},
{ID="bookskill_hand to hand5", name="Master Zoaraym's Tale +26"},
{ID="BookSkill_Acrobatics5", name="Mystery of Talara, Part 1 +20"},
{ID="BookSkill_Restoration5", name="Mystery of Talara, Part 2 +15"},
{ID="BookSkill_Destruction5", name="Mystery of Talara, Part 3 +10"},
{ID="BookSkill_Destruction5_open", name="Mystery of Talara, Part 3 +10"},
{ID="bookskill_illusion5", name="Mystery of Talara, Part 4 +12"},
{ID="bookskill_blunt weapon3", name="Night Falls On Sentinel +4"},
{ID="bookskill_restoration2", name="Notes on Racial Phylogeny +15"},
{ID="bookskill_illusion4", name="Palla, Book I +12"},
{ID="bookskill_enchant3", name="Palla, Book II +9"},
{ID="bookskill_acrobatics1", name="Realizations of Acrobacy +20"},
{ID="bookskill_destruction2", name="Response to Bero's Speech +10"},
{ID="bookskill_illusion2", name="Silence +12"},
{ID="BookSkill_Alteration3", name="Sithis +11"},
{ID="bookskill_spear1", name="Smuggler's Island +7"},
{ID="BookSkill_Alchemy3", name="Song of the Alchemists +16"},
{ID="bookskill_security5", name="Surfeit of Thieves +18"},
{ID="sc_sjobalnote", name="Thauraver's Orders +18"},
{ID="BookSkill_Armorer1", name="The Armorer's Challenge +1"},
{ID="bookskill_destruction4", name="The Art of War Magic +10"},
{ID="bookskill_axe2", name="The Axe Man +6"},
{ID="BookSkill_Acrobatics4", name="The Black Arrow, Volume I +20"},
{ID="bookskill_marksman5", name="The Black Arrow, Volume II +23"},
{ID="bookskill_mercantile1", name="The Buying Game +24"},
{ID="BookSkill_Alchemy2", name="The Cake and the Diamond +16"},
{ID="BookSkill_Security3", name="The Dowry +18"},
{ID="BookSkill_Alteration2", name="The Dragon Break ReExamined +11"},
{ID="bookskill_enchant5", name="The Final Lesson +9"},
{ID="bookskill_mysticism1", name="The Firsthold Revolt +14"},
{ID="bookskill_restoration3", name="The Four Suitors of Benitah +15"},
{ID="bookskill_marksman1", name="The Gold Ribbon of Merit +23"},
{ID="bookskill_blunt weapon1", name="The Hope of the Redoran +4"},
{ID="bookskill_destruction1", name="The Horror of Castle Xyr +10"},
{ID="BookSkill_Blunt Weapon2", name="The Importance of Where +4"},
{ID="bookskill_security1", name="The Locked Room +18"},
{ID="BookSkill_Alteration5", name="The Lunar Lorkhan +11"},
{ID="bookskill_marksman4", name="The Marksmanship Lesson +23"},
{ID="bookskill_block2", name="The Mirror +0"},
{ID="bookskill_hand to hand1", name="The Prayers of Baranat +26"},
{ID="BookSkill_Athletics1", name="The Ransom of Zarek +8"},
{ID="BookSkill_Light Armor1", name="The Rear Guard +21"},
{ID="BookSkill_Axe3", name="The Seed +6"},
{ID="sc_GrandfatherFrost", name="Grandfather Frost's Song +16"},
{ID="sc_unclesweetshare", name="Uncle Sweetshare's Song +16"},
{ID="BookSkill_Axe1", name="The Third Door +6"},
{ID="bookskill_conjuration5", name="The Warrior's Charge +13"},
{ID="bookskill_security2", name="The Wolf Queen, Book I +18"},
{ID="bookskill_hand to hand2", name="The Wolf Queen, Book II +26"},
{ID="bookskill_illusion1", name="The Wolf Queen, Book III +12"},
{ID="bookskill_mercantile2", name="The Wolf Queen, Book IV +24"},
{ID="bookskill_speechcraft2", name="The Wolf Queen, Book V +25"},
{ID="bookskill_sneak1", name="The Wolf Queen, Book VI +19"},
{ID="bookskill_speechcraft4", name="The Wolf Queen, Book VII +25"},
{ID="BookSkill_Enchant2", name="The Wolf Queen, Book VIII +9"},
{ID="bookskill_unarmored1", name="The Wraith's Wedding Dowry +17"},
{ID="bookskill_sneak4", name="Trap +19"},
{ID="bookskill_short blade1", name="Unnamed Book +22"},
{ID="bookskill_marksman3", name="Vernaccus and Bourlor +23"},
{ID="bookskill_restoration1", name="Withershins +15"},
{ID="BookSkill_Long Blade1", name="Words and Philosophy +5"},
}
