return {
{ID="steel mace", name="Blunt Mace Steel"},
{ID="steel dagger", name="Short Dagger Steel"},
{ID="spiked club", name="Blunt Club Spiked"},
{ID="steel broadsword", name="Sword Broad Steel"},
{ID="steel shortsword", name="Short Sword Steel"},
{ID="imperial shortsword", name="Short Sword Imperial"},
{ID="steel spear", name="Spear Steel"},
{ID="steel tanto", name="Short Tanto Steel"},
{ID="imperial broadsword", name="Sword Broad Imperial"},
{ID="iron longsword", name="Sword Long Iron"},
{ID="iron shortsword", name="Short Sword Iron"},
{ID="nordic claymore", name="Claymore Nordic"},
{ID="steel dai-katana", name="TwoHanded Dai-Katana Steel"},
{ID="iron claymore", name="Claymore Iron"},
{ID="silver longsword", name="Sword Long Silver"},
{ID="ebony shortsword", name="Short Sword Ebony"},
{ID="ebony longsword", name="Sword Long Ebony"},
{ID="silver shortsword", name="Short Sword Silver"},
{ID="daedric longsword", name="Sword Long Daedric"},
{ID="nordic battle axe", name="Battle Axe Nordic"},
{ID="steel axe", name="Axe War Steel"},
{ID="iron battle axe", name="Battle Axe Iron"},
{ID="steel claymore", name="Claymore Steel"},
{ID="steel katana", name="Sword Katana Steel"},
{ID="steel saber", name="Sword Saber Steel"},
{ID="steel wakizashi", name="Short Wakizashi Steel"},
{ID="long bow", name="Bow Long"},
{ID="iron arrow", name="Arrow Iron"},
{ID="steel staff", name="Staff Steel"},
{ID="steel war axe", name="Axe War Steel"},
{ID="steel longsword", name="Sword Long Steel"},
{ID="steel club", name="Blunt Club Steel"},
{ID="steel battle axe", name="Battle Axe Steel"},
{ID="steel warhammer", name="Warhammer Steel"},
{ID="steel halberd", name="Spear Halberd Steel"},
{ID="steel crossbow", name="Crossbow Steel"},
{ID="steel throwing star", name="Thrown Star Steel"},
{ID="steel throwing knife", name="Thrown Knife Steel"},
{ID="steel dart", name="Thrown Dart Steel"},
{ID="chitin dagger", name="Short Dagger Chitin"},
{ID="chitin shortsword", name="Short Sword Chitin"},
{ID="chitin club", name="Blunt Club Chitin"},
{ID="chitin war axe", name="Axe War Chitin"},
{ID="chitin spear", name="Spear Chitin"},
{ID="chitin short bow", name="Bow Short Chitin"},
{ID="chitin throwing star", name="Thrown Star Chitin"},
{ID="iron dagger", name="Short Dagger Iron"},
{ID="iron tanto", name="Short Tanto Iron"},
{ID="iron wakizashi", name="Short Wakizashi Iron"},
{ID="iron broadsword", name="Sword Broad Iron"},
{ID="iron saber", name="Sword Saber Iron"},
{ID="iron club", name="Blunt Club Iron"},
{ID="iron mace", name="Blunt Mace Iron"},
{ID="iron warhammer", name="Warhammer Iron"},
{ID="iron war axe", name="Axe War Iron"},
{ID="iron spear", name="Spear Iron"},
{ID="iron halberd", name="Spear Halberd Iron"},
{ID="daedric battle axe", name="Battle Axe Daedric"},
{ID="daedric claymore", name="Claymore Daedric"},
{ID="daedric club", name="Blunt Club Daedric"},
{ID="daedric dagger", name="Short Dagger Daedric"},
{ID="daedric dai-katana", name="TwoHanded Dai-Katana Daedric"},
{ID="daedric dart", name="Thrown Dart Daedric"},
{ID="daedric katana", name="Sword Katana Daedric"},
{ID="daedric long bow", name="Bow Long Daedric"},
{ID="daedric mace", name="Blunt Mace Daedric"},
{ID="daedric shortsword", name="Short Sword Daedric"},
{ID="daedric spear", name="Spear Daedric"},
{ID="daedric staff", name="Staff Daedric"},
{ID="daedric tanto", name="Short Tanto Daedric"},
{ID="daedric wakizashi", name="Short Wakizashi Daedric"},
{ID="daedric war axe", name="Axe War Daedric"},
{ID="daedric warhammer", name="Warhammer Daedric"},
{ID="dreugh club", name="Blunt Club Dreugh"},
{ID="dreugh staff", name="Staff Dreugh"},
{ID="dwarven battle axe", name="Battle Axe Dwarven"},
{ID="dwarven claymore", name="Claymore Dwarven"},
{ID="dwarven crossbow", name="Crossbow Dwarven"},
{ID="dwarven halberd", name="Spear Halberd Dwarven"},
{ID="dwarven mace", name="Blunt Mace Dwarven"},
{ID="dwarven shortsword", name="Short Sword Dwarven"},
{ID="dwarven spear", name="Spear Dwarven"},
{ID="dwarven war axe", name="Axe War Dwarven"},
{ID="dwarven warhammer", name="Warhammer Dwarven"},
{ID="ebony broadsword", name="Sword Broad Ebony"},
{ID="ebony dart", name="Thrown Dart Ebony"},
{ID="ebony mace", name="Blunt Mace Ebony"},
{ID="ebony spear", name="Spear Ebony"},
{ID="ebony staff", name="Staff Ebony"},
{ID="ebony throwing star", name="Thrown Star Ebony"},
{ID="ebony war axe", name="Axe War Ebony"},
{ID="glass claymore", name="Claymore Glass"},
{ID="glass dagger", name="Short Dagger Glass"},
{ID="glass halberd", name="Spear Halberd Glass"},
{ID="glass longsword", name="Sword Long Glass"},
{ID="glass staff", name="Staff Glass"},
{ID="glass throwing knife", name="Thrown Knife Glass"},
{ID="glass throwing star", name="Thrown Star Glass"},
{ID="glass war axe", name="Axe War Glass"},
{ID="iron throwing knife", name="Thrown Knife Iron"},
{ID="short bow", name="Bow Short"},
{ID="silver claymore", name="Claymore Silver"},
{ID="silver dagger", name="Short Dagger Silver"},
{ID="silver dart", name="Thrown Dart Silver"},
{ID="silver spear", name="Spear Silver"},
{ID="silver staff", name="Staff Silver"},
{ID="silver throwing star", name="Thrown Star Silver"},
{ID="silver war axe", name="Axe War Silver"},
{ID="wooden staff", name="Staff Wooden"},
{ID="nordic broadsword", name="Sword Broad Nordic"},
{ID="Iron Long Spear", name="Spear Iron Long"},
{ID="lugrub's axe", name="Axe Lugrub's"},
{ID="steel blade of heaven", name="Short Blade of Heaven Steel"},
{ID="ebony wizard's staff", name="Staff Wizard's"},
{ID="steel jinkblade of the aegis", name="Short Jinkblade Steel of Aegis"},
{ID="fiend tanto", name="Short Tanto Fiend"},
{ID="bonemold arrow", name="Arrow Bonemold"},
{ID="dire viperarrow", name="Arrow of Dire Viper"},
{ID="6th bell hammer", name="Warhammer 6th House Bell Hammer"},
{ID="dwarven war axe_redas", name="Axe War Redas"},
{ID="bonemold long bow", name="Bow Long Bonemold"},
{ID="clutterbane", name="Blunt Clutterbane"},
{ID="water spear", name="Spear of Water"},
{ID="fireblade", name="Short Fireblade"},
{ID="icebreaker", name="Blunt Icebreaker"},
{ID="stormblade", name="Sword Long Iron of Storm"},
{ID="spiderbite", name="Sword Long of Spiderbite"},
{ID="flamestar", name="Thrown Star of Flame"},
{ID="shardstar", name="Thrown Star of Shard"},
{ID="viperstar", name="Thrown Star of Viper"},
{ID="demon tanto", name="Short Tanto Demon"},
{ID="corkbulb arrow", name="Arrow Corkbulb"},
{ID="chitin arrow", name="Arrow Chitin"},
{ID="silver arrow", name="Arrow Silver"},
{ID="glass arrow", name="Arrow Glass"},
{ID="ebony arrow", name="Arrow Ebony"},
{ID="daedric arrow", name="Arrow Daedric"},
{ID="corkbulb bolt", name="Bolt Corkbulb"},
{ID="iron bolt", name="Bolt Iron"},
{ID="steel bolt", name="Bolt Steel"},
{ID="silver bolt", name="Bolt Silver"},
{ID="bonemold bolt", name="Bolt Bonemold"},
{ID="orcish bolt", name="Bolt Orcish"},
{ID="flame_bolt", name="Bolt of Flame"},
{ID="shard_bolt", name="Bolt of Shard"},
{ID="spark_bolt", name="Bolt of Spark"},
{ID="viper_bolt", name="Bolt of Viper"},
{ID="flame arrow", name="Arrow of Flame"},
{ID="shard arrow", name="Arrow of Shard"},
{ID="spark arrow", name="Arrow of Spark"},
{ID="viper arrow", name="Arrow of Viper"},
{ID="steel arrow", name="Arrow Steel"},
{ID="grey shaft of holding", name="Arrow Grey Shaft of Holding"},
{ID="grey shaft of nonsense", name="Arrow Grey Shaft of Nonsense"},
{ID="grey shaft of unraveling", name="Arrow Grey Shaft of Unraveling"},
{ID="demon katana", name="Sword Katana Demon"},
{ID="steel longbow", name="Bow Long Steel"},
{ID="demon longbow", name="Bow Long Demon"},
{ID="peacemaker", name="Staff Peacemaker"},
{ID="cruel flameblade", name="Short Blade of Cruel Flame"},
{ID="cruel shardblade", name="Short Blade of Cruel Shard"},
{ID="cruel sparkblade", name="Short Blade of Cruel Spark"},
{ID="cruel viperblade", name="Short Blade of Cruel Viper"},
{ID="cruel flamesword", name="Short Sword of Cruel Flame"},
{ID="cruel shardsword", name="Short Sword of Cruel Shard"},
{ID="cruel sparksword", name="Short Sword of Cruel Spark"},
{ID="cruel vipersword", name="Short Sword of Cruel Viper"},
{ID="steel jinkblade", name="Short Jinkblade Steel"},
{ID="steel jinksword", name="Short Jinksword Steel"},
{ID="steel firesword", name="Sword Long Steel of Fire"},
{ID="steel frostsword", name="Sword Long Steel of Frost"},
{ID="steel stormsword", name="Sword Long Silver of Storm"},
{ID="steel poisonsword", name="Sword Long Steel of PoisonBloom"},
{ID="iron flameblade", name="Short Blade Iron of Flame"},
{ID="iron shardblade", name="Short Blade Iron of Shard"},
{ID="iron sparkblade", name="Short Blade Iron of Spark"},
{ID="iron viperblade", name="Short Blade Iron of Viper"},
{ID="iron flamecleaver", name="Spear Halberd Iron of Flame"},
{ID="iron shardcleaver", name="Spear Halberd Iron of Shard"},
{ID="iron sparkcleaver", name="Spear Halberd Iron of Spark"},
{ID="iron vipercleaver", name="Spear Halberd Iron of Viper"},
{ID="iron flamesword", name="Sword Long Iron of Flame"},
{ID="iron sparksword", name="Sword Long Iron of Spark"},
{ID="iron shardsword", name="Sword Long Iron of Shard"},
{ID="iron vipersword", name="Sword Long Iron of Viper"},
{ID="iron flamemace", name="Blunt Mace Iron of Flame"},
{ID="iron shardmace", name="Blunt Mace Iron of Shard"},
{ID="iron sparkmace", name="Blunt Mace Iron of Spark"},
{ID="iron sparkaxe", name="Axe War Iron of Spark"},
{ID="iron viperaxe", name="Axe War Iron of Viper"},
{ID="iron flameslayer", name="Claymore Iron of Flame"},
{ID="iron shardslayer", name="Claymore Iron of Shard"},
{ID="iron sparkslayer", name="Claymore Iron of Spark"},
{ID="iron viperslayer", name="Claymore Iron of Viper"},
{ID="iron flameskewer", name="Spear Iron of Flame"},
{ID="iron shardskewer", name="Spear Iron of Shard"},
{ID="iron sparkskewer", name="Spear Iron of Spark"},
{ID="iron viperskewer", name="Spear Iron of Viper"},
{ID="iron flamemauler", name="War Maul Iron of Flame"},
{ID="iron sparkmauler", name="War Maul Iron of Spark"},
{ID="iron shardmauler", name="War Maul Iron of Shard"},
{ID="iron vipermauler", name="War Maul Iron of Viper"},
{ID="wooden staff of peace", name="Staff Wooden of Peace"},
{ID="wooden staff of war", name="Staff Wooden of War"},
{ID="wooden staff of shaming", name="Staff Wooden of Shaming"},
{ID="wooden staff of chastening", name="Staff Wooden of Chastening"},
{ID="wooden staff of divine", name="Staff Wooden of Judgment"},
{ID="firebite sword", name="Short Sword of Firebite"},
{ID="firebite star", name="Thrown Star of Firebite"},
{ID="firebite war axe", name="Axe War of Firebite"},
{ID="firebite dagger", name="Short Dagger of Firebite"},
{ID="firebite club", name="Blunt Club of Firebite"},
{ID="shockbite mace", name="Blunt Mace of Shockbite"},
{ID="shockbite halberd", name="Spear Halberd of Shockbite"},
{ID="shockbite battle axe", name="Battle Axe Steel of Shockbite"},
{ID="shockbite war axe", name="Axe War of Shockbite"},
{ID="shockbite warhammer", name="Warhammer of Shockbite"},
{ID="last wish", name="Short Last Wish"},
{ID="foeburner", name="TwoHanded Foeburner"},
{ID="snowy crown", name="Blunt Snowy Crown"},
{ID="last rites", name="Battle Axe Last Rites"},
{ID="cruel flame bolt", name="Bolt of Cruel Flame"},
{ID="cruel shard bolt", name="Bolt of Cruel Shard"},
{ID="cruel spark bolt", name="Bolt of Cruel Spark"},
{ID="cruel viper bolt", name="Bolt of Cruel Viper"},
{ID="cruel flamearrow", name="Arrow of Cruel Flame"},
{ID="cruel shardarrow", name="Arrow of Cruel Shard"},
{ID="cruel sparkarrow", name="Arrow of Cruel Spark"},
{ID="cruel viperarrow", name="Arrow of Cruel Viper"},
{ID="cruel flamestar", name="Thrown Star of Cruel Flame"},
{ID="cruel sparkstar", name="Thrown Star of Cruel Spark"},
{ID="cruel shardstar", name="Thrown Star of Cruel Shard"},
{ID="cruel viperstar", name="Thrown Star of Cruel Viper"},
{ID="dire flameblade", name="Short Blade of Dire Flame"},
{ID="dire shardblade", name="Short Blade of Dire Shard"},
{ID="dire sparkblade", name="Short Blade of Dire Spark"},
{ID="dire viperblade", name="Short Blade of Dire Viper"},
{ID="dire flamesword", name="Short Sword of Dire Flame"},
{ID="dire shardsword", name="Short Sword of Dire Shard"},
{ID="dire sparksword", name="Short Sword of Dire Spark"},
{ID="dire vipersword", name="Short Sword of Dire Viper"},
{ID="orcish warhammer", name="Warhammer Orcish"},
{ID="orcish battle axe", name="Battle Axe Orcish"},
{ID="steel flameblade", name="Short Blade Steel of Flame"},
{ID="steel shardblade", name="Short Blade Steel of Shard"},
{ID="steel sparkblade", name="Short Blade Steel of Spark"},
{ID="steel viperblade", name="Short Blade Steel of Viper"},
{ID="steel flamesword", name="Sword Long Steel of Flame"},
{ID="steel shardsword", name="Sword Long Steel of Shard"},
{ID="steel sparksword", name="Sword Long Steel of Spark"},
{ID="steel vipersword", name="Sword Long Steel of Viper"},
{ID="steel flamemace", name="Blunt Mace Steel of Flame"},
{ID="steel shardmace", name="Blunt Mace Steel of Shard"},
{ID="steel sparkmace", name="Blunt Mace Steel of Spark"},
{ID="steel vipermace", name="Blunt Mace Steel of Viper"},
{ID="steel flameaxe", name="Axe War Steel of Flame"},
{ID="steel sparkaxe", name="Axe War Steel of Spark"},
{ID="steel shardaxe", name="Axe War Steel of Shard"},
{ID="steel viperaxe", name="Axe War Steel of Viper"},
{ID="steel flameslayer", name="Claymore Steel of Flame"},
{ID="steel shardslayer", name="Claymore Steel of Shard"},
{ID="steel sparkslayer", name="Claymore Steel of Spark"},
{ID="steel viperslayer", name="Claymore Steel of Viper"},
{ID="steel flamescythe", name="Scythe Steel of Cruel Flame"},
{ID="steel shardscythe", name="Scythe Steel of Cruel Shard"},
{ID="steel sparkscythe", name="Scythe Steel of Cruel Spark"},
{ID="steel viperscythe", name="Scythe Steel of Cruel Viper"},
{ID="steel flamecleaver", name="Spear Halberd Steel of Flame"},
{ID="steel shardcleaver", name="Spear Halberd Steel of Shard"},
{ID="steel sparkcleaver", name="Spear Halberd Steel of Spark"},
{ID="steel vipercleaver", name="Spear Halberd Steel of Viper"},
{ID="steel flameskewer", name="Spear Steel of Flame"},
{ID="steel shardskewer", name="Spear Steel of Shard"},
{ID="steel sparkskewer", name="Spear Steel of Spark"},
{ID="steel viperskewer", name="Spear Steel of Viper"},
{ID="steel flamemauler", name="War Maul Steel of Flame"},
{ID="steel shardmauler", name="War Maul Steel of Shard"},
{ID="steel sparkmauler", name="War Maul Steel of Spark"},
{ID="steel vipermauler", name="War Maul Steel of Viper"},
{ID="flying viper", name="Thrown Flying Viper"},
{ID="steel staff of peace", name="Staff Steel of Peace"},
{ID="steel staff of war", name="Staff Steel of War"},
{ID="steel staff of shaming", name="Staff Steel of Shaming"},
{ID="steel staff of chastening", name="Staff Steel of Chastening"},
{ID="steel staff of divine judgement", name="Staff Steel of Divine Judgment"},
{ID="steel staff of the ancestors", name="Staff Steel of the Ancestors"},
{ID="war axe of wounds", name="Axe War of Wounds"},
{ID="silver staff of reckoning", name="Staff of Reckoning Silver"},
{ID="dire flame bolt", name="Bolt of Dire Flame"},
{ID="dire shard bolt", name="Bolt of Dire Shard"},
{ID="dire spark bolt", name="Bolt of Dire Spark"},
{ID="dire viper bolt", name="Bolt of Dire Viper"},
{ID="dire flamearrow", name="Arrow of Dire Flame"},
{ID="dire shardarrow", name="Arrow of Dire Shard"},
{ID="dire sparkarrow", name="Arrow of Dire Spark"},
{ID="wild flameblade", name="Short Blade of Wild Flame"},
{ID="wild shardblade", name="Short Blade of Wild Shard"},
{ID="wild sparkblade", name="Short Blade of Wild Spark"},
{ID="wild viperblade", name="Short Blade of Wild Viper"},
{ID="wild flamesword", name="Short Sword of Wild Flame"},
{ID="wild shardsword", name="Short Sword of Wild Shard"},
{ID="wild sparksword", name="Short Sword of Wild Spark"},
{ID="wild vipersword", name="Short Sword of Wild Viper"},
{ID="glass jinkblade", name="Short Jinkblade Glass"},
{ID="dwemer jinksword", name="Short Jinksword Dwemer"},
{ID="glass firesword", name="Sword Long Glass of Fire"},
{ID="glass frostsword", name="Sword Long Glass of Frost"},
{ID="glass stormsword", name="Sword Long Glass of Storm"},
{ID="glass poisonsword", name="Sword Long Glass of Poison"},
{ID="silver flameblade", name="Short Blade Silver of Flame"},
{ID="silver shardblade", name="Short Blade Silver of Shard"},
{ID="silver sparkblade", name="Short Blade Silver of Spark"},
{ID="silver viperblade", name="Short Blade Silver of Viper"},
{ID="silver flamesword", name="Sword Long Silver of Flame"},
{ID="silver shardsword", name="Sword Long Silver of Shard"},
{ID="silver sparksword", name="Sword Long Silver of Spark"},
{ID="silver vipersword", name="Sword Long Silver of Viper"},
{ID="silver flameaxe", name="Axe War Silver of Flame"},
{ID="silver sparkaxe", name="Axe War Silver of Spark"},
{ID="silver shardaxe", name="Axe War Silver of Shard"},
{ID="silver viperaxe", name="Axe War Silver of Viper"},
{ID="silver flameslayer", name="Claymore Silver of Flame"},
{ID="silver shardslayer", name="Claymore Silver of Shard"},
{ID="silver sparkslayer", name="Claymore Silver of Spark"},
{ID="silver viperslayer", name="Claymore Silver of Viper"},
{ID="silver flameskewer", name="Spear Silver of Flame"},
{ID="silver shardskewer", name="Spear Silver of Shard"},
{ID="silver sparkskewer", name="Spear Silver of Spark"},
{ID="silver viperskewer", name="Spear Silver of Viper"},
{ID="silver staff of peace", name="Staff Silver of Peace"},
{ID="steel warhammer of smiting", name="Warhammer Steel of Smiting"},
{ID="steel broadsword of hewing", name="Sword Broad Steel of Hewing"},
{ID="steel claymore of hewing", name="Claymore of Hewing Steel"},
{ID="steel war axe of deep biting", name="Axe War of Deep Biting Steel"},
{ID="steel spear of impaling thrust", name="Spear Steel of Impaling Thrust"},
{ID="steel dagger of swiftblade", name="Short Dagger Steel Swiftblade"},
{ID="shortbow of sanguine sureflight", name="Bow Short Sanguine Sureflight"},
{ID="throwing knife of sureflight", name="Thrown Knife of Sureflight"},
{ID="gavel of the ordinator", name="Blunt Gavel of the Ordinator"},
{ID="light staff", name="Staff of Light"},
{ID="merisan club", name="Blunt Club Merisan"},
{ID="spirit-eater", name="Sword Spirit-Eater"},
{ID="daunting mace", name="Blunt Sword of White Woe"},
{ID="mephala's teacher", name="Blunt Mephala's Teacher"},
{ID="fiend katana", name="Sword Katana Fiend"},
{ID="fiend battle axe", name="Battle Axe Fiend"},
{ID="fiend spear", name="Spear Fiend"},
{ID="fiend longbow", name="Bow Long Fiend"},
{ID="silver staff of war", name="Staff Silver of War"},
{ID="divine judgement silver staff", name="Staff Silver of Divine Judgment"},
{ID="silver staff of chastening", name="Staff Silver of Chastening"},
{ID="silver staff of shaming", name="Staff Silver of Shaming"},
{ID="devil tanto", name="Short Tanto Devil"},
{ID="devil katana", name="Sword Katana Devil"},
{ID="devil spear", name="Spear Devil"},
{ID="devil longbow", name="Bow Long Devil"},
{ID="saint's black sword", name="Short Saint's Black Sword"},
{ID="daedric wakizashi_hhst", name="Short Wakizashi Daedric"},
{ID="demon mace", name="Blunt Mace Demon"},
{ID="chargen dagger", name="Short Dagger Iron"},
{ID="ebony staff caper", name="Staff Ebony Felen's"},
{ID="war_axe_airan_ammu", name="Axe War of Airan Ammu"},
{ID="keening", name="Short Keening"},
{ID="cruel frostarrow", name="Arrow of Cruel Frost"},
{ID="dire frostarrow", name="Arrow of Dire Frost"},
{ID="steelstaffancestors_ttsa", name="Staff of Ancestral Wisdom"},
{ID="cleaverstfelms", name="Axe Cleaver of St. Felms"},
{ID="crosierstllothis", name="Staff Crosier of St. Llothis"},
{ID="ebony_bow_auriel", name="Bow Auriel's"},
{ID="dwarven_hammer_volendrung", name="Warhammer Volendrung"},
{ID="devil_tanto_tgamg", name="Short Tanto Devil Anarenen's"},
{ID="ebony_dagger_mehrunes", name="Short Sword Ebony"},
{ID="ebony_staff_tges", name="Staff Maryon's"},
{ID="daedric dagger_mtas", name="Short Dagger Black Hands"},
{ID="iron_arrow_uniq_judgement", name="Arrow Dart of Judgment"},
{ID="daedric_club_tgdc", name="Blunt Club Anora's"},
{ID="glass_dagger_enamor", name="Short Enamor"},
{ID="sparkstar", name="Thrown Star of Spark"},
{ID="daedric_scourge_unique", name="Blunt Scourge"},
{ID="claymore_chrysamere_unique", name="TwoHanded Chrysamere"},
{ID="claymore_iceblade_unique", name="TwoHanded Monarch's Ice Blade"},
{ID="warhammer_crusher_unique", name="Blunt Skull Crusher"},
{ID="katana_goldbrand_unique", name="Sword Goldbrand"},
{ID="dagger_fang_unique", name="Short Fang of Haynekhtnamet"},
{ID="longsword_umbra_unique", name="TwoHanded Umbra Sword"},
{ID="dagoth dagger", name="Short Dagger Dagoth"},
{ID="mehrunes'_razor_unique", name="Short Mehrunes' Razor"},
{ID="mace of molag bal_unique", name="Blunt Mace of Molag Bal"},
{ID="erur_dan_spear_unique", name="Spear Erur-Dan's"},
{ID="ane_teria_mace_unique", name="Blunt Mace Ane Teria's"},
{ID="conoon_chodala_axe_unique", name="Axe Conoon Chodala's"},
{ID="Rusty_Dagger_UNIQUE", name="Short Dagger Rusty"},
{ID="fork_horripilation_unique", name="Short Fork of Horripilation"},
{ID="widowmaker_unique", name="Battle Axe Widowmaker"},
{ID="bonebiter_bow_unique", name="Bow Bonebiter of Sul-Senipul"},
{ID="herder_crook", name="Staff Herder's Crook"},
{ID="iron fork", name="Short Fork Iron"},
{ID="cloudcleaver_unique", name="Battle Axe Cloudcleaver"},
{ID="we_hellfirestaff", name="Staff Hellfire"},
{ID="we_stormforge", name="Spear Stormforge"},
{ID="we_temreki", name="TwoHanded Temreki Soul Shackler"},
{ID="Dagger of Judgement", name="Short Dagger of Judgment"},
{ID="we_illkurok", name="Spear Illkurok"},
{ID="Silver Dagger_Hanin Cursed", name="Short Dagger Silver Ancient"},
{ID="ebony_staff_trebonius", name="Staff Trebonius'"},
{ID="Fury", name="TwoHanded Fury"},
{ID="Greed", name="Spear Greed"},
{ID="banhammer_unique", name="Warhammer BanHammer"},
{ID="racerbeak", name="Short Racerbeak"},
{ID="Wind of Ahaz", name="Axe Wind of Ahaz"},
{ID="Karpal's Friend", name="Axe Karpal's Friend"},
{ID="we_shimsil", name="Short Shimsil"},
{ID="iron spider dagger", name="Short Dagger Iron of Spider"},
{ID="steel spider blade", name="Short Sword Steel of Spider"},
{ID="imperial netch blade", name="Short Sword Imperial Netch"},
{ID="glass netch dagger", name="Short Dagger Glass Netch"},
{ID="claymore_Agustas", name="TwoHanded Sword of Agustas"},
{ID="ebony spear_hrce_unique", name="Spear Ebony"},
{ID="lightofday_unique", name="Blunt Light of Day"},
{ID="glass stormblade", name="Short Glass Stormblade"},
{ID="daedric_crescent_unique", name="TwoHanded Daedric Crescent"},
{ID="Airan_Ahhe's_Spirit_Spear_uniq", name="Spear Airan-Ahhe's Spirit"},
{ID="katana_bluebrand_unique", name="Sword Eltonbrand"},
{ID="glass dagger_Dae_cursed", name="Short Dagger Glass"},
{ID="glass claymore_magebane", name="TwoHanded Magebane"},
{ID="daedric warhammer_ttgd", name="Warhammer Veloth's Judgment"},
{ID="dart_uniq_judgement", name="Thrown Dart of Judgment"},
{ID="Stormkiss", name="Battle Axe Stormkiss"},
{ID="dwarven axe_soultrap", name="Battle Axe Dwemer Pneuma-Trap"},
{ID="silver staff of hunger", name="Staff Silver of Hunger"},
{ID="daedric dagger_soultrap", name="Short Soul Drinker"},
{ID="dwarven halberd_soultrap", name="Spear Bthuangth's Harvester"},
{ID="fiend spear_Dae_cursed", name="Spear Fiend"},
{ID="ebony broadsword_Dae_cursed", name="Sword Broad Ebony"},
{ID="iron shardaxe", name="Battle Axe Iron of Shard"},
{ID="iron dagger_telasero_unique", name="Short Dagger Iron"},
{ID="Gravedigger", name="TwoHanded Gravedigger"},
{ID="silver dagger_droth_unique", name="Short Dagger Droth"},
{ID="longsword_umbra_unique_x", name="TwoHanded Umbra Sword"},
{ID="dagger_fang_unique_x", name="Short Fang of Haynekhtnamet"},
{ID="ebony_bow_auriel_X", name="Bow Auriel's"},
{ID="daedric warhammer_ttgd_x", name="Warhammer Veloth's Judgment"},
{ID="mace of molag bal_unique_x", name="Blunt Mace of Molag Bal"},
{ID="katana_goldbrand_unique_x", name="Sword Goldbrand"},
{ID="claymore_iceblade_unique_x", name="TwoHanded Monarch's Ice Blade"},
{ID="claymore_chrysamere_unique_x", name="TwoHanded Chrysamere"},
{ID="warhammer_crusher_unique_x", name="Blunt Skull Crusher"},
{ID="ebony war axe_elanande", name="Axe War Elanande's"},
{ID="ebony shortsword_soscean", name="Short Sword Soscean's"},
{ID="silver spear_uvenim", name="Spear Silver of Fear"},
{ID="goblin_club", name="Blunt Club Goblin"},
{ID="Mace of Slurring", name="Blunt Mace of Slurring"},
{ID="Bipolar Blade", name="TwoHanded BiPolar Blade"},
{ID="Ebony Scimitar", name="Sword Scimitar Ebony"},
{ID="spite_dart", name="Thrown Dart of Spite"},
{ID="King's_Oath", name="TwoHanded King's Oath"},
{ID="King's_Oath_pc", name="TwoHanded King's Oath"},
{ID="dwarven mace_salandas", name="Blunt Mace Suldreni's"},
{ID="Bipolar Blade_x", name="TwoHanded BiPolar Blade"},
{ID="Mace of Slurring_x", name="Blunt Mace of Slurring"},
{ID="spring dart", name="Thrown Dart Spring"},
{ID="bleeder dart", name="Thrown Dart Bleeder"},
{ID="carmine dart", name="Thrown Dart Carmine"},
{ID="black dart", name="Thrown Dart Black"},
{ID="fine black dart", name="Thrown Dart Black Select"},
{ID="fine carmine dart", name="Thrown Dart Carmine Select"},
{ID="fine bleeder dart", name="Thrown Dart Bleeder Select"},
{ID="fine spring dart", name="Thrown Dart Spring Select"},
{ID="goblin_sword", name="Short Sword Goblin"},
{ID="centurion_projectile_dart", name="Thrown Dart Dwarven"},
{ID="adamantium_shortsword", name="Short Sword Adamantium"},
{ID="adamantium_claymore", name="Claymore Adamantium"},
{ID="adamantium_axe", name="Battle Axe Adamantium"},
{ID="adamantium_spear", name="Spear Adamantium"},
{ID="adamantium_mace", name="Blunt Mace Adamantium"},
{ID="nerevarblade_01", name="Sword Trueflame"},
{ID="Sword of Almalexia", name="Sword Hopesfire"},
{ID="ebony dart_db_unique", name="Thrown Dart Ebony Carved"},
{ID="ebony arrow_sadri", name="Arrow of Poison Grip"},
{ID="stendar_hammer_unique", name="Warhammer Stendarr's Hammer"},
{ID="stendar_hammer_unique_x", name="Warhammer Stendarr's Hammer"},
{ID="centurion_projectile_dart_shock", name="Thrown Dart Dwarven of Shock"},
{ID="nerevarblade_01_flame", name="Sword Trueflame"},
{ID="daedric dagger_bar", name="Short Dagger Daedric"},
{ID="adamantium_shortsword_db", name="Short Jinkblade of Wounds"},
{ID="silver dagger_othril_unique", name="Short Dagger Othril"},
{ID="silver dagger_iryon_unique", name="Short Dagger Iryon"},
{ID="silver dagger_rathalas_unique", name="Short Dagger Rathalas"},
{ID="ebony spear_blessed_unique", name="Spear Blessed"},
{ID="glass dagger_symmachus_unique", name="Short Dagger of Symmachus"},
{ID="glass dagger_symmachus_unique_x", name="Short Dagger of Symmachus"},
{ID="silver dagger_droth_unique_a", name="Short Dagger Droth"},
{ID="BM huntsman axe", name="Axe Huntsman's"},
{ID="BM huntsman longsword", name="Sword Long Huntsman's"},
{ID="BM Huntsman Spear", name="Spear Huntsman's"},
{ID="BM ice longsword", name="Sword Long Stalhrim"},
{ID="BM ice mace", name="Blunt Mace Stalhrim"},
{ID="BM ice dagger", name="Short Dagger Stalhrim"},
{ID="BM nordic silver axe", name="Axe Silver Nordic"},
{ID="BM nordic silver claymore", name="Claymore Silver Nordic"},
{ID="BM nordic silver battleaxe", name="Battle Axe Silver Nordic"},
{ID="BM nordic silver dagger", name="Short Dagger Silver Nordic"},
{ID="BM nordic silver longsword", name="Sword Long Silver Nordic"},
{ID="BM nordic silver mace", name="Blunt Mace Silver Nordic"},
{ID="BM nordic silver shortsword", name="Short Sword Silver Nordic"},
{ID="warhammer_rammekald_unique", name="Warhammer Rammekald"},
{ID="solvistapp", name="Sword Solvistapp"},
{ID="steel saber_elberoth", name="Sword Saber Elberoth's"},
{ID="BM huntsman crossbow", name="Crossbow Huntsman"},
{ID="BM ice war axe", name="Axe War Stalhrim"},
{ID="BM huntsman war axe", name="Axe War Huntsman's"},
{ID="BM Huntsmanbolt", name="Bolt Huntsman's"},
{ID="imperial shortsword severio", name="Short Sword Imperial Severia's"},
{ID="nordic claymore_stormfang", name="TwoHanded Stormfang"},
{ID="BM_arrow_riekling_uni", name="Arrow Chitin"},
{ID="BM silver dagger wolfender", name="Short Dagger Silver Wolfender"},
{ID="silver arrow_thirsk_1", name="Arrow Silver"},
{ID="silver arrow_thirsk_2", name="Arrow Silver"},
{ID="silver arrow_thirsk_3", name="Arrow Silver"},
{ID="silver arrow_thirsk_4", name="Arrow Silver"},
{ID="silver arrow_thirsk_5", name="Arrow Silver"},
{ID="silver arrow_thirsk_6", name="Arrow Silver"},
{ID="silver arrow_thirsk_7", name="Arrow Silver"},
{ID="silver arrow_thirsk_8", name="Arrow Silver"},
{ID="silver arrow_thirsk_9", name="Arrow Silver"},
{ID="silver arrow_thirsk_0", name="Arrow Silver"},
{ID="BM_hunter_battleaxe_unique", name="Battle Axe Silver Nordic"},
{ID="BM_nordic_silver_lgswd_bloodska", name="Sword Bloodskal"},
{ID="BM Nordic Pick", name="Axe Pick Nordic Ancient"},
{ID="BM_ice_minion_lance", name="Short Riekling Lance"},
{ID="BM_dagger_wolfgiver", name="Short Dagger Silver Wolfgiver"},
{ID="bm_saber_seasplitter", name="Sword Seasplitter"},
{ID="BM nordic_longsword_tracker", name="Sword Long Silver Tracker's"},
{ID="BM riekling lance", name="Short Riekling Lance"},
{ID="BM riekling sword", name="Sword Riekling Blade"},
{ID="steel arrow_Carnius", name="Arrow Poisoned"},
{ID="steel longbow_carnius", name="Bow Long Steel"},
{ID="silver axe of paralysis", name="Axe of Paralysis Silver"},
{ID="silver sword of paralysis", name="Sword Long Silver of Paralysis"},
{ID="silver staff of paralysis", name="Staff Silver of Paralysis"},
{ID="BM nordic silver claymore_ber", name="Claymore Silver Berserker's"},
{ID="BM nordic silver longsword_ber", name="Sword Long Silver Berserker's"},
{ID="BM nordic silver axe_ber", name="Axe War Silver Berserker's"},
{ID="BM nordic silver battleaxe_ber", name="Battle Axe Silver Berserker's"},
{ID="BM Winterwound Dagger", name="Short Dagger Winterwound"},
{ID="BM_axe_Heartfang_Unique", name="Battle Axe Silver Heartfang's"},
{ID="BM_Mace_Aevar_UNI", name="Blunt Mace Aevar Stone-Singer"},
{ID="BM ice longsword_FG_Unique", name="Sword Long Stalhrim of Flame"},
{ID="bm reaver battle axe", name="Battle Axe Blood Axe"},
{ID="BM nordic silver axe_spurius", name="Axe of Paralysis Nordic"},
{ID="BM nordic silver longsword_cft", name="Sword Clanbringer"},
{ID="Lucky_Break", name="Staff Haakon's Lucky Break"},
{ID="BM frostgore", name="Short Frostgore"},
{ID="bm_ebonyarrow_s", name="Arrow of Slaying Ebony"},
{ID="bm_ebonylongsword_s", name="Sword Shadowsting"},
{ID="BM riekling sword_rusted", name="Sword Riekling Blade Rusted"},
{ID="glass dagger_Dae_cursed_PfP", name="Short Dagger Glass"},
{ID="Silver Dagger_Hanin Cursed_PfP", name="Short Dagger Silver Ancient"},
{ID="cruel_shockbloom_arrow", name="Arrow of Cruel ShockBloom"},
{ID="cruel_firestorm_arrow", name="Arrow of Cruel FireStorm"},
{ID="cruel_poisonbloom_arrow", name="Arrow of Cruel PoisonBloom"},
{ID="cruel_frostbloom_arrow", name="Arrow of Cruel FrostBloom"},
{ID="cruel_shockbloom_star", name="Thrown Star Cruel ShockBloom"},
{ID="cruel_firestorm_star", name="Thrown Star Cruel FireStorm"},
{ID="cruel_frostbloom_star", name="Thrown Star Cruel FrostBloom"},
{ID="cruel_poisonbloom_star", name="Thrown Star Cruel PoisonBloom"},
{ID="cruel_firestorm_bolt", name="Bolt of Cruel FireStorm"},
{ID="cruel_frostbloom_bolt", name="Bolt of Cruel FrostBloom"},
{ID="cruel_poisonbloom_bolt", name="Bolt of Cruel PoisonBloom"},
{ID="cruel_shockbloom_bolt", name="Bolt of Cruel ShockBloom"},
{ID="cruel_firestorm_dart", name="Thrown Dart Cruel FireStorm"},
{ID="cruel_frostbloom_dart", name="Thrown Dart Cruel FrostBloom"},
{ID="cruel_poisonbloom_dart", name="Thrown Dart Cruel PoisonBloom"},
{ID="cruel_shockbloom_dart", name="Thrown Dart Cruel ShockBloom"},
{ID="dire_firestorm_arrow", name="Arrow of Dire FireStorm"},
{ID="dire_frostbloom_arrow", name="Arrow of Dire FrostBloom"},
{ID="dire_poisonbloom_arrow", name="Arrow of Dire PoisonBloom"},
{ID="dire_shockbloom_arrow", name="Arrow of Dire ShockBloom"},
{ID="dire_firestorm_bolt", name="Bolt of Dire FireStorm"},
{ID="dire_frostbloom_bolt", name="Bolt of Dire FrostBloom"},
{ID="dire_poisonbloom_bolt", name="Bolt of Dire PoisonBloom"},
{ID="dire_shockbloom_bolt", name="Bolt of Dire ShockBloom"},
{ID="dire_firestorm_dart", name="Thrown Dart Dire FireStorm"},
{ID="dire_frostbloom_dart", name="Thrown Dart Dire FrostBloom"},
{ID="dire_poisonbloom_dart", name="Thrown Dart Dire PoisonBloom"},
{ID="dire_shockbloom_dart", name="Thrown Dart Dire ShockBloom"},
{ID="dire_firestorm_star", name="Thrown Star Dire FireStorm"},
{ID="dire_frostbloom_star", name="Thrown Star Dire FrostBloom"},
{ID="dire_poisonbloom_star", name="Thrown Star Dire PoisonBloom"},
{ID="dire_shockbloom_star", name="Thrown Star Dire ShockBloom"},
{ID="dread_firestorm_arrow", name="Arrow of Dread FireStorm"},
{ID="dread_frostbloom_arrow", name="Arrow of Dread FrostBloom"},
{ID="dread_poisonbloom_arrow", name="Arrow of Dread PoisonBloom"},
{ID="dread_shockbloom_arrow", name="Arrow of Dread ShockBloom"},
{ID="T_Nor_Iron_Seax_01", name="Short Seax Iron Nordic"},
{ID="T_Nor_Orn_Seax_01", name="Short Seax Nordic"},
{ID="T_Nor_Silver_Seax_01", name="Short Seax Silver Nordic"},
{ID="T_Imp_UNI_NafaalilargusClaw", name="Short Claw of Nafaalilargus"},
{ID="T_Nor_Orn_ThrowingAxe_01", name="Thrown Axe Ornate"},
{ID="T_Nor_Iron_ThrowingAxe_01", name="Thrown Axe Balanced"},
{ID="T_Rea_Regular_WarAxe_01", name="Axe War Reachmen"},
{ID="T_Rea_Regular_Warhammer_01", name="Warhammer Reachmen"},
{ID="T_Rea_Regular_Halberd_01", name="Spear Halberd Reachmen"},
{ID="T_Cr_Goblin_Club_01", name="Blunt Club Goblin"},
{ID="T_Orc_Regular_Bow_01", name="Bow Long Orc"},
{ID="T_Orc_Regular_WarAxeThooted_01", name="Battle Axe Orcish Toothed"},
{ID="T_Com_Var_Harpoon_01", name="Spear Harpoon"},
{ID="T_Rea_Regular_Halberd_Bloodlett", name="Spear Halberd Bloodletter"},
{ID="T_Rea_Regular_WarAxe_Witchwarri", name="Axe Witch-Warrior"},
{ID="T_Com_Var_Harpoon_Heartsting", name="Spear Heartstinger"},
{ID="T_Rea_Regular_WarAxe_Harrier", name="Axe Harrier"},
{ID="T_Rea_Regular_WarAxe_Bonesplitt", name="Axe Bonesplitter"},
{ID="T_Nor_Silver_Dagger_Danswyrm", name="Short Dagger Silver Danswyrm"},
{ID="T_Nor_Silver_Shortsword_Danswyr", name="Short Sword Silver Danswyrm"},
{ID="T_Nor_Orn_BattleAxe_Frostbitt", name="Battle Axe Frostbitten"},
{ID="T_Nor_Orn_Broadsword_Frostbitt", name="Sword Frostbitten"},
{ID="T_Com_Steel_Claymore_Redhilted", name="TwoHanded Sword Red-Hilted"},
{ID="T_Nor_Iron_WarAxe_01", name="Axe War Iron"},
{ID="T_He_Direnni_Longsword_01", name="Sword Long Elven Old"},
{ID="T_He_Direnni_Shortsword_01", name="Short Sword Elven Old"},
{ID="T_He_Direnni_BattleAxe_01", name="Battle Axe Elven Old"},
{ID="T_He_Direnni_Halberd_01", name="Spear Halberd Elven Old"},
{ID="T_He_Direnni_Staff_01", name="Staff Elven Old"},
{ID="T_Imp_Barrow_Axe_01", name="Axe Nedic Ancient"},
{ID="T_Imp_Barrow_Spear_01", name="Spear Nedic Ancient"},
{ID="T_Imp_Barrow_Sword_01", name="Short Sword Nedic Ancient"},
{ID="T_Cr_Goblin_Axe_01", name="Axe Goblin"},
{ID="T_Com_Farm_Scythe_01", name="Farmer's Scythe"},
{ID="T_Imp_Silver_Dagger_AugStalk", name="Short Dagger of Stalking"},
{ID="T_Imp_Silver_Dagger_AugGreenWis", name="Short Dagger of Green Wisdom"},
{ID="T_Imp_Silver_Javelin_AugHorker", name="Thrown Javelin of the Horker"},
{ID="T_Imp_Silver_Longsword_AugSurpr", name="Sword Long of Surprise"},
{ID="T_Imp_Silver_Longsword_AugGoldW", name="Sword Long of Gold Wisdom"},
{ID="T_Imp_Silver_Mace_AugDeepCrush", name="Blunt Mace of Deep Crushing"},
{ID="T_Imp_Silver_Saber_AugSwiftbl", name="Sword Saber of the Swift Blade"},
{ID="T_Imp_Silver_Shortsword_AugSwim", name="Short Sword of the Swimmer"},
{ID="T_Imp_Silver_Shortsword_AugSWis", name="Short Dagger of Silver Wisdom"},
{ID="T_Imp_Silver_WarAxe_AugHew", name="Axe War of Hewing"},
{ID="T_Com_Steel_Longbow_AugPrec", name="Bow Long of Precision"},
{ID="T_Com_Steel_Arrow_CruelFirestrm", name="Arrow of Cruel FireStorm"},
{ID="T_Com_Steel_Bolt_CruelFirestrm", name="Bolt of Cruel FireStorm"},
{ID="T_Com_Steel_Dart_CruelFirestrm", name="Thrown Dart Cruel FireStorm"},
{ID="T_Com_Steel_ThrowingStar_CrFrSt", name="Thrown Star Cruel FireStorm"},
{ID="T_Com_Steel_Arrow_CruelFrostB", name="Arrow of Cruel FrostBurst"},
{ID="T_Com_Steel_Bolt_CruelFrostB", name="Bolt of Cruel FrostBurst"},
{ID="T_Com_Steel_Dart_CruelFrostB", name="Thrown Dart Cruel FrostBurst"},
{ID="T_Com_Steel_ThrowingStar_CrFrB", name="Thrown Star Cruel FrostBurst"},
{ID="T_Com_Steel_Arrow_CruelPoisonCl", name="Arrow of Cruel PoisonCloud"},
{ID="T_Com_Steel_Bolt_CruelPoisonCl", name="Bolt of Cruel PoisonCloud"},
{ID="T_Com_Steel_Dart_CruelPoisonCl", name="Thrown Dart Cruel PoisonCloud"},
{ID="T_Com_Steel_ThrowingStar_CrPoiC", name="Thrown Star Cruel PoisonCloud"},
{ID="T_Com_Steel_Arrow_CruelShockSph", name="Arrow of Cruel ShockSphere"},
{ID="T_Com_Steel_Bolt_CruelShockSph", name="Bolt of Cruel ShockSphere"},
{ID="T_Com_Steel_Dart_CruelShockSph", name="Thrown Dart Cruel ShockSphere"},
{ID="T_Com_Steel_ThrowingStar_CrSSph", name="Thrown Star Cruel ShockSphere"},
{ID="T_Com_DaedSteel_Broadsword_Drem", name="Sword Broad of Darkness"},
{ID="T_Com_DaedSteel_Dagger_Scamp", name="Short Dagger of Mischief"},
{ID="T_Com_DaedSteel_Longsword_Hungr", name="Sword Long of Starvation"},
{ID="T_Com_DaedSteel_Shortsword_Clan", name="Short Sword of Fright"},
{ID="T_Imp_Silver_Arrow_DireFirestrm", name="Arrow of Dire FireStorm"},
{ID="T_Imp_Silver_Bolt_DireFirestrm", name="Bolt of Dire FireStorm"},
{ID="T_Imp_Silver_Dart_DireFirestrm", name="Thrown Dart Dire FireStorm"},
{ID="T_Imp_Silver_ThrowingStar_DrFSt", name="Thrown Star Dire FireStorm"},
{ID="T_Imp_Silver_Arrow_DireFrostBst", name="Arrow of Dire FrostBurst"},
{ID="T_Imp_Silver_Bolt_DireFrostBst", name="Bolt of Dire FrostBurst"},
{ID="T_Imp_Silver_Dart_DireFrostBst", name="Thrown Dart Dire FrostBurst"},
{ID="T_Imp_Silver_ThrowingStar_DrFrB", name="Thrown Star Dire FrostBurst"},
{ID="T_Imp_Silver_Arrow_DirePoisonCl", name="Arrow of Dire PoisonCloud"},
{ID="T_Imp_Silver_Bolt_DirePoisonCl", name="Bolt of Dire PoisonCloud"},
{ID="T_Imp_Silver_Dart_DirePoisonCl", name="Thrown Dart Dire PoisonCloud"},
{ID="T_Imp_Silver_ThrowingStar_DrPoi", name="Thrown Star Dire PoisonCloud"},
{ID="T_Imp_Silver_Arrow_DireShocksph", name="Arrow of Dire ShockSphere"},
{ID="T_Imp_Silver_Bolt_DireShocksph", name="Bolt of Dire ShockSphere"},
{ID="T_Imp_Silver_Dart_DireShocksph", name="Thrown Dart Dire ShockSphere"},
{ID="T_Imp_Silver_ThrowingStar_DrShk", name="Thrown Star Dire ShockSphere"},
{ID="T_De_Ebony_Arrow_DreadFirestorm", name="Arrow of Dread FireStorm"},
{ID="T_De_Ebony_Arrow_DreadFrostbrst", name="Arrow of Dread FrostBurst"},
{ID="T_De_Ebony_Arrow_DreadPoisonCld", name="Arrow of Dread PoisonCloud"},
{ID="T_De_Ebony_Arrow_DreadShockSphr", name="Arrow of Dread ShockSphere"},
{ID="T_Com_Wood_Mace_Judgement", name="Blunt Mace of Judgment Wooden"},
{ID="T_De_6th_Sickle_01", name="Battle Sickle of the 6th House"},
{ID="T_Com_Adamant_Bow_01", name="Bow Long Adamantium"},
{ID="T_Com_Adamant_Broadsword_01", name="Sword Broad Adamantium"},
{ID="T_Com_Adamant_Club_01", name="Blunt Club Adamantium"},
{ID="T_Com_Adamant_Crossbow_01", name="Crossbow Adamantium"},
{ID="T_Com_Adamant_Dagger_01", name="Short Dagger Adamantium"},
{ID="T_Com_Adamant_DaiKatana_01", name="TwoHanded Dai-Katana Adamantium"},
{ID="T_Com_Adamant_DoubleAxe_01", name="Battle Axe Adamantium"},
{ID="T_Com_Adamant_Halberd_01", name="Spear Halberd Adamantium"},
{ID="T_Com_Adamant_Katana_01", name="Sword Katana Adamantium"},
{ID="T_Com_Adamant_Longsword_01", name="Sword Long Adamantium"},
{ID="T_Com_Adamant_Saber_01", name="Sword Saber Adamantium"},
{ID="T_Com_Adamant_Scimitar_01", name="Sword Scimitar Adamantium"},
{ID="T_Com_Adamant_Staff_01", name="Staff Adamantium"},
{ID="T_Com_Adamant_Tanto_01", name="Short Tanto Adamantium"},
{ID="T_Com_Adamant_Wakizashi_01", name="Short Wakizashi Adamantium"},
{ID="T_Com_Adamant_WarAxe_01", name="Axe War Adamantium"},
{ID="T_Com_Adamant_Warhammer_01", name="Warhammer Adamantium"},
{ID="T_De_Aena_Arrow_01", name="Arrow Aena"},
{ID="T_De_Aena_Mace_01", name="War Mace Aena"},
{ID="T_De_Aena_Sickle_01", name="Short Sickle Aena"},
{ID="T_De_Aena_Spear_01", name="Spear Aena"},
{ID="T_Dae_UNI_BoethiahAxe", name="Battle Axe of Boethiah"},
{ID="T_De_Chitin_Longsword_01", name="Sword Long Chitin"},
{ID="T_Com_Var_Knife_01", name="Knife Cooking"},
{ID="T_Com_Var_Knife_02", name="Knife Cooking"},
{ID="T_Com_Var_Knife_03", name="Knife Cooking"},
{ID="T_Dae_Regular_Fang_01", name="Short Fang Daedric"},
{ID="T_Dae_Regular_Longspear_01", name="Spear Long Daedric"},
{ID="T_Dae_Regular_Longsword_01", name="Sword Long Daedric"},
{ID="T_Dae_Regular_Naginata_01", name="Spear Naginata Daedric"},
{ID="T_Dae_Regular_Saber_01", name="Sword Saber Daedric"},
{ID="T_Dae_Regular_Scimitar_01", name="TwoHanded Falchion Daedric"},
{ID="T_Dae_Regular_Scimitar_02", name="Sword Scimitar Daedric"},
{ID="T_Dae_Regular_Trident_01", name="Spear Trident Daedric"},
{ID="T_Dwe_Regular_Bolt_01", name="Bolt Dwarven"},
{ID="T_Dwe_Regular_Bolt_Jink", name="Bolt Dwarven Jinkbolt"},
{ID="T_Dwe_Regular_Broadsword_01", name="Sword Broad Dwarven"},
{ID="T_Dwe_Regular_Dagger_01", name="Short Dagger Dwarven"},
{ID="T_Dwe_Regular_Junkmace_01", name="Blunt Dwarven Junk Mace"},
{ID="T_Dwe_Regular_Longspear_01", name="Spear Long Dwarven"},
{ID="T_Dwe_Regular_Longsword_01", name="Sword Long Dwarven"},
{ID="T_Dwe_Regular_Staff_01", name="Staff Dwarven"},
{ID="T_De_Ebony_Claymore_01", name="Claymore Ebony"},
{ID="T_De_Ebony_Dagger_01", name="Short Dagger Ebony"},
{ID="T_De_Ebony_DaiKatana_01", name="TwoHanded Dai-Katana Ebony"},
{ID="T_De_Ebony_Halberd_01", name="Spear Bardiche Ebony"},
{ID="T_De_Ebony_Katana_01", name="Sword Katana Ebony"},
{ID="T_De_Ebony_Tanto_01", name="Short Tanto Ebony"},
{ID="T_De_Ebony_Wakizashi_01", name="Short Wakizashi Ebony"},
{ID="T_De_Glass_BattleAxe_01", name="Battle Axe Glass"},
{ID="T_De_Glass_DaiKatana_01", name="TwoHanded Dai-katana Glass"},
{ID="T_De_Glass_Katana_01", name="Sword Katana Glass"},
{ID="T_De_Glass_Spear_01", name="Spear Glass"},
{ID="T_De_Glass_Tanto_01", name="Short Tanto Glass"},
{ID="T_De_Glass_Wakizashi_01", name="Short Wakizashi Glass"},
{ID="T_Com_Gold_Dagger_01", name="Short Dagger Gold"},
{ID="T_Imp_Legion_Arrow_01", name="Arrow Steel Imperial"},
{ID="T_Imp_Legion_Bolt_01", name="Bolt Steel Imperial"},
{ID="T_Imp_Legion_Broadsword_01", name="Sword Broad Imperial"},
{ID="T_Imp_Legion_Broadsword_02", name="Sword Broad Imperial"},
{ID="T_Imp_Legion_Broadsword_03", name="Sword Broad Imperial"},
{ID="T_Imp_Legion_Dagger_01", name="Short Dagger Imperial"},
{ID="T_Imp_Legion_RoyalLongsword_01", name="Sword Long Silver Royal"},
{ID="T_Imp_Legion_Saber_01", name="Sword Saber Imperial"},
{ID="T_Com_Iron_Broadsword_01", name="Sword Broad Iron"},
{ID="T_Com_Iron_Broadsword_02", name="Sword Broad Iron"},
{ID="T_Com_Iron_Broadsword_03", name="Sword Broad Iron"},
{ID="T_Com_Iron_Dagger_01", name="Short Dagger Iron"},
{ID="T_Com_Iron_Dagger_02", name="Short Dagger Iron"},
{ID="T_Com_Iron_Morningstar_01", name="Blunt Morningstar Iron"},
{ID="T_Com_Iron_Saber_01", name="Sword Saber Iron"},
{ID="T_Com_Iron_Saber_02", name="Sword Saber Iron"},
{ID="T_Com_Iron_Saber_03", name="Sword Saber Iron"},
{ID="T_Com_Iron_Scimitar_01", name="Sword Scimitar Iron"},
{ID="T_Com_Iron_Tanto_01", name="Short Tanto Iron"},
{ID="T_Com_Iron_Tanto_02", name="Short Tanto Iron"},
{ID="T_Com_Iron_Tanto_03", name="Short Tanto Iron"},
{ID="T_Com_Iron_Tanto_04", name="Short Tanto Iron"},
{ID="T_Com_Iron_ThrowingKnife_01", name="Thrown Knife Iron"},
{ID="T_Com_Iron_ThrowingKnife_02", name="Thrown Knife Iron"},
{ID="T_Dae_UNI_MeridiaDagger", name="Short Dagger of Meridia"},
{ID="T_Com_UNI_Mosslog", name="Staff Mosslog"},
{ID="T_Nor_Orn_BattleAxe_01", name="Battle Axe Nordic"},
{ID="T_Nor_Orn_WarAxe_01", name="Axe Nordic"},
{ID="T_Nor_Orn_Dagger_01", name="Short Dagger Nordic"},
{ID="T_Nor_Orn_Longsword_01", name="Sword Long Nordic"},
{ID="T_Nor_Orn_Spear_01", name="Spear Nordic"},
{ID="T_Nor_Orn_Shortsword_01", name="Short Sword Nordic"},
{ID="T_Nor_Orn_Warhammer_01", name="Warhammer Nordic"},
{ID="T_Orc_Regular_Claymore_01", name="Claymore Orcish"},
{ID="T_Orc_Regular_Cleaver_01", name="Sword Long Orcish Cleaver"},
{ID="T_Orc_Regular_Dagger_01", name="Short Orcish Shank"},
{ID="T_Orc_Regular_Dagger_02", name="Short Orcish Skiver"},
{ID="T_Orc_Regular_Halberd_01", name="Spear Halberd Orcish"},
{ID="T_Orc_Regular_Longsword_01", name="Sword Long Orcish"},
{ID="T_Orc_Regular_Mace_01", name="War Mace Orcish"},
{ID="T_Orc_Regular_Spear_01", name="Spear Orcish"},
{ID="T_Orc_Regular_Spear_02", name="Spear Orcish"},
{ID="T_Orc_Regular_BattleAxe_01", name="Battle Axe Orcish"},
{ID="T_Nor_Var_WerewolfboneDagger_01", name="Short Sacrificial Dagger"},
{ID="T_Imp_Silver_Dagger_01", name="Short Dagger Silver"},
{ID="T_Imp_Silver_Dagger_02", name="Short Dagger Silver"},
{ID="T_Imp_Silver_Mace_01", name="Blunt Mace Silver"},
{ID="T_Imp_Silver_Saber_01", name="Sword Saber Silver"},
{ID="T_Com_DaedSteel_Broadsword_01", name="Sword Broad Steel Daedric"},
{ID="T_Com_DaedSteel_Claymore_01", name="Claymore Steel Daedric"},
{ID="T_Com_DaedSteel_Dagger_01", name="Short Dagger Steel Daedric"},
{ID="T_Com_DaedSteel_Longsword_01", name="Sword Long Steel Daedric"},
{ID="T_Com_DaedSteel_Shortsword_01", name="Short Sword Steel Daedric"},
{ID="T_Com_Steel_Dagger_01", name="Short Dagger Steel"},
{ID="T_Com_Steel_Knife_01", name="Thrown Knife Steel"},
{ID="T_Com_Steel_Scimitar_01", name="Sword Scimitar Steel"},
{ID="T_Com_Wood_Mace_01", name="Blunt Mace Wooden"},
{ID="T_Dwe_Regular_Dart_01", name="Thrown Dart Dwarven Light"},
{ID="T_Dwe_Regular_Dart_Shock", name="Thrown Dart Dwarven of Shock"},
{ID="T_Com_UNI_CrossbowOfGhostlight", name="Crossbow Steel of Ghostlight"},
{ID="T_Dwe_Regular_Spear_Retribut", name="Spear of Retribution Dwarven"},
{ID="T_Imp_Silver_Spear_Retribution", name="Spear of Retribution Silver"},
{ID="T_Com_Steel_BattleAxe_Precision", name="Battle Axe Steel of Precision"},
{ID="T_Imp_Silver_Spear_Paralysis", name="Spear of Paralysis Silver"},
{ID="T_De_Ebony_Halberd_Swim", name="Spear The Horker's Tooth"},
{ID="T_Dwe_Regular_CrossbowFix_01", name="Crossbow Dwarven"},
{ID="T_Com_Wood_Crossbow_01", name="Crossbow Wooden"},
{ID="T_Bre_Artisan_Broadsword_01", name="Sword Broad Wayrest Artisan"},
{ID="T_Bre_Artisan_Longsword_01", name="Sword Long Wayrest Artisan"},
{ID="T_Bre_Artisan_Shortsword_01", name="Short Sword Wayrest Artisan"},
{ID="T_Bre_Artisan_Dagger_01", name="Short Dagger Wayrest Artisan"},
{ID="T_Bre_Artisan_Claymore_01", name="Claymore Wayrest Artisan"},
{ID="T_Com_Var_Harpoon_02", name="Spear Harpoon"},
{ID="T_Com_Adamant_Gisern", name="Spear Giserne Adamantium"},
{ID="T_Com_Adamant_Star", name="Thrown Star Adamantium"},
{ID="T_De_Ebony_Battleaxe_01", name="Battle Axe Ebony"},
{ID="T_De_Ebony_Halberd_02", name="Spear Halberd Ebony"},
{ID="T_De_Ebony_Shortsword_02", name="Short Sword Ebony"},
{ID="T_De_Ebony_Scythe", name="Spear Warscythe Ebony"},
{ID="T_De_Ebony_Warhammer_01", name="Warhammer Ebony"},
{ID="T_Imp_Legion_Longsword_01", name="Sword Long Imperial"},
{ID="T_Imp_Silver_2HMace", name="War Mace Silver Spiked"},
{ID="T_Imp_Silver_Mace_02", name="Blunt Mace Silver"},
{ID="T_Imp_Silver_Saber_02", name="Short Saber Short Silver"},
{ID="T_Rga_Yoku_2hsword", name="Claymore Yoku"},
{ID="T_Rga_Yoku_Halberd_01", name="Spear Halberd Yoku"},
{ID="T_Rga_Yoku_Lsword_01", name="Sword Long Yoku"},
{ID="T_Rga_Yoku_Spear_01", name="Spear Yoku"},
{ID="T_Rga_Yoku_Waraxe_01", name="Axe War Yoku"},
{ID="T_Imp_Uni_SwiftcutSaber", name="Sword Saber Swiftcut"},
{ID="T_Nor_UNI_AxeRhorlaks", name="Battle Axe Rhorlak's"},
{ID="T_Cr_Goblin_Axe_Poison", name="Axe Goblin of Poison"},
{ID="T_Rga_Alik_Waraxe_01", name="Axe War Alik'r"},
{ID="T_Rga_Verk_Cutlass_01", name="Short Verkathi Cutlass"},
{ID="T_Rga_Cera_SSword_01", name="Short Sword Ceramic"},
{ID="T_Rga_Alik_Dagger_01", name="Short Dagger Alik'r"},
{ID="T_Rga_Alik_Broadsword_01", name="Sword Broad Alik'r"},
{ID="T_Dae_UNI_EbonyBlade", name="Sword Ebony Blade"},
{ID="T_Imp_Silver_Longbow_01", name="Bow Long Silver"},
{ID="T_Dwe_Regular_Arrow_01", name="Arrow Dwarven"},
{ID="T_Dwe_UNI_NeldracsReach", name="Bow Nchunak's"},
{ID="T_Dae_UNI_SoulAnchorSaber", name="Sword Soul Anchor"},
{ID="T_Dae_UNI_SoulAnchorTrident", name="Spear Soul Anchor"},
{ID="T_Dae_UNI_SanguineRose", name="Staff Sanguine's Rose"},
{ID="T_Ayl_UNI_Chillrend", name="Short Chillrend"},
{ID="T_Dae_UNI_GwaiLo", name="TwoHanded Gwai-lo"},
{ID="T_Dae_UNI_SkullOfCorruption", name="Blunt Skull of Corruption"},
{ID="T_Nor_UNI_ShardOfVehemence", name="Short Shard of Vehemence"},
{ID="T_Com_UNI_BladeOfWoe", name="Short Blade of Woe"},
{ID="T_Dae_UNI_RuefulAxe", name="Battle Axe Rueful"},
{ID="T_Dae_UNI_NebCrescen", name="Sword Neb-Crescen"},
{ID="T_De_UNI_EthosKnife", name="Short Ethos Knife"},
{ID="T_Dae_Uni_Dawnbreaker", name="Sword Dawnbreaker"},
{ID="T_Dae_Uni_CorruptBreaker", name="Sword Corrupted Dawnbreaker"},
{ID="T_Ayl_UNI_Sinweaver", name="TwoHanded Sinweaver"},
{ID="T_Com_Steel_Longsword_01", name="Sword Long Steel"},
{ID="T_Com_Steel_Shortsword_01", name="Short Sword Steel"},
{ID="T_Com_Steel_Broadsword_01", name="Sword Broad Steel"},
{ID="T_Com_Steel_Shortsword_02", name="Short Sword Steel"},
{ID="T_Imp_UNI_CutlassArchon", name="Sword Cutlass of Archon"},
{ID="T_Nor_UNI_StuhnsForge", name="Blunt Stuhn's Forge"},
{ID="T_He_UNI_Keenblood", name="Sword Keenblood Blade"},
{ID="T_De_UNI_Muatra", name="Spear Muatra"},
{ID="T_Nor_UNI_Askenhost", name="Battle Axe Askenhost"},
{ID="T_Dae_UNI_Wabbajack", name="Staff Wabbajack"},
{ID="T_Nor_Ice_Bow_01", name="Bow Long Stalhrim"},
{ID="T_Nor_Huntsman_Bow_01", name="Bow Long Huntsman's"},
{ID="T_Nor_Silver_Bow_01", name="Bow Long Silver Nordic"},
{ID="T_De_Ebony_Bow_01", name="Bow Long Ebony"},
{ID="T_Nor_Huntsman_Shortsword_01", name="Short Sword Huntsman's"},
{ID="T_Dae_Regular_Halberd_01", name="Spear Halberd Daedric"},
{ID="T_Com_Iron_Staff_01", name="Staff Iron"},
{ID="T_Com_Iron_Warpick_01", name="Axe War Pick Iron"},
{ID="T_Com_Silver_Warpick_01", name="Axe War Pick Silver"},
{ID="T_Com_Iron_GreatMace_01", name="War Mace Iron Great"},
{ID="T_Com_Adamant_Arrow_01", name="Arrow Adamantium"},
{ID="T_Com_Adamant_Bolt_01", name="Bolt Adamantium"},
{ID="T_Dae_Regular_GSword_01", name="TwoHanded Greatsword Daedric"},
{ID="T_Com_Adamant_DoubleAxe_02", name="Battle Axe Adamantium"},
{ID="T_Imp_UNI_BeraidSpear", name="Spear Nandor's"},
{ID="T_Imp_Legion_Shortsword_01", name="Short Sword Imperial"},
{ID="T_Imp_Legion_Katana_01", name="Sword Katana Imperial"},
{ID="T_Imp_Legion_WarAxe_01", name="Axe War Imperial"},
{ID="T_Ayl_Arrow_01", name="Arrow Ayleid"},
{ID="T_Nor_Steel_Waraxe_01", name="Axe War Steel Nordic"},
{ID="T_Nor_Steel_WarHammer_01", name="Warhammer Steel Nordic"},
{ID="T_Nor_Steel_Spear_01", name="Spear Steel Nordic"},
{ID="T_Nor_UNI_RagnidAxe", name="Axe Ragnid the Axe"},
{ID="T_Nor_Iron_Spear_01", name="Spear Iron Nordic"},
{ID="T_Bre_Fine_Dagger_01", name="Short Fine Betony Dagger"},
{ID="T_Nor_FineSteel_Seax_01", name="Short Seax Steel of Quality"},
{ID="T_Nor_Regular_Longsword_01", name="Sword Long Steel"},
{ID="T_Com_Silver_Staff_01", name="Staff Silver"},
{ID="T_De_UNI_NerevarAxe", name="Axe Nerevar's"},
{ID="T_Dae_Regular_Broadsword_01", name="Sword Broad Daedric"},
{ID="T_De_Ind_BellHammer_01", name="Warhammer Indoril Bell Hammer"},
{ID="T_De_UNI_AlmaRulaGavel", name="Warhammer Gavel of Alma Rula"},
{ID="T_De_Glass_Dart_01", name="Thrown Dart Glass"},
{ID="T_Dae_Regular_ThrowingStar_01", name="Thrown Thrown Star Daedric"},
{ID="T_De_Glass_Mace_01", name="Blunt Mace Glass"},
{ID="T_De_Glass_Bolt_01", name="Bolt Glass"},
{ID="T_De_Glass_Shortsword_01", name="Short Sword Glass"},
{ID="T_De_Glass_Shortsword_02", name="Short Sword Glass"},
{ID="T_Orc_Regular_Dart_01", name="Thrown Dart Orcish"},
{ID="T_Nor_Orn_Warhammer_02", name="Warhammer Nordic"},
{ID="T_Ayl_Regular_LongBow_01", name="Bow Ayleid Longbow"},
{ID="T_Ayl_Regular_WarAxe_01", name="Axe Ayleid War Axe"},
{ID="T_Ayl_Regular_ShortBlade_01", name="Short Ayleid Curved Short Blade"},
{ID="T_Ayl_Regular_LongBlade_01", name="Sword Ayleid Curved Long Blade"},
{ID="T_Ayl_Regular_Dagger_01", name="Short Ayleid Sacrificial Dagger"},
{ID="T_Ayl_Regular_Spear_01", name="Spear Ayleid"},
{ID="T_Rga_UNI_snakebow", name="Bow Sep's"},
{ID="T_De_Glass_Warhammer_01", name="Warhammer Glass"},
{ID="T_De_UNI_TreasureWoodSword", name="Short Treasure Wood Sword"},
{ID="T_Nor_StalhrimShortsword_01", name="Short Sword Stalhrim"},
{ID="T_Nor_StalhrimSpear_01", name="Spear Stalhrim"},
{ID="T_Nor_SilverSpear_01", name="Spear Silver Nordic"},
{ID="T_Imp_Reman_Shortsword_01", name="Short Sword Reman Legion"},
{ID="T_Imp_Reman_Broadsword_01", name="Sword Broad Reman Legion"},
{ID="T_Imp_Reman_Spear_01", name="Spear Reman Legion"},
{ID="T_Imp_Reman_Mace_01", name="Blunt Mace Reman Legion"},
{ID="T_Imp_Reman_Javelin_01", name="Thrown Javelin Reman Legion"},
{ID="T_Nor_UNI_NebsTalon", name="Short Neb's Talon"},
{ID="T_Com_Wood_Arrow_01", name="Arrow Wooden"},
{ID="T_Com_Wood_Bolt_01", name="Bolt Wooden"},
{ID="T_Bre_UNI_AzraMace", name="Blunt Mace Azra's"},
{ID="T_Imp_UNI_Debaser", name="Short Debaser"},
{ID="T_Nor_UNI_GodsbloodAxe", name="Battle Axe Hrygg Godsblood Axe"},
{ID="T_Nor_UNI_GodsbloodSeax", name="Short Vrigyn Godsblood Seax"},
{ID="T_Nor_UNI_GodsbloodSpear", name="Spear Ulfgyir Godsblood Spear"},
{ID="T_Imp_Silver_Katana_01", name="Sword Katana Silver"},
{ID="T_Rga_UNI_Gatkhel_01", name="TwoHanded Gatkhel"},
{ID="T_Rga_UNI_Utanogo_01", name="Spear Utanogo"},
{ID="T_Rga_UNI_Tangra_01", name="Sword Tangra"},
{ID="T_Rga_UNI_Duptro_01", name="Sword Duptro"},
{ID="T_Com_UNI_Spider_Impaler", name="Sword Spider Impaler"},
{ID="T_Imp_UNI_ChampionCudgel", name="Warhammer Champion's Cudgel"},
{ID="T_Nor_UNI_HammerOlfor", name="Warhammer of Olfor"},
{ID="T_Rga_Steel_SwiftcutSaber", name="Sword Saber Swiftcut"},
{ID="T_Rga_Steel_Saber_01", name="Sword Saber Steel"},
{ID="T_Imp_Silver_Warhammer_01", name="Warhammer Silver"},
{ID="T_Com_UNI_Clarentavious_Staff", name="Staff Clarentavious'"},
{ID="T_Com_UNI_Chimere_Staff", name="Staff Chimere's"},
{ID="T_De_Chitin_Bolt_01", name="Bolt Chitin"},
{ID="T_Tsa_Regular_Katana_01", name="Sword Katana Tsaesci"},
{ID="T_Tsa_Regular_Katana_02", name="Sword Old Rusty Tsaesci Katana"},
{ID="T_We_Wenbone_Bow_01", name="Bow Bosmeri Wenbone"},
{ID="T_Com_Iron_GSword_01", name="TwoHanded Greatsword Iron"},
{ID="T_Imp_Silver_Halberd_01", name="Spear Halberd Silver"},
{ID="T_Dae_Regular_ThrowingKnife_01", name="Thrown Knife Daedric"},
{ID="T_nor_Ice_Arrow_01", name="Arrow Stalhrim"},
{ID="T_Nor_Huntsman_Arrow_01", name="Arrow Huntsman's"},
{ID="T_Gob_Goblin_Arrow_01", name="Arrow Goblin"},
{ID="T_Orc_Orcish_Arrow", name="Arrow Orcish"},
{ID="AB_w_NordicLongAxe", name="Spear Nordic Long Axe"},
{ID="AB_w_EbonyHalberd", name="Spear Halberd Ebony"},
{ID="AB_w_ResinStaff", name="Staff Resin"},
{ID="AB_w_GoldStClaymore", name="Claymore Golden Saint"},
{ID="AB_w_CookKnifeBone", name="Knife Boning"},
{ID="AB_w_CookKnifeBread", name="Knife Bread"},
{ID="AB_w_CookKnifeChef", name="Knife Cook's"},
{ID="AB_w_ToolPitchfork", name="Farmer's Pitch Fork"},
{ID="AB_w_ResinStaffFire", name="Staff Resin of Incineration"},
{ID="AB_w_ResinStaffTerror", name="Staff Resin of Unholy Terror"},
{ID="AB_w_ResinStaffDevouring", name="Staff Resin of Devouring"},
{ID="AB_w_ToolEbonyPick", name="Miner's Pick Ebony"},
{ID="AB_w_ImpDaiKatana", name="TwoHanded Dai-katana Imperial"},
{ID="AB_w_OrcishMace", name="Blunt Mace Orcish"},
{ID="AB_w_SteelShortSaber", name="Short Saber Steel"},
{ID="AB_w_SixthKnife", name="Thrown Knife of the 6th House"},
{ID="AB_w_DaedricHalberd", name="Spear Halberd Daedric"},
{ID="AB_w_AshlBoneArrow", name="Arrow Bone Ashlander"},
{ID="AB_w_GlassSpear", name="Spear Glass"},
{ID="AB_w_DwrvArbalest", name="Crossbow Dwarven Arbalest"},
{ID="AB_w_ReCrossbow", name="Crossbow Reinforced"},
{ID="AB_w_BoneArrow", name="Arrow Bone"},
{ID="AB_w_BoneBolt", name="Bolt Bone"},
{ID="AB_w_GoblinArrow", name="Arrow Goblin"},
{ID="AB_w_HuntsArrow", name="Arrow Huntsman's"},
{ID="AB_w_StalhrimArrow", name="Arrow Stalhrim"},
{ID="AB_w_OrcishArrow", name="Arrow Orcish"},
{ID="AB_w_GlassDart", name="Thrown Dart Glass"},
{ID="AB_w_DaedricKnife", name="Thrown Knife Daedric"},
{ID="AB_w_SilverKnife", name="Thrown Knife Silver"},
{ID="AB_w_EbonyBolt", name="Bolt Ebony"},
{ID="AB_w_HuntsBow", name="Bow Long Huntsman's"},
{ID="AB_w_StalhrimBow", name="Bow Long Stalhrim"},
{ID="AB_w_NordicSilverBow", name="Bow Long Silver Nordic"},
{ID="AB_w_EbonyBow", name="Bow Long Ebony"},
{ID="AB_w_EbonyBolt_Viper", name="Bolt Ebony of Viper"},
{ID="AB_w_EbonyBolt_Bdeath", name="Bolt Ebony of Black Death"},
{ID="AB_w_EbonyBolt_Rdeath", name="Bolt Ebony of Red Death"},
{ID="AB_w_SilverHalberd", name="Spear Halberd Silver"},
{ID="AB_w_ImpKatana", name="Sword Katana Imperial"},
{ID="AB_w_ImpBow", name="Bow Short Imperial"},
{ID="AB_w_ImpSpear", name="Spear Imperial"},
{ID="AB_w_EbonyGlaive", name="Spear Glaive Ebony"},
{ID="AB_w_BoneSaw", name="Sword Bonesaw"},
{ID="AB_w_MarkingKnife", name="Knife Marking"},
{ID="AB_w_WoodArrow", name="Arrow Wooden"},
{ID="AB_w_WoodBolt", name="Bolt Wooden"},
{ID="AB_w_WoodCrossbow", name="Crossbow Wooden"},
{ID="AB_w_NordicSilverSpear", name="Spear Silver Nordic"},
{ID="AB_w_StalhrimSpear", name="Spear Stalhrim"},
{ID="AB_w_StalhrimShortsword", name="Short Sword Stalhrim"},
{ID="AB_w_DwrvLongspear", name="Spear Long Dwarven"},
{ID="AB_w_DaeLongpear", name="Spear Long Daedric"},
{ID="AB_w_GlassKatana", name="Sword Katana Glass"},
{ID="AB_w_GlassDkatana", name="TwoHanded Dai-Katana Glass"},
{ID="AB_w_EbonyClaymore", name="Claymore Ebony"},
{ID="AB_w_NordicMace", name="Blunt Mace Nordic"},
{ID="ab01waterSaber", name="Sword Saber of Water"},
{ID="AM_Hammer", name="Blunt Armorer's Hammer"},
{ID="LLCS_boss_weapon", name="Blunt Kralzar"},
{ID="izi_ebony_broadsword", name="Sword Broad Ebony"},
{ID="izi_ebony_mace", name="Blunt Mace Ebony"},
{ID="izi_ebony_spear", name="Spear Ebony"},
{ID="izi_ebony_staff", name="Staff Ebony"},
{ID="izi_glass_halberd", name="Spear Halberd Glass"},
{ID="izi_glass_staff", name="Staff Glass"},
{ID="izi_nordic_axe", name="Battle Axe Soul of Winter"},
{ID="izi_tanto", name="Short Pacifier"},
{ID="izi_dwarven_claymore", name="Claymore Dwarven"},
{ID="izi_steel_longbow", name="Bow Steady Hands"},
{ID="crcl_glasshalberd", name="Spear Halberd Glass Ancient"},
{ID="_GG_repair_master_01", name="Blunt Armorer's Hammer Master's"},
{ID="indoril_spear", name="Spear Indoril"},
{ID="VA_RCR_ashpitsword", name="Sword Long Chitin"},
{ID="daedric nodachi", name="TwoHanded Nodachi Daedric"},
{ID="ChK_rap_iron", name="Sword Rapier Iron"},
{ID="ChK_rap_steel", name="Sword Rapier Steel"},
{ID="ChK_rap_silver", name="Sword Rapier Silver"},
{ID="ChK_rap_glass", name="Sword Rapier Glass"},
{ID="ChK_rap_daedric", name="Sword Rapier Daedric"},
{ID="ChK_rap_adam", name="Sword Rapier Adamantium"},
{ID="ChK_rap_iron_uni_brkprd", name="Sword Broken Pride "},
{ID="ChK_rap_steel_crufla_en", name="Sword Lunger of Cruel Flame"},
{ID="ChK_rap_iron_shar_en", name="Sword Lunger Iron of Shard"},
{ID="ChK_rap_iron_vip_en", name="Sword Lunger Iron of Viper"},
{ID="ChK_rap_iron_spark_en", name="Sword Lunger Iron of Spark"},
{ID="ChK_rap_iron_flam_en", name="Sword Lunger Iron of Flame"},
{ID="ChK_rap_silver_uni_cw_en", name="Sword Chariot's Whip"},
{ID="ChK_rap_silver_uni_silbla", name="Sword Silver Blaze"},
{ID="ChK_rap_steel_uni_jump", name="Sword Rapier Tinur's Air Thrust"},
{ID="ChK_rap_steel_crusha_en", name="Sword Lunger of Cruel Shard"},
{ID="ChK_rap_steel_cruspa_en", name="Sword Lunger of Cruel Spark"},
{ID="ChK_rap_steel_cruvip_en", name="Sword Lunger of Cruel Viper"},
{ID="ChK_rap_silver_crufla_en", name="Sword Lunger Silver of Flame"},
{ID="ChK_rap_silver_crusha_en", name="Sword Lunger Silver of Shard"},
{ID="ChK_rap_silver_cruspa_en", name="Sword Lunger Silver of Spark"},
{ID="ChK_rap_silver_cruvip_en", name="Sword Lunger Silver of Viper"},
{ID="ChK_rap_glass_dirsto_en", name="Sword Lunger Glass of Storm"},
{ID="ChK_rap_glass_dirfla_en", name="Sword Lunger Glass of Fire"},
{ID="ChK_rap_glass_dirfro_en", name="Sword Lunger Glass of Frost"},
{ID="ChK_rap_glass_dirpos_en", name="Sword Lunger Glass of Poison"},
{ID="ChK_rap_daedric_uni_piercer", name="Sword Marrow Piercer"},
{ID="_DXXbonescepter", name="Blunt Crude Bone Scepter"},
{ID="_DXXboneaxe", name="Axe Necromatic Bone Axe"},
{ID="IEO_daggerfall", name="Short Dagger of Fall"},
{ID="_pd_daedric broadsword", name="Sword Broad Daedric"},
{ID="if_ca_rapier_aundae", name="Sword Aundae Family Rapier"},
{ID="_pd_fireatro_axe", name="Axe Battle Fiery"},
{ID="_pd_fireatro_sword", name="Sword Fiery"},
{ID="BST_Athkarni Axe", name="Axe Athkarni"},
{ID="BST_Athkarni Dagger", name="Short Dagger Athkarni"},
{ID="BST_Athkarni Longsword", name="Sword Long Athkarni"},
{ID="BST_Athkarni Spear", name="Spear Athkarni"},
{ID="BST_fine silver dagger", name="Short Dagger Silver of Quality"},
{ID="BST_fine_silver_longsword", name="Sword Long Silver of Quality"},
{ID="_pd_dwrv_saber", name="Sword Saber Dwemer"},
{ID="_pd_black_brown_bow", name="Bow Black and Brown"},
{ID="ks_chitin shortsword", name="Short Sword Chitin"},
{ID="KS_HS_Sword", name="TwoHanded Sword Han-Sashael's"},
{ID="ks_chitin_dagger", name="Short Dagger Chitin"},
{ID="KS_Ebony_Scimitar", name="Sword Scimitar Ebony Elegant"},
{ID="ks_shani_knife", name="Knife Shani's"},
{ID="daedric halberd", name="Spear Halberd Daedric"},
{ID="silver shortsword_thelas", name="Short Sword of Repentance Silvr"},
{ID="HB_arrow_of_paralysis_00", name="Arrow of Pacify Ahemmusa"},
{ID="HB_arrow_of_paralysis_01", name="Arrow of Pacify Ahemmusa"},
{ID="rem_dwrv_arbalest", name="Crossbow Dwarven Arbalest"},
{ID="rem_re_crossbow", name="Crossbow Reinforced"},
{ID="rem_bone_arrow", name="Arrow Bone"},
{ID="rem_bone_bolt", name="Bolt Bone"},
{ID="rem_goblin_arrow", name="Arrow Goblin"},
{ID="rem_hunts_arrow", name="Arrow Huntsman's"},
{ID="rem_stalh_arrow", name="Arrow Stalhrim"},
{ID="rem_orcish_arrow", name="Arrow Orcish"},
{ID="rem_glass_dart", name="Thrown Dart Glass"},
{ID="rem_daedric_knife", name="Thrown Knife Daedric"},
{ID="rem_silver_knife", name="Thrown Knife Silver"},
{ID="rem_ebony_bolt", name="Bolt Ebony"},
{ID="rem_hunts_bow", name="Bow Long Huntsman's"},
{ID="rem_stalhrim_bow", name="Bow Long Stalhrim"},
{ID="rem_nordic_silver_bow", name="Bow Long Silver Nordic"},
{ID="rem_ebony_bow", name="Bow Long Ebony"},
{ID="rem_ebony_bolt_viper", name="Bolt Ebony of Viper"},
{ID="rem_ebony_bolt_bdeath", name="Bolt Ebony of Black Death"},
{ID="rem_ebony_bolt_rdeath", name="Bolt Ebony of Red Death"},
{ID="arrow_plume", name="Arrow Racer"},
{ID="arrow_plume_fire_01", name="Arrow Racer of Flaming"},
{ID="arrow_plume_frost_01", name="Arrow Racer of Freezing"},
{ID="arrow_plume_poison_01", name="Arrow Racer of Poison"},
{ID="arrow_plume_poison_02", name="Arrow Racer of Cruel Poison"},
{ID="arrow_plume_fire_02", name="Arrow Racer of Cruel Flaming"},
{ID="arrow_plume_frost_02", name="Arrow Racer of Cruel Freezing"},
{ID="arrow_glass_fire_01", name="Arrow Glass of Flaming"},
{ID="arrow_plume_fire_03", name="Arrow Racer of Dire Flaming"},
{ID="arrow_plume_frost_03", name="Arrow Racer of Dire Freezing"},
{ID="arrow_plume_poison_03", name="Arrow Racer of Dire Poison"},
{ID="arrow_glass_fire_02", name="Arrow Glass of Cruel Flaming"},
{ID="arrow_glass_fire_03", name="Arrow Glass of Dire Flaming"},
{ID="arrow_glass_frost_01", name="Arrow Glass Freezing"},
{ID="arrow_glass_frost_02", name="Arrow Glass of Cruel Freezing"},
{ID="arrow_glass_frost_03", name="Arrow Glass of Dire Freezing"},
{ID="arrow_glass_poison_01", name="Arrow Glass Poison"},
{ID="arrow_glass_poison_02", name="Arrow Glass of Cruel Poison"},
{ID="arrow_glass_poison_03", name="Arrow Glass of Dire Poison"},
{ID="arrow_plume_paralyse_01", name="Arrow Racer of Paralysis"},
{ID="arrow_glass", name="Arrow Glass"},
{ID="bolt_glass", name="Bolt Glass"},
{ID="bolt_glass_fire_01", name="Bolt Glass of Flaming"},
{ID="bolt_glass_fire_02", name="Bolt Glass of Cruel Flaming"},
{ID="bolt_glass_fire_03", name="Bolt Glass of Dire Flaming"},
{ID="bolt_glass_frost_01", name="Bolt Glass of Freezing"},
{ID="bolt_glass_frost_02", name="Bolt Glass of Cruel Freezing"},
{ID="bolt_glass_frost_03", name="Bolt Glass of Dire Freezing"},
{ID="bolt_plume", name="Bolt Racer"},
{ID="bolt_plume_fire_01", name="Bolt Racer of Flaming"},
{ID="bolt_plume_fire_02", name="Bolt Racer of Cruel Flaming"},
{ID="bolt_plume_fire_03", name="Bolt Racer of Dire Flaming"},
{ID="bolt_plume_frost_01", name="Bolt Racer of Freezing"},
{ID="bolt_plume_frost_02", name="Bolt Racer of Cruel Freezing"},
{ID="bolt_plume_frost_03", name="Bolt Racer of Dire Freezing"},
{ID="bolt_plume_poison_01", name="Bolt Racer of Poison"},
{ID="bolt_plume_poison_02", name="Bolt Racer of Cruel Poison"},
{ID="bolt_plume_poison_03", name="Bolt Racer of Dire Poison"},
{ID="bolt_glass_poison_01", name="Bolt Glass of Poison"},
{ID="bolt_glass_poison_02", name="Bolt Glass of Cruel Poison"},
{ID="bolt_glass_poison_03", name="Bolt Glass of Dire Poison"},
{ID="dart_plume", name="Thrown Dart Racer"},
{ID="dart_plume_fire_01", name="Thrown Dart Racer Flame"},
{ID="dart_plume_fire_02", name="Thrown Dart Racer Cruel Flame"},
{ID="dart_plume_fire_03", name="Thrown Dart Racer Dire Flame"},
{ID="dart_plume_frost_01", name="Thrown Dart Racer Frost"},
{ID="dart_plume_frost_02", name="Thrown Dart Racer Cruel Frost"},
{ID="dart_plume_frost_03", name="Thrown Dart Racer Dire Frost"},
{ID="dart_plume_poison_01", name="Thrown Dart Racer Poison"},
{ID="dart_plume_poison_02", name="Thrown Dart Racer Cruel Poison"},
{ID="dart_plume_poison_03", name="Thrown Dart Racer Dire Poison"},
{ID="dart_glass", name="Thrown Dart Glass"},
{ID="dart_glass_fire_01", name="Thrown Dart Glass Flame"},
{ID="dart_glass_fire_02", name="Thrown Dart Glass Cruel Flame"},
{ID="dart_glass_fire_03", name="Thrown Dart Glass Dire Flame"},
{ID="dart_glass_frost_01", name="Thrown Dart Glass Frost"},
{ID="dart_glass_frost_02", name="Thrown Dart Glass Cruel Frost"},
{ID="dart_glass_frost_03", name="Thrown Dart Glass Dire Frost"},
{ID="dart_glass_poison_01", name="Thrown Dart Glass Poison"},
{ID="dart_glass_poison_02", name="Thrown Dart Glass Cruel Poison"},
{ID="dart_glass_poison_03", name="Thrown Dart Glass Dire Poison"},
{ID="arrow_glass_paralyse_01", name="Arrow Glass of Paralysis"},
{ID="bolt_glass_paralyse_01", name="Bolt Glass of Paralysis"},
{ID="bolt_plume_paralyse_01", name="Bolt Racer of Paralysis"},
{ID="dart_glass_paralyse_01", name="Thrown Dart of Paralysis Glass"},
{ID="dart_plume_paralyse_01", name="Thrown Dart of Paralysis Racer"},
{ID="arrow_plume_shock_01", name="Arrow Racer of Shocking"},
{ID="arrow_glass_shock_01", name="Arrow Glass of Shocking"},
{ID="arrow_glass_shock_02", name="Arrow Glass of Cruel Shocking"},
{ID="arrow_glass_shock_03", name="Arrow Glass of Dire Shocking"},
{ID="arrow_plume_shock_02", name="Arrow Racer of Cruel Shocking"},
{ID="arrow_plume_shock_03", name="Arrow Racer of Dire Shocking"},
{ID="bolt_glass_shock_01", name="Bolt Glass of Shocking"},
{ID="bolt_glass_shock_02", name="Bolt Glass of Cruel Shocking"},
{ID="bolt_glass_shock_03", name="Bolt Glass of Dire Shocking"},
{ID="bolt_plume_shock_01", name="Bolt Glass of Shocking"},
{ID="bolt_plume_shock_02", name="Bolt Racer of Cruel Shocking"},
{ID="bolt_plume_shock_03", name="Bolt Racer of Dire Shocking"},
{ID="dart_glass_shock_01", name="Thrown Dart Glass Shock"},
{ID="dart_glass_shock_02", name="Thrown Dart Glass Cruel Shock"},
{ID="dart_glass_shock_03", name="Thrown Dart Glass Dire Shock"},
{ID="dart_plume_shock_01", name="Thrown Dart Racer Shock"},
{ID="dart_plume_shock_02", name="Thrown Dart Racer Cruel Shock"},
{ID="dart_plume_shock_03", name="Thrown Dart Racer Dire Shock"},
{ID="arrow_plume_cupid", name="Arrow Cupid's Racer"},
{ID="arrow_glass_cupid", name="Arrow Cupid's Glass"},
{ID="bolt_glass_cupid", name="Bolt Cupid's Glass"},
{ID="bolt_plume_cupid", name="Bolt Cupid's Racer"},
{ID="dart_glass_cupid", name="Thrown Cupid's Glass Dart"},
{ID="dart_plume_cupid", name="Thrown Cupid's Racer Dart"},
{ID="arrow_glass_magebane", name="Arrow Mage Bane Glass"},
{ID="arrow_plume_magebane", name="Arrow Mage Bane Racer"},
{ID="bolt_glass_magebane", name="Bolt Mage Bane Glass"},
{ID="bolt_plume_magebane", name="Bolt Mage Bane Racer"},
{ID="dart_glass_magebane", name="Thrown Dart Mage Bane Glass"},
{ID="dart_plume_magebane", name="Thrown Dart Mage Bane Racer"},
{ID="arrow_glass_fury", name="Arrow Furious Glass"},
{ID="arrow_plume_fury", name="Arrow Furious Racer"},
{ID="bolt_glass_fury", name="Bolt Furious Glass"},
{ID="bolt_plume_fury", name="Bolt Furious Racer"},
{ID="dart_glass_fury", name="Thrown Dart Furious Glass"},
{ID="dart_plume_fury", name="Thrown Dart Furious Racer"},
{ID="asy_cooking_cleaver_00", name="Cleaver Meat"},
{ID="asy_cooking_knife_00", name="Knife Cooking Large"},
{ID="asy_cooking_knife_01", name="Knife Cooking"},
{ID="asy_cooking_knife_02", name="Knife Cooking"},
{ID="asy_cooking_knife_03", name="Thrown Knife Cooking"},
{ID="MI_serpentine_blade", name="TwoHanded Might and Contrition"},
{ID="MI_ruby_dagger", name="Short Dagger Ruby"},
{ID="MI_ebony staff", name="Staff Ebony"},
{ID="wh_crossbow_silver", name="Crossbow Silver"},
{ID="wh_crossbow_ebony", name="Crossbow Ebony"},
{ID="wh_crossbow_daedric", name="Crossbow Daedric"},
{ID="wh_crossbow_bone", name="Crossbow Bonemold"},
{ID="wh_crossbow_iron", name="Crossbow Iron"},
{ID="wh_daedric_bolt", name="Bolt Daedric"},
{ID="wh_crossbow_glass", name="Crossbow Glass"},
{ID="wh_glass_bolt", name="Bolt Glass"},
{ID="wh_crossbow_orc", name="Crossbow Orcish"},
{ID="wh_ebony_bolt", name="Bolt Ebony"},
{ID="wh_dwemer_bolt", name="Bolt Dwemer"},
{ID="orcish trapper bolt", name="Bolt Uftum Trapper"},
{ID="steel pike", name="Spear Pike Steel"},
{ID="chitin pike", name="Spear Pike Chitin"},
{ID="glass pike", name="Spear Pike Glass"},
{ID="ebony pike", name="Spear Pike Ebony"},
{ID="iron pike", name="Spear Pike Iron"},
{ID="dwemer pike", name="Spear Pike Dwarven"},
{ID="daedric pike", name="Spear Pike Daedric"},
{ID="constance silver dagger", name="Short Dagger Silver Constance's"},
{ID="aa_zs_ivybow", name="Bow Ivy Constance's"},
{ID="aa_ebonyshort", name="Short Sword Ebony"},
{ID="aa_nordicsilverspear", name="Spear Silver Nordic"},
{ID="aa_nordicsilverspear_Throwing", name="Thrown Spear Silver Nordic"},
{ID="aa_nordic silver axe throwing", name="Thrown Axe Silver Nordic"},
{ID="aa_Wunderbar_B_A", name="Axe Wunderbar"},
{ID="aa_Black Steel Battle Axe", name="Axe Steel Black War"},
{ID="aa_Black Steel Hack Axe", name="Axe Steel Black Hack"},
{ID="aa_Fjorgrin Bow", name="Bow Fjorngrin's"},
{ID="aa_Nordic Oak Long Bow", name="Bow Long Oak Nordic"},
{ID="aa_Nordic Cedar Bow", name="Bow Long Cedar Nordic"},
{ID="aa_Nordic Golden Oak Lbow", name="Bow Long Golden Oak Nordic"},
{ID="aa_Whale Ivory Arrow", name="Arrow Ivory Horker"},
{ID="aa_steel warhammer_Clo Ti", name="Warhammer Closing Time"},
{ID="aa_Axe Black_2hand", name="Battle Axe Steel Black"},
{ID="aa_warhammer_Thor_Bjorg", name="Warhammer of Thorjan Bjorg"},
{ID="aa_warhammer_Thor_Bjorg_Light", name="Warhammer of Thorjan Bjorg"},
{ID="aa_Kinslayer", name="Sword Kinslayer"},
{ID="aa_Grundsword", name="Sword Dragonblade"},
{ID="aa_LisNordCedarBow", name="Bow Long Cedar Nordic"},
{ID="aa_ZsGnarlLongBow_01", name="Bow Long Gnarled Nordic"},
{ID="aa_Johansilvershortsword", name="Short Sword Silver Johan's"},
{ID="DEG_OJAI01_DaggerFr", name="Short Frost Stinger"},
{ID="DEG_OJAI02_SwordHA", name="Sword Long of Fiery Passion"},
{ID="_DEG_AF01_QueWeaponSw", name="Claymore Wraithburner"},
{ID="_DEG_AF02_WeapSkeGu01", name="Claymore Belvravel Ancestral"},
{ID="_DEG_AF03_QueWeaponAx", name="Battle Axe Mersplitter"},
{ID="_DEG_AF04_QueWeaponHam", name="War Maul Frost Mauler"},
{ID="_DEG_AF05_WeaponDagUni", name="Short Dagger Blindng Acrobatics"},
{ID="_DEG_AF06_WeaponAxeUni", name="Axe War of Fiery Personality"},
{ID="_DEG_AF08_WeapSkeGua02", name="Sword Sarethi Ancestral Blade"},
{ID="POT_GhostSword", name="TwoHanded Velothi Ghost Sword"},
{ID="ABtv_w_MoonReiver", name="TwoHanded Sword of Moon Reiver"},
{ID="ABtv_w_TelvanniSpear", name="Spear Verminous"},
{ID="ABtv_w_AcidSpear", name="Spear Chitin Acid Etched"},
{ID="ABtv_w_VolatileFlameArrow", name="Arrow Volatile of Flame"},
{ID="ABtv_w_BlackSword", name="Sword Blade of Eminent Ember"},
{ID="ABtm_w_GoldStClaymore", name="Claymore Mindcleaver"},
{ID="AB_w_ToolSmithHammer", name="Hammer Blacksmith's"},
{ID="AB_w_AdamRapier", name="Sword Rapier Adamantium"},
{ID="AB_w_DaedricRapier", name="Sword Rapier Daedric"},
{ID="AB_w_GlassRapier", name="Sword Rapier Glass"},
{ID="AB_w_GlassRapierDirFla", name="Sword Lunger Glass of Fire"},
{ID="AB_w_GlassRapierDirFro", name="Sword Lunger Glass of Frost"},
{ID="AB_w_GlassRapierDirSto", name="Sword Lunger Glass of Storm"},
{ID="AB_w_GlassRapierDirVip", name="Sword Lunger Silver of Viper"},
{ID="AB_w_IronRapier", name="Sword Rapier Iron"},
{ID="AB_w_IronRapierFla", name="Sword Lunger Iron of Flame"},
{ID="AB_w_IronRapierSha", name="Sword Lunger Iron of Shard"},
{ID="AB_w_IronRapierSpa", name="Sword Lunger Iron of Spark"},
{ID="AB_w_IronRapierVip", name="Sword Lunger Iron of Viper"},
{ID="AB_w_SilverRapier", name="Sword Rapier Silver"},
{ID="AB_w_SilverRapierCruFla", name="Sword Lunger Silver of Flame"},
{ID="AB_w_SilverRapierCruSha", name="Sword Lunger Silver of Shard"},
{ID="AB_w_SilverRapierCruSpa", name="Sword Lunger Silver of Spark"},
{ID="AB_w_SilverRapierCruVip", name="Sword Lunger Silver of Viper"},
{ID="AB_w_SteelRapier", name="Sword Rapier Steel"},
{ID="AB_w_SteelRapierCruFla", name="Sword Lunger Steel of Flame"},
{ID="AB_w_SteelRapierCruSha", name="Sword Lunger Steel of Shard"},
{ID="AB_w_SteelRapierCruSpa", name="Sword Lunger Steel of Spark"},
{ID="AB_w_SteelRapierCruVip", name="Sword Lunger Steel of Viper"},
{ID="AB_w_WoodClub", name="Blunt Club Wooden"},
}
