return {
    "aa_death_greaves",
    "aa_death_bracer_l",
    "aa_death_bracer_r",
    "aa_death_cuirassb",
    "aa_death_boots",
    "aa_deathdealer_cuirass",
    "aa_deathdealer_greaves",
    "aa_deathdealer_pauldron_l",
    "aa_deathdealer_pauldron_r",
    "aa_deathdealer_gauntlet_l",
    "aa_deathdealer_gauntlet_r",
    "aa_wooden_shield_crest",
    "aa_nin_cuirass 6",
    "aa_nin_pantss",
    "aa_nin_gloves_l",
    "aa_nin_gloves_r",
    "aa_nin_boots",
    "aa_nin_sleeves l",
    "aa_nin_sleeves r",
    "aa_savior_pauldronl",
    "aa_savior_pauldronr",
    "aa_savior_gauntletl",
    "aa_savior_gauntletr",
    "aa_savior_greaves",
    "aa_savior_boots",
    "aa_gondor_shirt_03",
    "aa_gondor_shirt_05",
    "aa_glad_shield_gladr",
    "aa_glad_shield_glad",
    "aa_glad_cuirass_glad2",
    "aa_hh_nord_greaves",
    "aa_hh_nordic_shield02",
    "aa_netch_pauld_r",
    "aa_netch_pauld_l",
    "aa_netch_helmet_symphony",
    "aa_netch_greaves",
    "aa_netch_gaunt_r",
    "aa_netch_gaunt_l",
    "aa_netch_boots",
    "aa_netch_boiledhelm",
    "aa_netch_boiled_cuir",
    "aa_red_hf_bracerl",
    "aa_red_hf_bracerr",
    "aa_red_bracerl",
    "aa_red_bracerr",
    "aa_hh_nord_pauld_r",
    "aa_hh_nord_pauld_l",
    "aa_hh_nord_boots",
    "aa_sorc_greaves",
    "aa_sorc_lbracer",
    "aa_sorc_boots",
    "aa_sorc_cuirass",
    "aa_sorc_lpauldron",
    "aa_sorc_rpauldron",
    "aa_sorc_helm",
    "aa_sorc_rbracer",
    "aa_falc_cuirass_leather_f",
    "aa_falc_rangersheild",
    "aa_falc_boots_leather_f",
    "aa_falc_coats",
    "aa_falc_grev_female_lu",
    "aa_ard3_boots",
    "aa_ard3_bracerl",
    "aa_ard3_bracerr",
    "aa_ard3_cuirass",
    "aa_ard3_gauntletl",
    "aa_ard3_gauntletr",
    "aa_ard3_greaves",
    "aa_ard3_pauldron2l",
    "aa_ard3_pauldron2r",
    "aa_ard3_pauldron3l",
    "aa_ard3_pauldron3r",
    "aa_ard3_pauldron4l",
    "aa_ard3_pauldron4r",
    "aa_mithril_ard3_pauldronl",
    "aa_ard3_pauldronr",
    "aa_jade_cuir",
    "aa_jade_pld_r",
"aa_jade_pld_l",
"aa_jade_boots",
"aa_jade_gaunt_l",
"aa_jade_gaunt_r",
"aa_jade_skirt",
"aa_sfg_helm",
"aa_sfg_boots",
"aa_sfg_cuirass",
"aa_sfg_gaunt_r",
"aa_sfg_gaunt_l",
"aa_sfg_greaves",
"aa_sfg_pauld_l",
"aa_sfg_pauld_r",
"aa_sfg_towershield",
"aa_assasin_hood",
"aa_assasin_mask",
"aa_aedric_crystal_cuiras",
"aa_aedric_crystal_paul_l",
"aa_aedric_crystal_pald_r",
"aa_aedric_crystal_greave",
"aa_aedric_crystal_boots",
"aa_aedric_crystal_gauntl",
"aa_aedric_crystal_gauntr",
"aa_aedric_crystal_helmet",
"aa_nin_shirt",
"aa_nin_pants",
"aa_nin_shoes",
"aa_nin_glovel",
"aa_nin_glover",
"aa_nin_sleevel",
"aa_nin_sleever",
"aa_nin3_shirt3",
"aa_nin3_sleeve3l",
"aa_nin3_sleeve3r",
"aa_nin3_shoes3",
"aa_nin3_glove3r",
"aa_nin3_glove3l",
"aa_nin3_pants3",
"aa_corprus_boots",
"aa_corprus_cuirass",
"aa_corprus_helm",
"aa_corprus_greaves",
"aa_corprus_pauldron_left",
"aa_corprus_pauldron_r",
"aa_corprus_bracer_left",
"aa_corprus_bracer_right",
"aa_corprus_shield",
"aa_mithril_boots",
"aa_mithril_bracer_ l",
"aa_mithril_bracer_r",
"aa_mithril_helm",
"aa_mithril_cuirass",
"aa_mithril_greaves",
"aa_mithril_pald_l",
"aa_mithril_plad_r",
"aa_shalk boots",
"aa_shalk cuirass",
"aa_shalk greaves",
"aa_shalk guantlet - left",
"aa_shalk guantlet - right",
"aa_shalk pauldron - left",
"aa_shalk pauldron - right",
"aa_wood_boot_gnd",
"aa_wood_cuirass_gnd",
"aa_wood_gauntlet_right",
"aa_wood_gauntlet_left",
"aa_wood_greave_gnd",
"aa_wood_pauldron_gnd",
"aa_wood_pauldron_gnd2",
"aa_wood_shield",
"aa_stalker boots",
"aa_stalker cuirass",
"aa_stalker glove left",
"aa_stalker glove right",
"aa_stalker greaves",
"aa_stalker pauldron left",
"aa_stalker pauldron r",
"aa_stalker hood ",
"aa_stalker mask",
"aa_ws_pauldron_l2",
"aa_ws_helm",
"aa_ws_cuir",
"aa_ws_boots",
"aa_ws_greaves",
"aa_ws_gauntlet_l",
"aa_ws_gauntlet_r",
"aa_ws_pauldron_r2",
"aa_darkglass_boots",
"aa_darkglass_gauntlet_l",
"aa_darkglass_gauntlet_r",
"aa_darkglass_helm",
"aa_darkglass_pauldron_l",
"aa_darkglass_pauldron_r",
"aa_chitin boots",
"aa_chitin cuirass",
"aa_chitin greaves",
"aa_chitin guantlet - l",
"aa_chitin guantlet - r",
"aa_chitin pauldron - l",
"aa_chitin pauldron - r",
"aa_dkbrthrh boots",
"aa_dkbrthrh cuirass_jn",
"aa_dkbrthrh cuirass_op",
"aa_dkbrthrh cuirass_pu",
"aa_dkbrthrh cuirass_wb",
"aa_dkbrthrh greaves",
"aa_dkbrthrh helm",
"aa_dkbrthrh pauldron_l",
"aa_dkbrthrh pauldron_r",
"aa_mithril_cuirass_f",
"aa_mithril_boots_f",
"aa_mithril_greaves_f",
"aa_mithril_pald_l_f",
"aa_mithril_pald_r_f",
"aa_falc_boots_leather_m",
"aa_falc_grev_male",
"aa_falc_skirt_leather",
"aa_falc_cuirass_m",
"aa_guard_cuirass",
"aa_dragonbone_boots_unique",
"aa_nordic_ringmail_gaunt_l",
"aa_nordic_ringmail_gaunt_r",
"aa_nordic_ringmail_pauld_l",
"aa_nordic_ringmail_pauld_r",
"aa_silver_dukesguard_boots",
"aa_silver_dukesguard_greav",
"aa_hh_nord_ringmail_cuirass",
"aa_silver_dukesguard_pa_l",
"aa_silver_dukesguard_pa_r",
"aa_pikeman_cuirasshh",
"aa_pikeman_greaveshh",
"aa_akatosh_gauntlet_left",
"aa_akatosh_pauldron_left",
"aa_dibella_gauntlet_left",
"aa_dibella_pauldron_left",
"aa_kynareth_gauntl_right",
"aa_kynareth_pauldr_right",
"aa_dwemer_pauldron_right",
"aa_emerald_ym_gaunt_right",
"aa_emerald_ym_pauld_right",
"aa_chain_glove_gnd_right",
"aa_glad_pauldron_glad(cm)",
"aa_glad_pauldron_glad(st)",
"aa_japanese_ glove_right",
"aa_indoril pauldron right",
"aa_indoril right gauntlet",
"aa_dragonbone_gauntlet_l",
"aa_dragonbone_gauntlet_r",
"aa_dragonbone_pauldron_l",
"aa_dragonbone_pauldron_r",
"aa_ebony_pauldron_right",
"aa_pikeman_pauldr",
"aa_arkay right pauldron",
"aa_arkay_gauntlet_right",
"aa_kynareth_pauldr_left",
"aa_maran_pauldron_right",
"aa_dwemer_pauldron_left",
"aa_emerald_ym_gaunt_left",
"aa_emerald_ym_pauld_left",
"aa_altm_pauldron_right",
"aa_chain_glove_gnd_left",
"aa_ebonbone_bracer_right",
"aa_japanese_ glove_left",
"aa_japanese_ pauldron_l",
"aa_japanese_ pauldron_r",
"aa_dndoril_greaves",
"aa_indoril left gauntlet",
"aa_indoril pauldron left",
"aa_lords_pauldron_right",
"aa_silver_dukesguard_gauntlet_l",
"aa_silver_dukesguard_gauntlet_r",
"aa_ebony_pauldron_left",
"aa_arkay left pauldron",
"aa_arkay_gauntlet_left",
"aa_kynareth_gauntlet_l",
"aa_kynareth_open_helm2",
"aa_maran_pauldron_left",
"aa_goblin_bracer_right",
"aa_dwemer_bracer_right",
"aa_wmindoril_gauntlet_l",
"aa_wmindoril_gauntlet_r",
"aa_wmindoril_pauldron_l",
"aa_wmindoril_pauldron_r",
"aa_altm_pauldron_left",
"aa_durzog_bracer_right",
"aa_rust_pauldron_right",
"aa_ebonbone_bracer_left",
"aa_helsethguard_shield1",
"aa_helsethguard_shield2",
"aa_helsethguard_shield3",
"aa_ebon_plate_pa_right",
"aa_lords_pauldron_left",
"aa_ebony_bracer_right",
"aa_orcshield_sm101",
"aa_dreugh_cuirass_hh",
"aa_pikeman_helmhh",
"aa_akatosh_gauntlet_r",
"aa_akatosh_pauldron_r",
"aa_dibella_gauntlet_r",
"aa_dibella_pauldron_r",
"aa_kynareth_open_helm",
"aa_arcanepauldronright",
"aa_goblin_bracer_left",
"aa_goblin_paul_1right",
"aa_goblin_paul_2right",
"aa_goblin_paul_3right",
"aa_goblin_paul_4right",
"aa_dwemer_bracer_left",
"aa_morkeleb_gauntlet_l",
"aa_morkeleb_gauntlet_r",
"aa_ymrarmor_gauntlet_l",
"aa_ymrarmor_gauntlet_r",
"aa_ymrarmor_pauldron_l",
"aa_ymrarmor_pauldron_r",
"aa_chain_pa_gnd_right",
"aa_durzog_bracer_left",
"aa_durzog_helmet_open",
"aa_warlock_lrerebrace",
"aa_warlock_rrerebrace",
"aa_dreugh_shield2",
"aa_tbg_gauntlet_rgnd",
"aa_rust_pauldron_left",
"aa_ebonbone_l_pauldron",
"aa_ebonbone_l_spaulder",
"aa_ebonbone_r_pauldron",
"aa_ebonbone_r_spaulder",
"aa_gloomarm_gauntlet_l",
"aa_gloomarm_gauntlet_r",
"aa_gloomarm_pauldron_l",
"aa_gloomarm_pauldron_r",
"aa_dragonbone_greaves",
"aa_ebon_plate_pa_left",
"aa_silver_dukesguard_gauntlet_s",
"aa_ice minion_shld1",
"aa_ice minion_shld2",
"aa_ebony_bracer_left",
"aa_ebony_towershield",
"aa_akatosh_shield_01",
"aa_arkay_towershield",
"aa_dibella_greaves_2",
"aa_jg_gauntlet_right",
"aa_jg_pauldron_right",
"aa_arcanepauldronleft",
"aa_goblin_claw_right",
"aa_goblin_paul_1left",
"aa_goblin_paul_2left",
"aa_goblin_paul_3left",
"aa_goblin_paul_4left",
"aa_emerald_ym_cuirass",
"aa_emerald_ym_greaves",
"aa_ymarmor_gauntlet_l",
"aa_ymarmor_gauntlet_r",
"aa_ymarmor_pauldron_l",
"aa_ymarmor_pauldron_r",
"aa_chain_pa_gnd_left",
"aa_durzog_pauldron_l",
"aa_durzog_pauldron_r",
"aa_leather_lpauldron",
"aa_leather_rpauldron",
"aa_bronze_gauntlet_l",
"aa_bronze_gauntlet_r",
"aa_bronzetowershield",
"aa_nih5_greaves_saya",
"aa_tbg_gauntlet_gnd",
"aa_rust_bracer_right",
"aa_sam_r_pauldron  2",
"aa_dndoril_gauntlet_l",
"aa_dndoril_gauntlet_r",
"aa_dndoril_pauldron_l",
"aa_dndoril_pauldron_r",
"aa_deathdealer_boots",
"aa_savior_shield",
"aa_orcpauldron_l",
"aa_orcpauldron_r",
"aa_jg_gauntlet_left",
"aa_jg_greaves_plate",
"aa_jg_pauldron_left",
"aa_kynareth_cuirass",
"aa_kynareth_greaves",
"aa_arcanebracerright",
"aa_goblin_claw_left",
"aa_dwemer_helm_open",
"aa_gondor_gauntlet_l",
"aa_gondor_gauntlet_r",
"aa_gondor_pauldron_l",
"aa_gondor_pauldron_r",
"aa_emerald_ym_helm02",
"aa_wmindoril_cuirass",
"aa_wmindoril_greaves",
"aa_altm_gauntlet_l",
"aa_altm_gauntlet_r",
"aa_guard_gauntlet_l",
"aa_guard_gauntlet_r",
"aa_guard_pauldron_l",
"aa_guard_pauldron_r",
"aa_hkg_fists_gauntlet_l",
"aa_hkg_fists_gauntlet_r",
"aa_hku_fists_gauntlet_l",
"aa_hku_fists_gauntlet_r",
"aa_bronze_pauldronl",
"aa_bronze_pauldronr",
"aa_nih5_glove_right",
"aa_tbg_bracer_rgnd",
"aa_tbg_cuirass_gnd",
"aa_tbg_greaves_gnd",
"aa_tbg_pauld2_rgnd",
"aa_rust_bracer_left",
"aa_sam_l_pauldron 2",
"aa_japanese_cuirass",
"aa_japanese_greaves",
"aa_indoril helmet_open",
"aa_dragonbon helm",
"aa_dragonbone_shld",
"aa_newtscale_shld",
"aa_nordic_ringmail_shield",
"aa_ruby_pauldron_l",
"aa_ruby_pauldron_r",
"aa_ard2_pauldron2l",
"aa_ard2_pauldron2r",
"aa_ard2_pauldron3l",
"aa_ard2_pauldron3r",
"aa_ard2_pauldron4l",
"aa_ard2_pauldron4r",
"aa_ard4_pauldron2l",
"aa_ard4_pauldron2r",
"aa_ard4_pauldron3l",
"aa_ard4_pauldron3r",
"aa_ard4_pauldron4l",
"aa_ard4_pauldron4r",
"aa_akatosh_cuirass",
"aa_akatosh_greaves",
"aa_dibella_cuirass",
"aa_kynareth_shield",
"aa_arcanebracerleft",
"aa_gondorcuirass_01",
"aa_emerald_ym_boots",
"aa_emerald_ymshield",
"aa_morkeleb_cuirass",
"aa_morkeleb_greaves",
"aa_morkeleb_pauld_l",
"aa_morkeleb_pauld_r",
"aa_wmindoril_helmet",
"aa_wmindoril_shield",
"aa_ymrarmor_cuirass",
"aa_ymrarmor_greaves",
"aa_chain_boots_gnd",
"aa_warlock_stetson",
"aa_deathdealer_helm",
"aa_leather_cuirass",
"aa_leather_greaves",
"aa_leather_lbracer",
"aa_leather_rbracer",
"aa_bronze_bracer l",
"aa_bronze_bracer r",
"aa_nih5_glove_left",
"aa_nih5_kabuto_wo_",
"aa_nih5_sode_right",
"aa_tbg_bracer_gnd",
"aa_tbg_pauld2_gnd",
"aa_ebonbone_cuirass",
"aa_ebonbone_greaves",
"aa_gloomarm_cuirass",
"aa_gloomarm_greaves",
"aa_sam_l_pauldron ",
"aa_sam_r_pauldron ",
"aa_japanese_ boots",
"aa_silver_dukesguard_gauntlet_h",
"aa_savior_helmet",
"aa_orcbracer_l",
"aa_orcbracer_r",
"aa_ard2_gauntletl",
"aa_ard2_gauntletr",
"aa_ard2_pauldronl",
"aa_ard2_pauldronr",
"aa_ard4_gauntletl",
"aa_ard4_gauntletr",
"aa_ard4_pauldronl",
"aa_ard4_pauldronr",
"aa_akatosh_shield",
"aa_dibella_helmet",
"aa_dibella_shield",
"aa_kynareth_boots",
"aa_dwemer_cuirass",
"aa_dwemer_greaves",
"aa_rohcm_gauntletr",
"aa_emerald_ym_helm",
"aa_morkeleb_helmet",
"aa_morkeleb_shield",
"aa_wmindoril_boots",
"aa_ymarmor_cuirass",
"aa_ymarmor_greaves",
"aa_ymrarmor_shield",
"aa_arach_greaves",
"aa_arach_pld_l",
"aa_arach_pld_r",
"aa_durzog_cuirass",
"aa_durzog_greaves",
"aa_warlock_cuisse",
"aa_ard_pauldron2l",
"aa_ard_pauldron2r",
"aa_ard_pauldron3l",
"aa_ard_pauldron3r",
"aa_ard_pauldron4l",
"aa_ard_pauldron4r",
"aa_bronze_cuirass",
"aa_bronze_greaves",
"aa_nih5_sode_left",
"aa_tbg_boots_gnd",
"aa_ebonbone_crowny",
"aa_ebonbone_shield",
"aa_sam_l_gauntlet",
"aa_sam_r_gauntlet",
"aa_gondor_glove_l",
"aa_gondor_glove_r",
"aa_gondor_shirt_02",
"aa_dndoril_cuirass",
"aa_indoril cuirass",
"aa_indoril greaves",
"aa_ebony_cuirass",
"aa_ebony_greaves",
"aa_orcgreaves",
"aa_ebony_shield_round_hh",
"aa_akatosh_boots",
"aa_arkay_cuirass",
"aa_arkay_greaves",
"aa_dibella_boots",
"aa_kynareth_helm",
"aa_maran_cuirass",
"aa_gondor_greaves",
"aa_ymarmor_shield",
"aa_ymrarmor_boots",
"aa_altm_cuirass",
"aa_altm_greaves",
"aa_guard_greaves",
"aa_arach_cuir",
"aa_durzog_helmet",
"aa_warlock_aegis",
"aa_warlock_boots",
"aa_warlock_lhand",
"aa_warlock_rhand",
"aa_ghob p gauntlet l",
"aa_ghob p gauntlet r",
"aa_ghob p pauldron l",
"aa_ghob p pauldron r",
"aa_ard_gauntletl",
"aa_ard_gauntletr",
"aa_ard_pauldronl",
"aa_ard_pauldronr",
"aa_leather_boots",
"aa_man_gauntletl",
"aa_man_gauntletr",
"aa_man_pauldronl",
"aa_man_pauldronr",
"aa_asent_cuirass",
"aa_asent_gaunt_l",
"aa_asent_gaunt_r",
"aa_asent_greaves",
"aa_asent_pauld_l",
"aa_asent_pauld_r",
"aa_tbg_mask_gnd",
"aa_ebonbone_boots",
"aa_gloomarm_boots",
"aa_dag_pauldron_l",
"aa_dag_pauldron_r",
"aa_sam_cuirass 5",
"aa_japanese_helm",
"aa_indoril helmet",
"aa_indoril shield",
"aa_ruby_cuirass",
"aa_ruby_glove_l",
"aa_ruby_glove_r",
"aa_ruby_greaves",
"aa_ard2_bracerl",
"aa_ard2_bracerr",
"aa_ard2_cuirass",
"aa_ard2_greaves",
"aa_ard4_bracerl",
"aa_ard4_bracerr",
"aa_ard4_cuirass",
"aa_ard4_greaves",
"aa_akatosh_helm",
"aa_maran_shield",
"aa_arcanecuirass",
"aa_arcanegreaves",
"aa_br_guantletl",
"aa_dwemer_boots",
"aa_rohcm_grieves",
"aa_morkeleb_boot",
"aa_ymarmor_boots",
"aa_ymrarmor_helm",
"aa_altm_shield",
"aa_chain_gr_gnd",
"aa_chain_helmet",
"aa_arach_boots",
"aa_durzog_boots",
"aa_bronze_boots",
"aa_nih5_kabuto_",
"aa_rust_cuirass",
"aa_rust_greaves",
"aa_indoril boots",
"aa_dndoril_shield_elited",
"aa_orcarmor",
"aa_orcboots",
"aa_ruby_shield",
"aa_arkay boots",
"aa_maran_boots",
"aa_pr_bracer_l",
"aa_pr_bracer_r",
"aa_arcaneshield",
"aa_goblin_boots",
"aa_goblin_helm",
"aa_br_pauld(r)",
"aa_dwemer_helm",
"aa_gondor_boots",
"aa_rohcm_pauldronl",
"aa_rohcm_pauldronr",
"aa_ymarmor_helm",
"aa_altm_boots",
"aa_chain_c_gnd",
"aa_guard_boots",
"aa_arach_helm",
"aa_ard_bracerl",
"aa_ard_bracerr",
"aa_ard_cuirass",
"aa_ard_greaves",
"aa_man_cuirass",
"aa_man_greaves",
"aa_asent_boots",
"aa_sam_cuirass",
"aa_sam_greaves",
"aa_dndoril_boot",
"aa_dndoril_helm",
"aa_dndoril_helm_d",
"aa_ebony_helm_panoplies",
"aa_orchelm",
"aa_ruby_boots",
"aa_ard2_boots",
"aa_ard4_boots",
"aa_arkay_helm",
"aa_jg_cuirass",
"aa_jg_greaves",
"aa_maran_helm",
"aa_pr_cuirass",
"aa_pr_pauld_l",
"aa_pr_pauld_r",
"aa_arcaneboots",
"aa_br_cuirass",
"aa_br_greaves",
"aa_rohcm_boots",
"aa_guard_mask",
"aa_ghob p cuirass",
"aa_ghob p greaves",
"aa_hkg_pauldron_l",
"aa_hkg_pauldron_r",
"aa_hku_pauldron_l",
"aa_hku_pauldron_r",
"aa_man_shield",
"aa_rust boots",
"aa_dag_cuirass",
"aa_dag_greaves",
"aa_dag_helm_01",
"aa_dag_helm_02",
"aa_dag_helm_03",
"aa_dag_shield1",
"aa_sam_helmet",
"aa_ruby_helm",
"aa_jg_shield",
"aa_pr_shield",
"aa_arcanehelm",
"aa_br_guantr",
"aa_br_pauldl",
"aa_ghob p shield",
"aa_ard_boots",
"aa_ard_helm1",
"aa_man_boots",
"aa_nih_boots",
"aa_rust_helm",
"aa_sam_boots",
"aa_jg_boots",
"aa_pr_boots",
"aa_pr_skirt",
"aa_br_boots",
"aa_ghob p boots",
"aa_man_helm",
"aa_jg_helm",
"aa_pr_helm",
"aa_br_helm",
"aa_rohcm_cuirass",
"aa_ghob p helm",
"aa_hkg_cuirass",
"aa_hkg_greaves",
"aa_hku_cuirass",
"aa_hku_greaves",
"aa_nih5_do",
"aa_hkg_helmet",
"aa_hku_helmet",
"aa_hkg_boots",
"aa_hkg_crown",
"aa_hku_boots",
"aa_hku_crown",
"aa_glad_boots_glad(l)",
"aa_glad_boots_glad(e)",
"aa_dragonbone_leg",
"aa_adamantium_towershield",
"aa_ebony_boots",
"aa_pikeman_pauldl",
"aa_maran_greaves",
"aa_rohcm_gauntletl",
"aa_glad_cuirass_glad",
"orcish_cuirass@d",
"aa_imperial right gauntlet_d@",
"aa_imperial cuirass_armor_d2",
"aa_imperial left gauntlet_d@",
"aa_imperial left pauldron_d@",
"aa_imperial_greaves_d@",
"aa_adamantium_shield_@x2",
"aa_adamantium_pauldron_r_dark",
"aa_adamantium_bracer_r_dark",
"aa_adamantium_pauldron_l_dark",
"aa_adamantium_bracer_l_dark",
"aa_addamantium_helm_st_@x",
"aa_adamantium_helm_dark",
"aa_adamantium_greaves_dark",
"aa_adamantium_cuirass_dark",
"aa_adamantium boots_dark",
"aa_imperial shield_@6_d",
"aa_imperial right pauldron_d@",
"aa_imperial boots_d@",
"aa_chitin pauldron - right_old",
"aa_chitin pauldron - left_old",
"aa_chitin helm_old",
"aa_chitin guantlet - right_old",
"aa_chitin guantlet - left_old",
"aa_chitin greaves_old",
"aa_chitin cuirass_old",
"aa_chitin boots_old",
"aa_dbh_pauldron_r",
"aa_dbh_gauntlet_r",
"aa_dbh_pauldron_l",
"aa_dbh_gauntlet_l",
"aa_dbh_helm_st3",
"aa_dbh_greaves",
"aa_dbh_cuirass_up3",
"aa_dbh_boots",
"aa_greatbone_bracer_right_@x",
"aa_greatbone_pauldron_r_@x",
"aa_greatbone_bracer_left_@x",
"aa_greatbone_pauldron_l_@x",
"aa_greatbone_helm_@x",
"aa_greatbone_greaves_@x",
"aa_greatbone_cuirass_@x",
"aa_greatbone_boots_@x",
"aa_ebony_pl_right_olddanmer_@x",
"aa_ebony_br_right_olddanmer_@x",
"aa_ebony_pl_left_olddanmer_@x",
"aa_ebony_br_left_olddanmer_@x",
"aa_ebony_greaves_olddanmer_@x",
"aa_ebony_boots_olddanmer_@x",
"aa_ebony_shield_olddanmer_@x",
"aa_ebony_cuirass_olddanmer_@x",
"aa_ebony_bracer_right_f@",
"aa_ebony_pauldron_right_f@",
"aa_ebony_pauldron_left_f@",
"aa_ebony_bracer_left_f@",
"aa_ebony_greaves_f@",
"aa_ebony_cuirass_f@",
"aa_ebony_closed_helm_f@",
"aa_ebony_boots_f@",
"aa_dw_meduim_q_ya_griv",
"aa_dw_meduim_q_ya_r_pl",
"aa_dw_meduim_q_ya_l_pl",
"aa_dw_meduim_q_ya_r_br",
"aa_dw_meduim_q_ya_sh",
"aa_dw_meduim_q_ya_l_br",
"aa_dw_meduim_q_ya_bt",
"aa_dw_meduim_q_ya_hl",
"aa_dw_meduim_q_ya_cir",
"aa_dragonbone_cuirass",
}
