return {
    "agent",
    "akatosh",
    "akaviri scout",
    "altmeri",
    "ambermatrix",
    "ancient bronze",
    "arachnus",
    "arcane",
    "ardeas",
    "arkay",
    "armored",
    "assassin",
    "black",
    "boukyaku",
    "brass god",
    "breasal",
    "budoka no",
    "captain",
    "chieftain",
    "crimson cross",
    "crystal",
    "dark",
    "death",
    "deathdealer",
    "dibella",
    "dragonbone",
    "dreugh lord",
    "dukes guard",
    "dumac",
    "duru-balsan",
    "durzog",
    "emerald",
    "falconer",
    "flesh",
    "gladiator",
    "gloom",
    "goblin",
    "golden",
    "gondor",
    "harmony",
    "heavy",
    "illuminatus",
    "jet & gold",
    "kynareth",
    "lord's",
    "mantodea's",
    "maran",
    "mithril",
    "morkeleb",
    "nee'enamor",
    "noble",
    "nord",
    "pikeman",
    "praetorian",
    "red",
    "riekling",
    "ruby",
    "russet",
    "rusty",
    "senche",
    "sentinel's",
    "shalk",
    "shu officer",
    "sicarian",
    "silver flame",
    "stalker",
    "treated",
    "tsaesci",
    "unholy",
    "warlock's",
    "warmaster",
    "wood",
    "wooden",
    "ymsidril",
}