return {
	"_ar_abugshield_01",
	"_ar_abugshield_02",
	"_ar_abugshield_03",
	"_ar_abugshield_04",
	"_ar_abugshield_61",
	"_ar_abugshield_62",
	"_ar_abugshield_63",
	"_ar_abugshield_64",
	"_ar_chitin greaves",
	"_ar_chitin pauldron - left",
	"_ar_chitin pauldron - right",
	"_ar_neckgarb",
	"_ar_netch_leather_greaves",
	"_ar_netch_leather_pauldron_l",
	"_ar_netch_leather_pauldron_r",
	"_ar_pauldron left",
	"_ar_pauldron right",
	"_arhlaalu",
	"_arimpbattlemage",
	"_arimpofficial",
	"_arnightblade",
	"_arredoran",
	"_arspellsword",
	"_artelvanni",
	"_ashlr_lbbrac_1",
	"_ashlr_lbbrac_1r",
	"_ashlr_lbbrac_2",
	"_ashlr_lbbrac_2r",
	"_ashlr_lbbrac_3",
	"_ashlr_lbbrac_3r",
	"_ashlr_lbcuirass1",
	"_ashlr_lbcuirass2",
	"_ashlr_lbcuirass3",
	"_ashlr_lbcuirass4",
	"_ashlr_lbpauldron_1",
	"_ashlr_lbpauldron_1r",
	"_ashlr_lbpauldron_2",
	"_ashlr_lbpauldron_2r",
	"_rv_archnecrohood",
	"_rv_archnecromask",
	"_rv_necrohood",
	"_rv_necromask",
	"_rv_netchimans cap",
	"ash_bonemold_war_helm",
	"ash_client_robe_gnd",
	"ash_tr_client_helm",
	"bm nordic silver longsword",
	"bonemold_cuirass",
	"chitin boots",
	"chitin boots n",
	"chitin bracer - left",
	"chitin bracer - right",
	"chitin cuirass",
	"chitin cuirass ash",
	"chitin cuirass ba",
	"chitin cuirass n",
	"chitin cuirass r",
	"chitin cuirass s",
	"chitin greaves",
	"chitin guantlet - left",
	"chitin guantlet - right",
	"chitin helm",
	"chitin pauldron - left",
	"chitin pauldron - left ash",
	"chitin pauldron - left ba",
	"chitin pauldron - left r",
	"chitin pauldron - right",
	"chitin pauldron - right ash",
	"chitin pauldron - right ba",
	"chitin pauldron - right r",
	"chitin_mask_helm",
	"chitin_shield",
	"chitin_towershield",
	"daedric dagger",
	"daedric warhammer",
	"dreugh_cuirass",
	"ebony dai-katana",
	"ebony katana",
	"ebony tanto",
	"ebony wakizashi",
	"glass claymore",
	"glass dagger",
	"imperial_chain_greaves",
	"imperial_chain_pauldron_left",
	"imperial_chain_pauldron_right",
	"imperial_studded_gauntlet_l",
	"imperial_studded_gauntlet_r",
	"mwc_a_de_brcrl_mwc1_3_g",
	"mwc_a_de_brcrl_mwc2_3_g",
	"mwc_a_de_brcrl_mwc3_0_g",
	"mwc_a_de_brcrl_mwc3_1_g",
	"mwc_a_de_brcrl_mwc4_3_g",
	"mwc_a_de_brcrr_mwc1_3_g",
	"mwc_a_de_brcrr_mwc2_3_g",
	"mwc_a_de_brcrr_mwc3_0_g",
	"mwc_a_de_brcrr_mwc3_1_g",
	"mwc_a_de_brcrr_mwc4_3_g",
	"mwc_a_de_bt_mwc1_0_gnd",
	"mwc_a_de_bt_mwc1_0a_gnd",
	"mwc_a_de_bt_mwc1_0b_gnd",
	"mwc_a_de_cuir_mwc1_1_gnd",
	"mwc_a_de_cuir_mwc2_6_g",
	"mwc_a_de_cuir_mwc2r_0_g",
	"mwc_a_de_cuir_mwc3_10_g",
	"mwc_a_de_cuir_mwc4_1_gnd",
	"mwc_a_de_cuir_mwc4_2_gnd",
	"mwc_a_de_cuir_mwc5_5_gnd",
	"mwc_a_de_helm_mwc1_4a_g",
	"mwc_a_de_helm_mwc2_0_g",
	"mwc_a_de_helm_mwc2_1_g",
	"mwc_a_de_helm_mwc7_2a_g",
	"mwc_a_de_helm_mwc7_2b_g",
	"mwc_a_de_helm_mwc7_2c_g",
	"mwc_a_de_pldcll_mwc2_2a_g",
	"mwc_a_de_pldcll_mwc2_3a_g",
	"mwc_a_de_pldcll_mwc3_0_g",
	"mwc_a_de_pldcll_mwc3_2_g",
	"mwc_a_de_pldcll_mwc3_3_g",
	"mwc_a_de_pldcll_mwc3_4h_g",
	"mwc_a_de_pldcll_mwc4_6_g",
	"mwc_a_de_pldcll_mwc4_8_g",
	"mwc_a_de_pldcll_mwc5_0_g",
	"mwc_a_de_pldcll_mwc5_1a_g",
	"mwc_a_de_pldclr_mwc2_2a_g",
	"mwc_a_de_pldclr_mwc2_3a_g",
	"mwc_a_de_pldclr_mwc3_0_g",
	"mwc_a_de_pldclr_mwc3_2_g",
	"mwc_a_de_pldclr_mwc3_3_g",
	"mwc_a_de_pldclr_mwc3_4h_g",
	"mwc_a_de_pldclr_mwc4_6_g",
	"mwc_a_de_pldclr_mwc4_8_g",
	"mwc_a_de_pldclr_mwc5_0_g",
	"mwc_a_de_pldclr_mwc5_1a_g",
	"mwc_a_de_pldual_mwc1_2_g",
	"mwc_a_de_pldual_mwc2_2_g",
	"mwc_a_de_pldual_mwc2_4_g",
	"mwc_a_de_pldual_mwc4_6_g",
	"mwc_a_de_plduar_mwc1_2_g",
	"mwc_a_de_plduar_mwc2_2_g",
	"mwc_a_de_plduar_mwc2_4_g",
	"mwc_a_de_plduar_mwc4_6_g",
	"mwc_a_de_shield_mwc1_2a_g",
	"mwc_a_de_shield_mwc2_1_g",
	"mwc_w_halberd_mwc1_2",
	"mwc_w_ssword_mwc0_2",
	"mwc_w_sword_mwc10a",
	"mwc_w_sword_mwc7",
	"mwc_w_sword_mwc7a",
	"netch_leather_boots",
	"netch_leather_cuirass",
	"netch_leather_greaves",
	"netch_leather_pauldron_left",
	"netch_leather_pauldron_right",
	"nordic claymore",
	"rdaa_a_de_bt_mwc1_5_gnd",
	"rdaa_a_de_bt_mwc3_1_gnd",
	"rdaa_a_de_c_mwc1_5f_gnd",
	"rdaa_a_de_cuir_mwc1_2_gnd",
	"rdaa_a_de_cuir_mwc1_2egnd",
	"rdaa_a_de_cuir_mwc1_5_gnd",
	"rdaa_a_de_cuir_mwc2_10a_gnd",
	"rdaa_a_de_cuir_mwc2_10b_gnd",
	"rdaa_a_de_cuir_mwc2_9_gnd",
	"rdaa_a_de_cuir_mwc2_9d_gnd",
	"rdaa_a_de_cuir_mwc3_10f_g",
	"rdaa_a_de_cuir_mwc_12_5_gnd",
	"rdaa_a_de_gntl_mwc12_gnd",
	"rdaa_a_de_gntl_mwc12a_gnd",
	"rdaa_a_de_gntl_mwc12c_gnd",
	"rdaa_a_de_gntr_mwc12_gnd",
	"rdaa_a_de_gntr_mwc12a_gnd",
	"rdaa_a_de_gntr_mwc12c_gnd",
	"rdaa_a_de_helm_mwc2_3b_gnd",
	"rdaa_a_de_helm_mwc9_2c_gnd",
	"rdaa_a_de_pldcll_mwc10_5",
	"rdaa_a_de_pldcll_mwc10_6",
	"rdaa_a_de_pldcll_mwc11_gnd",
	"rdaa_a_de_pldcll_mwc11b_gnd",
	"rdaa_a_de_pldcll_mwc3_4j",
	"rdaa_a_de_pldcll_mwc3_4jj",
	"rdaa_a_de_pldcll_mwc3_5aa",
	"rdaa_a_de_pldcll_mwc3_5b",
	"rdaa_a_de_pldcll_mwc3_5c",
	"rdaa_a_de_pldcll_mwc4_9e_gnd",
	"rdaa_a_de_pldcll_mwc4_9f_gnd",
	"rdaa_a_de_pldclr_mwc10_5",
	"rdaa_a_de_pldclr_mwc10_6",
	"rdaa_a_de_pldclr_mwc11_gnd",
	"rdaa_a_de_pldclr_mwc11b_gnd",
	"rdaa_a_de_pldclr_mwc3_4j",
	"rdaa_a_de_pldclr_mwc3_4jj",
	"rdaa_a_de_pldclr_mwc3_5aa",
	"rdaa_a_de_pldclr_mwc3_5b",
	"rdaa_a_de_pldclr_mwc3_5c",
	"rdaa_a_de_pldclr_mwc4_9e_gnd",
	"rdaa_a_de_pldclr_mwc4_9f_gnd",
	"rdaa_a_de_pldual_mwc1_2",
	"rdaa_a_de_pldual_mwc2_5a",
	"rdaa_a_de_pldual_mwc_cr2",
	"rdaa_a_de_pldual_mwc_cr5d",
	"rdaa_a_de_plduar_mwc1_2",
	"rdaa_a_de_plduar_mwc2_5a",
	"rdaa_a_de_plduar_mwc_cr2",
	"rdaa_a_de_plduar_mwc_cr5d",
	"rdaa_a_de_shield_mwc3_0a_g",
	"rdaa_a_de_shield_mwc3_0b_g",
	"rdaa_a_racer2_gl_gnd",
	"rdaa_a_racer2_gr_gnd",
	"rdaa_a_racer_gl_gnd",
	"rdaa_a_racer_gr_gnd",
	"rdaa_w_sword_mwc7b",
	"rdaa_w_sword_mwc7c",
	"rdaa_w_sword_mwc7cc",
	"rp_kama",
	"rptrl_a_de_bt_mwc3_0_gnd",
	"rptrl_a_de_cuir_rptrl1_gnd",
	"rptrl_a_de_cuir_rptrl2_gnd",
	"rptrl_a_de_gntl_mwc12_gnd",
	"rptrl_a_de_gntr_mwc12_gnd",
	"rptrl_a_de_helm_rptrl1_3c_g",
	"rptrl_a_de_pldl_rptrl1_1_g",
	"rptrl_a_de_pldr_rptrl1_1_g",
	"rptrl_c_skirt_rdptrl1_4_gnd",
	"sm_scarf_head",
	"sm_scarf_head_01",
	"steel spear",
	"steel war axe",
	"t_imp_studdedleather_pauldrl_01",
	"t_imp_studdedleather_pauldrr_01",
	"t_nor_iron_pauldronl_01",
	"t_nor_iron_pauldronr_01",
	"tb_a_clothmask1",
	"tb_a_clothmask2",
	"tb_a_clothmask3",
	"vd_ashdustmask",
	"vd_ashgoggles",
	"vd_bonemold_hat",
	"vd_bonemold_helm",
	"vd_bug_helm",
	"vd_bug_helm_2",
	"vd_cloth_googles",
	"vd_gondaliergoggles",
	"vd_mcrabhelmgoggle",
	"vd_morag_tong_mask",
	"vd_netch_leather_boiled_helm",
	"vd_rm_crab_hat_02",
	"vd_rm_crab_shield_01",
	"vvc_back_dustpack5b_gnd",
	"vvc_c_robe_comm_4_4c_g",
	"vvc_c_robe_comm_4_5d_g",
	"vvc_c_robe_comm_4re_2bg",
	"wooden staff",
}
