local I = require('openmw.interfaces')

local MODNAME = 'Throwing'

I.Settings.registerPage {
    key = MODNAME,
    l10n = MODNAME,
    name = 'PageName',
    description = 'PageDescription',
}

I.Settings.registerGroup {
    key = 'Settings_' .. MODNAME,
    page = MODNAME,
    l10n = MODNAME,
    name = 'SettingsName',
    description = 'SettingsDescription',
    permanentStorage = true,
    settings = {
        {
            key = 'enabled',
            renderer = 'checkbox',
            name = 'SettingEnabled',
            description = 'SettingEnabledDescription',
            default = true,
        },
        {
            key = 'replaceMarksman',
            renderer = 'checkbox',
            name = 'SettingReplaceMarksman',
            description = 'SettingReplaceMarksmanDescription',
            default = true,
        },
        {
            key = 'perkMessageStyle',
            renderer = 'number',
            name = 'SettingPerkMessageStyle',
            description = 'SettingPerkMessageStyleDescription',
            default = 1,
            argument = { integer = true, min = 0, max = 2 },
        },
        {
            key = 'perkPopupDetail',
            renderer = 'number',
            name = 'SettingPerkPopupDetail',
            description = 'SettingPerkPopupDetailDescription',
            default = 0,
            argument = { integer = true, min = 0, max = 1 },
        },
        {
            key = 'hideSensoryPerkPopups',
            renderer = 'checkbox',
            name = 'SettingHideSensoryPerkPopups',
            description = 'SettingHideSensoryPerkPopupsDescription',
            default = false,
        },
        {
            key = 'showFeedback',
            renderer = 'checkbox',
            name = 'SettingShowFeedback',
            description = 'SettingShowFeedbackDescription',
            default = false,
        },
        {
            key = 'popupPosition',
            renderer = 'number',
            name = 'SettingPopupPosition',
            description = 'SettingPopupPositionDescription',
            default = 4,
            argument = { integer = true, min = 0, max = 4 },
        },
        {
            key = 'popupDuration',
            renderer = 'number',
            name = 'SettingPopupDuration',
            description = 'SettingPopupDurationDescription',
            default = 1.35,
            argument = { min = 0.5, max = 10, step = 0.05 },
        },
        {
            key = 'popupMaxVisible',
            renderer = 'number',
            name = 'SettingPopupMaxVisible',
            description = 'SettingPopupMaxVisibleDescription',
            default = 5,
            argument = { integer = true, min = 1, max = 10 },
        },
        {
            key = 'popupColourPreset',
            renderer = 'number',
            name = 'SettingPopupColourPreset',
            description = 'SettingPopupColourPresetDescription',
            default = 0,
            argument = { integer = true, min = 0, max = 1 },
        },
        {
            key = 'perkMessageTextR',
            renderer = 'number',
            name = 'SettingPerkMessageTextR',
            description = 'SettingPerkMessageTextRDescription',
            default = 255,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageTextG',
            renderer = 'number',
            name = 'SettingPerkMessageTextG',
            description = 'SettingPerkMessageTextGDescription',
            default = 113,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageTextB',
            renderer = 'number',
            name = 'SettingPerkMessageTextB',
            description = 'SettingPerkMessageTextBDescription',
            default = 24,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageShadowR',
            renderer = 'number',
            name = 'SettingPerkMessageShadowR',
            description = 'SettingPerkMessageShadowRDescription',
            default = 139,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageShadowG',
            renderer = 'number',
            name = 'SettingPerkMessageShadowG',
            description = 'SettingPerkMessageShadowGDescription',
            default = 43,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'perkMessageShadowB',
            renderer = 'number',
            name = 'SettingPerkMessageShadowB',
            description = 'SettingPerkMessageShadowBDescription',
            default = 39,
            argument = { integer = true, min = 0, max = 255 },
        },
        {
            key = 'xpMultiplier',
            renderer = 'number',
            name = 'SettingXpMultiplier',
            description = 'SettingXpMultiplierDescription',
            default = 100,
            argument = { integer = true, min = 0, max = 300 },
        },
        {
            key = 'quickThrowEnabled',
            renderer = 'checkbox',
            name = 'SettingQuickThrowEnabled',
            description = 'SettingQuickThrowEnabledDescription',
            default = true,
        },
        {
            key = 'shortRangeBonusEnabled',
            renderer = 'checkbox',
            name = 'SettingShortRangeBonusEnabled',
            description = 'SettingShortRangeBonusEnabledDescription',
            default = true,
        },
        {
            key = 'perksEnabled',
            renderer = 'checkbox',
            name = 'SettingPerksEnabled',
            description = 'SettingPerksEnabledDescription',
            default = true,
        },
        {
            key = 'criticalEnabled',
            renderer = 'checkbox',
            name = 'SettingCriticalEnabled',
            description = 'SettingCriticalEnabledDescription',
            default = true,
        },
        {
            key = 'twinFlightEnabled',
            renderer = 'checkbox',
            name = 'SettingTwinFlightEnabled',
            description = 'SettingTwinFlightEnabledDescription',
            default = true,
        },
        {
            key = 'bleedEnabled',
            renderer = 'checkbox',
            name = 'SettingBleedEnabled',
            description = 'SettingBleedEnabledDescription',
            default = true,
        },
        {
            key = 'paralyzeEnabled',
            renderer = 'checkbox',
            name = 'SettingParalyzeEnabled',
            description = 'SettingParalyzeEnabledDescription',
            default = true,
        },
        {
            key = 'showMechanicTooltips',
            renderer = 'checkbox',
            name = 'SettingShowMechanicTooltips',
            description = 'SettingShowMechanicTooltipsDescription',
            default = true,
        },
        {
            key = 'showPerkTooltips',
            renderer = 'checkbox',
            name = 'SettingShowPerkTooltips',
            description = 'SettingShowPerkTooltipsDescription',
            default = true,
        },
        {
            key = 'tooltipUnlockedOnly',
            renderer = 'checkbox',
            name = 'SettingTooltipUnlockedOnly',
            description = 'SettingTooltipUnlockedOnlyDescription',
            default = false,
        },
        {
            key = 'debugMessages',
            renderer = 'checkbox',
            name = 'SettingDebugMessages',
            description = 'SettingDebugMessagesDescription',
            default = false,
        },
    },
}
