local defaultConfig = {
	modEnabled = true,
	knowsPrice = 20,
	knowsSpecialization = 30,
	knowsExport = 45,
	knowsForbidden = 20,
	canInvest = 65,
	canTradeWithEveryone = 85,
	canBarterEquipped = 95,
	difficultyLevel = 3,
	sdModifier = 80,
	restockTime = 3,
	removeBought = true,
	forbidden = {
		T_De_Drink_PunavitResin_01 = true,
		T_De_Drink_PunavitJug = true,
		AB_Misc_SoulGemBlack = true,
		bk_NGastaKvataKvakis_c = true,
		bk_NGastaKvataKvakis_o = true,
		bk_progressoftruth = true,
		bk_vampiresofvvardenfell1 = true,
		bk_vampiresofvvardenfell2 = true,
		bk_vivec_murders = true,
		T_Bk_SakaPunikaTR = true,
		bk_ArkayTheEnemy = true,
		NC_bonelord_misc = true,
		NC_boneoverlord_misc = true,
		NC_bonespider_misc = true,
		NC_shambles_misc = true,
		NC_skeleton_champ_misc = true,
		NC_skeleton_war_misc = true,
		NC_skeleton_weak_misc = true,
		NC_SoulGem_AzuraB = true,
		NC_Misc_SoulGemDratha = true

	},
	smuggler = {},
	["Aanthirin Region"] = {
		export = {
			ingred_netch_leather_01 = true,
			ashfall_backpack_n = true,
			ingred_ash_yam_01 = true,
			ingred_black_anther_01 = true,
			ingred_comberry_01 = true,
			potion_comberry_brandy_01 = true,
			potion_comberry_wine_01 = true,
			ingred_corkbulb_01 = true,
			ingred_gold_canet_01 = true,
			ingred_heather_01 = true,
			ingred_marshmerrow_01 = true,
			ingred_saltrice_01 = true,
			AB_IngFood_SaltriceBread = true,
			Potion_Local_Brew_01 = true,
			ingred_willow_flower_01 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
			T_IngFlor_ThirrineLily_01 = true,
			T_IngFlor_TempleDome_01 = true,
			T_IngFlor_OrangeMoss_01 = true,
			T_IngFood_BreadDeshaan_01 = true,
			T_IngFood_BreadDeshaan_02 = true,
			T_IngFood_BreadDeshaan_03 = true,
			T_IngFood_BreadDeshaan_04 = true,
			T_IngFood_BreadDeshaan_05 = true,
			["ingred_hackle-lo_leaf_01"] = true,
			Ingred_scrib_cabbage_01 = true,
			ingred_muck_01 = true,
			ingred_stoneflower_01 = true,
			T_IngCrea_VelkNectarSack_01 = true,
			T_IngCrea_YethResin_01 = true,
		},
		import = {
			AB_w_ToolHandscythe00 = true,
			AB_w_ToolHandscythe01 = true,
			AB_w_ToolScythe = true,
		}
	},


	["Alt Orethan Region"] = {
		export = {
			Ingred_nirthfly_stalks_01 = true,
			Ingred_meadow_rye_01 = true,
			ingred_bittergreen_01 = true,
			ingred_chokeweed_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_roobrush_01 = true,
			ingred_muck_01 = true,
			ingred_stoneflower_01 = true,
			ingred_gold_canet_01 = true,
			["Ingred_timsa-come-by_01"] = true,
			ingred_black_anther_01 = true,
			ingred_willow_flower_01 = true,
			Ingred_noble_sedge_01 = true,
			Ingred_golden_sedge_01 = true,
			ingred_saltrice_01 = true,
			ingred_heather_01 = true,
			ashfall_firewood = true,

		},
		import = {

		}

	},
	["Roth Roryn Region"] = {
		export = {
			ingred_black_anther_01 = true,
			ingred_comberry_01 = true,
			potion_comberry_brandy_01 = true,
			potion_comberry_wine_01 = true,
			ingred_corkbulb_01 = true,
			ingred_gold_canet_01 = true,
			ingred_heather_01 = true,
			Potion_Local_Brew_01 = true,
			ingred_ruby_01 = true, 
			T_IngFlor_ThirrineLily_01 = true,
			ingred_willow_flower_01 = true,
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
		}
	},
	["Boethiah's Spine Region"] = {
		export = {
			ingred_wickwheat_01 = true,
			ingred_kresh_fiber_01 = true,
			-- alit, kagooti, clifracer, 
		},
		import = {
		}
	},
	["Molag Ruhn Region"] = {
		export = {
			["ingred_hackle-lo_leaf_01"] = true,
			ingred_wickwheat_01 = true,
		},
		import = {
		}
	},
	["Armun Ashlands Region"] = {
		export = {
			ingred_hound_meat_01 = true,
			ingred_raw_glass_01 = true,
			ingred_raw_ebony_01 = true,
			ingred_diamond_01 = true,
			ingred_fire_fern_01 = true,
			ingred_red_lichen_01 = true,
			ingred_scathecraw_01 = true,
			ingred_trama_root_01 = true,
			ingred_shalk_resin_01 = true,
			ingred_scuttle_01 = true,
			AB_IngFood_ScuttlePie = true,
			ingred_ash_salts_01 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
		},
		import = {
			ashfall_firewood = true,
			ingred_bread_01 = true,
			p_cure_blight_s = true,
			AB_w_EggminerHook = true,
			AB_a_EggminerHelm = true,
		}
	},
	["Lan Orethan Region"] = {
		export = {
			ingred_corkbulb_01 = true,
			ashfall_firewood = true,
			Ingred_nirthfly_stalks_01 = true,
			Ingred_meadow_rye_01 = true,
			--ingred_bittergreen_01 = true,
			ingred_chokeweed_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_roobrush_01 = true,
			ingred_comberry_01 = true,
			--ingred_muck_01 = true,
			ingred_stoneflower_01 = true,
			ingred_gold_canet_01 = true,
			["Ingred_timsa-come-by_01"] = true,
			ingred_black_anther_01 = true,
			ingred_willow_flower_01 = true,
			Ingred_noble_sedge_01 = true,
			Ingred_golden_sedge_01 = true,
			T_IngMine_OreGold_01 = true,
			T_IngMine_OreGoldDae_01 = true,

		},
		import = {
		}
	},
	["Mephalan Vales Region"] = {
		export = {
			ingred_hound_meat_01 = true,
			T_IngCrea_BeetleResin_01 = true,
			T_IngCrea_BeetleShell_01 = true,
			T_IngCrea_BeetleShell_02 = true,
			T_IngCrea_BeetleShell_03 = true,
			T_IngCrea_BeetleShell_04 = true,
			ingred_guar_hide_01 = true,
			ingred_alit_hide_01 = true,
			ingred_kagouti_hide_01 = true,
			ingred_racer_plumes_01 = true

		},
		import = {
		}
	},
	["Dagon Urul Region"] = {
		export = {
			["ingred_hackle-lo_leaf_01"] = true,
			ingred_wickwheat_01 = true,
			ingred_marshmerrow_01 = true,
			T_IngCrea_FlyMusk_01 = true,
			T_IngCrea_BeetleResin_01 = true,
			T_IngCrea_BeetleShell_01 = true,
			T_IngCrea_BeetleShell_02 = true,
			T_IngCrea_BeetleShell_03 = true,
			T_IngCrea_BeetleShell_04 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
			ingred_alit_hide_01 = true,
			ingred_hound_meat_01 = true,
			ingred_raw_ebony_01 = true,
		},
		import = {
		}
	},
	
	["Sunad Mora Region"] = {
		export = {
			["ingred_hackle-lo_leaf_01"] = true,
			ingred_wickwheat_01 = true,
			ingred_marshmerrow_01 = true,
			T_IngCrea_FlyMusk_01 = true,
			T_IngCrea_BeetleResin_01 = true,
			T_IngCrea_BeetleShell_01 = true,
			T_IngCrea_BeetleShell_02 = true,
			T_IngCrea_BeetleShell_03 = true,
			T_IngCrea_BeetleShell_04 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
			ingred_alit_hide_01 = true,
			ingred_hound_meat_01 = true,
			ingred_raw_ebony_01 = true,
		},
		import = {
		}
	},
	
	["Nedothril Region"] = {
		export = {
			Ingred_nirthfly_stalks_01 = true,
			Ingred_meadow_rye_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_corkbulb_01 = true,
			ingred_stoneflower_01 = true,
		},
		import = {
		}
	},
	["Padomaic Ocean Region"] = {
		export = {
			T_IngCrea_Ambergris = true,
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
		}
	},
	["Sea of Ghosts Region"] = {
		export = {
		},
		import = {
		}
	},
	["Sundered Scar Region"] = {
		export = { -- durzog?
			ashfall_backpack_n = true,
			ingred_netch_leather_01 = true,
			ingred_bungler_bane_01 = true,
			T_IngFlor_TempleDome_01 = true,
			ingred_draggle_tail_01 = true,
			ingred_hypha_facia = true,
			ingred_luminous_russula_01 = true,
			ingred_slough_fern_01 = true,
			ingred_violet_coprinus_01 = true,
			ingred_raw_glass_01 = true,
			ingred_hound_meat_01 = true
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
			p_cure_common_s = true,
		}
	},


	["Telvanni Isles Region"] = {
		export = {
			T_IngCrea_FlyMusk_01 = true,
			T_IngCrea_BeetleResin_01 = true,
			T_IngCrea_BeetleShell_01 = true,
			T_IngCrea_BeetleShell_02 = true,
			T_IngCrea_BeetleShell_03 = true,
			T_IngCrea_BeetleShell_04 = true,
			ingred_kresh_fiber_01 = true,
			ingred_muck_01 = true,
			ingred_netch_leather_01 = true, -- netch and strider farm
			--molecrab armor
		},
		import = {
			-- saltrice for mazte?
		}
	},

	["Roth Roryn Region"] = {
		export = {
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
			ingred_alit_hide_01 = true,
			ingred_kagouti_hide_01 = true,
			ingred_hound_meat_01 = true,
			ingred_netch_leather_01 = true,
			ingred_muck_01 = true,
			ingred_wickwheat_01 = true,
			Ingred_scrib_cabbage_01 = true,
			ingred_ash_yam_01 = true,
			ingred_corkbulb_01 = true,
			["ingred_hackle-lo_leaf_01"] = true
		},
		import = {
		}
	},
	["Sacred Lands Region"] = {
		export = {
			ingred_wickwheat_01 = true,
			ingred_chokeweed_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_roobrush_01 = true,
			ingred_muck_01 = true,
			ingred_stoneflower_01 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
			T_IngCrea_BeetleResin_01 = true,
			T_IngCrea_BeetleShell_01 = true,
			T_IngCrea_BeetleShell_02 = true,
			T_IngCrea_BeetleShell_03 = true,
			T_IngCrea_BeetleShell_04 = true,
			ingred_hound_meat_01 = true
			-- moths?
		},
		import = {}
	},
    ["Grazelands Region"] = {
		export = {
			ingred_hound_meat_01 = true,
			ingred_alit_hide_01 = true,
			ingred_kagouti_hide_01 = true,
			ingred_raw_glass_01 = true,
			["ingred_hackle-lo_leaf_01"] = true,
			ingred_stoneflower_01 = true,
			ingred_wickwheat_01 = true,
			ingred_shalk_resin_01 = true,
			ingred_scuttle_01 = true,
			AB_IngFood_ScuttlePie = true,
			AB_IngFlor_TelvanniResin = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
		},
		import = {
			["sc_paper plain"] = true,
			ashfall_firewood = true,
			AB_sc_Blank = true,
			AB_sc_BlankBargain = true,
			AB_sc_BlankCheap = true,
			AB_sc_BlankExclusive = true,
			AB_sc_BlankQuality = true,
		}
    }, 
    ["West Gash Region"] = {
		export = {
			ingred_hound_meat_01 = true,
			ingred_alit_hide_01 = true,
			ingred_kagouti_hide_01 = true,
			ingred_raw_ebony_01 = true,
			ingred_bittergreen_01 = true,
			AB_IngFlor_BgSlime_01 = true,
			ingred_chokeweed_01 = true,
			ingred_green_lichen_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_roobrush_01 = true,
			ingred_muck_01 = true,
			ingred_stoneflower_01 = true,
			potion_local_liquor_01  = true
		},
		import = {
			AB_w_EggminerHook = true,
			AB_a_EggminerHelm = true,
		}
    },
    ["Ashlands Region"] = {
		export = {
			ingred_hound_meat_01 = true,
			ingred_raw_glass_01 = true,
			ingred_raw_ebony_01 = true,
			ingred_diamond_01 = true,
			ingred_fire_fern_01 = true,
			ingred_red_lichen_01 = true,
			ingred_scathecraw_01 = true,
			ingred_trama_root_01 = true,
			ingred_shalk_resin_01 = true,
			ingred_scuttle_01 = true,
			AB_IngFood_ScuttlePie = true,
			ingred_ash_salts_01 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
		},
		import = {
			ashfall_firewood = true,
			ingred_bread_01 = true,
			p_cure_blight_s = true,
			AB_w_EggminerHook = true,
			AB_a_EggminerHelm = true,
            p_cure_blight_s = true,
            p_cure_common_s =true,
		}
    },
	
	["Red Mountain Region"] = {
		export = {
			ingred_raw_glass_01 = true,
			ingred_raw_ebony_01 = true,
			ingred_diamond_01 = true,
			ingred_fire_fern_01 = true,
			ingred_red_lichen_01 = true,
			ingred_scathecraw_01 = true,
			ingred_trama_root_01 = true,
			ingred_shalk_resin_01 = true,
			ingred_scuttle_01 = true,
			AB_IngFood_ScuttlePie = true,
			ingred_ash_salts_01 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
		},
		import = {
			ashfall_firewood = true,
			ingred_bread_01 = true,
            p_cure_blight_s = true,
            p_cure_common_s =true,
		}
    },
	
    ["Bitter Coast Region"] = {
		export = {
			ashfall_backpack_n = true,
			ingred_netch_leather_01 = true,
			ingred_bungler_bane_01 = true,
			ingred_draggle_tail_01 = true,
			ingred_hypha_facia = true,
			ingred_luminous_russula_01 = true,
			ingred_slough_fern_01 = true,
			ingred_violet_coprinus_01 = true,
			ingred_hound_meat_01 = true,
			potion_skooma_01 = true,
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
			p_cure_common_s = true,
		}
    },
    ["Ascadian Isles Region"] = {
		export = {
			ingred_hound_meat_01 = true,
			ingred_kagouti_hide_01 = true,
			ingred_netch_leather_01 = true,
			ashfall_backpack_n = true,
			ingred_ash_yam_01 = true,
			ingred_black_anther_01 = true,
			ingred_comberry_01 = true,
			potion_comberry_brandy_01 = true,
			potion_comberry_wine_01 = true,
			ingred_corkbulb_01 = true,
			ingred_gold_canet_01 = true,
			ingred_heather_01 = true,
			ingred_marshmerrow_01 = true,
			ingred_saltrice_01 = true,
			AB_IngFood_SaltriceBread = true,
			Potion_Local_Brew_01 = true,
			ingred_willow_flower_01 = true,
			AB_IngCrea_GuarMeat_01 = true,
			ingred_guar_hide_01 = true,
			potion_skooma_01 = true,
		},
		import = {
			AB_w_ToolHandscythe00 = true,
			AB_w_ToolHandscythe01 = true,
			AB_w_ToolScythe = true,
		}
    },
    ["Molag Amur Region"] = {
		export = {
			ingred_fire_fern_01 = true,
			food_kwama_egg_01 = true,
			food_kwama_egg_02 = true,
			ingred_scathecraw_01 = true,
			ingred_trama_root_01 = true,
			ingred_shalk_resin_01 = true,
			ingred_scuttle_01 = true,
			ingred_racer_plumes_01 = true,
			AB_IngFood_ScuttlePie = true
		},
		import = {
			ashfall_firewood = true,
			ingred_bread_01 = true,
			AB_w_EggminerHook = true,
			AB_a_EggminerHelm = true,
            p_cure_blight_s = true,
            p_cure_common_s =true,
		}
    },
    ["Azura's Coast Region"] = {
		export = {
			ingred_alit_hide_01 = true,
			ingred_black_anther_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_marshmerrow_01 = true,
			ingred_muck_01 = true,
			ingred_saltrice_01 = true,
			AB_IngFood_SaltriceBread = true,
			Potion_Local_Brew_01 = true,
			AB_IngFlor_TelvanniResin = true,
			ingred_racer_plumes_01 = true,
		},
		import = {
			["sc_paper plain"] = true,
			ashfall_firewood = true,
			AB_sc_Blank = true,
			AB_sc_BlankBargain = true,
			AB_sc_BlankCheap = true,
			AB_sc_BlankExclusive = true,
			AB_sc_BlankQuality = true,
		}
    },

    ["Almas Thirr"] = {
		export = {
			ingred_black_anther_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_marshmerrow_01 = true,
			ingred_muck_01 = true,
			ingred_saltrice_01 = true,
			AB_IngFood_SaltriceBread = true,
			Potion_Local_Brew_01 = true,
			AB_IngFlor_TelvanniResin = true,
		},
		import = {
			["sc_paper plain"] = true,
			ashfall_firewood = true,
			AB_sc_Blank = true,
			AB_sc_BlankBargain = true,
			AB_sc_BlankCheap = true,
			AB_sc_BlankExclusive = true,
			AB_sc_BlankQuality = true,
			potion_skooma_01 = true,
			ingred_moon_sugar_01 = true,
		}
    },

    ["Vivec"] = {
		export = {
			ingred_black_anther_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_marshmerrow_01 = true,
			ingred_muck_01 = true,
			ingred_saltrice_01 = true,
			AB_IngFood_SaltriceBread = true,
			Potion_Local_Brew_01 = true,
			AB_IngFlor_TelvanniResin = true,
		},
		import = {
			["sc_paper plain"] = true,
			ashfall_firewood = true,
			AB_sc_Blank = true,
			AB_sc_BlankBargain = true,
			AB_sc_BlankCheap = true,
			AB_sc_BlankExclusive = true,
			AB_sc_BlankQuality = true,
			potion_skooma_01 = true,
			ingred_moon_sugar_01 = true,
		}
    },

    ["Sheogorad Region"] = {
		export = {
			ingred_black_anther_01 = true,
			ingred_gold_canet_01 = true,
			ingred_green_lichen_01 = true,
			ingred_kresh_fiber_01 = true,
			ingred_racer_plumes_01 = true,
		},
		import = {
			ashfall_firewood = true,
		}
    },
	Solstheim = {
		export = {
			ingred_raw_ebony_01 = true,
			ingred_bear_pelt = true,
			ingred_boar_leather = true,
			ingred_belladonna_01 = true,
			ingred_belladonna_02 = true,
			ingred_holly_01 = true,
			ingred_horker_tusk_01 = true,
			ashfall_backpack_b = true,
			ashfall_backpack_w = true,
			ashfall_firewood = true,
			potion_nord_mead = true,
			T_IngFood_MeatHorker_01 = true,
		},
		import = {
			potion_cyro_brandy_01 = true,
			Potion_Cyro_Whiskey_01 = true,
		}
	},
	["Ald-ruhn"] = {
		export = {
			AB_a_BonemLightBoots = true,
			AB_a_BonemLightBracerL = true,
			AB_a_BonemLightBracerR = true,
			AB_a_BonemLightCuirass = true,
			AB_a_BonemLightGreaves = true,
			AB_a_BonemLightHelm = true,
			AB_a_BonemLightPaulL = true,
			AB_a_BonemLightPaulR = true,
			AB_a_IronDeBoots = true,
			AB_a_IronDeCuirass = true,
			AB_a_IronDeHelm = true,
			AB_a_IronDePldLeft = true,
			AB_a_IronDePldRight = true,
			["bonemold_gah-julan_cuirass"] = true,
			["bonemold_gah-julan_helm"] = true,
			["bonemold_gah-julan_pauldron_l"] = true,
			["bonemold_gah-julan_pauldron_r"] = true,
			["bonemold_tshield_redoranguard"] = true,
		},
		import = {
			-- Non-native armor and weapons
			["BM bear boots"] = true,
			["BM bear cuirass"] = true,
			["BM bear greaves"] = true,
			["BM Bear Helmet"] = true,
			["bm bear left gauntlet"] = true,
			["BM bear right gauntlet"] = true,
			["BM Bear left Pauldron"] = true,
			["BM bear right pauldron"] = true,
			["BM bear shield"] = true,
			["BM wolf boots"] = true,
			["BM wolf cuirass"] = true,
			["BM wolf greaves"] = true,
			["bm wolf left gauntlet"] = true,
			["BM wolf right gauntlet"] = true,
			["BM Wolf Left Pauldron"] = true,
			["BM wolf right pauldron"] = true,
			["BM wolf shield"] = true,
			BM_bear_boots_snow = true,
			BM_bear_cuirass_snow = true,
			BM_bear_greaves_snow = true,
			BM_bear_helmet_snow = true,
			BM_bear_left_gauntlet_snow = true,
			BM_Bear_left_Pauldron_snow = true,
			BM_bear_right_gauntlet_snow = true,
			BM_bear_right_pauldron_snow = true,
			BM_Ice_Boots = true,
			BM_Ice_cuirass = true,
			BM_Ice_gauntletL = true,
			BM_Ice_gauntletR = true,
			BM_Ice_greaves = true,
			BM_Ice_Helmet = true,
			BM_Ice_PauldronL = true,
			BM_Ice_PauldronR = true,
			BM_Ice_Shield = true,
			BM_NordicMail_Boots = true,
			BM_NordicMail_cuirass = true,
			BM_NordicMail_gauntletL = true,
			BM_NordicMail_gauntletR = true,
			BM_NordicMail_greaves = true,
			BM_NordicMail_Helmet = true,
			BM_NordicMail_PauldronL = true,
			BM_NordicMail_PauldronR = true,
			BM_NordicMail_Shield = true,
			BM_wolf_boots_snow = true,
			BM_wolf_cuirass_snow = true,
			BM_wolf_greaves_snow = true,
			BM_wolf_helmet_snow = true,
			BM_wolf_left_gauntlet_snow = true,
			BM_wolf_left_pauldron_snow = true,
			BM_wolf_right_gauntlet_snow = true,
			BM_wolf_right_pauldron_snow = true,
			ingred_raw_Stalhrim_01 = true,
			T_Com_MetalPieceIron_01 = true,
			T_Com_MetalPieceSteel_01 = true,
		}
	},
	Balmora = {
		export = {
			["bonemold_armun-an_cuirass"] = true,
			["bonemold_armun-an_helm"] = true,
			["bonemold_armun-an_pauldron_l"] = true,
			["bonemold_armun-an_pauldron_r"] = true,
			["bonemold_tshield_hlaaluguard"] = true,
			potion_skooma_01 = true,
		},
		import = {
			T_He_DirenniScales_01 = true,
			T_Imp_SilverScales_01 = true,
			T_Imp_SilverScales_02 = true,
		}
	},

	["Hlan Oek"] = {
		export = {
			["bonemold_armun-an_cuirass"] = true,
			["bonemold_armun-an_helm"] = true,
			["bonemold_armun-an_pauldron_l"] = true,
			["bonemold_armun-an_pauldron_r"] = true,
			["bonemold_tshield_hlaaluguard"] = true,
			potion_skooma_01 = true,
		},
		import = {
			T_He_DirenniScales_01 = true,
			T_Imp_SilverScales_01 = true,
			T_Imp_SilverScales_02 = true,
		}
	},
	
	["Narsis"] = {
		export = {
			["bonemold_armun-an_cuirass"] = true,
			["bonemold_armun-an_helm"] = true,
			["bonemold_armun-an_pauldron_l"] = true,
			["bonemold_armun-an_pauldron_r"] = true,
			["bonemold_tshield_hlaaluguard"] = true,
		},
		import = {
			T_He_DirenniScales_01 = true,
			T_Imp_SilverScales_01 = true,
			T_Imp_SilverScales_02 = true,
		}
	},

	Suran = {
		export = {
			["bonemold_armun-an_cuirass"] = true,
			["bonemold_armun-an_helm"] = true,
			["bonemold_armun-an_pauldron_l"] = true,
			["bonemold_armun-an_pauldron_r"] = true,
			["bonemold_tshield_hlaaluguard"] = true,
			potion_skooma_01 = true,
		},
		import = {
			T_He_DirenniScales_01 = true,
			T_Imp_SilverScales_01 = true,
			T_Imp_SilverScales_02 = true,
		}
	},
	Caldera = {
		export = {
			ingred_raw_ebony_01 = true,
		},
		import = {
		}
	},
	["Khuul"] = {
		export = {
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
			p_cure_common_s = true,
		}
	},
	["Ald Velothi"] = {
		export = {
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
			p_cure_common_s = true,
		}
	},
	["Gnisis"] = {
		export = {
			food_kwama_egg_01 = true,
			food_kwama_egg_02 = true,
		},
		import = {
			p_cure_blight_s = true,
			AB_w_EggminerHook = true,
			AB_a_EggminerHelm = true,
		}
	},
	["Hla Oad"] = {
		export = {
			ingred_netch_leather_01 = true,
			ingred_bungler_bane_01 = true,
			ingred_draggle_tail_01 = true,
			ingred_hypha_facia = true,
			ingred_luminous_russula_01 = true,
			ingred_slough_fern_01 = true,
			ingred_violet_coprinus_01 = true,
			ingred_hound_meat_01 = true,
			potion_skooma_01 = true,
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
			p_cure_common_s = true,
		}
	},
	["Gnaar Mok"] = {
		export = {
			ingred_netch_leather_01 = true,
			ingred_bungler_bane_01 = true,
			ingred_draggle_tail_01 = true,
			ingred_hypha_facia = true,
			ingred_luminous_russula_01 = true,
			ingred_slough_fern_01 = true,
			ingred_violet_coprinus_01 = true,
			ingred_hound_meat_01 = true,
			potion_skooma_01 = true,
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
			p_cure_common_s = true,
		}
	},
	["Seyda Neen"] = {
		export = {
			ingred_netch_leather_01 = true,
			ingred_bungler_bane_01 = true,
			ingred_draggle_tail_01 = true,
			ingred_hypha_facia = true,
			ingred_luminous_russula_01 = true,
			ingred_slough_fern_01 = true,
			ingred_violet_coprinus_01 = true,
			ingred_hound_meat_01 = true,
		},
		import = {
			AB_w_ToolFishingNet = true,
			T_Rga_FishingSpear_01 = true,
			p_cure_common_s = true,
		}
	},
	["Tel Branora"] = {
		export = {
			bonemold_tshield_telvanniguard = true,
			cephalopod_helm = true,
			AB_a_CephHelmOpen = true,
			AB_a_CephPauldronLeft = true,
			AB_a_CephPauldronRight = true,
			dust_adept_helm = true,
			mole_crab_helm = true,
			potion_t_bug_musk_01 = true,
		},
		import = {
			food_kwama_egg_01 = true,
			food_kwama_egg_02 = true,
			misc_uniq_egg_of_gold = true,
		}
	},
	["Tel Aruhn"] = {
		export = {
			bonemold_tshield_telvanniguard = true,
			AB_a_CephHelmOpen = true,
			AB_a_CephPauldronLeft = true,
			AB_a_CephPauldronRight = true,
			cephalopod_helm = true,
			mole_crab_helm = true,
			dust_adept_helm = true,
			potion_t_bug_musk_01 = true,
		},
		import = {
			["6th bell hammer"] = true,
			misc_goblet_dagoth = true,
			AB_Misc_6thBell = true,
			AB_Misc_6thFlute = true,
			misc_6th_ash_statue_01 = true,
			AB_Misc_6thAshStatue13 = true,
			AB_Misc_6thAshStatue07 = true,
			AB_Misc_6thAshStatue04 = true,
			AB_Misc_6thAshStatue02 = true,
			AB_Misc_6thMug = true,
			AB_Misc_6thBowl = true,
			misc_de_goblet_04_dagoth = true,
			AB_Misc_6thPlate02 = true,
			AB_Misc_6thPlate01 = true,
			potion_ancient_brandy = true,
			ingred_corprus_weepings_01 = true,
			ingred_ghoul_heart_01 = true,
		}
	},
	["Sadrith Mora"] = {
		export = {
			bonemold_tshield_telvanniguard = true,
			AB_a_CephHelmOpen = true,
			AB_a_CephPauldronLeft = true,
			AB_a_CephPauldronRight = true,
			cephalopod_helm = true,
			mole_crab_helm = true,
			dust_adept_helm = true,
			potion_t_bug_musk_01 = true,
		},
		import = {
			-- rare items, artifacts and gimmicks
			artifact_bittercup_01 = true,
			misc_vivec_ashmask_01 = true,
			Misc_SoulGem_Azura = true,
			Nuccius_ring = true,
			index_valen = true,
			index_telas = true,
			index_roth = true,
			index_maran = true,
			index_indo = true,
			index_hlor = true,
			index_falen = true,
			index_falas = true,
			index_beran = true,
			index_andra = true,
			T_De_Index_Hlomaseth = true,
			T_De_Index_Hlorandar = true,
			T_De_Index_Idaverrano = true,
			T_De_Index_Khalaan = true,
			T_De_Index_Othrano = true,
			T_De_Index_Romayon = true,
			T_De_Index_Vandirelyon = true,
			T_De_Index_Volenfaryon = true,
			T_De_UNI_PilgrimStone = true,
			T_De_UNI_RenaldLute = true,
			T_De_UNI_UlvoClawMisc = true,
			T_He_DirenniWelkyndInv_01 = true,
			T_Com_UNI_KingOrgnumCoffer_01 = true,
			T_Ayl_WelkyndInv_01 = true,
			T_Ayl_VarlaInv_01 = true,
			T_Ayl_Statuette_01 = true,
			T_Ayl_DWelkyndInv_01 = true,
			T_He_DirenniScales_01 = true,
			T_Rga_MemoryStone_01 = true,
			T_He_DngDirenni_Welkynd01_50 = true,
			T_He_DirenniAlembic_01 = true,
			T_He_DirenniMortar_01 = true,
			T_De_PunavitComCup_01 = true,
			T_De_PunavitSamovar_01 = true,
		}
	},

	Vhuul = {
		export = {
			T_De_Drink_PunavitJug = true,
			T_De_Drink_PunavitResin_01 = true
		},
		import = {
			T_IngCrea_VelkNectarSack_01 = true
		}
	},

	chitin = {
		["chitin arrow"] = true,
		["chitin club"] = true,
		["chitin dagger"] = true,
		["chitin short bow"] = true,
		["chitin shortsword"] = true,
		["chitin spear"] = true,
		["chitin throwing star"] = true,
		["chitin war axe"] = true,
		["chitin boots"] = true,
		["chitin cuirass"] = true,
		["chitin greaves"] = true,
		["chitin guantlet - left"] = true,
		["chitin guantlet - right"] = true,
		["chitin helm"] = true,
		["chitin pauldron - left"] = true,
		["chitin pauldron - right"] = true,
		["chitin_shield"] = true,
		["chitin_towershield"] = true,
		T_De_Chitin_HelmOpen_01 = true,
		T_De_Chitin_PauldrL_01 = true,
		T_De_Chitin_PauldrR_01 = true,
		AB_a_ChitinHelmOpen = true,
		AB_a_ChitinHlaHelm01 = true,
		AB_a_ChitinRedHelm01 = true,
		AB_a_ChitinScoutHelm = true,
		AB_a_ChitinTelHelm01 = true,
		AB_w_ChitinHalberd = true,
		AB_w_ChitinMace = true,
		AB_w_ChitinSickle = true,
		T_De_Chitin_Bolt_01 = true,
		T_De_Chitin_Crossbow = true,
		T_De_Chitin_Dart_01 = true,
		T_De_Chitin_Halberd_01 = true,
		T_De_Chitin_Javelin_01 = true,
		T_De_Chitin_Longsword_01 = true,
		T_De_Chitin_Mace_01 = true,
		T_De_Chitin_Sickle_01 = true,
		T_De_Chitin_Staff = true,
	},
	
	netch = {
		netch_leather_boiled_cuirass = true,
		netch_leather_boiled_helm = true,
		netch_leather_boots = true,
		netch_leather_cuirass = true,
		netch_leather_gauntlet_left = true,
		netch_leather_gauntlet_right = true,
		netch_leather_greaves = true,
		netch_leather_helm = true,
		netch_leather_pauldron_left = true,
		netch_leather_pauldron_right = true,
		netch_leather_shield = true,
		netch_leather_towershield = true,
		AB_a_NetchBoilPldLeft = true,
		AB_a_NetchBoilPldRight = true,
		T_De_Netch_Cuirass_01 = true,
		T_De_Netch_Cuirass_02 = true,
		T_De_Netch_Cuirass_03 = true,
		T_De_Netch_Helm_01 = true,
		T_De_Netch_Helm_02 = true,
		T_De_NetchRogue_Cuirass_01 = true,
		T_De_NetchRogue_Helm_01 = true,
		T_De_NetchRogue_Helm_02 = true,
		AB_a_NetchimanCap = true,
		T_De_NetchStalker_Helm_01 = true,

	},
	
	ashlander = {
		AB_Misc_AshlFlute = true,
		AB_w_AshlBoneArrow = true,
		AB_w_BoneArrow = true,
		AB_a_BugBlueBoots = true,
		AB_a_BugBlueCuirass = true,
		AB_a_BugBlueGntLeft = true,
		AB_a_BugBlueGntRight = true,
		AB_a_BugBlueGreaves = true,
		AB_a_BugBlueHelm = true,
		AB_a_BugBluePldLeft = true,
		AB_a_BugBluePldRight = true,
		AB_a_BugBlueShield = true,
		AB_a_BugGreenBoots = true,
		AB_a_BugGreenCuirass = true,
		AB_a_BugGreenGntLeft = true,
		AB_a_BugGreenGntRight = true,
		AB_a_BugGreenGreaves = true,
		AB_a_BugGreenHelm = true,
		AB_a_BugGreenPldLeft = true,
		AB_a_BugGreenPldRight = true,
		AB_a_BugGreenShield = true,
	},
	
	dwemer = {
		AB_Misc_DwGyro00 = true,
	},
	daedra = {
		ingred_daedra_skin_01 = true,
		ingred_daedras_heart_01 = true,
		ingred_fire_salts_01 = true,
		ingred_frost_salts_01 = true,
		ingred_void_salts_01 = true,
		ingred_scamp_skin_01 = true,
		AB_IngCrea_ClannClaw_01 = true,
		AB_IngCrea_TwilightMembrane = true,
		AB_IngCrea_DaeTeeth_01 = true,
		["daedric arrow"] = true,
		["daedric battle axe"] = true,
		["daedric claymore"] = true,
		["daedric club"] = true,
		["daedric dagger"] = true,
		["daedric dagger_bar"] = true,
		["daedric dagger_mtas"] = true,
		["daedric dagger_soultrap"] = true,
		["daedric dai-katana"] = true,
		["daedric dart"] = true,
		["daedric katana"] = true,
		["daedric long bow"] = true,
		["daedric longsword"] = true,
		["daedric mace"] = true,
		["daedric shortsword"] = true,
		["daedric spear"] = true,
		["daedric staff"] = true,
		["daedric tanto"] = true,
		["daedric wakizashi"] = true,
		["daedric wakizashi_hhst"] = true,
		["daedric war axe"] = true,
		["daedric warhammer"] = true,
		["daedric warhammer_ttgd"] = true,
		["daedric warhammer_ttgd_x"] = true,
		["daedric_club_tgdc"] = true,
		["daedric_crescent_unique"] = true,
		["daedric_scourge_unique"] = true,
		["ebony arrow"] = true,
		["ebony arrow_sadri"] = true,
		["ebony broadsword"] = true,
		["ebony broadsword_Dae_cursed"] = true,
		["ebony dart"] = true,
		["ebony dart_db_unique"] = true,
		["ebony longsword"] = true,
		["ebony mace"] = true,
		["Ebony Scimitar"] = true,
		["Ebony Scimitar_her"] = true,
		["ebony shortsword"] = true,
		["ebony shortsword_soscean"] = true,
		["ebony spear"] = true,
		["ebony spear_blessed_unique"] = true,
		["ebony spear_hrce_unique"] = true,
		["ebony staff"] = true,
		["ebony staff caper"] = true,
		["ebony throwing star"] = true,
		["ebony war axe"] = true,
		["ebony war axe_elanande"] = true,
		["ebony_bow_auriel"] = true,
		["ebony_bow_auriel_X"] = true,
		["ebony_dagger_mehrunes"] = true,
		["ebony_staff_tges"] = true,
		["ebony_staff_trebonius"] = true,
		["glass arrow"] = true,
		["glass claymore"] = true,
		["glass claymore_magebane"] = true,
		["glass dagger"] = true,
		["glass dagger_Dae_cursed"] = true,
		["glass dagger_symmachus_unique"] = true,
		["glass dagger_symmachus_unique_x"] = true,
		["glass firesword"] = true,
		["glass frostsword"] = true,
		["glass halberd"] = true,
		["glass jinkblade"] = true,
		["glass longsword"] = true,
		["glass netch dagger"] = true,
		["glass poisonsword"] = true,
		["glass staff"] = true,
		["glass stormblade"] = true,
		["glass stormsword"] = true,
		["glass throwing knife"] = true,
		["glass throwing star"] = true,
		["glass war axe"] = true,
		["glass_dagger_enamor"] = true,
		
	},

	undead = {
		ingred_bonemeal_01 = true,
		ingred_ectoplasm_01 = true
	},
	
	sea = {
		ingred_pearl_01 = true,
		T_IngMine_PearlBlack_01 = true,
		T_IngMine_PearlBlue_01 = true,
		T_IngMine_PearlKardesh_01 = true,
		T_IngMine_PearlPink_01 = true,
		ingred_dreugh_wax_01 = true,
		ingred_crab_meat_01 = true,
		ingred_scales_01 = true,
		AB_IngCrea_DreughShell_01 = true,
		AB_IngCrea_SfMeat_01 = true,
		T_IngCrea_ShellMolecrab_02 = true,
		T_IngCrea_ShellMolecrab_01 = true,
		T_IngCrea_CephalopodShell_01 = true,
		T_IngFood_EggMolecrab_01 = true,
		T_IngFood_MeatOrnada_01 = true,
		T_IngFood_EggOrnada_01 = true,
		T_IngFood_FishBrowntrout_01 = true,
		T_IngFood_FishChrysophant_01 = true,
		T_IngFood_FishCod_01 = true,
		T_IngFood_FishCodDried_01 = true,
		T_IngFood_FishLeaperTail_01 = true,
		T_IngFood_FishLongfinFilet_01 = true,
		T_IngFood_FishPike_01 = true,
		T_IngFood_FishPikeperch_01 = true,
		T_IngFood_FishSalmon_01 = true,
		T_IngFood_FishSlaughterDried_01 = true,
		T_IngFood_FishSlaughterDried_02 = true,
		T_IngFood_FishSlaughterDried_03 = true,
		T_IngFood_FishSpr_01 = true,
		T_IngFood_FishStrid_01 = true,
	},
	
	kwama = {
		food_kwama_egg_01 = true,
        food_kwama_egg_02 = true,
		ingred_scrib_jelly_01 = true,
		ingred_scrib_jerky_01 = true,
		AB_IngCrea_KwamaPoison = true,
		AB_IngCrea_ScribShell_01 = true,
		AB_IngFood_KwamaLoaf = true,
		T_IngFood_MeatKwama_01 = true,
		T_IngFood_ScribPie_01 = true,
		T_IngCrea_KwamaChitin_01 = true,
	},
	
	coins = {
		lucky_coin = true,
		misc_dwrv_coin00 = true,
		misc_dwrv_cursed_coin00 = true,
		T_Ayl_CoinBig_01 = true,
		T_Ayl_CoinGold_01 = true,
		T_Ayl_CoinSquare_01 = true,
		T_Com_GoldCoinDae_01 = true,
		T_Com_GoldCoinDae_05 = true,
		T_Com_GoldCoinDae_25 = true,
		T_De_GoldCoinGhost_05 = true,
		T_De_GoldCoinGhost_25 = true,
		T_He_DirenniCoin_01 = true,
		T_Imp_CoinAlessian_01 = true,
		T_Imp_CoinReman_01 = true,
		T_Nor_CoinBarrowCopper_01 = true,
		T_Nor_CoinBarrowIron_01 = true,
		T_Nor_CoinBarrowSilver_01 = true,
		TR_m3_q_fakedwemercoin = true,
	},

	farming_tools = {
		AB_w_ToolHandscythe00 = true,
		AB_w_ToolHandscythe01 = true,
		AB_w_ToolScythe = true,
		T_Com_Farm_Hatchet_01 = true,
		T_Com_Farm_Hoe_01 = true,
		T_Com_Farm_Pitchfork_01 = true,
		T_Com_Farm_Scythe_01 = true,
		T_Com_Farm_Shovel_01 = true,
		T_Com_Farm_Sledgehammer_01 = true,
		T_Com_Farm_Trovel_01 = true,
	},

	embalming_tools = {
		T_Com_Embalming_Knife_01 = true,
		T_Com_EmbalmingScissor_01 = true,
		T_Com_Embalming_Hook_01 = true

	},

	fishing_tools = {
		misc_de_fishing_pole = true,
		T_Com_FishFeed_01 = true,
		T_De_FishingNet_01 = true,
	},
	
	luxury = {
		AB_Misc_DaeSigilstone_01 = true,
		AB_Misc_DeEbonyBowl_01 = true,
		AB_Misc_DeEbonyCup_01 = true,
		AB_Misc_DeEbonyFlask_01 = true,
		AB_Misc_DeEbonyFork_01 = true,
		AB_Misc_DeEbonyGlass_01 = true,
		AB_Misc_DeEbonyInkwell_01 = true,
		AB_Misc_DeEbonyKnife_01 = true,
		AB_Misc_DeEbonyPlate_01 = true,
		AB_Misc_DeEbonyPlatter_01 = true,
		AB_Misc_DeEbonySpoon_01 = true,
		AB_Misc_LwBowlSmall = true,
        AB_Misc_LwPitcher = true,
        AB_Misc_LwVase = true,
		AB_c_ExquisiteAmulet01 = true,
		AB_c_ExquisiteRing01 = true,
		exquisite_amulet_01 = true,
		exquisite_belt_01 = true,
		exquisite_pants_01 = true,
		exquisite_ring_01 = true,
		exquisite_ring_02 = true,
		exquisite_robe_01 = true,
		exquisite_shirt_01 = true,
		exquisite_shirt_01_rasha = true,
		exquisite_shoes_01 = true,
		exquisite_skirt_01 = true,
        misc_lw_bowl = true,
        misc_lw_cup = true,
        misc_lw_flask = true,
        misc_lw_platter = true,
        T_Com_Astrolabe_01 = true,
        T_Com_MetalPieceGold_01 = true,
        T_Com_MetalPieceGold_02 = true,
        T_Com_MetalPieceGold_03 = true,
        T_Com_MetalPieceSilver_01 = true,
        T_Com_MetalPieceSilver_02 = true,
        T_Com_MetalPieceSilver_03 = true,
        T_Com_Sextant_01 = true,
		T_De_Ebony_Bowl_01 = true,
		T_De_Ebony_Bowl_02 = true,
		T_De_Ebony_Cup_01 = true,
		T_De_Ebony_Fork_01 = true,
		T_De_Ebony_Knife_01 = true,
		T_De_Ebony_LargeFlask_01 = true,
		T_De_Ebony_Plate_01 = true,
		T_De_Ebony_Platter_01 = true,
		T_De_Ebony_Spoon_01 = true,
        T_De_PunavitAshJar_01 = true,
        T_De_PunavitKettle_01 = true,
        T_Imp_GoldBowl_01 = true,
        T_Imp_GoldBowl_01 = true,
        T_Imp_GoldCandlestick_01 = true,
        T_Imp_GoldCandlestick_02 = true,
        T_Imp_GoldGoblet_01 = true,
        T_Imp_GoldPitcher_01 = true,
		
		T_Bre_Ex_Ring_01 = true,
		T_Com_Ex_Ring_Whispers = true,
		T_Com_Ex_Shirt_01 = true,
		T_Com_Ex_Shirt_02 = true,
		T_Com_Ex_Shirt_03 = true,
		T_Com_Ex_Skirt_01 = true,
		T_Com_Ex_Skirt_02 = true,
		T_Com_Ex_Skirt_03 = true,
		T_De_Ex_Pants_01 = true,
		T_De_Ex_Pants_02 = true,
		T_De_Ex_Pants_03 = true,
		T_De_Ex_Pants_04 = true,
		T_De_Ex_Pants_05 = true,
		T_De_Ex_Pants_06 = true,
		T_De_Ex_Pants_07 = true,
		T_De_Ex_Pants_08 = true,
		T_De_Ex_Robe_01 = true,
		T_De_Ex_RobeHla_01 = true,
		T_De_Ex_RobeHla_02 = true,
		T_De_Ex_RobeNecrom_01 = true,
		T_De_Ex_RobeTelv_01 = true,
		T_De_Ex_Shirt_01 = true,
		T_De_Ex_Shirt_02 = true,
		T_De_Ex_Shirt_03 = true,
		T_De_Ex_Shirt_04 = true,
		T_De_Ex_Shirt_05 = true,
		T_De_Ex_Shirt_06 = true,
		T_De_Ex_Shirt_07 = true,
		T_De_Ex_Shirt_08 = true,
		T_De_Ex_Shirt_08fff = true,
		T_De_Ex_Shoes_01 = true,
		T_De_Ex_Shoes_08 = true,
		T_De_Ex_Skirt_03 = true,
		T_De_Ex_Skirt_04 = true,
		T_De_Ex_Skirt_05 = true,
		T_De_Ex_Skirt_06 = true,
		T_De_Ex_Skirt_07 = true,
		T_De_Ex_SkirtNecrom_01 = true,
		T_He_Ex_Amulet_01 = true,
		T_He_Ex_Ring_01 = true,
		T_Imp_Ex_Amulet_01 = true,
		T_Imp_Ex_Amulet_Dibellan = true,
		T_Imp_Ex_Amulet_WithheldBlade = true,
		T_Imp_Ex_RobeNib_01 = true,
		T_Imp_Ex_RobeNib_02 = true,
		T_Nor_Ex_Belt_01 = true,
		T_Nor_Ex_Belt_01_WardIce = true,
		T_Nor_Ex_Belt_01_WardShock = true,
		T_Nor_Ex_Belt_02 = true,
		T_Nor_Ex_Belt_02_GreaterHealing = true,
		T_Nor_Ex_Belt_02_WardFire = true,
		T_Bre_Et_Ring_01 = true,
		T_Bre_Et_Ring_02 = true,
		T_Com_Et_GloveL_02 = true,
		T_Com_Et_GloveR_02 = true,
		T_Com_Et_Shirt_02 = true,
		T_Com_Et_Shirt_03 = true,
		T_Com_Et_Shoes_01 = true,
		T_Com_Et_Shoes_02 = true,
		T_Com_Et_Shoes_03 = true,
		T_Com_Et_Shoes_04 = true,
		T_Com_Et_Skirt_01 = true,
		T_Com_Et_Skirt_02 = true,
		T_De_Et_Amulet_Horker = true,
		T_De_Et_Amulet_MeriyonsFins = true,
		T_De_Et_Pants_01 = true,
		T_De_Et_PantsSacredBonemold_01 = true,
		T_De_Et_Robe_01 = true,
		T_De_Et_Robe_Magickeater = true,
		T_De_Et_Robe_Magickmirror = true,
		T_De_Et_RobeNecromPriest_01 = true,
		T_De_Et_RobeShin_01 = true,
		T_De_Et_RobeShin_02 = true,
		T_De_Et_RobeTelv_01 = true,
		T_De_Et_Shirt_01 = true,
		T_De_Et_Shirt_02 = true,
		T_De_Et_Shirt_03 = true,
		T_De_Et_Shirt_04 = true,
		T_De_Et_Shirt_05 = true,
		T_De_Et_Shirt_06 = true,
		T_De_Et_Shirt_07 = true,
		T_De_Et_Shirt_08 = true,
		T_De_Et_Shirt_09 = true,
		T_De_Et_Shirt_10 = true,
		T_De_Et_ShirtDres_01 = true,
		T_De_Et_ShirtDres_02 = true,
		T_De_Et_ShirtDres_03 = true,
		T_De_Et_ShirtInd_01 = true,
		T_De_Et_ShirtInd_02 = true,
		T_De_Et_Shoes_01 = true,
		T_De_Et_Shoes_02 = true,
		T_De_Et_Shoes_03 = true,
		T_De_Et_Shoes_04 = true,
		T_De_Et_Shoes_05 = true,
		T_De_Et_Skirt_01 = true,
		T_De_Et_SkirtRedHero_01 = true,
		T_De_Et_SkirtRedHero_02 = true,
		T_He_Et_Amulet_01 = true,
		T_He_Et_Amulet_02 = true,
		T_He_Et_Ring_01 = true,
		T_He_Et_Ring_02 = true,
		T_Imp_Et_Amulet_01a = true,
		T_Imp_Et_Amulet_01b = true,
		T_Imp_Et_Amulet_01c = true,
		T_Imp_Et_Amulet_01d = true,
		T_Imp_Et_Amulet_02 = true,
		T_Imp_Et_Amulet_AdamantineWill = true,
		T_Imp_Et_Amulet_AstralThorns = true,
		T_Imp_Et_Amulet_Fortress = true,
		T_Imp_Et_Amulet_Foundation = true,
		T_Imp_Et_Amulet_Hailstorm = true,
		T_Imp_Et_Amulet_OpenDoors = true,
		T_Imp_Et_Amulet_Rakiv = true,
		T_Imp_Et_Amulet_RestlessBones = true,
		T_Imp_Et_Amulet_Runner = true,
		T_Imp_Et_Amulet_Sovereign = true,
		T_Imp_Et_Amulet_Stasis = true,
		T_Imp_Et_Amulet_Thunderstroke = true,
		T_Imp_Et_BeltCol_01 = true,
		T_Imp_Et_BeltCol_Brawler = true,
		T_Imp_Et_BeltCol_FourthBarrier = true,
		T_Imp_Et_BeltCol_Healing = true,
		T_Imp_Et_BeltCol_Infirmity = true,
		T_Imp_Et_PantsColWest_01 = true,
		T_Imp_Et_PantsColWest_02 = true,
		T_Imp_Et_PantsColWest_03 = true,
		T_Imp_Et_Robe_01 = true,
		T_Imp_Et_RobeNib_01 = true,
		T_Imp_Et_RobeNib_02 = true,
		T_Imp_Et_RobeNib_03 = true,
		T_Imp_Et_RobeNib_04 = true,
		T_Imp_Et_ShirtColWest_01 = true,
		T_Imp_Et_ShirtColWest_02 = true,
		T_Imp_Et_ShirtColWest_03 = true,
		T_Imp_Et_ShirtColWest_04 = true,
		T_Imp_Et_ShirtColWest_05 = true,
		T_Imp_Et_ShirtColWest_06 = true,
		T_Imp_Et_SkirtColWest_01 = true,
		T_Imp_Et_SkirtColWest_02 = true,
		T_Nor_Et_Amulet_01 = true,
		T_Nor_Et_Amulet_01_GreaterFort = true,
		T_Nor_Et_Amulet_02 = true,
		T_Nor_Et_Amulet_02_Nightspirit = true,
		T_Nor_Et_Belt_01 = true,
		T_Nor_Et_Belt_01_WardSteel = true,
		T_Nor_Et_Belt_02 = true,
		T_Nor_Et_Dress_01 = true,
		T_Nor_Et_Dress_02 = true,
		T_Nor_Et_Pants_01 = true,
		T_Nor_Et_Pants_02 = true,
		T_Nor_Et_Shirt_01 = true,
		T_Nor_Et_Shirt_02 = true,
		T_QyC_Et_Amulet_01 = true,
		T_Rga_Et_Ring_01 = true,
		T_Rga_Et_Ring_02 = true,
		T_Rga_Et_Robe_01 = true,
        },
        
        
        ingmine = {
        ingred_diamond_01 =  true,
        ingred_emerald_01 =  true,
        ingred_pearl_01 =  true,
        ingred_raw_ebony_01 =  true,
        ingred_ruby_01 =  true,
        ingred_adamantium_ore_01 =  true,
        ingred_raw_Stalhrim_01 =  true,
		AB_IngMine_Amber_01 = true,
		AB_IngMine_Amethyst_01 = true,
		AB_IngMine_BlackPearl_01 = true,
		AB_IngMine_BlackTourmaline_01 = true,
		AB_IngMine_BlueDiamond = true,
		AB_IngMine_Diopside_01 = true,
		AB_IngMine_Firejade_01 = true,
		AB_IngMine_Garnet_01 = true,
		AB_IngMine_GoldPearl_01 = true,
		AB_IngMine_Lodestone = true,
		AB_IngMine_Obsidian_01 = true,
		AB_IngMine_Peridot_01 = true,
		AB_IngMine_RedDiamond = true,
		AB_IngMine_Sapphire_01 = true,
		AB_IngMine_Sulphur = true,
		AB_IngMine_Topaz_01 = true,
		AB_IngMine_Tourmaline_01 = true,
		T_IngMine_Agate_01 = true,
		T_IngMine_Agate_02 = true,
		T_IngMine_Agate_03 = true,
		T_IngMine_Agate_04 = true,
		T_IngMine_Amber_01 = true,
		T_IngMine_AmberDae_01 = true,
		T_IngMine_Amethyst_01 = true,
		T_IngMine_AmethystDae_01 = true,
		T_IngMine_Ametrine_01 = true,
		T_IngMine_Antimony_01 = true,
		T_IngMine_Aquamarine_01 = true,
		T_IngMine_AquamarineDae_01 = true,
		T_IngMine_Arsenic_01 = true,
		T_IngMine_Bloodstone_01 = true,
		T_IngMine_BloodstoneDae_01 = true,
		T_IngMine_CaputMortuum_01 = true,
		T_IngMine_Charcoal_01 = true,
		T_IngMine_Citrine_01 = true,
		T_IngMine_Coal_01 = true,
		T_IngMine_DiamondDeTomb_01 = true,
		T_IngMine_EmeraldDeTomb_01 = true,
		T_IngMine_FireOpal_01 = true,
		T_IngMine_FoolsGold_01 = true,
		T_IngMine_Garnet_01 = true,
		T_IngMine_GarnetDae_01 = true,
		T_IngMine_IceCrystal_01 = true,
		T_IngMine_Jade_01 = true,
		T_IngMine_Jet_01 = true,
		T_IngMine_JetDae_01 = true,
		T_IngMine_KhajiitEye_01 = true,
		T_IngMine_KhajiitEyeDae_01 = true,
		T_IngMine_Lodestone_01 = true,
		T_IngMine_LunarCaustic_01 = true,
		T_IngMine_Malouchite_01 = true,
		T_IngMine_Moonstone_01 = true,
		T_IngMine_MoonstoneDae_01 = true,
		T_IngMine_Onyx_01 = true,
		T_IngMine_Opal_01 = true,
		T_IngMine_OpalDae_01 = true,
		T_IngMine_OreCopper_01 = true,
		T_IngMine_OreGold_01 = true,
		T_IngMine_OreGoldDae_01 = true,
		T_IngMine_OreIron_01 = true,
		T_IngMine_OreLead_01 = true,
		T_IngMine_OreOrichalcum_01 = true,
		T_IngMine_OreOrichalcum_02 = true,
		T_IngMine_OreQuicksilver_01 = true,
		T_IngMine_OreSilver_01 = true,
		T_IngMine_OreSulfur_01 = true,
		T_IngMine_OreTin_01 = true,
		T_IngMine_OreZinc_01 = true,
		T_IngMine_PearlBlack_01 = true,
		T_IngMine_PearlBlackDae_01 = true,
		T_IngMine_PearlDeTomb_01 = true,
		T_IngMine_PearlKardesh_01 = true,
		T_IngMine_Peridot_01 = true,
		T_IngMine_PeridotDae_01 = true,
		T_IngMine_Realgar_01 = true,
		T_IngMine_Rockcrystal_01 = true,
		T_IngMine_RockCrystalDae_01 = true,
		T_IngMine_RoseQuartz_01 = true,
		T_IngMine_RubyDeTomb_01 = true,
		T_IngMine_Salt_01 = true,
		T_IngMine_Sapphire_01 = true,
		T_IngMine_SapphireDae_01 = true,
		T_IngMine_SmokyQuartz_01 = true,
		T_IngMine_Spellstone_01 = true,
		T_IngMine_Spinel_01 = true,
		T_IngMine_SpinelDae_01 = true,
		T_IngMine_Tektite_01 = true,
		T_IngMine_TektiteDae_01 = true,
		T_IngMine_Topaz_01 = true,
		T_IngMine_TopazDae_01 = true,
		T_IngMine_Turquoise_01 = true,
		T_IngMine_TurquoiseDae_01 = true,
        },
        
        skillBooks = {
        
        },
        pottery = {
		misc_com_plate = true,
        
        },
        glass = {
		misc_de_bowl_glass_peach_01 = true,
		misc_de_bowl_glass_yellow_01 = true,
		Misc_DE_glass_green_01 = true,
		misc_de_glass_yellow_01 = true,
		misc_de_pot_glass_peach_01 = true,
		misc_de_pot_glass_peach_02 = true,
		T_Bre_GreenGlassBeaker_01 = true,
		T_Bre_GreenGlassBowl_01 = true,
		T_Bre_GreenGlassCup_01 = true,
		T_Bre_GreenGlassFlask_01 = true,
		T_Bre_GreenGlassGoblet_01 = true,
		T_Bre_GreenGlassPitcher_01 = true,
		T_Bre_GreenGlassPlate_01 = true,
		T_Bre_GreenGlassPlatter_01 = true,
		T_Bre_GreenGlassPot_01 = true,
		T_Bre_GreenGlassPot_02 = true,
		T_Bre_GreenGlassVase_01 = true,
		T_Bre_GreenGlassVase_02 = true,
		T_Bre_GreenGlassVase_03 = true,
		T_Bre_RedGlassBowl_01 = true,
		T_Bre_RedGlassBowl_02 = true,
		T_Bre_RedGlassCup_01 = true,
		T_Bre_RedGlassFork_01 = true,
		T_Bre_RedGlassGoblet_01 = true,
		T_Bre_RedGlassInkwell_01 = true,
		T_Bre_RedGlassKnife_01 = true,
		T_Bre_RedGlassPitcher_01 = true,
		T_Bre_RedGlassPlate_01 = true,
		T_Bre_RedGlassPlatter_01 = true,
		T_Bre_RedGlassPot_01 = true,
		T_Bre_RedGlassSpoon_01 = true,
		T_Bre_RedGlassVase_01 = true,
		T_Com_Hourglass_01 = true,
		T_Com_Spyglass01 = true,
		T_De_BlueGlassBowel_01 = true,
		T_De_BlueGlassBowl_01 = true,
		T_De_BlueGlassCup_01 = true,
		T_De_BlueGlassGlass_01 = true,
		T_De_Glass_Rod_01 = true,
		T_De_GreenGlassBowl_01 = true,
		T_De_GreenGlassBowl_02 = true,
		T_De_GreenGlassCup_01 = true,
		T_De_GreenGlassPitcher_01 = true,
		T_De_GreenGlassPlate_01 = true,
		T_De_GreenGlassPlatter_01 = true,
		T_De_GreenGlassPot_01 = true,
		T_De_PeachGlassCup_01 = true,
		T_De_PurpleGlassBowl_01 = true,
		T_De_PurpleGlassBowl_02 = true,
		T_De_PurpleGlassBowl_03 = true,
		T_De_PurpleGlassCup_01 = true,
		T_De_PurpleGlassCup_02 = true,
		T_De_PurpleGlassFlask_01 = true,
		T_De_PurpleGlassFlask_02 = true,
		T_De_PurpleGlassFork_01 = true,
		T_De_PurpleGlassKnife_01 = true,
		T_De_PurpleGlassPlate_01 = true,
		T_De_PurpleGlassPlatter_01 = true,
		T_De_PurpleGlassPot_01 = true,
		T_De_PurpleGlassPot_02 = true,
		T_De_PurpleGlassSpoon_01 = true,
		T_De_YellowGlassBowl01 = true,
		T_De_YellowGlassCup01 = true,
		T_De_YellowGlassFlask01 = true,
		T_De_YellowGlassPot01 = true,
		T_Qy_RedGlassBowl_01 = true,
		T_Qy_RedGlassBowl_02 = true,
		T_Qy_RedGlassBowl_03 = true,
		T_Qy_RedGlassCup_01 = true,
		T_Qy_RedGlassCup_02 = true,
		T_Qy_RedGlassFork = true,
		T_Qy_RedGlassKnife = true,
		T_Qy_RedGlassPitcher = true,
		T_Qy_RedGlassPlate_01 = true,
		T_Qy_RedGlassPlate_02 = true,
		T_Qy_RedGlassPlatter = true,
		T_Qy_RedGlassSpoon = true,
		T_Qy_RedGlassVase = true,
		T_Rga_GlasswareBowl_01 = true,
		T_Rga_GlasswareBowl_02 = true,
		T_Rga_GlasswarePlate_01 = true,

        },
        food = {
        food_kwama_egg_01 = true,
        food_kwama_egg_02 = true,
        ingred_scrib_jelly_01 = true,
        ingred_scrib_jerky_01 = true,
        ingred_ash_yam_01 = true,
        ingred_bread_01 = true,
        ingred_bread_01_UNI2 = true,
        ingred_bread_01_UNI3 = true,
        ingred_crab_meat_01 = true,
        ingred_saltrice_01 = true,
        ingred_scuttle_01 = true,
        AB_IngCrea_GuarMeat_01 = true,
        AB_IngCrea_HorseMeat01 = true,
        AB_IngCrea_SfMeat_01 = true,
        T_IngCrea_VelkNectarSack_01 = true,
        potion_comberry_brandy_01 = true,
        potion_comberry_wine_01 = true,
        Potion_Local_Brew_01 = true,
        potion_local_liquor_01 = true,
        ingred_marshmerrow_01 = true,
		T_We_Drink_PigmilkbeerJagga_01 = true,
		["ingred_hackle-lo_leaf_01"] = true,
		T_IngFood_AltachiPear_01 = true,
		T_IngFood_Apple_01 = true,
		T_IngFood_AppleSkyrim_01 = true,
		T_IngFood_Blackberry_01 = true,
		T_IngFood_Blueberry_01 = true,
		T_IngFood_Bread_01 = true,
		T_IngFood_Bread_02 = true,
		T_IngFood_Bread_03 = true,
		T_IngFood_BreadBretonLong_01 = true,
		T_IngFood_BreadBretonLong_02 = true,
		T_IngFood_BreadBretonLong_03 = true,
		T_IngFood_BreadColovian_01 = true,
		T_IngFood_BreadColovian_02 = true,
		T_IngFood_BreadDeshaan_01 = true,
		T_IngFood_BreadDeshaan_02 = true,
		T_IngFood_BreadDeshaan_03 = true,
		T_IngFood_BreadDeshaan_04 = true,
		T_IngFood_BreadDeshaan_05 = true,
		T_IngFood_BreadFlat_01 = true,
		T_IngFood_BreadFlat_02 = true,
		T_IngFood_BreadFlat_03 = true,
		T_IngFood_BreadKeptu_01 = true,
		T_IngFood_BreadKeptu_02 = true,
		T_IngFood_BreadKeptu_03 = true,
		T_IngFood_BreadNordRye_01 = true,
		T_IngFood_BreadNordRye_02 = true,
		T_IngFood_BreadNordRye_03 = true,
		T_IngFood_BreadRedguard_01 = true,
		T_IngFood_BreadRedguard_02 = true,
		T_IngFood_BreadRedguard_03 = true,
		T_IngFood_BridethornBerry_01 = true,
		T_IngFood_Cake_01 = true,
		T_IngFood_Carrot_01 = true,
		T_IngFood_CheeseBreton_01 = true,
		T_IngFood_CheeseBreton_02 = true,
		T_IngFood_CheeseColovian_01 = true,
		T_IngFood_CheeseNord_01 = true,
		T_IngFood_CheeseRedguard_01 = true,
		T_IngFood_CloudyCorn_01 = true,
		T_IngFood_Cookie_01 = true,
		T_IngFood_Cookie_02 = true,
		T_IngFood_Cracker_01 = true,
		T_IngFood_CustTartRedguard_01 = true,
		T_IngFood_EggChicken_01 = true,
		T_IngFood_EggMolecrab_01 = true,
		T_IngFood_EggOrnada_01 = true,
		T_IngFood_EggSeagull_01 = true,
		T_IngFood_Fig_01 = true,
		T_IngFood_Fig_Dried_01 = true,
		T_IngFood_FishBrowntrout_01 = true,
		T_IngFood_FishChrysophant_01 = true,
		T_IngFood_FishCod_01 = true,
		T_IngFood_FishCodDried_01 = true,
		T_IngFood_FishLeaperTail_01 = true,
		T_IngFood_FishLongfinFilet_01 = true,
		T_IngFood_FishPike_01 = true,
		T_IngFood_FishPikeperch_01 = true,
		T_IngFood_FishSalmon_01 = true,
		T_IngFood_FishSlaughterDried_01 = true,
		T_IngFood_FishSlaughterDried_02 = true,
		T_IngFood_FishSlaughterDried_03 = true,
		T_IngFood_FishSlaughterDried_04 = true,
		T_IngFood_FishSpr_01 = true,
		T_IngFood_FishStrid_01 = true,
		T_IngFood_Flour_01 = true,
		T_IngFood_Garlic_01 = true,
		T_IngFood_Gooseb01 = true,
		T_IngFood_Gorapple_01 = true,
		T_IngFood_Grape_01 = true,
		T_IngFood_Grape_02 = true,
		T_IngFood_GrapeWrothgarian_01 = true,
		T_IngFood_Hardtack_01 = true,
		T_IngFood_Honey_01 = true,
		T_IngFood_Indureta_01 = true,
		T_IngFood_Ironrye_01 = true,
		T_IngFood_Leek_01 = true,
		T_IngFood_LotteFruit_01 = true,
		T_IngFood_Lyco_01 = true,
		T_IngFood_Mango_01 = true,
		T_IngFood_MarmongPaste_01 = true,
		T_IngFood_MeatAlit_01 = true,
		T_IngFood_MeatArenthJerky_01 = true,
		T_IngFood_MeatBeef_01 = true,
		T_IngFood_MeatBoar_02 = true,
		T_IngFood_MeatChicken_01 = true,
		T_IngFood_MeatCliffracer_01 = true,
		T_IngFood_MeatDolphin_01 = true,
		T_IngFood_MeatGuar_01 = true,
		T_IngFood_MeatHam_01 = true,
		T_IngFood_MeatHorker_01 = true,
		T_IngFood_MeatHorse_01 = true,
		T_IngFood_MeatKagouti_01 = true,
		T_IngFood_MeatKwama_01 = true,
		T_IngFood_MeatMutton_01 = true,
		T_IngFood_MeatOrnada_01 = true,
		T_IngFood_MeatParastylus_01 = true,
		T_IngFood_MeatPork_01 = true,
		T_IngFood_MeatSqrl_01 = true,
		T_IngFood_MeatVenison_01 = true,
		T_IngFood_Mokre_01 = true,
		T_IngFood_NoodlesEsriWheat_01 = true,
		T_IngFood_NoodlesYnesaiRice_01 = true,
		T_IngFood_Olives_01 = true,
		T_IngFood_Onion_01 = true,
		T_IngFood_PassionFruit_01 = true,
		T_IngFood_PastryFrRedguard_01 = true,
		T_IngFood_Plum_01 = true,
		T_IngFood_Pomegranate_01 = true,
		T_IngFood_PoppadGourd_01 = true,
		T_IngFood_PorridgePalm_01 = true,
		T_IngFood_Potato_01 = true,
		T_IngFood_Radish_01 = true,
		T_IngFood_Rice_01 = true,
		T_IngFood_RiceCake_01 = true,
		T_IngFood_RiverstriderEgg_01 = true,
		T_IngFood_Scone_01 = true,
		T_IngFood_ScribPie_01 = true,
		T_IngFood_Sfiha_01 = true,
		T_IngFood_Sfiha_02 = true,
		T_IngFood_SilverPalmfruit_01 = true,
		T_IngFood_Siyat_02 = true,
		T_IngFood_Snowberry_01 = true,
		T_IngFood_Strawberry_01 = true,
		T_IngFood_Sweetroll_01 = true,
		T_IngFood_TartRedguard_01 = true,
		T_IngFood_TGuarHide = true,
		T_IngFood_Tomato_01 = true,
		T_IngFood_TrinityFruit_01 = true,
		T_IngFood_UNI_ChocoMuffin = true,
		T_IngFood_Vinegar_01 = true,
		T_IngFood_WasabiRoot_01 = true,
		T_IngFood_Wheat_01 = true,
		
		ingred_crab_meat_01 = true,
		ingred_durzog_meat_01 = true,
		ingred_hound_meat_01 = true,
		ingred_rat_meat_01 = true,
		T_IngCrea_ClamMeat = true,
		T_IngCrea_HopperMeat = true,
		T_IngCrea_MeatDark_01 = true,
		T_IngCrea_OysterMeat_01 = true,
		T_IngCrea_OysterMeat_02 = true,
		T_IngCrea_RedSharkMeat_01 = true,
		T_IngCrea_SeaUrchinMeat_01 = true,
		T_IngCrea_SilverSpadeMeat_01 = true,
		T_IngCrea_SturgeonMeat_01 = true,
		T_IngFood_MeatAlit_01 = true,
		T_IngFood_MeatArenthJerky_01 = true,
		T_IngFood_MeatBeef_01 = true,
		T_IngFood_MeatBoar_02 = true,
		T_IngFood_MeatChicken_01 = true,
		T_IngFood_MeatCliffracer_01 = true,
		T_IngFood_MeatDolphin_01 = true,
		T_IngFood_MeatGuar_01 = true,
		T_IngFood_MeatHam_01 = true,
		T_IngFood_MeatHorker_01 = true,
		T_IngFood_MeatHorse_01 = true,
		T_IngFood_MeatKagouti_01 = true,
		T_IngFood_MeatKwama_01 = true,
		T_IngFood_MeatMutton_01 = true,
		T_IngFood_MeatOrnada_01 = true,
		T_IngFood_MeatParastylus_01 = true,
		T_IngFood_MeatPork_01 = true,
		T_IngFood_MeatSqrl_01 = true,
		T_IngFood_MeatVenison_01 = true,
        },

        cyrodimp = {
                potion_cyro_brandy_01 = true,
                Potion_Cyro_Whiskey_01 = true,
		["imperial broadsword"] = true,
		["imperial netch blade"] = true,
		["imperial shortsword"] = true,
		["imperial shortsword severio"] = true,
		["imperial boots"] = true,
		["imperial cuirass_armor"] = true,
		["imperial helmet armor"] = true,
		["imperial helmet armor_Dae_curse"] = true,
		["imperial left gauntlet"] = true,
		["imperial left pauldron"] = true,
		["imperial right gauntlet"] = true,
		["imperial right pauldron"] = true,
		["imperial shield"] = true,
		silver_cuirass = true,
		silver_dukesguard_cuirass = true,
		silver_helm = true,
		
		T_Com_Et_Hat_Imperious = true,
		T_Imp_AlessianBrnz_Boots_01 = true,
		T_Imp_AlessianBrnz_Cuirass_01 = true,
		T_Imp_AlessianBrnz_GauntletL_01 = true,
		T_Imp_AlessianBrnz_GauntletR_01 = true,
		T_Imp_AlessianBrnz_Helm_01 = true,
		T_Imp_AlessianBrnz_PauldronL_01 = true,
		T_Imp_AlessianBrnz_PauldronR_01 = true,
		T_Imp_AlessianBrnz_TShield_01 = true,
		T_Imp_Chain_Boots_01 = true,
		T_Imp_Chain_GauntletL_01 = true,
		T_Imp_Chain_GauntletR_02 = true,
		T_Imp_Chainmail_cuirass_01 = true,
		T_Imp_Chainmail_cuirass_02 = true,
		T_Imp_Chainmail_cuirass_03 = true,
		T_Imp_Chainmail_cuirass_04 = true,
		T_Imp_Chainmail_Helm_01 = true,
		T_Imp_Chainmail_Helm_02 = true,
		T_Imp_Chainmail_Helm_03 = true,
		T_Imp_Chainmail_Helm_04 = true,
		T_Imp_Cm_BootsCol_01 = true,
		T_Imp_Cm_BootsCol_02 = true,
		T_Imp_Cm_BootsCol_03 = true,
		T_Imp_Cm_BootsCol_04 = true,
		T_Imp_Cm_HatColWest_01 = true,
		T_Imp_Cm_HatColWest_02 = true,
		T_Imp_ColBronzeOld_Helm_01 = true,
		T_Imp_ColFur_Boots_01 = true,
		T_Imp_ColFur_Boots_02 = true,
		T_Imp_ColFur_Boots_03 = true,
		T_Imp_ColFur_Boots_04 = true,
		T_Imp_ColFur_Cuirass_01 = true,
		T_Imp_ColFur_Cuirass_02 = true,
		T_Imp_ColFur_Cuirass_03 = true,
		T_Imp_ColFur_Cuirass_04 = true,
		T_Imp_ColFur_GauntL_01 = true,
		T_Imp_ColFur_GauntL_02 = true,
		T_Imp_ColFur_GauntL_03 = true,
		T_Imp_ColFur_GauntL_04 = true,
		T_Imp_ColFur_GauntR_01 = true,
		T_Imp_ColFur_GauntR_02 = true,
		T_Imp_ColFur_GauntR_03 = true,
		T_Imp_ColFur_GauntR_04 = true,
		T_Imp_ColFur_HelmBl_01 = true,
		T_Imp_ColFur_HelmEx_01 = true,
		T_Imp_ColFur_HelmR_01 = true,
		T_Imp_ColFur_HelmTiger_01 = true,
		T_Imp_ColGoatHide_Boots_01 = true,
		T_Imp_ColGoatHide_Greaves_01 = true,
		T_Imp_ColGoatHide_Helmet_01 = true,
		T_Imp_ColIron_Boots_01 = true,
		T_Imp_ColIron_BracerL_01 = true,
		T_Imp_ColIron_BracerR_01 = true,
		T_Imp_ColIron_Cuirass_01 = true,
		T_Imp_ColIron_Greaves_01 = true,
		T_Imp_ColIron_Helmet_01 = true,
		T_Imp_ColIron_Helmet_02 = true,
		T_Imp_ColIron_PauldronL_01 = true,
		T_Imp_ColIron_PauldronR_01 = true,
		T_Imp_ColIron1_Boots_01 = true,
		T_Imp_ColIron1_Boots_02 = true,
		T_Imp_ColIron1_Boots_03 = true,
		T_Imp_ColIron1_Boots_04 = true,
		T_Imp_ColIron1_Cuirass_01 = true,
		T_Imp_ColIron1_Cuirass_02 = true,
		T_Imp_ColIron1_Cuirass_03 = true,
		T_Imp_ColIron1_Cuirass_04 = true,
		T_Imp_ColIron1_GauntletL_01 = true,
		T_Imp_ColIron1_GauntletL_02 = true,
		T_Imp_ColIron1_GauntletL_03 = true,
		T_Imp_ColIron1_GauntletL_04 = true,
		T_Imp_ColIron1_GauntletR_01 = true,
		T_Imp_ColIron1_GauntletR_02 = true,
		T_Imp_ColIron1_GauntletR_03 = true,
		T_Imp_ColIron1_GauntletR_04 = true,
		T_Imp_ColIron1_Greaves_01 = true,
		T_Imp_ColIron1_Greaves_02 = true,
		T_Imp_ColIron1_Greaves_03 = true,
		T_Imp_ColIron1_Greaves_04 = true,
		T_Imp_ColIron1_Helm_01 = true,
		T_Imp_ColIron1_Helm_02 = true,
		T_Imp_ColIron1_Helm_03 = true,
		T_Imp_ColIron1_Helm_04 = true,
		T_Imp_ColIron1_PauldronL_01 = true,
		T_Imp_ColIron1_PauldronL_02 = true,
		T_Imp_ColIron1_PauldronL_03 = true,
		T_Imp_ColIron1_PauldronL_04 = true,
		T_Imp_ColIron1_PauldronR_01 = true,
		T_Imp_ColIron1_PauldronR_02 = true,
		T_Imp_ColIron1_PauldronR_03 = true,
		T_Imp_ColIron1_PauldronR_04 = true,
		T_Imp_ColIron2_Boots_01 = true,
		T_Imp_ColIron2_BracerL_01 = true,
		T_Imp_ColIron2_BracerR_01 = true,
		T_Imp_ColIron2_Cuirass_01 = true,
		T_Imp_ColIron2_Greaves_01 = true,
		T_Imp_ColIron2_Helm_01 = true,
		T_Imp_ColIron2_PauldronL_01 = true,
		T_Imp_ColIron2_PauldronR_01 = true,
		T_Imp_ColLamellar_Boots_01 = true,
		T_Imp_ColLamellar_BracerL_01 = true,
		T_Imp_ColLamellar_BracerR_01 = true,
		T_Imp_ColLamellar_Cuirass_01 = true,
		T_Imp_ColLamellar_Greaves_01 = true,
		T_Imp_ColLamellar_Helm_01 = true,
		T_Imp_ColLamellar_HelmOpen_01 = true,
		T_Imp_ColLamellar_MaskHelm_01 = true,
		T_Imp_ColLamellar_MaskHelm_02 = true,
		T_Imp_ColLamellar_PauldronL_01 = true,
		T_Imp_ColLamellar_PauldronR_01 = true,
		T_Imp_ColLeather_Boots_01 = true,
		T_Imp_ColLeather_Boots_02 = true,
		T_Imp_ColLeather_BracerL_01 = true,
		T_Imp_ColLeather_BracerL_02 = true,
		T_Imp_ColLeather_BracerR_01 = true,
		T_Imp_ColLeather_BracerR_02 = true,
		T_Imp_ColLeather_Cuirass_01 = true,
		T_Imp_ColLeather_Cuirass_02 = true,
		T_Imp_ColLeather_Greaves_01 = true,
		T_Imp_ColLeather_Greaves_02 = true,
		T_Imp_ColLeather_Helm_01 = true,
		T_Imp_ColLeather_Helm_02 = true,
		T_Imp_ColLeather_PauldronL_01 = true,
		T_Imp_ColLeather_PauldronL_02 = true,
		T_Imp_ColLeather_PauldronR_01 = true,
		T_Imp_ColLeather_PauldronR_02 = true,
		T_Imp_ColSteel_Boots_01 = true,
		T_Imp_ColSteel_Boots_02 = true,
		T_Imp_ColSteel_Boots_03 = true,
		T_Imp_ColSteel_Boots_04 = true,
		T_Imp_ColSteel_BracerL_03 = true,
		T_Imp_ColSteel_BracerL_04 = true,
		T_Imp_ColSteel_BracerR_03 = true,
		T_Imp_ColSteel_BracerR_04 = true,
		T_Imp_ColSteel_Cuirass_01 = true,
		T_Imp_ColSteel_Cuirass_02 = true,
		T_Imp_ColSteel_Cuirass_03 = true,
		T_Imp_ColSteel_Cuirass_04 = true,
		T_Imp_ColSteel_GauntletL_01 = true,
		T_Imp_ColSteel_GauntletL_02 = true,
		T_Imp_ColSteel_GauntletR_01 = true,
		T_Imp_ColSteel_GauntletR_02 = true,
		T_Imp_ColSteel_Greaves_01 = true,
		T_Imp_ColSteel_Greaves_02 = true,
		T_Imp_ColSteel_Greaves_03 = true,
		T_Imp_ColSteel_Greaves_04 = true,
		T_Imp_ColSteel_Helm_01 = true,
		T_Imp_ColSteel_Helm_02 = true,
		T_Imp_ColSteel_Helm_03 = true,
		T_Imp_ColSteel_Helm_04 = true,
		T_Imp_ColSteel_Helm_05 = true,
		T_Imp_ColSteel_Helm_06 = true,
		T_Imp_ColSteel_PauldronL_01 = true,
		T_Imp_ColSteel_PauldronL_02 = true,
		T_Imp_ColSteel_PauldronL_03 = true,
		T_Imp_ColSteel_PauldronL_04 = true,
		T_Imp_ColSteel_PauldronR_01 = true,
		T_Imp_ColSteel_PauldronR_02 = true,
		T_Imp_ColSteel_PauldronR_03 = true,
		T_Imp_ColSteel_PauldronR_04 = true,
		T_Imp_ColSteel1_Boots_01 = true,
		T_Imp_ColSteel1_Boots_02 = true,
		T_Imp_ColSteel1_Boots_03 = true,
		T_Imp_ColSteel1_Boots_04 = true,
		T_Imp_ColSteel1_BracerL_01 = true,
		T_Imp_ColSteel1_BracerL_02 = true,
		T_Imp_ColSteel1_BracerL_03 = true,
		T_Imp_ColSteel1_BracerL_04 = true,
		T_Imp_ColSteel1_BracerR_01 = true,
		T_Imp_ColSteel1_BracerR_02 = true,
		T_Imp_ColSteel1_BracerR_03 = true,
		T_Imp_ColSteel1_BracerR_04 = true,
		T_Imp_ColSteel1_Cuirass_01 = true,
		T_Imp_ColSteel1_Cuirass_02 = true,
		T_Imp_ColSteel1_Cuirass_03 = true,
		T_Imp_ColSteel1_Cuirass_04 = true,
		T_Imp_ColSteel1_Greaves_01 = true,
		T_Imp_ColSteel1_Greaves_02 = true,
		T_Imp_ColSteel1_Greaves_03 = true,
		T_Imp_ColSteel1_Greaves_04 = true,
		T_Imp_ColSteel1_Helm_01 = true,
		T_Imp_ColSteel1_Helm_02 = true,
		T_Imp_ColSteel1_Helm_03 = true,
		T_Imp_ColSteel1_Helm_04 = true,
		T_Imp_ColSteel1_PauldronL_01 = true,
		T_Imp_ColSteel1_PauldronL_02 = true,
		T_Imp_ColSteel1_PauldronL_03 = true,
		T_Imp_ColSteel1_PauldronL_04 = true,
		T_Imp_ColSteel1_PauldronR_01 = true,
		T_Imp_ColSteel1_PauldronR_02 = true,
		T_Imp_ColSteel1_PauldronR_03 = true,
		T_Imp_ColSteel1_PauldronR_04 = true,
		T_Imp_Domina_Boots_01 = true,
		T_Imp_Domina_Cuirass_01 = true,
		T_Imp_Domina_GauntletL_01 = true,
		T_Imp_Domina_GauntletR_01 = true,
		T_Imp_Domina_Greaves_01 = true,
		T_Imp_Domina_Helm_01 = true,
		T_Imp_Domina_PauldronL_01 = true,
		T_Imp_Domina_PauldronR_01 = true,
		T_Imp_Dragonscale_BarcerL_01 = true,
		T_Imp_Dragonscale_BarcerR_01 = true,
		T_Imp_Dragonscale_Boots_01 = true,
		T_Imp_Dragonscale_BracerL_01 = true,
		T_Imp_Dragonscale_BracerR_01 = true,
		T_Imp_Dragonscale_cuirass_01 = true,
		T_Imp_Dragonscale_Greaves_01 = true,
		T_Imp_Dragonscale_helm_01 = true,
		T_Imp_Dragonscale_PauldronL_01 = true,
		T_Imp_Dragonscale_PauldronR_01 = true,
		T_Imp_Ebonweave_Boots_01 = true,
		T_Imp_Ebonweave_BracerL_01 = true,
		T_Imp_Ebonweave_BracerR_01 = true,
		T_Imp_Ebonweave_Cuirass_01 = true,
		T_Imp_Ebonweave_Greaves_01 = true,
		T_Imp_Ebonweave_Helm_01 = true,
		T_Imp_Ebonweave_Helm_02 = true,
		T_Imp_Ebonweave_PauldronL_01 = true,
		T_Imp_Ebonweave_PauldronR_01 = true,
		T_Imp_Ebony_Boots = true,
		T_Imp_Ebony_BracerL = true,
		T_Imp_Ebony_BracerR = true,
		T_Imp_Ebony_Cuirass = true,
		T_Imp_Ebony_Helmet_01 = true,
		T_Imp_Ebony_Helmet_02 = true,
		T_Imp_Ebony_Helmet_02b = true,
		T_Imp_Ebony_Helmet_03 = true,
		T_Imp_Ebony_Helmet_03b = true,
		T_Imp_Ebony_PauldronL = true,
		T_Imp_Ebony_PauldronR = true,
		T_Imp_Ebony_ShieldTower_01 = true,
		T_Imp_Ep_Hat_02 = true,
		T_Imp_Ep_HatColWest_01 = true,
		T_Imp_Ep_HatColWest_02 = true,
		T_Imp_Ep_HatColWest_03 = true,
		T_Imp_Ep_HatColWest_04 = true,
		T_Imp_Et_HatColNorth_01 = true,
		T_Imp_Et_HatColNorth_02 = true,
		T_Imp_Et_HatColNorth_03 = true,
		T_Imp_Et_HatColNorth_04 = true,
		T_Imp_Et_HatColNorth_05 = true,
		T_Imp_Gold_Boots_02 = true,
		T_Imp_Gold_BracerL_02 = true,
		T_Imp_Gold_BracerR_02 = true,
		T_Imp_Gold_Cuirass_01 = true,
		T_Imp_Gold_Cuirass_02 = true,
		T_Imp_Gold_GauntletL_02 = true,
		T_Imp_Gold_GauntletR_02 = true,
		T_Imp_Gold_Greaves_02 = true,
		T_Imp_Gold_Helm_01 = true,
		T_Imp_Gold_Helm_02 = true,
		T_Imp_Gold_PauldronL_01 = true,
		T_Imp_Gold_PauldronL_02 = true,
		T_Imp_Gold_PauldronR_01 = true,
		T_Imp_Gold_PauldronR_02 = true,
		T_Imp_Gold_Shield_01 = true,
		T_Imp_Gold_ShieldBuckler_01 = true,
		T_Imp_GuardSutch_Cuirass_01 = true,
		T_Imp_GuardSutch_GauntletL_01 = true,
		T_Imp_GuardSutch_GauntletR_01 = true,
		T_Imp_GuardSutch_Helm_01 = true,
		T_Imp_GuardSutch_PauldrL_01 = true,
		T_Imp_GuardSutch_PauldrR_01 = true,
		T_Imp_GuardSutch_ShieldTow_01 = true,
		T_Imp_GuardTown1_Boots_01 = true,
		T_Imp_GuardTown1_Cuirass_01 = true,
		T_Imp_GuardTown1_GauntletL_01 = true,
		T_Imp_GuardTown1_GauntletR_01 = true,
		T_Imp_GuardTown1_Greaves_01 = true,
		T_Imp_GuardTown1_Helm_01 = true,
		T_Imp_GuardTown1_HelmAnv_01 = true,
		T_Imp_GuardTown1_HelmStr_01 = true,
		T_Imp_GuardTown1_HelmSut_01 = true,
		T_Imp_GuardTown1_PauldrL_01 = true,
		T_Imp_GuardTown1_PauldrR_01 = true,
		T_Imp_GuardTown1_ShieldAnv_01 = true,
		T_Imp_GuardTown2_Boots_01 = true,
		T_Imp_GuardTown2_Cuirass_01 = true,
		T_Imp_GuardTown2_GauntletL_01 = true,
		T_Imp_GuardTown2_GauntletR_01 = true,
		T_Imp_GuardTown2_Greaves_01 = true,
		T_Imp_GuardTown2_Helm_01 = true,
		T_Imp_GuardTown2_HelmArt_01 = true,
		T_Imp_GuardTown2_HelmBru_01 = true,
		T_Imp_GuardTown2_HelmCho_01 = true,
		T_Imp_GuardTown2_PauldrL_01 = true,
		T_Imp_GuardTown2_PauldrR_01 = true,
		T_Imp_GuardTown3_Boots_01 = true,
		T_Imp_GuardTown3_Cuirass_01 = true,
		T_Imp_GuardTown3_GauntletL_01 = true,
		T_Imp_GuardTown3_GauntletR_01 = true,
		T_Imp_GuardTown3_Greaves_01 = true,
		T_Imp_GuardTown3_Helm_01 = true,
		T_Imp_GuardTown3_HelmKva_01 = true,
		T_Imp_GuardTown3_HelmSar_01 = true,
		T_Imp_GuardTown3_HelmSkn_01 = true,
		T_Imp_GuardTown3_PauldrL_01 = true,
		T_Imp_GuardTown3_PauldrR_01 = true,
		T_Imp_Mananaut_Helm_01 = true,
		T_Imp_Militia_Boots_01 = true,
		T_Imp_Militia_Cuirass_01 = true,
		T_Imp_Militia_GauntL_01 = true,
		T_Imp_Militia_GauntR_01 = true,
		T_Imp_Militia_Greaves_01 = true,
		T_Imp_Militia_Helm_01 = true,
		T_Imp_Militia_PauldronL_01 = true,
		T_Imp_Militia_PauldronR_01 = true,
		T_Imp_MothHerder_Helmet_01 = true,
		T_Imp_NavyOff_Boots_01 = true,
		T_Imp_NavyOff_BracerL_01 = true,
		T_Imp_NavyOff_BracerR_01 = true,
		T_Imp_NavyOff_Cuirass_01 = true,
		T_Imp_NavyOff_Greaves_01 = true,
		T_Imp_NavyOff_Helmet_01 = true,
		T_Imp_NavyOff_PauldronL_01 = true,
		T_Imp_NavyOff_PauldronR_01 = true,
		T_Imp_NavyStud_Boots_01 = true,
		T_Imp_NavyStud_Cuirass_01 = true,
		T_Imp_NavyStud_GauntletL_01 = true,
		T_Imp_NavyStud_GauntletR_01 = true,
		T_Imp_NavyStud_Helm_01 = true,
		T_Imp_NavyStud_PauldrL_01 = true,
		T_Imp_NavyStud_PauldrR_01 = true,
		T_Imp_Newtscale_Boots_01 = true,
		T_Imp_Newtscale_Cuirass_01 = true,
		T_Imp_Newtscale_GauntletL_01 = true,
		T_Imp_Newtscale_GauntletR_01 = true,
		T_Imp_Newtscale_Greaves_01 = true,
		T_Imp_Newtscale_Helm_01 = true,
		T_Imp_Newtscale_PauldronL_01 = true,
		T_Imp_Newtscale_PauldronR_01 = true,
		T_Imp_NibBronze_Boots_01 = true,
		T_Imp_NibBronze_BracerL_01 = true,
		T_Imp_NibBronze_BracerR_01 = true,
		T_Imp_NibBronze_Cuirass_01 = true,
		T_Imp_NibBronze_Greaves_01 = true,
		T_Imp_NibBronze_Helm_01 = true,
		T_Imp_NibBronze_PauldronL_01 = true,
		T_Imp_NibBronze_PauldronR_01 = true,
		T_Imp_Reman_Boots_01 = true,
		T_Imp_Reman_BracerL_01 = true,
		T_Imp_Reman_BracerR_01 = true,
		T_Imp_Reman_Cuirass_01 = true,
		T_Imp_Reman_Greaves_01 = true,
		T_Imp_Reman_Helm_01 = true,
		T_Imp_Reman_PauldronL_01 = true,
		T_Imp_Reman_PauldronR_01 = true,
		T_Imp_Reman_Shield_01 = true,
		T_Imp_Silver_Boots_01 = true,
		T_Imp_Silver_BracerL_01 = true,
		T_Imp_Silver_BracerR_01 = true,
		T_Imp_Silver_Cap_01 = true,
		T_Imp_Silver_Cap_02 = true,
		T_Imp_Silver_CuirassFW_01 = true,
		T_Imp_Silver_CuirassRed_01 = true,
		T_Imp_Silver_Greaves_01 = true,
		T_Imp_Silver_Helm_Mask = true,
		T_Imp_Silver_PauldronL_01 = true,
		T_Imp_Silver_PauldronR_01 = true,
		T_imp_SilverWareBell_01 = true,
		T_Imp_StuddedLeather_Boots_01 = true,
		T_Imp_StuddedLeather_BracerL_01 = true,
		T_Imp_StuddedLeather_BracerR_01 = true,
		T_Imp_StuddedLeather_cuirass_02 = true,
		T_Imp_StuddedLeather_cuirass_03 = true,
		T_Imp_StuddedLeather_Greaves_01 = true,
		T_Imp_StuddedLeather_Helm_01 = true,
		T_Imp_StuddedLeather_Helm_02 = true,
		T_Imp_StuddedLeather_Helm_03 = true,
		T_Imp_StuddedLeather_PauldrL_01 = true,
		T_Imp_StuddedLeather_PauldrR_01 = true,
		T_Imp_Templar_ShieldTower_01 = true,
		
		T_Imp_AlessianBronze_Falcata_01 = true,
		T_Imp_Barrow_Axe_01 = true,
		T_Imp_Barrow_Spear_01 = true,
		T_Imp_Barrow_Sword_01 = true,
		T_Imp_Cane_M = true,
		T_Imp_Cane_P = true,
		T_Imp_Cane_R = true,
		T_Imp_Cane_R_ShockCudgel = true,
		T_Imp_Col_House_Sword_01 = true,
		T_Imp_Executioners_Axe = true,
		T_Imp_Legion_Arrow_01 = true,
		T_Imp_Legion_Battleaxe_01 = true,
		T_Imp_Legion_Bolt_01 = true,
		T_Imp_Legion_Broadsword_01 = true,
		T_Imp_Legion_Broadsword_02 = true,
		T_Imp_Legion_Broadsword_03 = true,
		T_Imp_Legion_Broadsword_Biting = true,
		T_Imp_Legion_Broadsword_Fire = true,
		T_Imp_Legion_Broadsword_Firmam = true,
		T_Imp_Legion_Broadsword_Frost = true,
		T_Imp_Legion_Broadsword_Poison = true,
		T_Imp_Legion_Broadsword_Shock = true,
		T_Imp_Legion_Broadsword_Uncert = true,
		T_Imp_Legion_Broadsword_Unnatur = true,
		T_Imp_Legion_BroadswordBroke_01 = true,
		T_Imp_Legion_Claymore_01 = true,
		T_Imp_Legion_Claymore_Fire = true,
		T_Imp_Legion_Claymore_Frost = true,
		T_Imp_Legion_Claymore_Poison = true,
		T_Imp_Legion_Claymore_Shock = true,
		T_Imp_Legion_Club_01 = true,
		T_Imp_Legion_Crossbow_01 = true,
		T_Imp_Legion_Crossbow_Pursuit = true,
		T_Imp_Legion_Dagger_01 = true,
		T_Imp_Legion_Dagger_02 = true,
		T_Imp_Legion_Dagger_Patrol = true,
		T_Imp_Legion_Daikatana_01 = true,
		T_Imp_Legion_Dart_01 = true,
		T_Imp_Legion_GSword_01 = true,
		T_Imp_Legion_Halberd_01 = true,
		T_Imp_Legion_Halberd_Fire = true,
		T_Imp_Legion_Halberd_Frost = true,
		T_Imp_Legion_Halberd_Poison = true,
		T_Imp_Legion_Halberd_Shock = true,
		T_Imp_Legion_Katana_01 = true,
		T_Imp_Legion_Knife_01 = true,
		T_Imp_Legion_Longspear_01 = true,
		T_Imp_Legion_Longsword_01 = true,
		T_Imp_Legion_Mace_01 = true,
		T_Imp_Legion_Mace_Fire = true,
		T_Imp_Legion_Mace_Frost = true,
		T_Imp_Legion_Mace_Poison = true,
		T_Imp_Legion_Mace_Shock = true,
		T_Imp_Legion_Naginata_01 = true,
		T_Imp_Legion_RoyalLongsword_01 = true,
		T_Imp_Legion_Saber_01 = true,
		T_Imp_Legion_Saber_Fire = true,
		T_Imp_Legion_Saber_Frost = true,
		T_Imp_Legion_Saber_Poison = true,
		T_Imp_Legion_Saber_Shock = true,
		T_Imp_Legion_Shortsword_01 = true,
		T_Imp_Legion_Shortsword_Fire = true,
		T_Imp_Legion_Shortsword_Frost = true,
		T_Imp_Legion_Shortsword_Poison = true,
		T_Imp_Legion_Shortsword_Shock = true,
		T_Imp_Legion_ShortswordBroke_01 = true,
		T_Imp_Legion_Spear_01 = true,
		T_Imp_Legion_Spear_Fire = true,
		T_Imp_Legion_Spear_Frost = true,
		T_Imp_Legion_Spear_Poison = true,
		T_Imp_Legion_Spear_Shock = true,
		T_Imp_Legion_Star_01 = true,
		T_Imp_Legion_Tanto_01 = true,
		T_Imp_Legion_Wakizashi_01 = true,
		T_Imp_Legion_WarAxe_01 = true,
		T_Imp_Legion_WarAxe_Fire = true,
		T_Imp_Legion_WarAxe_Frost = true,
		T_Imp_Legion_WarAxe_Poison = true,
		T_Imp_Legion_WarAxe_Shock = true,
		T_Imp_Legion_Warhammer_01 = true,
		T_Imp_Legion_Warhammer_Fire = true,
		T_Imp_Legion_Warhammer_Frost = true,
		T_Imp_Legion_Warhammer_Poison = true,
		T_Imp_Legion_Warhammer_Shock = true,
		T_Imp_Nibenese_Daikatana_01 = true,
		T_Imp_Nibenese_Katana_01 = true,
		T_Imp_Reman_Broadsword_01 = true,
		T_Imp_Reman_Javelin_01 = true,
		T_Imp_Reman_Mace_01 = true,
		T_Imp_Reman_Shortsword_01 = true,
		T_Imp_Reman_Spear_01 = true,
		T_Imp_Silver_2HMace = true,
		T_Imp_Silver_Arrow_DireFirestrm = true,
		T_Imp_Silver_Arrow_DireFrostBst = true,
		T_Imp_Silver_Arrow_DirePoisonCl = true,
		T_Imp_Silver_Arrow_DireShocksph = true,
		T_Imp_Silver_Battleaxe_01 = true,
		T_Imp_Silver_Bolt_DireFirestrm = true,
		T_Imp_Silver_Bolt_DireFrostBst = true,
		T_Imp_Silver_Bolt_DirePoisonCl = true,
		T_Imp_Silver_Bolt_DireShocksph = true,
		T_Imp_Silver_Broadsword_01 = true,
		T_Imp_Silver_Claymore_AugFleet = true,
		T_Imp_Silver_Claymore_AugWis = true,
		T_Imp_Silver_Dagger_01 = true,
		T_Imp_Silver_Dagger_02 = true,
		T_Imp_Silver_Dagger_AugGreenWis = true,
		T_Imp_Silver_Dagger_AugStalk = true,
		T_Imp_Silver_Dagger_Prowess = true,
		T_Imp_Silver_DaggerBroken_01 = true,
		T_Imp_Silver_DaiKatana_01 = true,
		T_Imp_Silver_Dart_DireFirestrm = true,
		T_Imp_Silver_Dart_DireFrostBst = true,
		T_Imp_Silver_Dart_DirePoisonCl = true,
		T_Imp_Silver_Dart_DireShocksph = true,
		T_Imp_Silver_GSword_01 = true,
		T_Imp_Silver_Halberd_01 = true,
		T_Imp_Silver_Javelin_AugHorker = true,
		T_Imp_Silver_Katana_01 = true,
		T_Imp_Silver_Longbow_01 = true,
		T_Imp_Silver_Longhammer_01 = true,
		T_Imp_Silver_Longhammer_Fire = true,
		T_Imp_Silver_Longhammer_Frost = true,
		T_Imp_Silver_Longhammer_Poison = true,
		T_Imp_Silver_Longhammer_Shock = true,
		T_Imp_Silver_Longspear_01 = true,
		T_Imp_Silver_Longsword_AugGoldW = true,
		T_Imp_Silver_Longsword_AugSurpr = true,
		T_Imp_Silver_Mace_01 = true,
		T_Imp_Silver_Mace_02 = true,
		T_Imp_Silver_Mace_AugDeepCrush = true,
		T_Imp_Silver_Mace_Blessed = true,
		T_Imp_Silver_Saber_01 = true,
		T_Imp_Silver_Saber_02 = true,
		T_Imp_Silver_Saber_AugSwiftbl = true,
		T_Imp_Silver_Shortsword_AugSwim = true,
		T_Imp_Silver_Shortsword_AugSWis = true,
		T_Imp_Silver_Spear_Paralysis = true,
		T_Imp_Silver_Spear_Retribution = true,
		T_Imp_Silver_StaffAncestors_01 = true,
		T_Imp_Silver_Tanto_01 = true,
		T_Imp_Silver_ThrowingKnife_01 = true,
		T_Imp_Silver_ThrowingKnife_Fire = true,
		T_Imp_Silver_ThrowingKnife_Fros = true,
		T_Imp_Silver_ThrowingKnife_Pois = true,
		T_Imp_Silver_ThrowingKnife_Shoc = true,
		T_Imp_Silver_ThrowingStar_DrFrB = true,
		T_Imp_Silver_ThrowingStar_DrFSt = true,
		T_Imp_Silver_ThrowingStar_DrPoi = true,
		T_Imp_Silver_ThrowingStar_DrShk = true,
		T_Imp_Silver_Truncheon_01 = true,
		T_Imp_Silver_Truncheon_Blessed = true,
		T_Imp_Silver_Truncheon_Judgment = true,
		T_Imp_Silver_Wakizashi_01 = true,
		T_Imp_Silver_WarAxe_AugHew = true,
		T_Imp_Silver_Warhammer_01 = true,
		T_Imp_Templar_Battleaxe_01 = true,
		T_Imp_Templar_Dagger_01 = true,
		T_Imp_Templar_Longspear_01 = true,
		T_Imp_Templar_Longsword_01 = true,
		T_Imp_Templar_Longsword_Blessed = true,
		T_Imp_Templar_Shortsword_01 = true,
		T_Imp_Templar_Spear_01 = true,
		T_Imp_Templar_Waraxe_01 = true,
		T_Imp_Templar_Warhammer_01 = true,
        },

        illdrug = {
		potion_skooma_01 = true,
		ingred_moon_sugar_01 = true,
        },

        nordimp = {
                potion_nord_mead = true,
		["BM bear boots"] = true,
		["BM bear cuirass"] = true,
		["BM bear greaves"] = true,
		["BM Bear Helmet"] = true,
		["BM Bear Helmet eddard"] = true,
		["BM Bear Helmet_ber"] = true,
		["bm bear left gauntlet"] = true,
		["BM Bear left Pauldron"] = true,
		["BM bear right gauntlet"] = true,
		["BM bear right pauldron"] = true,
		["BM bear shield"] = true,
		["BM wolf boots"] = true,
		["BM wolf cuirass"] = true,
		["BM wolf greaves"] = true,
		["BM Wolf Helmet"] = true,
		["BM Wolf Helmet_heartfang"] = true,
		["bm wolf left gauntlet"] = true,
		["BM Wolf Left Pauldron"] = true,
		["BM wolf right gauntlet"] = true,
		["BM Wolf right pauldron"] = true,
		["BM wolf shield"] = true,
		["BM huntsman axe"] = true,
		["BM huntsman crossbow"] = true,
		["BM huntsman longsword"] = true,
		["BM Huntsman Spear"] = true,
		["BM huntsman war axe"] = true,
		["BM Huntsmanbolt"] = true,
		["BM ice dagger"] = true,
		["BM ice longsword"] = true,
		["BM ice longsword_FG_Unique"] = true,
		["BM ice mace"] = true,
		["BM ice war axe"] = true,
		["BM nord leg"] = true,
		["BM Nordic Pick"] = true,
		["BM nordic silver axe"] = true,
		["BM nordic silver axe_ber"] = true,
		["BM nordic silver axe_spurius"] = true,
		["BM nordic silver battleaxe"] = true,
		["BM nordic silver battleaxe_ber"] = true,
		["BM nordic silver claymore"] = true,
		["BM nordic silver claymore_ber"] = true,
		["BM nordic silver dagger"] = true,
		["BM nordic silver longsword"] = true,
		["BM nordic silver longsword_ber"] = true,
		["BM nordic silver longsword_cft"] = true,
		["BM nordic silver mace"] = true,
		["BM nordic silver shortsword"] = true,
		["BM nordic_longsword_tracker"] = true,
		["bm reaver battle axe"] = true,
		["BM riekling lance"] = true,
		["BM riekling sword"] = true,
		["BM riekling sword_rusted"] = true,
		["BM silver dagger wolfender"] = true,
		["BM Winterwound Dagger"] = true,
		
		T_Nor_Ancient_Shield = true,
		T_Nor_Bearskin_Boots_01 = true,
		T_Nor_Bearskin_BracerL_01 = true,
		T_Nor_Bearskin_BracerL_Claw = true,
		T_Nor_Bearskin_BracerR_01 = true,
		T_Nor_Bearskin_BracerR_Claw = true,
		T_Nor_Bearskin_Greaves_01 = true,
		T_Nor_Bearskin_Helm_01 = true,
		T_Nor_Bearskin_Helm_Hiber = true,
		T_Nor_Bearskin_PauldronL_01 = true,
		T_Nor_Bearskin_PauldronR_01 = true,
		T_Nor_Companion_Boots_01 = true,
		T_Nor_Companion_Cuirass_01 = true,
		T_Nor_Companion_GauntletL_01 = true,
		T_Nor_Companion_GauntletR_01 = true,
		T_Nor_Companion_Greaves_01 = true,
		T_Nor_Companion_Helm_01 = true,
		T_Nor_Companion_PauldronL_01 = true,
		T_Nor_Companion_PauldronR_01 = true,
		T_Nor_Guard_Boots_01 = true,
		T_Nor_Guard_Cuirass_01 = true,
		T_Nor_Guard_GauntletL_01 = true,
		T_Nor_Guard_GauntletR_01 = true,
		T_Nor_Guard_Greaves_01 = true,
		T_Nor_Guard_Helm_01 = true,
		T_Nor_Guard_PauldronL_01 = true,
		T_Nor_Guard_PauldronR_01 = true,
		T_Nor_GuardFalkr_Boots_01 = true,
		T_Nor_GuardFalkr_BracerL_01 = true,
		T_Nor_GuardFalkr_BracerR_01 = true,
		T_Nor_GuardFalkr_Cuirass_01 = true,
		T_Nor_GuardFalkr_Greaves_01 = true,
		T_Nor_GuardFalkr_Helm_01 = true,
		T_Nor_GuardFalkr_Helm_02 = true,
		T_Nor_GuardFalkr_PauldronL_01 = true,
		T_Nor_GuardFalkr_PauldronR_01 = true,
		T_Nor_GuardFalkr_Shield_01 = true,
		T_Nor_GuardFalkr_TowerShield_01 = true,
		T_Nor_Iron_Boots_01 = true,
		T_Nor_Iron_Boots_Leap = true,
		T_Nor_Iron_Cuirass_Wintery = true,
		T_Nor_Iron_GauntletL_01 = true,
		T_Nor_Iron_GauntletR_01 = true,
		T_Nor_Iron_Greaves_01 = true,
		T_Nor_Iron_PauldronL_01 = true,
		T_Nor_Iron_PauldronR_01 = true,
		T_Nor_Ironwood_Shield_01 = true,
		T_Nor_Ironwood_Shield_02 = true,
		T_Nor_Leather1_BarcerL_01 = true,
		T_Nor_Leather1_BarcerR_01 = true,
		T_Nor_Leather1_Boots_01 = true,
		T_Nor_Leather1_Cuirass_01 = true,
		T_Nor_Leather1_Greaves_01 = true,
		T_Nor_Leather1_Helm_01 = true,
		T_Nor_Leather1_PauldL_01 = true,
		T_Nor_Leather1_PauldR_01 = true,
		T_Nor_ReaRoy_Boots_01 = true,
		T_Nor_ReaRoy_BracerL_01 = true,
		T_Nor_ReaRoy_BracerR_01 = true,
		T_Nor_ReaRoy_Cuirass_01 = true,
		T_Nor_ReaRoy_Helm_01 = true,
		T_Nor_ReaRoy_PauldronL_01 = true,
		T_Nor_ReaRoy_PauldronR_01 = true,
		T_Nor_Ringmail_Boots_01 = true,
		T_Nor_Ringmail_Boots_02 = true,
		T_Nor_Ringmail_BracerL_02 = true,
		T_Nor_Ringmail_BracerR_02 = true,
		T_Nor_Ringmail_Cuirass_01 = true,
		T_Nor_Ringmail_Greaves_01 = true,
		T_Nor_Ringmail_Greaves_02 = true,
		T_Nor_Ringmail_Helm_Closed = true,
		T_Nor_Ringmail_Helmet_01 = true,
		T_Nor_Ringmail_Helmet_02 = true,
		T_Nor_Ringmail_PauldronL_02 = true,
		T_Nor_Ringmail_PauldronR_02 = true,
		T_Nor_Sabrecat_Helm_01 = true,
		T_Nor_Sabrecat_Helm_02 = true,
		T_Nor_Sabrecat_Helm_Sight = true,
		T_Nor_Steel_Boots_01 = true,
		T_Nor_Steel_Cuirass_01 = true,
		T_Nor_Steel_Cuirass_SteelHearth = true,
		T_Nor_Steel_GauntletL_01 = true,
		T_Nor_Steel_GauntletR_01 = true,
		T_Nor_Steel_Greaves_01 = true,
		T_Nor_Steel_Helm_01 = true,
		T_Nor_Steel_PauldronL_01 = true,
		T_Nor_Steel_PauldronR_01 = true,
		T_Nor_Toadscale_Boots_01 = true,
		T_Nor_Toadscale_Boots_02 = true,
		T_Nor_Toadscale_Cuirass_01 = true,
		T_Nor_Toadscale_Cuirass_02 = true,
		T_Nor_Toadscale_GauntletL_01 = true,
		T_Nor_Toadscale_GauntletL_02 = true,
		T_Nor_Toadscale_GauntletR_01 = true,
		T_Nor_Toadscale_GauntletR_02 = true,
		T_Nor_Toadscale_Greaves_01 = true,
		T_Nor_Toadscale_Greaves_02 = true,
		T_Nor_Toadscale_Helm_01 = true,
		T_Nor_Toadscale_Helm_02 = true,
		T_Nor_Toadscale_Helm_03 = true,
		T_Nor_Toadscale_Helm_04 = true,
		T_Nor_Toadscale_PauldL_01 = true,
		T_Nor_Toadscale_PauldL_02 = true,
		T_Nor_Toadscale_PauldR_01 = true,
		T_Nor_Toadscale_PauldR_02 = true,
		T_Nor_Toadscale_Shield_01 = true,
		T_Nor_Toadscale_Shield_02 = true,
		T_Nor_Trollbone_Boots_01 = true,
		T_Nor_Trollbone_BracerL_01 = true,
		T_Nor_Trollbone_BracerR_01 = true,
		T_Nor_Trollbone_Greaves_01 = true,
		T_Nor_Trollbone_Greaves_Vigor = true,
		T_Nor_Trollbone_PauldronL_01 = true,
		T_Nor_Trollbone_PauldronR_01 = true,
		
		T_Nor_Ancient_Arrow_01 = true,
		T_Nor_Ancient_BattleAxe_01 = true,
		T_Nor_Ancient_Broadsword_01 = true,
		T_Nor_Ancient_Claymore_01 = true,
		T_Nor_Ancient_Dagger_01 = true,
		T_Nor_Ancient_Longbow_01 = true,
		T_Nor_Ancient_Mace_01 = true,
		T_Nor_Ancient_Seax_01 = true,
		T_Nor_Ancient_Shortsword_01 = true,
		T_Nor_Ancient_Spear_01 = true,
		T_Nor_Ancient_Staff_01 = true,
		T_Nor_Ancient_WarAxe_01 = true,
		T_Nor_Cane_M = true,
		T_Nor_Cane_P = true,
		T_Nor_Cane_R = true,
		T_Nor_FineSteel_Seax_01 = true,
		T_Nor_GuardFalkr_Axe_01 = true,
		T_Nor_Huntsman_Arrow_01 = true,
		T_Nor_Huntsman_Bow_01 = true,
		T_Nor_Huntsman_Shortsword_01 = true,
		T_Nor_Ice_Arrow_01 = true,
		T_Nor_Ice_Bow_01 = true,
		T_Nor_Iron_Seax_01 = true,
		T_Nor_Iron_Spear_01 = true,
		T_Nor_Iron_ThrowingAxe_01 = true,
		T_Nor_Iron_WarAxe_01 = true,
		T_Nor_Orn_Arrow_01 = true,
		T_Nor_Orn_BattleAxe_01 = true,
		T_Nor_Orn_BattleAxe_Frostbitt = true,
		T_Nor_Orn_Bolt_01 = true,
		T_Nor_Orn_Broadsword_Frostbitt = true,
		T_Nor_Orn_Club_01 = true,
		T_Nor_Orn_Dagger_01 = true,
		T_Nor_Orn_Dart_01 = true,
		T_Nor_Orn_Halberd_01 = true,
		T_Nor_Orn_Longspear_01 = true,
		T_Nor_Orn_Longsword_01 = true,
		T_Nor_Orn_Mace_01 = true,
		T_Nor_Orn_Seax_01 = true,
		T_Nor_Orn_Shortsword_01 = true,
		T_Nor_Orn_Spear_01 = true,
		T_Nor_Orn_Staff_01 = true,
		T_Nor_Orn_ThrowingAxe_01 = true,
		T_Nor_Orn_ThrowingKnife_01 = true,
		T_Nor_Orn_WarAxe_01 = true,
		T_Nor_Orn_Warhammer_01 = true,
		T_Nor_Orn_Warhammer_02 = true,
		T_Nor_Regular_Longsword_01 = true,
		T_Nor_Silver_Bow_01 = true,
		T_Nor_Silver_Claw_01 = true,
		T_Nor_Silver_Dagger_Danswyrm = true,
		T_Nor_Silver_Seax_01 = true,
		T_Nor_Silver_Shortsword_Danswyr = true,
		T_Nor_SilverSpear_01 = true,
		T_Nor_StalhrimBattleAxe_01 = true,
		T_Nor_StalhrimBroadsword_01 = true,
		T_Nor_StalhrimClaymore_01 = true,
		T_Nor_StalhrimHalberd_01 = true,
		T_Nor_StalhrimShortsword_01 = true,
		T_Nor_StalhrimSpear_01 = true,
		T_Nor_StalhrimStaff_01 = true,
		T_Nor_StalhrimWarhammer_01 = true,
		T_Nor_Steel_Spear_01 = true,
		T_Nor_Steel_Waraxe_01 = true,
		T_Nor_Steel_WarHammer_01 = true,
		T_Nor_Trollbone_Club_01 = true,

        },


        enchanted = {},
        
        soulgem = {
                Misc_SoulGem_Petty = true,
                Misc_SoulGem_Lesser = true,
                Misc_SoulGem_Common = true,
                Misc_SoulGem_Greater = true,
                Misc_SoulGem_Grand = true,
                Misc_SoulGem_Azura = true,
                AB_Misc_SoulGemBlack = true,
        }
}

local function isSmuggler(actor)
        return actor.class.id == "Smuggler"
			or actor.class.id == "Necromancer"
			or (actor.faction and (actor.faction.id == "Thieves Guild"
								or actor.faction.id == "Camonna Tong"
								or actor.faction.id == "Ashlanders"
								or actor.faction.id == "Telvanni"
								or actor.faction.id == "T_Sky_ThievesGuild"
								or actor.faction.id == "T_Cyr_ThievesGuild"
								))
end

local function isDwemer(item)
        return string.find(item.id, "dwrv") or string.find(item.id, "dwemer") or string.find(item.id, "dwarven") or string.find(item.id, "AB_*_dw") or string.startswith(item.id, "T_Dwe_") 
end

local function isForbidden(item)
        local mineral =  string.find(item.id, "raw_glass") or string.find(item.id, "raw_ebony")
        local skooma = string.find(item.id, "potion_skooma") or string.find(item.id, "moon_sugar")
        return mineral or skooma
end

local function addCategoryToRegionExport(category, regions)
        for _, region in ipairs(regions) do
                if not defaultConfig[region] then
                        defaultConfig[region] = {
                                export = {},
                                import = {}
                        }
                end
                for item, status in pairs(defaultConfig[category]) do
                        if defaultConfig[region].import[item] ~= true then
                                defaultConfig[region].export[item] = true
                        else
                                defaultConfig[region].import[item] = nil
                        end
                end
        end
end

local function addCategoryToRegionImport(category, regions)
        for _, region in ipairs(regions) do
                if not defaultConfig[region] then
                        defaultConfig[region] = {
                                export = {},
                                import = {}
                        }
                end
                for item, status in pairs(defaultConfig[category]) do
                        if defaultConfig[region].export[item] ~= true then
                                defaultConfig[region].import[item] = true
                        else
                                defaultConfig[region].export[item] = nil
                        end
                end
        end
end

local function addRegionGoods(region, towns)
        for _, town in ipairs(towns) do
                if not defaultConfig[town] then
                        defaultConfig[town] = {
                                export = {
                                },
                                import = {
                                }
                        }
                end
                
                for item, status in pairs(defaultConfig[region].export) do
                        if status then
                                if defaultConfig[town].export[item] ~= false then
                                        defaultConfig[town].export[item] = status
                                end
                        end
                end
                
                for item, status in pairs(defaultConfig[region].import) do
                        if status then
                                if defaultConfig[town].import[item] ~= false then
                                        defaultConfig[town].import[item] = status
                                end
                        end
                end
        end
end

for obj in tes3.iterateObjects(tes3.objectType.npc) do
        if isSmuggler(obj) then
                defaultConfig.smuggler[obj.id] = true
        end
end

local itemTypes = { [tes3.objectType.alchemy] = true, [tes3.objectType.ammunition] = true, [tes3.objectType.apparatus] = true, [tes3.objectType.armor] = true, [tes3.objectType.book] = true, [tes3.objectType.clothing] = true, [tes3.objectType.ingredient] = true, [tes3.objectType.light] = true, [tes3.objectType.lockpick] = true, [tes3.objectType.miscItem] = true, [tes3.objectType.probe] = true, [tes3.objectType.repairItem] = true, [tes3.objectType.weapon] = true }        

for obj in tes3.iterateObjects() do
        if (itemTypes[obj.objectType]) then
                if isDwemer(obj) then
                        defaultConfig.dwemer[obj.id] = true
                        defaultConfig.forbidden[obj.id] = true
                elseif isForbidden(obj) then
                        defaultConfig.forbidden[obj.id] = true
                end
        end
end

for clot in tes3.iterateObjects(tes3.objectType.clothing) do
        if string.startswith(clot.id, "T_De_Ex_") or string.startswith(clot.id, "T_De_UNI_") or string.startswith(clot.id, "T_Nor_Ex_") or string.startswith(clot.id, "T_Imp_Ex_") or string.startswith(clot.id, "T_Com_Ex_") or string.startswith(clot.id, "T_Com_UNI_") or string.startswith(clot.id, "exquisite_") then
                defaultConfig.luxury[clot.id] = true
        end
end

for book in tes3.iterateObjects(tes3.objectType.book) do
        if book.skill >= 0 then
                defaultConfig.skillBooks[book.id] = true
        end
end

for ingred in tes3.iterateObjects(tes3.objectType.ingredient) do
        if string.startswith(ingred.id, "AB_IngFood_") or string.startswith(ingred.id, "T_IngFood_") then
                defaultConfig.food[ingred.id] = true
        end
end



for potion in tes3.iterateObjects(tes3.objectType.alchemy) do
        if string.startswith(potion.id, "AB_dri_") then
                defaultConfig.food[potion.id] = true
        end
end


for potion in tes3.iterateObjects(tes3.objectType.alchemy) do
        if string.startswith(potion.id, "T_Nor_Drink_") then
                defaultConfig.nordimp[potion.id] = true
        end
end

for armo in tes3.iterateObjects(tes3.objectType.armor) do
        if string.startswith(armo.id, "T_Nor_") or string.startswith(armo.id, "BM_") or string.startswith(armo.id, "fur_") or string.startswith(armo.id, "nordic_") then
                defaultConfig.nordimp[armo.id] = true
        end
end

for weap in tes3.iterateObjects(tes3.objectType.weapon) do
        if string.startswith(weap.id, "T_Nor_") or string.startswith(weap.id, "BM_") then
                defaultConfig.nordimp[weap.id] = true
        end
end

for misc in tes3.iterateObjects(tes3.objectType.miscItem) do
        if string.startswith(misc.id, "T_Nor_") then
                defaultConfig.nordimp[misc.id] = true
        end
end




for armo in tes3.iterateObjects(tes3.objectType.armor) do
        if string.startswith(armo.id, "daedric_") or string.startswith(armo.id, "glass_") or string.startswith(armo.id, "T_Ayl_") or string.startswith(armo.id, "T_Dae_") or string.startswith(armo.id, "ebony_") or string.startswith(armo.id, "T_He_Direnni_") or string.startswith(armo.id, "T_De_NativeEbony_") then
                defaultConfig.daedra[armo.id] = true
        end
end

for weap in tes3.iterateObjects(tes3.objectType.weapon) do
        if string.startswith(weap.id, "T_Dae_") or string.startswith(weap.id, "AB_w_Dae") or string.startswith(weap.id, "T_Ayl_") or string.startswith(weap.id, "T_De_Ebony") or string.startswith(weap.id, "T_De_Glass") or string.startswith(weap.id, "T_De_Ebony_") then
                defaultConfig.daedra[weap.id] = true
        end
end




for potion in tes3.iterateObjects(tes3.objectType.alchemy) do
        if string.startswith(potion.id, "T_Imp_Drink_") or string.startswith(potion.id, "T_Bre_Drink_") then
                defaultConfig.cyrodimp[potion.id] = true
        end
end

for ingred in tes3.iterateObjects(tes3.objectType.ingredient) do
        if string.startswith(ingred.id, "T_IngSpice_") then
                defaultConfig.cyrodimp[ingred.id] = true
        end
end

for armo in tes3.iterateObjects(tes3.objectType.armor) do
        if string.startswith(armo.id, "T_Imp_") or string.startswith(armo.id, "imperial_") or string.startswith(armo.id, "AB_a_Imp") or string.startswith(armo.id, "dragonscale_") then
                defaultConfig.cyrodimp[armo.id] = true
        end
end

for weap in tes3.iterateObjects(tes3.objectType.weapon) do
        if string.startswith(weap.id, "T_Imp_") or string.startswith(weap.id, "imperial_") or string.startswith(weap.id, "AB_w_Imp") or string.startswith(weap.id, "T_Bre_") then
                defaultConfig.cyrodimp[weap.id] = true
        end
end

for misc in tes3.iterateObjects(tes3.objectType.miscItem) do
        if string.startswith(misc.id, "T_Imp_") or string.startswith(misc.id, "misc_imp_") then
                defaultConfig.cyrodimp[misc.id] = true
        end
end

for misc in tes3.iterateObjects(tes3.objectType.miscItem) do
        if string.startswith(misc.id, "AB_Misc_DeBlue") or string.startswith(misc.id, "AB_Misc_DeEbony") or string.startswith(misc.id, "AB_Misc_DeGreen") or string.startswith(misc.id, "AB_Misc_DePeach") or string.startswith(misc.id, "AB_Misc_DeYel") or string.startswith(misc.id, "misc_com_bottle") or string.startswith(misc.id, "misc_de_goblet") then
                defaultConfig.glass[misc.id] = true
        elseif string.startswith(misc.id, "misc_com_redware") or string.startswith(misc.id, "misc_com_plate") or string.startswith(misc.id, "misc_de_bowl_redware") or string.startswith(misc.id, "misc_de_pot_redware") or string.startswith(misc.id, "AB_Misc_DeYel") then
                defaultConfig.pottery[misc.id] = true
        end
end

local enchantedLvlLists = {"l_m_enchantitem_telvanni_rank01", "l_m_enchantitem_telvanni_rank6", "l_m_enchantitem_telvanni_rank8"}


for i, leveledItem in ipairs(enchantedLvlLists) do
        leveledItem = tes3.getObject(leveledItem)
        for _, listNode in ipairs(leveledItem.list) do
                local item = listNode.object
                defaultConfig.enchanted[item.id] = true
        end
end

addRegionGoods("West Gash Region", {"Balmora", "Caldera", "Gnisis", "Khuul", "Ald Velothi"})
addRegionGoods("Bitter Coast Region", {"Seyda Neen", "Gnaar Mok", "Hla Oad"})
addRegionGoods("Ascadian Isles Region", {"Suran", "Pelagiad", "Ebonheart"})
addRegionGoods("Molag Amur Region", {"Molag Mar", "Erabenimsun Camp"})
addRegionGoods("Azura's Coast Region", {"Tel Branora", "Tel Aruhn", "Sadrith Mora", "Tel Mora"})
addRegionGoods("Grazelands Region", {"Vos", "Tel Vos", "Ahemmusa Camp", "Zainab Camp"})
addRegionGoods("Sheogorad Region", {"Dagon Fel"})
addRegionGoods("Ashlands Region", {"Ald-ruhn", "Maar Gan", "Urshilaku Camp", "Armun Ashlands Region", "Arvud"})
addRegionGoods("Red Mountain Region", {"Ghostgate"})
addRegionGoods("Solstheim", {"Felsaad Coast", "Hirstaang Forest", "Isinfier Plains", "Moesring Mountains", "Skaal Village", "Thirsk", "Raven Rock", "Fort Frostmoth", "Karthwasten", "Dragonstar East"})

addCategoryToRegionExport("netch", {"Balmora", "Suran", "Pelagiad", "Ascadian Isles Region", "Arvud"})
addCategoryToRegionExport("chitin", {"Ald-ruhn", "Urshilaku Camp", "Erabenimsun Camp", "Ahemmusa Camp", "Zainab Camp", "Arvud", "Grazelands Region", "Armun Ashlands Region"})
addCategoryToRegionExport("ashlander", {"Urshilaku Camp", "Erabenimsun Camp", "Ahemmusa Camp", "Zainab Camp", "Armun Ashlands Region", "Arvud"})
addCategoryToRegionExport("enchanted", {"Necrom", "Tel Branora", "Tel Aruhn", "Sadrith Mora", "Tel Mora", "Vos", "Tel Vos", "Port Telvannis", "Gah Sadrith"})
addCategoryToRegionExport("kwama", {"Hlan Oek", "Molag Amur Region", "West Gash Region", "Ashlands Region", "Sacred Lands Region", "Boethiah's Spine Region", "Mephalan Vales Region", "Aanthirin Region", "Akamora"})
addCategoryToRegionExport("daedra", {"Grazelands Region", "Azura's Coast Region", "Molag Amur Region", "Boethiah's Spine Region", "Mephalan Vales Region", "Armun Ashlands Region", "Port Telvannis", "Gah Sadrith"})
addCategoryToRegionExport("dwemer", {"Molag Amur Region", "Boethiah's Spine Region", "Sheogorad Region", "Helnim"})
addCategoryToRegionExport("sea", {"Aimrah", "Idathren", "Hlan Oek", "Bitter Coast Region", "Azura's Coast Region", "Sheogorad Region", "Padomaic Ocean Region", "Sea of Ghosts Region", "Roth Roryn Region", "Telvanni Isles Region", "Hla Oad", "Gnaar Mok", "Dagon Fel", "Stirk", "Helnim", "Firewatch", "Nivalis", "Anvil", "Charach"})
addCategoryToRegionExport("undead", {"Necrom", "Sacred Lands Region", "Aranyon Pass Region", "Roa Dyr"})
addCategoryToRegionExport("food", {"Aimrah", "Ascadian Isles Region", "Pelagiad", "Suran", "Andothren", "Dondril", "Vhuul", "Brina Cross"})
addCategoryToRegionExport("cyrodimp", {"Old Ebonheart", "Anvil"})
addCategoryToRegionExport("nordimp", {"Solstheim", "Dagon Fel", "Felsaad Coast", "Hirstaang Forest", "Isinfier Plains", "Moesring Mountains", "Skaal Village", "Thirsk", "Raven Rock", "Fort Frostmoth", "Karthwasten", "Dragonstar East"})
addCategoryToRegionExport("glass", {"Ald-ruhn", "Grazelands Region", "Ghostgate", "Red Mountain Region"})
addCategoryToRegionExport("pottery", {"Ald-ruhn", "Roth Roryn", "Andothren", "Stirk", "Almas Thirr"})
addCategoryToRegionExport("ingmine", {"Karthwasten", "Arvud", "Grazelands Region", "Molag Mar", "Raven Rock", "Firewatch"})
addCategoryToRegionExport("coins", {"Karthwasten", "Dagon Fel", "Arvud", "Grazelands Region", "Molag Mar", "Khuul", "Raven Rock"})



addCategoryToRegionImport("ingmine", {"Balmora", "Old Ebonheart", "Andothren", "Anvil", "Charach", "Narsis"})
addCategoryToRegionImport("luxury", {"Balmora", "Old Ebonheart", "Firewatch", "Helnim", "Akamora", "Andothren", "Anvil", "Charach", "Narsis"})
addCategoryToRegionImport("coins", {"Balmora", "Old Ebonheart", "Helnim", "Firewatch", "Anvil"})
addCategoryToRegionImport("daedra", {"Balmora", "Old Ebonheart", "Helnim", "Firewatch", "Ald-ruhn"})
addCategoryToRegionImport("soulgem", {"Necrom", "Tel Branora", "Tel Aruhn", "Sadrith Mora", "Tel Mora", "Vos", "Tel Vos"})
addCategoryToRegionImport("food", {"Necrom", "Ald-ruhn", "Red Mountain", "Maar Gan", "Ghostgate", "Dagon Fel", "Old Ebonheart", "Ebonheart", "Firewatch", "Helnim", "Arvud", "Molag Mar", "Dragonstar East", "Dragonstar West", "Stirk", "Nivalis", "Padomaic Ocean Region", "Distant Horizon", "Anvil", "Charach", "Narsis"})
addCategoryToRegionImport("cyrodimp", {"Firewatch", "Helnim", "Pelagiad", "Caldera", "Karthwasten", "Stirk", "Nivalis", "Teyn", "Seyda Neen", "Gnisis", "Fort Ghostmoth", "Old Ebonheart"})
addCategoryToRegionImport("illdrug", {"Old Ebonheart", "Firewatch", "Helnim", "Vivec", "Dragonstar East", "Karthwasten", "Ald-ruhn", "Caldera", "Gnisis", "Almas Thirr", "Anvil"})




local mwseConfig = mwse.loadConfig("buyingGame", defaultConfig)

return mwseConfig;
