local strings = {}

strings.modName = "Buying Game"
strings.illicitTrade = "Illicit Trade"
strings.settings = "Settings"
strings.perks = "Perks"
strings.restockTime = "Restock Time Modifier"
strings.restockTimeDesc = "This value is multiplied on fBarterGoldResetDelay (24 hours by default) to get time intervals in hours before each restock"
strings.knowsPrice = "Value Estimate"
strings.knowsPriceDesc = "Mercantile skill level from which the player will see the base value of every item"
strings.knowsForbid = "Knowledge of Prohibited Items"
strings.knowsForbidDesc = "Mercantile skill level from which the player will be able to see information about which items are prohibited for sale"
strings.knowsSpecialization = "Knowledge of Specialization"
strings.knowsSpecializationDesc = "Mercantile skill level from which the player will be able to get better prices, bartering goods, which traders specialize in"
strings.knowsExport = "Knowledge of Supply and Demand"
strings.knowsExportDesc = "Mercantile skill level from which the player will be able to see item prices with regional modifiers and take advantage of them"
strings.sdModifier = "Suppply and Demand Modifier"
strings.sdModifierDesc = "Modifier in percents affecting price of the goods due to supply and demand in the region"
strings.canInvest = "Investor"
strings.canInvestDesc = "Mercantile skill level from which the player will be able to invest in traders businesses, increasing their base gold and amount of restockable goods"
strings.canBarterEquipped = "Barter of Equipment"
strings.canBarterEquippedDesc = "Mercantile skill level from which the player will be able to buy equipped weapons and jewelry"
strings.canTradeWithEveryone = "Unlimited Trade"
strings.canTradeWithEveryoneDesc = "Mercantile skill level from which the player will be able to barter with every npc in game with no restrictions to item types"
strings.modEnabled = "Mod Enabled"
strings.modEnabledDesc = "Enabling and disabling the mod and all its functionality"
strings.removeBought = "Remove bought items on restock"
strings.removeBoughtDesc = "When this option is on, traders other than Pawnbrokers will free their inventory from items they bought from the player on every restock. Pawnbrokers will still continue to keep bought items indefinetely."
strings.smuggler = "Smugglers"
strings.smugglerDesc = "List of NPCs, who will buy forbidden items from you. By default includes all the members of Thieves Guild and Camonna Tong as well as all NPCs with class Smuggler"
strings.forbidden = "Forbidden Items"
strings.forbiddenDesc = "List of items, which are considered to be forbidden and won't be bought by normal traders. By default includes Skooma, Moon Sugar, Dwemer items, Raw Ebony and Raw Glass"
strings.export = "Due to high supply in the region, the prices for these items are lowered"
strings.import = "Due to high demand in the region, the prices for these items are raised"

strings.forbiddenItemRefused = "I do not buy %s, that's illegal!"
strings.contraband = "Illegal item"

return strings