return {
    "'bhu",
    "'kaa",
    "'s mastery",
    "abya",
    "ahmar",
    "alladan's",
    "altia's",
    "amethyst",
    "ang",
    "ani'",
    "artisana's",
    "asfar",
    "ashan",
    "asmar",
    "assassin's",
    "aswa",
    "atalan's",
    "autumnal",
    "azar",
    "azmar",
    "azra",
    "bamboo ",
    "bella domina",
    "bhu'",
    "bloodstone",
    "box weave",
    "canisia's",
    "cermonial", 
    "ceruila's",
    "cirithel's",
    "crystal",
    "daedric arcana",
    "dark",
    "dawn song",
    "dirian's",
    "djinni",
    "dragon's breath",
    "dragontail",
    "drake skin",
    "dunmer leather",
    "eastern province",
    "eleth's",
    "elven sorcery",
    "elven",
    "emmissary's",
    "espiria's",
    "ethron's",
    "finuola's",
    "galidorn's",
    "golden",
    "golitha's",
    "gul'",
    "hak'",
    "halidan's",
    "high guard",
    "hra'",
    "ilrion's",
    "jas'",
    "kaa'",
    "kak'",
    "kheran",
    "kilian's",
    "kiriel's",
    "laal'",
    "leviathan", 
    "light wicker",
    "lirian's",
    "mage",
    "maille",
    "malefica",
    "mannan's",
    "masquerade",
    "meridian",
    "merisande's",
    "merisian's",
    "mindstone",
    "mithiria's",
    "night song",
    "nii'",
    "nuada's", 
    "nuala's",
    "of mab",
    "of morganna",
    "of oberon",
    "of the aurora",
    "of the dark lord",
    "of the fae",
    "of the kyn",
    "of titania",
    "orian's",
    "phantasm",
    "quartz",
    "raw silk",
    "rinola's",
    "saf'",
    "sea kindred",
    "sea",
    "shadow fox",
    "skyrim",
    "soulstone",
    "spectral",
    "summerset",
    "virian's",
    "wicker ",
    "wizard's",
    "wooden",
    "woven ",
    "xdar",
    "yathar",
    "yokudan",
}