local tooltipsComplete = require("Tooltips Complete.interop")
local tooltipData = {
    -- Armor
    { id = "adamantium_tail", description = "Armor made from adamantium crafted to protect the tails of Argonian adventurers." },
    { id = "armunan_tail", description = "Armor made from bonemold in the Armun-An style crafted to protect the tails of Argonian adventurers." },
    { id = "bonemold_tail", description = "Armor made from bonemold crafted to protect the tails of Argonian adventurers." },
    { id = "chitin_tail", description = "Armor made from chitin crafted to protect the tails of Argonian adventurers." },
    { id = "daedric_tail", description = "Armor with seemingly daedric orgins crafted to protect the tails of Argonian adventurers." },
    { id = "dwemer_tail", description = "Armor made from dwemer metal crafted to protect the tails of Argonian adventurers." },
    { id = "ebony_tail", description = "Armor made from ebony crafted to protect the tails of Argonian adventurers." },
    { id = "gahjulan_tail", description = "Armor made from bonemold in the Gah-Julan style crafted to protect the tails of Argonian adventurers." },
    { id = "glass_tail", description = "Armor made from glass crafted to protect the tails of Argonian adventurers." },
    { id = "ice_tail", description = "Armor made from an ice-like material crafted to protect the tails of Argonian adventurers." },
    { id = "indoril_tail", description = "Armor made in the Indoril style worn by Ordinators. Wearing this will grant the wearer the wrath of Ordinators." },
    { id = "iron_tail", description = "Armor made from iron crafted to protect the tails of Argonian adventurers." },
    { id = "netch_tail", description = "Armor made from netch leather crafted to protect the tails of Argonian adventurers." },
    { id = "nordic_tail", description = "Armor made in the nordic style crafted to protect the tails of Argonian adventurers." },
    { id = "orc_tail", description = "Armor made in the orchish style crafted to protect the tails of Argonian adventurers." },
    { id = "steel_tail", description = "Armor made from steel crafted to protect the tails of Argonian adventurers." },
    { id = "almindoril_tail", description = "Armor made in the Indoril style worn by High Ordinators. Wearing this will grant the wearer the wrath of Ordinators." },
    { id = "bear_tail", description = "Armor made from snow bear hide, crafted by Brynjolfr. Grants the wearer protection from the cold." },
    { id = "chain_tail", description = "Armor made from chainmail, crafted to protect the tails of Argonian Legionnaires." },
    { id = "db_tail", description = "Tail armor crafted specifically for Argonian members of the Dark Brotherhood." },
    { id = "domina_tail", description = "Crafted by Sirollus Saccus, this tail armor is specially designed for female Argonians." },
    { id = "dreugh_tail", description = "Armor made from dreugh shells, crafted to protect the tails of Argonian adventurers." },
    { id = "golden_tail", description = "Armor made from steel , crafted to protect the tails of Argonian adventurers." },
    { id = "helseth_tail", description = "Tail armor made specially for the Royal Guards of King Helseth of Morrowind." },
    { id = "impsteel_tail", description = "Armor made from Imperial steel, crafted to protect the tails of Argonian Legionnaires." },
    { id = "scale_tail", description = "Armor made in the Imperial Dragonscale style, crafted to protect the tails of Argonian Legionnaires." },
    { id = "templar_tail", description = "Armor made in the Imperial Templar style, crafted to protect the tails of Argonian Legionnaires of the Knight Errant rank." },
    { id = "wolf_tail", description = "Armor made from snow wolf hide, crafted by Brynjolfr. Grants the wearer protection from the cold." },
    { id = "hist_adamantium", description = "A special adamantium helm crafted by Bols Indaren shaped to fit the head of Argonians." },
    { id = "hist_darkbro", description = "A helm specially made for Argonian members of the Dark Brotherhood known as Shadowscales." },
    { id = "hist_dragon", description = "A special dragonscale helm shaped to fit the head of Argonians." },
    { id = "hist_dreugh", description = "A special dreugh helm shaped to fit the head of Argonians." },
    { id = "hist_dwem", description = "Made from special Dwemer metal, this helm follows the typical style of Dwemer armor except in it's shape, allowing Beastfolk to wear it." },
    { id = "hist_glass", description = "A special glass helm crafted by Bols Indaren shaped to fit the head of Argonians." },
    { id = "hist_gold", description = "Crafted by Sirollus Saccus, this helm is specially designed for female Argonians." },
    { id = "hist_herhand", description = "A seemingly abandoned High Ordinator helm found in the basement of the Mournhold Temple. Wearing this helm around High Ordinators is sure to earn the wearer their wrath." },
    { id = "hist_ice", description = "A special stalhrim helm shaped to fit the head of Argonians." },
    { id = "hist_imperial", description = "A steel helm designed to fit Argonian Legionnaires." },
    { id = "hist_nordic", description = "Found in The Greathall of the Skaal, this strange nordic helm is seemingly designed to fit Argonian warriors." },
    { id = "hist_royal", description = "Designed for and worn specifically by the Royal Guards of King Helseth of Morrowind, this helm is specially crafted for Argonian guards." },
    { id = "hist_silver", description = "A unique silver helm seemingly designed to be worn by Argonian warriors." },
    { id = "arg_domina", description = "A unique version of the Domina cuirass designed with female Argonians in mind. Also appears to fit males." },
    { id = "blackrose_crown", description = "A flower crown made of Black Roses, crafted by Picks-Many-Flowers." },
    { id = "duskb_crown", description = "A flower crown made of Duskbell Flowers, crafted by Picks-Many-Flowers." },
    { id = "goldsedge_crown", description = "A flower crown made of Golden Sedge Flowers, crafted by Picks-Many-Flowers." },
    { id = "hornlily_crown", description = "A flower crown made of Hornlilies, crafted by Picks-Many-Flowers." },
    { id = "laurelf_crown", description = "A flower crown made of Laurels, crafted by Picks-Many-Flowers." },
    { id = "mornglory_crown", description = "A flower crown made of Morningglories, crafted by Picks-Many-Flowers." },
    { id = "mtndamask_crown", description = "A flower crown made of Mountain Damask Flowers, crafted by Picks-Many-Flowers." },
    { id = "nobsedge_crown", description = "A flower crown made of Noble Sedge Flowers, crafted by Picks-Many-Flowers." },
    { id = "orcscrown_crown", description = "A flower crown made of Orcscrown Flowers, crafted by Picks-Many-Flowers." },
    { id = "pipeony_crown", description = "A flower crown made of Pink Peonies, crafted by Picks-Many-Flowers." },
    { id = "prosepi_crown", description = "A flower crown made of Pink Primroses, crafted by Picks-Many-Flowers." },
    { id = "prosered_crown", description = "A flower crown made of Red Primroses, crafted by Picks-Many-Flowers." },
    { id = "redrose_crown", description = "A flower crown made of Red Roses, crafted by Picks-Many-Flowers." },
    { id = "sweetbarrel_crown", description = "A flower crown made of Sweetbarrel Flowers, crafted by Picks-Many-Flowers." },
    { id = "tigerlily_crown", description = "A flower crown made of Tiger Lilies, crafted by Picks-Many-Flowers." },
    { id = "timsaf_crown", description = "A flower crown made of Timsa-Come-By-Flowers, crafted by Picks-Many-Flowers." },
    { id = "shalk_boots", description = "Specially made boots crafted from the chitin of Shalks by the Zainab Ashlanders." },
    { id = "shalk_helmet", description = "Specially made helmet crafted from the chitin of Shalks by the Zainab Ashlanders." },
    { id = "shalk_cuirass", description = "Specially made cuirass crafted from the chitin of Shalks by the Zainab Ashlanders." },
    { id = "shalk_gauntlet_l", description = "Specially made gauntlet crafted from the chitin of Shalks by the Zainab Ashlanders." },
    { id = "shalk_gauntlet_r", description = "Specially made gauntlet crafted from the chitin of Shalks by the Zainab Ashlanders." },
    { id = "shalk_greaves", description = "Specially made greaves crafted from the chitin of Shalks by the Zainab Ashlanders." },
    { id = "shalk_pauldron_l", description = "Specially made pauldron crafted from the chitin of Shalks by the Zainab Ashlanders." },
    { id = "shalk_pauldron_r", description = "Specially made pauldron crafted from the chitin of Shalks by the Zainab Ashlanders." },

    -- Books
    { id = "1loveletter", description = "An unsent love letter written by Menseni Andrethi to the Hlaalu guard Daloyn Rallom." },
    { id = "sonnwejournal", description = "The personal journal of Sonnwe Mones.", itemType = "book" },
    { id = "1sinntarbook", description = "Describes various fungi found in a strange cave in the Azura's Coast Region. Written by Sinnatar and illustrated by Ma'basa.", itemType = "unique" },
    { id = "hap_armorbook", description = "Written by master Dunmeri smith Uradras Uvanloth describing the process of crafting armor.", itemType = "book" },
    { id = "hap_jewelrybook", description = "Written by master Dunmeri smith Uradras Uvanloth describing the process of crafting jewelry.", itemType = "book" },
    { id = "hap_weaponsbook", description = "Written by master Dunmeri smith Uradras Uvanloth describing the process of crafting weapons.", itemType = "book" },

    -- Clothing
    { id = "1jewelrydiseaseamulet", description = "A special amulet gifted to you by Menseni Andrethi for agreeing to clear Andrethi Ancestral Tomb of vampires." },
    { id = "1menseniring", description = "A ring once belonging to Tonaisi Andrethi, mother of Ryton and Menseni Andrethi.", itemType = "quest" },
    { id = "1leviamu", description = "An amulet with a Cast-On-Use levitation enchantment." },
    { id = "commonbelt1", description = "A belt usually worn by commoners and peasants.", itemType = "clothing" },
    { id = "commonbelt3", description = "A belt usually worn by commoners and peasants.", itemType = "clothing" },
    { id = "commonbelt4", description = "A belt usually worn by commoners and peasants.", itemType = "clothing" },
    { id = "exquistebelt", description = "A belt usually worn by merchants and nobles.", itemType = "clothing" },
    { id = "commonbelt5", description = "A belt usually worn by commoners and peasants.", itemType = "clothing" },
    { id = "expensivebelt1", description = "A belt usually worn by merchants and traders.", itemType = "clothing" },
    { id = "expensivebelt2", description = "A belt usually worn by merchants and traders.", itemType = "clothing" },
    { id = "extravagantbelt1", description = "A belt usually worn by merchants and nobles.", itemType = "clothing" },
    { id = "extravagantbelt2", description = "A belt usually worn by merchants and nobles.", itemType = "clothing" },
    { id = "expensivebelt3", description = "A belt usually worn by merchants and traders.", itemType = "clothing" },
    { id = "commonbelt2", description = "A belt usually worn by commoners and peasants.", itemType = "clothing" },
    { id = "heartfire", description = "A belt in the style of the Sixth House.", itemType = "clothing" },
    { id = "erabenimsun", description = "A belt in the style of the Erabenimsun Ashlanders.", itemType = "clothing" },
    { id = "blight_amulet_ff", description = "A special amulet from Lumma Lexius meant to be given to an Ashlander Ashkhan." },    
    { id = "lummaamulet", description = "Lumma Lexius' personal amulet to aid in studying venomous insects." },

    -- Ingredients
    { id = "1bguarmeat", description = "Soft meat from a bantam guar." },
    { id = "2bguarmeat", description = "Soft meat from a bantam guar." },
    { id = "3bguarmeat", description = "Soft meat from a bantam guar." },
    { id = "1clay", description = "Unfired clay used to create various types of ceramics." },
    { id = "1feather", description = "The feathers of a bird used to fletch arrows." },
    { id = "ingred_bguarhide", description = "The hide of a bantam guar." },
    { id = "aseeds", description = "The seeds from the Ash Lotus, a hardy water plant adapted to Vvardenfell's harsh environment." },
    { id = "hap_boiled_leather_n", description = "The hardy leather of a netch, boiled to become even stronger." },
    { id = "hap_sabre_pelt", description = "The pelt of one of Skyrim's fiercest and strongest creatures, the Saber Cat." },
    { id = "hap_Snowsabre_pelt", description = "The pelt of one of Skyrim's fiercest and strongest creatures, the Snowy Saber Cat." },
    { id = "hap_tempered_glass", description = "Volcanic glass that has been smelted and tempered to remove impurities." },

    -- Lights
    { id = "lanterndwem", description = "A Dwemer style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaper14", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaper11", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaper10", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaper7", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaper5", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaper1", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "glasslantern2", description = "A glass style lantern. Attachable at the hip.", itemType = "light" },
    { id = "glasslantern6", description = "A glass style lantern. Attachable at the hip.", itemType = "light" },
    { id = "travellantern1", description = "A travel style lantern. Attachable at the hip.", itemType = "light" },
    { id = "travellantern2", description = "A travel style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indorilgreen1", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indorilgreen2", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indorilgreen3", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indoril1", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indoril2", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indoril3", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indorilpur1", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indorilpur2", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "indorilpur3", description = "An Indoril style lantern. Attachable at the hip.", itemType = "light" },
    { id = "glasslanternyel", description = "A glass style lantern. Attachable at the hip.", itemType = "light" },
    { id = "glasslanternred", description = "A glass style lantern. Attachable at the hip.", itemType = "light" },
    { id = "glasslanterngrn", description = "A glass style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpapery1", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpapery4", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaperprp4", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "colovianlant2", description = "A colovian style lantern. Attachable at the hip.", itemType = "light" },
    { id = "colovianlant3", description = "A colovian style lantern. Attachable at the hip.", itemType = "light" },
    { id = "colovianlant4", description = "A colovian style lantern. Attachable at the hip.", itemType = "light" },
    { id = "colovianlant5", description = "A colovian style lantern. Attachable at the hip.", itemType = "light" },
    { id = "cavernlant", description = "A cavern style lantern. Attachable at the hip.", itemType = "light" },
    { id = "woodlantern", description = "A wooden style lantern. Attachable at the hip.", itemType = "light" },
    { id = "orclantern1", description = "An orcish style lantern. Attachable at the hip.", itemType = "light" },
    { id = "orclantern2", description = "An orchish style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpapergrn4", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpapergrn1", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaperprp1", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaperblue1", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "lanternpaperblue4", description = "A paper style lantern. Attachable at the hip.", itemType = "light" },
    { id = "ashl1", description = "An Ashlander style lantern. Attachable at the hip.", itemType = "light" },
    { id = "ashl2", description = "An Ashlander style lantern. Attachable at the hip.", itemType = "light" },
    { id = "ashl3", description = "An Ashlander style lantern. Attachable at the hip.", itemType = "light" },
    { id = "ashl4", description = "An Ashlander style lantern. Attachable at the hip.", itemType = "light" },
    { id = "ashl5", description = "An Ashlander style lantern. Attachable at the hip.", itemType = "light" },
    { id = "ashl6", description = "An Ashlander style lantern. Attachable at the hip.", itemType = "light" },
    { id = "ashl7", description = "An Ashlander style lantern. Attachable at the hip.", itemType = "light" },

    -- Keys
    { id = "1keytodavah", description = "Key to Davah Saardtha's house.", itemType = "key" },
    { id = "1keytofarmbase", description = "Key to He-Who-Collects' basement.", itemType = "key" },
    { id = "1keytofarmhouse", description = "Key to He-Who-Collects' house.", itemType = "key" },
    { id = "1keytomenseni", description = "Key to Menseni Andrethi's house.", itemType = "key" },
    { id = "1keytomones", description = "Key to the Mones' house.", itemType = "key" },
    { id = "1keytorahindahouse", description = "Key to Ra'hinda's house.", itemType = "key" },
    { id = "1keytoryton", description = "Key to Ryton Andrethi's house.", itemType = "key" },
    { id = "1keytotalavosi", description = "Key to Talavosi Hlavmon's house.", itemType = "key" },
    { id = "1keytouelinhouse", description = "Key to Uelin's house.", itemType = "key" },
    { id = "1keytoworkshop", description = "Key to the Andrethi's workshop.", itemType = "key" },
    { id = "1keytoyagnak", description = "Key to Yagnak gro-Dumah's house.", itemType = "key" },
    { id = "MovihaFatarokey", description = "The key to Moviha Fataro's market chest.", itemType = "key" },
    { id = "keyforiegnchest", description = "The key to Ja'danha's lantern chest.", itemType = "key" },

    -- Misc
    { id = "1sonnwecup", description = "The first ceramic cup created by Sonnwe Mones." },
    { id = "1unfiredbowl", description = "An unfired ceramic bowl." },
    { id = "1unfiredcup", description = "An unfired ceramic cup." },
    { id = "1unfiredcup2", description = "An unfired ceramic cup." },
    { id = "can_mold1", description = "A mold used to form candle's into specific shapes.", },
    { id = "tonagraph", description = "A special dwemer artifact that can be used to print ink-based silhouettes using tonal architecture.", itemType = "quest"},
    { id = "morchellatona", description = "A tonagraph of the Umber Morchella fungus." },
    { id = "sweettona", description = "A tonagraph of the Sweetbread Polypore fungus." },
    { id = "dusttona", description = "A tonagraph of the Dustcap fungus." },
    { id = "glowingtona", description = "A tonagraph of the Roridomyces Phyllostachydis fungus." },
    { id = "glowtona", description = "A tonagraph of the Glowing Chanterelle fungus." },
    { id = "sporetona", description = "A tonagraph of the Blister Spore fungus." },
    { id = "pyroustona", description = "A tonagraph of the Pyrous Uracia fungus." },
    { id = "veiledtona", description = "A tonagraph of the Veiled Urnula fungus." },
    { id = "victona", description = "A tonagraph of the Vicious Chanterelle fungus." },
    { id = "talltona", description = "A tonagraph of the Scypha Mycena fungus." },
    { id = "black_wolf_head", description = "The mounted head of a black wolf." },
    { id = "red_wolf_head", description = "The mounted head of a red wolf." },
    { id = "white_wolf_head", description = "The mounted head of a white wolf." },
    { id = "black_wolf_statue", description = "A taxidermied black wolf." },
    { id = "red_wolf_statue", description = "A taxidermied red wolf." },
    { id = "white_wolf_statue", description = "A taxidermied white wolf." },
    { id = "alit_statue", description = "A taxidermied alit." },
    { id = "guar_statue", description = "A taxidermied guar." },
    { id = "bristleback_statue", description = "A taxidermied bristleback." },
    { id = "brown_bear_statue", description = "A taxidermied brown bear." },
    { id = "tan_bear_statue", description = "A taxidermied tan bear." },
    { id = "white_bear_statue", description = "A taxidermied white bear." },
    { id = "durzog_statue", description = "A taxidermied durzog." },
    { id = "kag_statue", description = "A taxidermied kagouti." },
    { id = "brown_bear_head", description = "The mounted head of a brown bear." },
    { id = "white_bear_head", description = "The mounted head of a white bear." },
    { id = "tan_bear_head", description = "The mounted head of a tan bear." },
    { id = "alit_head", description = "The mounted head of an alit." },
    { id = "guar_head", description = "The mounted head of a guar." },
    { id = "kag_head", description = "The mounted head of a kagouti." },
    { id = "mudcrab_statue", description = "A taxidermied mudcrab." },
    { id = "shalk_statue", description = "A taxidermied shalk." },
    { id = "nixhound_statue", description = "A taxidermied nix-hound." },
    { id = "racer_statue", description = "A taxidermied cliff racer." },
    { id = "rat_statue", description = "A taxidermied rat." },
    { id = "scrib_statue", description = "A taxidermied scrib." },
    { id = "boar_head", description = "The mounted head of a bristleback." },
    { id = "durzog_head", description = "The mounted head of a durzog." },
    { id = "horker_head", description = "The mounted head of a horker." },
    { id = "horker_statue", description = "A taxidermied horker." },
    { id = "mudcrab_head", description = "The mounted shell of a mudcrab." },
    { id = "nix_head", description = "The mounted head of a nix-hound." },
    { id = "racer_head", description = "The mounted head of a cliff racer." },
    { id = "rat_head", description = "The mounted head of a rat." },
    { id = "scrib_head", description = "The mounted head of a scrib." },
    { id = "shalk_head", description = "The mounted head of a shalk." },
    { id = "akatosh", description = "A shrine dedicated to the god Akatosh, the Dragon God of Time and chief deity of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Will of Akatosh - temporarily fortifying willpower." },
    { id = "nerevarstat", description = "A shrine dedicated to Saint Nerevar the Captain, the patron saint of warriors and statesmen of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Spirit of Nerevar - temporarily fortifying one's health." },
    { id = "vivecalmsivishrine", description = "A shrine dedicated to Vivec, one of the three God-Kings of Morrowind and a god of the Tribunal Temple associated with poetry and battle. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Vivec's Mystery - temporarily fortifying luck attribute." },
    { id = "araloralmsivishrine", description = "A shrine dedicated to Saint Aralor the Penitent, the patron saint of tanners and miners of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Aralor's Intervention - temporarily fortifying luck attribute." },
    { id = "delynshrine", description = "A shrine dedicated to Saint Delyn the Wise, the patron saint of potters and glassmakers of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Shield of St. Delyn - temporarily increasing resistence to blight diseases." },
    { id = "felmsshrine", description = "A shrine dedicated to Saint Felms the Bold, the patron saint of butchers and fishmongers of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Felms' Glory - temporarily fortifying the restoration skill." },
    { id = "llothisshrine", description = "A shrine dedicated to Saint Llothis the Pious, the patron saint of tailors and dyers of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Rock of Llothis - temporarily fortifying the willpower attribute." },
    { id = "merisshrine", description = "A shrine dedicated to Saint Meris the Peacemaker, the patron saint of farmers and laborers of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Meris' Warding - temporarily increasing resistence to corprus disease." },
    { id = "olmsshrine", description = "A shrine dedicated to Saint Olms the Just, the patron saint of chandlers and clerks of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Olms' Benediction - temporarily increasing resistence to common diseases." },
    { id = "rilmsalmsivi", description = "A shrine dedicated to Saint Rilms the Barefooted, the patron saint of pilgrims and beggars of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Rilm's Grace - temporarily fortifying the endurance attribute." },
    { id = "rorisshrine", description = "A shrine dedicated to Saint Roris the Martyr, the patron saint of furnishers and caravaners of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Roris' Bloom - temporarily fortifying one's health." },
    { id = "serynshrine", description = "A shrine dedicated to Saint Seryn the Merciful, the patron saint of brewers, bakers, and distillers of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Seryn's Shield - increasing resistence to poisons." },
    { id = "velothshrine", description = "A shrine dedicated to Saint Veloth the Prophet, the patron saint of outcasts and scholars of the Tribunal Temple. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Veloth's Indwelling - temporarily fortifying one's magicka." },
    { id = "mara", description = "A shrine dedicated to the goddess Mara, the goddess of love and compassion of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Compassion of Mara - temporarily fortifying the endurance attribute." },
    { id = "talos", description = "A shrine dedicated to the god Talos, a once mortal emperor named Tiber Septim who upon death, achieved apotheosis and became one of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Might of Talos - temporarily fortifying attack power." },
    { id = "arkay", description = "A shrine dedicated to the god Arkay, the god of birth and death of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Gift of Arkay - temporarily fortifying the agility attribute." },
    { id = "kynareth", description = "A shrine dedicated to the goddess Kynareth, the goddess of heavens, winds, and rain of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Wind of Kynareth - temporarily fortifying the speed attribute." },
    { id = "dibella", description = "A shrine dedicated to the goddess Dibella, the goddess of beauty and art of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Kiss of Dibella - temporarily fortifying the personality attribute." },
    { id = "julianos", description = "A shrine dedicated to the god Julianos, the god of logic, wisdom, and the arts of magic of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Logic of Julianos - temporarily fortifying the intelligence attribute." },
    { id = "stendarr", description = "A shrine dedicated to the god Stendarr, the god of mercy, justice, and righteousness of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Protection of Stendarr - temporarily fortifying the strength attribute." },
    { id = "zenithar", description = "A shrine dedicated to the god Zenithar, the god of work, commerce, and wealth of the Nine Divines. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Blessing of Zenithar - temporarily fortifying the luck attribute." },
    { id = "azurashrine", description = "A shrine dedicated to the Daedric Prince Azura, whose sphere consists of dawn and dusk. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Shadow of Azura - temporarily fortifying the sneak skill." },
    { id = "balshrine", description = "A shrine dedicated to the Daedric Prince Molag Bal, whose sphere consists of domination and conquest. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Fury of Molag Bal - temporarily fortifying attack power." },
    { id = "boeshrine", description = "A shrine dedicated to the Daedric Prince Boethiah, whose sphere consists of deceit and treason. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Hand of Boethiah - temporarily fortifying the long blade skill." },
    { id = "dagonshrine", description = "A shrine dedicated to the Daedric Prince Mehrunes Dagon, whose sphere consists of destruction and revolution. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Wrath of Mehrunes Dagon - temporarily fortifying the destruction skill." },
    { id = "hermashrine", description = "A shrine dedicated to the Daedric Prince Hermaeus Mora, whose sphere consists of forbidden knowledge and destiny. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Wisdom of Hermaeus Mora - temporarily fortifying the intelligence attribute." },
    { id = "hircineshrine", description = "A shrine dedicated to the Daedric Prince Hircine, whose sphere consists the thrill of the hunt. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Arrow of Hircine - temporarily fortifying the marksman skill." },
    { id = "malashrine", description = "A shrine dedicated to the Daedric Prince Malacath, whose sphere consists of broken oaths and the spurned. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Oath of Malacath - temporarily fortifying the axe skill." },
    { id = "mephshrine", description = "A shrine dedicated to the Daedric Prince Mephala, whose sphere consists of murder and secrets. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Web of Mephala - temporarily fortifying the mercantile skill." },
    { id = "merishrine", description = "A shrine dedicated to the Daedric Prince Meridia, whose sphere consists of energies and life. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Light of Meridia - temporarily fortifying the restoration skill." },
    { id = "namirashrine", description = "A shrine dedicated to the Daedric Prince Namira, whose sphere consists of darkness and decay. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Power of Namira - temporarily fortifying the conjuration skill." },
    { id = "nocshrine", description = "A shrine dedicated to the Daedric Prince Nocturnal, whose sphere consists of shadows and mystery. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Hand of Nocturnal - temporarily fortifying the security skill." },
    { id = "peryishrine", description = "A shrine dedicated to the Daedric Prince Peryite, whose sphere consists of natural order and disease. Praying to this shrine can cure the worshipper of poisons, restore damaged attributes, or bless the worshipper with the Tribulation of Peryite - temporarily fortifying the endurance attribute." },
    { id = "sanguineshrine", description = "A shrine dedicated to the Daedric Prince Sanguine, whose sphere consists of hedonism and debauchery. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Tongue of Sanguine - temporarily fortifying the personality attribute." },
    { id = "sithisshrine", description = "A shrine dedicated to Sithis, the embodiment and personification of chaos and change. Worshipped and known as the Dread Father by the Dark Brotherhood, his worship is primarily done through sacrifice and murder. Praying to this shrine will bless the worshipper with the Embrace of Sithis - temporarily fortifying the sneak, light armor, and short blade skills." },
    { id = "sheoshrine", description = "A shrine dedicated to the Daedric Prince Sheogorath, whose sphere consists of madness and creativity. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Madness of Sheogorath - temporarily fortifying the luck attribute." },
    { id = "vileshrine", description = "A shrine dedicated to the Daedric Prince Clavicus Vile, whose sphere consists of pacts and tricks. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Charm of Clavicus Vile - temporarily fortifying the speechcraft skill." },
    { id = "almaalmsivishrine", description = "A shrine dedicated to Almalexia, one of the three God-Kings of Morrowind and a goddess of the Tribunal Temple associated with compassion, sympathy, and forgiveness. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with Lady's Grace - temporarily fortifying the endurance attribute." },
    { id = "sothaalmsivishrine", description = "A shrine dedicated to Sotha Sil, one of the three God-Kings of Morrowind and a god of the Tribunal Temple associated with magic, mysteries, and clockwork. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Soul of Sotha Sil - temporarily fortifying one's magicka." },
    { id = "vaeshrine", description = "A shrine dedicated to the Daedric Prince Vaermina, whose sphere consists of dreams and nightmares. Praying to this shrine can cure the worshipper of diseases and poisons, restore damaged attributes, or bless the worshipper with the Veil of Vaermina - temporarily fortifying the illusion skill." },
    { id = "smalldagothshrine", description = "A shrine dedicated to Dagoth Ur, the Lord of the Sixth House and father of the Divine Disease. Praying to this shrine can bless the worshipper with Innvocation of the Sharmat, Music of the Tribe Unmourned, or Dreamer of the Sixth House - temporaily decreasing one's resistence to corprus, allowing one to hear music of the Sixth House, or fortifying one's illusion skill respectively." },
    { id = "bug_bowl", description = "Ornamental bowl native to Morrowind and utilized both for practical and aesthetic purposes." },
    { id = "bug_cup", description = "Ornamental cup native to Morrowind and utilized both for practical and aesthetic purposes." },
    { id = "bug_fork", description = "Ornamental fork native to Morrowind and utilized both for practical and aesthetic purposes." },
    { id = "bug_knife", description = "Ornamental knife native to Morrowind and utilized both for practical and aesthetic purposes." },
    { id = "bug_pitcher", description = "Ornamental pitcher native to Morrowind and utilized both for practical and aesthetic purposes." },
    { id = "bug_plate", description = "Ornamental plate native to Morrowind and utilized both for practical and aesthetic purposes." },
    { id = "bug_spoon", description = "Ornamental spoon native to Morrowind and utilized both for practical and aesthetic purposes." },
    { id = "hap_adamantium_ingot", description = "A solid ingot of smelted and refined adamantium, free of impurties." },
    { id = "hap_copper_ingot", description = "A solid ingot of smelted and refined copper, free of impurties." },
    { id = "hap_daedric_ingot", description = "A solid ingot of smelted and refined ebony infused with the essence of a lesser daedra." },
    { id = "hap_dwemer_ingot", description = "A solid ingot of smelted and refined metal once used by the Dwemer." },
    { id = "hap_ebony_ingot", description = "A solid ingot of smelted and refined ebony, free of impurties." },
    { id = "hap_mithril_ingot", description = "A solid ingot of smelted and refined silver and iron, creating a special metal known as mithril." },
    { id = "hap_orch_ingot", description = "A solid ingot of smelted and refined orichalcum, free of impurties." },

    -- Potions
    { id = "tonagraph_ink", description = "Special ink required to use the dwemer artifact known as the Tonagrapher." },

    -- Souls
    { id = "1bantamguar", description = "Contains the soul of a Bantam Guar, a small creature native to Morrowind.", itemType = "creature" },
    { id = "1bantamguarcomp", description = "Contains the soul of a Bantam Guar, a small creature native to Morrowind.", itemType = "creature" },
    { id = "1farmbg", description = "Contains the soul of a Bantam Guar, a small creature native to Morrowind.", itemType = "creature" },
    { id = "1farmbgbby", description = "Contains the soul of a Bantam Guar, a small creature native to Morrowind.", itemType = "creature" },
    { id = "1nixie", description = "Contains the soul of Nixie, a Nix-Hound used by the Mones family to protect their herd.", itemType = "creature" },
    { id = "2bantamguar", description = "Contains the soul of a Bantam Guar, a small creature native to Morrowind.", itemType = "creature" },
    { id = "2farmbg", description = "Contains the soul of a Bantam Guar, a small creature native to Morrowind.", itemType = "creature" },
    { id = "2farmbgbby", description = "Contains the soul of a Bantam Guar, a small creature native to Morrowind.", itemType = "creature" },
    { id = "1tervvulcorpurs", description = "Contains the soul of Tervvul, an unfortunate adventurer turned into a Corprus Stalker.", itemType = "creature" },

    -- Tools
    { id = "hap_apprentice_needle", description = "Simple tool capable of repairing weapons and armor, best utilized by experienced armorers." },
	{ id = "hap_journeyman_needle", description = "Average tool capable of repairing weapons and armor, best utilized by experienced armorers."},
	{ id = "hap_master_needle", description = "Quality tool capable of repairing weapons and armor, best utilized by experienced armorers."},
	{ id = "hap_grandmaster_needle", description = "Superb tool capable of repairing weapons and armor, best utilized by experienced armorers."},
    { id = "hap_secretmaster_needle", description = "Greatest of tools capable of repairing weapons and armor, best utilized by experienced armorers."},

    -- Weapons
    { id = "shalk_spear", description = "Specially made spear crafted from the chitin of Shalks by the Zainab Ashlanders." }
}
local function initialized()
    if tooltipsComplete then
        for _, data in ipairs(tooltipData) do
            tooltipsComplete.addTooltip(data.id, data.description, data.itemType)
        end
    end
end
event.register("initialized", initialized)