return {
  interfaceName = "shopobjects_data",
  interface = {
    version = 1,
    objectTypes = {
      { SubType = "Amulet", Spawn_Chance = 80, Item_ID = "common_amulet_01", Class = "Clothier", MaxCount = 3,
                                                                                                          MinCount = 1, },
      { SubType = "Pants", Spawn_Chance = 80, Item_ID = "common_pants_01", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Pants", Spawn_Chance = 80, Item_ID = "common_pants_06", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Shirt", Spawn_Chance = 90, Item_ID = "common_shirt_02", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Shirt", Spawn_Chance = 90, Item_ID = "common_shirt_01", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 80, Item_ID = "common_skirt_01", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 80, Item_ID = "common_skirt_02", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 80, Item_ID = "common_skirt_03", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 80, Item_ID = "common_skirt_04", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 80, Item_ID = "common_skirt_05", Class = "Clothier", MaxCount = 3, MinCount = 1, },
      { SubType = "Pants", Spawn_Chance = 40, Item_ID = "expensive_pants_01", Class = "Clothier", MaxCount = 3,
                                                                                                          MinCount = 1, },
      { SubType = "Shirt", Spawn_Chance = 40, Item_ID = "expensive_shirt_02", Class = "Clothier", MaxCount = 3,
                                                                                                          MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 40, Item_ID = "expensive_skirt_03", Class = "Clothier", MaxCount = 3,
                                                                                                          MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 40, Item_ID = "expensive_skirt_02", Class = "Clothier", MaxCount = 3,
                                                                                                          MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 40, Item_ID = "expensive_skirt_01", Class = "Clothier", MaxCount = 3,
                                                                                                          MinCount = 1, },
      { SubType = "Ring", Spawn_Chance = 5, Item_ID = "exquisite_ring_01", Class = "Clothier", MaxCount = 1, MinCount = 1, },
      { SubType = "Robe", Spawn_Chance = 10, Item_ID = "exquisite_robe_01", Class = "Clothier", MaxCount = 1, MinCount = 1, },
      { SubType = "Shirt", Spawn_Chance = 10, Item_ID = "exquisite_shirt_01", Class = "Clothier", MaxCount = 1,
                                                                                                          MinCount = 1, },
      { SubType = "Amulet", Spawn_Chance = 5, Item_ID = "exquisite_amulet_01", Class = "Clothier", MaxCount = 1,
                                                                                                          MinCount = 1, },
      { SubType = "Skirt", Spawn_Chance = 15, Item_ID = "exquisite_skirt_01", Class = "Clothier", MaxCount = 1,
                                                                                                          MinCount = 1, },
    }
  }
}
