
---@class ClassImages.Config
local config= {}
config.metadata = toml.loadFile("Data Files\\DynamicClassImages-metadata.toml") --[[@as MWSE.Metadata]]
config.modName = "Динамические изображения классов"
---@class ClassImages.Config.mcm
local mcmDefault = {
    enabled = true,
    logLevel = "INFO"
}

---@type ClassImages.Config.mcm
config.mcm = mwse.loadConfig(config.modName, mcmDefault)
config.save = function()
    mwse.saveConfig(config.modName, config.mcm)
end

config.maxPieces = 15

config.slotsOrdered = {
    "Background_Left",
    "Background_Middle",
    "Background_Right",
    "Midground_Left",
    "Midground_Middle",
    "Midground_Right",
    "Foreground_Left",
    "Foreground_Middle",
    "Foreground_Right",
    "Below_Left_1",
    "Below_Left_2",
    "Below_Left_3",
    "Below_Left_4",
    "Below_Left_5",
    "Below_Middle",
    "Below_Right_1",
    "Below_Right_2",
    "Below_Right_3",
    "Above_Left_1",
    "Above_Left_2",
    "Above_Left_3",
    "Above_Left_4",
    "Above_Middle",
    "Above_Right_1",
    "Above_Right_2",
    "Above_Right_3",
    "Above_Right_4",
    "Above_Right_5",
    "Above_Left_5",
}


---@class ClassImages.ImageConfig
---@field imageBlockName string The name of the image block to use.
---@field createBlock boolean Whether to create a new block for the image.
---@field width number The width of the image block.
---@field height number The height of the image block.
---@field parentWidth number The width of the parent block.
---@field parentHeight number The height of the parent block.

---@type table<string, ClassImages.ImageConfig>
config.menuData = {
    MenuLevelUp = {
        imageBlockName = "MenuLevelUp_Picture",
        width = 390,
        height = 198,
        parentWidth = 390,
        parentHeight = 198,
    },
    MenuChooseClass = {
        imageBlockName = "MenuChooseClass_description",
        width = 256,
        height = 128,
        parentWidth = 264,
        parentHeight = 136,
    },
}

---@type  ClassImages.ImageConfig
config.tooltipConfig = {
    imageBlockName = "image_container",
    width = 384,
    height = 192,
    parentWidth = 384,
    parentHeight = 192,
}

config.createClassMenuConfig = {
    imageBlockName = "CreateClassImage",
    width  = 451,
    height = 256,
    parentWidth = 453,
    parentHeight = 258,
}

---@type ClassImages.ImagePiece[]
config.imagePieces = {
    {
        texture = "fill_A_R_alchemy",
        priority = 6,
        excludedPieces = { 310 },
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.alchemy },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type =tes3.specialization.magic },
        },
    },
    {
        texture = "fill_A_L_Merch",
        priority = 7,
        excludedPieces = { 8 },
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.mercantile, major = true },
            { type = tes3.skill.speechcraft, major = true },
        },
        attributeRequirements = {
            { type = tes3.attribute.personality },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_R_Merch",
        priority = 8,
        excludedPieces = { 7 },
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.mercantile, major = true },
            { type = tes3.skill.speechcraft, major = true },
        },
        attributeRequirements = {
            { type = tes3.attribute.personality },
        },
        specialisationRequirements = {},
    },
    {
        texture = "misc_gold_CR_Luck",
        priority = 9,
        excludedPieces = { 10, 181, 340, 350, 360, 551 },
        slots = { "Foreground_Right", "Below_Right_3" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.mercantile },
            { type = tes3.skill.sneak },
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {
            { type = tes3.attribute.luck },
        },
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_A_L_Luck_01",
        priority = 10,
        excludedPieces = { 9, 181, 551 },
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.luck },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_L_Books_01",
        priority = 11,
        excludedPieces = { 121 },
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.alteration },
            { type = tes3.skill.mysticism },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_A_L_Books_02",
        priority = 12,
        excludedPieces = { 121 },
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.restoration },
            { type = tes3.skill.destruction },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_A_L_Books_03",
        priority = 13,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.illusion },
            { type = tes3.skill.conjuration },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "armo_cuirass",
        priority = 20,
        excludedPieces = {},
        slots = { "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.unarmored },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_cuirass_sh",
        priority = 20,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.unarmored },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_R_Books_01",
        priority = 31,
        excludedPieces = { 291 },
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.mysticism },
            { type = tes3.skill.restoration },
			{ type = tes3.skill.destruction },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_A_R_Books_02",
        priority = 32,
        excludedPieces = { 122 },
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.alteration },
            { type = tes3.skill.conjuration },
			{ type = tes3.skill.illusion },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "bk_scroll_open_pickssoulgems",
        priority = 40,
        excludedPieces = { 50, 60, 70, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.enchant },
            { type = tes3.skill.security },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "bk_scroll_open_picks",
        priority = 50,
        excludedPieces = { 40, 60, 70, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.security },
            { type = tes3.skill.enchant, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "bk_scroll_open_soulgems",
        priority = 60,
        excludedPieces = { 40, 50, 70, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.enchant },
            { type = tes3.skill.security, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "fill_A_L_Soulgems",
        priority = 65,
        excludedPieces = { 40, 60, 320 },
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.enchant, major = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "bk_scroll_open",
        priority = 70,
        excludedPieces = { 120, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.security, negative = true },
            { type = tes3.skill.enchant, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "weap_spear",
        priority = 80,
        excludedPieces = {},
        slots = { "Below_Left_2" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.spear },
            { type = tes3.skill.acrobatics },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_alembic",
        priority = 90,
        excludedPieces = {},
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.alchemy },
            { type = tes3.skill.restoration },
            { type = tes3.skill.mercantile },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_ingred",
        priority = 100,
        excludedPieces = {},
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.alchemy }
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_waraxe",
        priority = 110,
        excludedPieces = {},
        slots = { "Above_Left_1" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.axe},
        },
        attributeRequirements = {
            { type = tes3.attribute.strength, negative = true },
        },
        specialisationRequirements = {
            { type = tes3.specialization.combat, negative = true },
        },
    },
    {
        texture = "fill_B_M_Books_01",
        priority = 121,
        excludedPieces = { 11, 12 },
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.alteration},
			{ type = tes3.skill.conjuration},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_B_M_Books_02",
        priority = 122,
        excludedPieces = { 32 },
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {
			{ type = tes3.skill.destruction},
			{ type = tes3.skill.illusion},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_B_M_Books_03",
        priority = 123,
        excludedPieces = {},
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {
			{ type = tes3.skill.mysticism},
			{ type = tes3.skill.restoration},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "bk_note",
        priority = 130,
        excludedPieces = { 40, 50, 60, 70, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_gloves",
        priority = 140,
        excludedPieces = { 130, 340, 350, 360 },
        slots = { "Foreground_Left", "Below_Left_3" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.handToHand, major = true },
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_hammer",
        priority = 150,
        excludedPieces = {},
        slots = { "Midground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.armorer, negative = true },
            { type = tes3.skill.heavyArmor },
        },
        attributeRequirements = {
            { type = tes3.attribute.endurance, negative = true },
			{ type = tes3.attribute.strength, negative = true },
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_lsword_ssword",
        priority = 160,
        excludedPieces = { 170, 410, 420 },
        slots = { "Below_Right_1" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.longBlade},
            { type = tes3.skill.shortBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_ssword",
        priority = 170,
        excludedPieces = { 160 },
        slots = { "Below_Right_1" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.shortBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_gems",
        priority = 180,
        excludedPieces = {},
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.athletics },
            { type = tes3.skill.acrobatics },
            { type = tes3.skill.security, major = true },
            { type = tes3.skill.sneak, major = true },
        },
        attributeRequirements = {
            { type = tes3.attribute.luck, negative = true },
        },
        specialisationRequirements = {},
    },
    {
        texture = "misc_gems_luck",
        priority = 181,
        excludedPieces = { 9,10, 551 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.athletics },
            { type = tes3.skill.acrobatics },
            { type = tes3.skill.security, major = true },
            { type = tes3.skill.sneak, major = true },
        },
        attributeRequirements = {
            { type = tes3.attribute.luck },
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_staff",
        priority = 190,
        excludedPieces = {},
        slots = { "Below_Left_4" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon },
            { type = tes3.skill.unarmored, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_shield_tower",
        priority = 200,
        excludedPieces = { 210, 220 },
        slots = { "Background_Left", "Background_Middle", "Midground_Left", "Midground_Middle" },
        shieldState = "isShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.heavyArmor, major = true },
            { type = tes3.skill.block },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_shield_iron",
        priority = 210,
        excludedPieces = { 200, 220 },
        slots = { "Midground_Middle" },
        shieldState = "isShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.block },
            { type = tes3.skill.mediumArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_shield_netch",
        priority = 220,
        excludedPieces = { 200, 210 },
        slots = { "Midground_Middle" },
        shieldState = "isShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.block },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_lute",
        priority = 230,
        excludedPieces = {},
        slots = { "Above_Right_1" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
        classRequirements = {
            { type = "bard" }
        }
    },
    {
        texture = "armo_boots_leather",
        priority = 240,
        excludedPieces = { 250, 255 },
        slots = { "Background_Right", "Midground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.mediumArmor },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_boots_netch",
        priority = 250,
        excludedPieces = { 240, 255 },
        slots = { "Midground_Right", "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.lightArmor },
            { type = tes3.skill.sneak },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_boots_netch_CL",
        priority = 255,
        excludedPieces = { 240, 250 },
        slots = { "Background_Left", "Midground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.lightArmor },
            { type = tes3.skill.sneak },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_picks",
        priority = 261,
        excludedPieces = {},
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.security},
            { type = tes3.skill.speechcraft, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_picks_gold",
        priority = 262,
        excludedPieces = { 340, 350 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.security},
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_R_picks",
        priority = 265,
        excludedPieces = { 40, 50, 261, 262 },
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.security},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_warhammer",
        priority = 270,
        excludedPieces = {},
        slots = { "Background_Right", "Midground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
	{
        texture = "fill_C_L_Books_01",
        priority = 281,
        excludedPieces = { 31 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.alteration},
			{ type = tes3.skill.conjuration},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_L_Books_02",
        priority = 282,
        excludedPieces = { 291, 320 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.destruction},
			{ type = tes3.skill.illusion},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_L_Books_03",
        priority = 283,
        excludedPieces = { 292 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.mysticism},
			{ type = tes3.skill.restoration},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_R_Books_01",
        priority = 291,
        excludedPieces = { 282, 320 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.alteration},
			{ type = tes3.skill.conjuration},
			{ type = tes3.skill.destruction},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_R_Books_02",
        priority = 292,
        excludedPieces = { 283 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.illusion},
			{ type = tes3.skill.mysticism},
			{ type = tes3.skill.restoration},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_R_abacus",
        priority = 295,
        excludedPieces = { 296 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.mercantile, major = true },
        },
        attributeRequirements = {
            { type = tes3.attribute.intelligence},
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_C_L_abacus",
        priority = 296,
        excludedPieces = { 295 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.mercantile, major = true },
        },
        attributeRequirements = {
            { type = tes3.attribute.intelligence},
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_dagger",
        priority = 300,
        excludedPieces = { 360 },
        slots = { "Below_Right_2" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.shortBlade, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_dagger_poison",
        priority = 305,
        excludedPieces = {},
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.shortBlade },
            { type = tes3.skill.sneak },
            { type = tes3.skill.alchemy, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "misc_mortar",
        priority = 310,
        excludedPieces = { 6 },
        slots = { "Midground_Left", "Above_Left_1" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.alchemy},
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type =tes3.specialization.magic },
        },
    },
    {
        texture = "misc_soulgems",
        priority = 320,
        excludedPieces = { 282 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.enchant},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_waraxe_sh",
        priority = 330,
        excludedPieces = { 331 },
        slots = { "Above_Left_1" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.axe},
        },
        attributeRequirements = {
            { type = tes3.attribute.strength, negative = true },
        },
        specialisationRequirements = {
            { type = tes3.specialization.combat, negative = true },
        },
    },
    {
        texture = "weap_waraxe_sh_02",
        priority = 331,
        excludedPieces = { 330 },
        slots = { "Above_Left_1" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.axe},
        },
        attributeRequirements = {
            { type = tes3.attribute.strength, negative = true },
        },
        specialisationRequirements = {
            { type = tes3.specialization.combat },
        },
    },
    {
        texture = "misc_gold_CR",
        priority = 340,
        excludedPieces = { 9, 350, 360 },
        slots = { "Foreground_Right", "Below_Right_3" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.mercantile },
            { type = tes3.skill.sneak },
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {
            { type = tes3.attribute.luck, negative = true },
        },
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "misc_gold_CL",
        priority = 350,
        excludedPieces = { 340, 360 },
        slots = { "Foreground_Left", "Below_Left_5" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.mercantile },
            { type = tes3.skill.sneak },
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "misc_gold_CL_quiver",
        priority = 355,
        excludedPieces = { 340, 350, 360 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, major = true },
            { type = tes3.skill.sneak },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_club",
        priority = 360,
        excludedPieces = { 140, 300, 340, 350, 355 },
        slots = { "Above_Left_2" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon, major = true},
            { type = tes3.skill.unarmored},
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.combat },
        },
    },
    {
        texture = "weap_stars",
        priority = 370,
        excludedPieces = {},
        slots = { "Above_Left_3" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman},
            { type = tes3.skill.sneak},
        },
        attributeRequirements = {
            { type = tes3.attribute.agility},
            { type = tes3.attribute.speed},
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_battleaxe",
		priority = 380,
		excludedPieces = {},
		slots = { "Above_Left_4" },
		shieldState = "noShield",
        isGold = false,
		isFiller = false,
		skillRequirements = {
			{ type = tes3.skill.axe},
		},
		attributeRequirements = {
			{ type = tes3.attribute.strength},
		},
		specialisationRequirements = {
			{ type = tes3.specialization.combat },
		},
	},
    {
        texture = "weap_battleaxe_sh",
        priority = 390,
        excludedPieces = {},
        slots = { "Above_Left_4" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.axe},
        },
        attributeRequirements = {
            { type = tes3.attribute.strength},
        },
        specialisationRequirements = {
            { type = tes3.specialization.combat },
        },
    },
    {
        texture = "misc_repairkit",
        priority = 400,
        excludedPieces = { 360, 401 },
        slots = { "Above_Right_4" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.armorer},
            { type = tes3.skill.heavyArmor},
        },
        attributeRequirements = {
            { type = tes3.attribute.endurance},
            { type = tes3.attribute.strength},
        },
        specialisationRequirements = {},
    },
    {
        texture = "armo_helm_sh",
        priority = 401,
        excludedPieces = {},
        slots = { "Above_Left_5" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.heavyArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_lsword",
        priority = 410,
        excludedPieces = { 160, 420 },
        slots = { "Below_Right_1" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.longBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_lsword_sh",
        priority = 420,
        excludedPieces = { 160, 420 },
        slots = { "Above_Right_2" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.longBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_mace",
        priority = 430,
        excludedPieces = {},
        slots = { "Above_Right_3" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_mace_sh",
        priority = 440,
        excludedPieces = {},
        slots = { "Above_Right_3" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_repairkit_sh",
        priority = 460,
        excludedPieces = {},
        slots = { "Above_Right_4" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.armorer},
            { type = tes3.skill.heavyArmor},
        },
        attributeRequirements = {
            { type = tes3.attribute.endurance},
            { type = tes3.attribute.strength},
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_bow",
        priority = 470,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, minor = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_bow_sh",
        priority = 480,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, minor = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_bowarrows",
        priority = 490,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_bowarrows_sh",
        priority = 500,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_L_Booze_01",
        priority = 510,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.strength },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_L_Booze_02",
        priority = 520,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.endurance },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_R_Booze_01",
        priority = 530,
        excludedPieces = {},
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.strength },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_R_Booze_02",
        priority = 540,
        excludedPieces = {},
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.endurance },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_C_L_gauntlet",
        priority = 545,
        excludedPieces = { 546 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.heavyArmor },
			{ type = tes3.skill.mediumArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_R_gauntlet",
        priority = 546,
        excludedPieces = { 545 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.heavyArmor },
			{ type = tes3.skill.mediumArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_L_Booze_01",
        priority = 550,
        excludedPieces = {},
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.strength },
			{ type = tes3.attribute.endurance },
        },
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_C_R_Luck_01",
        priority = 551,
        excludedPieces = { 9, 10, 181 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.luck },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_C_R_Booze_01",
        priority = 560,
        excludedPieces = {},
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.strength },
			{ type = tes3.attribute.endurance },
        },
        specialisationRequirements = {},
		isOr = true,
    },
    {
        texture = "fill_A_L_Books_04",
        priority = 561,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {
            { type = tes3.attribute.intelligence },
        },
        specialisationRequirements = {},
    },
    {
        texture = "fill_B_M_Waterskin_01",
        priority = 580,
        excludedPieces = { 590 },
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.unarmored, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "fill_B_M_Satchel_01",
        priority = 590,
        excludedPieces = { 580 },
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.unarmored },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "fill_A_L_coinpurse",
        priority = 610,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {
            { type = tes3.skill.sneak },
			{ type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
}

return config