-- ============================================================
-- GLOBAL SCRIPT (global.lua)
-- ============================================================
local core
local world
pcall(function() core = require('openmw.core'); world = require('openmw.world') end)
local GENERATE_DATA = false
-- first run ingame, paste the spell list into SPELL_LIST, then run offline and copy the script text




-- List of spell IDs (index 1+, 0 = do nothing)
SPELL_LIST = {
"test_spell",
"voice of the emperor",
"eye of fear",
"eye of night",
"immune to poison",
"immune to disease",
"beast tongue",
"star of the west",
"adrenaline rush",
"resist poison_75",
"resist disease_75",
"resist magicka_50",
"thunder fist",
"woad",
"immune to frost",
"resist shock_50",
"weakness fire_50",
"weakness magicka_50",
"weakness frost_25",
"weakness shock_25",
"burning hand",
"ancestor guardian",
"resist fire_50",
"dragon skin",
"magicka mult bonus_5",
"magicka mult bonus_15",
"hearth heal",
"frost_shield",
"wizard's brand",
"argonian breathing",
"buoyancy",
"burden",
"burden touch",
"burden of sin",
"heavy burden",
"heavy burden touch",
"great burden of sin",
"crushing burden",
"crushing burden touch",
"crushing burden of sin",
"weary",
"cruel weary",
"dire weary",
"great feather",
"strong feather",
"feather",
"ulms juicedaw's feather",
"fire barrier",
"fire shield",
"strong fire shield",
"fierce fire shield",
"frost barrier",
"strong frost shield",
"fierce frost shield",
"jump",
"tinur's hoptoad",
"great levitate",
"strong levitate",
"levitate",
"wild levitate",
"fenrick's doorjam",
"lock",
"great open",
"strong open",
"wild open",
"open",
"ondusi's open door",
"shield",
"first barrier",
"second barrier",
"third barrier",
"fourth barrier",
"fifth barrier",
"sixth barrier",
"shock barrier",
"shock shield",
"strong shock shield",
"fierce shock shield",
"water breathing",
"vivec's kiss",
"water walking",
"blessed touch",
"blessed word",
"holy touch",
"holy word",
"saintly touch",
"saintly word",
"bound dagger",
"bound longsword",
"bound mace",
"bound battle-axe",
"bound spear",
"bound longbow",
"bound cuirass",
"bound helm",
"bound gauntlets",
"bound boots",
"bound shield",
"ghost guard",
"summon ancestral ghost",
"summon bonelord",
"summon clanfear",
"summon daedroth",
"summon dremora",
"summon golden saint",
"summon greater bonewalker",
"summon least bonewalker",
"summon scamp",
"bone guard",
"summon winged twilight",
"turn undead",
"curse agility",
"grave curse: agility",
"dread curse: agility",
"stumble",
"curse endurance",
"grave curse: endurance",
"dread curse: endurance",
"gripes",
"curse fatigue",
"grave curse: fatigue",
"dread curse: fatigue",
"doze",
"fleabite",
"hornhand",
"ironhand",
"knuckle luck",
"ash curse: fatigue",
"curse health",
"grave curse: health",
"dread curse: health",
"spirit knife",
"blood sacrifice",
"heartbite",
"ash curse: health",
"firefist",
"five fingers of pain",
"black hand",
"stormhand",
"curse intelligence",
"grave curse: intelligence",
"dread curse: intelligence",
"fuddle",
"curse luck",
"grave curse: luck",
"dread curse: luck",
"hex",
"curse personality",
"grave curse: personality",
"dread curse: personality",
"evil eye",
"curse speed",
"grave curse: speed",
"dread curse: speed",
"clench",
"curse spell points",
"grave curse: spell points",
"dread curse: spell points",
"soulpinch",
"ash curse: spell points",
"curse strength",
"grave curse: strength",
"dread curse: strength",
"curse willpower",
"grave curse: willpower",
"dread curse: willpower",
"woe",
"armor eater",
"disintegrate armor",
"weapon eater",
"disintegrate weapon",
"clumsy touch",
"clumsiness",
"wild clumsiness",
"straining touch",
"strain",
"wild strain",
"exhausting touch",
"exhaustion",
"hand of sleep",
"ordeal of st. olms",
"sleep",
"wild exhaustion",
"wearying touch",
"weariness",
"hand of decay",
"sphere of negation",
"wild weeping wound",
"wounding touch",
"weeping wound",
"wizard's fire",
"wound",
"distracting touch",
"distraction",
"wild distraction",
"scourge blade",
"misfortunate touch",
"misfortune",
"wild misfortune",
"spite touch",
"spite",
"wild spite",
"drain enchant",
"drain destruction",
"drain alteration",
"drain illusion",
"drain conjuration",
"drain mysticism",
"drain restoration",
"drain alchemy",
"drain unarmored",
"drain block",
"drain armorer",
"drain medium armor",
"drain heavy armor",
"drain blunt weapon",
"drain long blade",
"drain axe",
"drain spear",
"drain athletics",
"drain security",
"drain sneak",
"drain acrobatics",
"drain light armor",
"drain short blade",
"drain marksman",
"drain mercantile",
"drain speechcraft",
"drain hand-to-hand",
"touchdrain enchant",
"touchdrain destruction",
"touchdrain alteration",
"touchdrain illusion",
"touchdrain conjuration",
"touchdrain mysticism",
"touchdrain restoration",
"touchdrain alchemy",
"touchdrain unarmored",
"touchdrain block",
"touchdrain armorer",
"touchdrain light armor",
"touchdrain medium armor",
"touchdrain heavy armor",
"touchdrain blunt weapon",
"touchdrain long blade",
"touchdrain axe",
"touchdrain spear",
"touchdrain athletics",
"touchdrain security",
"touchdrain sneak",
"touchdrain acrobatics",
"touchdrain short blade",
"touchdrain marksman",
"touchdrain mercantile",
"touchdrain speechcraft",
"touchdrain hand to hand",
"torpor touch",
"torpor",
"wild torpor",
"flay spirit",
"flay spirit [ranged]",
"gash spirit",
"gash spirit [ranged]",
"magicka leech",
"spell drain",
"wild flay spirit",
"strength leech",
"wild weakness",
"weakening touch",
"weakness",
"tempting touch",
"temptation",
"wild temptation",
"burning touch",
"fire storm",
"fireball",
"god's fire",
"firebloom",
"cruel firebloom",
"fire bite",
"flame",
"flamebolt",
"freezing touch",
"frostbite",
"frostball",
"frostbloom",
"shockbloom",
"wild shockbloom",
"shard",
"deadly poison",
"deadly poison [ranged]",
"poison",
"potent poison",
"potent poison [ranged]",
"alit bite",
"poisonbloom",
"sting",
"viper",
"viperbolt",
"lightning bolt",
"lightning storm",
"shockball",
"shocking touch",
"smite the ungodly",
"shockbite",
"spark",
"weakness to blight disease",
"weakness to corpus disease",
"weakness to common disease",
"dire weakness to fire",
"weakness to fire",
"dire weakness to frost",
"weakness to frost",
"dire weakness to magicka",
"weakness to magicka",
"dire weakness to poison",
"weakness to poison",
"dire weakness to shock",
"weakness to shock",
"force bolt",
"wizard rend",
"blind",
"alad's caliginy",
"erelvam's wild sty",
"crying eye",
"soothe the savage beast",
"calming touch",
"command beast",
"commanding touch",
"frenzy beast",
"frenzying touch",
"demoralize beast",
"demoralizing touch",
"rally beast",
"rallying touch",
"calm creature",
"calm humanoid",
"command creature",
"command humanoid",
"frenzy creature",
"frenzy humanoid",
"demoralize creature",
"demoralize humanoid",
"rally creature",
"rally humanoid",
"chameleon",
"shadowmask",
"golanar's eye-maze",
"shadow form",
"charming touch",
"charm mortal",
"brevusa's averted eyes",
"invisibility",
"hide",
"concealment",
"light",
"night-eye",
"spider touch",
"paralysis",
"medusa's gaze",
"sanctuary",
"father's hand",
"sotha's grace",
"far silence",
"silence",
"noise",
"cruel noise",
"dire noise",
"earwig",
"cruel earwig",
"dire earwig",
"wild earwig",
"almsivi intervention",
"detect enchantment",
"tevral's hawkshaw",
"purge magic",
"self dispel",
"touch dispel",
"almalexia's grace",
"divine intervention",
"mark",
"recall",
"reflect",
"llivam's reversal",
"strong reflect",
"wild reflect",
"sotha's mirror",
"soul trap",
"weak spelldrinker",
"tranasa's spelltrap",
"strong spelldrinker",
"wild spelldrinker",
"vivec's feast",
"spell absorption",
"telekinesis",
"shalidor's mirror",
"absorb agility",
"absorb agility [ranged]",
"absorb endurance",
"absorb endurance [ranged]",
"absorb fatigue",
"absorb fatigue [ranged]",
"energy leech",
"absorb health",
"absorb health [ranged]",
"vampire's kiss",
"vampire touch",
"righteousness",
"drain blood",
"absorb intelligence",
"absorb intelligence [ranged]",
"absorb luck",
"absorb luck [ranged]",
"absorb personality",
"absorb personality [ranged]",
"absorb speed",
"absorb speed [ranged]",
"absorb spell points",
"absorb spell points [ranged]",
"absorb strength",
"absorb strength [ranged]",
"absorb willpower",
"absorb willpower [ranged]",
"red despair",
"crimson despair",
"blood despair",
"vivec's tears",
"cure common disease",
"rilm's cure",
"rilm's gift",
"cure corpus disease",
"free action",
"balyna's antidote",
"cure poison",
"seryn's gift",
"resist fire",
"resist cold",
"resist poison",
"resist shock",
"fortify acrobatics skill",
"fortify alchemy skill",
"fortify alteration skill",
"fortify armorer skill",
"fortify athletics skill",
"fortify axe skill",
"fortify block skill",
"fortify blunt weapons skill",
"fortify conjuration skill",
"fortify destruction skill",
"fortify enchant skill",
"fortify hand to hand skill",
"fortify heavy armor skill",
"fortify illusion skill",
"fortify light armor skill",
"fortify unarmored skill",
"fortify long blade skill",
"fortify marksman skill",
"fortify medium armor skill",
"fortify mercantile skill",
"fortify mysticism skill",
"fortify restoration skill",
"fortify security skill",
"fortify short blade skill",
"fortify sneak skill",
"fortify spear skill",
"fortify speechcraft skill",
"shrine speechcraft skill",
"shrine acrobatics skill",
"shrine alchemy skill",
"shrine alteration skill",
"shrine armorer skill",
"shrine athletics skill",
"shrine axe skill",
"shrine block skill",
"shrine blunt weapon skill",
"shrine conjuration skill",
"shrine destruction skill",
"shrine enchant skill",
"shrine hand to hand skill",
"shrine heavy armor skill",
"shrine illusion skill",
"shrine light armor skill",
"shrine long blade skill",
"shrine marksman skill",
"shrine medium armor skill",
"shrine mercantile skill",
"shrine mysticism skill",
"shrine restoration skill",
"shrine security skill",
"shrine short blade skill",
"shrine sneak skill",
"shrine spear skill",
"shrine unarmored skill",
"imperial unarmored skill",
"imperial acrobatics skill",
"imperial alchemy skill",
"imperial alteration skill",
"imperial armorer skill",
"imperial athletics skill",
"imperial axe skill",
"imperial block skill",
"imperial blunt weapon skill",
"imperial conjuration skill",
"imperial destruction skill",
"imperial enchant skill",
"imperial hand to hand skill",
"imperial heavy armor skill",
"imperial illusion skill",
"imperial light armor skill",
"imperial long blade skill",
"imperial marksman skill",
"imperial medium armor skill",
"imperial mercantile skill",
"imperial mysticism skill",
"imperial restoration skill",
"imperial security skill",
"imperial short blade skill",
"imperial sneak skill",
"imperial spear skill",
"imperial speechcraft skill",
"saguine leaping",
"assured leaping",
"masterful leaping",
"surpassing leaping",
"nimbleness",
"assured sublime wisdom",
"masterful sublime wisdom",
"surpassing sublime wisdom",
"assured golden wisdom",
"masterful golden wisdom",
"surpassing golden wisdom",
"assured martial craft",
"masterful martial craft",
"surpassing martial craft",
"assured fleetness",
"masterful fleetness",
"surpassing fleetness",
"assured deep biting",
"masterful deep biting",
"surpassing deep biting",
"hand of the hart-king",
"assured denial",
"masterful denial",
"surpassing denial",
"assured smiting",
"masterful smiting",
"surpassing smiting",
"assured transcendant wisdom",
"masterful transcendant wisdom",
"surpassing transcendant wisdom",
"assured red wisdom",
"masteful red wisdom",
"surpassing red wisdom",
"assured transfiguring wisdom",
"masterful transfiguring wisdom",
"surpassing transfiguring wisdom",
"fortitude",
"lady's grace",
"vigor",
"reman's girdle",
"spirit of nerevar",
"assured horny fist",
"masterful horny fist",
"surpassing horny fist",
"vitality",
"ysmir's cough",
"roris's bloom",
"nibenay's wit",
"blood gift",
"assured stolid armor",
"masteful stolid armor",
"surpassing stolid armor",
"assured silver wisdom",
"masterful silver wisdom",
"surpassing silver wisdom",
"wisdom",
"assured nimble armor",
"masterful nimble armor",
"surpassing nimble armor",
"the eight gifts",
"assured hewing",
"masterful hewing",
"surpassing hewing",
"wulfharthÔÇÖs cups",
"jack of trades",
"vivec's mystery",
"assured sureflight",
"masterful sureflight",
"surpassing sunlight",
"surpassing sureflight",
"assured balanced armor",
"masterful balanced armor",
"surpassing balanced armor",
"assured enterprise",
"masterful enterprise",
"surpassing enterprise",
"assured unseen wisdom",
"masterful unseen wisdom",
"surpassing unseen wisdom",
"charisma",
"colovia's grace",
"assured green wisdom",
"masterful green wisdom",
"surpassing green wisdom",
"assured safekeeping",
"masterful safekeeping",
"surpassing safekeeping",
"assured swiftblade",
"masterful swiftblade",
"surpassing swiftblade",
"assured stalking",
"masterful stalking",
"surpassing stalking",
"assured impaling thrust",
"masterful impaling thrust",
"surpassing impaling thrust",
"assured glib speech",
"masterful glib speech",
"surpassing glib speech",
"feet of notorgo",
"skylamp's shadow",
"soul of sotha sil",
"powerwell",
"orc's strength",
"the eight wonders",
"assured fluid evasion",
"masterful fluid evasion",
"surpassing fluid evasion",
"iron will",
"the rock of llothis",
"emperor's blessing",
"divine aid",
"the moth-wing mirror",
"the red diamond",
"shield of the armiger",
"shield of st. delyn",
"vivec's mercy",
"poet's whim",
"blightguard",
"great resist common disease",
"olms' benediction",
"seryn's blessing",
"variable resist common disease",
"the dove's promise",
"resist common disease",
"great resist corpus disease",
"meris's warding",
"strong resist corpus disease",
"variable resist corpus disease",
"resist corpus disease",
"great resist fire",
"strong resist fire",
"flameguard",
"variable resist fire",
"great resist frost",
"frostguard",
"strong resist frost",
"variable resist frost",
"resist frost",
"great resist magicka",
"shockguard",
"strong resist magicka",
"variable resist magicka",
"resist magicka",
"greater resist poison",
"magickguard",
"strong resist poison",
"variable resist poison",
"great resist shock",
"poisonguard",
"strong resist shock",
"variable resist shock",
"restore agility",
"restore endurance",
"rest of st. merris",
"stamina",
"balyna's efficacious balm",
"balyna's perfect balm",
"balyna's soothing balm",
"great heal companion",
"regenerate",
"rapid regenerate",
"strong heal companion",
"troll's blood",
"veloth's benison",
"veloth's gift",
"veloth's grace",
"heal companion",
"mother's kiss",
"restore intelligence",
"restore luck",
"restore personality",
"restore speed",
"restore strength",
"restore willpower",
"baleful glower",
"eye of talos",
"wild fortify acrobatics skill",
"wild fortify alchemy skill",
"wild fortify alteration skill",
"wild fortify armorer skill",
"wild fortify athletics skill",
"wild fortify axe skill",
"wild fortify block skill",
"wild fortify blunt weapon skill",
"wild fortify conjuration skill",
"wild fortify destruction skill",
"wild fortify enchant skill",
"wild fortify hand to hand skill",
"wild fortify heavy armor skill",
"wild fortify light armor skill",
"wild fortify long blade skill",
"wild fortify marksman skill",
"wild fortify medium armor skill",
"wild fortify mercantile skill",
"wild fortify mysticism skill",
"wild fortify restoration skill",
"wild fortify security skill",
"wild fortify short blade skill",
"wild fortify sneak skill",
"wild fortify spear skill",
"wild fortify speechcraft skill",
"wild fortify unarmored skill",
"sanil's murdrum",
"slave belt",
"ash woe blight",
"black-heart blight",
"chanthrax blight",
"ash-chancre",
"rattles",
"yellow tick",
"brown rot",
"collywobbles",
"swamp fever",
"wither",
"ataxia",
"droops",
"rust chancre",
"dampworm",
"greenspore",
"serpiginous dementia",
"chills",
"witbane",
"helljoint",
"rockjoint",
"orc_beserk",
"dispel",
"slowfall",
"summon storm atronach",
"summon flame atronach",
"summon frost atronach",
"summon skeletal minion",
"lightning shield",
"daedric bite",
"daedric intelligence",
"daedric health",
"daedric endurance",
"daedric agility",
"daedric luck",
"daedric personality",
"daedric speed",
"daedric strength",
"daedric willpower",
"daedric fatigue",
"corprus",
"wrath of uthol",
"hand of uthol",
"god's frost",
"god's spark",
"mirpal_waterwalk",
"lustidrike_cocktail",
"frost bolt",
"frost shield",
"frost storm",
"frostfist",
"dynamic sublime wisdom",
"dynamic golden wisdom",
"dynamic martial craft",
"dynamic fleetness",
"dynamic deep biting",
"dynamic denial",
"dynamic smiting",
"dynamic transcendant wisdom",
"dynamic red wisdom",
"dynamic transfiguring wisdom",
"dynamic horny fist",
"dynamic stolid armor",
"dynamic silver wisdom",
"dynamic nimble armor",
"dynamic hewing",
"dynamic sureflight",
"dynamic balanced armor",
"dynamic enterprise",
"dynamic unseen wisdom",
"dynamic green wisdom",
"dynamic safekeeping",
"dynamic swiftblade",
"dynamic stalking",
"dynamic impaling thrust",
"dynamic glib speech",
"dynamic fluid evasion",
"vampire sun damage",
"vampire attributes",
"vampire skills",
"vampire immunities",
"vampire levitate",
"vampire quarra specials",
"vampire aundae specials",
"vampire berne specials",
"star-curse",
"magicka mult bonus_10",
"wombburn",
"mara's gift",
"charioteer ability",
"lady's favor",
"blood of the north",
"akaviri danger-sense",
"elfborn ability",
"fay ability",
"trollkin ability",
"warywrd ability",
"mooneye ability",
"moonshadow",
"beggar's nose spell",
"mooncalf ability",
"tower key",
"lover's kiss",
"resist magicka_25",
"sheogorath's blessing",
"ghost ability",
"shrine_gnisis_sp",
"shrine_ghostgate_sp",
"shrine_koalcave_sp",
"shrine_kummu_sp",
"shrine_palace_sp",
"shrine_puzzle_sp",
"shrine_stopmoon_sp",
"skillmephala_sp",
"shrine_dagonfel_sp",
"shrine_aldsotha_sp",
"shrine_balur_sp",
"shrine_alddaedroth_sp",
"wrath of vemyn",
"hand of vemyn",
"wrath of endus",
"hand of endus",
"wrath of odros",
"hand of odros",
"wrath of tureynul",
"hand of tureynul",
"wrath of gilvoth",
"hand of gilvoth",
"wrath of araynys",
"hand of araynys",
"wrath of dagoth",
"hand of dagoth",
"nchuleftingth_trap_sp",
"ghost_snake",
"dagoth's bosom",
"vampire blood aundae",
"vampire blood berne",
"vampire blood quarra",
"witchwither",
"water walking (unique)",
"masterful red wisdom",
"masterful stolid armor",
"healingtouch_sp_uniq",
"immune to normal weapons",
"reflect_60",
"ghost curse",
"resist frost_75",
"resist shock_75",
"regenerate [ability]",
"chameleon_60",
"weakness frost_60",
"immune to fire",
"resist frost_50",
"immune to shock",
"resist fire_75",
"ogrul's_strong_again",
"ogrul's_staunch_again",
"ogrul's_quick_again",
"ogrul's_lucky_again",
"detect_creature",
"swimmer's_blessing",
"shrine_maargan_sp",
"blood_rage_unique",
"shadow weave",
"summon hunger",
"detect_key",
"reflect_20",
"zenithar_gospel",
"zenithar_blessing",
"blindself",
"cure common disease other",
"tap energy",
"cure blight disease",
"cure common disease victim",
"troll strength",
"sp_glyphofweakness",
"ash feast",
"drain health_fatigue",
"poison_powerful",
"suicide_test",
"sp_nchurdamzsummon",
"sp_ccd",
"vivec's_wrath",
"trap_poison00",
"trap_fire00",
"trap_health00",
"trap_frost00",
"trap_paralyze00",
"trap_shock00",
"trap_silence00",
"sp_hvaulttrap",
"father ahaz",
"sp_rangedheal",
"sp_touchprotect",
"shrine_sanctus_sp",
"shrine_mountkand_sp",
"scrib_paralysis",
"corprus immunity",
"blight disease immunity",
"common disease immunity",
"cure poison touch",
"resist paralysis",
"fire_fathasa_unique",
"chameleon_100_unique",
"shalk_firebite",
"seryn's shield",
"veloth's indwelling",
"aralor's intervention",
"vivec's fury",
"vivec's humility",
"quicksilver",
"emasculate",
"enervate",
"enervating touch",
"frostball_large",
"poisonous touch",
"viperbite",
"shock",
"fireball_large",
"turn of the wheel",
"enrichment",
"shockball_large",
"panacea",
"cure_blight_target",
"summon_centurion_unique",
"roris' bloom",
"meris' warding",
"icarian_flight",
"luck_of_the_emperor",
"shrine_maargan_npc_sp",
"water_walk_unique",
"weakness to corprus disease",
"cure corprus disease",
"great resist corprus disease",
"strong resist corprus disease",
"variable resist corprus disease",
"resist corprus disease",
"weakness poison_50",
"kwama_poison",
"cure blight_self",
"wulfharth's cups",
"dagoth_ur_shield_01",
"dagoth_ur_shield_02",
"dagoth_ur_shield_03",
"dagoth_ur_shield_04",
"hand of azura",
"lady's grace shrine",
"vivec_abilities",
"hand of vivec",
"wrath of vivec",
"shrine_balur2_sp",
"dratha_spite",
"gothren_gout",
"aryon_rest",
"restore attributes",
"almsivi restoration",
"royal_blood",
"royal_resistance",
"blood curse: fatigue",
"resist paralysis_50",
"resist fire_100",
"her_mirror",
"her_hand",
"her_ironskin",
"her_tamed_lightning",
"her_reflected_glory",
"trap_fire_killer",
"trap_frost_killer",
"trap_shock_killer",
"trap_poison_killer",
"almalexia's blessing",
"resist paralysis_100",
"resist normal weapons_50",
"prox_mine_fire",
"prox_mine_frost",
"prox_mine_shock",
"prox_mine_poison",
"prox_mine_life",
"relvel_damage",
"relvel_shield",
"relvel_regenerate",
"proj_trap_spell",
"heavy_eyes_unique",
"fireball_bar_uni",
"gaenor_spell",
"crimson_plague",
"shockimperfect",
"rotbone",
"her_hand_2",
"her_mirror_2",
"gaenor_abilities",
"almalexia's shield",
"grace of almsivi",
"almalexia's light",
"dire shockball",
"almalexia's wrath",
"regen_imperfect",
"her_protection",
"hroldar_death",
"ulfgar_ghost_sp",
"ulfgar_ghost_ring",
"stone_erlendr",
"stone_ulfgar",
"stone_hunroor",
"stone_nikulas",
"immune to paralysis",
"snowshield",
"hrothmund blessing",
"colony_rug",
"werewolf blood",
"werewolf hunger",
"touchdrain agility",
"glenmoril_ring",
"werewolf_ritual_ring",
"werewolf vision",
"werewolf regeneration",
"bm_bearregen_unique",
"bm_draugr_curse",
"brittlewind",
"bm_resistpara_unique",
"bm_summonwolf",
"bm_summonbear",
"bm_summonbonewolf",
"bm_paralyze_hirc",
"bm_strresist",
"bm_spdresist",
"bm_huntresist",
"bm_fireregen",
"bm_frstgnt",
"bm_hunterwind",
"werewolf resists",
"t_aka_tsaesci_health",
"t_aka_tsaesci_regen",
"t_aka_tsaesci_restore",
"t_ayl_cnj_summonwelkyndspirit",
"t_ayl_des_dwelkynd_fir",
"t_ayl_des_dwelkynd_frs",
"t_ayl_des_dwelkynd_shk",
"t_ayl_des_gas",
"t_chi_ab_resistmagicka",
"t_chi_ab_resistshock",
"t_chi_ab_weaknesstoblight",
"t_chi_pow_ancestorwarden",
"t_chi_pow_spritofquey",
"t_com_alt_biterbitten",
"t_com_alt_daedrafireeye",
"t_com_alt_dalgorsentwining",
"t_com_alt_dreughsgrace",
"t_com_alt_falling1stbarrier",
"t_com_alt_fling",
"t_com_alt_forcewall",
"t_com_alt_fuchongentledescent",
"t_com_alt_grandvigil",
"t_com_alt_greatervigil",
"t_com_alt_jumping",
"t_com_alt_lesservigil",
"t_com_alt_lightness",
"t_com_alt_slowfalling",
"t_com_alt_spellshield",
"t_com_alt_suicidedive",
"t_com_alt_tothejakhajay",
"t_com_alt_weightofguilt",
"t_com_alt_wizardlock",
"t_com_cnj_assistance",
"t_com_cnj_bloodspirit",
"t_com_cnj_bloodletter",
"t_com_cnj_bonesong",
"t_com_cnj_boundgreatsword",
"t_com_cnj_boundgreaves",
"t_com_cnj_boundpauldron",
"t_com_cnj_boundwaraxe",
"t_com_cnj_boundwarhammer",
"t_com_cnj_callofthebeasts",
"t_com_cnj_daedrameridianlight",
"t_com_cnj_daedricweapon",
"t_com_cnj_deaddust",
"t_com_cnj_deathhowl",
"t_com_cnj_doomhammer",
"t_com_cnj_experimentfrostatr",
"t_com_cnj_fleshdremora",
"t_com_cnj_foolsgloves",
"t_com_cnj_foundation",
"t_com_cnj_kievierspecternane",
"t_com_cnj_minionofmehrunes",
"t_com_cnj_monstersummoning",
"t_com_cnj_quietundead",
"t_com_cnj_razorsedge",
"t_com_cnj_summonauroran",
"t_com_cnj_summonboneman",
"t_com_cnj_summondevourer",
"t_com_cnj_summondremoraarcher",
"t_com_cnj_summondremoracaster",
"t_com_cnj_summonfleshatronach",
"t_com_cnj_summonfrostmonarch",
"t_com_cnj_summonguardian",
"t_com_cnj_summonhellhound",
"t_com_cnj_summonherne",
"t_com_cnj_summonironatronach",
"t_com_cnj_summonlesserclannfear",
"t_com_cnj_summonmistman",
"t_com_cnj_summonmorphoid",
"t_com_cnj_summonogrim",
"t_com_cnj_summonseducer",
"t_com_cnj_summonseducerdark",
"t_com_cnj_summonskeletonchamp",
"t_com_cnj_summonspiderdaedra",
"t_com_cnj_summonstormmonarch",
"t_com_cnj_summonvermai",
"t_com_cnj_summonwraithman",
"t_com_con_peryitonspelleast",
"t_com_con_peryitonspellfringes",
"t_com_con_peryitonspellnorth",
"t_com_con_peryitonspellsouth",
"t_com_con_peryitonspellwest",
"t_com_des_azrawrath",
"t_com_des_balefulwoe",
"t_com_des_beakslighting",
"t_com_des_blaze",
"t_com_des_blisteringfire",
"t_com_des_bonefrost",
"t_com_des_bonesear",
"t_com_des_broadforce",
"t_com_des_burningblows",
"t_com_des_causedamage",
"t_com_des_causedisease",
"t_com_des_chasteringfire",
"t_com_des_cleansingfire",
"t_com_des_continuousdamage",
"t_com_des_corruption",
"t_com_des_damage",
"t_com_des_despair",
"t_com_des_disease",
"t_com_des_drain",
"t_com_des_duck",
"t_com_des_excerscence",
"t_com_des_explosion",
"t_com_des_fatherblight",
"t_com_des_fearoftheflame",
"t_com_des_finspite",
"t_com_des_firedart",
"t_com_des_flakessnow",
"t_com_des_fleshfire",
"t_com_des_fleshrime",
"t_com_des_fracturearmor",
"t_com_des_grandforce",
"t_com_des_handfire",
"t_com_des_harkenor",
"t_com_des_harmarmor",
"t_com_des_icebolt",
"t_com_des_icestorm",
"t_com_des_ignitefoe",
"t_com_des_journeyman",
"t_com_des_kingorgcoffer_vanish",
"t_com_des_lightning",
"t_com_des_lotfate",
"t_com_des_magefire",
"t_com_des_magepin",
"t_com_des_magewrack",
"t_com_des_maidrime",
"t_com_des_mysteries",
"t_com_des_pinprick",
"t_com_des_rageofmagnus",
"t_com_des_revelations",
"t_com_des_siftingstain",
"t_com_des_skinchill",
"t_com_des_slow",
"t_com_des_sparkling",
"t_com_des_subtleforce",
"t_com_des_sweetpin",
"t_com_des_terrorbaluokmir",
"t_com_des_tinct",
"t_com_des_uni_daedricseptis",
"t_com_des_vampirestouch",
"t_com_des_webmaster",
"t_com_des_weirdbane",
"t_com_des_wildfire",
"t_com_des_windsstorm",
"t_com_des_witchscurse",
"t_com_des_wizardbrand",
"t_com_des_writhering",
"t_com_des_wyvernsting",
"t_com_ilu_alluringspeech",
"t_com_ilu_azuraslight",
"t_com_ilu_blindfold",
"t_com_ilu_confusion",
"t_com_ilu_daedrahunterseye",
"t_com_ilu_distractcreature",
"t_com_ilu_distracthumanoid",
"t_com_ilu_etherealness",
"t_com_ilu_falensjustice",
"t_com_ilu_fear",
"t_com_ilu_livingstatue",
"t_com_ilu_monstrousvision",
"t_com_ilu_onthemove",
"t_com_ilu_orcseye",
"t_com_ilu_paralysis",
"t_com_ilu_serenenature",
"t_com_ilu_shamefulcowardice",
"t_com_ilu_skein",
"t_com_ilu_smokeandmirrors",
"t_com_ilu_steadfast",
"t_com_ilu_tame",
"t_com_ilu_voices",
"t_com_ilu_wanderlight",
"t_com_mys_absorb",
"t_com_mys_anchor",
"t_com_mys_banishdaedra",
"t_com_mys_blink",
"t_com_mys_boneresolve",
"t_com_mys_brightwell",
"t_com_mys_daedrabloodlust",
"t_com_mys_daedrabloodstorm",
"t_com_mys_detectenemy",
"t_com_mys_detecthumanoid",
"t_com_mys_detectinvisibility",
"t_com_mys_dispelmagic",
"t_com_mys_distortedreflect",
"t_com_mys_fuchonkeyfinder",
"t_com_mys_insight",
"t_com_mys_lifesteal",
"t_com_mys_necromancerssoultrap",
"t_com_mys_nullmagicka",
"t_com_mys_reflectdamage",
"t_com_mys_removeenchantment",
"t_com_mys_reunrefine",
"t_com_mys_spellabsorption",
"t_com_mys_spellreflection",
"t_com_mys_spellresistance",
"t_com_mys_spellshifting",
"t_com_mys_tag",
"t_com_mys_teleport",
"t_com_mys_tides",
"t_com_mys_uni_passwall",
"t_com_mys_uni_pitfalls",
"t_com_mys_vampire",
"t_com_mys_vampiricdrain",
"t_com_mys_vampirictouch",
"t_com_res_armorresartus",
"t_com_res_azrasustenance",
"t_com_res_balynabalm",
"t_com_res_bloodbeat",
"t_com_res_bodymind",
"t_com_res_curedisease",
"t_com_res_curehealth",
"t_com_res_deftsecurity",
"t_com_res_dragoncombat",
"t_com_res_energize",
"t_com_res_ewerpurity",
"t_com_res_feebleblade",
"t_com_res_fieryward",
"t_com_res_frenzy",
"t_com_res_frostyward",
"t_com_res_grandwarding",
"t_com_res_haste",
"t_com_res_heal",
"t_com_res_healtrue",
"t_com_res_healwound",
"t_com_res_impossibleeffort",
"t_com_res_lightheal",
"t_com_res_manaward",
"t_com_res_poisonward",
"t_com_res_pureblood",
"t_com_res_purify",
"t_com_res_raiseattribute",
"t_com_res_raisestrength",
"t_com_res_rejuvenator",
"t_com_res_resistance",
"t_com_res_roothero",
"t_com_res_seedhealing",
"t_com_res_shockward",
"t_com_res_stillimage",
"t_com_res_swiftness",
"t_com_res_tongues",
"t_com_res_unearnedgenius",
"t_com_res_varla",
"t_com_res_weaponresartus",
"t_com_res_wholeflesh",
"t_com_spectralarmy",
"t_com_trp_acid",
"t_com_trp_acidmaster",
"t_com_trp_burglarsbane",
"t_com_trp_burnout",
"t_com_trp_dmgagl",
"t_com_trp_dmgend",
"t_com_trp_dmgint",
"t_com_trp_dmglck",
"t_com_trp_dmgprs",
"t_com_trp_dmgspd",
"t_com_trp_dmgstr",
"t_com_trp_dmgwil",
"t_com_trp_firegmaster",
"t_com_trp_flash",
"t_com_trp_frostgmaster",
"t_com_trp_hailstone",
"t_com_trp_poisongmaster",
"t_com_trp_shockgmaster",
"t_com_trp_shockmild",
"t_com_trp_toxicshock",
"t_cr_ab_auroranlight",
"t_cr_ab_dridreamephalasblessing",
"t_cr_ab_goblinblindness",
"t_cr_ab_icewraithfireweakness",
"t_cr_ab_icewraithweaponresist",
"t_cr_ab_lichgreater",
"t_cr_ab_regeneratemagickaquick",
"t_cr_ab_regeneratemagickaslow",
"t_cr_ab_skyrender",
"t_cr_ab_thresher",
"t_cr_ab_tinyplesioluck",
"t_cr_alt_auroranshield",
"t_cr_alt_aylsorcklightshield",
"t_cr_alt_draugrlightnshield",
"t_cr_cnj_aylsorcksummon1",
"t_cr_cnj_aylsorcksummon2",
"t_cr_cnj_aylsorcksummon3",
"t_cr_cnj_sloadsummonskeleton",
"t_cr_des_aspisvenom",
"t_cr_des_auroranshock",
"t_cr_des_aylsorckdrainattr",
"t_cr_des_aylsorckdrainmagicka",
"t_cr_des_aylsorckshock",
"t_cr_des_aylsorcksparks",
"t_cr_des_danswyrmvenom",
"t_cr_des_direkagoutitusks",
"t_cr_des_dridreapoison",
"t_cr_des_dridreawebbloom",
"t_cr_des_frostmonarchwrath",
"t_cr_des_ghostcurse",
"t_cr_des_hagravencurse",
"t_cr_des_hagravenparalyze",
"t_cr_des_hagravenweapbane",
"t_cr_des_parastylusvenom",
"t_cr_des_redeemedktouch",
"t_cr_des_skeletonmagebane",
"t_cr_des_skeletonthiefbane",
"t_cr_des_skeletonwarriorbane",
"t_cr_des_skyrenderpoison",
"t_cr_des_skyrenderqueenpoison",
"t_cr_des_spidervenom1",
"t_cr_des_spidervenom2",
"t_cr_des_spidervenom3",
"t_cr_des_stormmonarchwrath",
"t_cr_des_welkyndsplightn1",
"t_cr_des_welkyndsplightn2",
"t_cr_ilu_goblinevileye",
"t_cr_ilu_goblinshamanscurse",
"t_cr_ilu_redeemedkparalyze",
"t_cr_la_juvrivstrider_ability",
"t_cr_mys_goblinfeeding",
"t_cr_mys_koglingblooddrain",
"t_cr_mys_lichgreatdreadcurse",
"t_cr_mys_welkyndspreflect",
"t_cr_res_redeemedkregen",
"t_cr_res_sloadattackspell",
"t_cr_res_welkyndspheal",
"t_curse_freeze",
"t_cyr_ayl_lightofauriel",
"t_cyr_cnj_summonbarrowguard",
"t_cyr_cnj_summonghost",
"t_cyr_cnj_summonminobarrowguard",
"t_cyr_cnj_summonwraith",
"t_dae_ab_lillandril",
"t_dae_alt_uni_wabbajacktrans",
"t_dae_cnj_uni_corruptionsummon",
"t_dae_seducer_chameleon",
"t_de_ab_facelesshelm",
"t_de_cnj_bonewalkerritual",
"t_de_cnj_summonbonelord",
"t_de_cnj_summongreaterbonelord",
"t_de_cnj_summonproxyhound",
"t_de_cnj_uni_boundhammerresdayn",
"t_de_cnj_uni_boundrazororesdayn",
"t_de_des_necromordfire",
"t_de_des_weaknesscorprus",
"t_de_mys_templesong",
"t_de_res_akatoshblessing",
"t_de_res_almalexiafury",
"t_de_res_almalexiasmercy",
"t_de_res_arkayblessing",
"t_de_res_blessingwdiv",
"t_de_res_dibellablessing",
"t_de_res_generosity",
"t_de_res_julianosblessing",
"t_de_res_kynarethblessing",
"t_de_res_marablessing",
"t_de_res_mercyunexpected",
"t_de_res_ordinatorblessing",
"t_de_res_restoreconstitution",
"t_de_res_restorefinesse",
"t_de_res_restorefortitude",
"t_de_res_restoresorcery",
"t_de_res_sothasilsmastery",
"t_de_res_stendarrblessing",
"t_de_res_talosblessing",
"t_de_res_zenitharblessing",
"t_dis_astralvapors",
"t_dis_bloodlung",
"t_dis_bloodrot",
"t_dis_bluepox",
"t_dis_bonebreakfever",
"t_dis_brainfever",
"t_dis_brainrot",
"t_dis_calironscurse",
"t_dis_chrondiasis",
"t_dis_feeblelimb",
"t_dis_frostbite",
"t_dis_palefever",
"t_dis_reddeath",
"t_dis_redrage",
"t_dis_scarletfever",
"t_dis_shakes",
"t_dis_shipfever",
"t_dis_stomachrot",
"t_dis_swamprot",
"t_dis_ticklebritch",
"t_dis_tunnelcough",
"t_dis_wastingconsumption",
"t_dis_wereboarblood",
"t_dis_werewolfblood",
"t_dis_whithereye",
"t_dis_witbane",
"t_dis_witchespox",
"t_dis_witlesspox",
"t_dis_wizardfever",
"t_dis_woundrot",
"t_dis_yellowrot",
"t_dua_ab_weaknesstoshock",
"t_dua_alt_tavasgale",
"t_dua_pow_cardinalaptitude",
"t_dwe_cnj_uni_summondwespectre",
"t_dwe_cnj_uni_summonspidercent",
"t_dwe_cnj_uni_summonsteamcent",
"t_gia_ab_atmoranblood",
"t_gia_ab_colossalframe",
"t_gia_ab_skinofstone",
"t_img_ab_soulbranch",
"t_img_pow_prophetsdenial",
"t_imp_alt_ulmsjuicedawsfeather",
"t_imp_alt_vivecskiss",
"t_imp_des_ordealstolms",
"t_imp_des_vivecswrath",
"t_imp_ilu_sothasgrace",
"t_imp_mys_almalexiasgrace",
"t_imp_mys_vivecsfeast",
"t_imp_pow_doombappr",
"t_imp_pow_doombatro",
"t_imp_pow_doomblady",
"t_imp_pow_doomblord",
"t_imp_pow_doomblover",
"t_imp_pow_doombmage",
"t_imp_pow_doombritual",
"t_imp_pow_doombritual2",
"t_imp_pow_doombserp",
"t_imp_pow_doombshadow",
"t_imp_pow_doombsteed",
"t_imp_pow_doombthief",
"t_imp_pow_doombtower",
"t_imp_pow_doombtower2",
"t_imp_pow_doombwarrior",
"t_imp_pow_doomhaeth",
"t_imp_pow_doomhdrag",
"t_imp_pow_doomhjode",
"t_imp_pow_doomhjone",
"t_imp_pow_doomhmagnus",
"t_imp_pow_doomhnirn",
"t_imp_pow_doomhshez",
"t_imp_pow_doomhsithis",
"t_imp_res_blessingalessia",
"t_imp_res_blessingclavicus",
"t_imp_res_blessingcuhlecain",
"t_imp_res_blessingincarnadine",
"t_imp_res_blessingmorihaus",
"t_imp_res_blessingpelinal",
"t_imp_res_blessingreman",
"t_imp_res_blessingstart",
"t_imp_res_blessingstcolo",
"t_imp_res_blessingstemp",
"t_imp_res_blessingstfortune",
"t_imp_res_blessingsthealer",
"t_imp_res_blessingsthearth",
"t_imp_res_blessingstino",
"t_imp_res_blessingstlaw",
"t_imp_res_blessingstproph",
"t_imp_res_blessingstteach",
"t_imp_res_blessingsttrade",
"t_imp_res_blessingstwar",
"t_imp_res_blessingstwork",
"t_imp_res_blessingstatakatosh",
"t_imp_res_blessingstatarkay",
"t_imp_res_blessingstatdibella",
"t_imp_res_blessingstatjulianos",
"t_imp_res_blessingstatkynareth",
"t_imp_res_blessingstatmara",
"t_imp_res_blessingstatstendarr",
"t_imp_res_blessingstattalos",
"t_imp_res_blessingstatzenithar",
"t_imp_res_blessingwaka",
"t_imp_res_blessingwark",
"t_imp_res_blessingwdib",
"t_imp_res_blessingwjul",
"t_imp_res_blessingwkyn",
"t_imp_res_blessingwmara",
"t_imp_res_blessingwste",
"t_imp_res_blessingwtib",
"t_imp_res_blessingwzen",
"t_imp_res_reststmerris",
"t_imp_res_rilmscure",
"t_imp_res_serynsblessing",
"t_imp_res_serynsgift",
"t_imp_res_sothasmirror",
"t_imp_res_velothsbenison",
"t_imp_res_velothsgift",
"t_imp_res_velothsgrace",
"t_kc_ab_vitality",
"t_kcr_ab_blood",
"t_kdr_alt_treedweller",
"t_kdr_pow_shadowpaw",
"t_kep_ab_weaknesstoblight",
"t_kep_pow_spritofquey",
"t_kep_pow_unbreakable",
"t_ko_ab_resistdisease_25",
"t_kor_ab_resistparalysis_25",
"t_ks_pow_grace",
"t_mao_ab_serpentblessing",
"t_mao_ab_veilblessing",
"t_mao_pow_mistshroud",
"t_mo_ab_bloodofmalahk",
"t_mo_pow_berserk",
"t_mw_des_poisonbloom",
"t_nor_alt_harkinsgills",
"t_nor_alt_tsunsward",
"t_nor_alt_ulmsjuicedawsfeather",
"t_nor_alt_vivecskiss",
"t_nor_alt_windofkyne",
"t_nor_cnj_summondraugr",
"t_nor_cnj_summonicewraith",
"t_nor_cnj_summonspriggan",
"t_nor_des_mountainwind",
"t_nor_des_ordealstolms",
"t_nor_des_starfrost",
"t_nor_des_vivecswrath",
"t_nor_ilu_raveneye",
"t_nor_ilu_raveneyegreater",
"t_nor_ilu_sothasgrace",
"t_nor_mys_almalexiasgrace",
"t_nor_mys_extendedarm",
"t_nor_mys_jogvirssoultheft",
"t_nor_mys_jogvirsswordhand",
"t_nor_mys_kynesintervention",
"t_nor_mys_sothasmirror",
"t_nor_mys_vivecsfeast",
"t_nor_res_blessingdibella",
"t_nor_res_blessingkyne",
"t_nor_res_blessingmara",
"t_nor_res_eagleeye",
"t_nor_res_reststmerris",
"t_nor_res_rilmscure",
"t_nor_res_serynsblessing",
"t_nor_res_serynsgift",
"t_nor_res_treefellersrage",
"t_nor_res_velothsbenison",
"t_nor_res_velothsgift",
"t_nor_res_velothsgrace",
"t_nor_res_whisperhermamora",
"t_nor_res_winterymantle",
"t_ogr_ab_drainint",
"t_ogr_ab_resistwep40",
"t_ogr_ab_strength",
"t_ogr_pow_ethereal",
"t_ogr_pow_roar",
"t_orc_res_spiritwarrior",
"t_rea_alt_ulmsjuicedawsfeather",
"t_rea_alt_vivecskiss",
"t_rea_des_cuhlecaincurse",
"t_rea_des_extinguisher",
"t_rea_des_ironeater",
"t_rea_des_legbreaker",
"t_rea_des_meatrot",
"t_rea_des_mindrot",
"t_rea_des_ordealstolms",
"t_rea_des_shadowrust",
"t_rea_des_steeleater",
"t_rea_des_vivecswrath",
"t_rea_ilu_sothasgrace",
"t_rea_mys_almalexiasgrace",
"t_rea_mys_marastouch",
"t_rea_mys_sothasmirror",
"t_rea_mys_soulwither",
"t_rea_mys_soultheft",
"t_rea_mys_vivecsfeast",
"t_rea_pow_bloodchant",
"t_rea_pow_witcheye",
"t_rea_res_reststmerris",
"t_rea_res_rilmscure",
"t_rea_res_serynsblessing",
"t_rea_res_serynsgift",
"t_rea_res_velothsbenison",
"t_rea_res_velothsgift",
"t_rea_res_velothsgrace",
"t_rga_alt_ulmsjuicedawsfeather",
"t_rga_alt_vivecskiss",
"t_rga_des_ordealstolms",
"t_rga_des_vivecswrath",
"t_rga_ilu_sothasgrace",
"t_rga_mys_almalexiasgrace",
"t_rga_mys_sothasmirror",
"t_rga_mys_vivecsfeast",
"t_rga_res_reststmerris",
"t_rga_res_rilmscure",
"t_rga_res_serynsblessing",
"t_rga_res_serynsgift",
"t_rga_res_velothsbenison",
"t_rga_res_velothsgift",
"t_rga_res_velothsgrace",
"t_riv_pow_mirror",
"t_test_acrobaticspackage",
"t_test_brightlight",
"t_test_flight",
"t_test_regeneration",
"t_test_waterwalking",
"t_tsa_ab_tsaescires",
"t_tsa_ilu_tsaescikiai",
"t_tsa_mys_tsaescibite",
"t_uni_sainttelynblessing",
"t_vamp_ab_baluath",
"t_vamp_ab_baluath_ash",
"t_vamp_ab_baluath_sundmg",
"t_vamp_ab_disguise",
"t_vamp_ab_khulari",
"t_vamp_ab_order",
"t_vamp_ab_order_disguise",
"t_vamp_ab_orlukh",
"t_vamp_dis_baluath",
"t_vamp_dis_khulari",
"t_vamp_dis_order",
"t_vamp_dis_orlukh",
"t_vamp_sp_baluath_ash",
"t_vamp_sp_order_disguise",
"t_were_ab_boareye",
"t_were_ab_boarregen",
"t_were_ab_boarresist",
"t_were_ab_boarstrength",
"t_yne_abi_sneak",
"t_yne_pow_dragon",
"ab_ab_enchantbonus",
"ab_ab_enchantbonusogrim",
"ab_ab_enchantbonusscamp",
"ab_ab_spell absorb20",
"ab_ab_weaknessfrost50",
"ab_dis_fleas",
"ab_sp_azurablessing",
"ab_sp_boethiahblessing",
"ab_sp_mephalablessing",
"ab_sp_poisonbite_fau",
"ab_sp_thunderquake_dae",
"ab_sp_webparalyze",
"ab_trap_dwrvproxmine",
"ab_trap_kwamaacid",
"ab_trap_lightningstrike",
"ab_trap_runestone_01",
"ab_trap_runestone_02",
"ab_trap_runestone_03",
"tr_ad_aldrane's ward",
"tr_fm_ab_dozhir",
"tr_fm_ab_grurn",
"tr_fm_ab_weaknessfire25",
"tr_fm_sp_crackle",
"tr_fm_sp_fireshield",
"tr_fm_sp_grurnbuff",
"tr_fm_sp_heal",
"tr_fm_sp_holyfire",
"tr_fm_sp_lightningcrown",
"tr_fm_sp_lightningcrown2",
"tr_fm_sp_lightningcrown3",
"tr_fm_sp_luckleach",
"tr_fm_sp_summonhorde",
"tr_follow_lv_fake",
"tr_follow_lv_real",
"tr_follow_ww_fake",
"tr_follow_ww_real",
"tr_m1_q66_ght_summon",
"tr_mg_lichgreater_ab",
"tr_medensreech",
"tr_medensspeed",
"tr_q_curse",
"tr_rothroryn_monastery_almspell",
"tr_weebem_naez_spell",
"tr_blindcurse",
"tr_m0_q_ic_fortifyattributes",
"tr_m1_backstab",
"tr_m1_delvamdest",
"tr_m1_dral_attack",
"tr_m1_dral_attacktouch",
"tr_m1_dral_aura",
"tr_m1_dral_bound",
"tr_m1_dral_chameleon",
"tr_m1_dral_shield",
"tr_m1_dral_specialmix",
"tr_m1_draythen_damage",
"tr_m1_eldale_attack",
"tr_m1_eldale_attacktouch",
"tr_m1_eldale_shield",
"tr_m1_enaeroth_bolt",
"tr_m1_fwmg_tathdest",
"tr_m1_fwmg_tathshld",
"tr_m1_faruna_shield",
"tr_m1_faruna_specialmix_sp",
"tr_m1_frostshock",
"tr_m1_ginyan_debuff",
"tr_m1_il_thenimdrain",
"tr_m1_liretha_damage",
"tr_m1_mithras_bound",
"tr_m1_ptfly",
"tr_m1_q50_g03_angondef",
"tr_m1_q50_g03_angonfire",
"tr_m1_q50_g03_angonweak",
"tr_m1_q50_g03_rewspel",
"tr_m1_q50_g03_rewspela",
"tr_m1_q50_g05paral_curse",
"tr_m1_q_curse_end",
"tr_m1_rathra_attack",
"tr_m1_rathra_attacktouch",
"tr_m1_rathra_fatigue",
"tr_m1_selurasummon",
"tr_m1_shalathbuff",
"tr_m1_shalathdestr1",
"tr_m1_shalathdestr2",
"tr_m1_summoneffect",
"tr_m1_tedryn_debuff",
"tr_m1_telwarlock",
"tr_m1_telvanni_levitate",
"tr_m1_voun_ench_buff",
"tr_m1_cr_i2_drekbuff",
"tr_m1_cr_i2_drekdest",
"tr_m1_cr_i2_dreksumm",
"tr_m1_good_feather",
"tr_m1_lud_paralyse",
"tr_m1_q_fw_mg02_levab",
"tr_m1_q_mg3_levab",
"tr_m1_q_mg4dispel",
"tr_m1_q_rr_5_reward",
"tr_m1_q_ttshrine1_spell",
"tr_m1_q_ttshrine2_spell",
"tr_m1_q_ttshrine3_spell",
"tr_m1_sp_gindaman",
"tr_m1_sp_i2_burden",
"tr_m1_sp_i2_glaivesplode",
"tr_m1_sp_i2_paralysis",
"tr_m1_sp_i2_poison",
"tr_m1_sp_i2_shock",
"tr_m2_445_ayempower",
"tr_m2_445_fx_asv",
"tr_m2_445_sehtpower",
"tr_m2_445_spikepoison",
"tr_m2_445_vehkpower",
"tr_m2_ancasarion_debuff",
"tr_m2_ancasarion_debuff_2",
"tr_m2_ancasarion_debuff_3",
"tr_m2_do_damageluck",
"tr_m2_do_damagestrength",
"tr_m2_ensalda_chill",
"tr_m2_fg_selynspell",
"tr_m2_fg_paralysis",
"tr_m2_fatigueburn",
"tr_m2_immolatingtouch",
"tr_m2_mzankh_elec_ab",
"tr_m2_mzankh_elec_sp",
"tr_m2_va_weebemnaezsundmg",
"tr_m2_vaerin_attack",
"tr_m2_vaerin_blind",
"tr_m2_vaerin_chameleon",
"tr_m2_crushing_burden_cheap",
"tr_m2_kmlz_king_elec",
"tr_m2_q_21_flametrapex",
"tr_m2_q_21_flametrapme",
"tr_m2_q_21_flametrapst",
"tr_m2_q_21_flametrapwe",
"tr_m2_q_22_effects",
"tr_m2_q_29_2_invisible",
"tr_m2_q_29_2_paralyze",
"tr_m2_q_29_4_surolchamp",
"tr_m2_q_38_playertouch",
"tr_m2_q_5_trials_sp",
"tr_m2_q_a8_5_firespell",
"tr_m2_q_a8_5_spell",
"tr_m2_q_nm_wake_suicidespell",
"tr_m2_q_ttshrine1_spell",
"tr_m2_q_ttshrine2_spell",
"tr_m2_q_ttshrine3_spell",
"tr_m2_q_vaerinpunaviteffect",
"tr_m2_shambalu_trap",
"tr_m3-649_akatoshblessing",
"tr_m3-649_arkayblessing",
"tr_m3-649_dibellablessing",
"tr_m3-649_julianosblessing",
"tr_m3-649_kynarethblessing",
"tr_m3-649_marablessing",
"tr_m3-649_stendarrblessing",
"tr_m3-649_talosblessing",
"tr_m3-649_zenitharblessing",
"tr_m3_at_armiger_sp",
"tr_m3_at_calmwaters",
"tr_m3_at_ratfriend_spell",
"tr_m3_bloodstoneblessing",
"tr_m3_brother_aralorspell",
"tr_m3_dilavesa_explosion",
"tr_m3_hh_gm_dispel",
"tr_m3_il_urenim_spell",
"tr_m3_kha_escape_sp",
"tr_m3_kha_methatsheal",
"tr_m3_kha_sy_soulwound1",
"tr_m3_kha_sy_soulwound2",
"tr_m3_kha_sy_soulwound3",
"tr_m3_kha_scamp_fire",
"tr_m3_kha_whisp_fountain_sp",
"tr_m3_la_hengorspell",
"tr_m3_oe_armisticeability",
"tr_m3_oe_armisticefiretrap",
"tr_m3_oe_armisticethiefmark",
"tr_m3_oe_ebontowerforgespell",
"tr_m3_oe_fakeenchant",
"tr_m3_oe_fakesummon",
"tr_m3_oe_ghostglow",
"tr_m3_oe_hhontratpoison",
"tr_m3_oe_icarianflight",
"tr_m3_oe_mg_debilitate",
"tr_m3_oe_songfatigue",
"tr_m3_oe_songhealth",
"tr_m3_oe_songmagicka",
"tr_m3_oe_vaultshockspell",
"tr_m3_oe_beru_spell",
"tr_m3_oe_haybale_spell",
"tr_m3_rd_daebarrier_par",
"tr_m3_reynard abilities",
"tr_m3_sabine abilities",
"tr_m3_sabine unlife",
"tr_m3_tt_cohealgreat",
"tr_m3_tt_dis_regen",
"tr_m3_tt_fs_backfire",
"tr_m3_tt_fs_boon",
"tr_m3_tt_fs_magic",
"tr_m3_tt_fs_nerf",
"tr_m3_yathosildebuff",
"tr_m3_yathosilpoison",
"tr_m3_bartdrain",
"tr_m3_invisibility_touch",
"tr_m3_paruddma_absorb_spell",
"tr_m3_paruddma_drown_spell",
"tr_m3_paruddma_flesh_spell",
"tr_m3_q_3_burglar_sp",
"tr_m3_q_at_mg01_summon",
"tr_m3_q_kha_thul_power",
"tr_m3_q_oe_mg_effspell",
"tr_m3_q_sy_fakespell",
"tr_m3_q_sy_blessing",
"tr_m3_q_chesteffect",
"tr_m3_q_invisiblesadryn",
"tr_m3_sephen_guardian_spell",
"tr_m3_summon zymel kaaz",
"tr_m3_trap_frostpara",
"tr_m3_unending_blind",
"tr_m3_unending_burden",
"tr_m3_unending_drainhp",
"tr_m3_unending_poison",
"tr_m3_unending_silence",
"tr_m4_ando_increaseprice",
"tr_m4_ando_mg_8a_rewardspell",
"tr_m4_ando_mg_lightningburst",
"tr_m4_ando_reduceprice",
"tr_m4_ando_songblade",
"tr_m4_ando_songblunt",
"tr_m4_andoth_andasspell01",
"tr_m4_bal_alvayahtrap",
"tr_m4_bal_amuletpower1",
"tr_m4_bal_amuletpower2",
"tr_m4_bal_amuletpower3",
"tr_m4_bal_bloodlusttrap",
"tr_m4_bal_levitateother",
"tr_m4_bal_vampseduction",
"tr_m4_bal_vampterror",
"tr_m4_baurel_sanctuary",
"tr_m4_belbetublessing",
"tr_m4_belbetukillingshock",
"tr_m4_delvenubavani_d",
"tr_m4_emmurbalpitughost_en",
"tr_m4_fg_ushudimmusnake",
"tr_m4_hautharmo unlife",
"tr_m4_kaariheal",
"tr_m4_lisklisskurabilities",
"tr_m4_lodyna_fire",
"tr_m4_naarie_absorb",
"tr_m4_naarie_poison",
"tr_m4_naarie_summon",
"tr_m4_nakedwitchparalyzation",
"tr_m4_ostraladest",
"tr_m4_rr_battlebodrumblessing",
"tr_m4_rr_savrethiwinespell",
"tr_m4_rr_saylenusspell",
"tr_m4_rr_storigglow",
"tr_m4_tg_andosneakspell",
"tr_m4_tj_ancg_court1_sp",
"tr_m4_tj_ancg_court2_sp",
"tr_m4_tj_ancg_court3_sp",
"tr_m4_tj_ancg_court4_sp",
"tr_m4_tj_ancg_court5_sp",
"tr_m4_tj_ancg_court6_sp",
"tr_m4_tj_court_drain",
"tr_m4_tt_blessspeechcraft",
"tr_m4_tt_orcvivecability",
"tr_m4_tt_shrineolmsrefl_sp",
"tr_m4_tt_shrineolmsrest_sp",
"tr_m4_tt_stfelmsconviction",
"tr_m4_tur_julan_sanctum_trap",
"tr_m4_va_ashsleep_sundmg",
"tr_m4_visthinahaste",
"tr_m4_visthinaleech",
"tr_m4_visthinasummon",
"tr_m4_willtogoon_curse",
"tr_m4_aum_golgafrost",
"tr_m4_aum_krogdest",
"tr_m4_aum_krogskel",
"tr_m4_bonewlk_uni_spell",
"tr_m4_caeringil_skeletons",
"tr_m4_empowered_will",
"tr_m4_ilvaalmu_abi",
"tr_m4_ilvaalmu_icebreath",
"tr_m4_immetarca_boots_fail",
"tr_m4_immetarca_walks",
"tr_m4_lightinvis",
"tr_m4_menaan_int8_shock",
"tr_m4_pooreyesight",
"tr_m4_q_ag_summon",
"tr_m4_q_fakesound",
"tr_m4_q_nirnboundspell",
"tr_m4_q_tmm_bolsdisease",
"tr_m4_q_trollfregen",
"tr_m4_q_vf_spell",
"tr_m4_q_mabrigash_ch",
"tr_m4_q_mm_mabrigashcurse",
"tr_m4_q_mm_paralysis",
"tr_m4_q_mm_selfcurse",
"tr_m4_varoswrath",
"tr_m4_vesidur_breath",
"tr_m4_wickeddrainblood",
"tr_m7_ai_savi_swim",
"tr_m7_aldkhanshrine_blessing",
"tr_m7_alvon_lightingshieldconst",
"tr_m7_alvonsbarrier",
"tr_m7_alvonsnova",
"tr_m7_alvonsrangedshock",
"tr_m7_alvonssweakness",
"tr_m7_alvonsshockbloom",
"tr_m7_ashir_ahat_trap",
"tr_m7_baezablind",
"tr_m7_baezafear",
"tr_m7_baezafire",
"tr_m7_baezaparalyze",
"tr_m7_baezapurify",
"tr_m7_cealuniafire",
"tr_m7_cealuniafrost",
"tr_m7_cleliadamage",
"tr_m7_cleliaparalyze",
"tr_m7_corridusleech",
"tr_m7_corridusscour",
"tr_m7_cruliusdamage",
"tr_m7_cruliusdebuff",
"tr_m7_cruliussummon",
"tr_m7_da_nam_curse",
"tr_m7_damagemagickatrap",
"tr_m7_dro'jaaban_sp",
"tr_m7_eec_guarfever",
"tr_m7_fainurin_fireball",
"tr_m7_fainurin_frostball",
"tr_m7_freedommovement",
"tr_m7_gahtha-lal_vanish",
"tr_m7_gallus_blind",
"tr_m7_gallus_burden",
"tr_m7_hh_alvynu_4_luck",
"tr_m7_hh_alvynu_7_explosion",
"tr_m7_hlevisbolt",
"tr_m7_hleviskill",
"tr_m7_hlevisknockdown",
"tr_m7_hlevisprotect",
"tr_m7_imeyracurse_1",
"tr_m7_imeyracurse_2",
"tr_m7_imeyracurse_3",
"tr_m7_indrasifire",
"tr_m7_indrasifrost",
"tr_m7_indrasishock",
"tr_m7_intercession",
"tr_m7_jns_poisongas_sp",
"tr_m7_jns_thebossblind",
"tr_m7_jns_thebossfly",
"tr_m7_jns_thebosshunger",
"tr_m7_jns_thebosspoison",
"tr_m7_jns_thebossscamp",
"tr_m7_longjumpspell",
"tr_m7_longjumptrack",
"tr_m7_mg_arch03_spell",
"tr_m7_mt_mephalablessing",
"tr_m7_mt_mephalablessing2",
"tr_m7_mt_nightmothercurse",
"tr_m7_mt_nightmotherkiss",
"tr_m7_mt_nightmotherveil",
"tr_m7_marlenaantimage",
"tr_m7_marlenadamage",
"tr_m7_meer-ei_discount",
"tr_m7_mervisllarelbound",
"tr_m7_myron_discount",
"tr_m7_nroomsshrine_blessing",
"tr_m7_narsis_songcanah",
"tr_m7_narsis_songwalk",
"tr_m7_ns_antigonefrostfist",
"tr_m7_ns_antigonefrostfist_aoe",
"tr_m7_ns_antigoneregen",
"tr_m7_ns_arena_13_heal",
"tr_m7_ns_ethalaspell",
"tr_m7_ns_fg_5_skqupoison",
"tr_m7_ns_mg_alt_jump",
"tr_m7_ns_mg_arch02_spell01",
"tr_m7_ns_olms_gavel",
"tr_m7_ns_ragebuff",
"tr_m7_ns_stagefright_rewardab",
"tr_m7_ns_tg_door02_sp",
"tr_m7_ns_q_dorlenesummon",
"tr_m7_ns_q_faengornabsorb",
"tr_m7_oth_bugtest2_spell",
"tr_m7_oth_mg_3_callaid",
"tr_m7_othm_songsendel",
"tr_m7_othm_songworkers",
"tr_m7_othm_songzalabelk",
"tr_m7_othrano_staff_satarat_spl",
"tr_m7_pedestal_muatra_bless",
"tr_m7_philaminusdamage",
"tr_m7_philaminusslow",
"tr_m7_philosophercurse_sp",
"tr_m7_prestidigitation",
"tr_m7_qorinue-najan_buff",
"tr_m7_razarraspell",
"tr_m7_renixiaatronachs",
"tr_m7_renixiaclannfears",
"tr_m7_renixiascamps",
"tr_m7_renixiasummonspell",
"tr_m7_rescueblessing",
"tr_m7_rirayneaturn",
"tr_m7_secfamvaultbuff",
"tr_m7_shrine_conviction_bless",
"tr_m7_sigisound",
"tr_m7_sigillahshock",
"tr_m7_simpleflight",
"tr_m7_springheel_acro",
"tr_m7_springheel_attack",
"tr_m7_springheel_refresh",
"tr_m7_tt_shrineseryndevotion",
"tr_m7_tv10_tomb_01_canespell",
"tr_m7_tv4_mhas_heal",
"tr_m7_telorascurse",
"tr_m7_thirilbard",
"tr_m7_ussiranbonelordbolt",
"tr_m7_ussiranbonelordbolt2",
"tr_m7_ussiranbonelordshield",
"tr_m7_vandir_belchill",
"tr_m7_vanrythdamage",
"tr_m7_varla_malator_ab",
"tr_m7_veldynheal",
"tr_m7_vodrynpoison",
"tr_m7_burdenofveloth_sp",
"tr_m7_devourofveloth_sp",
"tr_m7_prisonofveloth_sp",
"tr_m7_q_arnielopenspell",
"tr_m7_q_hr_aldiuval_sujamma",
"tr_m7_q_ns_ic1_blessingzen",
"tr_m7_q_ns_ic3_badluck",
"tr_m7_q_ns_ic8_finalesfx",
"tr_m7_q_palebitereffect",
"tr_m7_q_palebite",
"tr_m7_q_renixiasummoneffect",
"tr_orlukh_power",
"tr_q_mightofvaros",
"tr_m3_akuband_bolt",
"tr_m3_akuband_bolt_1",
"tr_m3_akuband_bolt_2",
"tr_m3_akuband_bolt_3",
"tr_m3_akuband_heal",
"tr_m3_akuband_repair",
"tr_m3_akuband_shield",
"tr_m7_bridgetrollregen",
"aa_bs_appr_common",
"aa_bs_appr_know",
"aa_bs_appr_manawell",
"aa_bs_appr_gifted",
"aa_bs_atron_common",
"aa_bs_atron_fire",
"aa_bs_atron_frost",
"aa_bs_atron_shock",
"aa_bs_lady_common",
"aa_bs_lady_lake",
"aa_bs_lady_woods",
"aa_bs_lady_hearth",
"aa_bs_lord_common",
"aa_bs_lord_tyrant",
"aa_bs_lord_benevolent",
"aa_bs_mage_common",
"aa_bs_mage_scholar",
"aa_bs_mage_sage",
"aa_bs_mage_thaumat",
"aa_bs_ritual_common",
"aa_bs_ritual_temple01",
"aa_bs_lord_bureaucrat",
"aa_bs_ritual_temple02",
"aa_bs_ritual_ic01",
"aa_bs_ritual_ic02",
"aa_bs_ritual_ancestor",
"aa_bs_serpent_common",
"aa_bs_serpent_cobra",
"aa_bs_serpent_anaconda",
"aa_bs_serpent_eel",
"aa_bs_shadow_common",
"aa_bs_shadow_night",
"aa_bs_shadow_shade",
"aa_bs_shadow_moonlight",
"aa_bs_steed_common",
"aa_bs_steed_stallion",
"aa_bs_steed_burden",
"aa_bs_steed_war",
"aa_bs_thief_common",
"aa_bs_thief_nimble",
"aa_bs_thief_lucky",
"aa_bs_thief_cunning",
"aa_bs_tower_common",
"aa_bs_tower_bastion",
"aa_bs_tower_prison01",
"aa_bs_tower_prison02",
"aa_bs_tower_lookout",
"aa_bs_warrior_common",
"aa_bs_warrior_iron",
"aa_bs_warrior_infantry",
"aa_bs_warrior_skirmisher",
"aa_bs_lover_common",
"aa_bs_lover_boon",
"aa_bs_lover_wrath",
"aa_bs_lover_secret",
"aa_bs_steed_courier01",
"aa_bs_steed_courier02",
"aa_bs_ritual_dae",
"aa_bs_tower_frostfall",
"aa_bs_warrior_lastseed",
"aa_bs_thief_eveningstar",
"aa_bs_steed_midyear",
"aa_bs_shadow_secondseed",
"aa_bs_serpent_xxx",
"aa_bs_ritual_morningstar",
"aa_bs_mage_rainshand",
"aa_bs_lover_sunsdawn",
"aa_bs_lord_firstseed",
"aa_bs_lady_hearthfire",
"aa_bs_atron_sunsdusk",
"aa_bs_appr_sunsheight",
"sign_atronach_mas_ability",
"sign_lord_sec_ability",
"sign_lover_mas_ability_2",
"sign_mage_mas_ability",
"sign_shadow_sec_ability",
"sign_warrior_mas_ability",
"sign_apprentice_sec_ability_2",
"sign_lady_sec_ability",
"sign_atronach_sec_ability",
"sign_lover_sec_ability",
"sign_mage_sec_ability",
"sign_steed_sec_ability",
"sign_shadow_sec_spell",
"sign_steed_sec_power",
"sign_serpent_war_ability",
"sign_serpent_thief_ability",
"sign_serpent_mage_ability",
"sign_serpent_mage_power",
"sign_serpent_war_power",
"sign_serpent_thief_power",
"sign_serpent_all_spell",
"sign_shadow_sec_power",
"sign_steed_mas_ability",
"sign_thief_mas_ability_2",
"sign_tower_mas_ability",
"sign_warrior_mas_ability_2",
"sign_tower_sec_spell",
"sign_tower_sec_power",
"sign_lady_mas_ability",
"sign_apprentice_mas_ability",
"sign_steed_mas_ability_2",
"sign_ritual_sec_power",
"sign_thief_mas_ability",
"sign_thief_sec_ability",
"sign_lover_mas_ability",
"sign_ritual_mas_ability_2",
"sign_ritual_mas_ability_3",
"sign_ritual_mas_ability",
"sign_tower_mas_ability_2",
"sign_lord_sec_ability_2",
"sign_tower_sec_ability",
"sign_ritual_sec_ability",
"sign_lover_sec_ability_2",
"sign_lover_sec_spell",
"sign_mage_sec_ability_2",
"sign_lord_mas_ability",
"sign_lord_mas_ability_2",
"sign_mage_sec_power",
"sign_thief_sec_spell",
"sign_lover_sec_power",
"sign_lady_sec_power",
"sign_shadow_mas_ability",
"sign_apprentice_sec_ability",
"sign_atronach_sec_spell",
"sign_warrior_sec_ability",
"sign_warrior_sec_ability_2",
"sign_warrior_sec_power",
"sign_thief_sec_power",
"sign_apprentice_sec_power",
"sign_ritual_sec_spell",
"sign_steed_sec_spell",
"sign_steed_sec_spell_2",
"sign_lord_sec_power",
"sign_serpent_mage_ability_2",
"sign_serpent_thief_ability_2",
"sign_serpent_war_ability_2",
"sign_lady_mas_ability_2",
"nv_appmasserpower",
"nv_atronachdispelpower",
"nv_atronachshield",
"nv_atronachshieldsec",
"nv_bloodofthenorth",
"nv_bloodofthenorthspell",
"nv_cobradance",
"nv_elfborn",
"nv_equilibriumspell",
"nv_fay",
"nv_fortifysmith",
"nv_ladygrace",
"nv_ladymirror",
"nv_loverbower",
"nv_loverskiss",
"nv_magestaffbonus",
"nv_magestaffsec",
"nv_moonshadow",
"nv_ritualsecundasummon",
"nv_starcurse",
"nv_thiefsec",
"nv_towerkey",
"nv_towerreflect",
"nv_warriorlaststandsecunda",
"nv_warriorsign",
"nv_wombburn",
"nv_wombburndrainspell",
"nv_wombburnempty",
"nv_womburned",
"nv_hara",
"ke_sr_feral wrath",
"ke_sr_savanah wind",
"ke_sr_tall grass",
"ke_sr_savage focus",
"ke_sr_jaguar mysticism",
"ke_sr_galdes of tenmar",
"ke_sr_breeze of tenmar",
"ke_sr_canopy springs",
"war_eye of fear_ohmes",
"war_eye of night_ohmes",
"war_confusion_ohmes",
"sd_c_sp_bath_bubb",
"sd_c_sp_bath_col",
"sd_c_sp_bath_h",
"sd_c_sp_bath_i",
"sd_c_sp_bath_imp",
"sd_c_sp_bath_lot",
"sd_c_sp_bath_n",
"sd_c_sp_bath_oil",
"sd_c_sp_bath_om",
"sd_c_sp_bath_perf",
"sd_c_sp_bath_r",
"sd_c_sp_bath_salt",
"sd_c_sp_bath_t",
"sd_c_sp_bath_t_bug_musk",
"sd_c_sp_bath_tow",
"sd_c_sp_bath_tt",
"sd_c_sp_dune",
"sd_c_sp_soap_01",
"sd_c_sp_soap_02",
"sd_c_sp_soap_03",
"sd_c_sp_soap_04",
"sd_c_sp_soap_05",
"sd_c_sp_soap_06",
"sd_c_sp_soap_07",
"sd_c_sp_soap_08",
"sd_clean_0",
"sd_clean_1",
"sd_clean_2",
"sd_clean_3",
"sd_clean_4",
"sd_clean_5",
"sd_h_sp_cannibal",
"sd_h_sp_corprus",
"sd_h_sp_fasting",
"sd_h_sp_foodpoisoning",
"sd_h_sp_foodpoisoning_2",
"sd_h_sp_foodpoisoning_3",
"sd_h_sp_foodpoisoning_c",
"sd_h_sp_greenpact",
"sd_h_sp_greenpact_2",
"sd_h_sp_varied",
"sd_hearthfire_1",
"sd_hearthfire_2",
"sd_hearthfire_3",
"sd_hearthfire_4",
"sd_hunger_0",
"sd_hunger_0_c",
"sd_hunger_1",
"sd_hunger_1_c",
"sd_hunger_2",
"sd_hunger_2_c",
"sd_hunger_3",
"sd_hunger_3_2",
"sd_hunger_3_3",
"sd_hunger_3_c",
"sd_hunger_4",
"sd_hunger_4_2",
"sd_hunger_4_3",
"sd_hunger_4_c",
"sd_hunger_5",
"sd_hunger_5_2",
"sd_hunger_5_3",
"sd_hunger_5_c",
"sd_t_sp_insomniac",
"sd_t_sp_morninglark",
"sd_t_sp_nightowl",
"sd_temp_0",
"sd_temp_1",
"sd_temp_2",
"sd_temp_3",
"sd_temp_4",
"sd_temp_5",
"sd_temp_6",
"sd_temp_sp_fire_dmg_1",
"sd_temp_sp_fire_dmg_10",
"sd_temp_sp_fire_dmg_2",
"sd_temp_sp_fire_dmg_3",
"sd_temp_sp_fire_dmg_4",
"sd_temp_sp_fire_dmg_5",
"sd_temp_sp_fire_dmg_6",
"sd_temp_sp_fire_dmg_7",
"sd_temp_sp_fire_dmg_8",
"sd_temp_sp_fire_dmg_9",
"sd_temp_sp_fire_slow",
"sd_temp_sp_frost_dmg_1",
"sd_temp_sp_frost_dmg_10",
"sd_temp_sp_frost_dmg_2",
"sd_temp_sp_frost_dmg_3",
"sd_temp_sp_frost_dmg_4",
"sd_temp_sp_frost_dmg_5",
"sd_temp_sp_frost_dmg_6",
"sd_temp_sp_frost_dmg_7",
"sd_temp_sp_frost_dmg_8",
"sd_temp_sp_frost_dmg_9",
"sd_temp_sp_frost_slow",
"sd_thirst_0",
"sd_thirst_0_c",
"sd_thirst_1",
"sd_thirst_1_c",
"sd_thirst_2",
"sd_thirst_2_c",
"sd_thirst_3",
"sd_thirst_3_2",
"sd_thirst_3_3",
"sd_thirst_3_c",
"sd_thirst_4",
"sd_thirst_4_2",
"sd_thirst_4_3",
"sd_thirst_4_c",
"sd_thirst_5",
"sd_thirst_5_2",
"sd_thirst_5_3",
"sd_thirst_5_c",
"sd_tiredness_0",
"sd_tiredness_0_c",
"sd_tiredness_1",
"sd_tiredness_1_c",
"sd_tiredness_2",
"sd_tiredness_2_c",
"sd_tiredness_3",
"sd_tiredness_3_2",
"sd_tiredness_3_3",
"sd_tiredness_3_c",
"sd_tiredness_4",
"sd_tiredness_4_2",
"sd_tiredness_4_3",
"sd_tiredness_4_c",
"sd_tiredness_5",
"sd_tiredness_5_2",
"sd_tiredness_5_3",
"sd_tiredness_5_c",
"sd_wet_1",
"sd_wet_2",
"sd_wet_3",
"sd_wet_4",
"sd_wet_5",
"startcooking_dummy",
"weakness fire_35",
"evocate",
"disenchanting_expertise_1",
"disenchanting_expertise_128",
"disenchanting_expertise_16",
"disenchanting_expertise_2",
"disenchanting_expertise_32",
"disenchanting_expertise_4",
"disenchanting_expertise_64",
"disenchanting_expertise_8",
"enchantdummy_absorbattribute",
"enchantdummy_absorbfatigue",
"enchantdummy_absorbhealth",
"enchantdummy_absorbmagicka",
"enchantdummy_absorbskill",
"enchantdummy_almsiviintervention",
"enchantdummy_blind",
"enchantdummy_boundbattleaxe",
"enchantdummy_boundboots",
"enchantdummy_boundcuirass",
"enchantdummy_bounddagger",
"enchantdummy_boundgloves",
"enchantdummy_boundhelm",
"enchantdummy_boundlongbow",
"enchantdummy_boundlongsword",
"enchantdummy_boundmace",
"enchantdummy_boundshield",
"enchantdummy_boundspear",
"enchantdummy_burden",
"enchantdummy_calmcreature",
"enchantdummy_calmhumanoid",
"enchantdummy_chameleon",
"enchantdummy_charm",
"enchantdummy_commandcreature",
"enchantdummy_commandhumanoid",
"enchantdummy_cureblightdisease",
"enchantdummy_curecommondisease",
"enchantdummy_curecorprus",
"enchantdummy_cureparalyzation",
"enchantdummy_curepoison",
"enchantdummy_damageattribute",
"enchantdummy_damagefatigue",
"enchantdummy_damagehealth",
"enchantdummy_damagemagicka",
"enchantdummy_damageskill",
"enchantdummy_demoralizecreature",
"enchantdummy_demoralizehumanoid",
"enchantdummy_detectanimal",
"enchantdummy_detectenchantment",
"enchantdummy_detectkey",
"enchantdummy_disintegratearmor",
"enchantdummy_disintegrateweapon",
"enchantdummy_dispel",
"enchantdummy_divineintervention",
"enchantdummy_drainattribute",
"enchantdummy_drainfatigue",
"enchantdummy_drainhealth",
"enchantdummy_drainmagicka",
"enchantdummy_drainskill",
"enchantdummy_extraspell",
"enchantdummy_feather",
"enchantdummy_firedamage",
"enchantdummy_fireshield",
"enchantdummy_fortifyattack",
"enchantdummy_fortifyattribute",
"enchantdummy_fortifyfatigue",
"enchantdummy_fortifyhealth",
"enchantdummy_fortifymagicka",
"enchantdummy_fortifymagickamultiplier",
"enchantdummy_fortifyskill",
"enchantdummy_frenzycreature",
"enchantdummy_frenzyhumanoid",
"enchantdummy_frostdamage",
"enchantdummy_frostshield",
"enchantdummy_invisibility",
"enchantdummy_jump",
"enchantdummy_levitate",
"enchantdummy_light",
"enchantdummy_lightningshield",
"enchantdummy_lock",
"enchantdummy_mark",
"enchantdummy_nighteye",
"enchantdummy_open",
"enchantdummy_paralyze",
"enchantdummy_poison",
"enchantdummy_rallycreature",
"enchantdummy_rallyhumanoid",
"enchantdummy_recall",
"enchantdummy_reflect",
"enchantdummy_removecurse",
"enchantdummy_resistblightdisease",
"enchantdummy_resistcommondisease",
"enchantdummy_resistcorprus",
"enchantdummy_resistfire",
"enchantdummy_resistfrost",
"enchantdummy_resistmagicka",
"enchantdummy_resistnormalweapons",
"enchantdummy_resistparalysis",
"enchantdummy_resistpoison",
"enchantdummy_resistshock",
"enchantdummy_restoreattribute",
"enchantdummy_restorefatigue",
"enchantdummy_restorehealth",
"enchantdummy_restoremagicka",
"enchantdummy_restoreskill",
"enchantdummy_sanctuary",
"enchantdummy_shield",
"enchantdummy_shockdamage",
"enchantdummy_silence",
"enchantdummy_slowfall",
"enchantdummy_soultrap",
"enchantdummy_sound",
"enchantdummy_spellabsorption",
"enchantdummy_stuntedmagicka",
"enchantdummy_summonbear",
"enchantdummy_summonbonewolf",
"enchantdummy_summonbonelord",
"enchantdummy_summoncenturionsphere",
"enchantdummy_summonclannfear",
"enchantdummy_summondaedroth",
"enchantdummy_summondremora",
"enchantdummy_summonfabricant",
"enchantdummy_summonflameatronach",
"enchantdummy_summonfrostatronach",
"enchantdummy_summonghost",
"enchantdummy_summongoldensaint",
"enchantdummy_summongreaterbonewalker",
"enchantdummy_summonhunger",
"enchantdummy_summonleastbonewalker",
"enchantdummy_summonscamp",
"enchantdummy_summonskeleton",
"enchantdummy_summonstormatronach",
"enchantdummy_summontwilight",
"enchantdummy_summonwolf",
"enchantdummy_sundamage",
"enchantdummy_swiftswim",
"enchantdummy_telekinesis",
"enchantdummy_turnundead",
"enchantdummy_waterbreathing",
"enchantdummy_waterwalking",
"enchantdummy_weaknesstoblightdisease",
"enchantdummy_weaknesstocommondisease",
"enchantdummy_weaknesstocorprus",
"enchantdummy_weaknesstofire",
"enchantdummy_weaknesstofrost",
"enchantdummy_weaknesstomagicka",
"enchantdummy_weaknesstonormalweapons",
"enchantdummy_weaknesstopoison",
"enchantdummy_weaknesstoshock",
"enchantdummy_fortifymaximummagicka",
"roguelite_almsivi",
"roguelite_disposition",
"roguelite_divine",
"roguelite_feather",
"roguelite_hitchance",
"roguelite_hitchance_companion",
"roguelite_intellect",
"roguelite_jack",
"roguelite_mark",
"roguelite_recall",
"roguelite_sanctuary",
"roguelite_sanctuary_companion",
"roguelite_shadowdancing",
"roguelite_silencehack",
"roguelite_slumber",
"roguelite_sneak",
"roguelite_soundhack",
"am_cham",
"am_comp01",
"am_hasfollowed",
"am_inv",
"am_lev",
"am_recall1",
"am_resist1",
"am_ww",
"hearthstone_dummy",
"sky_follow_lv_fake",
"sky_follow_lv_real",
"sky_follow_ww_fake",
"sky_follow_ww_real",
"sky_ire_dh_scampmesa07_bless",
"sky_ire_ha_houseofgods_spell",
"sky_qre_bm5_sunblo",
"sky_qre_dsmg_spell_slow",
"sky_qre_ha2_rewardspell",
"sky_qre_ha2_witchspell",
"sky_qre_kg3_reward",
"sky_qre_kw1_power_alte",
"sky_qre_kw1_power_conj",
"sky_qre_kw1_power_dest",
"sky_qre_kw1_power_myst",
"sky_qre_kwmg2_spell",
"sky_qre_mai4_boots_en",
"sky_qre_nar1_ability_cham",
"merc_fargoth_abi01",
"merc_fargoth_abi02",
"merc_fargoth_abi03",
"merc_fargoth_fight4ring_abi",
"merc_fargoth_flee_abi",
"merc_fargoth__delet0001",
"necro_abl_bound_shield",
"necro_abl_bound_dagger",
"necro_abl_bound_mace",
"necro_abl_bound_longsword",
"necro_abl_bound_battle_axe",
"r0_absorb_fire",
"r0_absorb_frost",
"r0_absorb_shock",
"plx_hungercurse",
"plx_hungersfeast",
"plx_reflect10",
"plx_regen_magic",
"plx_centurion_resistances",
"plx_ghost_iceblast",
"plx_cent_spider_poison",
"plx_cent_spider_fire",
"immune to magicka",
"r0_slaughterfish_shock_spell",
"r0_slaughterfish_blind_ability",
"r0_dreugh_land_spell",
"r0_slaughterfish_shock_charge",
"r0_mudcrab_king_spell",
"r0_wc_water_creature_ability",
"r0_wc_hard_shell_ability",
"r0_magicka_resist_20_ability",
"r0_dreugh_man'o'war_spell",
"un_undead_immunities",
"un_undead_immunitiesm",
"un_lich touch",
"un_ghosttouch",
"un_grave's curse",
"un_touch of the deads",
"un_black death",
"un_spellabsorption",
"un_healing touch",
"necro_abl_bound_all",
"necro_abl_bound_bow",
"gr_draugr_abilities",
"gr_restore_attribute_ability",
"gr_summon_boners",
"gr_shadow_weave_great",
"gr_summon_skeletons",
"gr_fifth_barrier_brief",
"gr_energy_leech",
"gr_magicka_leech",
"gr_life_leech",
"gr_icy_death_touch",
"gr_icy_death_ranged",
"gr_dragon_priest_abilities",
"gr_super_sanctuary",
"gr_eleventh_barrier",
"gr_five_fingers_of_death",
"gr_draugr_powerup",
"gr_heal_self_100",
"gr_fire_wyrm",
"gr_summon_draugr",
"gr_strength_boost_draugr",
"gr_draugr_abilities_skel",
"gr_strength_boost",
"gr_dragon_poison",
"gr_draugr_sun_weakness",
"necro_abl_bound_spear",
"btsh_dagoth_drain",
"btsh_dagoth_flamestrike",
"plx_bomb_boom",
"plx_shock_boom",
"perfect sanctuary",
"fantastic sanctuary",
"nv_chooseboundarmortype",
"ser_bandspell",
"ma_nosundamage",
"detd_playerdrewweapon",
"detd_blackoutnaked",
"bes_eleshield_armor_1",
"bes_eleshield_armor_10",
"bes_eleshield_armor_11",
"bes_eleshield_armor_12",
"bes_eleshield_armor_13",
"bes_eleshield_armor_14",
"bes_eleshield_armor_15",
"bes_eleshield_armor_16",
"bes_eleshield_armor_17",
"bes_eleshield_armor_18",
"bes_eleshield_armor_19",
"bes_eleshield_armor_2",
"bes_eleshield_armor_20",
"bes_eleshield_armor_3",
"bes_eleshield_armor_4",
"bes_eleshield_armor_5",
"bes_eleshield_armor_6",
"bes_eleshield_armor_7",
"bes_eleshield_armor_8",
"bes_eleshield_armor_9",
"bes_eleshield_fire_dmg",
"bes_eleshield_frost_dmg",
"bes_eleshield_shock_dmg",
"bes_eleshield_slow",
"bes_eleshield_weak",
"bes_soundbuff_1",
"bes_soundbuff_10",
"bes_soundbuff_11",
"bes_soundbuff_12",
"bes_soundbuff_13",
"bes_soundbuff_14",
"bes_soundbuff_15",
"bes_soundbuff_16",
"bes_soundbuff_17",
"bes_soundbuff_18",
"bes_soundbuff_19",
"bes_soundbuff_2",
"bes_soundbuff_20",
"bes_soundbuff_3",
"bes_soundbuff_4",
"bes_soundbuff_5",
"bes_soundbuff_6",
"bes_soundbuff_7",
"bes_soundbuff_8",
"bes_soundbuff_9",
"pilferer_detected",
"o_nourishment_m",
"skill evolution block training cap",
"skill evolution armorer training cap",
"skill evolution mediumarmor training cap",
"skill evolution heavyarmor training cap",
"skill evolution bluntweapon training cap",
"skill evolution longblade training cap",
"skill evolution axe training cap",
"skill evolution spear training cap",
"skill evolution athletics training cap",
"skill evolution enchant training cap",
"skill evolution destruction training cap",
"skill evolution alteration training cap",
"skill evolution illusion training cap",
"skill evolution conjuration training cap",
"skill evolution mysticism training cap",
"skill evolution restoration training cap",
"skill evolution alchemy training cap",
"skill evolution unarmored training cap",
"skill evolution security training cap",
"skill evolution sneak training cap",
"skill evolution acrobatics training cap",
"skill evolution lightarmor training cap",
"skill evolution shortblade training cap",
"skill evolution marksman training cap",
"skill evolution mercantile training cap",
"skill evolution speechcraft training cap",
"skill evolution handtohand training cap",
"felms' glory",
"rilm's grace",
"nv_appdebuff2",
"nv_charioteer",
"nv_ladyfavor",
"nv_ladywarding",
"nv_maramercy",
"nv_maramilk",
"nv_ritualfortifysummons",
"nv_sneakshadow",
"nv_steedattackbonus",
"nv_steedattackspell2",
"nv_thiefnocastattack",
"nv_warriorlaststand",
}

-- ============================================================
-- MWSCRIPT AND SPELL LIST GENERATOR
-- ============================================================
if GENERATE_DATA then
	if core then
		SPELL_LIST = {}
		print("SPELL_LIST = {")
		for _, spell in pairs(core.magic.spells.records) do
			if spell.id:sub(1,#"Generated:") ~= "Generated:" then
				print('"'..spell.id..'",')
				table.insert(SPELL_LIST, spell.id)
			end
		end
		print("}")
	else
		local lines = {
			"Begin RemoveSpellScript",
			"",
			"short spelltoremove",
			"",
			"if ( spelltoremove == 0 )",
			"\\treturn",
			"endif",
			"",
		}
		
		for i, spellId in ipairs(SPELL_LIST) do
			local condition = i == 1 and "if" or "elseif"
			table.insert(lines, condition .. " ( spelltoremove == " .. i .. " )")
			table.insert(lines, "\\tif ( player->GetSpell \\\"" .. spellId .. "\\\" )")
			table.insert(lines, "\\t\\tplayer->RemoveSpell \\\"" .. spellId .. "\\\"")
			table.insert(lines, "\\tendif")
		end
		
		table.insert(lines, "endif")
		table.insert(lines, "")
		table.insert(lines, "set spelltoremove to 0")
		table.insert(lines, "")
		table.insert(lines, "End")
		
		print(table.concat(lines, "\\n"))
	end
end


-- Build reverse lookup map
local SPELL_TO_INDEX = {}
for i, spellId in ipairs(SPELL_LIST) do
    SPELL_TO_INDEX[spellId] = i
end


local function onRequestSpellRemoval(data)
    local spellId = data.spell
    local index = SPELL_TO_INDEX[spellId] or 0
    
    if index == 0 then
        print("Unknown spell ID: " .. spellId)
		return
	end
	local script = world.mwscript.getGlobalScript("removeSpellFix_remove")
	if not script then
		print("ERROR: removeSpellFix.omwaddon is not loaded, spell removal failed")
		return
	end
	
	script.variables.spelltoremove = index
end

return {
    eventHandlers = {
        requestSpellRemoval = onRequestSpellRemoval
    },
	interfaceName = "removeSpellFix",
	interface = {
		SPELL_TO_INDEX = SPELL_TO_INDEX,
	}
}


