local defaultConfig = {
    classMod = true,
    indvMod = true,
    levelMod = true,
    majorMod = 10,
    minorMod = 10,
    miscMod = 10,
	acrobaticsMod = 10,
    alchemyMod = 10,
	alterationMod = 10,
    armorerMod = 10,
    athleticsMod = 10,
    axeMod = 10,
    blockMod = 10,
    bluntMod = 10,
    conjurationMod = 10,
    destructionMod = 10,
    enchantMod = 10,
    handMod = 10,
    heavyMod = 10,
    illusionMod = 10,
    lightMod = 10,
    longMod = 10,
    marksmanMod = 10,
    mediumMod = 10,
    mercantileMod = 10,
    mysticismMod = 10,
    restorationMod = 10,
    securityMod = 10,
    shortMod = 10,
    sneakMod = 10,
    spearMod = 10,
    speechcraftMod = 10,
    unarmoredMod = 10,
    levelMod25 = 20,
    levelMod50 = 15,
    levelMod75 = 10,
    levelMod100 = 5,
}

local mwseConfig = mwse.loadConfig("Krimson.Adjustable Skill Progression", defaultConfig)

return mwseConfig