
local M = {
	["ascadian isles region"] = 0,
	["ashlands region"] = 0,
	["azura\'s coast region"] = 0,
	["bitter coast region"] = 0,
	["brodir grove region"] = 0,
	["felsaad coast region"] = 0,
	["grazelands region"] = 0,
	["hirstaang forest region"] = 0,
	["isinfier plains region"] = 0,
	["moesring mountains region"] = 0,
	["molag mar region"] = 0,
	["mournhold region"] = 0,
	["red mountain region"] = 0,
	["sheogorad"] = 0,
	["thirsk region"] = 0,
	["west gash region"] = 0,


	-- TR/SHOTN/PC 23.10

	["aanthirin region"] = 0,
	["abecean sea region"] = 0,
	["alt orethan region"] = 0,
	["aranyon pass region"] = 0,
	["armun ashlands region"] = 0,
	["arnesian jungle region"] = 0,
	["ascadian bluffs region"] = 0,
	["boethiah\'s spine region"] = 0,
	["broken cape region"] = 0,
	["clambering moor region"] = 0,
	["colovian barrowlands region"] = 0,
	["colovian highlands region"] = 0,
	["dagon urul region"] = 0,
	["dasek marsh region"] = 0,
	["deshaan plains region"] = 0,
	["drajkmyr marsh region"] = 0,
	["druadach highlands region"] = 0,
	["falkheim region"] = 0,
	["gilded hills region"] = 0,
	["gold coast region"] = 0,
	["gorvigh mountains region"] = 0,
	["grey meadows region"] = 0,
	["helnim fields region"] = 0,
	["hirsing forest region"] = 0,
	["hrimbald plateau region"] = 0,
	["jerall mountains region"] = 0,
	["julan-shar region"] = 0,
	["kilkreath mountains region"] = 0,
	["kreathi vale region"] = 0,
	["kvetch pass region"] = 0,
	["lan orethan region"] = 0,
	["lorchwuir heath region"] = 0,
	["mephalan vales region"] = 0,
	["mhorken hills region"] = 0,
	["midkarth region"] = 0,
	["molah ruhn region"] = 0,
	["molagreahd region"] = 0,
	["mudflats region"] = 0,
	["nedothril region"] = 0,
	["northshore region"] = 0,
	["old ebonheart region"] = 0,
	["othreleth woods region"] = 0,
	["padomaic ocean region"] = 0,
	["reaver\'s shore region"] = 0,
	["rift valley region"] = 0,
	["roth roryn region"] = 0,
	["sacred lands region"] = 0,
	["salt marsh region"] = 0,
	["sea of ghosts region"] = 0,
	["seitur region"] = 0,
	["shambalun veil region"] = 0,
	["shipal-shin region"] = 0,
	["skaldring mountains region"] = 0,
	["solitude forest region"] = 0,
	["solitude forest region s"] = 0,
	["southern gold coast region"] = 0,
	["stirk isle region"] = 0,
	["sundered hills region"] = 0,
	["sundered scar region"] = 0,
	["telvanni isles region"] = 0,
	["temaris isle region"] = 0,
	["thirr valley region"] = 0,
	["throat of the world region"] = 0,
	["trolls\'s teeth mountains region"] = 0,
	["uld vraech region"] = 0,
	["valstaag highlands region"] = 0,
	["velothi mountains region"] = 0,
	["vorndgad forest region"] = 0,
	["west weald region"] = 0,
	["white plains region"] = 0,
	["wuurthal dale region"] = 0,
	["ysheim region"] = 0,

}


return M
