return {
    "jewelled",
    "(amethyst) a",
    "(amethyst) b",
    "(emerald)",
    "(sapphire)",
    "(peridot)",
    "(garnet)",
    "(bloodstone)",
    "(agate)",
    "(onyx)",
    "(carnelian)",
    "(beryl)",
    "(topaz)",
    "(ruby)",
    "(tiger's eye)",
    "(spinel)",
    "(zircon)",
    "(ebony)",
    "(citrin)",
    "(aquamarine)",
    "(pearl)",
    "(amber)",
    "(rose quartz)",
    "(black onyx)",
    "(abalone)",
}