local icons = {}
icons.MG = "\\Icons\\SSQN\\MG.dds"
icons.FG = "\\Icons\\SSQN\\FG.dds"
icons.HH = "\\Icons\\SSQN\\HH.dds"
icons.HR = "\\Icons\\SSQN\\HR.dds"
icons.HT = "\\Icons\\SSQN\\HT.dds"
icons.TG = "\\Icons\\SSQN\\TG.dds"
icons.MT = "\\Icons\\SSQN\\MT.dds"
icons.TT = "\\Icons\\SSQN\\TT.dds"
icons.IL = "\\Icons\\SSQN\\IL.dds"
icons.BM = "\\Icons\\SSQN\\BM.dds"
icons.VV = "\\Icons\\SSQN\\vamp.dds"
icons.DA = "\\Icons\\SSQN\\daedric.dds"
--Tribunal also not playing nice
icons.TR = "\\Icons\\SSQN\\TR.dds"
icons.TR_MissingHand = "\\Icons\\SSQN\\TR.dd"
icons.TR05_People = "\\Icons\\SSQN\\TR.dds"
icons.TR06 = "\\Icons\\SSQN\\TR.dds"
icons.TR07 = "\\Icons\\SSQN\\TR.dds"
icons.TR08_Hlaalu = "\\Icons\\SSQN\\TR.dds"
icons.TR08_Hlaalu_Alen = "\\Icons\\SSQN\\TR.dds"
icons.TR08_Hlaalu_Berano = "\\Icons\\SSQN\\TR.dds"
icons.TR08_Hloggar = "\\Icons\\SSQN\\TR.dds"
icons.TR09 = "\\Icons\\SSQN\\TR.dds"
icons.CO = "\\Icons\\SSQN\\EEC.dds"
icons.Colony_update = "\\Icons\\SSQN\\EEC.dds"
--The mess that is the IC Journal Entries
icons.IC1_marshmerrow = "\\Icons\\SSQN\\IC.dds"
icons.IC2_Muck = "\\Icons\\SSQN\\IC.dds"
icons.IC3_willow = "\\Icons\\SSQN\\IC.dds"
icons.IC4_scrib = "\\Icons\\SSQN\\IC.dds"
icons.IC5_corkbulb = "\\Icons\\SSQN\\IC.dds"
icons.IC6_Rat = "\\Icons\\SSQN\\IC.dds"
icons.IC7_netch = "\\Icons\\SSQN\\IC.dds"
icons.IC_8_Nord_alms = "\\Icons\\SSQN\\IC.dds"
icons.IC9_Argonian = "\\Icons\\SSQN\\IC.dds"
icons.IC10_buckmoth = "\\Icons\\SSQN\\IC.dds"
icons.IC11_shirt = "\\Icons\\SSQN\\IC.dds"
icons.IC12_dinner = "\\Icons\\SSQN\\IC.dds"
icons.IC13_rich = "\\Icons\\SSQN\\IC.dds"
icons.IC14_Ponius = "\\Icons\\SSQN\\IC.dds"
icons.IC15_Missing_Limeware = "\\Icons\\SSQN\\IC.dds"
icons.IC16_Haunting = "\\Icons\\SSQN\\IC.dds"
icons.IC17_Witch = "\\Icons\\SSQN\\IC.dds"
icons.IC18_Silver = "\\Icons\\SSQN\\IC.dds"
icons.IC19_Restless = "\\Icons\\SSQN\\IC.dds"
icons.IC25_JonHawker = "\\Icons\\SSQN\\IC.dds"
icons.IC26_AmaNin = "\\Icons\\SSQN\\IC.dds"
icons.IC27_Oracle = "\\Icons\\SSQN\\IC.dds"
icons.IC28_Urjorad = "\\Icons\\SSQN\\IC.dds"
icons.IC29_Crusher = "\\Icons\\SSQN\\IC.dds"
icons.IC30_Imperial_veteran = "\\Icons\\SSQN\\IC.dds"
--Main Quest (also kind of a mess)
icons.A1 = "\\Icons\\SSQN\\MW.dds"
icons.A1_V = "\\Icons\\SSQN\\MW.dds"
icons.A2_1 = "\\Icons\\SSQN\\MW.dds"
icons.A2_2 = "\\Icons\\SSQN\\MW.dds"
icons.A2_3 = "\\Icons\\SSQN\\MW.dds"
icons.A2_4 = "\\Icons\\SSQN\\MW.dds"
icons.A2_6 = "\\Icons\\SSQN\\MW.dds"
icons.B1 = "\\Icons\\SSQN\\MW.dds"
icons.B2 = "\\Icons\\SSQN\\MW.dds"
icons.B2a = "\\Icons\\SSQN\\MW.dds"
icons.B2b = "\\Icons\\SSQN\\MW.dds"
icons.B2c = "\\Icons\\SSQN\\MW.dds"
icons.B3 = "\\Icons\\SSQN\\MW.dds"
icons.B4 = "\\Icons\\SSQN\\MW.dds"
icons.B5 = "\\Icons\\SSQN\\MW.dds"
icons.B6 = "\\Icons\\SSQN\\MW.dds"
icons.B7 = "\\Icons\\SSQN\\MW.dds"
icons.B8 = "\\Icons\\SSQN\\MW.dds"
icons.C0_Act_C = "\\Icons\\SSQN\\MW.dds"
icons.C0_Act_C_Expo = "\\Icons\\SSQN\\MW.dds"
icons.C2 = "\\Icons\\SSQN\\MW.dds"
icons.C3 = "\\Icons\\SSQN\\MW.dds"
icons.CX = "\\Icons\\SSQN\\MWbackpath.dds"
-- Galen's Quest for Truth Thanks to Danae for the below icons and quest IDs
icons.aa_ws = "\\Icons\\SSQN\\galennotif.dds"
-- The Rishajiit
		icons.aa_lat =  "\\Icons\\SSQN\\lattenotif.dds"
		icons.aa_lat_00 =  "\\Icons\\SSQN\\lattenotif.dds"
-- Friends and Frens
		icons.aa_ff =  "\\Icons\\SSQN\\ffrens.dds"
		icons.aa_FF =  "\\Icons\\SSQN\\ffrens.dds"
-- Mysterious Affair of Sara Shenk
		icons.aa_shenk00 =  "\\Icons\\SSQN\\saranotif.dds"
		icons.aa_shenk01 =  "\\Icons\\SSQN\\saranotif.dds"
		icons.aa_shenk02 =  "\\Icons\\SSQN\\saranotif.dds"
		icons.aa_shenk03 =  "\\Icons\\SSQN\\saranotif.dds"
		icons.aa_shenk03a =  "\\Icons\\SSQN\\saranotif.dds"
		icons.aa_shenk03b =  "\\Icons\\SSQN\\saranotif.dds"
		icons.aa_shenk03c =  "\\Icons\\SSQN\\saranotif.dds"
		icons.aa_shenk03d =  "\\Icons\\SSQN\\saranotif.dds"
--Sails and Sales
		icons.DS_ =  "\\Icons\\SSQN\\sailsnotif.dds"
		icons.ds22 =  "\\Icons\\SSQN\\sailsnotif.dds"
		icons.ds =  "\\Icons\\SSQN\\sailsnotif.dds"
		icons.ds22_crew =  "\\Icons\\SSQN\\sailsnotif.dds"
		icons.ds22_cross =  "\\Icons\\SSQN\\sailsnotif.dds"
		icons.ds22_get =  "\\Icons\\SSQN\\sailsnotif.dds"
		icons.ds22_intro =  "\\Icons\\SSQN\\sailsnotif.dds"
		icons.ds22_supply =  "\\Icons\\SSQN\\sailsnotif.dds"
-- Imperial Factions
		icons.aa_fact_fg =  "\\Icons\\SSQN\\FG.dds"
		icons.aa_fact_mg =  "\\Icons\\SSQN\\MG.dds"
		icons.aa_fact_tg =  "\\Icons\\SSQN\\TG.dds"
-- Divine Providence
		icons.aa_fal =  "\\Icons\\SSQN\\divine.dds"
-- Suran Underworld
		icons.A_BF =  "\\Icons\\SSQN\\suran.dds"
		icons.A_CT =  "\\Icons\\SSQN\\suran.dds"
		icons.A_SS =  "\\Icons\\SSQN\\suran.dds"
-- Pimp my Shrine
		icons.ss20 =  "\\Icons\\SSQN\\daedric.dds"
-- Hircine's Quest
		icons._quest =  "\\Icons\\SSQN\\daedric.dds"
-- The Sable Dragon
		icons.man =  "\\Icons\\SSQN\\sable.dds"
-- Surfracer
		icons.aa_surf =  "\\Icons\\SSQN\\surf.dds"
-- Failed Incarnate Pilgrimage
		icons.aa_mj20 =  "\\Icons\\SSQN\\ash.dds"
-- Olyn Hleran
		icons.MM_Redo =  "\\Icons\\SSQN\\HR.dds"
-- Ebonheart Underworks
		icons.dd19 =  "\\Icons\\SSQN\\ebon.dds"


return icons