--[[ Crafting-materials listing -- Replace items in the just-entered cell
		Part of Morrowind Crafting 3.0
		Toccatta and Drac --]]

        local makerlist = {}
        makerlist = {
            {id = "furn_anvil00",
            newId = "mc_anvil_p",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "furn_de_loom_01",
            newId = "mc_loom_p",
            xtOffset = 0,
            ytOffset = 1,
            ztOffset = -51.5,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 180},

            {id = "furn_spinningwheel_01",
            newId = "mc_spinningwheel_p",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "furn_spinwheel00",
            newId = "mc_Cordagewheel_p",
            xtOffset = -12,
            ytOffset = -0.5,
            ztOffset = -64,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = -90},

            {id = "furn_log_01",
            newId = "mc_log_hickory",
            altId = "mc_log_cypress",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "furn_log_02",
            newId = "mc_log_ash",
            altId = "mc_log_swirlwood",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "furn_log_03",
            newId = "mc_log_pine",
            altId = "mc_log_oak",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "furn_log_04",
            newId = "mc_log_scrap",
            altId = "mc_log_parasol",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "in_t_crystal_01",
            newId = "Crystal_01_Pulse",
			altId = "Crystal_01_Pulse",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "in_t_crystal_02",
            newId = "Crystal_02_Pulse",
			altId = "Crystal_02_Pulse",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "T_Com_Furn_Potterswheel_01",
            newId = "mc_potterswheel02_p",
            scale = 1.54,
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

            {id = "T_Imp_Furn_Printpress_01",
            newId = "mc_printpress01_perm",
            scale = 1,
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},
			
			{id = "in_mudboulder00",
            newId = "in_mudboulder00",
			altId = "mc_ironboulder00A",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_moldboulder00",
            newId = "in_moldboulder00",
			altId = "mc_ironboulder00B",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_pyboulder00",
            newId = "in_pyboulder00",
			altId = "mc_silverboulder00",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},
			
			{id = "in_mudboulder01",
            newId = "in_mudboulder01",
			altId = "mc_ironboulder01A",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_moldboulder01",
            newId = "in_moldboulder01",
			altId = "mc_ironboulder01B",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_pyboulder01",
            newId = "in_pyboulder01",
			altId = "mc_silverboulder01",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},
			
			{id = "in_mudboulder02",
            newId = "in_mudboulder02",
			altId = "mc_ironboulder02A",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_moldboulder02",
            newId = "in_moldboulder02",
			altId = "mc_ironboulder02B",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_pyboulder02",
            newId = "in_pyboulder02",
			altId = "mc_silverboulder02",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},
			
			{id = "in_mudboulder03",
            newId = "in_mudboulder03",
			altId = "mc_ironboulder03A",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_moldboulder03",
            newId = "in_moldboulder03",
			altId = "mc_ironboulder03B",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_pyboulder03",
            newId = "in_pyboulder03",
			altId = "mc_silverboulder03",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},
			
			{id = "in_mudboulder04",
            newId = "in_mudboulder04",
			altId = "mc_ironboulder04A",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_moldboulder04",
            newId = "in_moldboulder04",
			altId = "mc_ironboulder04B",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_pyboulder04",
            newId = "in_pyboulder04",
			altId = "mc_silverboulder04",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},
			
			{id = "in_mudboulder05",
            newId = "in_mudboulder05",
			altId = "mc_ironboulder05A",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_moldboulder05",
            newId = "in_moldboulder05",
			altId = "mc_ironboulder05B",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0},

			{id = "in_pyboulder05",
            newId = "in_pyboulder05",
			altId = "mc_silverboulder05",
            xtOffset = 0,
            ytOffset = 0,
            ztOffset = 0,
            xrOffset = 0,
            yrOffset = 0,
            zrOffset = 0}
        }
		
		

        return makerlist