local playSound = {
    alitMOAN = function() tes3.playSound{ sound = "alitMOAN" } end,
alitROAR = function() tes3.playSound{ sound = "alitROAR" } end,
alitSCRM = function() tes3.playSound{ sound = "alitSCRM" } end,
Alma_att0 = function() tes3.playSound{ sound = "Alma_att0" } end,
Alma_att1 = function() tes3.playSound{ sound = "Alma_att1" } end,
Alma_att2 = function() tes3.playSound{ sound = "Alma_att2" } end,
Alma_hit0 = function() tes3.playSound{ sound = "Alma_hit0" } end,
Alma_hit1 = function() tes3.playSound{ sound = "Alma_hit1" } end,
Alma_hit2 = function() tes3.playSound{ sound = "Alma_hit2" } end,
alteration_area = function() tes3.playSound{ sound = "alteration area" } end,
alteration_bolt = function() tes3.playSound{ sound = "alteration bolt" } end,
alteration_cast = function() tes3.playSound{ sound = "alteration cast" } end,
alteration_hit = function() tes3.playSound{ sound = "alteration hit" } end,
Ambient_Factory_Ruins = function() tes3.playSound{ sound = "Ambient Factory Ruins" } end,
ancestor_ghost_moan = function() tes3.playSound{ sound = "ancestor ghost moan" } end,
ancestor_ghost_roar = function() tes3.playSound{ sound = "ancestor ghost roar" } end,
ancestor_ghost_scream = function() tes3.playSound{ sound = "ancestor ghost scream" } end,
animalLARGEleft = function() tes3.playSound{ sound = "animalLARGEleft" } end,
animalLARGEright = function() tes3.playSound{ sound = "animalLARGEright" } end,
animalSMALLleft = function() tes3.playSound{ sound = "animalSMALLleft" } end,
animalSMALLright = function() tes3.playSound{ sound = "animalSMALLright" } end,
ash_ghoul_moan = function() tes3.playSound{ sound = "ash ghoul moan" } end,
ash_ghoul_roar = function() tes3.playSound{ sound = "ash ghoul roar" } end,
ash_ghoul_scream = function() tes3.playSound{ sound = "ash ghoul scream" } end,
ash_slave_moan = function() tes3.playSound{ sound = "ash slave moan" } end,
ash_slave_roar = function() tes3.playSound{ sound = "ash slave roar" } end,
ash_slave_scream = function() tes3.playSound{ sound = "ash slave scream" } end,
ash_vampire_moan = function() tes3.playSound{ sound = "ash vampire moan" } end,
ash_vampire_roar = function() tes3.playSound{ sound = "ash vampire roar" } end,
ash_vampire_scream = function() tes3.playSound{ sound = "ash vampire scream" } end,
ash_zombie_moan = function() tes3.playSound{ sound = "ash zombie moan" } end,
ash_zombie_roar = function() tes3.playSound{ sound = "ash zombie roar" } end,
ash_zombie_scream = function() tes3.playSound{ sound = "ash zombie scream" } end,
Ashstorm = function() tes3.playSound{ sound = "Ashstorm" } end,
atroflame_moan = function() tes3.playSound{ sound = "atroflame moan" } end,
atroflame_roar = function() tes3.playSound{ sound = "atroflame roar" } end,
atroflame_scream = function() tes3.playSound{ sound = "atroflame scream" } end,
atrofrost_moan = function() tes3.playSound{ sound = "atrofrost moan" } end,
atrofrost_roar = function() tes3.playSound{ sound = "atrofrost roar" } end,
atrofrost_scream = function() tes3.playSound{ sound = "atrofrost scream" } end,
atrostorm_moan = function() tes3.playSound{ sound = "atrostorm moan" } end,
atrostorm_roar = function() tes3.playSound{ sound = "atrostorm roar" } end,
atrostorm_scream = function() tes3.playSound{ sound = "atrostorm scream" } end,
bear_moan = function() tes3.playSound{ sound = "bear moan" } end,
bear_roar = function() tes3.playSound{ sound = "bear roar" } end,
bear_scream = function() tes3.playSound{ sound = "bear scream" } end,
bearsniff = function() tes3.playSound{ sound = "bearsniff" } end,
bell1 = function() tes3.playSound{ sound = "bell1" } end,
bell2 = function() tes3.playSound{ sound = "bell2" } end,
bell3 = function() tes3.playSound{ sound = "bell3" } end,
bell4 = function() tes3.playSound{ sound = "bell4" } end,
bell5 = function() tes3.playSound{ sound = "bell5" } end,
bell6 = function() tes3.playSound{ sound = "bell6" } end,
blackoutin = function() tes3.playSound{ sound = "blackoutin" } end,
Blight = function() tes3.playSound{ sound = "Blight" } end,
BM_big_fire = function() tes3.playSound{ sound = "BM big fire" } end,
BM_Blizzard = function() tes3.playSound{ sound = "BM Blizzard" } end,
BM_Nord_attack = function() tes3.playSound{ sound = "BM Nord attack" } end,
BM_Nord_attackF = function() tes3.playSound{ sound = "BM Nord attackF" } end,
BM_pipe_large = function() tes3.playSound{ sound = "BM pipe large" } end,
BM_pipe_medium = function() tes3.playSound{ sound = "BM pipe medium" } end,
BM_pipe_small = function() tes3.playSound{ sound = "BM pipe small" } end,
BM_Sun = function() tes3.playSound{ sound = "BM Sun" } end,
BM_Wilderness = function() tes3.playSound{ sound = "BM Wilderness" } end,
BM_Wilderness2 = function() tes3.playSound{ sound = "BM Wilderness2" } end,
BM_Wilderness3 = function() tes3.playSound{ sound = "BM Wilderness3" } end,
BM_Wind = function() tes3.playSound{ sound = "BM Wind" } end,
BM_Ice_Sheet = function() tes3.playSound{ sound = "BM_Ice_Sheet" } end,
boar_moan = function() tes3.playSound{ sound = "boar moan" } end,
boar_roar = function() tes3.playSound{ sound = "boar roar" } end,
boar_scream = function() tes3.playSound{ sound = "boar scream" } end,
boarsniff = function() tes3.playSound{ sound = "boarsniff" } end,
Boat_Creak = function() tes3.playSound{ sound = "Boat Creak" } end,
boat_docked = function() tes3.playSound{ sound = "boat docked" } end,
Boat_Hull = function() tes3.playSound{ sound = "Boat Hull" } end,
Body_Fall_Large = function() tes3.playSound{ sound = "Body Fall Large" } end,
Body_Fall_Medium = function() tes3.playSound{ sound = "Body Fall Medium" } end,
Body_Fall_Small = function() tes3.playSound{ sound = "Body Fall Small" } end,
bonelord_moan = function() tes3.playSound{ sound = "bonelord moan" } end,
bonelord_roar = function() tes3.playSound{ sound = "bonelord roar" } end,
bonelord_scream = function() tes3.playSound{ sound = "bonelord scream" } end,
bonewalkerMOAN = function() tes3.playSound{ sound = "bonewalkerMOAN" } end,
bonewalkerROAR = function() tes3.playSound{ sound = "bonewalkerROAR" } end,
bonewalkerSCRM = function() tes3.playSound{ sound = "bonewalkerSCRM" } end,
bonewalkerWAR_moan = function() tes3.playSound{ sound = "bonewalkerWAR moan" } end,
bonewalkerWAR_roar = function() tes3.playSound{ sound = "bonewalkerWAR roar" } end,
bonewalkerWAR_scream = function() tes3.playSound{ sound = "bonewalkerWAR scream" } end,
book_close = function() tes3.playSound{ sound = "book close" } end,
book_open = function() tes3.playSound{ sound = "book open" } end,
book_page = function() tes3.playSound{ sound = "book page" } end,
book_page2 = function() tes3.playSound{ sound = "book page2" } end,
bowPull = function() tes3.playSound{ sound = "bowPull" } end,
bowShoot = function() tes3.playSound{ sound = "bowShoot" } end,
Bubbles = function() tes3.playSound{ sound = "Bubbles" } end,
Cave_Drip = function() tes3.playSound{ sound = "Cave Drip" } end,
Cave_Wind = function() tes3.playSound{ sound = "Cave Wind" } end,
Cave_Waterfall = function() tes3.playSound{ sound = "Cave_Waterfall" } end,
cavein = function() tes3.playSound{ sound = "cavein" } end,
cent_proj_moan = function() tes3.playSound{ sound = "cent proj moan" } end,
cent_proj_roar = function() tes3.playSound{ sound = "cent proj roar" } end,
cent_proj_scream = function() tes3.playSound{ sound = "cent proj scream" } end,
cent_proj_shoot = function() tes3.playSound{ sound = "cent proj shoot" } end,
cent_sphere_moan = function() tes3.playSound{ sound = "cent sphere moan" } end,
cent_sphere_roar = function() tes3.playSound{ sound = "cent sphere roar" } end,
cent_sphere_scream = function() tes3.playSound{ sound = "cent sphere scream" } end,
cent_spider_moan = function() tes3.playSound{ sound = "cent spider moan" } end,
cent_spider_roar = function() tes3.playSound{ sound = "cent spider roar" } end,
cent_spider_scream = function() tes3.playSound{ sound = "cent spider scream" } end,
cent_steam_fall = function() tes3.playSound{ sound = "cent steam fall" } end,
cent_steam_moan = function() tes3.playSound{ sound = "cent steam moan" } end,
cent_steam_roar = function() tes3.playSound{ sound = "cent steam roar" } end,
cent_steam_scream = function() tes3.playSound{ sound = "cent steam scream" } end,
chest_close = function() tes3.playSound{ sound = "chest close" } end,
chest_open = function() tes3.playSound{ sound = "chest open" } end,
chimes_wood = function() tes3.playSound{ sound = "chimes wood" } end,
clannfear_moan = function() tes3.playSound{ sound = "clannfear moan" } end,
clannfear_roar = function() tes3.playSound{ sound = "clannfear roar" } end,
clannfear_scream = function() tes3.playSound{ sound = "clannfear scream" } end,
cliff_racer_moan = function() tes3.playSound{ sound = "cliff racer moan" } end,
cliff_racer_roar = function() tes3.playSound{ sound = "cliff racer roar" } end,
cliff_racer_scream = function() tes3.playSound{ sound = "cliff racer scream" } end,
conjuration_area = function() tes3.playSound{ sound = "conjuration area" } end,
conjuration_bolt = function() tes3.playSound{ sound = "conjuration bolt" } end,
conjuration_cast = function() tes3.playSound{ sound = "conjuration cast" } end,
conjuration_hit = function() tes3.playSound{ sound = "conjuration hit" } end,
corpDRAG = function() tes3.playSound{ sound = "corpDRAG" } end,
corpus_stalker_moan = function() tes3.playSound{ sound = "corpus stalker moan" } end,
corpus_stalker_roar = function() tes3.playSound{ sound = "corpus stalker roar" } end,
corpus_stalker_scream = function() tes3.playSound{ sound = "corpus stalker scream" } end,
corpuslameMOAN = function() tes3.playSound{ sound = "corpuslameMOAN" } end,
corpuslameROAR = function() tes3.playSound{ sound = "corpuslameROAR" } end,
corpuslameSCRM = function() tes3.playSound{ sound = "corpuslameSCRM" } end,
Creeky_Wood = function() tes3.playSound{ sound = "Creeky Wood" } end,
critical_damage = function() tes3.playSound{ sound = "critical damage" } end,
crossbowPull = function() tes3.playSound{ sound = "crossbowPull" } end,
crossbowShoot = function() tes3.playSound{ sound = "crossbowShoot" } end,
crowd_booing = function() tes3.playSound{ sound = "crowd booing" } end,
CrowdBoo = function() tes3.playSound{ sound = "CrowdBoo" } end,
Crystal_Ringing = function() tes3.playSound{ sound = "Crystal Ringing" } end,
Daedric_Chant = function() tes3.playSound{ sound = "Daedric Chant" } end,
daedroth_moan = function() tes3.playSound{ sound = "daedroth moan" } end,
daedroth_roar = function() tes3.playSound{ sound = "daedroth roar" } end,
daedroth_scream = function() tes3.playSound{ sound = "daedroth scream" } end,
Dagoth_Ur_Moan = function() tes3.playSound{ sound = "Dagoth Ur Moan" } end,
Dagoth_Ur_Scream = function() tes3.playSound{ sound = "Dagoth Ur Scream" } end,
Default_Moan = function() tes3.playSound{ sound = "Default Moan" } end,
Default_Roar = function() tes3.playSound{ sound = "Default Roar" } end,
Default_Scream = function() tes3.playSound{ sound = "Default Scream" } end,
DefaultLand = function() tes3.playSound{ sound = "DefaultLand" } end,
DefaultLandWater = function() tes3.playSound{ sound = "DefaultLandWater" } end,
destruction_area = function() tes3.playSound{ sound = "destruction area" } end,
destruction_bolt = function() tes3.playSound{ sound = "destruction bolt" } end,
destruction_cast = function() tes3.playSound{ sound = "destruction cast" } end,
destruction_hit = function() tes3.playSound{ sound = "destruction hit" } end,
Disarm_Trap = function() tes3.playSound{ sound = "Disarm Trap" } end,
Disarm_Trap_Fail = function() tes3.playSound{ sound = "Disarm Trap Fail" } end,
Dock_Creak = function() tes3.playSound{ sound = "Dock Creak" } end,
Door_Creaky_Close = function() tes3.playSound{ sound = "Door Creaky Close" } end,
Door_Creaky_Open = function() tes3.playSound{ sound = "Door Creaky Open" } end,
Door_Heavy_Close = function() tes3.playSound{ sound = "Door Heavy Close" } end,
Door_Heavy_Open = function() tes3.playSound{ sound = "Door Heavy Open" } end,
Door_Latched_One_Close = function() tes3.playSound{ sound = "Door Latched One Close" } end,
Door_Latched_One_Open = function() tes3.playSound{ sound = "Door Latched One Open" } end,
Door_Latched_Two_Close = function() tes3.playSound{ sound = "Door Latched Two Close" } end,
Door_Latched_Two_Open = function() tes3.playSound{ sound = "Door Latched Two Open" } end,
Door_Metal_Close = function() tes3.playSound{ sound = "Door Metal Close" } end,
Door_Metal_Open = function() tes3.playSound{ sound = "Door Metal Open" } end,
Door_Stone_Close = function() tes3.playSound{ sound = "Door Stone Close" } end,
Door_Stone_Open = function() tes3.playSound{ sound = "Door Stone Open" } end,
dremora_moan = function() tes3.playSound{ sound = "dremora moan" } end,
dremora_roar = function() tes3.playSound{ sound = "dremora roar" } end,
dremora_scream = function() tes3.playSound{ sound = "dremora scream" } end,
dreugh_moan = function() tes3.playSound{ sound = "dreugh moan" } end,
dreugh_roar = function() tes3.playSound{ sound = "dreugh roar" } end,
dreugh_scream = function() tes3.playSound{ sound = "dreugh scream" } end,
drgr_moan = function() tes3.playSound{ sound = "drgr moan" } end,
drgr_roar = function() tes3.playSound{ sound = "drgr roar" } end,
drgr_scream = function() tes3.playSound{ sound = "drgr scream" } end,
Drink = function() tes3.playSound{ sound = "Drink" } end,
drown = function() tes3.playSound{ sound = "drown" } end,
drowning_damage = function() tes3.playSound{ sound = "drowning damage" } end,
dwarven_ghost_moan = function() tes3.playSound{ sound = "dwarven ghost moan" } end,
dwarven_ghost_roar = function() tes3.playSound{ sound = "dwarven ghost roar" } end,
dwarven_ghost_scream = function() tes3.playSound{ sound = "dwarven ghost scream" } end,
Dwe_waterfall = function() tes3.playSound{ sound = "Dwe_waterfall" } end,
Dwemer_Door_Close = function() tes3.playSound{ sound = "Dwemer Door Close" } end,
Dwemer_Door_Open = function() tes3.playSound{ sound = "Dwemer Door Open" } end,
Dwemer_Fan = function() tes3.playSound{ sound = "Dwemer Fan" } end,
enchant_fail = function() tes3.playSound{ sound = "enchant fail" } end,
enchant_success = function() tes3.playSound{ sound = "enchant success" } end,
endboom1 = function() tes3.playSound{ sound = "endboom1" } end,
endboom2 = function() tes3.playSound{ sound = "endboom2" } end,
endboom3 = function() tes3.playSound{ sound = "endboom3" } end,
endboom4 = function() tes3.playSound{ sound = "endboom4" } end,
endrumble = function() tes3.playSound{ sound = "endrumble" } end,
FabBossAlive = function() tes3.playSound{ sound = "FabBossAlive" } end,
FabBossClank = function() tes3.playSound{ sound = "FabBossClank" } end,
fabBossDead = function() tes3.playSound{ sound = "fabBossDead" } end,
FabBossGyro = function() tes3.playSound{ sound = "FabBossGyro" } end,
FabBossHit = function() tes3.playSound{ sound = "FabBossHit" } end,
fabBossLeft = function() tes3.playSound{ sound = "fabBossLeft" } end,
fabBossRight = function() tes3.playSound{ sound = "fabBossRight" } end,
FabBossRoar = function() tes3.playSound{ sound = "FabBossRoar" } end,
FabBossWhir = function() tes3.playSound{ sound = "FabBossWhir" } end,
FabHulkLeft = function() tes3.playSound{ sound = "FabHulkLeft" } end,
fabHulkMoan = function() tes3.playSound{ sound = "fabHulkMoan" } end,
FabHulkRight = function() tes3.playSound{ sound = "FabHulkRight" } end,
fabHulkRoar = function() tes3.playSound{ sound = "fabHulkRoar" } end,
fabHulkScream = function() tes3.playSound{ sound = "fabHulkScream" } end,
fabVermLeft = function() tes3.playSound{ sound = "fabVermLeft" } end,
fabVermMoan = function() tes3.playSound{ sound = "fabVermMoan" } end,
fabVermRight = function() tes3.playSound{ sound = "fabVermRight" } end,
fabVermRoar = function() tes3.playSound{ sound = "fabVermRoar" } end,
fabVermScream = function() tes3.playSound{ sound = "fabVermScream" } end,
Fire = function() tes3.playSound{ sound = "Fire" } end,
Fire_40 = function() tes3.playSound{ sound = "Fire 40" } end,
Fire_50 = function() tes3.playSound{ sound = "Fire 50" } end,
Flag = function() tes3.playSound{ sound = "Flag" } end,
Flies = function() tes3.playSound{ sound = "Flies" } end,
FootBareLeft = function() tes3.playSound{ sound = "FootBareLeft" } end,
FootBareRight = function() tes3.playSound{ sound = "FootBareRight" } end,
FootHeavyLeft = function() tes3.playSound{ sound = "FootHeavyLeft" } end,
FootHeavyRight = function() tes3.playSound{ sound = "FootHeavyRight" } end,
FootLightLeft = function() tes3.playSound{ sound = "FootLightLeft" } end,
FootLightRight = function() tes3.playSound{ sound = "FootLightRight" } end,
FootMedLeft = function() tes3.playSound{ sound = "FootMedLeft" } end,
FootMedRight = function() tes3.playSound{ sound = "FootMedRight" } end,
FootWaterLeft = function() tes3.playSound{ sound = "FootWaterLeft" } end,
FootWaterRight = function() tes3.playSound{ sound = "FootWaterRight" } end,
forcefield = function() tes3.playSound{ sound = "forcefield" } end,
frgiant_moan = function() tes3.playSound{ sound = "frgiant moan" } end,
frgiant_roar = function() tes3.playSound{ sound = "frgiant roar" } end,
frgiant_scream = function() tes3.playSound{ sound = "frgiant scream" } end,
frgtLeft = function() tes3.playSound{ sound = "frgtLeft" } end,
frgtRight = function() tes3.playSound{ sound = "frgtRight" } end,
frost_area = function() tes3.playSound{ sound = "frost area" } end,
frost_bolt = function() tes3.playSound{ sound = "frost_bolt" } end,
frost_cast = function() tes3.playSound{ sound = "frost_cast" } end,
frost_hit = function() tes3.playSound{ sound = "frost_hit" } end,
Gate_Large_Locked = function() tes3.playSound{ sound = "Gate Large Locked" } end,
ghostgate_sound = function() tes3.playSound{ sound = "ghostgate sound" } end,
goblin_large_moan = function() tes3.playSound{ sound = "goblin large moan" } end,
goblin_large_roar = function() tes3.playSound{ sound = "goblin large roar" } end,
goblin_large_scream = function() tes3.playSound{ sound = "goblin large scream" } end,
goblin_moan = function() tes3.playSound{ sound = "goblin moan" } end,
goblin_roar = function() tes3.playSound{ sound = "goblin roar" } end,
goblin_scream = function() tes3.playSound{ sound = "goblin scream" } end,
gold_saint_moan = function() tes3.playSound{ sound = "gold saint moan" } end,
gold_saint_roar = function() tes3.playSound{ sound = "gold saint roar" } end,
gold_saint_scream = function() tes3.playSound{ sound = "gold saint scream" } end,
gren_moan = function() tes3.playSound{ sound = "gren moan" } end,
gren_roar = function() tes3.playSound{ sound = "gren roar" } end,
gren_scream = function() tes3.playSound{ sound = "gren scream" } end,
greneat = function() tes3.playSound{ sound = "greneat" } end,
guar_moan = function() tes3.playSound{ sound = "guar moan" } end,
guar_roar = function() tes3.playSound{ sound = "guar roar" } end,
guar_scream = function() tes3.playSound{ sound = "guar scream" } end,
Hand_To_Hand_Hit = function() tes3.playSound{ sound = "Hand To Hand Hit" } end,
Hand_to_Hand_Hit_2 = function() tes3.playSound{ sound = "Hand to Hand Hit 2" } end,
Haunted = function() tes3.playSound{ sound = "Haunted" } end,
Health_Damage = function() tes3.playSound{ sound = "Health Damage" } end,
Heart = function() tes3.playSound{ sound = "Heart" } end,
heartdead = function() tes3.playSound{ sound = "heartdead" } end,
hearthit1 = function() tes3.playSound{ sound = "hearthit1" } end,
hearthit2 = function() tes3.playSound{ sound = "hearthit2" } end,
hearthit3 = function() tes3.playSound{ sound = "hearthit3" } end,
hearthit4 = function() tes3.playSound{ sound = "hearthit4" } end,
heartsunder = function() tes3.playSound{ sound = "heartsunder" } end,
Heavy_Armor_Hit = function() tes3.playSound{ sound = "Heavy Armor Hit" } end,
hirc_moan = function() tes3.playSound{ sound = "hirc moan" } end,
hirc_roar = function() tes3.playSound{ sound = "hirc roar" } end,
hirc_scream = function() tes3.playSound{ sound = "hirc scream" } end,
howl1 = function() tes3.playSound{ sound = "howl1" } end,
howl2 = function() tes3.playSound{ sound = "howl2" } end,
howl3 = function() tes3.playSound{ sound = "howl3" } end,
howl4 = function() tes3.playSound{ sound = "howl4" } end,
howl5 = function() tes3.playSound{ sound = "howl5" } end,
howl6 = function() tes3.playSound{ sound = "howl6" } end,
howl7 = function() tes3.playSound{ sound = "howl7" } end,
howl8 = function() tes3.playSound{ sound = "howl8" } end,
hrkLeft = function() tes3.playSound{ sound = "hrkLeft" } end,
hrkr_moan = function() tes3.playSound{ sound = "hrkr moan" } end,
hrkr_roar = function() tes3.playSound{ sound = "hrkr roar" } end,
hrkr_scream = function() tes3.playSound{ sound = "hrkr scream" } end,
hrkrbellow = function() tes3.playSound{ sound = "hrkrbellow" } end,
hrkRight = function() tes3.playSound{ sound = "hrkRight" } end,
ice_troll_moan = function() tes3.playSound{ sound = "ice troll moan" } end,
ice_troll_roar = function() tes3.playSound{ sound = "ice troll roar" } end,
ice_troll_scream = function() tes3.playSound{ sound = "ice troll scream" } end,
illusion_area = function() tes3.playSound{ sound = "illusion area" } end,
illusion_bolt = function() tes3.playSound{ sound = "illusion bolt" } end,
illusion_cast = function() tes3.playSound{ sound = "illusion cast" } end,
illusion_hit = function() tes3.playSound{ sound = "illusion hit" } end,
Item_Ammo_Down = function() tes3.playSound{ sound = "Item Ammo Down" } end,
Item_Ammo_Up = function() tes3.playSound{ sound = "Item Ammo Up" } end,
Item_Apparatus_Down = function() tes3.playSound{ sound = "Item Apparatus Down" } end,
Item_Apparatus_Up = function() tes3.playSound{ sound = "Item Apparatus Up" } end,
Item_Armor_Heavy_Down = function() tes3.playSound{ sound = "Item Armor Heavy Down" } end,
Item_Armor_Heavy_Up = function() tes3.playSound{ sound = "Item Armor Heavy Up" } end,
Item_Armor_Light_Down = function() tes3.playSound{ sound = "Item Armor Light Down" } end,
Item_Armor_Light_Up = function() tes3.playSound{ sound = "Item Armor Light Up" } end,
Item_Armor_Medium_Down = function() tes3.playSound{ sound = "Item Armor Medium Down" } end,
Item_Armor_Medium_Up = function() tes3.playSound{ sound = "Item Armor Medium Up" } end,
Item_Bodypart_Down = function() tes3.playSound{ sound = "Item Bodypart Down" } end,
Item_Bodypart_Up = function() tes3.playSound{ sound = "Item Bodypart Up" } end,
Item_Book_Down = function() tes3.playSound{ sound = "Item Book Down" } end,
Item_Book_Up = function() tes3.playSound{ sound = "Item Book Up" } end,
Item_Clothes_Down = function() tes3.playSound{ sound = "Item Clothes Down" } end,
Item_Clothes_Up = function() tes3.playSound{ sound = "Item Clothes Up" } end,
Item_Gold_Down = function() tes3.playSound{ sound = "Item Gold Down" } end,
Item_Gold_Up = function() tes3.playSound{ sound = "Item Gold Up" } end,
Item_Ingredient_Down = function() tes3.playSound{ sound = "Item Ingredient Down" } end,
Item_Ingredient_Up = function() tes3.playSound{ sound = "Item Ingredient Up" } end,
Item_Lockpick_Down = function() tes3.playSound{ sound = "Item Lockpick Down" } end,
Item_Lockpick_Up = function() tes3.playSound{ sound = "Item Lockpick Up" } end,
Item_Misc_Down = function() tes3.playSound{ sound = "Item Misc Down" } end,
Item_Misc_Up = function() tes3.playSound{ sound = "Item Misc Up" } end,
Item_Potion_Down = function() tes3.playSound{ sound = "Item Potion Down" } end,
Item_Potion_Up = function() tes3.playSound{ sound = "Item Potion Up" } end,
Item_Probe_Down = function() tes3.playSound{ sound = "Item Probe Down" } end,
Item_Probe_Up = function() tes3.playSound{ sound = "Item Probe Up" } end,
Item_Repair_Down = function() tes3.playSound{ sound = "Item Repair Down" } end,
Item_Repair_Up = function() tes3.playSound{ sound = "Item Repair Up" } end,
Item_Ring_Down = function() tes3.playSound{ sound = "Item Ring Down" } end,
Item_Ring_Up = function() tes3.playSound{ sound = "Item Ring Up" } end,
Item_Weapon_Blunt_Down = function() tes3.playSound{ sound = "Item Weapon Blunt Down" } end,
Item_Weapon_Blunt_Up = function() tes3.playSound{ sound = "Item Weapon Blunt Up" } end,
Item_Weapon_Bow_Down = function() tes3.playSound{ sound = "Item Weapon Bow Down" } end,
Item_Weapon_Bow_Up = function() tes3.playSound{ sound = "Item Weapon Bow Up" } end,
Item_Weapon_Crossbow_Down = function() tes3.playSound{ sound = "Item Weapon Crossbow Down" } end,
Item_Weapon_Crossbow_Up = function() tes3.playSound{ sound = "Item Weapon Crossbow Up" } end,
Item_Weapon_Longblade_Down = function() tes3.playSound{ sound = "Item Weapon Longblade Down" } end,
Item_Weapon_Longblade_Up = function() tes3.playSound{ sound = "Item Weapon Longblade Up" } end,
Item_Weapon_Shortblade_Down = function() tes3.playSound{ sound = "Item Weapon Shortblade Down" } end,
Item_Weapon_Shortblade_Up = function() tes3.playSound{ sound = "Item Weapon Shortblade Up" } end,
Item_Weapon_Spear_Down = function() tes3.playSound{ sound = "Item Weapon Spear Down" } end,
Item_Weapon_Spear_Up = function() tes3.playSound{ sound = "Item Weapon Spear Up" } end,
kagouti_moan = function() tes3.playSound{ sound = "kagouti moan" } end,
kagouti_roar = function() tes3.playSound{ sound = "kagouti roar" } end,
kagouti_scream = function() tes3.playSound{ sound = "kagouti scream" } end,
kwama_forager_slither = function() tes3.playSound{ sound = "kwama forager slither" } end,
kwamaF_left = function() tes3.playSound{ sound = "kwamaF left" } end,
kwamaF_right = function() tes3.playSound{ sound = "kwamaF right" } end,
kwamF_moan = function() tes3.playSound{ sound = "kwamF moan" } end,
kwamF_roar = function() tes3.playSound{ sound = "kwamF roar" } end,
kwamF_scream = function() tes3.playSound{ sound = "kwamF scream" } end,
kwamQ_moan = function() tes3.playSound{ sound = "kwamQ moan" } end,
kwamQ_roar = function() tes3.playSound{ sound = "kwamQ roar" } end,
kwamQ_scream = function() tes3.playSound{ sound = "kwamQ scream" } end,
kwamWK_moan = function() tes3.playSound{ sound = "kwamWK moan" } end,
kwamWK_roar = function() tes3.playSound{ sound = "kwamWK roar" } end,
kwamWK_scream = function() tes3.playSound{ sound = "kwamWK scream" } end,
kwamWR_moan = function() tes3.playSound{ sound = "kwamWR moan" } end,
kwamWR_roar = function() tes3.playSound{ sound = "kwamWR roar" } end,
kwamWR_scream = function() tes3.playSound{ sound = "kwamWR scream" } end,
Lava_Layer = function() tes3.playSound{ sound = "Lava Layer" } end,
LeftL = function() tes3.playSound{ sound = "LeftL" } end,
LeftM = function() tes3.playSound{ sound = "LeftM" } end,
LeftS = function() tes3.playSound{ sound = "LeftS" } end,
lich_lord_moan = function() tes3.playSound{ sound = "lich lord moan" } end,
lich_lord_roar = function() tes3.playSound{ sound = "lich lord roar" } end,
lich_lord_scream = function() tes3.playSound{ sound = "lich lord scream" } end,
Light_Armor_Hit = function() tes3.playSound{ sound = "Light Armor Hit" } end,
LockedChest = function() tes3.playSound{ sound = "LockedChest" } end,
LockedDoor = function() tes3.playSound{ sound = "LockedDoor" } end,
Machinery = function() tes3.playSound{ sound = "Machinery" } end,
magic_sound = function() tes3.playSound{ sound = "magic sound" } end,
Medium_Armor_Hit = function() tes3.playSound{ sound = "Medium Armor Hit" } end,
Menu_Click = function() tes3.playSound{ sound = "Menu Click" } end,
Menu_Size = function() tes3.playSound{ sound = "Menu Size" } end,
miss = function() tes3.playSound{ sound = "miss" } end,
MournDayAmb = function() tes3.playSound{ sound = "MournDayAmb" } end,
MournGates = function() tes3.playSound{ sound = "MournGates" } end,
MournGatesClose = function() tes3.playSound{ sound = "MournGatesClose" } end,
MournNightAmb = function() tes3.playSound{ sound = "MournNightAmb" } end,
MournSpray = function() tes3.playSound{ sound = "MournSpray" } end,
MournTempleAmb = function() tes3.playSound{ sound = "MournTempleAmb" } end,
mud_bubbles = function() tes3.playSound{ sound = "mud bubbles" } end,
mudcrab_moan = function() tes3.playSound{ sound = "mudcrab moan" } end,
mudcrab_roar = function() tes3.playSound{ sound = "mudcrab roar" } end,
mudcrab_scream = function() tes3.playSound{ sound = "mudcrab scream" } end,
mysticism_area = function() tes3.playSound{ sound = "mysticism area" } end,
mysticism_bolt = function() tes3.playSound{ sound = "mysticism bolt" } end,
mysticism_cast = function() tes3.playSound{ sound = "mysticism cast" } end,
mysticism_hit = function() tes3.playSound{ sound = "mysticism hit" } end,
netchBET_moan = function() tes3.playSound{ sound = "netchBET moan" } end,
netchBET_roar = function() tes3.playSound{ sound = "netchBET roar" } end,
netchBET_scream = function() tes3.playSound{ sound = "netchBET scream" } end,
netchBUL_moan = function() tes3.playSound{ sound = "netchBUL moan" } end,
netchBUL_roar = function() tes3.playSound{ sound = "netchBUL roar" } end,
netchBUL_scream = function() tes3.playSound{ sound = "netchBUL scream" } end,
nix_hound_moan = function() tes3.playSound{ sound = "nix hound moan" } end,
nix_hound_roar = function() tes3.playSound{ sound = "nix hound roar" } end,
nix_hound_scream = function() tes3.playSound{ sound = "nix hound scream" } end,
ogrim_moan = function() tes3.playSound{ sound = "ogrim moan" } end,
ogrim_roar = function() tes3.playSound{ sound = "ogrim roar" } end,
ogrim_scream = function() tes3.playSound{ sound = "ogrim scream" } end,
oil_bubbly = function() tes3.playSound{ sound = "oil bubbly" } end,
Open_Lock = function() tes3.playSound{ sound = "Open Lock" } end,
Open_Lock_Fail = function() tes3.playSound{ sound = "Open Lock Fail" } end,
Pack = function() tes3.playSound{ sound = "Pack" } end,
potion_fail = function() tes3.playSound{ sound = "potion fail" } end,
potion_success = function() tes3.playSound{ sound = "potion success" } end,
power_hummer = function() tes3.playSound{ sound = "power hummer" } end,
Power_Light = function() tes3.playSound{ sound = "Power Light" } end,
Power_light_50 = function() tes3.playSound{ sound = "Power light 50" } end,
Rain = function() tes3.playSound{ sound = "Rain" } end,
rain_heavy = function() tes3.playSound{ sound = "rain heavy" } end,
rat_moan = function() tes3.playSound{ sound = "rat moan" } end,
rat_roar = function() tes3.playSound{ sound = "rat roar" } end,
rat_scream = function() tes3.playSound{ sound = "rat scream" } end,
Repair = function() tes3.playSound{ sound = "Repair" } end,
repair_fail = function() tes3.playSound{ sound = "repair fail" } end,
restoration_area = function() tes3.playSound{ sound = "restoration area" } end,
restoration_bolt = function() tes3.playSound{ sound = "restoration bolt" } end,
restoration_cast = function() tes3.playSound{ sound = "restoration cast" } end,
restoration_hit = function() tes3.playSound{ sound = "restoration hit" } end,
riek_moan = function() tes3.playSound{ sound = "riek moan" } end,
riek_roar = function() tes3.playSound{ sound = "riek roar" } end,
riek_scream = function() tes3.playSound{ sound = "riek scream" } end,
RightL = function() tes3.playSound{ sound = "RightL" } end,
RightM = function() tes3.playSound{ sound = "RightM" } end,
RightS = function() tes3.playSound{ sound = "RightS" } end,
rmnt_moan = function() tes3.playSound{ sound = "rmnt moan" } end,
rmnt_roar = function() tes3.playSound{ sound = "rmnt roar" } end,
rmnt_scream = function() tes3.playSound{ sound = "rmnt scream" } end,
rock_and_roll = function() tes3.playSound{ sound = "rock and roll" } end,
rocks1 = function() tes3.playSound{ sound = "rocks1" } end,
rocks2 = function() tes3.playSound{ sound = "rocks2" } end,
rocks3 = function() tes3.playSound{ sound = "rocks3" } end,
rocks4 = function() tes3.playSound{ sound = "rocks4" } end,
rocks5 = function() tes3.playSound{ sound = "rocks5" } end,
rocks6 = function() tes3.playSound{ sound = "rocks6" } end,
rocks7 = function() tes3.playSound{ sound = "rocks7" } end,
rocks8 = function() tes3.playSound{ sound = "rocks8" } end,
ropebridge = function() tes3.playSound{ sound = "ropebridge" } end,
rumble1 = function() tes3.playSound{ sound = "rumble1" } end,
rumble2 = function() tes3.playSound{ sound = "rumble2" } end,
rumble3 = function() tes3.playSound{ sound = "rumble3" } end,
rumble4 = function() tes3.playSound{ sound = "rumble4" } end,
SatchelBlast = function() tes3.playSound{ sound = "SatchelBlast" } end,
scamp_moan = function() tes3.playSound{ sound = "scamp moan" } end,
scamp_roar = function() tes3.playSound{ sound = "scamp roar" } end,
scamp_scream = function() tes3.playSound{ sound = "scamp scream" } end,
scrib_moan = function() tes3.playSound{ sound = "scrib moan" } end,
scrib_roar = function() tes3.playSound{ sound = "scrib roar" } end,
scrib_scream = function() tes3.playSound{ sound = "scrib scream" } end,
scribLEFT = function() tes3.playSound{ sound = "scribLEFT" } end,
scribRIGHT = function() tes3.playSound{ sound = "scribRIGHT" } end,
scroll = function() tes3.playSound{ sound = "scroll" } end,
shalk_moan = function() tes3.playSound{ sound = "shalk moan" } end,
shalk_roar = function() tes3.playSound{ sound = "shalk roar" } end,
shalk_scream = function() tes3.playSound{ sound = "shalk scream" } end,
shock_area = function() tes3.playSound{ sound = "shock area" } end,
shock_bolt = function() tes3.playSound{ sound = "shock bolt" } end,
shock_cast = function() tes3.playSound{ sound = "shock cast" } end,
shock_hit = function() tes3.playSound{ sound = "shock hit" } end,
Silt_1 = function() tes3.playSound{ sound = "Silt_1" } end,
Silt_2 = function() tes3.playSound{ sound = "Silt_2" } end,
Silt_3 = function() tes3.playSound{ sound = "Silt_3" } end,
Sixth_Bell = function() tes3.playSound{ sound = "Sixth_Bell" } end,
SkaalAttackNoise = function() tes3.playSound{ sound = "SkaalAttackNoise" } end,
skeleton_moan = function() tes3.playSound{ sound = "skeleton moan" } end,
skeleton_roar = function() tes3.playSound{ sound = "skeleton roar" } end,
skeleton_scream = function() tes3.playSound{ sound = "skeleton scream" } end,
skillraise = function() tes3.playSound{ sound = "skillraise" } end,
slaughterfish_moan = function() tes3.playSound{ sound = "slaughterfish moan" } end,
slaughterfish_roar = function() tes3.playSound{ sound = "slaughterfish roar" } end,
slaughterfish_scream = function() tes3.playSound{ sound = "slaughterfish scream" } end,
sludgeworm_fall = function() tes3.playSound{ sound = "sludgeworm fall" } end,
sludgeworm_left = function() tes3.playSound{ sound = "sludgeworm left" } end,
sludgeworm_moan = function() tes3.playSound{ sound = "sludgeworm moan" } end,
sludgeworm_right = function() tes3.playSound{ sound = "sludgeworm right" } end,
sludgeworm_roar = function() tes3.playSound{ sound = "sludgeworm roar" } end,
sludgeworm_scream = function() tes3.playSound{ sound = "sludgeworm scream" } end,
SothaAmbient = function() tes3.playSound{ sound = "SothaAmbient" } end,
SothaBlade = function() tes3.playSound{ sound = "SothaBlade" } end,
SothaBladeRoll = function() tes3.playSound{ sound = "SothaBladeRoll" } end,
SothaDoorClose = function() tes3.playSound{ sound = "SothaDoorClose" } end,
SothaDoorOpen = function() tes3.playSound{ sound = "SothaDoorOpen" } end,
SothaFabMachine = function() tes3.playSound{ sound = "SothaFabMachine" } end,
SothaGear = function() tes3.playSound{ sound = "SothaGear" } end,
SothaGiantBlade = function() tes3.playSound{ sound = "SothaGiantBlade" } end,
SothaLab = function() tes3.playSound{ sound = "SothaLab" } end,
SothaLever = function() tes3.playSound{ sound = "SothaLever" } end,
SothaSpark = function() tes3.playSound{ sound = "SothaSpark" } end,
SothaSpikes = function() tes3.playSound{ sound = "SothaSpikes" } end,
Sound_Test = function() tes3.playSound{ sound = "Sound Test" } end,
Sound_Test_Loop = function() tes3.playSound{ sound = "Sound Test Loop" } end,
sound_boat_creak = function() tes3.playSound{ sound = "sound_boat_creak" } end,
Spell_Failure_Alteration = function() tes3.playSound{ sound = "Spell Failure Alteration" } end,
Spell_Failure_Conjuration = function() tes3.playSound{ sound = "Spell Failure Conjuration" } end,
Spell_Failure_Destruction = function() tes3.playSound{ sound = "Spell Failure Destruction" } end,
Spell_Failure_Illusion = function() tes3.playSound{ sound = "Spell Failure Illusion" } end,
Spell_Failure_Mysticism = function() tes3.playSound{ sound = "Spell Failure Mysticism" } end,
Spell_Failure_Restoration = function() tes3.playSound{ sound = "Spell Failure Restoration" } end,
spellmake_fail = function() tes3.playSound{ sound = "spellmake fail" } end,
spellmake_success = function() tes3.playSound{ sound = "spellmake success" } end,
spiderATTACK1 = function() tes3.playSound{ sound = "spiderATTACK1" } end,
spiderATTACK2 = function() tes3.playSound{ sound = "spiderATTACK2" } end,
spiderLEFT = function() tes3.playSound{ sound = "spiderLEFT" } end,
spiderRIGHT = function() tes3.playSound{ sound = "spiderRIGHT" } end,
Spirit_Ambient_Voices = function() tes3.playSound{ sound = "Spirit Ambient Voices" } end,
spriggan_moan = function() tes3.playSound{ sound = "spriggan moan" } end,
spriggan_resurrect = function() tes3.playSound{ sound = "spriggan resurrect" } end,
spriggan_roar = function() tes3.playSound{ sound = "spriggan roar" } end,
spriggan_scream = function() tes3.playSound{ sound = "spriggan scream" } end,
sprigganmagic = function() tes3.playSound{ sound = "sprigganmagic" } end,
Steam = function() tes3.playSound{ sound = "Steam" } end,
steamATTACK1 = function() tes3.playSound{ sound = "steamATTACK1" } end,
steamATTACK2 = function() tes3.playSound{ sound = "steamATTACK2" } end,
steamLEFT = function() tes3.playSound{ sound = "steamLEFT" } end,
steamRIGHT = function() tes3.playSound{ sound = "steamRIGHT" } end,
steamROLL = function() tes3.playSound{ sound = "steamROLL" } end,
Stone_Door_Open_1 = function() tes3.playSound{ sound = "Stone Door Open 1" } end,
StoneSound = function() tes3.playSound{ sound = "StoneSound" } end,
Swallow = function() tes3.playSound{ sound = "Swallow" } end,
swamp_1 = function() tes3.playSound{ sound = "swamp 1" } end,
swamp_2 = function() tes3.playSound{ sound = "swamp 2" } end,
swamp_3 = function() tes3.playSound{ sound = "swamp 3" } end,
Swim_Left = function() tes3.playSound{ sound = "Swim Left" } end,
Swim_Right = function() tes3.playSound{ sound = "Swim Right" } end,
SwishL = function() tes3.playSound{ sound = "SwishL" } end,
SwishM = function() tes3.playSound{ sound = "SwishM" } end,
SwishS = function() tes3.playSound{ sound = "SwishS" } end,
Thunder0 = function() tes3.playSound{ sound = "Thunder0" } end,
Thunder1 = function() tes3.playSound{ sound = "Thunder1" } end,
Thunder2 = function() tes3.playSound{ sound = "Thunder2" } end,
Thunder3 = function() tes3.playSound{ sound = "Thunder3" } end,
ThunderClap = function() tes3.playSound{ sound = "ThunderClap" } end,
Torch_Out = function() tes3.playSound{ sound = "Torch Out" } end,
Underwater = function() tes3.playSound{ sound = "Underwater" } end,
volcano_rumble = function() tes3.playSound{ sound = "volcano rumble" } end,
Water_Layer = function() tes3.playSound{ sound = "Water Layer" } end,
waterfall_small = function() tes3.playSound{ sound = "waterfall small" } end,
Weapon_Swish = function() tes3.playSound{ sound = "Weapon Swish" } end,
were_moan = function() tes3.playSound{ sound = "were moan" } end,
were_roar = function() tes3.playSound{ sound = "were roar" } end,
were_scream = function() tes3.playSound{ sound = "were scream" } end,
weregrowl = function() tes3.playSound{ sound = "weregrowl" } end,
werehowl = function() tes3.playSound{ sound = "werehowl" } end,
weresniff = function() tes3.playSound{ sound = "weresniff" } end,
wind_calm1 = function() tes3.playSound{ sound = "wind calm1" } end,
wind_calm2 = function() tes3.playSound{ sound = "wind calm2" } end,
wind_calm3 = function() tes3.playSound{ sound = "wind calm3" } end,
wind_calm4 = function() tes3.playSound{ sound = "wind calm4" } end,
wind_calm5 = function() tes3.playSound{ sound = "wind calm5" } end,
wind_des1 = function() tes3.playSound{ sound = "wind des1" } end,
wind_des2 = function() tes3.playSound{ sound = "wind des2" } end,
wind_des3 = function() tes3.playSound{ sound = "wind des3" } end,
wind_des4 = function() tes3.playSound{ sound = "wind des4" } end,
Wind_Light = function() tes3.playSound{ sound = "Wind Light" } end,
wind_low1 = function() tes3.playSound{ sound = "wind low1" } end,
wind_low2 = function() tes3.playSound{ sound = "wind low2" } end,
wind_low3 = function() tes3.playSound{ sound = "wind low3" } end,
wind_trees1 = function() tes3.playSound{ sound = "wind trees1" } end,
wind_trees2 = function() tes3.playSound{ sound = "wind trees2" } end,
wind_trees3 = function() tes3.playSound{ sound = "wind trees3" } end,
wind_trees4 = function() tes3.playSound{ sound = "wind trees4" } end,
wind_trees5 = function() tes3.playSound{ sound = "wind trees5" } end,
wind_trees6 = function() tes3.playSound{ sound = "wind trees6" } end,
wind_trees7 = function() tes3.playSound{ sound = "wind trees7" } end,
WindBag = function() tes3.playSound{ sound = "WindBag" } end,
winged_twil_moan = function() tes3.playSound{ sound = "winged twil moan" } end,
winged_twil_roar = function() tes3.playSound{ sound = "winged twil roar" } end,
winged_twil_scream = function() tes3.playSound{ sound = "winged twil scream" } end,
wolf_moan = function() tes3.playSound{ sound = "wolf moan" } end,
wolf_roar = function() tes3.playSound{ sound = "wolf roar" } end,
wolf_scream = function() tes3.playSound{ sound = "wolf scream" } end,
WolfActivator1 = function() tes3.playSound{ sound = "WolfActivator1" } end,
WolfContainer1 = function() tes3.playSound{ sound = "WolfContainer1" } end,
WolfContainer2 = function() tes3.playSound{ sound = "WolfContainer2" } end,
WolfCreature1 = function() tes3.playSound{ sound = "WolfCreature1" } end,
WolfCreature2 = function() tes3.playSound{ sound = "WolfCreature2" } end,
WolfCreature3 = function() tes3.playSound{ sound = "WolfCreature3" } end,
WolfEquip1 = function() tes3.playSound{ sound = "WolfEquip1" } end,
WolfEquip2 = function() tes3.playSound{ sound = "WolfEquip2" } end,
WolfEquip3 = function() tes3.playSound{ sound = "WolfEquip3" } end,
WolfEquip4 = function() tes3.playSound{ sound = "WolfEquip4" } end,
WolfEquip5 = function() tes3.playSound{ sound = "WolfEquip5" } end,
WolfHit1 = function() tes3.playSound{ sound = "WolfHit1" } end,
WolfHit2 = function() tes3.playSound{ sound = "WolfHit2" } end,
WolfHit3 = function() tes3.playSound{ sound = "WolfHit3" } end,
wolfhowl = function() tes3.playSound{ sound = "wolfhowl" } end,
WolfItem1 = function() tes3.playSound{ sound = "WolfItem1" } end,
WolfItem2 = function() tes3.playSound{ sound = "WolfItem2" } end,
WolfItem3 = function() tes3.playSound{ sound = "WolfItem3" } end,
WolfNPC1 = function() tes3.playSound{ sound = "WolfNPC1" } end,
WolfNPC2 = function() tes3.playSound{ sound = "WolfNPC2" } end,
WolfNPC3 = function() tes3.playSound{ sound = "WolfNPC3" } end,
WolfRun = function() tes3.playSound{ sound = "WolfRun" } end,
wolfskel_moan = function() tes3.playSound{ sound = "wolfskel moan" } end,
wolfskel_roar = function() tes3.playSound{ sound = "wolfskel roar" } end,
wolfskel_scream = function() tes3.playSound{ sound = "wolfskel scream" } end,
wolfskhowl = function() tes3.playSound{ sound = "wolfskhowl" } end,
WolfSwing = function() tes3.playSound{ sound = "WolfSwing" } end,
WolfSwing1 = function() tes3.playSound{ sound = "WolfSwing1" } end,
WolfSwing2 = function() tes3.playSound{ sound = "WolfSwing2" } end,
WolfSwing3 = function() tes3.playSound{ sound = "WolfSwing3" } end,
Wooden_Door_Close_1 = function() tes3.playSound{ sound = "Wooden Door Close 1" } end,
Wooden_Door_Open_1 = function() tes3.playSound{ sound = "Wooden Door Open 1" } end,
}

return playSound