return {
"ko_fae_bow",
"ko_fae_bow_arrows",
"ko_fae_blade",
"ko_butterfly arrow",
"ko_butterfly arrowau",
"ko_butterfly arrowwi",
"ko_fae_bow2",
"ko_fae_bow_arrows_2",
"staff_magnus_unique_",
"ko_staff",
"ko_redglasslongswod",
"ko_redglass war axe",
"ko_glass dagger",
"ko_redglass throwing star",
"ko_redglass claymore",
"ko_redglass throwing knife",
"ko_redglass halberd",
"ko_redglass staff",
"ko_redglass arrow",
}