---@meta AdvancedWorldMap.Interface

---@class AdvancedWorldMap.DataHandler.EntranceData
---@field pos any position
---@field cId string cell id
---@field isEx boolean is in exterior cell
---@field isLEx boolean is destination in like exterior cell
---@field dCId string destination cell id
---@field dPos any destination position
---@field isDEx boolean is destination cell exterior
---@field isDLEx boolean is destination cell like exterior
---@field name string destination cell name
---@field fName string destination cell full name
---@field dHash string door hash

---@class AdvancedWorldMap.Interface.UIElements
---@field scrollBox fun(params: any): Layout creates a scroll box
---@field button fun(params: any): Layout creates a button
---@field borders fun(): Layout[] creates borders
---@field checkbox fun(params: any): Layout creates a checkbox
---@field interval fun(width: number, height: number): Layout creates an interval
---@field tooltip table module for creating tooltips

---@class AdvancedWorldMap.Interface
---@field version integer version of the interface
---@field events AdvancedWorldMap.Event event system
---@field openMapMenu fun(inMenuMode: boolean): AdvancedWorldMap.Menu.Map opens the world map menu
---@field closeMapMenu fun() closes the world map menu
---@field toggleMapMenu fun() toggles the world map menu
---@field getMapMenu fun() : AdvancedWorldMap.Menu.Map gets the world map menu
---@field getConfig fun() : table gets the current configuration
---@field setConfigValue fun(path: string, value: any) sets a configuration value at the given path. Like setConfigValue("main.updateFrequency", 25)
---@field isDiscovered fun(cellId: string) : boolean checks if the cell with the given ID is discovered
---@field isVisited fun(cellId: string) : number? checks if the cell with the given ID is visited. Returns timestamp or nil
---@field getCellNameById fun(cellId: string) : string? gets the cell name by its ID
---@field getExteriorCellName fun(pos: any) : string? gets the exterior cell name by position
---@field getEntranceMarkerData fun(cellId: string) : table<string, AdvancedWorldMap.DataHandler.EntranceData>? gets the entrance marker data for the given cell ID. Returns a table where keys are door hashes and values are EntranceData
---@field uiElements AdvancedWorldMap.Interface.UIElements