return {
  "stone door open 1",
  "disarm trap",
  "light armor hit",
  "heavy armor hit",
  "health damage",
  "hand to hand hit",
  "medium armor hit",
  "pack",
  "body fall small",
  "body fall medium",
  "body fall large",
  "thunderclap",
  "wooden door open 1",
  "wooden door close 1",
  "open lock",
  "disarm trap fail",
  "open lock fail",
  "thunder3",
  "sound test",
  "sound test loop",
  "cave wind",
  "cave drip",
  "underwater",
  "fire",
  "flag",
  "boat hull",
  "rain",
  "ashstorm",
  "wind light",
  "door creaky open",
  "door creaky close",
  "door heavy open",
  "door heavy close",
  "door metal open",
  "door metal close",
  "door stone close",
  "door latched one open",
  "door latched two open",
  "door latched one close",
  "door latched two close",
  "heart",
  "menu click",
  "menu size",
  "item apparatus up",
  "item apparatus down",
  "item armor light up",
  "item armor light down",
  "item armor medium up",
  "item armor medium down",
  "item bodypart up",
  "item bodypart down",
  "item book up",
  "item book down",
  "item clothes up",
  "item clothes down",
  "item ingredient up",
  "item ingredient down",
  "item lockpick up",
  "item lockpick down",
  "item misc up",
  "item misc down",
  "item probe up",
  "item probe down",
  "item repair up",
  "item repair down",
  "item ammo up",
  "item ammo down",
  "item gold up",
  "item gold down",
  "footwaterleft",
  "footwaterright",
  "default roar",
  "default scream",
  "default moan",
  "swim left",
  "swim right",
  "illusion bolt",
  "illusion cast",
  "illusion hit",
  "mysticism bolt",
  "mysticism cast",
  "mysticism hit",
  "restoration bolt",
  "restoration cast",
  "restoration hit",
  "alteration bolt",
  "alteration cast",
  "alteration hit",
  "conjuration bolt",
  "conjuration cast",
  "conjuration hit",
  "destruction bolt",
  "destruction cast",
  "destruction hit",
  "conjuration area",
  "alteration area",
  "destruction area",
  "illusion area",
  "mysticism area",
  "restoration area",
  "blackoutin",
  "leftl",
  "rights",
  "rightl",
  "rightm",
  "footbareleft",
  "footbareright",
  "footlightleft",
  "footlightright",
  "footmedleft",
  "footmedright",
  "footheavyleft",
  "footheavyright",
  "spell failure alteration",
  "spell failure conjuration",
  "spell failure destruction",
  "spell failure illusion",
  "spell failure mysticism",
  "spell failure restoration",
  "repair",
  "power light",
  "bubbles",
  "creeky wood",
  "steam",
  "machinery",
  "ambient factory ruins",
  "spirit ambient voices",
  "dwemer door open",
  "dwemer door close",
  "boat docked",
  "boat creak",
  "sound_boat_creak",
  "daedric chant",
  "crystal ringing",
  "haunted",
  "dock creak",
  "skillraise",
  "lockeddoor",
  "lockedchest",
  "alitmoan",
  "alitroar",
  "alitscrm",
  "bonewalkermoan",
  "bonewalkerroar",
  "bonewalkerscrm",
  "corpuslamemoan",
  "corpuslameroar",
  "corpuslamescrm",
  "corpus stalker moan",
  "corpus stalker roar",
  "corpus stalker scream",
  "nix hound moan",
  "nix hound roar",
  "nix hound scream",
  "kagouti moan",
  "kagouti roar",
  "kagouti scream",
  "cliff racer moan",
  "cliff racer roar",
  "cliff racer scream",
  "crossbowpull",
  "bowpull",
  "bowshoot",
  "door stone open",
  "torch out",
  "swallow",
  "drink",
  "flies",
  "thunder0",
  "thunder1",
  "thunder2",
  "silt_3",
  "cent spider moan",
  "cent spider roar",
  "cent spider scream",
  "cent steam moan",
  "cent steam roar",
  "cent steam scream",
  "cent sphere moan",
  "cent sphere roar",
  "cent sphere scream",
  "scamp moan",
  "scamp roar",
  "scamp scream",
  "winged twil moan",
  "winged twil roar",
  "winged twil scream",
  "gold saint moan",
  "gold saint roar",
  "gold saint scream",
  "item weapon bow up",
  "item weapon bow down",
  "item weapon crossbow up",
  "item weapon crossbow down",
  "item weapon longblade up",
  "item weapon longblade down",
  "item weapon shortblade up",
  "item weapon shortblade down",
  "item weapon spear up",
  "item weapon spear down",
  "item weapon blunt up",
  "item weapon blunt down",
  "crossbowshoot",
  "silt_1",
  "silt_2",
  "sixth_bell",
  "atroflame moan",
  "atroflame roar",
  "atroflame scream",
  "atrofrost moan",
  "atrofrost roar",
  "atrofrost scream",
  "atrostorm moan",
  "atrostorm roar",
  "atrostorm scream",
  "clannfear moan",
  "clannfear roar",
  "clannfear scream",
  "daedroth moan",
  "daedroth roar",
  "daedroth scream",
  "guar moan",
  "guar roar",
  "guar scream",
  "slaughterfish moan",
  "slaughterfish roar",
  "slaughterfish scream",
  "mudcrab moan",
  "mudcrab roar",
  "mudcrab scream",
  "ogrim moan",
  "ogrim roar",
  "ogrim scream",
  "shalk moan",
  "shalk roar",
  "shalk scream",
  "dreugh moan",
  "dreugh roar",
  "dreugh scream",
  "bonelord moan",
  "bonelord roar",
  "bonelord scream",
  "skeleton moan",
  "skeleton roar",
  "skeleton scream",
  "dremora moan",
  "dremora roar",
  "dremora scream",
  "ash vampire moan",
  "ash vampire roar",
  "ash vampire scream",
  "ash ghoul moan",
  "ash ghoul scream",
  "ash zombie moan",
  "ash zombie roar",
  "ash zombie scream",
  "ash slave moan",
  "ash slave roar",
  "ash slave scream",
  "ancestor ghost moan",
  "ancestor ghost roar",
  "ancestor ghost scream",
  "ash ghoul roar",
  "bonewalkerwar moan",
  "bonewalkerwar roar",
  "bonewalkerwar scream",
  "kwamf moan",
  "kwamf roar",
  "kwamf scream",
  "kwamwk moan",
  "kwamwk roar",
  "kwamwk scream",
  "kwamwr moan",
  "kwamwr roar",
  "kwamwr scream",
  "kwamq moan",
  "kwamq roar",
  "kwamq scream",
  "rat moan",
  "rat roar",
  "rat scream",
  "netchbul moan",
  "netchbul roar",
  "netchbul scream",
  "netchbet moan",
  "netchbet roar",
  "netchbet scream",
  "scrib moan",
  "scrib roar",
  "scrib scream",
  "book open",
  "book close",
  "book page",
  "book page2",
  "bell1",
  "bell2",
  "bell3",
  "bell4",
  "bell5",
  "bell6",
  "mud bubbles",
  "forcefield",
  "chimes wood",
  "waterfall small",
  "lefts",
  "leftm",
  "hand to hand hit 2",
  "frost area",
  "ghostgate sound",
  "cave_waterfall",
  "corpdrag",
  "steamleft",
  "steamright",
  "spiderattack1",
  "spiderattack2",
  "steamattack1",
  "steamattack2",
  "animallargeleft",
  "animallargeright",
  "animalsmallleft",
  "animalsmallright",
  "scribright",
  "scribleft",
  "steamroll",
  "spiderleft",
  "spiderright",
  "miss",
  "critical damage",
  "drown",
  "endboom1",
  "endboom2",
  "endboom3",
  "endboom4",
  "weapon swish",
  "water layer",
  "drowning damage",
  "chest open",
  "chest close",
  "scroll",
  "kwama forager slither",
  "rain heavy",
  "swishs",
  "swishm",
  "swishl",
  "lava layer",
  "item armor heavy up",
  "item armor heavy down",
  "potion success",
  "potion fail",
  "enchant success",
  "enchant fail",
  "spellmake success",
  "spellmake fail",
  "dwarven ghost moan",
  "dwarven ghost roar",
  "dwarven ghost scream",
  "howl1",
  "howl2",
  "howl3",
  "howl4",
  "howl5",
  "howl6",
  "howl7",
  "howl8",
  "rocks1",
  "rocks2",
  "rocks3",
  "rocks4",
  "rocks5",
  "rocks6",
  "rocks7",
  "rocks8",
  "rumble1",
  "rumble2",
  "rumble3",
  "rumble4",
  "wind calm1",
  "wind calm2",
  "wind calm3",
  "wind calm4",
  "wind calm5",
  "wind des1",
  "wind des2",
  "wind des3",
  "wind des4",
  "wind low1",
  "wind low2",
  "wind low3",
  "wind trees1",
  "wind trees2",
  "wind trees3",
  "wind trees4",
  "wind trees5",
  "wind trees6",
  "wind trees7",
  "repair fail",
  "dagoth ur moan",
  "dagoth ur scream",
  "heartsunder",
  "hearthit1",
  "hearthit2",
  "hearthit3",
  "hearthit4",
  "heartdead",
  "fire 40",
  "fire 50",
  "power light 50",
  "kwamaf left",
  "kwamaf right",
  "item ring up",
  "item ring down",
  "frost_cast",
  "frost_bolt",
  "frost_hit",
  "shock area",
  "shock bolt",
  "shock cast",
  "shock hit",
  "item potion up",
  "item potion down",
  "volcano rumble",
  "swamp 1",
  "swamp 2",
  "swamp 3",
  "defaultland",
  "defaultlandwater",
  "ropebridge",
  "endrumble",
  "magic sound",
  "cent steam fall",
  "ashstorm",
  "drgr moan",
  "drgr roar",
  "drgr scream",
  "hrkr moan",
  "hrkr roar",
  "hrkr scream",
  "wolf moan",
  "wolf roar",
  "wolf scream",
  "bear moan",
  "bear roar",
  "bear scream",
  "boar moan",
  "boar roar",
  "boar scream",
  "frgiant moan",
  "frgiant roar",
  "frgiant scream",
  "hirc moan",
  "hirc roar",
  "hirc scream",
  "riek moan",
  "riek roar",
  "riek scream",
  "rmnt moan",
  "rmnt roar",
  "rmnt scream",
  "blight",
  "bm blizzard",
  "were moan",
  "were roar",
  "were scream",
  "spriggan moan",
  "spriggan roar",
  "spriggan scream",
  "gren roar",
  "gren scream",
  "gren moan",
  "bm wilderness",
  "bm wilderness2",
  "bm wilderness3",
  "bm sun",
  "bm wind",
  "wolfskel roar",
  "wolfskel moan",
  "wolfskel scream",
  "spriggan resurrect",
  "bearsniff",
  "boarsniff",
  "hrkrbellow",
  "sprigganmagic",
  "weregrowl",
  "werehowl",
  "weresniff",
  "wolfhowl",
  "wolfskhowl",
  "bm_ice_sheet",
  "greneat",
  "ice troll roar",
  "ice troll moan",
  "ice troll scream",
  "bm big fire",
  "bm pipe small",
  "bm pipe medium",
  "bm pipe large",
  "bm nord attack",
  "wolfequip1",
  "wolfequip2",
  "wolfequip3",
  "wolfequip4",
  "wolfequip5",
  "wolfswing",
  "wolfswing1",
  "wolfswing2",
  "wolfswing3",
  "wolfhit1",
  "wolfhit2",
  "wolfhit3",
  "wolfcontainer1",
  "wolfcontainer2",
  "wolfnpc1",
  "wolfnpc2",
  "wolfnpc3",
  "wolfcreature1",
  "wolfcreature2",
  "wolfcreature3",
  "wolfactivator1",
  "wolfitem1",
  "wolfitem2",
  "wolfitem3",
  "wolfrun",
  "frgtleft",
  "frgtright",
  "hrkleft",
  "hrkright",
  "skaalattacknoise",
  "windbag",
  "stonesound",
  "bm nord attackf",
  "cave wind",
  "cave drip",
  "bubbles",
  "machinery",
  "ambient factory ruins",
  "crowd booing",
  "goblin moan",
  "goblin roar",
  "goblin scream",
  "goblin large moan",
  "goblin large roar",
  "goblin large scream",
  "lich lord moan",
  "lich lord roar",
  "lich lord scream",
  "cent proj moan",
  "cent proj roar",
  "cent proj scream",
  "cent proj shoot",
  "sludgeworm moan",
  "sludgeworm roar",
  "sludgeworm scream",
  "sludgeworm left",
  "sludgeworm right",
  "sludgeworm fall",
  "sothadooropen",
  "sothadoorclose",
  "sothalever",
  "sothablade",
  "sothaspikes",
  "sothagear",
  "sothaspark",
  "sothagiantblade",
  "sothafabmachine",
  "rock and roll",
  "power hummer",
  "sothaambient",
  "fabvermleft",
  "fabvermright",
  "fabvermmoan",
  "fabvermroar",
  "fabvermscream",
  "fabhulkmoan",
  "fabhulkroar",
  "fabhulkscream",
  "fabbossleft",
  "fabbossright",
  "cavein",
  "satchelblast",
  "dwemer fan",
  "sothalab",
  "fabbossdead",
  "fabbosshit",
  "fabbossroar",
  "fabbossalive",
  "mourndayamb",
  "mournnightamb",
  "mourntempleamb",
  "mournspray",
  "mourngates",
  "mourngatesclose",
  "crowdboo",
  "dwe_waterfall",
  "sothabladeroll",
  "oil bubbly",
  "fabbossclank",
  "fabbosswhir",
  "fabbossgyro",
  "gate large locked",
  "fabhulkleft",
  "fabhulkright",
  "alma_hit0",
  "alma_hit1",
  "alma_hit2",
  "alma_att0",
  "alma_att1",
  "alma_att2",
}