local soundBank =      {
  id = 'tr_ost_cell_vanilla_caves',
  interiorOnly = true,
  cellNamePatterns = {
    'Cave',
	'Tunnel',
	'Mine',
	'Eggmine',
	'Cavern',
	'Caverns',
	'Grotto',
	'Abanabi',
    'Abernanit',
    'Adanumuran',
    'Addamasartus',
    'Aharnabi',
    'Aharunartus',
    'Ahinipalit',
    'Ainat',
    'Ansi',
    'Ashanammu',
    'Ashinabi',
	'Ashirbadon',
    'Ashir%-Dan',
	'Assarnud',
    'Assu',
	'Assumanu',
    'Beshara',
    'Dubdilla',
    'Dun%-Ahhe',
    'Habinbaes',
	'Hinnabi',
    'Ibar%-Dad',
    'Kora%-Dur',
    'Kudanat',
    'Kumarahaz',
    'Kunirai',
    'Maba%-Ilu',
    'Mallapi',
    'Mannammu',
    'Masseranit',
    'Mat',
    'Milk',
    'Minabi',
    'Nallit',
	'Nammu',
    'Nissintu',
    'Nund',
    'Odaishah',
    'Odibaal',
    'Odirnamat',
    'Palansour',
    'Panat',
    'Pinsun',
    'Pulk',
    'Punabi',
    'Punammu',
    'Punsabanit',
    'Sanabi',
    'Sargon',
    'Saturan',
	'Sha%-Adnius',
    'Shal',
    'Shallit',
    'Shurinbaal',
    'Shushan',
    'Shushishi',
    'Sinsibadon',
    'Sud',
    'Surirulk',
    'Tin%-Ahhe',
    'Tukushapal',
    'Ulummusa',
    'Urshilaku',
    'Yakanalit',
    'Yasamsi',
    'Yesamsi',
    'Zainsipilu',
    'Zaintirari',
    'Zanabi',
    'Zebabi',
    'Zenarbael'
  },
  tracks = {
    {
      path='Music/MS/interior/TR cave/Cave 1.mp3',
      length=181
    },
    {
      path='Music/MS/interior/TR cave/Cave 2.mp3',
      length=121
    },
  }
}

return soundBank
