local I = require('openmw.interfaces')
local shared   = require('scripts.gko_shared')
local DEFAULTS = shared.DEFAULTS

I.Settings.registerPage {
    key         = 'GothicKnockout',
    l10n        = 'GothicKnockout',
    name        = 'page_name',
    description = 'page_desc',
}

I.Settings.registerGroup {
    key              = 'SettingsGKD',
    page             = 'GothicKnockout',
    l10n             = 'GothicKnockout',
    name             = 'settings_group_name',
    permanentStorage = true,
    order            = 1,
    settings = {
        {
            key         = 'MOD_ENABLED',
            name        = 'mod_enabled_name',
            description = 'mod_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.MOD_ENABLED,
        },
        {
            key         = 'KNOCKDOWN_DURATION',
            name        = 'knockdown_duration_name',
            description = 'knockdown_duration_desc',
            renderer    = 'number',
            default     = DEFAULTS.KNOCKDOWN_DURATION,
            argument    = { integer = true, min = 6, max = 30 },
        },
        {
            key         = 'DROP_WEAPON',
            name        = 'drop_weapon_name',
            description = 'drop_weapon_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.DROP_WEAPON,
        },
        {
            key         = 'PICKUP_DELAY',
            name        = 'pickup_delay_name',
            description = 'pickup_delay_desc',
            renderer    = 'number',
            default     = DEFAULTS.PICKUP_DELAY,
            argument    = { min = 0.5, max = 10.0 },
        },
        {
            key         = 'SET_FIGHT',
            name        = 'set_fight_name',
            description = 'set_fight_desc',
            renderer    = 'number',
            default     = DEFAULTS.SET_FIGHT,
            argument    = { integer = true, min = 0, max = 100 },
        },
        {
            key         = 'SET_DISPOSITION',
            name        = 'set_disposition_name',
            description = 'set_disposition_desc',
            renderer    = 'number',
            default     = DEFAULTS.SET_DISPOSITION,
            argument    = { integer = true, min = 0, max = 100 },
        },
        {
            key         = 'HP_AFTER_KNOCKDOWN',
            name        = 'hp_after_knockdown_name',
            description = 'hp_after_knockdown_desc',
            renderer    = 'number',
            default     = DEFAULTS.HP_AFTER_KNOCKDOWN,
            argument    = { min = 0.05, max = 1.0 },
        },
        {
            key         = 'BLUNT_ONLY',
            name        = 'blunt_only_name',
            description = 'blunt_only_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.BLUNT_ONLY,
        },
        {
            key         = 'PLAYER_KNOCKDOWN',
            name        = 'player_knockdown_name',
            description = 'player_knockdown_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.PLAYER_KNOCKDOWN,
        },
        {
            key         = 'NPC_LOOT_PLAYER',
            name        = 'npc_loot_player_name',
            description = 'npc_loot_player_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.NPC_LOOT_PLAYER,
        },
        {
            key         = 'LOOT_MIN_PERCENT',
            name        = 'loot_min_percent_name',
            description = 'loot_min_percent_desc',
            renderer    = 'number',
            default     = DEFAULTS.LOOT_MIN_PERCENT,
            argument    = { integer = true, min = 10, max = 100 },
        },
        {
            key         = 'FIGHT_THRESHOLD_ENABLED',
            name        = 'fight_threshold_enabled_name',
            description = 'fight_threshold_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.FIGHT_THRESHOLD_ENABLED,
        },
        {
            key         = 'FIGHT_THRESHOLD',
            name        = 'fight_threshold_name',
            description = 'fight_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.FIGHT_THRESHOLD,
            argument    = { integer = true, min = 70, max = 100 },
        },
        {
            key         = 'PLAYER_FIGHT_THRESHOLD_ENABLED',
            name        = 'player_fight_threshold_enabled_name',
            description = 'player_fight_threshold_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.PLAYER_FIGHT_THRESHOLD_ENABLED,
        },
        {
            key         = 'PLAYER_FIGHT_THRESHOLD',
            name        = 'player_fight_threshold_name',
            description = 'player_fight_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.PLAYER_FIGHT_THRESHOLD,
            argument    = { integer = true, min = 70, max = 100 },
        },
        {
            key         = 'BOUNTY_THRESHOLD_ENABLED',
            name        = 'bounty_threshold_enabled_name',
            description = 'bounty_threshold_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.BOUNTY_THRESHOLD_ENABLED,
        },
        {
            key         = 'BOUNTY_THRESHOLD',
            name        = 'bounty_threshold_name',
            description = 'bounty_threshold_desc',
            renderer    = 'number',
            default     = DEFAULTS.BOUNTY_THRESHOLD,
            argument    = { integer = true, min = 1000, max = 50000 },
        },
        {
            key         = 'BH_COMPAT',
            name        = 'bh_compat_name',
            description = 'bh_compat_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.BH_COMPAT,
        },
    }
}