local runtime_stats = {}

local counters = {}

local function asNumber(value)
    return tonumber(value) or 0
end

function runtime_stats.inc(name, amount)
    if type(name) ~= "string" or name == "" then
        return 0
    end
    local delta = amount == nil and 1 or asNumber(amount)
    counters[name] = asNumber(counters[name]) + delta
    return counters[name]
end

function runtime_stats.max(name, value)
    if type(name) ~= "string" or name == "" then
        return 0
    end
    local next_value = asNumber(value)
    local current = asNumber(counters[name])
    if next_value > current then
        counters[name] = next_value
    elseif counters[name] == nil then
        counters[name] = current
    end
    return counters[name]
end

function runtime_stats.get(name)
    return asNumber(counters[name])
end

function runtime_stats.snapshot()
    local out = {}
    for name, value in pairs(counters) do
        out[name] = value
    end
    return out
end

function runtime_stats.reset()
    counters = {}
end

local function g(name)
    return runtime_stats.get(name)
end

function runtime_stats.summaryLines()
    return {
        string.format(
            "dispatch attempts=%d dry_run=%d qualified=%d rejected=%d ok=%d failed=%d fallback=%d suppressed=%d blocked=%d duplicate_suppressed=%d",
            g("live_2_2c_attempts"),
            g("live_2_2c_dry_run_attempts"),
            g("live_2_2c_qualified"),
            g("live_2_2c_rejected"),
            g("live_2_2c_dispatch_ok"),
            g("live_2_2c_dispatch_failed"),
            g("legacy_fallback_used"),
            g("compiled_dispatch_suppressed"),
            g("fallback_after_enqueue_blocked"),
            g("duplicate_cast_or_dispatch_suppressed")
        ),
        string.format(
            "plans compiled=%d reused=%d helpers attached=%d created=%d reused=%d attach_failed=%d",
            g("plans_compiled"),
            g("plans_reused"),
            g("helper_records_attached"),
            g("helper_records_created"),
            g("helper_records_reused"),
            g("helper_records_attach_failed")
        ),
        string.format(
            "jobs enqueued=%d live_enqueued=%d processed=%d live_processed=%d failed=%d live_failed=%d expired=%d skipped_not_ready=%d max_queue=%d drained=%d",
            g("jobs_enqueued"),
            g("live_helper_jobs_enqueued"),
            g("jobs_processed"),
            g("live_helper_jobs_processed"),
            g("jobs_failed"),
            g("live_helper_jobs_failed"),
            g("jobs_expired"),
            g("jobs_skipped_not_ready"),
            g("max_queue_depth"),
            g("queue_drained_observed")
        ),
        string.format(
            "chaos_budget default=%d chaos=%d cap_reject=%d projectile_reject=%d job_reject=%d depth_reject=%d queue_reject=%d fanout_reject=%d launch_density_throttle=%d launch_density_burst=%d high_fanout_smoke=%d max_jobs=%d max_queue=%d max_projectiles=%d max_live_launches_per_tick=%d max_live_launch_initial_burst=%d",
            g("chaos_budget_profile_default"),
            g("chaos_budget_profile_chaos"),
            g("chaos_budget_cap_reject"),
            g("chaos_budget_projectile_cap_reject"),
            g("chaos_budget_job_cap_reject"),
            g("chaos_budget_depth_cap_reject"),
            g("chaos_budget_queue_cap_reject"),
            g("chaos_budget_fanout_cap_reject"),
            g("chaos_budget_launch_density_throttle"),
            g("chaos_budget_launch_density_initial_burst"),
            g("chaos_budget_high_fanout_smoke"),
            g("chaos_budget_max_jobs_observed"),
            g("chaos_budget_max_queue_observed"),
            g("chaos_budget_max_projectiles_observed"),
            g("chaos_budget_max_live_launches_per_tick_observed"),
            g("chaos_budget_max_live_launches_initial_burst_observed")
        ),
        string.format(
            "sfp launch attempts=%d ok=%d failed=%d missing_interface=%d projectile_id=%d projectile_missing=%d",
            g("sfp_launch_attempts"),
            g("sfp_launch_ok"),
            g("sfp_launch_failed"),
            g("sfp_launch_missing_interface"),
            g("sfp_projectile_id_returned"),
            g("sfp_projectile_id_missing")
        ),
        string.format(
            "sfp adapter launch calls=%d ok=%d failed=%d detonate calls=%d ok=%d failed=%d missing_detonate=%d cancel calls=%d ok=%d failed=%d missing_cancel=%d area_vfx=%d area_scale=%d exclude_target=%d spawn_offset=%d max_lifetime=%d force_vec=%d mute_cast_glow=%d",
            g("sfp_adapter_launch_calls"),
            g("sfp_adapter_launch_ok"),
            g("sfp_adapter_launch_failed"),
            g("sfp_adapter_detonate_calls"),
            g("sfp_adapter_detonate_ok"),
            g("sfp_adapter_detonate_failed"),
            g("sfp_adapter_missing_detonate"),
            g("sfp_adapter_cancel_calls"),
            g("sfp_adapter_cancel_ok"),
            g("sfp_adapter_cancel_failed"),
            g("sfp_adapter_missing_cancel"),
            g("sfp_adapter_area_vfx_forwarded"),
            g("sfp_adapter_area_vfx_scale_forwarded"),
            g("sfp_adapter_exclude_target_forwarded"),
            g("sfp_adapter_spawn_offset_forwarded"),
            g("sfp_adapter_max_lifetime_forwarded"),
            g("sfp_adapter_force_vec_forwarded"),
            g("sfp_adapter_mute_cast_glow_forwarded")
        ),
        string.format(
            "hits seen=%d userData=%d spellIdFallback=%d unresolved=%d mismatch=%d live=%d dev=%d legacy=%d",
            g("hits_seen"),
            g("hits_userdata_routed"),
            g("hits_spellid_fallback_routed"),
            g("hits_unresolved"),
            g("hits_userdata_mismatch"),
            g("hits_live_helper_seen"),
            g("hits_dev_helper_seen"),
            g("hits_legacy_seen")
        ),
        string.format(
            "cast_ids created=%d missing=%d reused_unexpected=%d compiled_ok=%d",
            g("cast_ids_created"),
            g("cast_ids_missing"),
            g("cast_ids_reused_unexpectedly"),
            g("compiled_dispatch_ok")
        ),
        string.format(
            "multicast attempts=%d qualified=%d rejected=%d planned=%d jobs=%d cap_reject=%d payload_reject=%d unsupported_reject=%d",
            g("live_multicast_attempts"),
            g("live_multicast_qualified"),
            g("live_multicast_rejected"),
            g("live_multicast_emissions_planned"),
            g("live_multicast_jobs_enqueued"),
            g("live_multicast_cap_rejections"),
            g("live_multicast_payload_rejections"),
            g("live_multicast_unsupported_opcode_rejections")
        ),
        string.format(
            "spread attempts=%d qualified=%d rejected=%d planned=%d burst attempts=%d qualified=%d rejected=%d planned=%d pattern_jobs=%d pattern_failed=%d payload_reject=%d unsupported_reject=%d",
            g("live_spread_attempts"),
            g("live_spread_qualified"),
            g("live_spread_rejected"),
            g("live_spread_emissions_planned"),
            g("live_burst_attempts"),
            g("live_burst_qualified"),
            g("live_burst_rejected"),
            g("live_burst_emissions_planned"),
            g("live_pattern_direction_jobs"),
            g("live_pattern_direction_failed"),
            g("live_pattern_payload_rejections"),
            g("live_pattern_unsupported_opcode_rejections")
        ),
        string.format(
            "trigger attempts=%d qualified=%d rejected=%d disabled=%d source_jobs=%d source_hits=%d payload_jobs=%d payload_processed=%d payload_ok=%d payload_failed=%d duplicate_suppressed=%d depth_reject=%d payload_missing=%d route_failed=%d post_hit_smoke=%d",
            g("live_trigger_attempts"),
            g("live_trigger_qualified"),
            g("live_trigger_rejected"),
            g("live_trigger_disabled_rejections"),
            g("live_trigger_source_jobs_enqueued"),
            g("live_trigger_source_hits"),
            g("live_trigger_payload_jobs_enqueued"),
            g("live_trigger_payload_jobs_processed"),
            g("live_trigger_payload_launch_ok"),
            g("live_trigger_payload_launch_failed"),
            g("live_trigger_duplicate_hits_suppressed"),
            g("live_trigger_depth_rejections"),
            g("live_trigger_payload_missing"),
            g("live_trigger_payload_route_failed"),
            g("live_trigger_post_hit_smoke_observed")
        ),
        string.format(
            "timer attempts=%d qualified=%d rejected=%d disabled=%d source_jobs=%d wait_jobs=%d wait_processed=%d wait_not_ready=%d wait_expired=%d payload_jobs=%d payload_processed=%d payload_ok=%d payload_failed=%d duplicate_suppressed=%d async_scheduled=%d async_callback=%d async_missing=%d async_enqueued=%d async_payload_ok=%d async_pending=%d async_cleared=%d async_dup=%d depth_reject=%d payload_missing=%d route_failed=%d delay_invalid=%d delay_capped=%d real_delay_attempts=%d real_matured=%d real_payload_ok=%d real_delay_smoke=%d real_smoke_scheduled=%d real_smoke_pending=%d real_smoke_callback_ok=%d immediate_blocked=%d source_detonation_checked=%d source_detonation_attempts=%d source_detonation_ok=%d source_detonation_failed=%d source_detonation_skipped=%d source_cancel_ok=%d source_cancel_failed=%d source_detonation_blocked=%d",
            g("live_timer_attempts"),
            g("live_timer_qualified"),
            g("live_timer_rejected"),
            g("live_timer_disabled_rejections"),
            g("live_timer_source_jobs_enqueued"),
            g("live_timer_wait_jobs_enqueued"),
            g("live_timer_wait_jobs_processed"),
            g("live_timer_wait_jobs_not_ready"),
            g("live_timer_wait_jobs_expired"),
            g("live_timer_payload_jobs_enqueued"),
            g("live_timer_payload_jobs_processed"),
            g("live_timer_payload_launch_ok"),
            g("live_timer_payload_launch_failed"),
            g("live_timer_duplicate_schedules_suppressed"),
            g("live_timer_async_scheduled"),
            g("live_timer_async_callback_seen"),
            g("live_timer_async_callback_missing"),
            g("live_timer_async_payload_enqueued"),
            g("live_timer_async_payload_ok"),
            g("live_timer_async_pending"),
            g("live_timer_async_pending_cleared"),
            g("live_timer_async_duplicate_suppressed"),
            g("live_timer_depth_rejections"),
            g("live_timer_payload_missing"),
            g("live_timer_payload_route_failed"),
            g("live_timer_delay_invalid"),
            g("live_timer_delay_capped"),
            g("live_timer_real_delay_attempts"),
            g("live_timer_real_delay_matured"),
            g("live_timer_real_delay_payload_ok"),
            g("live_timer_real_delay_smoke_observed"),
            g("live_timer_real_delay_smoke_scheduled"),
            g("live_timer_real_delay_smoke_pending"),
            g("live_timer_real_delay_smoke_callback_ok"),
            g("live_timer_immediate_payload_blocked"),
            g("timer_source_detonation_checked"),
            g("timer_source_detonation_attempts"),
            g("timer_source_detonation_ok"),
            g("timer_source_detonation_failed"),
            g("timer_source_detonation_skipped"),
            g("timer_source_cancel_ok"),
            g("timer_source_cancel_failed"),
            g("timer_source_detonation_blocked")
        ),
        string.format(
            "bounce attempts=%d qualified=%d rejected=%d disabled=%d trigger_qualified=%d chain_payload_qualified=%d source_jobs=%d events=%d source_detonate_attempts=%d source_detonate_ok=%d source_detonate_failed=%d trigger_payloads=%d chain_payload_attempts=%d chain_source_inferred=%d chain_source_missing=%d chain_payload_ok=%d chain_payload_ignored=%d chain_payload_failed=%d payload_detonate_attempts=%d payload_detonate_ok=%d payload_detonate_failed=%d duplicate_suppressed=%d final_cancel_ok=%d final_cancel_failed=%d cap_reject=%d fanout_reject=%d modifier_reject=%d homing_reject=%d nested_payload_reject=%d chain_reject=%d post_launch_bounce_attempts=%d post_launch_bounce_ok=%d post_launch_bounce_failed=%d post_launch_actor_toggle_attempts=%d post_launch_actor_toggle_ok=%d post_launch_actor_toggle_failed=%d post_launch_projectile_missing=%d",
            g("live_bounce_attempts"),
            g("live_bounce_qualified"),
            g("live_bounce_rejected"),
            g("live_bounce_disabled_rejections"),
            g("live_bounce_trigger_qualified"),
            g("live_bounce_chain_payload_qualified"),
            g("live_bounce_source_jobs_enqueued"),
            g("live_bounce_events"),
            g("live_bounce_source_detonation_attempts"),
            g("live_bounce_source_detonation_ok"),
            g("live_bounce_source_detonation_failed"),
            g("live_bounce_trigger_payloads"),
            g("live_bounce_chain_payload_attempts"),
            g("live_bounce_chain_source_target_inferred"),
            g("live_bounce_chain_source_target_missing"),
            g("live_bounce_chain_payload_ok"),
            g("live_bounce_chain_payload_ignored"),
            g("live_bounce_chain_payload_failed"),
            g("live_bounce_trigger_payload_detonation_attempts"),
            g("live_bounce_trigger_payload_detonation_ok"),
            g("live_bounce_trigger_payload_detonation_failed"),
            g("live_bounce_duplicate_suppressed"),
            g("live_bounce_final_cancel_ok"),
            g("live_bounce_final_cancel_failed"),
            g("live_bounce_cap_reject"),
            g("live_bounce_fanout_reject"),
            g("live_bounce_modifier_reject"),
            g("live_bounce_homing_reject"),
            g("live_bounce_nested_payload_reject"),
            g("live_bounce_chain_reject"),
            g("sfp_post_launch_bounce_attempts"),
            g("sfp_post_launch_bounce_ok"),
            g("sfp_post_launch_bounce_failed"),
            g("sfp_post_launch_actor_toggle_attempts"),
            g("sfp_post_launch_actor_toggle_ok"),
            g("sfp_post_launch_actor_toggle_failed"),
            g("sfp_post_launch_physics_projectile_missing")
        ),
        string.format(
            "pierce attempts=%d qualified=%d rejected=%d disabled=%d source_jobs=%d source_ok=%d events=%d trigger_payload_enqueued=%d trigger_payload_ok=%d duplicate_suppressed=%d limit_stop_ok=%d limit_stop_failed=%d cap_reject=%d deferred_reject=%d ir_attempts=%d ir_enqueued=%d ir_fallback=%d ir_mismatch=%d post_launch_pierce_attempts=%d post_launch_pierce_ok=%d post_launch_pierce_failed=%d",
            g("live_pierce_attempts"),
            g("live_pierce_qualified"),
            g("live_pierce_rejected"),
            g("live_pierce_disabled_rejections"),
            g("live_pierce_source_jobs"),
            g("live_pierce_source_ok"),
            g("live_pierce_events"),
            g("live_pierce_trigger_payload_enqueued"),
            g("live_pierce_trigger_payload_ok"),
            g("live_pierce_duplicate_suppressed"),
            g("live_pierce_limit_stop_ok"),
            g("live_pierce_limit_stop_failed"),
            g("live_pierce_cap_reject"),
            g("live_pierce_deferred_reject"),
            g("ir_pierce_runtime_attempts"),
            g("ir_pierce_runtime_enqueued"),
            g("ir_pierce_runtime_fallback"),
            g("ir_pierce_runtime_mismatch"),
            g("sfp_post_launch_pierce_attempts"),
            g("sfp_post_launch_pierce_ok"),
            g("sfp_post_launch_pierce_failed")
        ),
        string.format(
            "nested_audit attempts=%d ok=%d rejected=%d future_candidates=%d chain_deferred=%d cap_rejections=%d",
            g("nested_payload_audit_attempts"),
            g("nested_payload_audit_ok"),
            g("nested_payload_audit_rejected"),
            g("nested_payload_audit_future_candidates"),
            g("nested_payload_audit_chain_deferred"),
            g("nested_payload_audit_cap_rejections")
        ),
        string.format(
            "payload_multicast attempts=%d qualified=%d rejected=%d jobs=%d timer_jobs=%d trigger_jobs=%d cap_reject=%d nested_reject=%d chain_reject=%d disabled_reject=%d ok=%d",
            g("payload_multicast_attempts"),
            g("payload_multicast_qualified"),
            g("payload_multicast_rejected"),
            g("payload_multicast_jobs"),
            g("payload_multicast_timer_jobs"),
            g("payload_multicast_trigger_jobs"),
            g("payload_multicast_cap_reject"),
            g("payload_multicast_nested_reject"),
            g("payload_multicast_chain_reject"),
            g("payload_multicast_disabled_reject"),
            g("payload_multicast_runtime_ok")
        ),
        string.format(
            "payload_pattern attempts=%d qualified=%d rejected=%d jobs=%d timer_jobs=%d trigger_jobs=%d spread_jobs=%d burst_jobs=%d disabled_reject=%d cap_reject=%d nested_reject=%d chain_reject=%d ok=%d",
            g("payload_pattern_attempts"),
            g("payload_pattern_qualified"),
            g("payload_pattern_rejected"),
            g("payload_pattern_jobs"),
            g("payload_pattern_timer_jobs"),
            g("payload_pattern_trigger_jobs"),
            g("payload_pattern_spread_jobs"),
            g("payload_pattern_burst_jobs"),
            g("payload_pattern_disabled_reject"),
            g("payload_pattern_cap_reject"),
            g("payload_pattern_nested_reject"),
            g("payload_pattern_chain_reject"),
            g("payload_pattern_runtime_ok")
        ),
        string.format(
            "nested_tt attempts=%d qualified=%d rejected=%d disabled=%d depth_reject=%d chain_reject=%d multicast_reject=%d pattern_reject=%d modifier_reject=%d timer_trigger=%d trigger_timer=%d intermediate_jobs=%d final_jobs=%d timer_callbacks=%d trigger_hits=%d duplicate_suppressed=%d ok=%d",
            g("nested_tt_attempts"),
            g("nested_tt_qualified"),
            g("nested_tt_rejected"),
            g("nested_tt_disabled_reject"),
            g("nested_tt_depth_reject"),
            g("nested_tt_chain_reject"),
            g("nested_tt_multicast_reject"),
            g("nested_tt_pattern_reject"),
            g("nested_tt_modifier_reject"),
            g("nested_tt_timer_trigger_qualified"),
            g("nested_tt_trigger_timer_qualified"),
            g("nested_tt_intermediate_jobs"),
            g("nested_tt_final_jobs"),
            g("nested_tt_timer_callbacks"),
            g("nested_tt_trigger_hits"),
            g("nested_tt_duplicate_suppressed"),
            g("nested_tt_runtime_ok")
        ),
        string.format(
            "nested_final_fanout attempts=%d qualified=%d rejected=%d disabled=%d depth_reject=%d chain_reject=%d same_kind_reject=%d nested_behavior_reject=%d cap_reject=%d pattern_reject=%d timer_trigger=%d trigger_timer=%d jobs=%d timer_jobs=%d trigger_jobs=%d spread_jobs=%d burst_jobs=%d duplicate_suppressed=%d ok=%d",
            g("nested_final_fanout_attempts"),
            g("nested_final_fanout_qualified"),
            g("nested_final_fanout_rejected"),
            g("nested_final_fanout_disabled_reject"),
            g("nested_final_fanout_depth_reject"),
            g("nested_final_fanout_chain_reject"),
            g("nested_final_fanout_same_kind_reject"),
            g("nested_final_fanout_nested_behavior_reject"),
            g("nested_final_fanout_cap_reject"),
            g("nested_final_fanout_pattern_reject"),
            g("nested_final_fanout_timer_trigger_qualified"),
            g("nested_final_fanout_trigger_timer_qualified"),
            g("nested_final_fanout_jobs"),
            g("nested_final_fanout_timer_jobs"),
            g("nested_final_fanout_trigger_jobs"),
            g("nested_final_fanout_spread_jobs"),
            g("nested_final_fanout_burst_jobs"),
            g("nested_final_fanout_duplicate_suppressed"),
            g("nested_final_fanout_runtime_ok")
        ),
        string.format(
            "chain_audit attempts=%d ok=%d rejected=%d future_candidates=%d hop_attempts=%d hop_ok=%d hop_rejected=%d hops_requested=%d hops_completed=%d stop_max=%d stop_no_target=%d resolve_attempts=%d resolve_ok=%d resolve_rejected=%d candidates_seen=%d valid=%d selected=%d no_target=%d radius_reject=%d cap_reject=%d invalid_context=%d nested_reject=%d multicast_reject=%d pattern_reject=%d trigger_timer_reject=%d recursion_reject=%d runtime_deferred=%d no_immediate_repeat=%d",
            g("chain_audit_attempts"),
            g("chain_audit_ok"),
            g("chain_audit_rejected"),
            g("chain_audit_future_candidate"),
            g("chain_hop_dry_run_attempts"),
            g("chain_hop_dry_run_ok"),
            g("chain_hop_dry_run_rejected"),
            g("chain_hops_requested"),
            g("chain_hops_completed"),
            g("chain_hop_stop_max"),
            g("chain_hop_stop_no_target"),
            g("chain_target_resolve_attempts"),
            g("chain_target_resolve_ok"),
            g("chain_target_resolve_rejected"),
            g("chain_target_candidates_seen"),
            g("chain_target_candidates_valid"),
            g("chain_target_candidates_selected"),
            g("chain_target_no_target_reject"),
            g("chain_target_radius_reject"),
            g("chain_target_cap_reject"),
            g("chain_target_invalid_context_reject"),
            g("chain_target_nested_reject"),
            g("chain_target_multicast_reject"),
            g("chain_target_pattern_reject"),
            g("chain_target_trigger_timer_reject"),
            g("chain_target_recursion_reject"),
            g("chain_target_runtime_deferred"),
            g("chain_target_no_immediate_repeat_exclusions")
        ),
        string.format(
            "chain_runtime attempts=%d qualified=%d rejected=%d disabled=%d direct=%d trigger_chain=%d source_hits=%d hop_attempts=%d hop_qualified=%d hop_rejected=%d hops_launched=%d hops_completed=%d stop_max=%d stop_no_target=%d no_target=%d provider_missing=%d payload_jobs=%d payload_processed=%d payload_ok=%d payload_failed=%d duplicate_suppressed=%d sfp_attempts=%d sfp_ok=%d sfp_failed=%d multicast_reject=%d pattern_reject=%d trigger_timer_reject=%d nested_reject=%d recursion_reject=%d cap_reject=%d context_reject=%d los_requests=%d los_visible=%d los_no_visible=%d los_unavailable=%d",
            g("chain_runtime_attempts"),
            g("chain_runtime_qualified"),
            g("chain_runtime_rejected"),
            g("chain_runtime_disabled_reject"),
            g("chain_runtime_direct_qualified"),
            g("chain_runtime_trigger_chain_qualified"),
            g("chain_runtime_source_hits"),
            g("chain_runtime_hop_attempts"),
            g("chain_runtime_hop_qualified"),
            g("chain_runtime_hop_rejected"),
            g("chain_runtime_hops_launched"),
            g("chain_runtime_hops_completed"),
            g("chain_runtime_stop_max_hops"),
            g("chain_runtime_stop_no_target"),
            g("chain_runtime_no_target"),
            g("chain_runtime_target_provider_missing"),
            g("chain_runtime_payload_jobs"),
            g("chain_runtime_payload_processed"),
            g("chain_runtime_payload_ok"),
            g("chain_runtime_probe_virtual_payload_jobs"),
            g("chain_runtime_probe_virtual_payload_ok"),
            g("chain_runtime_payload_failed"),
            g("chain_runtime_duplicate_suppressed"),
            g("chain_runtime_sfp_launch_attempts"),
            g("chain_runtime_sfp_launch_ok"),
            g("chain_runtime_sfp_launch_failed"),
            g("chain_runtime_multicast_reject"),
            g("chain_runtime_pattern_reject"),
            g("chain_runtime_trigger_timer_reject"),
            g("chain_runtime_nested_reject"),
            g("chain_runtime_recursion_reject"),
            g("chain_runtime_cap_reject"),
            g("chain_runtime_context_reject"),
            g("chain_runtime_los_requests"),
            g("chain_runtime_los_visible_candidates"),
            g("chain_runtime_los_no_visible_target"),
            g("chain_runtime_los_unavailable")
        ),
        string.format(
            "chain_modifier attempts=%d qualified=%d rejected=%d speed_qualified=%d size_qualified=%d speed_jobs=%d size_jobs=%d speed_mutated=%d size_mutated=%d size_specs=%d disabled_reject=%d combo_reject=%d unsupported_reject=%d payload_ok=%d payload_failed=%d",
            g("chain_modifier_attempts"),
            g("chain_modifier_qualified"),
            g("chain_modifier_rejected"),
            g("chain_modifier_speed_qualified"),
            g("chain_modifier_size_qualified"),
            g("chain_modifier_speed_jobs"),
            g("chain_modifier_size_jobs"),
            g("chain_modifier_speed_mutated"),
            g("chain_modifier_size_mutated"),
            g("chain_modifier_size_specs_mutated"),
            g("chain_modifier_disabled_reject"),
            g("chain_modifier_combo_reject"),
            g("chain_modifier_unsupported_reject"),
            g("chain_modifier_payload_ok"),
            g("chain_modifier_payload_failed")
        ),
        string.format(
            "chain_multicast attempts=%d qualified=%d rejected=%d disabled_reject=%d fanout_cap_reject=%d hops=%d jobs=%d payload_ok=%d payload_failed=%d branch_events=%d branch_groups=%d max_branch_fanout=%d",
            g("chain_multicast_attempts"),
            g("chain_multicast_qualified"),
            g("chain_multicast_rejected"),
            g("chain_multicast_disabled_reject"),
            g("chain_multicast_fanout_cap_reject"),
            g("chain_multicast_hops"),
            g("chain_multicast_jobs"),
            g("chain_multicast_payload_ok"),
            g("chain_multicast_payload_failed"),
            g("branch_observability_events"),
            g("branch_observability_chain_multicast_branches"),
            g("branch_observability_max_branch_fanout")
        ),
        string.format(
            "chain_provider attempts=%d real_attempts=%d real_ok=%d real_unavailable=%d real_failed=%d mock_attempts=%d candidates_seen=%d candidates_returned=%d candidate_cap_hit=%d actor_scan_cap_hit=%d current_excluded=%d caster_excluded=%d radius_applied=%d context_missing=%d position_missing=%d cell_missing=%d object_invalid=%d selected_real=%d selected_mock=%d",
            g("chain_provider_attempts"),
            g("chain_provider_real_attempts"),
            g("chain_provider_real_ok"),
            g("chain_provider_real_unavailable"),
            g("chain_provider_real_failed"),
            g("chain_provider_mock_attempts"),
            g("chain_provider_candidates_seen"),
            g("chain_provider_candidates_returned"),
            g("chain_provider_candidate_cap_hit"),
            g("chain_provider_actor_scan_cap_hit"),
            g("chain_provider_current_target_excluded"),
            g("chain_provider_caster_excluded"),
            g("chain_provider_radius_applied"),
            g("chain_provider_context_missing"),
            g("chain_provider_position_missing"),
            g("chain_provider_cell_missing"),
            g("chain_provider_object_invalid"),
            g("chain_provider_selected_real"),
            g("chain_provider_selected_mock")
        ),
        string.format(
            "impact_vfx metadata_present=%d metadata_missing=%d default_area_fallback=%d area_override=%d invalid_area_override_suppressed=%d hit_model_attempted=%d spawn_failed=%d",
            g("impact_vfx_metadata_present"),
            g("impact_vfx_metadata_missing"),
            g("impact_vfx_default_area_fallback_used"),
            g("impact_vfx_area_override_used"),
            g("impact_vfx_invalid_area_override_suppressed"),
            g("impact_vfx_hit_model_spawn_attempted"),
            g("impact_vfx_spawn_failed")
        ),
        string.format(
            "speed_plus attempts=%d qualified=%d rejected=%d disabled=%d jobs_mutated=%d invalid=%d capped=%d field_missing=%d payload_reject=%d unsupported_reject=%d smoke=%d",
            g("live_speed_plus_attempts"),
            g("live_speed_plus_qualified"),
            g("live_speed_plus_rejected"),
            g("live_speed_plus_disabled_rejections"),
            g("live_speed_plus_jobs_mutated"),
            g("live_speed_plus_value_invalid"),
            g("live_speed_plus_value_capped"),
            g("live_speed_plus_field_missing"),
            g("live_speed_plus_payload_rejections"),
            g("live_speed_plus_unsupported_combo_rejections"),
            g("live_speed_plus_smoke_observed")
        ),
        string.format(
            "size_plus attempts=%d qualified=%d rejected=%d disabled=%d jobs_mutated=%d specs_mutated=%d invalid=%d capped=%d field_missing=%d payload_reject=%d unsupported_reject=%d smoke=%d",
            g("live_size_plus_attempts"),
            g("live_size_plus_qualified"),
            g("live_size_plus_rejected"),
            g("live_size_plus_disabled_rejections"),
            g("live_size_plus_jobs_mutated"),
            g("live_size_plus_specs_mutated"),
            g("live_size_plus_value_invalid"),
            g("live_size_plus_value_capped"),
            g("live_size_plus_field_missing"),
            g("live_size_plus_payload_rejections"),
            g("live_size_plus_unsupported_combo_rejections"),
            g("live_size_plus_smoke_observed")
        ),
        string.format(
            "homing attempts=%d qualified=%d rejected=%d disabled=%d jobs_mutated=%d target_reject=%d force_invalid=%d payload_reject=%d unsupported_reject=%d smoke=%d",
            g("live_homing_attempts"),
            g("live_homing_qualified"),
            g("live_homing_rejected"),
            g("live_homing_disabled_rejections"),
            g("live_homing_jobs_mutated"),
            g("live_homing_target_rejections"),
            g("live_homing_force_invalid"),
            g("live_homing_payload_rejections"),
            g("live_homing_unsupported_combo_rejections"),
            g("live_homing_smoke_observed")
        ),
        string.format(
            "soft_homing probe_registered=%d runtime_registered=%d disabled_probe=%d disabled_runtime=%d cap_reject=%d runtime_cap_reject=%d ticks=%d considered=%d updated=%d state_requested=%d state_ok=%d state_failed=%d redirect_attempted=%d redirect_ok=%d redirect_failed=%d redirect_blended=%d target_acquired=%d target_missing=%d retarget_attempted=%d retarget_ok=%d retarget_cooldown_skip=%d retarget_budget_skip=%d retarget_not_better=%d retarget_candidates=%d retarget_cone_reject=%d retarget_creatures=%d retarget_npcs=%d retarget_actors=%d static_search_started=%d static_search_ticks=%d retired_hit=%d retired_timeout=%d retired_missing_state=%d retired_api_failure=%d retired_static_overshot=%d active_max=%d",
            g("homing_probe_registered"),
            g("homing_runtime_registered"),
            g("homing_probe_rejected_disabled"),
            g("homing_runtime_rejected_disabled"),
            g("homing_probe_rejected_cap"),
            g("homing_runtime_rejected_cap"),
            g("homing_tick_runs"),
            g("homing_entries_considered"),
            g("homing_entries_updated"),
            g("homing_state_requested"),
            g("homing_state_ok"),
            g("homing_state_failed"),
            g("homing_redirect_attempted"),
            g("homing_redirect_ok"),
            g("homing_redirect_failed"),
            g("homing_redirect_blended"),
            g("homing_target_acquired"),
            g("homing_target_missing"),
            g("homing_retarget_attempted"),
            g("homing_retarget_ok"),
            g("homing_retarget_skipped_cooldown"),
            g("homing_retarget_skipped_budget"),
            g("homing_retarget_skipped_not_better"),
            g("homing_retarget_candidates_seen"),
            g("homing_retarget_cone_rejected"),
            g("homing_retarget_creature_candidates"),
            g("homing_retarget_npc_candidates"),
            g("homing_retarget_actor_candidates"),
            g("homing_static_overshot_search_started"),
            g("homing_static_overshot_search_ticks"),
            g("homing_entry_retired_hit"),
            g("homing_entry_retired_timeout"),
            g("homing_entry_retired_missing_state"),
            g("homing_entry_retired_api_failure"),
            g("homing_entry_retired_static_overshot"),
            g("homing_active_max_observed")
        ),
        string.format(
            "homing_v2 register_attempted=%d register_ok=%d register_failed=%d missing_projectile=%d budget_skipped=%d state_requested=%d state_ok=%d redirect_attempted=%d redirect_ok=%d redirect_failed=%d",
            g("homing_v2_register_attempted"),
            g("homing_v2_register_ok"),
            g("homing_v2_register_failed"),
            g("homing_runtime_registration_missing_projectile_id"),
            g("homing_v2_budget_skipped"),
            g("homing_v2_state_requested"),
            g("homing_v2_state_ok"),
            g("homing_v2_redirect_attempted"),
            g("homing_v2_redirect_ok"),
            g("homing_v2_redirect_failed")
        ),
    }
end

return runtime_stats
