return {
    "khajiit",
    "shuttered",
    "covered",
    "hook",
    "civic",
    "tufted",
    "ashlander",
    "reinforced",
    "assassin's",
    "marksmans",
    "traditional",
    "lochaber",
    "doubled bladed",
    "right",
    "bronze",
    "plated",
    "bastard",
    "sacrificial",
    "ceremonial",
    "double",
    "harvesting",
    "beach wood",
    "heavy",
    "elitist",
}