return {
"da_gurkha",
"da_navaja",
"da_kukri",
"da_kukri_01",
"da_katar_01",
"da_katar_02",
"da_trident_01",
"da_spindlemace",
"da_trident_02",
"da_dagger_e",
"da_stilletto_02",
"da_stilletto_03",
"da_halbar",
"da_kukri_02",
"da_stilletto_01",
"da_axe_02",
"da_axe_01",
"da_bardiche",
"da_cresenthead",
"da_katar_03",
"da_kern",
"da_kriss_01",
"da_kriss_02",
"da_axe_03",
"da_morningstar",
"da_rapier",
"da_trident_03",
"da_axe_04",
"_ws_right_tonfa",
"ar_rapier",
"ar_wolfscim_right",
"ar_glass katana",
"ar_glass dai-katana",
"ar_glass wakizashi",
"ar_ornate_gold_katana",
"ar_ornate_gold_katana_double",
"ar_ebony dai-katana",
"ar_steel wristblade",
"ar_ornate_gold_wristblade",
"ar_ornate_sacrificial_dagger",
"ar_ornate_gold dai-katana",
"ar_kris",
"ar_ornate_gold_scythe",
"ar_glass wristblade",
"ar_steel kama",
"ar_steel sicle",
"ar_glass kama",
"ar_glass sicle",
"ar_bolt rifle",
"ar_glass 2 katana",
"ar_steel 2 katana",
"ar_steel sai",
"ar_glass wakizashjink",
"ar_silver_kris",
"ar_silver_sai",
"ar_ornate_gold_claymore",
"ar_steel_scythe",
"ar_silver dagashi",
"ar_warbow",
"ar_heavywoodcross",
"ar_silver rapier",
"ar_adamantium_battleaxe",
"ar_silver_battle",
"ar_bolt sniper",
"ar_bastard sword 01",
"ar_bastard sword 02",
"ar_bastard sword 03",
"ar_bastard sword 04",
}