return {
    DEFAULTS = {
        CHECK_INTERVAL      = 0.25,
        HEAL_THRESHOLD      = 10,
        HP_PENALTY          = 1,
        MIN_BASE_HP         = 1,
        DAMAGE_THRESHOLD    = 10,
        ATTR_PENALTY        = 3,
        PERSONALITY_PENALTY = 6,
        MOD_ENABLED         = true,
        HP_RESTORE          = true,
        CE_IGNORE           = true,
        CE_INTERVAL         = 10,
        WISDOM_ENABLED      = false,
        WISDOM_CHANCE       = 30,
        WISDOM_GAIN         = 1,
        RECOVERY_ENABLED    = false,
        RECOVERY_DAYS       = 7,
        RECOVERY_PARTIAL    = false,
    },
    FOOD = {
        "Resin",
        "Sweetpulp",
        "Wickwheat",
        "Marshmerrow",
    },
    PENALTY_MESSAGES = {
        "Your body grows weaker from over-reliance on healing.",
        "Repeated mending takes its toll. Your vitality wanes.",
        "The flesh remembers every shortcut taken in battle.",
        "You feel a lasting weakness settle into your bones.",
        "Your constitution suffers from excessive restoration.",
        "The body was not meant to be mended so frequently.",
        "Each healing leaves you a little less than before.",
        "Restoration has its price. Your vitality diminishes.",
        "The repeated strain of healing has left its mark.",
        "You sense a permanent frailty creeping through your body.",
        "Old scars ache where magic cannot reach.",
        "Some wounds run too deep for any restoration spell to mend.",
    },
    RECOVERY_MESSAGES = {
        "Time has mended what magic could not. You feel restored.",
        "Rest and the passage of days have healed your deeper wounds.",
        "The body, given time, remembers its former strength.",
        "Your scars have faded. Vitality returns to your limbs.",
        "Days of hardship and rest have renewed you.",
        "What was taken by excess healing has slowly returned.",
        "The world turns, and with it, your strength is restored.",
    },
    WISDOM_MESSAGES = {
        "Pain is a patient teacher.",
        "What does not kill you leaves a scar worth learning from.",
        "The body forgets comfort. The mind does not.",
        "Suffering has sharpened something within you.",
        "From ruin, a clearer understanding.",
        "Adversity has carved new pathways in your thinking.",
        "You have paid for this insight with your flesh.",
        "The wound taught you what comfort never could.",
        "Something in you has grown sharper from the ordeal.",
    },
    ATTR_MESSAGES = {
        strength = {
            "Your grip feels less certain than it once did.",
            "A tremor runs through your arms. You are not as strong as you were.",
            "The blow has cost you more than blood. Your strength has diminished.",
            "You feel the weight of your weapons more keenly now.",
        },
        agility = {
            "Your footing feels uncertain. Something in your balance has shifted.",
            "You move a little slower, a little clumsier than before.",
            "The wound has stiffened your joints. You will not forget it easily.",
            "A subtle wrongness in your step. Your agility has suffered.",
            "You catch yourself stumbling where you once moved surely.",
        },
        speed = {
            "Your legs feel heavier. The ground seems to resist you.",
            "You notice a sluggishness that was not there before.",
            "The injury has slowed you in ways rest cannot fully undo.",
            "You will not outrun your mistakes as easily from now on.",
            "You find yourself falling behind where you once kept pace.",
        },
        endurance = {
            "You feel hollowed out. Your body cannot take what it once could.",
            "A deep exhaustion has settled in. Your endurance has waned.",
            "The repeated trauma has worn something essential away.",
            "Your breath comes harder now. The damage runs deep.",
            "Your lungs burn sooner than they used to.",
        },
        personality = {
            "The pain has left its mark on your face. People will notice.",
            "Something in your bearing has changed. You seem diminished.",
            "The ordeal has taken a toll beyond the physical.",
            "You carry the wounds where others can see them now.",
            "Your eyes have a haunted look that others notice.",
        },
    },
}