local ssqn = include("SSQN.interop") --Must come before function calls

local function init()
    if (ssqn) then
    	ssqn.registerQIcon("PC_m1_AFP01","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP02","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP03","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP04","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP05","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP06","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP07","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP08","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP09","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP10","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP11","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP12","\\Icons\\pc\\q\\PC_m1_AFP.dds")
	ssqn.registerQIcon("PC_m1_Anv_Bounty","\\Icons\\pc\\q\\PC_m1_Bounty.dds")	
	ssqn.registerQIcon("PC_m1_Anv_Goldenrod","\\Icons\\pc\\q\\PC_m1_K1.dds")
	ssqn.registerQIcon("PC_m1_Anv_GoldenrodBR","\\Icons\\pc\\q\\PC_m1_K1.dds")
	ssqn.registerQIcon("PC_m1_Anv_GoldenrodDR","\\Icons\\pc\\q\\PC_m1_K1.dds")
	ssqn.registerQIcon("PC_m1_Anv_GoldenrodEH","\\Icons\\pc\\q\\PC_m1_K1.dds")
	ssqn.registerQIcon("PC_m1_Anv_GoldenrodLI","\\Icons\\pc\\q\\PC_m1_K1.dds")
	ssqn.registerQIcon("PC_m1_Anv_GoldenrodPA","\\Icons\\pc\\q\\PC_m1_K1.dds")
	ssqn.registerQIcon("PC_m1_Anv_GoldenrodSM","\\Icons\\pc\\q\\PC_m1_K1.dds")
	ssqn.registerQIcon("PC_m1_Anv_GoldenrodST","\\Icons\\pc\\q\\PC_m1_K1.dds")
    	ssqn.registerQIcon("PC_m1_Anv","\\Icons\\pc\\q\\PC_m1_Anv.dds")
    	ssqn.registerQIcon("PC_m1_Arc","\\Icons\\pc\\q\\PC_m1_Arc.dds")
    	ssqn.registerQIcon("PC_m1_BC","\\Icons\\pc\\q\\PC_m1_BC.dds")
    	ssqn.registerQIcon("PC_m1_Cha","\\Icons\\pc\\q\\PC_m1_Cha.dds")
    	ssqn.registerQIcon("PC_m1_DM","\\Icons\\pc\\q\\PC_m1_DM.dds")
    	ssqn.registerQIcon("PC_m1_FG","\\Icons\\pc\\q\\PC_m1_FG.dds")
    	ssqn.registerQIcon("PC_m1_Gld","\\Icons\\pc\\q\\PC_m1_Gld.dds")
    	ssqn.registerQIcon("PC_m1_IP","\\Icons\\pc\\q\\PC_m1_IP.dds")
    	ssqn.registerQIcon("PC_m1_K1","\\Icons\\pc\\q\\PC_m1_K1.dds")
    	ssqn.registerQIcon("PC_m1_MG","\\Icons\\pc\\q\\PC_m1_MG.dds")
    	ssqn.registerQIcon("PC_m1_Mrv","\\Icons\\pc\\q\\PC_m1_Mrv.dds")
    	ssqn.registerQIcon("PC_m1_SC","\\Icons\\pc\\q\\PC_m1_SC.dds")
	ssqn.registerQIcon("PC_m1_SC_Bounty","\\Icons\\pc\\q\\PC_m1_Bounty.dds")
    	ssqn.registerQIcon("PC_m1_Sdk","\\Icons\\pc\\q\\PC_m1_Sdk.dds")
    	ssqn.registerQIcon("PC_m1_TG","\\Icons\\pc\\q\\PC_m1_TG.dds")
    	ssqn.registerQIcon("PC_m1_Tvy","\\Icons\\pc\\q\\PC_m1_Tvy.dds")
    end
end

event.register(tes3.event.initialized, init)