return {
    --Houses
    " house",
    " manor",
    " domain",
    " shack",
    " apartment",
    " yurt",
    "farm",
    "plantation",
    "storage",
    "warehouse",
    "hlaalu",
    "redoran",
    "telvanni",
    "indoril",

    --Guards
    "tower",
    "outpost",
    "fort",
    "tel ",
    "legion",
    "garrison",

    --Velothi
    "ancestral tomb",
    " temple",
    " shrine",
    " chapel",

    --Nord
    "barrow",

    --Guilds
    " guild",
    "fighter",
    "mages",
    "morag",
    "east empire",

    --Mines
    " mine",
    "quarry",
    " cave",

    --Ships
    "ship",
    "cabin",
    "deck",
    "upper level",
    "lighthouse",


    --Shops
    " fine ",
    "trade",
    " goods",
    "market",
    "bazaar",
    "enchanter",
    "pawnbroker",
    "alchemist",
    "apothecary",
    "philter",
    "elixir",
    "potion",
    "book",
    "librar",
    "outfitter",
    "clothier",
    "tailor",
    "smith",
    "armorer",
    "weapons",
    "potter",
    "arrows",
    "fetcher",

    --Inns
    "council club",
    "the rat in the pot",
    "eight plates",
    "lucky lockup",
    " shovel",
    "the end of the world",
    "six fishes",
    "tower of dusk",
    " tavern",
    " hole in the wall",
    " inn",
    "cornerclub",
    "arrille",
    "earthly delights",
    "plot and plaster",
    "the covenant",
    "the lizard",
    "the avenue",
    "s rest",
    "the dancing jug",
    "the glass goblet",
    "the golden glade",
    "the howling noose",
    "limping scrib",
    "the magic mudcrab",
    "mining bunkhouse", 
    " alehouse", 
    "the note in your eye",
    "s cutlass",
    "the silver serpent",
    "the swallow",
    "twisted root",

    
    --Dwemer ruins
    "aleft",
    "amschend",
    "arkngth",
    "bethamez",
    "bthanchend",
    "dagoth ur",
    "druscashti",
    "endusal",
    "galom daeus",
    "mudan",
    "mzahnch",
    "mzanchend",
    "mzuleft",
    "nchard",
    "nchu",
    "odrosal",
    "tureynulal",
    "vemynal",
    "akuband",
    "alencheth",
    "amthuandz",
    "archtumz",
    "barzamthuand",
    "bazak",
    "bazhthum",
    "bthalag",
    "bthangthamuzand",
    "bthuangthuv",
    "bthung",
    "bthzundch",
    "chunzefk",
    "durthungz",
    "stardumz",
    "kemel",
    "khadumzunch",
    "leftunch",
    "manrizache",
    "mvelthngth",
    "mzankh",
    "mzungleft",
    "nchal",
    "nchazdrumn",
    "nchulark",
    "nchulegfth",
    "ngelfltingth",
    "ratharzak",
    "rthungzark",
    "yaztaramz",

    
    --Dunmer Strongholds
    "andasreth",
    "berandas",
    "falasmaryon",
    "falensarano",
    "hlormaren",
    "indoranyon",
    "kogoruhn",
    "marandus",
    "rotheran",
    "telasero",
    "valenvaryon",
    "baan urlai",
    "bisandryon",
    "hlorandus",
    "idaverrano",
    "koranyon",
    "mandaran",
    "merihayan",
    "othrano",
    "romayon",
    "salandus",
    "tulesmath",
    "turendas",
    "valendus",
    "volenfaryon",


    --Daedric Shrines
    "ashunartes",
    "ashurnibibi",
    "asurdirapal",
    "dushariran",
    "ibishammus",
    "kaushtarari",
    "shashpilamat",
    "zergonipal",
    "ald sotha",
    "ashalmimilkala",
    "assarnatamat",
    "assernerairan",
    "ebernanit",
    "ularradallaku",
    "yasammidan",
    "ashalmawia",
    "bal ur",
    "estunamus",
    "kushtashpi",
    "ramimilk",
    "tusenend",
    "yasirramus",
    "addadshashanammu",
    "ald daedroth",
    "almurbalarammi",
    "asslkushalit",
    "bal fell",
    "ihinipalit",
    "maelkashishi",
    "onnisiralis",
    "zaintiraris",
    "anudnabia",
    "shrine of azura",
    "shrine of boethia",
    "balititashpi",
    "yashazmus",
    "ald uman",
    "alumawia",
    "mashadananit",
    "ashushushi",
    "onimushili",
    "ald mirathi",
    "ossurnashalit",
    "ald niripal",
    "ald uran",
    "ebamusharisus",
    "ashpibishal",
    "bal dushal",
    "veranzaris",
    "baelkashpitu",
    "yanishanabi",
    "hummurushtapi",
    "anashbibi",
    "yamandalkal",
    "yabananit",
    "kannidamarus",
    "ald balaal",
    "essarnartes",
    "esuranamit",
    "hadrumnibibi",
    "ikinammassu",
    "ibiammusashan",
    "bapatipi",
    "shambalu",
    "ebunammidan",
    "bushipananit",
    "ulanababia",
    "malkamalit",
    "teknilashashulpi",
    "yamuninisharn",


}
