local tooltipsComplete = include("Tooltips Complete.interop")
local tooltipData =
{
    { id = "tew_ahlouad", description = "This ancient instrument's name can be rendered as \"river surface\", as the upper edge of its neck is covered with a smooth layer, allowing for long-reaching pitch \"slides\", typical for most intricate Dunmeri compositions. The wood's bulkiness is balanced by rich ornamentation, and the price is accordingly high."},
    { id = "tew_ahlouad-orn", description = "This ancient instrument's name can be rendered as \"river surface\", as the upper edge of its neck is covered with a smooth layer, allowing for long-reaching pitch \"slides\", typical for most intricate Dunmeri compositions. The wood's bulkiness is balanced by rich ornamentation, and the price is accordingly high."},
    { id = "tew_ahlouad-red", description = "This ancient instrument's name can be rendered as \"river surface\", as the upper edge of its neck is covered with a smooth layer, allowing for long-reaching pitch \"slides\", typical for most intricate Dunmeri compositions. The wood's bulkiness is balanced by rich ornamentation, and the price is accordingly high."},
    { id = "tew_ahlouad-seryn", description = "This ancient instrument's name can be rendered as \"river surface\", as the upper edge of its neck is covered with a smooth layer, allowing for long-reaching pitch \"slides\", typical for most intricate Dunmeri compositions. The wood's bulkiness is balanced by rich ornamentation, and the price is accordingly high."},
    { id = "tew_dayereh-alit", description = "A simple frame drum made of a carved piece of wood and a piece of thin skin. The Dunmer play the dayereh using a variety of hand strokes, producing a wide array of sounds - from low thumb thuds to rapid finger trills."},
    { id = "tew_dayereh-daed", description = "A simple frame drum made of a carved piece of wood and a piece of thin skin. The Dunmer play the dayereh using a variety of hand strokes, producing a wide array of sounds - from low thumb thuds to rapid finger trills."},
    { id = "tew_dayereh-guar1", description = "A simple frame drum made of a carved piece of wood and a piece of thin skin. The Dunmer play the dayereh using a variety of hand strokes, producing a wide array of sounds - from low thumb thuds to rapid finger trills."},
    { id = "tew_dayereh-guar2", description = "A simple frame drum made of a carved piece of wood and a piece of thin skin. The Dunmer play the dayereh using a variety of hand strokes, producing a wide array of sounds - from low thumb thuds to rapid finger trills."},
    { id = "tew_cahnjerlosh-tel", description = "Literally meaning \"three ropes\", the cahnjerlosh is a traditional Dunmeri long-necked, fretless lute, sporting two drone strings and one thin melody string. Vastly popular throughout Morrowind, the cahnjerlosh is usually accompanied by a guarskin drum or voice."},
    { id = "tew_cahnjerlosh", description = "Literally meaning \"three ropes\", the cahnjerlosh is a traditional Dunmeri long-necked, fretless lute, sporting two drone strings and one thin melody string. Vastly popular throughout Morrowind, the cahnjerlosh is usually accompanied by a guarskin drum or voice."},
    { id = "tew_fisrokahr", description = "The fisrokahr can be translated as \"bowl-sounding instrument\", since this bowed lyre resonates through a metal-encrusted cavity, skilfully crafted to amplify frequencies of ancient Velothi heptatonic scales. The fisrokahr are said to invoke strong emotions, and the weeping, droning sounds were so mind-altering that the instrument was historically banned from Temple grounds."},
    { id = "tew_fisrokahr2", description = "The fisrokahr can be translated as \"bowl-sounding instrument\", since this bowed lyre resonates through a metal-encrusted cavity, skilfully crafted to amplify frequencies of ancient Velothi heptatonic scales. The fisrokahr are said to invoke strong emotions, and the weeping, droning sounds were so mind-altering that the instrument was historically banned from Temple grounds."},
    { id = "tew_fisrokahr3", description = "The fisrokahr can be translated as \"bowl-sounding instrument\", since this bowed lyre resonates through a metal-encrusted cavity, skilfully crafted to amplify frequencies of ancient Velothi heptatonic scales. The fisrokahr are said to invoke strong emotions, and the weeping, droning sounds were so mind-altering that the instrument was historically banned from Temple grounds."},
    { id = "tew_jentreng", description = "A central part of Dunmeri ancestral rituals, the jentreng is a plucked zither fashioned from a large piece of dry wood and decorated in a variety of ways. The traditional way of playing the jentreng involves memorising a set of \"gashneh\", or movements, each tied closely to an ancestral dance piece, where a dancer swirls gracefully on one foot, holding a piece of coloured fabric fluttering through incense-filled air. The performance is said to summon spirits of the ancestors."},
    { id = "tew_jentreng2", description = "A central part of Dunmeri ancestral rituals, the jentreng is a plucked zither fashioned from a large piece of dry wood and decorated in a variety of ways. The traditional way of playing the jentreng involves memorising a set of \"gashneh\", or movements, each tied closely to an ancestral dance piece, where a dancer swirls gracefully on one foot, holding a piece of coloured fabric fluttering through incense-filled air. The performance is said to summon spirits of the ancestors."},
    { id = "tew_jentreng3", description = "A central part of Dunmeri ancestral rituals, the jentreng is a plucked zither fashioned from a large piece of dry wood and decorated in a variety of ways. The traditional way of playing the jentreng involves memorising a set of \"gashneh\", or movements, each tied closely to an ancestral dance piece, where a dancer swirls gracefully on one foot, holding a piece of coloured fabric fluttering through incense-filled air. The performance is said to summon spirits of the ancestors."},
    { id = "tew_jentreng4", description = "A central part of Dunmeri ancestral rituals, the jentreng is a plucked zither fashioned from a large piece of dry wood and decorated in a variety of ways. The traditional way of playing the jentreng involves memorising a set of \"gashneh\", or movements, each tied closely to an ancestral dance piece, where a dancer swirls gracefully on one foot, holding a piece of coloured fabric fluttering through incense-filled air. The performance is said to summon spirits of the ancestors."},
    { id = "tew_kushik", description = "The kushik is a small hand drum, widely popular amongst many cultures of Tamriel due to of its simple design. Nevertheless, an able musician will be able to use the thin membrane and two sets of loose zills to play a nearly innumerable number of rhytmic patterns."},
    { id = "tew_kushik2", description = "The kushik is a small hand drum, widely popular amongst many cultures of Tamriel due to of its simple design. Nevertheless, an able musician will be able to use the thin membrane and two sets of loose zills to play a nearly innumerable number of rhytmic patterns."},
    { id = "tew_kushik3", description = "The kushik is a small hand drum, widely popular amongst many cultures of Tamriel due to of its simple design. Nevertheless, an able musician will be able to use the thin membrane and two sets of loose zills to play a nearly innumerable number of rhytmic patterns."},
    { id = "tew_kushik4", description = "The kushik is a small hand drum, widely popular amongst many cultures of Tamriel due to of its simple design. Nevertheless, an able musician will be able to use the thin membrane and two sets of loose zills to play a nearly innumerable number of rhytmic patterns."},
    { id = "tew_kushik5", description = "The kushik is a small hand drum, widely popular amongst many cultures of Tamriel due to of its simple design. Nevertheless, an able musician will be able to use the thin membrane and two sets of loose zills to play a nearly innumerable number of rhytmic patterns."},
    { id = "tew_kushik6", description = "The kushik is a small hand drum, widely popular amongst many cultures of Tamriel due to of its simple design. Nevertheless, an able musician will be able to use the thin membrane and two sets of loose zills to play a nearly innumerable number of rhytmic patterns."},
    { id = "tew_bow", description = "A simple wooden bow used in traditional Dark Elf music - or \"leyr\" in Dunmeri parlance. The legend has it the early Velothi hunters discovered the musical properties of a simple chitin bow by accident, when their resin-covered hands touched a lute string, producing a sound unlike any before. To this day the resin retrieved from Vvardenfell shalks is widely used in Dunmeri music tradition."},
    { id = "tew_bow2", description = "A simple wooden bow used in traditional Dark Elf music - or \"leyr\" in Dunmeri parlance. The legend has it the early Velothi hunters discovered the musical properties of a simple chitin bow by accident, when their resin-covered hands touched a lute string, producing a sound unlike any before. To this day the resin retrieved from Vvardenfell shalks is widely used in Dunmeri music tradition."},
    { id = "tew_bow3", description = "A simple wooden bow used in traditional Dark Elf music - or \"leyr\" in Dunmeri parlance. The legend has it the early Velothi hunters discovered the musical properties of a simple chitin bow by accident, when their resin-covered hands touched a lute string, producing a sound unlike any before. To this day the resin retrieved from Vvardenfell shalks is widely used in Dunmeri music tradition."},
    { id = "tew_tumbehk", description = "The tumbehk (an onomatopoeia) are traditional Dunmeri goblet drums, carved from a large piece of wood and covered with a stretched skin membrane. The drum can be placed horizontally or verically, the slim central piece nested between the player's legs. The instrument's shape allows a skilled musician to produce a vast amount of different sounds, and the tumbehk can be heard both solo and accompanying other players."},
    { id = "tew_tumbehk2", description = "The tumbehk (an onomatopoeia) are traditional Dunmeri goblet drums, carved from a large piece of wood and covered with a stretched skin membrane. The drum can be placed horizontally or verically, the slim central piece nested between the player's legs. The instrument's shape allows a skilled musician to produce a vast amount of different sounds, and the tumbehk can be heard both solo and accompanying other players."},
    { id = "tew_tumbehk3", description = "The tumbehk (an onomatopoeia) are traditional Dunmeri goblet drums, carved from a large piece of wood and covered with a stretched skin membrane. The drum can be placed horizontally or verically, the slim central piece nested between the player's legs. The instrument's shape allows a skilled musician to produce a vast amount of different sounds, and the tumbehk can be heard both solo and accompanying other players."},
    { id = "tew_tumbehk4", description = "The tumbehk (an onomatopoeia) are traditional Dunmeri goblet drums, carved from a large piece of wood and covered with a stretched skin membrane. The drum can be placed horizontally or verically, the slim central piece nested between the player's legs. The instrument's shape allows a skilled musician to produce a vast amount of different sounds, and the tumbehk can be heard both solo and accompanying other players."},
    { id = "tew_tumbehk5", description = "The tumbehk (an onomatopoeia) are traditional Dunmeri goblet drums, carved from a large piece of wood and covered with a stretched skin membrane. The drum can be placed horizontally or verically, the slim central piece nested between the player's legs. The instrument's shape allows a skilled musician to produce a vast amount of different sounds, and the tumbehk can be heard both solo and accompanying other players."},
    { id = "tew_zuileyr", description = "This wooden lute with curved, protruding frets was so popular amongst the settled Dunmer that its name literally translates as \"music thing\" or simply \"instrument\". The zuileyr's six strings - two drone strings, a double sympathetic string, and two melody strings - are more than enough to perform any piece of the poetry-inspired \"morhbaldefur\" (\"the hand above\") genre that brings together the myths and tales of all Dumner Houses."},
    { id = "tew_zuileyr-wht", description = "This wooden lute with curved, protruding frets was so popular amongst the settled Dunmer that its name literally translates as \"music thing\" or simply \"instrument\". The zuileyr's six strings - two drone strings, a double sympathetic string, and two melody strings - are more than enough to perform any piece of the poetry-inspired \"morhbaldefur\" (\"the hand above\") genre that brings together the myths and tales of all Dunmer Houses."},

}

local function initialized()
    if tooltipsComplete then
        for _, data in ipairs(tooltipData) do
            tooltipsComplete.addTooltip(data.id, data.description, data.itemType)
        end
    end
end

event.register("initialized", initialized)