local data = {}
data.raceReactions = {
    ["imperial"] = {
        ["imperial"] = 0, ["breton"] = 0, ["nord"] = 0, ["redguard"] = 0,
        ["dark elf"] = -5, ["high elf"] = 0, ["wood elf"] = 0,
        ["orc"] = -5, ["argonian"] = -5, ["khajiit"] = -5,
    },

    ["dark elf"] = {
        ["dark elf"] = 0, ["imperial"] = -5, ["breton"] = -5, ["nord"] = -5,
        ["redguard"] = -5, ["high elf"] = -5, ["wood elf"] = -5,
        ["orc"] = -5, ["argonian"] = -10, ["khajiit"] = -10,
    },

    ["breton"] = {
        ["breton"] = 0, ["imperial"] = 0, ["nord"] = 0, ["redguard"] = 0,
        ["dark elf"] = -5, ["high elf"] = 0, ["wood elf"] = 0,
        ["orc"] = -5, ["argonian"] = -5, ["khajiit"] = -5,
    },

    ["nord"] = {
        ["nord"] = 0, ["imperial"] = 0, ["breton"] = 0, ["redguard"] = 0,
        ["dark elf"] = -5, ["high elf"] = -5, ["wood elf"] = 0,
        ["orc"] = -5, ["argonian"] = -5, ["khajiit"] = -5,
    },

    ["redguard"] = {
        ["redguard"] = 0, ["imperial"] = 0, ["breton"] = 0, ["nord"] = 0,
        ["dark elf"] = -5, ["high elf"] = -5, ["wood elf"] = 0,
        ["orc"] = -5, ["argonian"] = -5, ["khajiit"] = -5,
    },

    ["high elf"] = {
        ["high elf"] = 0, ["imperial"] = 0, ["breton"] = 0,
        ["nord"] = -5, ["redguard"] = -5, ["dark elf"] = -5,
        ["wood elf"] = 0, ["orc"] = -5, ["argonian"] = -5, ["khajiit"] = -5,
    },

    ["wood elf"] = {
        ["wood elf"] = 0, ["imperial"] = 0, ["breton"] = 0, ["nord"] = 0,
        ["redguard"] = 0, ["dark elf"] = -5, ["high elf"] = 0,
        ["orc"] = -5, ["argonian"] = -5, ["khajiit"] = -5,
    },

    ["orc"] = {
        ["orc"] = 0, ["imperial"] = -5, ["breton"] = -5, ["nord"] = -5,
        ["redguard"] = -5, ["dark elf"] = -5, ["high elf"] = -5,
        ["wood elf"] = -5, ["argonian"] = -5, ["khajiit"] = -5,
    },

    ["argonian"] = {
        ["argonian"] = 0, ["imperial"] = -5, ["breton"] = -5, ["nord"] = -5,
        ["redguard"] = -5, ["dark elf"] = -10, ["high elf"] = -5,
        ["wood elf"] = -5, ["orc"] = -5, ["khajiit"] = -5,
    },

    ["khajiit"] = {
        ["khajiit"] = 0, ["imperial"] = -5, ["breton"] = -5, ["nord"] = -5,
        ["redguard"] = -5, ["dark elf"] = -10, ["high elf"] = -5,
        ["wood elf"] = -5, ["orc"] = -5, ["argonian"] = -5,
    }
}
data.raceAlias = {
    ["t_els_cathay"] = "khajiit",
    ["t_els_cathay-raht"] = "khajiit",
    ["t_els_dagi-raht"] = "khajiit",
    ["t_els_ohmes"] = "bosmer",
    ["t_els_ohmes-raht"] = "khajiit",
    ["t_els_suthay"] = "khajiit",
    ["t_val_imga"] = "khajiit",
    ["t_sky_reachman"] = "nord",
    ["t_pya_seaelf"] = "orc",
    ["t_yne_ynesai"] = "breton",
    ["t_cnq_chimeriquey"] = "breton",
    ["t_cnq_keptu"] = "breton",
    ["t_cnq_ayleid"] = "high elf",
    ["t_mw_malahk_orc"] = "orc",
    ["t_sky_hill_giant"] = "orc",
    ["t_hr_riverfolk"] = "breton"
}

data.factionReactions = {
    ["fighters guild"] = {
        ["mages guild"] = 7,      
        ["thieves guild"] = -6,
        ["imperial legion"] = 7, 
        ["imperial cult"] = 3,
        ["hlaalu"] = 0,
        ["redoran"] = 0,
        ["telvanni"] = -3,
        ["tribunal temple"] = 0,
        ["morag tong"] = -6,
        ["t_mw_housedres"] = -6,
        ["t_mw_houseindoril"] = -3,
        ["t_mw_janattasyndicate"] = -3,
        ["t_glb_archaeologicalsociety"] = 3,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 7,
        ["t_mw_eastempirecompany"] = 3,
        ["t_cyr_kingdomanvil"] = 3,
        ["t_cyr_kingdomkvatch"] = 3,
        ["t_cyr_kingdomsutch"] = 3,
        ["t_cyr_itinerantpriests"] = 0,
        ["t_cyr_fightersguild"] = 10,
        ["t_cyr_magesguild"] = 0,
        ["t_cyr_thievesguild"] = -3,
        ["t_cyr_imperiallegion"] = 7
    },

    ["mages guild"] = {
        ["fighters guild"] = 7,
        ["thieves guild"] = 0,
        ["imperial legion"] = 0,
        ["imperial cult"] = 0,
        ["hlaalu"] = 0,
        ["redoran"] = 0,
        ["telvanni"] = -9,
        ["tribunal temple"] = -3,
        ["morag tong"] = -6,
        ["t_mw_housedres"] = -6,
        ["t_mw_houseindoril"] = -6,
        ["t_mw_janattasyndicate"] = -3,
        ["t_glb_archaeologicalsociety"] = 0,
        ["t_glb_astrologicalsociety"] = 3,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 3,
        ["t_mw_eastempirecompany"] = 3,
        ["t_cyr_kingdomanvil"] = 3,
        ["t_cyr_kingdomkvatch"] = 3,
        ["t_cyr_kingdomsutch"] = 3,
        ["t_cyr_itinerantpriests"] = 3,
        ["t_cyr_fightersguild"] = 0,
        ["t_cyr_magesguild"] = 10,
        ["t_cyr_thievesguild"] = 3,
        ["t_cyr_imperiallegion"] = 3,
    },

    ["thieves guild"] = {
        ["fighters guild"] = -6,
        ["mages guild"] = 0,
        ["imperial legion"] = -6,
        ["imperial cult"] = -6,
        ["hlaalu"] = 0,
        ["redoran"] = 0,
        ["telvanni"] = 0,
        ["tribunal temple"] = 0,
        ["morag tong"] = -9,
        ["t_mw_housedres"] = -3,
        ["t_mw_houseindoril"] = -6,
        ["t_mw_janattasyndicate"] = -3,
        ["t_glb_archaeologicalsociety"] = -3,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = -6,
        ["t_mw_eastempirecompany"] = 0,
        ["t_cyr_kingdomanvil"] = -3,
        ["t_cyr_kingdomkvatch"] = -3,
        ["t_cyr_kingdomsutch"] = -3,
        ["t_cyr_itinerantpriests"] = -3,
        ["t_cyr_fightersguild"] = -3,
        ["t_cyr_magesguild"] = 3,
        ["t_cyr_thievesguild"] = 10,
        ["t_cyr_imperiallegion"] = -6,
    },

    ["imperial legion"] = {
        ["fighters guild"] = 7,
        ["mages guild"] = 0,
        ["thieves guild"] = -6,
        ["imperial cult"] = 7,
        ["hlaalu"] = 3,
        ["redoran"] = 0,
        ["telvanni"] = -6,
        ["tribunal temple"] = 0,
        ["morag tong"] = -9,
        ["t_mw_housedres"] = -9,
        ["t_mw_houseindoril"] = -6,
        ["t_mw_janattasyndicate"] = -6,
        ["t_glb_archaeologicalsociety"] = 0,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 7,
        ["t_mw_eastempirecompany"] = 7,
        ["t_cyr_kingdomanvil"] = 7,
        ["t_cyr_kingdomkvatch"] = 7,
        ["t_cyr_kingdomsutch"] = 7,
        ["t_cyr_itinerantpriests"] = 7,
        ["t_cyr_fightersguild"] = 7,
        ["t_cyr_magesguild"] = 3,
        ["t_cyr_thievesguild"] = -6,
        ["t_cyr_imperiallegion"] = 10,
    },

    ["imperial cult"] = {
        ["fighters guild"] = 3,
        ["mages guild"] = 3,
        ["thieves guild"] = -6,
        ["imperial legion"] = 7,
        ["hlaalu"] = 0,
        ["redoran"] = 0,
        ["telvanni"] = 0,
        ["tribunal temple"] = -9,
        ["morag tong"] = -9,
        ["t_mw_housedres"] = -9,
        ["t_mw_houseindoril"] = -6,
        ["t_mw_janattasyndicate"] = -3,
        ["t_glb_archaeologicalsociety"] = 0,
        ["t_glb_astrologicalsociety"] = 3,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 0,
        ["t_mw_eastempirecompany"] = 7,
        ["t_cyr_kingdomanvil"] = 0,
        ["t_cyr_kingdomkvatch"] = 0,
        ["t_cyr_kingdomsutch"] = 0,
        ["t_cyr_itinerantpriests"] = 0,
        ["t_cyr_fightersguild"] = 0,
        ["t_cyr_magesguild"] = 0,
        ["t_cyr_thievesguild"] = -3,
        ["t_cyr_imperiallegion"] = 7,
    },

    ["hlaalu"] = {
        ["fighters guild"] = 0,
        ["mages guild"] = 0,
        ["thieves guild"] = 0,
        ["imperial legion"] = 3,
        ["imperial cult"] = 0,
        ["redoran"] = -9,
        ["telvanni"] = -6,
        ["tribunal temple"] = 0,
        ["morag tong"] = 0,
        ["t_mw_housedres"] = -9,
        ["t_mw_houseindoril"] = -6,
        ["t_mw_janattasyndicate"] = -3,
        ["t_glb_archaeologicalsociety"] = 0,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 0,
        ["t_mw_eastempirecompany"] = 0,
        ["t_cyr_kingdomanvil"] = 0,
        ["t_cyr_kingdomkvatch"] = 0,
        ["t_cyr_kingdomsutch"] = 0,
        ["t_cyr_itinerantpriests"] = 0,
        ["t_cyr_fightersguild"] = 0,
        ["t_cyr_magesguild"] = 0,
        ["t_cyr_thievesguild"] = -3,
        ["t_cyr_imperiallegion"] = 3,
    },

    ["redoran"] = {
        ["fighters guild"] = 0,
        ["mages guild"] = 0,
        ["thieves guild"] = 0,
        ["imperial legion"] = 0,
        ["imperial cult"] = 0,
        ["hlaalu"] = -9,
        ["telvanni"] = -6,
        ["tribunal temple"] = 0,
        ["morag tong"] = 0,
        ["t_mw_housedres"] = 3,
        ["t_mw_houseindoril"] = 7,
        ["t_mw_janattasyndicate"] = 0,
        ["t_glb_archaeologicalsociety"] = -3,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 0,
        ["t_mw_eastempirecompany"] = 3,
        ["t_cyr_kingdomanvil"] = 0,
        ["t_cyr_kingdomkvatch"] = 0,
        ["t_cyr_kingdomsutch"] = 0,
        ["t_cyr_itinerantpriests"] = 0,
        ["t_cyr_fightersguild"] = 0,
        ["t_cyr_magesguild"] = 0,
        ["t_cyr_thievesguild"] = -3,
        ["t_cyr_imperiallegion"] = 0,
    },

    ["telvanni"] = {
        ["fighters guild"] = -3,
        ["mages guild"] = -9,
        ["thieves guild"] = 0,
        ["imperial legion"] = -6,
        ["imperial cult"] = 0,
        ["hlaalu"] = -6,
        ["redoran"] = -6,
        ["tribunal temple"] = -3,
        ["morag tong"] = -6,
        ["t_mw_housedres"] = 7,
        ["t_mw_houseindoril"] = -6,
        ["t_mw_janattasyndicate"] = 0,
        ["t_glb_archaeologicalsociety"] = 0,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 0,
        ["t_mw_eastempirecompany"] = -3,
        ["t_cyr_kingdomanvil"] = 0,
        ["t_cyr_kingdomkvatch"] = 0,
        ["t_cyr_kingdomsutch"] = 0,
        ["t_cyr_itinerantpriests"] = 0,
        ["t_cyr_fightersguild"] = -3,
        ["t_cyr_magesguild"] = -9,
        ["t_cyr_thievesguild"] = 0,
        ["t_cyr_imperiallegion"] = -6,
    },

    ["tribunal temple"] = {
        ["fighters guild"] = 0,
        ["mages guild"] = -3,
        ["thieves guild"] = 0,
        ["imperial legion"] = 0,
        ["imperial cult"] = -9,
        ["hlaalu"] = 0,
        ["redoran"] = 0,
        ["telvanni"] = -3,
        ["morag tong"] = 0,
        ["t_mw_housedres"] = 3,
        ["t_mw_houseindoril"] = 7,
        ["t_mw_janattasyndicate"] = -3,
        ["t_glb_archaeologicalsociety"] = 0,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 0,
        ["t_mw_eastempirecompany"] = 0,
        ["t_cyr_kingdomanvil"] = 0,
        ["t_cyr_kingdomkvatch"] = 0,
        ["t_cyr_kingdomsutch"] = 0,
        ["t_cyr_itinerantpriests"] = 0,
        ["t_cyr_fightersguild"] = 0,
        ["t_cyr_magesguild"] = -3,
        ["t_cyr_thievesguild"] = 0,
        ["t_cyr_imperiallegion"] = 0,
    },

    ["morag tong"] = {
        ["fighters guild"] = -6,
        ["mages guild"] = -6,
        ["thieves guild"] = -9,
        ["imperial legion"] = -9,
        ["imperial cult"] = -9,
        ["hlaalu"] = 0,
        ["redoran"] = 0,
        ["telvanni"] = -6,
        ["tribunal temple"] = 0,
        ["t_mw_housedres"] = -6,
        ["t_mw_houseindoril"] = -6,
        ["t_mw_janattasyndicate"] = 0,
        ["t_glb_archaeologicalsociety"] = 0,
        ["t_glb_astrologicalsociety"] = 0,
        ["t_glb_geographicalsociety"] = 0,
        ["t_cyr_imperialnavy"] = 0,
        ["t_mw_eastempirecompany"] = 0,
        ["t_cyr_kingdomanvil"] = 0,
        ["t_cyr_kingdomkvatch"] = 0,
        ["t_cyr_kingdomsutch"] = 0,
        ["t_cyr_itinerantpriests"] = 0,
        ["t_cyr_fightersguild"] = -6,
        ["t_cyr_magesguild"] = -6,
        ["t_cyr_thievesguild"] = -9,
        ["t_cyr_imperiallegion"] = -9,
    },
    ["t_mw_housedres"] = {
        ["telvanni"] = 7,
        ["t_mw_houseindoril"] = 3,
        ["redoran"] = 3,
        ["tribunal temple"] = 3,
        ["t_mw_eastempirecompany"] = -3,
        ["thieves guild"] = -3,
        ["fighters guild"] = -6,
        ["mages guild"] = -6,
        ["hlaalu"] = -9,
        ["imperial cult"] = -9,
        ["imperial legion"] = -9,
    },

    ["t_mw_houseindoril"] = {
        ["redoran"] = 7,
        ["tribunal temple"] = 7,
        ["t_mw_housedres"] = 3,
        ["fighters guild"] = -3,
        ["telvanni"] = -6,
        ["imperial legion"] = -6,
        ["t_mw_eastempirecompany"] = -6,
        ["hlaalu"] = -6,
        ["imperial cult"] = -6,
        ["thieves guild"] = -6,
    },

    ["t_mw_janattasyndicate"] = {
        ["fighters guild"] = -3,
        ["hlaalu"] = -3,
        ["imperial cult"] = -3,
        ["mages guild"] = -3,
        ["tribunal temple"] = -3,
        ["t_mw_housedres"] = -6,
        ["imperial legion"] = -6,
    },

    ["t_glb_archaeologicalsociety"] = {
        ["t_cyr_magesguild"] = 7,
        ["t_cyr_fightersguild"] = 3,
        ["t_mw_eastempirecompany"] = 3,
        ["fighters guild"] = 3,
        ["t_cyr_kingdomanvil"] = 3,
        ["t_cyr_kingdomsutch"] = 3,
        ["t_cyr_thievesguild"] = -3,
        ["redoran"] = -3,
        ["t_mw_houseindoril"] = -3,
        ["thieves guild"] = -3,
        ["t_mw_housedres"] = -9,
    },

    ["t_glb_astrologicalsociety"] = {
        ["t_glb_archaeologicalsociety"] = 7,
        ["t_cyr_magesguild"] = 3,
        ["mages guild"] = 3,
        ["imperial cult"] = 3,
    },

    ["t_glb_geographicalsociety"] = {
        ["t_glb_astrologicalsociety"] = 7,
        ["t_glb_archaeologicalsociety"] = 7,
        ["t_cyr_itinerantpriests"] = 3,
        ["t_cyr_imperialnavy"] = 3,
    },

    ["t_cyr_imperialnavy"] = {
        ["t_cyr_fightersguild"] = 7,
        ["t_cyr_imperiallegion"] = 7,
        ["t_cyr_kingdomsutch"] = 7,
        ["t_cyr_kingdomanvil"] = 7,
        ["t_cyr_itinerantpriests"] = 7,
        ["t_cyr_magesguild"] = 3,
        ["t_glb_geographicalsociety"] = 3,
        ["t_cyr_thievesguild"] = -6,
    },

    ["t_mw_eastempirecompany"] = {
        ["imperial cult"] = 7,
        ["imperial legion"] = 7,
        ["fighters guild"] = 3,
        ["redoran"] = 3,
        ["mages guild"] = 3,
        ["telvanni"] = -3,
    },

    ["t_cyr_kingdomanvil"] = {
        ["t_cyr_imperiallegion"] = 7,
        ["t_cyr_itinerantpriests"] = 7,
        ["t_cyr_imperialnavy"] = 7,
        ["t_cyr_magesguild"] = 3,
        ["t_cyr_fightersguild"] = 3,
        ["t_glb_archaeologicalsociety"] = 3,
        ["t_cyr_kingdomkvatch"] = 3,
        ["t_cyr_thievesguild"] = -3,
        ["t_cyr_kingdomsutch"] = -3,
    },

    ["t_cyr_kingdomkvatch"] = {
        ["t_cyr_imperiallegion"] = 7,
        ["t_cyr_itinerantpriests"] = 7,
        ["t_cyr_fightersguild"] = 3,
        ["t_cyr_magesguild"] = 3,
        ["t_cyr_kingdomanvil"] = 3,
        ["t_cyr_kingdomsutch"] = 3,
        ["t_cyr_thievesguild"] = -3,
    },

    ["t_cyr_kingdomsutch"] = {
        ["t_cyr_imperiallegion"] = 7,
        ["t_cyr_itinerantpriests"] = 7,
        ["t_cyr_imperialnavy"] = 7,
        ["t_cyr_fightersguild"] = 3,
        ["t_cyr_magesguild"] = 3,
        ["t_glb_archaeologicalsociety"] = 3,
        ["t_cyr_kingdomkvatch"] = 3,
        ["t_cyr_thievesguild"] = -3,
        ["t_cyr_kingdomanvil"] = -3,
    },

    ["t_cyr_itinerantpriests"] = {
        ["t_cyr_imperiallegion"] = 7,
        ["t_cyr_kingdomanvil"] = 7,
        ["t_cyr_kingdomkvatch"] = 7,
        ["t_cyr_kingdomsutch"] = 7,
        ["t_cyr_imperialnavy"] = 7,
        ["t_cyr_magesguild"] = 3,
        ["t_glb_geographicalsociety"] = 3,
        ["t_cyr_thievesguild"] = -3,
    },

    ["t_cyr_fightersguild"] = {
        ["fighters guild"] = 10,
        ["t_cyr_imperiallegion"] = 7,
        ["t_cyr_imperialnavy"] = 7,
        ["t_cyr_magesguild"] = 3,
        ["t_glb_archaeologicalsociety"] = 3,
        ["t_cyr_kingdomsutch"] = 3,
        ["t_cyr_kingdomkvatch"] = 3,
        ["t_cyr_kingdomanvil"] = 3,
        ["t_cyr_thievesguild"] = -3,
    },

    ["t_cyr_magesguild"] = {
        ["t_glb_archaeologicalsociety"] = 7,
        ["t_cyr_imperiallegion"] = 3,
        ["t_cyr_fightersguild"] = 3,
        ["t_cyr_thievesguild"] = 3,
        ["t_cyr_kingdomanvil"] = 3,
        ["t_cyr_kingdomsutch"] = 3,
        ["t_cyr_itinerantpriests"] = 3,
        ["t_cyr_imperialnavy"] = 3,
        ["mages guild"] = 10,
    },

    ["t_cyr_thievesguild"] = {
        ["t_cyr_magesguild"] = 3,
        ["t_cyr_fightersguild"] = -3,
        ["t_glb_archaeologicalsociety"] = -3,
        ["t_cyr_kingdomanvil"] = -3,
        ["t_cyr_kingdomkvatch"] = -3,
        ["t_cyr_kingdomsutch"] = -3,
        ["t_cyr_itinerantpriests"] = -3,
        ["t_cyr_imperiallegion"] = -6,
        ["t_cyr_imperialnavy"] = -6,
        ["thieves guild"] = 10,
    },

    ["t_cyr_imperiallegion"] = {
        ["t_cyr_fightersguild"] = 7,
        ["t_cyr_kingdomanvil"] = 7,
        ["t_cyr_kingdomkvatch"] = 7,
        ["t_cyr_kingdomsutch"] = 7,
        ["t_cyr_itinerantpriests"] = 7,
        ["t_cyr_imperialnavy"] = 7,
        ["t_cyr_magesguild"] = 3,
        ["t_cyr_thievesguild"] = -6,
        ["imperial legion"] = 10,
    },

}

return data


