return {
    "sorceror's",
    "artificer's",
    "enchanter's",
    "crusader's",
    "hiomaste's",
    "mage's",
    "dreamers' bane",
    "the eighth shadow",
    "loyalty's embrace",
    "heart unmourned",
    "pride of narsis",
    "ceremonial",
    "elven",
    "of the summoned",
    "of the summoned",
    "ancient",
    "salvaged",
}