local tooltipsComplete = include("Tooltips Complete.interop")
local tooltipData = {
	{ id = "fur_colovian_helm", description = "An eccentric style of hat native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Helm lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "fur_colovian_helm_red", description = "An eccentric style of red hat native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Helm lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "fur_colovian_helm_white", description = "An eccentric style of white hat native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Helm lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "T_De_Chitin_HelmOpen_01", description = "Offering exceptional freedom of movement despite its rigidity, Chitin helmets are made from laminated insect shell glued with organic resins. Particularly popular amongst the Ashlander tribes, suits of Chitin are commonly worn with a scarf to protect the neck and mouth from blowing sand or ash.", itemType = "armor" },
	{ id = "T_De_Chitin_PauldrL_01", description = "Offering exceptional freedom of movement despite its rigidity, Chitin pauldrons are made from laminated insect shell glued with organic resins. Particularly popular amongst the Ashlander tribes, suits of Chitin are commonly worn with a scarf to protect the neck and mouth from blowing sand or ash.", itemType = "armor" },
	{ id = "T_De_Chitin_PauldrR_01", description = "Offering exceptional freedom of movement despite its rigidity, Chitin pauldrons are made from laminated insect shell glued with organic resins. Particularly popular amongst the Ashlander tribes, suits of Chitin are commonly worn with a scarf to protect the neck and mouth from blowing sand or ash.", itemType = "armor" },
	{ id = "T_De_Dreugh_Boots_01", description = "Remarkably tough for their weight, Dreugh boots are created from the carapace of the ancient aquatic Dreughs inhabiting the seas of Tamriel. Their humanoid structure allows for relatively easy implementation of the shell into a piece of armor, but acquiring the material is another matter.", itemType = "armor" },
	{ id = "T_De_Dreugh_BracerL_01", description = "Remarkably tough for their weight, Dreugh bracers are created from the carapace of the ancient aquatic Dreughs inhabiting the seas of Tamriel. Their humanoid structure allows for relatively easy implementation of the shell into a piece of armor, but acquiring the material is another matter.", itemType = "armor" },
	{ id = "T_De_Dreugh_BracerR_01", description = "Remarkably tough for their weight, Dreugh bracers are created from the carapace of the ancient aquatic Dreughs inhabiting the seas of Tamriel. Their humanoid structure allows for relatively easy implementation of the shell into a piece of armor, but acquiring the material is another matter.", itemType = "armor" },
	{ id = "T_De_Dreugh_Greaves_01", description = "Remarkably tough for their weight, Dreugh greaves are created from the carapace of the ancient aquatic Dreughs inhabiting the seas of Tamriel. Their humanoid structure allows for relatively easy implementation of the shell into a piece of armor, but acquiring the material is another matter.", itemType = "armor" },
	{ id = "T_De_Dreugh_PauldronL_01", description = "Remarkably tough for their weight, Dreugh pauldrons are created from the carapace of the ancient aquatic Dreughs inhabiting the seas of Tamriel. Their humanoid structure allows for relatively easy implementation of the shell into a piece of armor, but acquiring the material is another matter.", itemType = "armor" },
	{ id = "T_De_Dreugh_PauldronR_01", description = "Remarkably tough for their weight, Dreugh pauldrons are created from the carapace of the ancient aquatic Dreughs inhabiting the seas of Tamriel. Their humanoid structure allows for relatively easy implementation of the shell into a piece of armor, but acquiring the material is another matter.", itemType = "armor" },
	{ id = "T_De_HvChit_Boots", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin boots are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_De_HvChit_Cuirass", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin cuirasses are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_De_HvChit_Gauntlet_L", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin gauntlets are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_De_HvChit_Gauntlet_R", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin gauntlets are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_De_HvChit_Greaves", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin greaves are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_De_HvChit_Helmet", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin helmets are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_De_HvChit_Pauldron_L", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin pauldrons are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_De_HvChit_Pauldron_R", description = "Fashioned from laminated insect shell glued with organic resins, Heavy Chitin pauldrons are made even more rigid through the layering of materials and hardening of binding agents with ancient Ashlander techniques, though at the cost of the flexibility usually characteristic of Chitin armor.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_boots", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap boots are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_Bracer_L", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap gauntlets are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_Bracer_R", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap gauntlets are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_Cuirass", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap cuirasses are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_Greaves", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap greaves are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_Helmet", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap helmets are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_Pauldron_L", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap pauldrons are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Dwe_Scrap_Pauldron_R", description = "Fashioned from spare Dwemer metals by inventive outlaws, Dwemer Scrap pauldrons are but one plebeian example of the repurposing of Dwarven materials, an art embraced most famously by the God-King Sotha-Sil.", itemType = "armor" },
	{ id = "T_Imp_Chain_Boots_01", description = "Basic uniform for Legion officers, Imperial Chain boots are crafted by linking small metal rings together to form a mesh, which is then fastened to the body with belts and straps beneath steel boots.", itemType = "armor" },
	{ id = "T_Imp_Chain_GauntletL_01", description = "Basic uniform for Legion officers, Imperial Chain gauntlets are crafted by linking small metal rings together to form a mesh, which is then fastened to the body with belts and straps beneath steel gauntlets.", itemType = "armor" },
	{ id = "T_Imp_Chain_GauntletR_02", description = "Basic uniform for Legion officers, Imperial Chain gauntlets are crafted by linking small metal rings together to form a mesh, which is then fastened to the body with belts and straps beneath steel gauntlets.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Boots_01", description = "An eccentric style of boots native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Boots lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Boots_02", description = "An eccentric style of white boots native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Boots lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Boots_03", description = "An eccentric style of red boots native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Boots lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Boots_04", description = "An eccentric style of black boots native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Boots lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Cuirass_01", description = "An eccentric style of cuirass native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Cuirass lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Cuirass_02", description = "An eccentric style of white cuirass native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Cuirass lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Cuirass_03", description = "An eccentric style of red cuirass native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Cuirass lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_Cuirass_04", description = "An eccentric style of black cuirass native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Cuirass lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntL_01", description = "An eccentric style of gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntL_02", description = "An eccentric style of white gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntL_03", description = "An eccentric style of red gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntL_04", description = "An eccentric style of black gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntR_01", description = "An eccentric style of gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntR_02", description = "An eccentric style of white gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntR_03", description = "An eccentric style of red gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_GauntR_04", description = "An eccentric style of black gauntlets native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What Colovian Fur Gauntlets lack in protection they make up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_HelmBl_01", description = "An eccentric style of black hat native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Helm lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_ColFur_HelmR_01", description = "An eccentric style of red hat native to the Colovian Highlands of Cyrodiil, the heart of the Empire. What the Colovian Fur Helm lacks in protection it makes up for in warmth.", itemType = "armor" },
	{ id = "T_Imp_Domina_Boots_01", description = "Specially tailored for the ladies, Domina boots are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Domina_Cuirass_01", description = "Specially tailored for the ladies, Domina cuirasses are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Domina_GauntletL_01", description = "Specially tailored for the ladies, Domina gauntlets are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Domina_GauntletR_01", description = "Specially tailored for the ladies, Domina gauntlets are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Domina_Greaves_01", description = "Specially tailored for the ladies, Domina greaves are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Domina_Helm_01", description = "Specially tailored for the ladies, Domina helmets are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Domina_PauldronL_01", description = "Specially tailored for the ladies, Domina pauldrons are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Domina_PauldronR_01", description = "Specially tailored for the ladies, Domina pauldrons are form-fitting, fashioned from leather, and colored purple with a dye derived from Netch jelly.", itemType = "armor" },
	{ id = "T_Imp_Gold_Cuirass_01", description = "Specially tailored for the ladies, Gold cuirasses are crafted from steel overlayed with gold plate, and while effective in combat the ease with which its golden exterior might be scraped off leads many to relegate the armor to mere status symbol.", itemType = "armor" },
	{ id = "T_Imp_Gold_Helm_01", description = "Specially tailored for the ladies, Gold helmets are crafted from steel overlayed with gold plate, and while effective in combat the ease with which its golden exterior might be scraped off leads many to relegate the armor to mere status symbol.", itemType = "armor" },
	{ id = "T_Imp_Gold_PauldronL_01", description = "Specially tailored for the ladies, Gold pauldrons are crafted from steel overlayed with gold plate, and while effective in combat the ease with which its golden exterior might be scraped off leads many to relegate the armor to mere status symbol.", itemType = "armor" },
	{ id = "T_Imp_Gold_PauldronR_01", description = "Specially tailored for the ladies, Gold pauldrons are crafted from steel overlayed with gold plate, and while effective in combat the ease with which its golden exterior might be scraped off leads many to relegate the armor to mere status symbol.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_Boots_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale boots are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_Cuirass_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale cuirasses are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_GauntletL_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale gauntlets are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_GauntletR_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale gauntlets are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_Greaves_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale greaves are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_Helm_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale helmets are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_PauldronL_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale pauldrons are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_Newtscale_PauldronR_01", description = "Native to Nibenay, the eastern portion of Cyrodiil and considered the cultural center of the Empire, Newtscale pauldrons are fashioned from the giant rivernewts of its eponymous river basin.", itemType = "armor" },
	{ id = "T_Imp_StuddedLeather_Boots_01", description = "Less commonly employed by the Legion, Imperial Studded Leather boots are fashioned from tough leather that has been reinforced with close-set steel rivets.", itemType = "armor" },
	{ id = "T_Imp_StuddedLeather_BracerL_01", description = "Less commonly employed by the Legion, Imperial Studded Leather bracers are fashioned from tough leather that has been reinforced with close-set steel rivets.", itemType = "armor" },
	{ id = "T_Imp_StuddedLeather_BracerR_01", description = "Less commonly employed by the Legion, Imperial Studded Leather bracers are fashioned from tough leather that has been reinforced with close-set steel rivets.", itemType = "armor" },
	{ id = "T_Imp_StuddedLeather_Greaves_01", description = "Less commonly employed by the Legion, Imperial Studded Leather greaves are fashioned from tough leather that has been reinforced with close-set steel rivets.", itemType = "armor" },
	{ id = "T_Imp_StuddedLeather_Helm_01", description = "Less commonly employed by the Legion, Imperial Studded Leather helms are fashioned from tough leather that has been reinforced with close-set steel rivets.", itemType = "armor" },
	{ id = "T_Imp_StuddedLeather_PauldrL_01", description = "Less commonly employed by the Legion, Imperial Studded Leather pauldrons are fashioned from tough leather that has been reinforced with close-set steel rivets.", itemType = "armor" },
	{ id = "T_Imp_StuddedLeather_PauldrR_01", description = "Less commonly employed by the Legion, Imperial Studded Leather pauldrons are fashioned from tough leather that has been reinforced with close-set steel rivets.", itemType = "armor" },
	{ id = "T_Nor_Iron_Boots_01", description = "Native to the northern province of Skyrim, Nordic Iron boots are crafted from common iron but designed in the cultural flavour of the Nords. While stronger than both Imperial iron and steel, it is notably heavier.", itemType = "armor" },
	{ id = "T_Nor_Iron_GauntletL_01", description = "Native to the northern province of Skyrim, Nordic Iron gauntlets are crafted from common iron but designed in the cultural flavour of the Nords. While stronger than both Imperial iron and steel, it is notably heavier.", itemType = "armor" },
	{ id = "T_Nor_Iron_GauntletR_01", description = "Native to the northern province of Skyrim, Nordic Iron gauntlets are crafted from common iron but designed in the cultural flavour of the Nords. While stronger than both Imperial iron and steel, it is notably heavier.", itemType = "armor" },
	{ id = "T_Nor_Iron_Greaves_01", description = "Native to the northern province of Skyrim, Nordic Iron greaves are crafted from common iron but designed in the cultural flavour of the Nords. While stronger than both Imperial iron and steel, it is notably heavier.", itemType = "armor" },
	{ id = "T_Nor_Iron_PauldronL_01", description = "Native to the northern province of Skyrim, Nordic Iron pauldrons are crafted from common iron but designed in the cultural flavour of the Nords. While stronger than both Imperial iron and steel, it is notably heavier.", itemType = "armor" },
	{ id = "T_Nor_Iron_PauldronR_01", description = "Native to the northern province of Skyrim, Nordic Iron pauldrons are crafted from common iron but designed in the cultural flavour of the Nords. While stronger than both Imperial iron and steel, it is notably heavier.", itemType = "armor" },
	{ id = "T_Nor_Trollbone_Boots_01", description = "As opposed to the more refined process of making Bonemold, Nordic Trollbone boots are fashioned crudely from the raw bone and hide of the troll, a creature native to the northern province of Skyrim.", itemType = "armor" },
	{ id = "T_Nor_Trollbone_BracerL_01", description = "As opposed to the more refined process of making Bonemold, Nordic Trollbone bracers are fashioned crudely from the raw bone and hide of the troll, a creature native to the northern province of Skyrim.", itemType = "armor" },
	{ id = "T_Nor_Trollbone_BracerR_01", description = "As opposed to the more refined process of making Bonemold, Nordic Trollbone bracers are fashioned crudely from the raw bone and hide of the troll, a creature native to the northern province of Skyrim.", itemType = "armor" },
	{ id = "T_Nor_Trollbone_Greaves_01", description = "As opposed to the more refined process of making Bonemold, Nordic Trollbone greaves are fashioned crudely from the raw bone and hide of the troll, a creature native to the northern province of Skyrim.", itemType = "armor" },
	{ id = "T_Nor_Trollbone_PauldronL_01", description = "As opposed to the more refined process of making Bonemold, Nordic Trollbone pauldrons are fashioned crudely from the raw bone and hide of the troll, a creature native to the northern province of Skyrim.", itemType = "armor" },
	{ id = "T_Nor_Trollbone_PauldronR_01", description = "As opposed to the more refined process of making Bonemold, Nordic Trollbone pauldrons are fashioned crudely from the raw bone and hide of the troll, a creature native to the northern province of Skyrim.", itemType = "armor" }
}

local function initialized()
    if tooltipsComplete then
        for _, data in ipairs(tooltipData) do
            tooltipsComplete.addTooltip(data.id, data.description, data.itemType)
        end
    end
end
event.register("initialized", initialized)

-- key - Generic keys or other objects used to unlock or activate objects, such as Propylon Indices. Lockpicks do NOT fall under this category.
-- quest - Items required for the completion of a quest.
-- unique - Notable items which may only be found once or rewarded once after a quest, generally have the same appearance as other generic items.
-- artifact - Objects with a unique appearance and lore significance, such as Daedric and Aedric objects.
-- armor - Regular and generic enchanted armor and shields.
-- weapon - Regular and generic enchanted weapons and ammunition.
-- tool - Objects centered around a game mechanic such as alchemical apparatus, lockpicks, probes, and repair hammers.
-- soulGem - Empty gems or similar added object capable of holding a soul.
-- creature - Any creature which might have its soul trapped, descriptions should generally be about the creature in question.
-- misc - Clutter, coins, decorative objects, and any other items that don't fall into another category.
-- light - Objects that emit light and may be picked up and/or equipped by the player.
-- book - Books, notes, and any other readable object the player may acquire.
-- clothing - Regular and generic enchanted clothing and jewelry.
-- alchemy - Magical potions that are pre-made or otherwise have unique IDs, beverages like Sujamma do NOT fall under this category.
-- ingredients - Any items that may be used to brew potions or poisons, as well as beverages like Sujamma.
-- scroll - Enchanted scrolls used to cast magical spells.