local data = {}

-- footprint statics keywords e.g. footPrint object ids examples:
-- 'ab01fpFootR', 'ab01fpBoot2L' (modPrefix+keyword+side)
data.fpStaTypes = {'Anml','Boot','Boot2','Foot','Hoof','Mech','Mech2','Paw','Rept','Skel','Taln'}

-- recognized creature lowercased meshes keywords
data.creStaTypes = {
['almalexia'] = 'Foot',
['ashghoul'] = 'Foot',
['ashvampire'] = 'Foot',
['ashzombie'] = 'Foot',
['atronach_fire'] = 'Boot2',
['atronach_frost'] = 'Boot',
['atronach_storm'] = 'Boot',
['bear_black_larger'] = 'Paw',
['bear_blond_larger'] = 'Paw',
['bear_brown_larger'] = 'Paw',
['bonewalker'] = 'Foot',
['byagram'] = 'Taln',
['cavemudcrab'] = 'Taln',
['centurionspider'] = 'Taln',
['clannfear'] = 'Rept',
['clannfear_daddy'] = 'Paw',
['corprus_stalker'] = 'Foot',
['cr_draugr'] = 'Boot2',
['daedroth'] = 'Foot',
['dagothr'] = 'Boot',
['draugrlord'] = 'Boot2',
['dremora'] = 'Boot2',
['durzog'] = 'Rept',
['durzogcollar'] = 'Rept',
['duskyalit'] = 'Rept',
['fabricant'] = 'Mech',
['fabricant_hulking'] = 'Taln',
['fabricant_imperfect'] = 'Boot',
['frostgiant'] = 'Paw',
['goblin01'] = 'Rept',
['goblin02'] = 'Rept',
['goblin03'] = 'Rept',
['golden saint'] = 'Boot2',
['greatbonewalker'] = 'Boot',
['guar'] = 'Rept',
['guar_white'] = 'Rept',
['guar_withpack'] = 'Rept',
['hircine'] = 'Boot',
['hircine_bear_larger'] = 'Paw',
['hircinewolf'] = 'Paw',
['hunger'] = 'Mech',
['ice troll'] = 'Paw',
['iceminion'] = 'Boot',
['icemraider'] = 'Hoof',
['kwama queen'] = 'Rept',
['kwama warior'] = 'Rept',
['kwama worker'] = 'Rept',
['lame_corprus'] = 'Foot',
['leastkagouti'] = 'Rept',
['liche_king'] = 'Skel',
['lordvivec'] = 'Foot',
['minescrib'] = 'Taln',
['mount'] = 'Hoof',
['nixhound'] = 'Rept',
['packrat'] = 'Rept',
['rust rat'] = 'Rept',
['scamp_fetch'] = 'Rept',
['scrib'] = 'Taln',
['shalk'] = 'Taln',
['skeleton'] = 'Skel',
['skinnpc'] = 'Paw',
['steam_centurions'] = 'Mech2',
['udyrfrykte'] = 'Paw',
['unDeadwolf_2'] = 'Paw',
['war_wt_armor'] = 'Rept',
['wingedtwilight'] = 'Rept',
['wolf_black'] = 'Paw',
['wolf_red'] = 'Paw',
['wolf_white'] = 'Paw',
}

return data