local M = {
    L10N = 'AutoZoom',
    PAGE_KEY = 'AutoZoomPage',
    GROUP_KEY = 'SettingsPlayerAutoZoom',
    RAY_DISTANCE = 5000,
    DEFAULTS = {
        enableInFirstPerson = true,
        enableInThirdPerson = true,
        triggerNPC = true,
        triggerCreatures = true,
        triggerActivators = true,
        triggerContainers = true,
        triggerDoors = true,
        triggerWeapons = true,
        triggerArmor = true,
        triggerClothing = true,
        triggerIngredients = true,
        triggerBooks = true,
        triggerLights = true,
        triggerMisc = true,
        triggerPotions = true,
        triggerLockpicks = true,
        triggerProbes = true,
        triggerRepairs = true,
        triggerApparatus = true,
        manualZoomKey = 'key_b',
        focusTime = 0.4,
        zoomSpeed = 4.0,
        magnification = 4.0,
        snapBackTime = 0.25,
        debugLogging = false,
    },
    TARGET_GRACE_TIME = 0.2,
    DEBUG_LOG_INTERVAL = 0.25,
}

return M
