local trophytaker = require("JC_Trophy.interop")

	trophytaker.addItem("horse", "T_IngFood_MeatHorse_01")
	trophytaker.addItem("chicken", "T_IngFood_MeatChicken_01")
	trophytaker.addItem("goat", "T_IngCrea_GoatPelt_01")
	trophytaker.addItem("spikeworm", "T_IngCrea_Spikeworm_01")
	trophytaker.addItem("boar", "T_IngFood_MeatBoar_02")
	trophytaker.addItem("wormmouth", "T_IngCrea_WormmouthHide_01")
	trophytaker.addItem("squirrel", "T_IngFood_MeatSqrl_01")
	trophytaker.addItem("cow", "T_IngFood_MeatBeef_01")
	trophytaker.addItem("danswyrm", "T_IngCrea_DWyrmGland")
	trophytaker.addItem("antler", "T_Nor_Antler_01")
	trophytaker.addItem("sabre_cat", "T_IngCrea_SaberCatTooth_01")
	trophytaker.addItem("mammoth", "T_IngCrea_Ivory")
	trophytaker.addItem("raki", "T_IngCrea_RakiTeeth_01")
	trophytaker.addItem("iron_toad", "T_IngCrea_IronToadHide")
	trophytaker.addItem("snow_ray", "T_IngCrea _SnowraySting_01")
	trophytaker.addItem("minotaur", "T_IngCrea_Minotaurhorn_01")
	trophytaker.addItem("kobold", "T_IngCrea_KoboldTongue_01")
	trophytaker.addItem("giant", "tt_meat")
	trophytaker.addItem("ice_wraith", "T_IngCrea_IcewraithTeeth_01")
	trophytaker.addItem("hagraven", "T_IngCrea_HagravenFeathers_01")

	trophytaker.addNameLink("horse","horse")
	trophytaker.addNameLink("boar","boar")
	trophytaker.addNameLink("wormmouth","wormmouth")
	trophytaker.addNameLink("spikeworm","spikeworm")
	trophytaker.addNameLink("goat","goat")
	trophytaker.addNameLink("chicken","chicken")
	trophytaker.addNameLink("squirrel","squirrel")
	trophytaker.addNameLink("cow","cow")
	trophytaker.addNameLink("danswyrm","danswyrm")
	trophytaker.addNameLink("elk","antler")
	trophytaker.addNameLink("sabre_cat","sabre_cat")
	trophytaker.addNameLink("sabre cat","sabre_cat")
	trophytaker.addNameLink("mammoth","mammoth")
	trophytaker.addNameLink("raki","raki")
	trophytaker.addNameLink("irontoad","iron_toad")
	trophytaker.addNameLink("snowray","snow_ray")
	trophytaker.addNameLink("minotaur","minotaur")
	trophytaker.addNameLink("kobold","kobold")
	trophytaker.addNameLink("hagraven","hagraven")
	trophytaker.addNameLink("sky_giant","giant")
	trophytaker.addNameLink("ice wraith","ice_wraith")
