return
{
["r\\guar.nif"] = {ar = 20},
["r\\guar_withpack.nif"] = {ar = 30},
["r\\duskyalit.nif"] = {ar = 20},
["r\\leastkagouti.nif"] = {ar = 30},
["r\\kagouti_dire.nif"] = {ar = 40},
["r\\cavemudcrab.nif"] = {ar = 50},
["r\\mudcrab_king.nif"] = {ar = 60},
["r\\mudcrab_titan.nif"] = {ar = 80},
["r\\mudcrab_rock.nif"] = {ar = 100},
["r\\dreugh.nif"] = {ar = 50},
["r\\dreugh_soldier.nif"] = {ar = 80},
["r\\dreugh_land.nif"] = {ar = 80},
["r\\minescrib.nif"] = {ar = 5},
["r\\slaughterfish.nif"] = {ar = 3},
["r\\slaughterfish_electro.nif"] = {ar = 3},
["r\\nixhound.nif"] = {ar = 20},
["r\\nix_mount.nif"] = {ar = 30},
["r\\kwama worker.nif"] = {ar = 40},
["r\\kwama warior.nif"] = {ar = 60},
["r\\kwama queen.nif"] = {ar = 10},
["r\\shalk.nif"] = {ar = 30},
["r\\netch_bull.nif"] = {ar = 30},
["r\\netch_betty.nif"] = {ar = 10},
["r\\cliffracer.nif"] = {ar = 3},
["r\\kwama forager.nif"] = {ar = 0},
["r\\rust rat.nif"] = {ar = 3},
["r\\packrat.nif"] = {ar = 20},
["r\\babelfish.nif"] = {ar = 3},
["r\\durzog_collar.nif"] = {ar = 50},
["r\\durzog.nif"] = {ar = 40},
["r\\fabricant_hulking.nif"] = {ar = 150, at = 1},
["r\\fabricant.nif"] = {ar = 100, at = 1},
["r\\bear_black_larger.nif"] = {ar = 40},
["r\\bear_brown_larger.nif"] = {ar = 40},
["r\\bear_blond_larger.nif"] = {ar = 40},
["r\\wolf_black.nif"] = {ar = 20},
["r\\wolf_red.nif"] = {ar = 20},
["r\\wolf_white.nif"] = {ar = 20},
["r\\frostgiant.nif"] = {ar = 150},
["r\\spriggan.nif"] = {ar = 50},
["r\\horker.nif"] = {ar = 5},
["r\\horker_larger.nif"] = {ar = 10},
["r\\udyrfrykte.nif"] = {ar = 50},
["r\\ice troll.nif"] = {ar = 80},

["r\\skeleton_weak.nif"] = {ar = 10},
["r\\skeleton.nif"] = {ar = 20},
["r\\skeleton_archer.nif"] = {ar = 30, at = 0},
["r\\skeleton_warrior.nif"] = {ar = 50, at = 2},
["r\\skeleton_champion.nif"] = {ar = 60, at = 1},
["r\\skeleton_knight.nif"] = {ar = 80, at = 2},
["r\\skeleton_nord.nif"] = {ar = 80, at = 2},
["r\\skeleton_pirate.nif"] = {ar = 20},
["r\\skeleton_pirate_captain.nif"] = {ar = 30},
["r\\skeleton_berserk.nif"] = {ar = 40},
["r\\skeleton_mage.nif"] = {ar = 20},
["r\\liche.nif"] = {ar = 50},
["r\\liche_king.nif"] = {ar = 100, at = 1},
["r\\lich_elder.nif"] = {ar = 100, at = 1},
["r\\bonelord.nif"] = {ar = 20},
["r\\undeadwolf_2.nif"] = {ar = 20},
["r\\bonewalker_weak.nif"] = {ar = 10},
["r\\bonewalker.nif"] = {ar = 10},
["r\\greatbonewalker.nif"] = {ar = 20},
["r\\ancestorghost.nif"] = {ar = 0},
["r\\ghost_great.nif"] = {ar = 0},
["r\\dwarvenspecter.nif"] = {ar = 0},
["r\\cr_draugr.nif"] = {ar = 50},
["r\\draugrlord.nif"] = {ar = 60},
["r\\draugr.nif"] = {ar = 50},
["r\\draugr_fem.nif"] = {ar = 50},
["r\\draugr_soldier.nif"] = {ar = 80, at = 1},
["r\\draugr_warrior.nif"] = {ar = 100, at = 2},
["r\\draugr_general.nif"] = {ar = 150, at = 2},
["r\\draugr_priest.nif"] = {ar = 50, at = 0},

["r\\scamp_fetch.nif"] = {ar = 5},
["r\\clannfear.nif"] = {ar = 30},
["r\\clannfear_lesser.nif"] = {ar = 20},
["r\\vermai.nif"] = {ar = 10},
["r\\daedroth.nif"] = {ar = 40},
["r\\clannfear_daddy.nif"] = {ar = 60},
["r\\ogrim_titan.nif"] = {ar = 80},
["r\\hunger.nif"] = {ar = 10},
["r\\wingedtwilight.nif"] = {ar = 20},
["r\\daedraspider.nif"] = {ar = 10},
["r\\xivilai.nif"] = {ar = 50},
["r\\atronach_fire.nif"] = {ar = 50},
["r\\atronach_frost.nif"] = {ar = 100, mat = "Ice"},
["r\\atronach_storm.nif"] = {ar = 150, mat = "Stone"},
["r\\atronach_flame_lord.nif"] = {ar = 100},
["r\\atronach_frost_lord.nif"] = {ar = 150, mat = "Ice"},
["r\\atronach_storm_lord.nif"] = {ar = 200, mat = "Stone"},
["r\\dremora.nif"] = {ar = 100, at = 2},
["r\\dremora_lord.nif"] = {ar = 150, at = 2},
["r\\dremora_mage.nif"] = {ar = 30},
["r\\dremora_archer.nif"] = {ar = 50, at = 0},
["r\\golden saint.nif"] = {ar = 120, at = 1},
["r\\mazken.nif"] = {ar = 80, at = 0},
["r\\skaafin.nif"] = {ar = 80, at = 1},
["r\\skaafin_archer.nif"] = {ar = 50, at = 0},
["r\\xivkyn.nif"] = {ar = 100},

["r\\corprus_stalker.nif"] = {ar = 5},
["r\\lame_corprus.nif"] = {ar = 20},
["r\\ash_ghoul.nif"] = {ar = 20},
["r\\ash_slave.nif"] = {ar = 10},
["r\\ash_zombie.nif"] = {ar = 10},
["r\\ashghoul.nif"] = {ar = 20},
["r\\ascendedsleeper.nif"] = {ar = 50},
["r\\ashzombie.nif"] = {ar = 10},
["r\\ashvampire.nif"] = {ar = 150},
["r\\ash_ghoul_high.nif"] = {ar = 30},
["r\\ash_revenant.nif"] = {ar = 80, at = 1},
["r\\ash_ghoul_warrior.nif"] = {ar = 100, at = 1},
["r\\ash_zombie_warrior.nif"] = {ar = 100, at = 1},

["r\\g_centurionspider.nif"] = {ar = 150},
["r\\centurion_spider_miner.nif"] = {ar = 150},
["r\\centurion_spider_tower.nif"] = {ar = 150},
["r\\sphere_centurions.nif"] = {ar = 200},
["r\\spherearcher.nif"] = {ar = 200},
["r\\steam_centurions.nif"] = {ar = 200},
["r\\centurion_mace.nif"] = {ar = 200},
["r\\centurion_sword.nif"] = {ar = 200},
["r\\centurion_tank.nif"] = {ar = 250},
["r\\centurion_weapon.nif"] = {ar = 200},
["r\\fabricant_imperfect.nif"] = {ar = 200},

["r\\goblin.nif"] = {ar = 20},
["r\\goblin01.nif"] = {ar = 30},
["r\\goblin02.nif"] = {ar = 50, at = 0},
["r\\goblin03.nif"] = {ar = 60, at = 0},
["r\\goblin_shaman.nif"] = {ar = 20},
["r\\iceminion.nif"] = {ar = 20, at = 0},
["r\\iceminion2.nif"] = {ar = 30, at = 0},
["r\\bm_riekling_shaman.nif"] = {ar = 30, at = 0},
["r\\bm_riekling_berserk.nif"] = {ar = 30, at = 0},
["r\\bm_riekling_warrior.nif"] = {ar = 50, at = 0},
["r\\bm_riekling_heavy.nif"] = {ar = 100, at = 2},
["r\\bm_riekling_chieftain.nif"] = {ar = 80, at = 1},
["r\\icemraider.nif"] = {ar = 30, at = 0},
["r\\bm_riekling_mounted_war.nif"] = {ar = 50, at = 0},



["oaab\\r\\ironatronach.nif"] = {ar = 200, mat = "Metal"},
["oaab\\r\\atro_storm_monarch.nif"] = {ar = 200, mat = "Stone"},
["oaab\\r\\mazken.nif"] = {ar = 80, at = 0},
["oaab\\r\\herne.nif"] = {ar = 10},
["oaab\\r\\cent_sphere_chute.nif"] = {ar = 200},
["oaab\\r\\bat.nif"] = {ar = 3},
["oaab\\r\\landdreugh.nif"] = {ar = 80},
["oaab\\r\\kwama grubber.nif"] = {ar = 20},
["oaab\\r\\r0_s-fish_blind.nif"] = {ar = 3},
["oaab\\r\\tr_siltstrider_vo.nif"] = {ar = 40},
["oaab\\r\\spider_black.nif"] = {ar = 10},
["oaab\\r\\lidicus_cspider.nif"] = {ar = 10},
["oaab\\r\\dwspecter_f.nif"] = {ar = 0},
["oaab\\r\\dwspecterwep.nif"] = {ar = 0},
["oaab\\r\\dwspecterwep_f.nif"] = {ar = 0},
["oaab\\r\\undeadglassknight.nif"] = {ar = 50},
["oaab\\r\\liche_ancient.nif"] = {ar = 80, at = 1},
["oaab\\r\\liche_ancient2.nif"] = {ar = 80, at = 1},
["oaab\\r\\skeleton_arg01.nif"] = {ar = 30},
["oaab\\r\\skeleton_arg00.nif"] = {ar = 30},
["oaab\\r\\skeleton_arg02.nif"] = {ar = 30},
["oaab\\r\\zombiefresh.nif"] = {ar = 10},
["oaab\\r\\zombiefresh2.nif"] = {ar = 10},
["oaab\\r\\zombiefresh3.nif"] = {ar = 10},


["tr\\cr\\tr_storm_tyrant.nif"] = {ar = 200, mat = "Stone"},
["tr\\cr\\tr_cr_devourer_01.nif"] = {ar = 30},
["tr\\cr\\tr_dremora.nif"] = {ar = 100, at = 2},
["tr\\cr\\tr_dremora_archer.nif"] = {ar = 50, at = 0},
["tr\\cr\\tr_dremora_caster.nif"] = {ar = 30},
["tr\\cr\\tr_dridrea_vo.nif"] = {ar = 20},
["tr\\cr\\tr_clannfear_lesser.nif"] = {ar = 20},
["tr\\cr\\tr_cr_seducer_01.nif"] = {ar = 20},
["tr\\cr\\tr_cr_seducerdark_01.nif"] = {ar = 20},
["tr\\cr\\tr_cr_seducerdark_02.nif"] = {ar = 20},
["tr\\cr\\tr_vermai.nif"] = {ar = 10},
["tr\\cr\\tr_xivilai.nif"] = {ar = 50},
["tr\\cr\\tr_dwemer.nif"] = {ar = 200},
["tr\\cr\\tr_dwe_colos_01.nif"] = {ar = 250},
["tr\\cr\\tr_golem_mud_vo.nif"] = {ar = 50, mat = "Dirt"},
["tr\\cr\\tr_kobold_01.nif"] = {ar = 20},
["tr\\cr\\tr_landdreugh.nif"] = {ar = 80},
["tr\\cr\\tr_troll_armor_01.nif"] = {ar = 150, at = 2},
["tr\\cr\\tr_troll_armor_02.nif"] = {ar = 150, at = 2},
["tr\\cr\\tr_troll_armor_03.nif"] = {ar = 150, at = 2},
["tr\\cr\\tr_troll_armor_04.nif"] = {ar = 150, at = 2},
["tr\\cr\\tr_troll_cave01.nif"] = {ar = 30},
["tr\\cr\\tr_troll_cave02.nif"] = {ar = 30},
["tr\\cr\\tr_troll_cave03.nif"] = {ar = 30},
["tr\\cr\\tr_troll_cave04.nif"] = {ar = 30},
["tr\\cr\\tr_troll_frost01.nif"] = {ar = 40},
["tr\\cr\\tr_troll_frost02.nif"] = {ar = 40},
["tr\\cr\\tr_troll_frost03.nif"] = {ar = 40},
["tr\\cr\\tr_troll_frost04.nif"] = {ar = 40},
["tr\\cr\\tr_seacrab.nif"] = {ar = 40},
["tr\\cr\\tr_liche_greater.nif"] = {ar = 100},
["tr\\cr\\tr_skeleton_arise01.nif"] = {ar = 20},
["tr\\cr\\tr_skeleton_arise02.nif"] = {ar = 20},
["tr\\cr\\tr_skeleton_arise03.nif"] = {ar = 20},
["tr\\cr\\tr_skeleton_arise04.nif"] = {ar = 20},
["tr\\cr\\tr_skeleton_khajiit.nif"] = {ar = 20},
["tr\\cr\\tr_skeleton_orc.nif"] = {ar = 30},
["tr\\cr\\tr_goblinshaman.nif"] = {ar = 20},
["tr\\cr\\tr_direkagouti.nif"] = {ar = 40},
["tr\\cr\\tr_hirv.nif"] = {ar = 20},
["tr\\cr\\tr_hoom.nif"] = {ar = 20},
["tr\\cr\\tr_juvriverstrider.nif"] = {ar = 5},
["tr\\cr\\tr_molecrab_vo.nif"] = {ar = 40},
["tr\\cr\\tr_muckleech_vo.nif"] = {ar = 30},
["tr\\cr\\tr_swampfly_vo.nif"] = {ar = 5},
["tr\\cr\\tr_nixmount.nif"] = {ar = 40},
["tr\\cr\\tr_ornada_vo.nif"] = {ar = 20},
["tr\\cr\\tr_ornada_clutch_vo.nif"] = {ar = 20},
["tr\\cr\\tr_parastylus_vo.nif"] = {ar = 40},
["tr\\cr\\tr_plainstrider_vo.nif"] = {ar = 60},
["tr\\cr\\tr_cr_redoranhound_01.nif"] = {ar = 20},
["tr\\cr\\tr_cr_redoranhound_02.nif"] = {ar = 20},
["tr\\cr\\tr_cr_redoranhound_03.nif"] = {ar = 20},
["tr\\cr\\tr_cr_redoranhound_04.nif"] = {ar = 20},
["tr\\cr\\tr_cr_redoranhound_05.nif"] = {ar = 20},
["tr\\cr\\tr_cr_redoranhound_06.nif"] = {ar = 20},
["tr\\cr\\tr_skyrender.nif"] = {ar = 40},
["tr\\cr\\tr_skyrenderm.nif"] = {ar = 50},
["tr\\cr\\tr_siltstrider_vo.nif"] = {ar = 60},
["tr\\cr\\tr_swamp_troll.nif"] = {ar = 30},
["tr\\cr\\tr_velk.nif"] = {ar = 20},
["tr\\cr\\tr_ancestorghostwpn.nif"] = {ar = 0},
["tr\\cr\\tr_mummy_vo.nif"] = {ar = 50},
["tr\\cr\\tr_mummy_02.nif"] = {ar = 50},
["tr\\cr\\tr_procebonewalker_01.nif"] = {ar = 20},
["tr\\cr\\tr_revbonewalker_01.nif"] = {ar = 20},
["tr\\cr\\tr_cr_ushudimmu_01.nif"] = {ar = 50},
}