local I = require('openmw.interfaces')
local DEFAULTS = require('scripts.tshared').DEFAULTS

I.Settings.registerGroup {
    key              = 'SettingsTP',
    page             = 'ThievesPickpocket',
    l10n             = 'ThievesPickpocket',
    name             = 'settings_groupName',
    permanentStorage = true,
    order            = 1,
    settings = {
        {
            key         = 'MOD_ENABLED',
            name        = 'mod_enabled_name',
            description = 'mod_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.MOD_ENABLED,
        },
        {
            key         = 'STEAL_ITEMS',
            name        = 'steal_items_name',
            description = 'steal_items_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.STEAL_ITEMS,
        },
        {
            key         = 'STEAL_RADIUS',
            name        = 'steal_radius_name',
            description = 'steal_radius_desc',
            renderer    = 'number',
            default     = DEFAULTS.STEAL_RADIUS,
            argument    = { integer = true, min = 50, max = 500 },
        },
        {
            key         = 'STEAL_CHANCE',
            name        = 'steal_chance_name',
            description = 'steal_chance_desc',
            renderer    = 'number',
            default     = DEFAULTS.STEAL_CHANCE,
            argument    = { min = 0.0, max = 1.0 },
        },
        {
            key         = 'MIN_GOLD',
            name        = 'min_gold_name',
            description = 'min_gold_desc',
            renderer    = 'number',
            default     = DEFAULTS.MIN_GOLD,
            argument    = { integer = true, min = 1, max = 1000 },
        },
        {
            key         = 'MAX_GOLD',
            name        = 'max_gold_name',
            description = 'max_gold_desc',
            renderer    = 'number',
            default     = DEFAULTS.MAX_GOLD,
            argument    = { integer = true, min = 1, max = 5000 },
        },
        {
            key         = 'AGILITY_MIN',
            name        = 'agility_min_name',
            description = 'agility_min_desc',
            renderer    = 'number',
            default     = DEFAULTS.AGILITY_MIN,
            argument    = { integer = true, min = 1, max = 100 },
        },
        {
            key         = 'SNEAK_MIN',
            name        = 'sneak_min_name',
            description = 'sneak_min_desc',
            renderer    = 'number',
            default     = DEFAULTS.SNEAK_MIN,
            argument    = { integer = true, min = 1, max = 100 },
        },
        {
            key         = 'SCAN_INTERVAL',
            name        = 'scan_interval_name',
            description = 'scan_interval_desc',
            renderer    = 'number',
            default     = DEFAULTS.SCAN_INTERVAL,
            argument    = { integer = true, min = 1, max = 10 },
        },
        {
            key         = 'USE_DISPOSITION',
            name        = 'use_disposition_name',
            description = 'use_disposition_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.USE_DISPOSITION,
        },
        {
            key         = 'MAX_DISPOSITION',
            name        = 'max_disposition_name',
            description = 'max_disposition_desc',
            renderer    = 'number',
            default     = DEFAULTS.MAX_DISPOSITION,
            argument    = { integer = true, min = 1, max = 100 },
        },
        {
            key         = 'PLAY_SOUND',
            name        = 'play_sound_name',
            description = 'play_sound_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.PLAY_SOUND,
        },
        {
            key         = 'SHOW_MESSAGE',
            name        = 'show_message_name',
            description = 'show_message_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.SHOW_MESSAGE,
        },
        {
            key         = 'RETALIATION_ENABLED',
            name        = 'retaliation_enabled_name',
            description = 'retaliation_enabled_desc',
            renderer    = 'checkbox',
            default     = DEFAULTS.RETALIATION_ENABLED,
        },
        {
            key         = 'RETALIATION_WINDOW',
            name        = 'retaliation_window_name',
            description = 'retaliation_window_desc',
            renderer    = 'number',
            default     = DEFAULTS.RETALIATION_WINDOW,
            argument    = { integer = true, min = 2, max = 10 },
        },
        {
            key         = 'RETALIATION_RADIUS',
            name        = 'retaliation_radius_name',
            description = 'retaliation_radius_desc',
            renderer    = 'number',
            default     = DEFAULTS.RETALIATION_RADIUS,
            argument    = { integer = true, min = 50, max = 500 },
        },
        {
            key         = 'RETALIATION_STANDOFF',
            name        = 'retaliation_standoff_name',
            description = 'retaliation_standoff_desc',
            renderer    = 'number',
            default     = DEFAULTS.RETALIATION_STANDOFF,
            argument    = { integer = true, min = 1, max = 10 },
        },
        {
            key         = 'RETALIATION_LEVEL_DIFF',
            name        = 'retaliation_level_diff_name',
            description = 'retaliation_level_diff_desc',
            renderer    = 'number',
            default     = DEFAULTS.RETALIATION_LEVEL_DIFF,
            argument    = { integer = true, min = 1, max = 50 },
        },
    }
}