return {
	"_rv nordic iron boots",
	"_rv nordic iron gauntletl",
	"_rv nordic iron gauntletr",
	"_rv nordic iron greaves",
	"_rv nordic iron pauldronl",
	"_rv nordic iron pauldronr",
	"_rv_battlemage facemask",
	"_rv_chitin helm d",
	"_rv_chitin helm e",
	"_rv_chitin helm f",
	"_rv_dwemscr_boots",
	"_rv_dwemscr_cuirass",
	"_rv_dwemscr_gauntlet_left",
	"_rv_dwemscr_gauntlet_right",
	"_rv_dwemscr_greaves",
	"_rv_dwemscr_helmet",
	"_rv_dwemscr_pauldron_left",
	"_rv_dwemscr_pauldron_right",
	"_rv_imperial battle pauldron.l",
	"_rv_imperial battle pauldron.r",
	"_rv_imperial battlemage hood",
	"_rv_imperial dust helm",
	"_rv_imperial_templar_mask2",
	"_rv_ls_bm_boots",
	"_rv_ls_bm_bracer_l",
	"_rv_ls_bm_bracer_r",
	"_rv_ls_bm_chest",
	"_rv_ls_bm_greaves",
	"_rv_ls_bm_helmet",
	"_rv_ls_bm_pauldron_l",
	"_rv_ls_bm_pauldron_r",
	"_rv_netchimans cap",
	"_rv_sacred_necro_boots",
	"_rv_sacred_necro_bracer_l",
	"_rv_sacred_necro_bracer_r",
	"_rv_sacred_necro_cuirass",
	"_rv_sacred_necro_greaves",
	"_rv_sacred_necro_hood",
	"_rv_sacred_necro_pauld_l",
	"_rv_sacred_necro_pauld_r",
	"_rv_templarmage_boots",
	"_rv_templarmage_bracer_left",
	"_rv_templarmage_bracer_right",
	"_rv_templarmage_greaves",
	"_rv_templarmage_helm",
	"_rv_templarmage_pauldron_left",
	"_rv_templarmage_pauldron_right",
	"nordic_iron_cuirass",
	"nordic_iron_helm",
	"t_imp_studdedleather_boots_01",
	"t_imp_studdedleather_bracerl_01",
	"t_imp_studdedleather_bracerr_01",
	"t_imp_studdedleather_greaves_01",
	"t_imp_studdedleather_helm_01",
	"t_imp_studdedleather_pauldrl_01",
	"t_imp_studdedleather_pauldrr_01",
	"t_nor_iron_boots_01",
	"t_nor_iron_gauntletl_01",
	"t_nor_iron_gauntletr_01",
	"t_nor_iron_greaves_01",
	"t_nor_iron_pauldronl_01",
	"t_nor_iron_pauldronr_01",
}
