local stuff = {}


----Companion Classes--------------------------------------------------------------------------------------
stuff.classes = {
	[1] = "Acrobat",
	[2] = "Agent",
	[3] = "Archer",
	[4] = "Assassin",
	[5] = "Barbarian",
	[6] = "Bard",
	[7] = "Battlemage",
	[8] = "Crusader",
	[9] = "Healer",
	[10] = "Knight",
	[11] = "Mage",
	[12] = "Monk",
	[13] = "Nightblade",
	[14] = "Pilgrim",
	[15] = "Rogue",
	[16] = "Scout",
	[17] = "Sorcerer",
	[18] = "Spellsword",
	[19] = "Thief",
	[20] = "Warrior",
	[21] = "Witchhunter",
	[22] = "Alchemist",
	[23] = "Apothecary",
	[24] = "Buoyant Armiger",
	[25] = "Drillmaster",
	[26] = "Enchanter",
	[27] = "Enforcer",
	[28] = "Hunter",
	[29] = "Merchant",
	[30] = "Necromancer",
	[31] = "Priest",
	[32] = "Savant",
	[33] = "Sharpshooter",
	[34] = "Slave",
	[35] = "Smith",
	[36] = "Smuggler",
	[37] = "Warlock",
	[38] = "Witch"
}


----Capitalization/Offset-------------------------------------------------------------
stuff.capitalization = {
	[0] = "Strength",
	[1] = "Intelligence",
	[2] = "Willpower",
	[3] = "Agility",
	[4] = "Speed",
	[5] = "Endurance",
	[6] = "Personality",
	[7] = "Luck"
}

stuff.capitalization2 = {
	[0] = "Combat",
	[1] = "Magic",
	[2] = "Stealth"
}


----Creature Types-----------------------------------------------------------
stuff.typeTable = {
	[0] = "Normal",
	[1] = "Daedra",
	[2] = "Undead",
	[3] = "Humanoid",
	[4] = "Centurion",
	[5] = "Spriggan",
	[6] = "Goblin",
	[7] = "Domestic"
}


----Specialization Attributes----------------------------------------------
--Agility, Speed, Personality, Luck------------------------------------------
stuff.stealthTable = {
	[1] = 6,
	[2] = 7,
	[3] = 3,
	[4] = 4
}

--Intelligence, Willpower, Personality, Luck---------------------------------
stuff.magicTable = {
	[1] = 1,
	[2] = 2,
	[3] = 6,
	[4] = 7
}

--Strength, Endurence, Agility, Speed----------------------------------------
stuff.combatTable = {
	[1] = 0,
	[2] = 3,
	[3] = 4,
	[4] = 5
}


----Specialization Skills----------------------------------------------------
----Acrobatics, Light Armor, Marksman, Sneak, Hand to Hand, Short Blade, Mercantile, Speechcraft, Security
stuff.stealthSkillTable = {
	[1] = 20,
	[2] = 21,
	[3] = 23,
	[4] = 19,
	[5] = 26,
	[6] = 22,
	[7] = 24,
	[8] = 25,
	[9] = 18
}

----Unarmored, Illusion, Alchemy, Conjuration, Enchant, Alteration, Destruction, Mysticism, Restoration
stuff.magicSkillTable = {
	[1] = 17,
	[2] = 12,
	[3] = 16,
	[4] = 13,
	[5] = 9,
	[6] = 11,
	[7] = 10,
	[8] = 14,
	[9] = 15
}

----Heavy Armor, Medium Armor, Spear, Armorer, Axe, Blunt Weapon, Long Blade, Block, Athletics
stuff.combatSkillTable = {
	[1] = 3,
	[2] = 2,
	[3] = 7,
	[4] = 1,
	[5] = 6,
	[6] = 4,
	[7] = 5,
	[8] = 0,
	[9] = 8
}


----Spell Learning Tables----------------------------------------------------
----Restoration--------------------------------------------------------------
stuff.restorationTable1 = {
	[1] = "Balyna's Efficacious Balm",
	[2] = "Cure Poison",
	[3] = "Rest of St. Merris",
	[4] = "Turn of the Wheel",
	[5] = "Vitality"
}

stuff.restorationTable2 = {
	[1] = "Balyna's Efficacious Balm",
	[2] = "Cure Poison",
	[3] = "Rest of St. Merris",
	[4] = "Turn of the Wheel",
	[5] = "Vitality",
	[6] = "Blood Gift",
	[7] = "Strong Resist Magicka",
	[8] = "Restore Strength",
	[9] = "Restore Intelligence",
	[10] = "Restore Agility",
	[11] = "Stamina",
	[12] = "Hearth Heal",
	[13] = "Regenerate",
	[14] = "Troll Strength"
}

stuff.restorationTable3 = {
	[1] = "Balyna's Efficacious Balm",
	[2] = "Cure Poison",
	[3] = "Rest of St. Merris",
	[4] = "Turn of the Wheel",
	[5] = "Vitality",
	[6] = "Blood Gift",
	[7] = "Strong Resist Magicka",
	[8] = "Restore Strength",
	[9] = "Restore Intelligence",
	[10] = "Restore Agility",
	[11] = "Stamina",
	[12] = "Hearth Heal",
	[13] = "Regenerate",
	[14] = "Troll Strength",
	[15] = "Rapid Regenerate",
	[16] = "Restore Luck",
	[17] = "Great Resist Fire",
	[18] = "Great Resist Frost",
	[19] = "Great Resist Shock",
	[20] = "Nimbleness",
	[21] = "Orc's Strength",
	[22] = "Masterful Fluid Evasion"
}

stuff.restorationTable4 = {
	[1] = "Balyna's Efficacious Balm",
	[2] = "Cure Poison",
	[3] = "Rest of St. Merris",
	[4] = "Turn of the Wheel",
	[5] = "Vitality",
	[6] = "Blood Gift",
	[7] = "Strong Resist Magicka",
	[8] = "Restore Strength",
	[9] = "Restore Intelligence",
	[10] = "Restore Agility",
	[11] = "Stamina",
	[12] = "Hearth Heal",
	[13] = "Regenerate",
	[14] = "Troll Strength",
	[15] = "Rapid Regenerate",
	[16] = "Restore Luck",
	[17] = "Great Resist Fire",
	[18] = "Great Resist Frost",
	[19] = "Great Resist Shock",
	[20] = "Nimbleness",
	[21] = "Orc's Strength",
	[22] = "Masterful Fluid Evasion",
	[23] = "Masterful Denial",
	[24] = "Masterful Stolid Armor",
	[25] = "Masterful Red Wisdom",
	[26] = "Masterful Smiting",
	[27] = "Divine Aid",
	[28] = "Daedric Fatigue",
	[29] = "Daedric Health",
	[30] = "Flameguard",
	[31] = "Frostguard",
	[32] = "Shockguard",
	[33] = "Magickguard",
	[34] = "Poisonguard",
	[35] = "The Eight Wonders"
}

----Destruction-------------------------------------------------------------
stuff.destructionTable1 = {
	[1] = "Spirit Knife",
	[2] = "Hornhand",
	[3] = "Soulpinch",
	[4] = "Black Hand",
	[5] = "Stormhand",
	[6] = "Weapon Eater",
	[7] = "Clumsy Touch"
}

stuff.destructionTable2 = {
	[1] = "Spirit Knife",
	[2] = "Hornhand",
	[3] = "Soulpinch",
	[4] = "Black Hand",
	[5] = "Stormhand",
	[6] = "Weapon Eater",
	[7] = "Clumsy Touch",
	[8] = "Poisonbloom",
	[9] = "Cruel Firebloom",
	[10] = "Frostbite",
	[11] = "Spark",
	[12] = "Hex",
	[13] = "Stumble",
	[14] = "Daedric Bite",
	[15] = "Strength Leech",
	[16] = "Distraction",
	[17] = "Dire Weakness to Poison"
}

stuff.destructionTable3 = {
	[1] = "Spirit Knife",
	[2] = "Hornhand",
	[3] = "Soulpinch",
	[4] = "Black Hand",
	[5] = "Stormhand",
	[6] = "Weapon Eater",
	[7] = "Clumsy Touch",
	[8] = "Poisonbloom",
	[9] = "Cruel Firebloom",
	[10] = "Frostbite",
	[11] = "Spark",
	[12] = "Hex",
	[13] = "Stumble",
	[14] = "Daedric Bite",
	[15] = "Strength Leech",
	[16] = "Distraction",
	[17] = "Dire Weakness to Poison",
	[18] = "Dire Weakness to Fire",
	[19] = "Dire Weakness to Frost",
	[20] = "Dire Weakness to Shock",
	[21] = "Dire Weakness to Magicka",
	[22] = "Deadly Poison",
	[23] = "Distant Combustion",
	[24] = "Distant Cold",
	[25] = "Distant Electrocution",
	[26] = "Scourge Blade",
	[27] = "Fuddle",
}

stuff.destructionTable4 = {
	[1] = "Spirit Knife",
	[2] = "Hornhand",
	[3] = "Soulpinch",
	[4] = "Black Hand",
	[5] = "Stormhand",
	[6] = "Weapon Eater",
	[7] = "Clumsy Touch",
	[8] = "Poisonbloom",
	[9] = "Cruel Firebloom",
	[10] = "Frostbite",
	[11] = "Spark",
	[12] = "Hex",
	[13] = "Stumble",
	[14] = "Daedric Bite",
	[15] = "Strength Leech",
	[16] = "Distraction",
	[17] = "Dire Weakness to Poison",
	[18] = "Dire Weakness to Fire",
	[19] = "Dire Weakness to Frost",
	[20] = "Dire Weakness to Shock",
	[21] = "Dire Weakness to Magicka",
	[22] = "Deadly Poison",
	[23] = "Distant Combustion",
	[24] = "Distant Cold",
	[25] = "Distant Electrocution",
	[26] = "Scourge Blade",
	[27] = "Fuddle",
	[28] = "Woe",
	[29] = "Incineration",
	[30] = "Glacierize",
	[31] = "Potent Poison",
	[32] = "Vaporization",
	[33] = "Blood Curse: Fatigue",
	[34] = "Dark Ray",
	[35] = "Cosmic Wound"
}

----Alteration-------------------------------------------------------------
stuff.alterationTable1 = {
	[1] = "First Barrier",
	[2] = "Weary",
	[3] = "Fire Barrier",
	[4] = "Frost Shield",
	[5] = "Shock Barrier"
}

stuff.alterationTable2 = {
	[1] = "First Barrier",
	[2] = "Weary",
	[3] = "Fire Barrier",
	[4] = "Frost Shield",
	[5] = "Shock Barrier",
	[6] = "Second Barrier",
	[7] = "Cruel Weary",
	[8] = "Strong Feather",
	[9] = "Strong Fire Shield",
	[10] = "Strong Shock Shield",
	[11] = "Water Breathing",
	[12] = "Water Walking"
}

stuff.alterationTable3 = {
	[1] = "First Barrier",
	[2] = "Weary",
	[3] = "Fire Barrier",
	[4] = "Frost Shield",
	[5] = "Shock Barrier",
	[6] = "Second Barrier",
	[7] = "Cruel Weary",
	[8] = "Strong Feather",
	[9] = "Strong Fire Shield",
	[10] = "Strong Shock Shield",
	[11] = "Water Breathing",
	[12] = "Water Walking",
	[13] = "Dire Weary",
	[14] = "Third Barrier",
	[15] = "Fourth Barrier",
}

stuff.alterationTable4 = {
	[1] = "First Barrier",
	[2] = "Weary",
	[3] = "Fire Barrier",
	[4] = "Frost Shield",
	[5] = "Shock Barrier",
	[6] = "Second Barrier",
	[7] = "Cruel Weary",
	[8] = "Strong Feather",
	[9] = "Strong Fire Shield",
	[10] = "Strong Shock Shield",
	[11] = "Water Breathing",
	[12] = "Water Walking",
	[13] = "Dire Weary",
	[14] = "Third Barrier",
	[15] = "Fourth Barrier",
	[16] = "Fifth Barrier",
	[17] = "Sixth Barrier",
	[18] = "Elemental Circle",
	[19] = "Burning Aegis",
	[20] = "Frozen Aegis",
	[21] = "Galvanic Aegis"
}

----Conjuration-------------------------------------------------------------
stuff.conjurationTable1 = {
	[1] = "Bound Dagger",
	[2] = "Bound Gauntlets",
	[3] = "Bound Boots",
	[4] = "Summon Ancestral Ghost",
	[5] = "Saintly Touch",
	[6] = "Commanding Touch"
}

stuff.conjurationTable2 = {
	[1] = "Bound Dagger",
	[2] = "Bound Gauntlets",
	[3] = "Bound Boots",
	[4] = "Summon Ancestral Ghost",
	[5] = "Saintly Touch",
	[6] = "Commanding Touch",
	[7] = "Bound Helm",
	[8] = "Bound Cuirass",
	[9] = "Bound Mace",
	[10] = "Bound Longbow",
	[11] = "Summon Skeletal Minion",
	[12] = "Summon Least Bonewalker",
	[13] = "Summon Scamp",
	[14] = "Turn Undead",
}

stuff.conjurationTable3 = {
	[1] = "Bound Dagger",
	[2] = "Bound Gauntlets",
	[3] = "Bound Boots",
	[4] = "Summon Ancestral Ghost",
	[5] = "Saintly Touch",
	[6] = "Commanding Touch",
	[7] = "Bound Helm",
	[8] = "Bound Cuirass",
	[9] = "Bound Mace",
	[10] = "Bound Longbow",
	[11] = "Summon Skeletal Minion",
	[12] = "Summon Least Bonewalker",
	[13] = "Summon Scamp",
	[14] = "Turn Undead",
	[15] = "Bound Longsword",
	[16] = "Bound Battle-Axe",
	[17] = "Bound Spear",
	[18] = "Bound Shield",
	[19] = "Summon Bonelord",
	[20] = "Summon Flame Atronach",
	[21] = "Summon Frost Atronach",
	[22] = "Summon Clannfear",
	[23] = "Summon Greater Bonewalker",
	[24] = "Blessed Touch",
}

stuff.conjurationTable4 = {
	[1] = "Bound Dagger",
	[2] = "Bound Gauntlets",
	[3] = "Bound Boots",
	[4] = "Summon Ancestral Ghost",
	[5] = "Saintly Touch",
	[6] = "Commanding Touch",
	[7] = "Bound Helm",
	[8] = "Bound Cuirass",
	[9] = "Bound Mace",
	[10] = "Bound Longbow",
	[11] = "Summon Skeletal Minion",
	[12] = "Summon Least Bonewalker",
	[13] = "Summon Scamp",
	[14] = "Turn Undead",
	[15] = "Bound Longsword",
	[16] = "Bound Battle-Axe",
	[17] = "Bound Spear",
	[18] = "Bound Shield",
	[19] = "Summon Bonelord",
	[20] = "Summon Flame Atronach",
	[21] = "Summon Frost Atronach",
	[22] = "Summon Clanfear",
	[23] = "Summon Greater Bonewalker",
	[24] = "Blessed Touch",
	[25] = "Summon Hunger",
	[26] = "Summon Dremora",
	[27] = "Summon Daedroth",
	[28] = "Summon Storm Atronach",
	[29] = "Summon Winged Twilight",
	[30] = "Summon Golden Saint"
}

----Illusion-------------------------------------------------------------
stuff.illusionTable1 = {
	[1] = "Erelvam's Wild Sty",
	[2] = "Father's Hand",
	[3] = "Silence",
	[4] = "Wild Earwig",
	[5] = "Paralysis",
	[6] = "Calm Creature"
}

stuff.illusionTable2 = {
	[1] = "Erelvam's Wild Sty",
	[2] = "Father's Hand",
	[3] = "Silence",
	[4] = "Wild Earwig",
	[5] = "Paralysis",
	[6] = "Calm Creature",
	[7] = "Calm Humanoid",
	[8] = "Alad's Caliginy",
	[9] = "Light",
	[10] = "Shadow Weave",
	[11] = "Far Silence",
	[12] = "Dire Noise",
}

stuff.illusionTable3 = {
	[1] = "Erelvam's Wild Sty",
	[2] = "Father's Hand",
	[3] = "Silence",
	[4] = "Wild Earwig",
	[5] = "Paralysis",
	[6] = "Calm Creature",
	[7] = "Calm Humanoid",
	[8] = "Alad's Caliginy",
	[9] = "Light",
	[10] = "Shadow Weave",
	[11] = "Far Silence",
	[12] = "Dire Noise",
	[13] = "Medusa's Gaze",
	[14] = "Invisibility",
	[15] = "Shadowmask",
}

stuff.illusionTable4 = {
	[1] = "Erelvam's Wild Sty",
	[2] = "Father's Hand",
	[3] = "Silence",
	[4] = "Wild Earwig",
	[5] = "Paralysis",
	[6] = "Calm Creature",
	[7] = "Calm Humanoid",
	[8] = "Alad's Caliginy",
	[9] = "Light",
	[10] = "Shadow Weave",
	[11] = "Far Silence",
	[12] = "Dire Noise",
	[13] = "Medusa's Gaze",
	[14] = "Invisibility",
	[15] = "Shadowmask",
	[16] = "Baleful Glower",
	[17] = "Perfect Camouflage",
	[18] = "Misperception",
	[19] = "Enduring Noise"
}

----Mysticism-------------------------------------------------------------
stuff.mysticismTable1 = {
	[1] = "Righteousness",
	[2] = "Almalexia's Grace",
	[3] = "Sotha's Mirror",
	[4] = "Soul Trap",
	[5] = "Absorb Speed",
}

stuff.mysticismTable2 = {
	[1] = "Righteousness",
	[2] = "Almalexia's Grace",
	[3] = "Sotha's Mirror",
	[4] = "Soul Trap",
	[5] = "Absorb Speed",
	[6] = "Absorb Intelligence",
	[7] = "Absorb Luck",
	[8] = "Absorb Health",
	[9] = "Dispel",
	[10] = "Reflect",
	[11] = "Weak Spelldrinker",
}

stuff.mysticismTable3 = {
	[1] = "Righteousness",
	[2] = "Almalexia's Grace",
	[3] = "Sotha's Mirror",
	[4] = "Soul Trap",
	[5] = "Absorb Speed",
	[6] = "Absorb Intelligence",
	[7] = "Absorb Luck",
	[8] = "Absorb Health",
	[9] = "Dispel",
	[10] = "Reflect",
	[11] = "Weak Spelldrinker",
	[12] = "Absorb Agility",
	[13] = "Absorb Strength",
	[14] = "Absorb Willpower",
	[15] = "Energy Leech",
	[16] = "Shalidor's Mirror",
	[17] = "Strong Spelldrinker",
	[18] = "Profane Touch"
}

stuff.mysticismTable4 = {
	[1] = "Righteousness",
	[2] = "Almalexia's Grace",
	[3] = "Sotha's Mirror",
	[4] = "Soul Trap",
	[5] = "Absorb Speed",
	[6] = "Absorb Intelligence",
	[7] = "Absorb Luck",
	[8] = "Absorb Health",
	[9] = "Dispel",
	[10] = "Reflect",
	[11] = "Weak Spelldrinker",
	[12] = "Absorb Agility",
	[13] = "Absorb Strength",
	[14] = "Absorb Willpower",
	[15] = "Energy Leech",
	[16] = "Shalidor's Mirror",
	[17] = "Strong Spelldrinker",
	[18] = "Profane Touch",
	[19] = "Llivam's Reversal",
	[20] = "Tranasa's Spelltrap",
	[21] = "The Moth-Wing Mirror",
	[22] = "Astral Drain"
}


----Creature Spell Tables---------------------------------------------------------------------------------------
stuff.normalTable1 = {
	[1] = "Poisonous Touch",
	[2] = "Clench",
	[3] = "Stumble",
	[4] = "Hornhand",
	[5] = "Weapon Eater",
	[6] = "Armor Eater",
	[7] = "Clumsy Touch",
	[8] = "Crying Eye",
	[9] = "Demoralize Beast",
	[10] = "Nimbleness",
	[11] = "Quicksilver",
	[12] = "Troll's Blood",
	[13] = "Earwig",
	[14] = "Vigor",
	[15] = "Resist Common Disease"
}

stuff.normalTable2 = {
	[1] = "Poisonous Touch",
	[2] = "Clench",
	[3] = "Stumble",
	[4] = "Hornhand",
	[5] = "Heartbite",
	[6] = "Weapon Eater",
	[7] = "Armor Eater",
	[8] = "Strength Leech",
	[9] = "Clumsy Touch",
	[10] = "Deadly Poison",
	[11] = "Crying Eye",
	[12] = "Demoralize Beast",
	[13] = "Hide",
	[14] = "Paralysis",
	[15] = "Nimbleness",
	[16] = "Quicksilver",
	[17] = "Troll Strength",
	[18] = "Troll's Blood",
	[19] = "Shadow Weave",
	[20] = "Earwig",
	[21] = "Vigor",
	[22] = "Vitality",
	[23] = "Resist Common Disease",
	[24] = "Resist Poison",
	[25] = "Stamina"
}

stuff.daedraTable1 = {
	[1] = "Fire Shield",
	[2] = "Frost Shield",
	[3] = "Levitate",
	[4] = "Lightning Shield",
	[5] = "Second Barrier",
	[6] = "Summon Clanfear",
	[7] = "Summon Flame Atronach",
	[8] = "Summon Scamp",
	[9] = "Fuddle",
	[10] = "Hex",
	[11] = "Daedric Bite",
	[12] = "Clumsy Touch",
	[13] = "Torpor",
	[14] = "Drain Blood",
	[15] = "Scourge Blade",
	[16] = "Stormhand",
	[17] = "Fire Bite",
	[18] = "Energy Leech",
	[19] = "Absorb Health",
	[20] = "Soulpinch"
}

stuff.daedraTable2 = {
	[1] = "Fire Shield",
	[2] = "Frost Shield",
	[3] = "Levitate",
	[4] = "Lightning Shield",
	[5] = "Second Barrier",
	[6] = "Third Barrier",
	[7] = "Fourth Barrier",
	[8] = "Summon Clanfear",
	[9] = "Summon Daedroth",
	[10] = "Summon Dremora",
	[11] = "Summon Flame Atronach",
	[12] = "Summon Frost Atronach",
	[13] = "Summon Golden Saint",
	[14] = "Summon Hunger",
	[15] = "Summon Scamp",
	[16] = "Summon Storm Atronach",
	[17] = "Summon Winged Twilight",
	[18] = "Fuddle",
	[19] = "Hex",
	[20] = "Daedric Bite",
	[21] = "Clumsy Touch",
	[22] = "Torpor",
	[23] = "Drain Blood",
	[24] = "Scourge Blade",
	[25] = "Cruel Firebloom",
	[26] = "Distant Combustion",
	[27] = "Distant Cold",
	[28] = "Potent Poison",
	[29] = "Deadly Poison",
	[30] = "Stormhand",
	[31] = "Distant Electrocution",
	[32] = "Dire Weakness to Fire",
	[33] = "Dire Weakness to Magicka",
	[34] = "Fire Bite",
	[35] = "Invisibility",
	[36] = "Paralysis",
	[37] = "Absorb Intelligence",
	[38] = "Energy Leech",
	[39] = "Absorb Health",
	[40] = "Reflect",
	[41] = "Wild Spelldrinker",
	[42] = "Orc's Strength",
	[43] = "Daedric Fatigue",
	[44] = "Daedric Health",
	[45] = "Great Resist Fire",
	[46] = "Great Resist Frost",
	[47] = "Elemental Circle",
	[48] = "Strong Resist Shock",
	[49] = "Regenerate",
	[50] = "Soulpinch",
	[51] = "Dark Ray",
	[52] = "Cosmic Wound",
	[53] = "Burning Aegis",
	[54] = "Frozen Aegis",
	[55] = "Galvanic Aegis"
}

stuff.undeadTable1 = {
	[1] = "Burden of Sin",
	[2] = "Frost Shield",
	[3] = "First Barrier",
	[4] = "Summon Ancestral Ghost",
	[5] = "Summon Least Bonewalker",
	[6] = "Summon Skeletal Minion",
	[7] = "Hex",
	[8] = "Stumble",
	[9] = "Woe",
	[10] = "Black Hand",
	[11] = "Armor Eater",
	[12] = "Clumsy Touch",
	[13] = "Torpor",
	[14] = "Strength Leech",
	[15] = "Blood Despair",
	[16] = "Frostbite",
	[17] = "Poison",
	[18] = "Poisonous Touch",
	[19] = "Alad's Caliginy",
	[20] = "Dire Noise",
	[21] = "Absorb Luck",
	[22] = "Absorb Agility",
	[23] = "Energy Leech",
	[24] = "Absorb Health"
}

stuff.undeadTable2 = {
	[1] = "Burden of Sin",
	[2] = "Frost Shield",
	[3] = "First Barrier",
	[4] = "Summon Ancestral Ghost",
	[5] = "Summon Bonelord",
	[6] = "Summon Least Bonewalker",
	[7] = "Summon Greater Bonewalker",
	[8] = "Summon Skeletal Minion",
	[9] = "Hex",
	[10] = "Stumble",
	[11] = "Woe",
	[12] = "Fuddle",
	[13] = "Black Hand",
	[14] = "Armor Eater",
	[15] = "Clumsy Touch",
	[16] = "Torpor",
	[17] = "Strength Leech",
	[18] = "Blood Despair",
	[19] = "Drain Destruction",
	[20] = "Frostbite",
	[21] = "Poison",
	[22] = "Poisonous Touch",
	[23] = "Viperbolt",
	[24] = "Deadly Poison",
	[25] = "Dire Weakness to Frost",
	[26] = "Dire Weakness to Poison",
	[27] = "Alad's Caliginy",
	[28] = "Sanctuary",
	[29] = "Dire Noise",
	[30] = "Absorb Luck",
	[31] = "Absorb Agility",
	[32] = "Absorb Intelligence",
	[33] = "Absorb Strength",
	[34] = "Energy Leech",
	[35] = "Absorb Health",
	[36] = "Dispel",
	[37] = "Troll Strength",
	[38] = "Blood Gift",
	[39] = "Stamina",
	[40] = "Regenerate",
	[41] = "Rapid Regenerate",
	[42] = "Profane Touch",
	[43] = "Dread Parasite",
	[44] = "Astral Drain"
}

stuff.humanoidTable1 = {
	[1] = "Fuddle",
	[2] = "Hex",
	[3] = "Stumble",
	[4] = "Woe",
	[5] = "Hornhand",
	[6] = "Black Hand",
	[7] = "Soulpinch",
	[8] = "Armor Eater",
	[9] = "Weapon Eater",
	[10] = "Strength Leech",
	[11] = "Blood Despair",
	[12] = "Fireball",
	[13] = "Poisonbloom",
	[14] = "Stormhand",
	[15] = "Alad's Caliginy",
	[16] = "Light",
	[17] = "Shadow Weave",
	[18] = "Silence",
	[19] = "Dire Noise",
	[20] = "Absorb Intelligence",
	[21] = "Absorb Health",
	[22] = "Weak Spelldrinker",
	[23] = "Restore Luck",
	[24] = "Restore Strength",
	[25] = "Stamina",
	[26] = "Second Barrier",
	[27] = "Fire Shield"
}

stuff.humanoidTable2 = {
	[1] = "Fuddle",
	[2] = "Hex",
	[3] = "Stumble",
	[4] = "Woe",
	[5] = "Hornhand",
	[6] = "Black Hand",
	[7] = "Heartbite",
	[8] = "Soulpinch",
	[9] = "Armor Eater",
	[10] = "Weapon Eater",
	[11] = "Strength Leech",
	[12] = "Blood Despair",
	[13] = "Scourge Blade",
	[14] = "Fireball",
	[15] = "Cruel Firebloom",
	[16] = "Distant Combustion",
	[17] = "Poisonbloom",
	[18] = "Viperbolt",
	[19] = "Stormhand",
	[20] = "Lightning Bolt",
	[21] = "Dire Weakness to Fire",
	[22] = "Dire Weakness to Magicka",
	[23] = "Dire Weakness to Shock",
	[24] = "Alad's Caliginy",
	[25] = "Invisibility",
	[26] = "Light",
	[27] = "Paralysis",
	[28] = "Medusa's Gaze",
	[29] = "Shadow Weave",
	[30] = "Silence",
	[31] = "Dire Noise",
	[32] = "Absorb Intelligence",
	[33] = "Absorb Strength",
	[34] = "Crimson Despair",
	[35] = "Energy Leech",
	[36] = "Absorb Health",
	[37] = "Dispel",
	[38] = "Strong Reflect",
	[39] = "Weak Spelldrinker",
	[40] = "Strong Spelldrinker",
	[41] = "Iron Will",
	[42] = "Orc's Strength",
	[43] = "Blood Gift",
	[44] = "Great Resist Fire",
	[45] = "Flameguard",
	[46] = "Great Resist Magicka",
	[47] = "Magickguard",
	[48] = "Strong Resist Shock",
	[49] = "Restore Strength",
	[50] = "Restore Agility",
	[51] = "Stamina",
	[52] = "Troll's Blood",
	[53] = "Regenerate",
	[54] = "Rapid Regenerate",
	[55] = "Far Silence",
	[56] = "Second Barrier",
	[57] = "Third Barrier",
	[58] = "Fourth Barrier",
	[59] = "Fire Shield",
	[60] = "Lightning Shield",
	[61] = "Incineration",
	[62] = "Cosmic Wound",
	[63] = "Dark Ray",
	[64] = "Profane Touch",
	[65] = "Astral Drain",
	[66] = "Burning Aegis"
}

stuff.centurionTable = {
	[1] = "Shock Barrier",
	[2] = "Fire Bite",
	[3] = "Shock",
	[4] = "Spark",
	[5] = "Fireball",
	[6] = "Light",
	[7] = "Stormhand",
	[8] = "Static Charge"
}

stuff.sprigganTable1 = {
	[1] = "Frost Barrier",
	[2] = "First Barrier",
	[3] = "Water Breathing",
	[4] = "Water Walking",
	[5] = "BM_summonwolf",
	[6] = "Saintly Touch",
	[7] = "Hornhand",
	[8] = "Black Hand",
	[9] = "Armor Eater",
	[10] = "Weapon Eater",
	[11] = "Frostbite",
	[12] = "Poison",
	[13] = "Poisonous Touch",
	[14] = "Crying Eye",
	[15] = "Calm Creature",
	[16] = "Shadow Weave",
	[17] = "Paralysis",
	[18] = "Sanctuary",
	[19] = "Earwig",
	[20] = "Righteousness",
	[21] = "Cure Poison",
	[22] = "Turn of the Wheel",
	[23] = "Quicksilver",
	[24] = "Vigor",
	[25] = "Vitality",
	[26] = "Variable Resist Frost",
	[27] = "Variable Resist Poison",
	[28] = "Restore Luck",
	[29] = "Rest of St. Merris",
	[30] = "Mother's Kiss",
	[31] = "Troll's Blood",
	[32] = "Hearth Heal"
}

stuff.sprigganTable2 = {
	[1] = "Frost Barrier",
	[2] = "Frost Shield",
	[3] = "First Barrier",
	[4] = "Second Barrier",
	[5] = "Third Barrier",
	[6] = "Water Breathing",
	[7] = "Water Walking",
	[8] = "BM_summonwolf",
	[9] = "BM_summonbear",
	[10] = "bm_summonbonewolf",
	[11] = "Saintly Touch",
	[12] = "Hornhand",
	[13] = "Black Hand",
	[14] = "Armor Eater",
	[15] = "Weapon Eater",
	[16] = "Clumsy Touch",
	[17] = "Frostbite",
	[18] = "Poison",
	[19] = "Poisonous Touch",
	[20] = "Poisonbloom",
	[21] = "Deadly Poison",
	[22] = "Potent Poison",
	[23] = "Dire Weakness to Poison",
	[24] = "Crying Eye",
	[25] = "Alad's Caliginy",
	[26] = "Calm Creature",
	[27] = "Shadow Weave",
	[28] = "Hide",
	[29] = "Paralysis",
	[30] = "Medusa's Gaze",
	[31] = "Sanctuary",
	[32] = "Earwig",
	[33] = "Absorb Luck",
	[34] = "Righteousness",
	[35] = "Dispel",
	[36] = "Reflect",
	[37] = "Weak Spelldrinker",
	[38] = "Panacea",
	[39] = "Cure Poison",
	[40] = "Turn of the Wheel",
	[41] = "Iron Will",
	[42] = "Nimbleness",
	[43] = "Quicksilver",
	[44] = "Troll Strength",
	[45] = "Divine Aid",
	[46] = "Vigor",
	[47] = "Vitality",
	[48] = "Blood Gift",
	[49] = "Variable Resist Frost",
	[50] = "Great Resist Frost",
	[51] = "Frostguard",
	[52] = "Variable Resist Magicka",
	[53] = "Great Resist Magicka",
	[54] = "Magickguard",
	[55] = "Variable Resist Poison",
	[56] = "Greater Resist Poison",
	[57] = "Poisonguard",
	[58] = "Variable Resist Shock",
	[59] = "Shockguard",
	[60] = "Restore Agility",
	[61] = "Restore Intelligence",
	[62] = "Restore Luck",
	[63] = "Restore Strength",
	[64] = "Restore Willpower",
	[65] = "Rest of St. Merris",
	[66] = "Stamina",
	[67] = "Mother's Kiss",
	[68] = "Troll's Blood",
	[69] = "Hearth Heal",
	[70] = "Regenerate",
	[71] = "Rapid Regenerate",
	[72] = "Distant Cold",
	[73] = "Glacierize",
	[74] = "Frozen Aegis"
}

stuff.goblinTable = {
	[1] = "Crying Eye",
	[2] = "Alad's Caliginy",
	[3] = "Calm Creature",
	[4] = "Calm Humanoid",
	[5] = "Chameleon",
	[6] = "Shadow Weave",
	[7] = "Demoralize Beast",
	[8] = "Hide",
	[9] = "Light",
	[10] = "Paralysis",
	[11] = "Medusa's Gaze",
	[12] = "Father's Hand",
	[13] = "Sanctuary",
	[14] = "Silence",
	[15] = "Far Silence",
	[16] = "Dire Earwig",
	[17] = "Dire Noise",
	[18] = "Perfect Camouflage",
	[19] = "Misperception",
	[20] = "Enduring Noise"
}

stuff.abList = {
	[1] = "kl_ab_norm_01",
	[2] = "kl_ab_norm_02",
	[3] = "kl_ab_norm_03",
	[4] = "kl_ab_norm_04",
	[5] = "kl_ab_dae_01",
	[6] = "kl_ab_dae_02",
	[7] = "kl_ab_dae_03",
	[8] = "kl_ab_dae_04",
	[9] = "kl_ab_und_01",
	[10] = "kl_ab_und_02",
	[11] = "kl_ab_und_03",
	[12] = "kl_ab_und_04",
	[13] = "kl_ab_hum_01",
	[14] = "kl_ab_hum_02",
	[15] = "kl_ab_hum_03",
	[16] = "kl_ab_hum_04",
	[17] = "kl_ab_cen_01",
	[18] = "kl_ab_cen_02",
	[19] = "kl_ab_cen_03",
	[20] = "kl_ab_cen_04",
	[21] = "kl_ab_spr_01",
	[22] = "kl_ab_spr_02",
	[23] = "kl_ab_spr_03",
	[24] = "kl_ab_spr_04",
	[25] = "kl_ab_gob_01",
	[26] = "kl_ab_gob_02",
	[27] = "kl_ab_gob_03",
	[28] = "kl_ab_gob_04",
	[29] = "kl_ab_gob_05",
	[30] = "kl_ab_gob_06",
	[31] = "kl_ab_gob_07",
	[32] = "kl_ab_gob_08"
}

----NPC Level Up Messages---------------------------------------------------------------
stuff.npcMessage = {
	[1] = "You'll have to get along from now on.",
	[2] = "The first step of a new journey can sometimes be the heaviest.",
	[3] = "Slow going. But none of you can afford to be careless.",
	[4] = "Thankfully, life on the road doesn't have to be a lonely one.",
	[5] = "You shake yourself from your reverie in time to catch your companion lost in their own.",
	[6] = "It seems to be getting easier, thanks to some help.",
	[7] = "You've realized over time that you have your own ways of doing things.",
	[8] = "How long can we keep this up?",
	[9] = "They let you take the lead, but not for lack of skill.",
	[10] = "Sometimes it's enough just to have someone else carry the firewood for a change.",
	[11] = "You thought they were gone for a moment. But then there they were.",
	[12] = "Your actions are becoming more synchronized, better coordinated. But it still isn't easy.",
	[13] = "Are they pushing themselves at their limit now, or does it come as naturally to them as it does to you?",
	[14] = "What is it that drives them?",
	[15] = "They just realized something.",
	[16] = "You've gained an understanding of each other's skills.",
	[17] = "How long do they plan on aiding you?",
	[18] = "There they go again. On to the next trial.",
	[19] = "Nothing need be said. You understand.",
	[20] = "How will they handle this next endeavor?",
	[21] = "You're beginning to think on how you might miss them if they were gone.",
	[22] = "So many stories exchanged over the campfire, stories you may one day forget.",
	[23] = "Their single-minded determination only serves to temper your own resolve.",
	[24] = "All your thoughts lately are related to the party's progress.",
	[25] = "You have cultivated great power within yourselves.",
	[26] = "This is what prowess feels like. You know it. They know it. But so too do your enemies.",
	[27] = "Just when you feel you're starting to slip, you remember someone else's life is on the line.",
	[28] = "It seems they no longer think. They just do.",
	[29] = "It's astonishing, thinking back on how they looked then compared to how they look now.",
	[30] = "Can perfection be achieved before death?",
	[31] = "They could have left so long ago. But they haven't.",
	[32] = "Always being hurried along. Now you see why.",
	[33] = "Thoughts of luxury are quickly dispersed.",
	[34] = "Couldn't be at the bottom forever.",
	[35] = "A moment of respite much deserved for everyone.",
	[36] = "The road twists and turns yet the fellowship holds true.",
	[37] = "Which of you has achieved more than the other? Does it even matter at this point?",
	[38] = "Excellence did not come easy for you and yours, but the struggle made the outcome all the sweeter.",
	[39] = "Others have heard of your party's exploits. You experienced them.",
	[40] = "By now, your group has made a lot of enemies. Time to make more.",
	[41] = "What joy is there in building an empire alone?",
	[42] = "Your struggles are their struggles now.",
	[43] = "They continue to surprise you every time.",
	[44] = "Together your party will achieve mastery.",
	[45] = "You can't seem to remember the last time you felt alone.",
	[46] = "What more could there be to learn? You are sure they will find out.",
	[47] = "You've decided it was all worth it. Every moment spent together.",
	[48] = "If the time comes that you go your separate ways, you know they will not want for protection.",
	[49] = "Perhaps a moment of thought is overdue. You've been so busy.",
	[50] = "The mystery of success is seemingly unraveled with help from your faithful companions.",
	[51] = "There is always yet more to learn.",
	[52] = "An effortless victory one moment, an insurmountable ordeal the next.",
	[53] = "All adventurers require rest, no matter their renown.",
	[54] = "Perhaps one day the fighting will simply stop.",
	[55] = "Where would you be now if you hadn't met each other then?",
	[56] = "It is repetition at this point. The journey to greater heights.",
	[57] = "Rest. They need it, and so do you.",
	[58] = "Much time has passed since you've last experienced failure.",
	[59] = "You've shared much with each other. What more is there to say?",
	[60] = "This could easily be the pinnacle of your abilities. Somehow you know it isn't.",
	[61] = "Past challenges are now a simple matter. Best keep it that way.",
	[62] = "So many choices left to make, you wonder if you'll ever get to it all.",
	[63] = "Soon the only road left untravelled will lead to retirement or death.",
	[64] = "Capable as they are, you still are wont to keep an eye on them just in case.",
	[65] = "Another day. How many has it been?",
	[66] = "Nirn holds many secrets too numerous to count. But you still try.",
	[67] = "A party of your caliber scares off all but the most desparate or daring.",
	[68] = "You never could have guesed you would have made it this far.",
	[69] = "Despite it all, you still have allies at your side.",
	[70] = "It all makes sense. Eyes unclouded, you realize there will always be more to see.",
	[71] = "When will you stop? Will you be forced to, or will it be of your own accord?",
	[72] = "For a short moment, you considered not getting up at all.",
	[73] = "They fought this entire time at your behest. Do they ever tire?",
	[74] = "Are the days getting shorter now or is this how it has always been?",
	[75] = "Sometimes you feel you've forgotten more about hardship than you care to remember.",
	[76] = "There is still time. There was never any need to worry.",
	[77] = "You've taught them as much as they've taught you, you hope.",
	[78] = "How many times have you awoke to them waiting on you?",
	[79] = "No obstacle can stand before you or your allies.",
	[80] = "Progress toward perfection remains unimpeded.",
	[81] = "The lack of certainty you once had...how could you have been so foolish?",
	[82] = "It is easy. So much can be done on but a whim.",
	[83] = "Each moment of peace becomes more precious than the last.",
	[84] = "The reputation of your party reaches further and further for each step taken.",
	[85] = "It's nice to finally sit down and simply...be.",
	[86] = "Is it possible to tire of discovery? You've done enough...but you're still not finished.",
	[87] = "Matters of great import are but distractions to them now.",
	[88] = "Survival is a daily ordeal. An ordeal that your group has long mastered.",
	[89] = "Spoils of adventure no longer entice them, only the thrill of the journey.",
	[90] = "The only way to go is forward.",
	[91] = "If the end is inevitable, why spend the time left to you in despair?",
	[92] = "There is no such thing as forever, and that's okay.",
	[93] = "Each and every time you look to them, they never disappoint.",
	[94] = "This may have been your story, but they've been with you through each chapter.",
	[95] = "With each action they alter the course of history.",
	[96] = "Will the scribes write of them as well? Or will they be forgotten?",
	[97] = "For every scar, a story. For every failure, a lesson.",
	[98] = "Even masters have to train to retain the title.",
	[99] = "You can feel it now. They are soon to be at the apex. The summit.",
	[100] = "Having left your mark on the world, you journey on with them at your side..."

}


return stuff