return mwse.loadConfig("stealth", {
	modEnabled = true,
	sneakAttack = true,
	adjustSneakIcon = true,
	invisFix = true,
	lightStealthEnabled = true,
	showLightBar = true,
	sneakDifficulty = 50,
	bootMultiplier = 10,
	invisibilityBonus = 30,
	chameleonMultiplier = 50,
	npcSneakBonus = 20,
	viewMultiplier = 3,
	noViewMultiplier = 50,
	sneakSkillMult = 100,
	sneakDistanceMultiplier = 500,
	sneakDistanceBase = 60,
	viewAngle = 110
})