return mwse.loadConfig("poisonCrafting", {
    version = 2.1,
    useBaseStats = true,
    useBonusProgress = true,
    useApplyMessage = true,
    useEffectIcons = true,
    skipApparatusEvents = false,
    ignore = {},
    classPoisonChance = {
        ["alchemist"]          = 30,
        ["alchemist service"]  = 30,
        ["apothecary"]         = 30,
        ["apothecary service"] = 30,
        ["assassin"]           = 20,
        ["assassin service"]   = 20,
        ["bard"]               = 20,
        ["scout"]              = 20,
        ["nightblade"]         = 10,
        ["nightblade service"] = 10,
        ["rogue"]              = 10,
        ["witch"]              = 10,
    },
    debugMode = false,
})
