--- A cell of the game world.
--- @class core.Cell
--- @field name string Name of the cell (can be an empty string).
--- @field id string Unique record ID of the cell, based on cell name for interiors and the worldspace for exteriors, or the formID of the cell for ESM4 cells.
--- @field region string Region of the cell.
--- @field isExterior boolean Whether the cell is an exterior cell. "Exterior" means a grid of cells where the player can seamlessly walk from one cell to another without teleports. QuasiExterior (interior with sky) is not an exterior.
--- @field isQuasiExterior boolean (DEPRECATED, use `hasTag("QuasiExterior")`) Whether the cell is a quasi exterior (like interior but with the sky and the weather).
--- @field gridX number Index of the cell by X (only for exteriors).
--- @field gridY number Index of the cell by Y (only for exteriors).
--- @field worldSpaceId string Id of the world space.
--- @field hasWater boolean True if the cell contains water.
--- @field waterLevel number|nil The water level of the cell. (nil if the cell has no water).
--- @field hasSky boolean True if in this cell sky should be rendered.
--- @field hasTag fun (self, tag: string): boolean Returns true if the cell has the given tag.
--- @field isInSameSpace fun (self, object: GameObject): boolean Returns true either if the cell contains the object or if the cell is an exterior and the object is also in an exterior.
--- @field getAll fun (self, type: any): ObjectList Get all objects of a given type from the cell; Only available from global scripts.
