return {
	"6th bell hammer",
	"aa_bonemold_boots_bad",
	"aa_bonemold_bracer_left_old",
	"aa_bonemold_bracer_right_old",
	"aa_bonemold_greaves_bad",
	"aa_bonemold_pauldron_l_old",
	"aa_bonemold_pauldron_r_old",
	"aa_bonemold_shield_old",
	"aa_steel_crossbow_old",
	"adamantium boots",
	"adamantium_axe",
	"adamantium_bracer_left",
	"adamantium_bracer_right",
	"adamantium_claymore",
	"adamantium_cuirass",
	"adamantium_greaves",
	"adamantium_mace",
	"adamantium_pauldron_left",
	"adamantium_pauldron_right",
	"adamantium_shortsword",
	"adamantium_spear",
	"addamantium_helm",
	"bm bear boots",
	"bm bear cuirass",
	"bm bear greaves",
	"bm bear helmet",
	"bm bear left gauntlet",
	"bm bear left pauldron",
	"bm bear right gauntlet",
	"bm bear right pauldron",
	"bm bear shield",
	"bm huntsman axe",
	"bm huntsman crossbow",
	"bm huntsman longsword",
	"bm huntsman spear",
	"bm huntsman war axe",
	"bm huntsmanbolt",
	"bm ice dagger",
	"bm ice longsword",
	"bm ice mace",
	"bm ice war axe",
	"bm nordic silver axe",
	"bm nordic silver battleaxe",
	"bm nordic silver claymore",
	"bm nordic silver dagger",
	"bm nordic silver longsword",
	"bm nordic silver mace",
	"bm nordic silver shortsword",
	"bm nordic silver spear",
	"bm riekling lance",
	"bm riekling sword",
	"bm wolf boots",
	"bm wolf cuirass",
	"bm wolf greaves",
	"bm wolf helmet",
	"bm wolf left gauntlet",
	"bm wolf left pauldron",
	"bm wolf right gauntlet",
	"bm wolf right pauldron",
	"bm wolf shield",
	"bm_ice minion_shield1",
	"bm_ice_boots",
	"bm_ice_cuirass",
	"bm_ice_gauntletl",
	"bm_ice_gauntletr",
	"bm_ice_greaves",
	"bm_ice_helmet",
	"bm_ice_pauldronl",
	"bm_ice_pauldronr",
	"bm_ice_shield",
	"bm_nordic01_glovel",
	"bm_nordic01_glover",
	"bm_nordic01_pants",
	"bm_nordic01_robe",
	"bm_nordic01_shirt",
	"bm_nordic01_shoes",
	"bm_nordic02_glovel",
	"bm_nordic02_glover",
	"bm_nordic02_pants",
	"bm_nordic02_shirt",
	"bm_nordic02_shoes",
	"bm_nordicmail_boots",
	"bm_nordicmail_cuirass",
	"bm_nordicmail_gauntletl",
	"bm_nordicmail_gauntletr",
	"bm_nordicmail_greaves",
	"bm_nordicmail_helmet",
	"bm_nordicmail_pauldronl",
	"bm_nordicmail_pauldronr",
	"bm_nordicmail_shield",
	"bm_wool01_glovel",
	"bm_wool01_glover",
	"bm_wool01_pants",
	"bm_wool01_robe",
	"bm_wool01_shirt",
	"bm_wool01_shoes",
	"bm_wool02_glovel",
	"bm_wool02_glover",
	"bm_wool02_pants",
	"bm_wool02_shirt",
	"bm_wool02_shoes",
	"bonemold arrow",
	"bonemold bolt",
	"bonemold long bow",
	"bonemold_armun-an_cuirass",
	"bonemold_armun-an_helm",
	"bonemold_armun-an_pauldron_l",
	"bonemold_armun-an_pauldron_r",
	"bonemold_boots",
	"bonemold_bracer_left",
	"bonemold_bracer_right",
	"bonemold_chuzei_helm",
	"bonemold_cuirass",
	"bonemold_founders_helm",
	"bonemold_gah-julan_cuirass",
	"bonemold_gah-julan_helm",
	"bonemold_gah-julan_pauldron_l",
	"bonemold_gah-julan_pauldron_r",
	"bonemold_greaves",
	"bonemold_helm",
	"bonemold_pauldron_l",
	"bonemold_pauldron_r",
	"bonemold_shield",
	"bonemold_towershield",
	"bonemold_tshield_hlaaluguard",
	"bonemold_tshield_hrlb",
	"bonemold_tshield_redoranguard",
	"bonemold_tshield_telvanniguard",
	"centurion_projectile_dart",
	"cephalopod_helm",
	"chitin arrow",
	"chitin boots",
	"chitin club",
	"chitin cuirass",
	"chitin dagger",
	"chitin greaves",
	"chitin guantlet - left",
	"chitin guantlet - right",
	"chitin helm",
	"chitin pauldron - left",
	"chitin pauldron - right",
	"chitin short bow",
	"chitin shortsword",
	"chitin spear",
	"chitin throwing star",
	"chitin war axe",
	"chitin_mask_helm",
	"chitin_shield",
	"chitin_towershield",
	"chitin_watchman_helm",
	"cloth bracer left",
	"cloth bracer right",
	"common_amulet_01",
	"common_amulet_02",
	"common_amulet_03",
	"common_amulet_04",
	"common_amulet_05",
	"common_belt_01",
	"common_belt_02",
	"common_belt_03",
	"common_belt_04",
	"common_belt_05",
	"common_glove_left_01",
	"common_glove_right_01",
	"common_pants_01",
	"common_pants_01_a",
	"common_pants_01_e",
	"common_pants_01_u",
	"common_pants_01_z",
	"common_pants_02",
	"common_pants_03",
	"common_pants_03_b",
	"common_pants_03_c",
	"common_pants_04",
	"common_pants_04_b",
	"common_pants_05",
	"common_pants_06",
	"common_pants_07",
	"common_ring_01",
	"common_ring_02",
	"common_ring_03",
	"common_ring_04",
	"common_ring_05",
	"common_robe_01",
	"common_robe_02",
	"common_robe_02_h",
	"common_robe_02_hh",
	"common_robe_02_r",
	"common_robe_02_rr",
	"common_robe_02_t",
	"common_robe_02_tt",
	"common_robe_03",
	"common_robe_03_a",
	"common_robe_04",
	"common_robe_05",
	"common_robe_05_a",
	"common_robe_05_b",
	"common_robe_05_c",
	"common_shirt_01",
	"common_shirt_01_a",
	"common_shirt_01_e",
	"common_shirt_01_u",
	"common_shirt_01_z",
	"common_shirt_02",
	"common_shirt_02_h",
	"common_shirt_02_hh",
	"common_shirt_02_r",
	"common_shirt_02_rr",
	"common_shirt_02_t",
	"common_shirt_02_tt",
	"common_shirt_03",
	"common_shirt_03_b",
	"common_shirt_03_c",
	"common_shirt_04",
	"common_shirt_04_a",
	"common_shirt_04_b",
	"common_shirt_04_c",
	"common_shirt_05",
	"common_shirt_06",
	"common_shirt_07",
	"common_shoes_01",
	"common_shoes_02",
	"common_shoes_03",
	"common_shoes_04",
	"common_shoes_05",
	"common_shoes_06",
	"common_shoes_07",
	"common_skirt_01",
	"common_skirt_02",
	"common_skirt_03",
	"common_skirt_04",
	"common_skirt_05",
	"common_skirt_06",
	"common_skirt_07",
	"corkbulb arrow",
	"corkbulb bolt",
	"daedric battle axe",
	"daedric claymore",
	"daedric club",
	"daedric dagger",
	"daedric dai-katana",
	"daedric dart",
	"daedric katana",
	"daedric long bow",
	"daedric longspear",
	"daedric longsword",
	"daedric mace",
	"daedric shortsword",
	"daedric spear",
	"daedric staff",
	"daedric tanto",
	"daedric wakizashi",
	"daedric war axe",
	"daedric warhammer",
	"daedric_boots",
	"daedric_cuirass",
	"daedric_fountain_helm",
	"daedric_gauntlet_left",
	"daedric_gauntlet_right",
	"daedric_god_helm",
	"daedric_greaves",
	"daedric_pauldron_left",
	"daedric_pauldron_right",
	"daedric_shield",
	"daedric_terrifying_helm",
	"daedric_towershield",
	"darkbrotherhood boots",
	"darkbrotherhood cuirass",
	"darkbrotherhood gauntlet_l",
	"darkbrotherhood gauntlet_r",
	"darkbrotherhood greaves",
	"darkbrotherhood helm",
	"darkbrotherhood pauldron_l",
	"darkbrotherhood pauldron_r",
	"dragonscale_cuirass",
	"dragonscale_helm",
	"dragonscale_towershield",
	"dreugh club",
	"dreugh staff",
	"dreugh_cuirass",
	"dreugh_helm",
	"dreugh_shield",
	"dust_adept_helm",
	"dwarven battle axe",
	"dwarven claymore",
	"dwarven crossbow",
	"dwarven halberd",
	"dwarven longspear",
	"dwarven mace",
	"dwarven shortsword",
	"dwarven spear",
	"dwarven war axe",
	"dwarven warhammer",
	"dwemer_boots",
	"dwemer_bracer_left",
	"dwemer_bracer_right",
	"dwemer_cuirass",
	"dwemer_greaves",
	"dwemer_helm",
	"dwemer_pauldron_left",
	"dwemer_pauldron_right",
	"dwemer_shield",
	"ebony broadsword",
	"ebony dart",
	"ebony longsword",
	"ebony mace",
	"ebony scimitar",
	"ebony shortsword",
	"ebony spear",
	"ebony staff",
	"ebony throwing star",
	"ebony war axe",
	"ebony_boots",
	"ebony_bracer_left",
	"ebony_bracer_right",
	"ebony_closed_helm",
	"ebony_cuirass",
	"ebony_greaves",
	"ebony_pauldron_left",
	"ebony_pauldron_right",
	"ebony_shield",
	"ebony_towershield",
	"expensive_amulet_01",
	"expensive_amulet_02",
	"expensive_amulet_03",
	"expensive_belt_01",
	"expensive_belt_02",
	"expensive_belt_03",
	"expensive_glove_left_01",
	"expensive_glove_right_01",
	"expensive_pants_01",
	"expensive_pants_01_a",
	"expensive_pants_01_e",
	"expensive_pants_01_u",
	"expensive_pants_01_z",
	"expensive_pants_02",
	"expensive_pants_03",
	"expensive_pants_mournhold",
	"expensive_ring_01",
	"expensive_ring_02",
	"expensive_ring_03",
	"expensive_robe_01",
	"expensive_robe_02",
	"expensive_robe_02_a",
	"expensive_robe_03",
	"expensive_shirt_01_a",
	"expensive_shirt_01_e",
	"expensive_shirt_01_u",
	"expensive_shirt_01_z",
	"expensive_shirt_02",
	"expensive_shirt_03",
	"expensive_shirt_mournhold",
	"expensive_shoes_02",
	"expensive_shoes_03",
	"expensive_shoes_mournhold",
	"expensive_skirt_01",
	"expensive_skirt_02",
	"expensive_skirt_03",
	"expensive_skirt_mournhold",
	"exquisite_amulet_01",
	"exquisite_belt_01",
	"exquisite_pants_01",
	"exquisite_ring_01",
	"exquisite_ring_02",
	"exquisite_robe_01",
	"exquisite_shirt_01",
	"exquisite_shoes_01",
	"exquisite_skirt_01",
	"extravagant_amulet_01",
	"extravagant_amulet_02",
	"extravagant_belt_01",
	"extravagant_belt_02",
	"extravagant_glove_left_01",
	"extravagant_glove_right_01",
	"extravagant_pants_01",
	"extravagant_pants_02",
	"extravagant_ring_01",
	"extravagant_ring_02",
	"extravagant_robe_01",
	"extravagant_robe_01_a",
	"extravagant_robe_01_b",
	"extravagant_robe_01_c",
	"extravagant_robe_01_h",
	"extravagant_robe_01_r",
	"extravagant_robe_01_t",
	"extravagant_robe_02",
	"extravagant_shirt_01",
	"extravagant_shirt_01_h",
	"extravagant_shirt_01_r",
	"extravagant_shirt_01_t",
	"extravagant_shirt_02",
	"extravagant_shoes_01",
	"extravagant_shoes_02",
	"extravagant_skirt_01",
	"extravagant_skirt_02",
	"fine spring dart",
	"fur_bearskin_cuirass",
	"fur_boots",
	"fur_bracer_left",
	"fur_bracer_right",
	"fur_colovian_helm",
	"fur_colovian_helm_red",
	"fur_colovian_helm_white",
	"fur_cuirass",
	"fur_gauntlet_left",
	"fur_gauntlet_right",
	"fur_greaves",
	"fur_helm",
	"fur_pauldron_left",
	"fur_pauldron_right",
	"glass claymore",
	"glass dagger",
	"glass halberd",
	"glass longsword",
	"glass staff",
	"glass throwing knife",
	"glass throwing star",
	"glass war axe",
	"glass_boots",
	"glass_bracer_left",
	"glass_bracer_right",
	"glass_cuirass",
	"glass_greaves",
	"glass_helm",
	"glass_pauldron_left",
	"glass_pauldron_right",
	"glass_shield",
	"glass_towershield",
	"goblin_club",
	"goblin_shield",
	"goblin_sword",
	"gondolier_helm",
	"heavy_leather_boots",
	"helsethguard_boots",
	"helsethguard_cuirass",
	"helsethguard_gauntlet_left",
	"helsethguard_gauntlet_right",
	"helsethguard_greaves",
	"helsethguard_helmet",
	"helsethguard_pauldron_left",
	"helsethguard_pauldron_right",
	"imperial belt",
	"imperial boots",
	"imperial broadsword",
	"imperial helmet armor",
	"imperial left gauntlet",
	"imperial left pauldron",
	"imperial right gauntlet",
	"imperial right pauldron",
	"imperial shield",
	"imperial shortsword",
	"imperial skirt_clothing",
	"imperial_chain_coif_helm",
	"imperial_chain_greaves",
	"imperial_chain_pauldron_left",
	"imperial_chain_pauldron_right",
	"imperial_greaves",
	"imperial_studded_cuirass",
	"indoril boots",
	"indoril left gauntlet",
	"indoril pauldron left",
	"indoril pauldron right",
	"indoril right gauntlet",
	"indoril shield",
	"indoril_belt",
	"indoril_mh_guard_boots",
	"indoril_mh_guard_gauntlet_l",
	"indoril_mh_guard_gauntlet_r",
	"indoril_mh_guard_greaves",
	"indoril_mh_guard_pauldron_l",
	"indoril_mh_guard_pauldron_r",
	"indoril_mh_guard_shield",
	"iron arrow",
	"iron battle axe",
	"iron bolt",
	"iron boots",
	"iron broadsword",
	"iron claymore",
	"iron club",
	"iron dagger",
	"iron fork",
	"iron halberd",
	"iron long spear",
	"iron longsword",
	"iron mace",
	"iron saber",
	"iron shortsword",
	"iron spear",
	"iron tanto",
	"iron throwing knife",
	"iron wakizashi",
	"iron war axe",
	"iron warhammer",
	"iron_bracer_left",
	"iron_bracer_right",
	"iron_cuirass",
	"iron_gauntlet_left",
	"iron_gauntlet_right",
	"iron_greaves",
	"iron_helmet",
	"iron_pauldron_left",
	"iron_pauldron_right",
	"iron_shield",
	"iron_towershield",
	"left leather bracer",
	"long bow",
	"mole_crab_helm",
	"morag_tong_helm",
	"netch_leather_boiled_cuirass",
	"netch_leather_boiled_helm",
	"netch_leather_boots",
	"netch_leather_cuirass",
	"netch_leather_gauntlet_left",
	"netch_leather_gauntlet_right",
	"netch_leather_greaves",
	"netch_leather_helm",
	"netch_leather_pauldron_left",
	"netch_leather_pauldron_right",
	"netch_leather_shield",
	"netch_leather_towershield",
	"newtscale_cuirass",
	"nordic battle axe",
	"nordic broadsword",
	"nordic claymore",
	"nordic_iron_cuirass",
	"nordic_iron_helm",
	"nordic_leather_shield",
	"nordic_ringmail_cuirass",
	"orcish battle axe",
	"orcish bolt",
	"orcish warhammer",
	"orcish_boots",
	"orcish_bracer_left",
	"orcish_bracer_right",
	"orcish_cuirass",
	"orcish_greaves",
	"orcish_helm",
	"orcish_pauldron_left",
	"orcish_pauldron_right",
	"orcish_towershield",
	"redoran_master_helm",
	"right leather bracer",
	"short bow",
	"silver arrow",
	"silver bolt",
	"silver claymore",
	"silver dagger",
	"silver dart",
	"silver longsword",
	"silver shortsword",
	"silver spear",
	"silver staff",
	"silver throwing star",
	"silver war axe",
	"silver_cuirass",
	"silver_helm",
	"spiked club",
	"spring dart",
	"steel arrow",
	"steel axe",
	"steel battle axe",
	"steel bolt",
	"steel broadsword",
	"steel claymore",
	"steel club",
	"steel crossbow",
	"steel dagger",
	"steel dai-katana",
	"steel dart",
	"steel halberd",
	"steel katana",
	"steel longbow",
	"steel longsword",
	"steel mace",
	"steel saber",
	"steel shortsword",
	"steel spear",
	"steel staff",
	"steel tanto",
	"steel throwing knife",
	"steel throwing star",
	"steel wakizashi",
	"steel war axe",
	"steel warhammer",
	"steel_boots",
	"steel_cuirass",
	"steel_gauntlet_left",
	"steel_gauntlet_right",
	"steel_greaves",
	"steel_helm",
	"steel_pauldron_left",
	"steel_pauldron_right",
	"steel_shield",
	"steel_towershield",
	"templar belt",
	"templar boots",
	"templar bracer left",
	"templar bracer right",
	"templar skirt obj",
	"templar_greaves",
	"templar_helmet_armor",
	"templar_pauldron_left",
	"templar_pauldron_right",
	"trollbone_cuirass",
	"trollbone_helm",
	"trollbone_shield",
	"wooden arrow",
	"wooden bolt",
	"wooden crossbow",
	"wooden staff",
}
