local this = {}

this.talkativeness = {
    ["Agent"] = 2,
    ["Bard"] = 2,
    ["Healer"] = 2,
    ["Knight"] = 2,
    ["Pilgrim"] = 2,
    ["Rogue"] = 2,
    ["Alchemist"] = 2,
    ["Apothecary"] = 2,
    ["Bookseller"] = 2,
    ["Buoyant Armiger"] = 2,
    ["Caravaner"] = 2,
    ["Clothier"] = 2,
    ["Drillmaster"] = 2,
    ["Enchanter"] = 2,
    ["Gondolier"] = 2,
    ["Guard"] = 2,
    ["Merchant"] = 2,
    ["Noble"] = 2,
    ["Pauper"] = 2,
    ["Pawnbroker"] = 2,
    ["Priest"] = 2,
    ["Publican"] = 2,
    ["Savant"] = 2,
    ["Shipmaster"] = 2,
    ["Trader"] = 2,
    ["Wise Woman"] = 2,
    ["Acrobat"] = 1,
    ["Archer"] = 1,
    ["Battlemage"] = 1,
    ["Crusader"] = 1,
    ["Mage"] = 1,
    ["Scout"] = 1,
    ["Sorcerer"] = 1,
    ["Spellsword"] = 1,
    ["Warrior"] = 1,
    ["Witchhunter"] = 1,
    ["Commoner"] = 1,
    ["Farmer"] = 1,
    ["Guild Guide"] = 1,
    ["Herder"] = 1,
    ["Hunter"] = 1,
    ["Mabrigash"] = 1,
    ["Master-at-Arms"] = 1,
    ["Miner"] = 1,
    ["Ordinator"] = 1,
    ["Ordinator Guard"] = 1,
    ["Smith"] = 1,
    ["Warlock"] = 1,
    ["Witch"] = 1,
    ["Assassin"] = 0.5,
    ["Barbarian"] = 0.5,
    ["Monk"] = 0.5,
    ["Nightblade"] = 0.5,
    ["Champion"] = 0.5,
    ["Dreamer"] = 0.5,
    ["Enforcer"] = 0.5,
    ["Necromancer"] = 0.5,
    ["Sharpshooter"] = 0.5,
    ["Slave"] = 0.5,
    ["Smuggler"] = 0.5,
    ["Thief"] = 0.5,
}

this.proTopics = {
    "Orders",
    "chores",
    "jobs",
    "duties",
    "Advancement",
    "Requirements",
    "work",
    "business",
    "rules",
    "writ",
}

return this