----	OMW patch to duplicate MWSE interop environment
local I = require("openmw.interfaces")
local function include()	return I.SSQN		end
local tes3 = { event={} }	local event = { register = function(_, fn)	fn()	end }
----	end patch


local ssqn = include("SSQN.interop") --Must come before function calls

local function init()
    if (ssqn) then
    	ssqn.registerQIcon("PC_m1_AFP01","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP02","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP03","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP04","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP05","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP06","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP07","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP08","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP09","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP10","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP11","\\Icons\\pc\\q\\PC_m1_AFP.dds")
    	ssqn.registerQIcon("PC_m1_AFP12","\\Icons\\pc\\q\\PC_m1_AFP.dds")
	ssqn.registerQIcon("PC_m1_Anv_Bounty","\\Icons\\pc\\q\\PC_m1_Bounty.dds")	
	ssqn.registerQIcon("PC_m1_Anv_Goldenrod","\\Icons\\pc\\q\\PC_m1_K1.dds")
    	ssqn.registerQIcon("PC_m1_Anv","\\Icons\\pc\\q\\PC_m1_Anv.dds")
    	ssqn.registerQIcon("PC_m1_Arc","\\Icons\\pc\\q\\PC_m1_Arc.dds")
    	ssqn.registerQIcon("PC_m1_BC","\\Icons\\pc\\q\\PC_m1_BC.dds")
    	ssqn.registerQIcon("PC_m1_Cha","\\Icons\\pc\\q\\PC_m1_Cha.dds")
    	ssqn.registerQIcon("PC_m1_DM","\\Icons\\pc\\q\\PC_m1_DM.dds")
    	ssqn.registerQIcon("PC_m1_FG","\\Icons\\pc\\q\\PC_m1_FG.dds")
    	ssqn.registerQIcon("PC_m1_Gld","\\Icons\\pc\\q\\PC_m1_Gld.dds")
    	ssqn.registerQIcon("PC_m1_IP","\\Icons\\pc\\q\\PC_m1_IP.dds")
    	ssqn.registerQIcon("PC_m1_K1","\\Icons\\pc\\q\\PC_m1_K1.dds")
    	ssqn.registerQIcon("PC_m1_MG","\\Icons\\pc\\q\\PC_m1_MG.dds")
    	ssqn.registerQIcon("PC_m1_Mrv","\\Icons\\pc\\q\\PC_m1_Mrv.dds")
    	ssqn.registerQIcon("PC_m1_SC","\\Icons\\pc\\q\\PC_m1_SC.dds")
	ssqn.registerQIcon("PC_m1_SC_Bounty","\\Icons\\pc\\q\\PC_m1_Bounty.dds")
    	ssqn.registerQIcon("PC_m1_Sdk","\\Icons\\pc\\q\\PC_m1_Sdk.dds")
    	ssqn.registerQIcon("PC_m1_TG","\\Icons\\pc\\q\\PC_m1_TG.dds")
    	ssqn.registerQIcon("PC_m1_Tvy","\\Icons\\pc\\q\\PC_m1_Tvy.dds")

        -- Add commands to block a journal ID from showing banner notifications
	
	ssqn.blockQBanner("PC_m1_Anv_AdvReadB")
	ssqn.blockQBanner("PC_m1_Anv_BookClubA")
	ssqn.blockQBanner("PC_m1_Anv_BookClubB")		
	ssqn.blockQBanner("PC_m1_Anv_BookClubG")
	ssqn.blockQBanner("PC_m1_Anv_BookClubM")
	ssqn.blockQBanner("PC_m1_Anv_GoldenrodBR")
        ssqn.blockQBanner("PC_m1_Anv_GoldenrodDR")
        ssqn.blockQBanner("PC_m1_Anv_GoldenrodEH")
        ssqn.blockQBanner("PC_m1_Anv_GoldenrodLI")
        ssqn.blockQBanner("PC_m1_Anv_GoldenrodPA")
        ssqn.blockQBanner("PC_m1_Anv_GoldenrodSM")
        ssqn.blockQBanner("PC_m1_Anv_GoldenrodST")
	ssqn.blockQBanner("PC_m1_Anv_NakedNardGloves")
	ssqn.blockQBanner("PC_m1_Anv_NakedNardHat")
	ssqn.blockQBanner("PC_m1_Anv_NakedNardPants")
	ssqn.blockQBanner("PC_m1_Anv_NakedNardShirt")	
	ssqn.blockQBanner("PC_m1_Anv_NakedNardShoes")
	ssqn.blockQBanner("PC_m1_Anv_OceanBlueDate")
	ssqn.blockQBanner("PC_m1_Anv_OceanBlueFood")
	ssqn.blockQBanner("PC_m1_Anv_OceanBlueRoute")
	ssqn.blockQBanner("PC_m1_Anv_OceanBlueShip")
	ssqn.blockQBanner("PC_m1_Anv_TakingTaxKra")
	ssqn.blockQBanner("PC_m1_Anv_TakingTaxSle")
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcFG")	
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcFish")	
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcIAS")	
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcKarrel")
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcNavy")	
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcRG")	
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcSmith")
	ssqn.blockQBanner("PC_m1_Anv_WorkOrcSW")
	ssqn.blockQBanner("PC_m1_BC_MurdCrossBrescius")
	ssqn.blockQBanner("PC_m1_BC_MurdCrossGosha")
	ssqn.blockQBanner("PC_m1_BC_MurdCrossMedina")
	ssqn.blockQBanner("PC_m1_BC_MurdCrossRamus")
	ssqn.blockQBanner("PC_m1_BC_MurdCrossWound")
	ssqn.blockQBanner("PC_m1_BC_WomPetriLegion")
	ssqn.blockQBanner("PC_m1_BC_WomPetriLetter")
        ssqn.blockQBanner("PC_m1_IP_HY4A")
        ssqn.blockQBanner("PC_m1_IP_HY4D")
        ssqn.blockQBanner("PC_m1_IP_HY4K")			
        ssqn.blockQBanner("PC_m1_IP_Run1BU")
        ssqn.blockQBanner("PC_m1_IP_Run1CA")
        ssqn.blockQBanner("PC_m1_IP_Run1CC")
        ssqn.blockQBanner("PC_m1_IP_Run1JV")
        ssqn.blockQBanner("PC_m1_IP_Run1LA")
        ssqn.blockQBanner("PC_m1_IP_Run1LE")
        ssqn.blockQBanner("PC_m1_IP_Run1LV")
        ssqn.blockQBanner("PC_m1_IP_Run1OS")
        ssqn.blockQBanner("PC_m1_IP_Run1OT")
        ssqn.blockQBanner("PC_m1_IP_Run1PS")
        ssqn.blockQBanner("PC_m1_IP_Run1TE")
        ssqn.blockQBanner("PC_m1_IP_Run1TH")
        ssqn.blockQBanner("PC_m1_IP_Run1TT")
        ssqn.blockQBanner("PC_m1_IP_Run1UO")
        ssqn.blockQBanner("PC_m1_IP_Run1VA")
        ssqn.blockQBanner("PC_m1_IP_Run2UO")
        ssqn.blockQBanner("PC_m1_K1_MC6H")
        ssqn.blockQBanner("PC_m1_K1_MC6L")
        ssqn.blockQBanner("PC_m1_K1_MC6M")
        ssqn.blockQBanner("PC_m1_K1_MC6S")
        ssqn.blockQBanner("PC_m1_K1_MC6V")
        ssqn.blockQBanner("PC_m1_K1_MC7T")
        ssqn.blockQBanner("PC_m1_K1_MC8S")
        ssqn.blockQBanner("PC_m1_K1_RP3B")
        ssqn.blockQBanner("PC_m1_MG_Anv1B")
        ssqn.blockQBanner("PC_m1_TG_Anv4B")
        ssqn.blockQBanner("PC_m1_TG_Anv6C")
        ssqn.blockQBanner("PC_m1_TG_Anv6M")
        ssqn.blockQBanner("PC_m1_TG_Anv6V")
        ssqn.blockQBanner("PC_m1_Tvy_NobleDebt1")
        ssqn.blockQBanner("PC_m1_Tvy_NobleDebt2")
        ssqn.blockQBanner("PC_m1_Tvy_NobleDebt3")



    end
end

event.register(tes3.event.initialized, init)


