return {
    "(black01-1)",
    "(black01-1s)",
    "(black01-2)",
    "(black02)",
    "(black02-1)",
    "(black02-1s)",
    "(black02-2)",
    "(black02-3)",
    "(black02-4)",
    "(black02-s)",
    "(black03-1)",
    "(black03-1s)",
    "(black04-2)",
    "(black04-2s)",
    "(brown01)",
    "(brown01-1)",
    "(brown01-2)",
    "(brown01-s)",
    "(brown02)",
    "(brown02-1)",
    "(brown02-2)",
    "(brown02-3)",
    "(brown02-s)",
    "(brown03-1)",
    "(helmet)",
    "(left ear)",
    "(no cloak)",
    "(opened ears)",
    "(red01-1)",
    "(red01-1s)",
    "(red01-2)",
    "(red02-1)",
    "(red02-4)",
    "(red02-s)",
    "(red03-1)",
    "(red04-1)",
    "(right ear)",
    "(shirt)",
    "(white01-1)",
    "(white01-2)",
    "(white02)",
    "(white02-1)",
    "(white02-3)",
    "(white03-1)",
    "armiger",
    "armored",
    "ashlander",
    "battlemage",
    "black",
    "black&gold&red",
    "black&green",
    "black&red",
    "blue",
    "brocade",
    "brown",
    "bug",
    "buoyant",
    "cataphract",
    "copper",
    "dres",
    "dunmer noble",
    "elven",
    "filippa's",
    "gold & teal",
    "golden",
    "green",
    "green&brown",
    "hlaalu",
    "imp.",
    "lavender",
    "leather&brocade",
    "legion's",
    "light",
    "mabrigash",
    "mithril",
    "nightblade",
    "of azura",
    "of boethiah",
    "of dres",
    "of hlaalu",
    "of imp. agent",
    "of indoril",
    "of mephala",
    "of redoran",
    "of telvanni",
    "of the 6th house",
    "of the temple",
    "olive",
    "orc",
    "order of doctrine",
    "order of inquisition",
    "pink",
    "purple",
    "rebel",
    "red",
    "reinforced",
    "silk",
    "silver",
    "simple",
    "small",
    "spellsword",
    "teal",
    "telvanni",
    "temple",
    "twin",
    "vvardenfell",
    "with diamond",
    "with diamonds",
    "with emerald",
    "with emeralds",
    "with gems",
    "with green stone",
    "with moonstone",
    "with pearl",
    "with pearls",
    "with red stone",
    "with rubies",
    "with ruby",
    "with saphire",
    "with sapphires",
    "with topaz",
    "yellow",
}